### ISSUE TITLE
Typo at Lab: Miniflow

### ISSUE THREAD

**Issue by bpinaya** [udacity/sdc-issue-reports#1]
In:
Requirements
This lab requires Python 3.5 and the following Python libraries installed:

Juypyter  <--- THIS IS THE TYPO, Jupyter

**Comment by MaximeLeclerc** [comment]
Same typo in the Traffic Sign Classifier Project

**Comment by Brok-Bucholtz** [comment]
@bpinaya 

This has been fixed!  Thanks for letting us know.
