### ISSUE TITLE
Possible typo in Playing with Networks in Lesson 6

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#10]
In Warming Up 3 It says "After about 500,000 iterations ..." Should this be 500 iterations. Likewise in Building a Classifier 3 it says "Click the blue Run button to train the network for 500,000 iterations" Should this also be 500 iterations?

**Comment by Brok-Bucholtz** [comment]
@rm51 

Thanks for giving us feedback!  We changed this to 500 iterations.
