### ISSUE TITLE
Slip Angle formula

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1000]
As pointed out by another student in [this forum post](https://discussions.udacity.com/t/slip-angle-formula/338254) - In [Term 2: Lesson 18, Part 10 "Dynamic Models - Slip Angle"](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/f1820894-8322-4bb3-81aa-b26b3c6dcbaf/lessons/af4fcd4f-eb1f-43d8-82b3-17bb1e71695f/concepts/e6511d73-cda0-4ee9-b94b-c0ccd02439ef) the audio says the slip angle is "the arctangent of the wheel longitudinal velocity divided by the wheel lateral velocity". Meanwhile the video display shows the formula with the velocities swapped: `alpha = arctan(wheel lateral velocity / wheel longitudinal velocity)`. The formula is correct and the audio needs to be corrected.

**Comment by baumanab** [comment]
Thank you for reporting this.  A note has been added below the video.
