### ISSUE TITLE
T3 L22 Your Virtual Machine - VM missing

### ISSUE THREAD

**Issue by Valtgun** [udacity/sdc-issue-reports#1001]
Link to compressed VM disk image does not work:
https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/Ubuntu+64-bit+Udacity+VM+V1.0.0.ova.zip

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BDC7138A54681777</RequestId>
<HostId>
s1cASB5OGVVOHv4gG880ECzN5l1P/qhlNdya0kh3WkgLkg6h0Ln5OC0lZROOHwFuo68IA7cna80=
</HostId>
</Error>

**Comment by baumanab** [comment]
Thanks for letting us know.  This was resolving on Monday during testing, I'm not sure why it isn't now, but we are working on it.

**Comment by baumanab** [comment]
The link is now resolving.
