### ISSUE TITLE
Term 1, Behavioral cloning, deprecated Keras example

### ISSUE THREAD

**Issue by shmulik-willinger** [udacity/sdc-issue-reports#1002]
on the Behavioral cloning project, part 17 - Generators.
function 'model.fit_generator()' in the example is not correct any more and gets exceptions.
The new implementation should be: 
model.fit_generator(train_generator, steps_per_epoch= len(train_samples), 
    validation_data=validation_generator, validation_steps=len(validation_samples), epochs=5, verbose = 1)

**Comment by baumanab** [comment]
Thank you for reporting this.  A note has been added to the code.
