### ISSUE TITLE
T3 L22 Your Virtual Machine - VM archive corrupt

### ISSUE THREAD

**Issue by Valtgun** [udacity/sdc-issue-reports#1003]
Access is not resolved, but now when downloading there is different filename than in lectures and also MD5 hash is different. Archive is corrupted.
ubuntu+64-bit+udacity+vm+v1.0.0.ova.zip
MD5: 5d58d7203f2dff38cb8bd90d9cd6f142

**Comment by baumanab** [comment]
Thanks for reporting this.  We are currently looking into it.

**Comment by swwelch** [comment]
Hi @Valtgun, sorry, the checksum was wrong (left over from a previous version of the simulator). It should be fixed now.
