### ISSUE TITLE
I am unable to see the Hybrid A* introductino video

### ISSUE THREAD

**Issue by Michael-Jing** [udacity/sdc-issue-reports#1004]
I am unable to see the Hybrid A* introduction video box, the video region is empty.
os: Ubuntu 16.04
browser: google-chrome and firefox

**Comment by baumanab** [comment]
Sorry for the technical issues.  This may have been local or intermittent.  I am able to see this in my student account using chrome and firefox.  Would you mind checking again?

**Comment by Michael-Jing** [comment]
Sorry, but the issue remains, and I am also unable to see the path planning project walkthrough video. By using developer tools in google-chrome, I see the following errors: Failed to load resource: https://s3.cn-north-1.amazonaws.com.cn/u-vid-hd/NuurQejBk0o.mp4 the server responded with a status of 403 (Forbidden).  Hope this can help you resolve the issue.

**Comment by baumanab** [comment]
This may be a separate issue.  I'm not sure about the linked file.  However, the walkthrough can be viewed here: https://www.youtube.com/watch?v=3QP3hJHm4WM&feature=youtu.be

Please let us know if you are not able to view this.
