### ISSUE TITLE
T3 Semantic Segmentation - 2. Project Page: Typo

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#1009]
In the line before the 'Start' section (section 3):

>Download the Kitti Road dataset from here. Extract the dataset in the data folder. This will create the folder data_road with all the training **a** test images.

-> 
>Download the Kitti Road dataset from here. Extract the dataset in the data folder. This will create the folder data_road with all the training **and** test images.

**Comment by baumanab** [comment]
Thank you, this has been corrected.
