### ISSUE TITLE
Term1: Vehicle Detection: HOG Sub-sampling: Error in formula

### ISSUE THREAD

**Issue by john-chan-k7** [udacity/sdc-issue-reports#1010]
Error in formula

**Comment by john-chan-k7** [comment]
I think there is an error in the script in lesson
Project: Vehicle Detection and Tracking: 35. Hog Sub-sampling Window Search

The value 1 needs to be added to nxsteps and nysteps so that the sampling covers the entire search region.

Original:
nxsteps = (nxblocks - nblocks_per_window) // cells_per_step
nysteps = (nyblocks - nblocks_per_window) // cells_per_step

Search region is from y:400-528 (128px). All values of x is used.

DEBUG: ch1.shape: (128, 1280)
DEBUG: box y:448-512 x:1200-1264

ch1 width is 1280, but right-most box extends only to x = 1264
1280-1264=16px, or 2 cells short)

ch1 height is 128, but bottom box extends only to 512
Search region in image starts at 400.
512-400 = 112. This is 128-112 = 16px or 2 cells short)

Correction:
nxsteps = (nxblocks - nblocks_per_window) // cells_per_step + 1 # added: + 1
nysteps = (nyblocks - nblocks_per_window) // cells_per_step + 1 # added: + 1

DEBUG: ch1.shape: (128, 1280)
DEBUG: box y:464-528 x:1216-1280

[udacity_carnd_term1_hog_error.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5927f9a4424ada5407a09f42/125516c66e82c728ace21e0d46fd909b208b97b0b0eabe51aa59cf802c542a22160cac2c4f80f13ab050394d4d1f0cf31b0d0c00eef39b2eaeb6357283540dbed0650b70c26f11acb88219bd02e821995397f4edd4189fb5646fb2c99d452c1d041288fa5d36a39c4bcf5eff43e54d47e9.txt)

**Comment by baumanab** [comment]
Good catch, the content has been updated.
