### ISSUE TITLE
Buggy Countdown to due date in classroom

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#1011]
I've noticed that my countdown (XX days) for my project cards in the website UI are not updating and are simply wrong.  For instance, it's August 22 today, and it's saying that there are 28 days until my September 4th project deadline.  I've noticed this issue only in Term 3.

**Comment by ksmith6** [comment]
![Screen Shot 2017-08-22 at 8.14.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59658bdd8bab8b001fc2d986/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f16b7191a370f1132f4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee5d1645d7dce3b42adb0d61bbb53ba208b4f83b4bfd84dd2f42f67b6d5db1063474f4dcbed5727a29f41c95df648e54854a5113665ee762431.png)

**Comment by baumanab** [comment]
Thanks for reporting this. The classroom experience team is looking into it.

**Comment by baumanab** [comment]
The classroom experience team was able to clarify that this is the intended behavior.  The days listed are the days between project due dates.  So there are 28 total days for this project.  This is not a countdown to the due date.  The days value will remain static unless due dates change.
