### ISSUE TITLE
All VGG layers need a 1x1 conv for the semantic segmentation project

### ISSUE THREAD

**Issue by hortovanyi** [udacity/sdc-issue-reports#1012]
Course material eludes that for FCN-8 the fully connected layers are replaced by 1x1 convs. However in Lesson 9, Skip Connections it does not have a 1x1 conv. Clarity is required to remove confusion for students to ensure 1x1 convs are applied also to skip layers.

**Comment by baumanab** [comment]
Thank you for reporting this.  The classroom and Github README have been updated to clarify aspects of the model and project.
