### ISSUE TITLE
Term1, Lesson 16, sec 27

### ISSUE THREAD

**Issue by aman-ahluwalia** [udacity/sdc-issue-reports#1013]
In the result video, the calculation of the entropy children is shown to have negative signs, which isn't correct, as its just a weighted average. Thought in the final step i.e. while subtracting from 1, the native sign hasn't been used which is correct.

**Comment by mvirgo** [comment]
This is actually from Sebastian's old Decision Trees lesson (starting around [here](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/3cd1d00f-ffb2-4030-bd33-ebc4b95c6740/concepts/a860a9b1-dfab-4d3d-9490-99e691050c49) in the V1 classroom), which is deprecated for V2 of SDC (the two-term version), so we'll pass for now.
