### ISSUE TITLE
Capstone camera configuration size

### ISSUE THREAD

**Issue by Valtgun** [udacity/sdc-issue-reports#1014]
There has been change in camera configuration file, changing it to the 800x600, howver image topic publishes resolution 2560x1280.

Possibly those changes should be rolled back? Because now starter code in ros/src/tl_detector/tl_detector.py takes size from configuration to use in pixel x,y calculation, which is passed to image processing function with different resolution.

https://github.com/udacity/CarND-Capstone/commit/b74f35e53678207fbadd7326905fdc99b276f3e1

**Comment by Valtgun** [comment]
Seems like redownloading simulator helper to resolve.

**Comment by baumanab** [comment]
Did redownloading the simulator resolve the issue?

**Comment by Valtgun** [comment]
Yes, resolution matches after reloading

**Comment by baumanab** [comment]
Would a note in the project be helpful?

**Comment by Valtgun** [comment]
It would be better to have visible versions on the download page and maybe message in slack when there is updates to already existing simulator or classroom pages (e.g. information on the submission page that now we need to test rosbags)

**Comment by baumanab** [comment]
It does look like simulator versions are now visible. 

https://github.com/udacity/self-driving-car-sim/releases

I'm not sure what the most effective way of announcing updates is, but I will discuss it with the team.
