### ISSUE TITLE
Capstone camera fx/fy

### ISSUE THREAD

**Issue by Valtgun** [udacity/sdc-issue-reports#1015]

**Comment by Valtgun** [comment]
Does capstone camera configuration contain the correct values for fx and fy (they are the same as with previous resolution)

**Comment by baumanab** [comment]
Would you mind elaborating on what is meant by "they are the same as with the previous resolution."  I think what is meant is that the resolution changed, per #1014 but the fx, fy did not change to match.  Is that correct?

**Comment by Valtgun** [comment]
Yes, you understood correctly. Asking because I have seen some solutions work with custom values for fx/fy, but with the standard ones people can not get it to work and choose custom calculations some even without those values.

**Comment by baumanab** [comment]
Thank you for clarifying.  I'll look into this.

**Comment by baumanab** [comment]
Has this been discussed on the forums?

**Comment by Valtgun** [comment]
Hello,

No, there has not been any discussions regarding this in slack.

**Comment by baumanab** [comment]
Hi @Valtgun ,

I've been looking into this and am starting to develop a better understanding.  I'm working towards clarifying this aspect of the project.  It would be really helpful to have more information regarding this statement:

>  I have seen some solutions work with custom values for fx/fy, but with the standard ones people can not get it to work and choose custom calculations some even without those values.

Where did you see these solutions and where did you learn about people not being able to get the project to work without custom calculations etc?  Seeing the impact of the res and focal length in the context how it impacts project completion will be very helpful in resolving the issue.

**Comment by baumanab** [comment]
I found the forum thread where this is discussed.  We are actively working on a resolution.

**Comment by ckirksey3** [comment]
Since there is not a good way to represent the focal length of our virtual camera in Unity, we've removed this value from the configuration.
