### ISSUE TITLE
Capstone - speed limit not published

### ISSUE THREAD

**Issue by Valtgun** [udacity/sdc-issue-reports#1016]
In the slack there are discussions that for submission speed should be limited to 10 mph. Can you please add this information to submission page.

**Comment by baumanab** [comment]
Thanks for bringing this to our attention.  I'll get confirmation on this and then note.

**Comment by baumanab** [comment]
Which capstone is this for?

**Comment by Valtgun** [comment]
CarND

**Comment by baumanab** [comment]
Sorry, I should have been more clear.  I thought there were multiple capstones (1 per elective).  Is that not the case?  Would you mind linking to the capstone?

**Comment by Valtgun** [comment]
Hello,

This was for final system-integration team project.

**Comment by baumanab** [comment]
A note has been added to the submission page.
