### ISSUE TITLE
T2 10.25 - Entropy statement

### ISSUE THREAD

**Issue by gnekut** [udacity/sdc-issue-reports#1017]
Statements 1 and 2 contradict each other. Statement 1 is incorrect.

Statement 1: The video mentions that entropy will go down after the update step and that entropy will go up after the measurement step.

Statement 2: In general, entropy measures the amount of uncertainty. Since the update step increases uncertainty, then entropy should increase. The measurement step decreases uncertainty, so entropy should decrease.

**Comment by baumanab** [comment]
Yes, these are definitely conflicting statements, thanks for letting us know.

**Comment by baumanab** [comment]
The text has been updated to align with the video.  The issue was that measurement, update, and movement were conflated.
