### ISSUE TITLE
Functional Safety - Lesson #13, Slide #2 - Terminology

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1023]
Incorrect terminology used, inconsistent with ISO 26262.

Functional safety concept requirements --> should be functional safety requirements.

Technical safety concept requirements --> should be technical safety requirements.

**Comment by Mandar-Pitale** [comment]
Agree with Karl

**Comment by baumanab** [comment]
We will be reviewing the module in the context of this comment and related comments.

**Comment by baumanab** [comment]
This has been changed.
