### ISSUE TITLE
Functional Safety - Lesson #13, Slide #2 - Safety Case

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1024]
What is described is not a full safety case nor is it an end-to-end safety case.  In fact, only about 15% of requirements to be in safety case for ISO 26262 are considered and it is only considering conceptual/design issues, nothing related to implementation, verification, validation, HW/SW integration, etc.

Should say that we are creating part of a safety case or work products to be part of a safety case in order to be technically correct.

**Comment by baumanab** [comment]
Thank you, this content has been updated.
