### ISSUE TITLE
Functional Safety - Lesson #14, Slide #1 - Poor phrasing

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1026]
Video @0:42 - "safe and functional" is bad phrasing as neither is addressed by functional safety.  The phrasing you are searching for is "functionally safe"

**Comment by baumanab** [comment]
Thank you feedback.  I do see your point here but it also seems like these two phrasings encode a similar set of information and meaning.

**Comment by karlgreb** [comment]
I see it as patently false and misleading.  The usage does not have the
same meaning in a functional safety context.

**Comment by baumanab** [comment]
A note has been added below the video.
