### ISSUE TITLE
Functional Safety - Lesson #14, Slide #2 - SOTIF vs. FuSa

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1027]
Video @0:15 - what is describe is not functional safety, but safety of the intended functionality (SOTIF).  Please review the definition of functional safety in ISO 26262-1.
"absence of unreasonable risk due to hazards caused by malfunctioning behavior of E/E systems"
Normal functionality is not in scope.

**Comment by baumanab** [comment]
Thank you for letting us know about this.  A note has been added to the classroom.
