### ISSUE TITLE
Estimated time values for the lessons/labs are gone

### ISSUE THREAD

**Issue by deanofthewebb** [udacity/sdc-issue-reports#103]
I've had students ask if they could refer to the estimate times (e.g. 5 Hours for the Mini-Flow Lab) after beginning the lesson. I remember seeing these values in a pop-up window that triggered on the first run of the lesson.

**Comment by MaximeLeclerc** [comment]
+1

**Comment by dhruvp** [comment]
Yup we can fix that. On it!

**Comment by dhruvp** [comment]
If you hit ">" at the end of a lesson you'll be able to see these still:

![image](https://cloud.githubusercontent.com/assets/2255690/20981757/b8cf5cc0-bc6a-11e6-9198-0b8f3b167bee.png)


Marking this as done as a result.
