### ISSUE TITLE
Functional Safety - Lesson #14, Slide #2 - Misleading statement

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1030]
"... IEC 61508, which covers general industrial functional safety"
Misleading statement.
IEC 61508 originated from industrial markets but has no content specific to industrial.  It was applied to auto before ISO 26262 exists.  Today it is a mother standard in the IEC/ISO basic safety publication which covers "general functional safety" for a dozen industries.

**Comment by baumanab** [comment]
Thank you for letting us know.  This has now been addressed.
