### ISSUE TITLE
Term 1 / 10 Keras / Lesson 6 Convolution in Keras

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#1031]
The solution is missing the border_mode parameter when adding Conv2D layer

with model.add(Convolution2D(32, 3, 3, input_shape=(32, 32, 3)))

Hint 2 in the text indicates it should be used but it's not present in the solution.

Student found this issue and posted in the forum about it.

**Comment by baumanab** [comment]
Thanks for pointing this out.  Since it isn't necessary, the hint has been removed to avoid confusion.
