### ISSUE TITLE
L14S4 - Bad Seat Belts Example

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1035]
Seat belts are claimed to be mechanical, but most now also include E/E components and would be functional safety relevant.  Need a better example to make the desired point.  May be able to clarify as "a mechanical seat belt system ..."

**Comment by karlgreb** [comment]
Sorry, this is related to the FuSa lessons if this wasn't already clear.

**Comment by baumanab** [comment]
Thank you for the feedback.  Text has been added to clarify.
