### ISSUE TITLE
FuSa - L14S4 Quiz

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1036]
Bad quiz answer.  ESC by definition includes yaw control, ABS, and TSC.  Not sure how it would be possible to implement ESC without also implementing ABS.  Quiz needs to be fixed.

**Comment by baumanab** [comment]
That does seem reasonable.  Is the following statement correct?

"In the USA, passenger vehicles are required to have electronic stability control but not anti-lock brakes."

**Comment by karlgreb** [comment]
I do not believe the statement is correct.
Looked a bit further.  Wikipedia article on anti-lock braking says under regulations it was made mandatory under same NHTS regulation that made ESC mandatory. 
 If you dig into the NHTSA site, this doc:  https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/esc_nprm.pdf which states:  "Currently, every vehicle that is equipped with ESC, is also equipped with ABS and traction control.  However, the agency believes that traction control is a convenience feature.  Accordingly, it is not required by this proposal."  Therefore by regulation ABS is required, as is ESC, but TC is not (but from practical point of view all three are implemented together).

**Comment by baumanab** [comment]
The quiz has been updated to reflect this information.
