### ISSUE TITLE
FuSa - L14S5 SOTIF vs. FuSa

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1037]
ML example is not related to FuSa because it addresses nominal performance.  The same ISO 26262 committee is working on a sister specification called ISO 21448, Safety of the Intended Function (SOTIF), to address concerns on nominal performance.  Needs to be updated in text to remove bad content or clarify.

**Comment by baumanab** [comment]
This is great to know, thank you.  The content has been clarified.
