### ISSUE TITLE
FuSa - L14S7 - Bad QM definition

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1038]
QM means "quality managed" not "quality management".  QM implies that development according to accepted quality principles is adequate to reduce risk.  This does not mean no additional action is needed as suggested here. Many products don't meet automotive quality and need significant work just to be classified as QM.

**Comment by baumanab** [comment]
Thank you for the feedback.  The content has been revised to reflect this definition.
