### ISSUE TITLE
FuSa - L14S7 - Bad Quiz

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1039]
HARAs are highly subjective and bad topics for a quiz as a result.  Any number of the responses could be acceptable with right argumentation.  

If such a quiz stays, it should give you some hints why the author thinks a response is wrong.  It shouldn't take an experienced practitioner 15 minutes to get the right answer by guessing.

**Comment by baumanab** [comment]
Is this in reference to this quiz?

https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/6dc3d743-2b0f-4ae6-97b7-e2ff866f17ef/lessons/d7a725c8-8376-4991-ae09-7b221043b6e8/concepts/18f30f1f-e1e7-4a6d-b8e0-af95668b9daf

**Comment by karlgreb** [comment]
This is lesson 14 slide 7, so it matches the title.  But, memory fails as
this has been several months since filed.
Trying to remember issue, main concern is that the correct answer is
arguably wrong and no rationale is provided why it is considered correct.
For example, D is considered almost highest risk, but this is a low risk
scenario in most HARAs (often used as a training example even) and C would
be higher risk.
There should be some rationale provided for the correct answer, or accept
multiple options as the correct answer.

**Comment by baumanab** [comment]
Ah, I think I see your point. The quiz may be conflating risk and impact. The answer seems to be ordered by severity of impact. If we consider probability of occurrence along with severity of impact, a different order may make sense. So, in the absence of a justification it’s not clear why the correct answer was chosen. Is that correct?

**Comment by karlgreb** [comment]
Correct. Some justification for the answer should be provided, or more
details to evaluate risk in the question.

I fell like the version I commented on was different though - I seem to
remember having to find the order of all four elements (not just given four
sequences to choose from) and this took a lot of time to figure out the
"right" answer.  Moving it to choose from one of four responses is better,
but still has some of the same issues.

**Comment by baumanab** [comment]
It looks like this has been updated to include the calculation of risk when choosing the correct response.  This is a severity * probability calculation.  The assignment of severity and probability are subjective but the quiz is designed to show students how to apply the formula to the values/situation given.
