### ISSUE TITLE
FuSa - L14S8 - Not aligned to ISO 26262

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1041]
Vehicle is an item in ISO 26262, not a system.  

Showing non-ISO v-models as start can only confuse the students.  Why not show the ISO V-model from start?

**Comment by baumanab** [comment]
This is a good point.  However, the concept does clarify the context of a system definition in the context of this concept and does appear fit to purpose.  We are may review this when we make some additional content changes but are going to keep it the same for now.
