### ISSUE TITLE
FuSa - L14S9 - Bad Safety Plan Definition

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1042]
Safety Plan as described is not consistent to what ISO 26262 says should be in the safety plan.  It may be that Elektrobit has their own tailoring, but students need to know ISO 26262 not what E-bit uses.  For example - item definition is a unique work product and is not part of safety plan per ISO 26262.

**Comment by Mandar-Pitale** [comment]
Agree with Karl

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
