### ISSUE TITLE
FuSa - L14S12 - Trolley problem not FuSa

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1047]
Note - trolley problem is SOTIF related as it is a nominal performance question.  It is not related to functional safety.  Otherwise good commentary.

**Comment by baumanab** [comment]
Thank you for all the comments and feedback. Do you work or have training in the field of functional safety?

**Comment by karlgreb** [comment]
I run safety engineering for NVIDIA.  Have been part of ISO 26262 standard working group for about nine years.  May have traded some emails from NVIDIA address a few months ago, but lost contact info.

**Comment by baumanab** [comment]
This is a good point regarding FUSA and SOTIF.  It seems in this case that Sebastian is illustrating the concept of trade-offs and how this relates to the practicality of autonomous vehicle safety, and is somewhat agnostic to how we label the problem scenario itself.
