### ISSUE TITLE
Bad link to Capstone Github Repo

### ISSUE THREAD

**Issue by ancabilloni** [udacity/sdc-issue-reports#1048]
On the Project: System Intergration/Programming a Self Driving Car section. The link the the project repo is bad. It leads to Page Not Found.

**Comment by baumanab** [comment]
This is resolving for me. https://github.com/udacity/CarND-Capstone

Would you mind double checking?  If it dies not resolve, would you mind pasting the link?

**Comment by ancabilloni** [comment]
Yes, the link you provided should be the correct link. But I mean the link being put in the `starter repo` at the `Programming a Self Driving Car` is not the same. Here is the link being there `https://github.com/udacity/CarND-System-Integration`

**Comment by baumanab** [comment]
Ah, thanks for clarifying. I'll take a look.

**Comment by baumanab** [comment]
My experience is that all links are resolving for the starter repo and the project repo.  Would you mind checking again?  Apologies if I am misunderstanding something.

**Comment by ancabilloni** [comment]
![selection_091](https://user-images.githubusercontent.com/23693651/30127602-e3bac1de-930d-11e7-9cd8-20498469c820.png)

I refreshed my browser again and the same link is still there. It's in the `starter repo` in the image in attached.

**Comment by baumanab** [comment]
Thank you.  That is the link I checked.  The link is resolving for me rather than returning a Page Not Found.  Is this returning a Page Not Found for you?  It could be since my account may have different permissions.  Would you mind checking while I check under a different account?

**Comment by baumanab** [comment]
ah, it is returning page not found under my other account.  Thanks for pointing this out.  I'll work on fixing this and update later.

**Comment by ancabilloni** [comment]
Yes. Thanks for going through the trouble.

**Comment by baumanab** [comment]
The original link (the one that did not resolve) was leftover from beta testing and is outdated.  The link now points to the current project repo.  https://github.com/udacity/CarND-Capstone
