### ISSUE TITLE
Cannot talk to mentor without checking in

### ISSUE THREAD

**Issue by mxbi** [udacity/sdc-issue-reports#105]
When there is a check-in due during the next week, there is no way to send messages to or view the messages received from your mentor. The message box is obstructed by the Check-in button.

You should be able to skip the checkin temporarily to talk to your mentor

**Comment by rm51** [comment]
Also one mentee is unable to complete the checkin and so can't talk to me anymore. So I have been talking to her in slack.

**Comment by dhruvp** [comment]
I believe this should be fixed now. Please reopen this if this is still an issue!
