### ISSUE TITLE
Term 2 simulator: "zoom in" doesn't work

### ISSUE THREAD

**Issue by KenOverholt** [udacity/sdc-issue-reports#1050]
I have Windows 8.1 and am using the Windows term 2 simulator version 1.45.  The Zoom In button doesn't work.  I can Zoom Out but In.

**Comment by KenOverholt** [comment]
Upon further experimentation, I have found that a part of each button is clickable and part is not.  A little less than half of the left portion of the left button responds to a click while the other portion does not.  A little less than half of the right portion of the right button responds while the rest does not.

**Comment by baumanab** [comment]
This is what I found when I investigated this issue. Thanks for verifying.

**Comment by KenOverholt** [comment]
Why was this closed?  The whole button should work as a button.  As it is, it is misleading and was very frustrating until I figured out it doesn't work as a regular button does.

**Comment by baumanab** [comment]
Hi, sorry for any confusion. The issue was closed since zoom does work. You raise a good point though. Please feel free to open a new issue, otherwise I will open a new issue by EBD tomorrow.

**Comment by baumanab** [comment]
This is now a ticket in our internal system

For Udacity reference:
https://udacity.atlassian.net/browse/DRIVE-4118
