### ISSUE TITLE
Add Red Line To Diagram

### ISSUE THREAD

**Issue by wfs** [udacity/sdc-issue-reports#1051]
Additional red line needed from Camera to Free Space Detection - T3.L21.V4.

Links
* https://carnd.slack.com/files/U38KLN4QL/F6XJERBHS/selection_999_2309_.png

* https://carnd.slack.com/archives/C2J6AVC5V/p1504728945000178?thread_ts=1504417653.000031&cid=C2J6AVC5V

**Comment by baumanab** [comment]
Thank you for the figure. I have added it below the video, along with a note.
