### ISSUE TITLE
FuSa - L15S1 - Wrong Safety Plan Contents

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1053]
Safety Culture, Safety Lifecycle, Development Interface Agreements, and Confirmation Measures are not part of the work product called "safety plan" according to ISO 26262.  

These are important elements, but they are not part of a safety plan per ISO 26262's definition.  They are separate work products.

It looks like E-bit has tailored there process to include multiple work products under the banner of "safety plan".  This is allowed per ISO 26262, but is a bad approach to teaching ISO 26262 and functional safety.

Please correct with a safety plan as defined in ISO 26262.

**Comment by baumanab** [comment]
Thank you, this has been clarified in the classroom.
