### ISSUE TITLE
FuSa - L15S1 - Wrong definition of audit vs. assessment

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1054]
"The audits check if the project followed the steps outlined in the standard and if the decisions made actually make the vehicle safer"

An audit in ISO 26262 only addresses process - the first part of the sentence.  It does not determine if safety is achieved.  A safety assessment is defined as separate from audit and evaluates whether appropriate safety is achieved.

**Comment by baumanab** [comment]
Thank you, the content has been edited.
