### ISSUE TITLE
FuSa - L15S2 - Links to standards

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1055]
ISO/TS 16949 was replaced by IATF 16949 in 2016 - http://www.aiag.org/quality/iatf16949/iatf-16949-2016

Also, ISO 9001 link could be better made to ISO instead of wikipedia for consistency to other standards references:  https://www.iso.org/standard/62085.html

**Comment by baumanab** [comment]
The content has been updated to reflect this information.
