### ISSUE TITLE
FuSa - L15S3 - Need better example of Tailoring

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1057]
The example given in the video is a typical case of tailoring according to ISO 26262 - it is more an example of performing an impact analysis per ISO/DIS 26262-2:2018; 6.5.1.  

It would be better to go through all the cases where tailoring might be applied - e.g. -2; 6.4.5.2 - 6.4.5.8

**Comment by baumanab** [comment]
This is a good point and something we may consider.  Going through all the cases is out of our current scope for these lessons.
