### ISSUE TITLE
FuSa - L15S4 - Roles

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1059]
Roles defined go beyond what ISO 26262 states.  ISO 26262 does not define safety engineer, safety auditor, safety assessor, or test manager roles. Only program manger and safety manager are defined.  What is provided may be one company's view, but it is not required by standard nor is it a universal view.  Many companies have a structure which is very different to this.

Recommend to note that only program manager and safety manager are defined by ISO, but state the other roles as one possible implementation.

**Comment by baumanab** [comment]
A note has been added to the classroom.
