### ISSUE TITLE
FuSa - L15S6 - Bad definitions

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1062]
Confirmation review, functional safety audit, and functional safety assessment definitions as provided are in contradiction with the definitions of same terms in ISO 26262-1.

Also, levels of independence is poorly explained.  Should show the difference between I0 - I4 levels of independence and which work products actually require confirmation reviews - it is only a small number in overall safety case.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
