### ISSUE TITLE
FuSa - L15S7 - Bad Lesson Reference

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1063]
Item definition references lesson #3 - should be updated to match term 3 lesson numbering.

**Comment by baumanab** [comment]
I can see where this could be confusing.  Lesson numbering is relative to the module.  The next lesson is the third lesson in the functional safety module.  This way if a new lesson is added to another module the numbering relative that module remains the same.  To clarify I've replaced the lesson number with the lesson title.
