### ISSUE TITLE
FuSa -L16S2 - Hierarchy of elements

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1064]
For enhancement - could be noted that the allocation of elements to the ISO hierachy is not always so simple and there is room for interpretation.  For example, a graphics card is not a hardware part to someone developing the components which are on board the graphics card.  

This is an area where there is always a lot of confusion, so it would be good to state that these examples are not absolute.

Also would be good to introduce hardware sub-parts and elementary sub-parts as lower than hardware part as this is coming in latest standard revision.

**Comment by baumanab** [comment]
Thank you, this has been clarified in the classroom.
