### ISSUE TITLE
FuSa - L16 - Enhancement

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1065]
Would be good to reference SAE J2980 as it provides extensive examples and further recommendations on how to perform hazard and risk assessment.  This is used by many expert practitioners - no need to define your own keywords and procedures where SAE has recommended guidance.

**Comment by baumanab** [comment]
Thank you for this suggestion.  Where would be the best place in L16 to place this reference?

**Comment by karlgreb** [comment]
I would introduce it before slide #6 - situational analysis.  Slide #6 uses
a lot of terms that are non-standard as guidewords and these are not in ISO
26262.  It would be better to use guidewords aligned to examples in the ISO
26262.  Also as the project uses the same non-standard guidewords they
should also be replaced.  Basically if you replace them starting in slide
#6, you need to continue throughout the rest of the slides in this section
for consistency.

**Comment by baumanab** [comment]
Thank you, SAE J2980 has been referenced.
