### ISSUE TITLE
FuSa - L16 - HARA Enhancement

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1067]
The description is missing a very important point - HARA is subjective and you will often find two different groups will define different values based on their view of severity, occurrence, and exposure.  

This often also has geographical or cultural bias.  For example in Japan headlights are not considered safety critical as majority of driving is urban and lower speeds; those considering driving in Germany on the autobahn will have a different view. It's also often joked that the horn is safety critical in India...

**Comment by baumanab** [comment]
Thank you for a great example of the subjectivity of HARA.  A note has been added to the classroom.
