### ISSUE TITLE
FuSa - L16S9 - False Statements

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1069]
Fault Tree analysis is not mandatory for ASIL C and ASIL D.  Deductive analysis (of which FTA is one type) is highly recommended for ASIL C and ASIL D.

ASIL D does not required a hardware failure rate of <10 faults per billion hours of operation.  ASIL D suggests a target for the PMHF metric of < 10 dangerous, undetected failures per billion hours of operation, but other targets are acceptable provided appropriate justification.

MC/DC coverage is not mandatory for ASIL D - it is highly recommended in conjunction with other methods.

These blatantly false statements in contradiction with ISO 26262 need to be corrected ASAP.

**Comment by baumanab** [comment]
Thank you, this has been updated.
