### ISSUE TITLE
Typo in Lesson

### ISSUE THREAD

**Issue by VjunetXuuftofi** [udacity/sdc-issue-reports#107]
Actually, not really a typo.
On [this page](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/db18966a-23fa-4810-80b3-9ef1670f2d63), you can see the following: "Applying Equation (something - the one about changing weights and biases)". It looks like somebody forgot to change out this placeholder (definitely something I would do!)

**Comment by giladgressel** [comment]
<img width="893" alt="screen shot 2016-11-04 at 10 59 44 pm" src="https://cloud.githubusercontent.com/assets/6275366/20028034/1295eb08-a2e3-11e6-8aca-bca9ff2ca273.png">

**Comment by dhruvp** [comment]
Thank you both for the catch! Checking it now.

**Comment by dhruvp** [comment]
Now fixed. Thank you!
