### ISSUE TITLE
FuSa - L16S10 - Safety Goal Bad Example

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1070]
Very poor example of safety goal definition - in what world is vibration critical enough to generate an ASIL C risk?  This is on par with an engine stalling a very high speed or your steering being stuck full lock at high speed! 
 This should be QM or ASIL A at best.

**Comment by baumanab** [comment]
yes, a vibrational warning does not seem to constitute ASIL B or C level risk.  I've updated the quiz.
