### ISSUE TITLE
FuSa - L17S1 - Video Issue

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1071]
Video shows allocating functional safety  requirements to elements of a system architectural design.  This is in violation of ISO 26262.  At this stage in the ISO process there is only a concept of functionality, there are no specific system designs yet.  System design does not come into play until we are looking at implementation level - the technical safety concept.  

Video needs to be remade to be consistent to ISO 26262.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
