### ISSUE TITLE
FuSa - L17, L18, L19 - Requirements not meeting ISO 26262

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1074]
Example requirements are not written respecting ISO 26262-8 's rules on how to write requirements.  Content on how to write requirements should be introduced and all example requirements should be reworked to be in compliance to ISO 26262 rules.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
