### ISSUE TITLE
Matrix math problems in L6: Linear Transform

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#108]
See the discussion here:
https://carnd-udacity.atlassian.net/wiki/display/CAR/questions/10324202/miniflow-lesson-6-section-8-linear-transform

Is it possible the math is incorrect? The weights matrix should have n x k values (k output nodes, with each needing a weight for each of n input nodes).

**Comment by domluna** [comment]
Hi @gilcarmel, thanks for the issue! I added to a comment to your question in the discussion.

The math is correct, the wording leaves a bit to be desired though. I'm working a better explanation to that section. Particularly the "n inputs and k outputs" part from what I see is the source of a lot of the confusion.

**Comment by domluna** [comment]
@gilcarmel there's a new version of Linear Transform up.

I'm going to close this issue in favour of #119.
