### ISSUE TITLE
FuSa - L17S7 - Video QM wrong

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1080]
It is impossible to decompose a safety requirement into a safety requirement and a non-safety relevant requirement.  Multiple false statements in the video based on authors lack of understanding of what QM means.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
