### ISSUE TITLE
FuSa - L18S3 - Bad definition of Latent Fault

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1088]
Definition of latent fault provided is not aligned to ISO 26262.  An ISO 26262 latent fault is 
"multiple-point fault (3.96) whose presence is not detected by a safety mechanism (3.141) nor perceived by the driver within the multiple-point fault detection time interval (3.97)"

**Comment by baumanab** [comment]
This more rigorous definition has been added to the classroom.
