### ISSUE TITLE
FuSa - LDW example flawed

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1092]
LDW shakes steering wheels with a vibration motor.  This is not done by actuating the steering motors, as this would be wildly dangerous.

**Comment by baumanab** [comment]
Thank you for reporting this.  It does appear the lane departure warning and lane keeping assistance may be conflated in this unit.  The essential concepts taught seem constant and not impacted by this.  As a result, no changes are being made for now.

**Comment by baumanab** [comment]
Note that some changes were made to other slides to separate the vibrational feedback from lane keeping assistance torque.
