### ISSUE TITLE
FuSa - L19S1 - What about SEooC?

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1094]
What has been described is "in-context' development, which is the least likely option from a business standpoint as it requires custom development of all hardware and software based on system requirements.  ISO 26262's most commonly used approach is "Safety Element out of Context", which considers using standard safety hardware and software components to address functional safety implementation.  This topic really needs to be covered for the viewer to understand how the standard is applied in real world.

**Comment by baumanab** [comment]
Thank you for this tip, a note and resource have been added to the classroom.
