### ISSUE TITLE
FuSa - L19S3 - Bad SPFM Example

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1099]
SPFM is the percentage of faults which are safe or dangerous but detected as compared to the overall population of faults.  

An SPFM of 99% does not mean 99% of faults are covered by a safety mechanism.

**Comment by baumanab** [comment]
Would you mind sharing a reference for this?  The definition here http://www.arteris.com/blog/top-35-iso-26262-acronyms-and-abbreviations seems consistent with the current content.

**Comment by karlgreb** [comment]
You should never be using a 3rd party blog to try to define something which
is defined in an international standard.  Start with the source material.
The SPFM is defined in ISO/DIS 26262-5; 2018; C.2.

The example in the lesson says this is only based on faults detected.  This
is false because it neglects the impact of safe faults.

[image: Inline image 1]

**Comment by baumanab** [comment]
I see your point. How should this read then? That is, what is the meaning of an SPFM of 99%?

**Comment by karlgreb** [comment]
99% SPFM means that 99% of single point faults are either detected or safe
for a specific safety goal.

**Comment by baumanab** [comment]
Thank you, this has been updated.
