### ISSUE TITLE
Build your own Tensor Flow.ipynb TODO: lego picture

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#11]
In the exercise: Train a neural net on MNIST with SGD there is a TODO: lego picture

**Comment by rm51** [comment]
There are also other TODOS scattered through out the files but it looks like very been done but haven't been removed such as # TODO: what's the gradient?

**Comment by Brok-Bucholtz** [comment]
@rm51 

This has been fixed in the newest version of Miniflow.  Thanks for letting us know!
