### ISSUE TITLE
FuSa - L19S3 - Bad perceived multi-point fault example

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1101]
Example state a perceived multi-point fault is seen by driver noticing a light - but warning lamps will only come on if a fault is detected, which would instead make this a detected multiple point fault.  

A better example would be that the driver detects his brakes are not braking with full performance, or that he turns on the headlights and they do not shine.

**Comment by baumanab** [comment]
That makes sense.  The example has been updated.
