### ISSUE TITLE
FuSa -L19S4 - SW Tools Odd placement

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1103]
Bad positioning of the content on evaluation of software tools.  This is not relevant just for SW dev - it is relevant for any SW tools used for item, system, hw, or sw development.

This really should be back earlier in overall safety management, as it is addressed in safety planning stage though is not part of the safety plan.  It doesn't make sense in current position.

**Comment by baumanab** [comment]
I can see where this could git in the previous section. However, it does seem very relevant to the theme of this lesson.
