### ISSUE TITLE
FuSa - L19S13 - Egas not a SW Approach

### ISSUE THREAD

**Issue by karlgreb** [udacity/sdc-issue-reports#1105]
EGAS is a systems approach, not specifically a SW approach.  It is addressing not only SW issues but also faults in HW.  Would be better to discuss this in the TSC lesson, along with other common patterns like 1oo2, 2oo3, etc.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
