### ISSUE TITLE
Fusa-L19S9

### ISSUE THREAD

**Issue by Mandar-Pitale** [udacity/sdc-issue-reports#1108]

**Comment by Mandar-Pitale** [comment]
For solving deadlocks,  disabling OS interrupts, that would stop process preemption, is very inefficient and bad way . This will compromise the overall response time and latency of the system. 

Instead there is a feature that is provided by RTOS called priority ceiling  that helps.  
https://en.wikipedia.org/wiki/Priority_ceiling_protocol

**Comment by baumanab** [comment]
Thank you for letting us know about this.  A note has been added to the classroom.
