### ISSUE TITLE
FuSa-L19S8: FFI from Spatial Interference

### ISSUE THREAD

**Issue by Mandar-Pitale** [udacity/sdc-issue-reports#1109]
The video at 0.53 second show that the ASIL D software cab read the data from QM software, where as QM software cant write data to ASIL D software.

This is not quite correct as the meaning of both is the same, which is essentially, the data is produced by QM software and consumed by ASIL D software. Such accesses will indeed introduce the interference. 

This fact that ASIL D software can read from QM software only makes sense when there is a decomposition, otherwise not.

**Comment by Mandar-Pitale** [comment]
![FFI.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5883d1c760fcb12000f8b955/125516c66e82c728ace21e0d46ceb2b361cec1b99de6b546a749b2ce6b137f237056fa732686b270bb162f035f5f4eac475a5c16fdeb9539e4e76224d50152a7842f4d7ed43c16a6b9871fba02b222884885b3bd835e8d.JPG)

**Comment by baumanab** [comment]
Thank you for letting us know about this and for sharing your expertise.  We may update this in a future version of the specialization.  For now, it is out of scope for our content.
