### ISSUE TITLE
formatting typo in miniflow - sigmoid function

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#111]
I think you didn't format this correct.
"modify Sigmoid#forward"

**Comment by giladgressel** [comment]
<img width="1087" alt="screen shot 2016-11-05 at 3 36 19 pm" src="https://cloud.githubusercontent.com/assets/6275366/20034036/cab6cc68-a36d-11e6-8cc2-10a7f0c99561.png">

**Comment by domluna** [comment]
Thanks @giladgressel changed to:

2. Open miniflow.py. Modify the `forward` method of the `Sigmoid` class to reflect the sigmoid function's behavior.
