### ISSUE TITLE
quiz's right answer issue @  term2, lesson3, artical22

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1113]
find @
 term 2 "sensor fusion....",
 lesson 3 "Kalman filters", 
 article 22 "Quiz : Another Prediction"

correct answer @ <input id="radio-3" .... value=3...
considered to be wrong answer, while it is the correct answer

**Comment by baumanab** [comment]
Thanks for reaching out. In my classroom the answer in the video and the answer accepted by the grader, are aligned. The correct answer is the radio button corresponding to 3 horizontal and 2 vertical. Is that not the case in your classroom?

**Comment by anasmatic** [comment]
oh, today it is working fine ! ,
great, thank you very much.

**Comment by baumanab** [comment]
That is great to hear, thanks for letting me know.
