### ISSUE TITLE
Simulator Issue for Term2 Kidnapped Vehicle

### ISSUE THREAD

**Issue by AWDun** [udacity/sdc-issue-reports#1116]
https://discussions.udacity.com/t/error-running-particle-filter-with-simulator-any-help-please/277082/13?u=andydun

**Comment by baumanab** [comment]
Thank you fir reporting this. We will look into it. Would you mind helping me understand why this is thought to be a simulator issue? This wasn't clear to me from the forum thread.

**Comment by baumanab** [comment]
I investigated this and I don't think this is a simulator issue.   I could be mistaken and please let me know if this is the case.  Here is the synopsis.

1. cloned your repo, built, and ran.  map file would not load
2.  replaced main.cpp that came with your repo with main.cpp from the project repo, built, ran. map file loaded, car moved, particle did not move, weights were Average of NaN and highest is -1, quickly resulted in a segmentation fault.
3. replaced particle_filter.cpp from your repo with 2 different working implementations of the filter, each of these worked as expected
4.  built and ran again with the particle_filter.cpp from your repo, and had the same result as step 2.

I can tell you that I had something similar happen when I first worked on completing this project and it was my implementation in particle_filter.cpp.

**Comment by AWDun** [comment]
Hi Andrew, 

Yes, “map file not found” is because I was running the code from the Xcode debug folder, so I needed to change the directory in order to access the map file. 

The problem for me is that I was not able to see the implementation problem in the simulator at all! The error comes before any of the particle_filter.cpp runs! Like I had described in the forum post: I put a break point at the “pf.init” line in main.cpp, and the code doesn’t even get there, and breaks at the h.run() line with the "libc++abi.dylib: terminating with uncaught exception of type std::domain_error: type must be string, but is null” error. 

I KNOW that my implementation is not correct. That’s because I haven’t been able to properly test it without the simulator working. I wasn’t even able to see what the weights were, because the code breaks before it gets to particle.cpp, like I explained in the forum post. 

Andy

**Comment by baumanab** [comment]
Thank you for the additional information regarding the point of failure.  I will bring this to the attention of the lead for the simulator.  I'm still not completely convinced this is the simulator, but I could definitely be missing something.  I did the following:

- ran code and sim from fresh repo install, and observed the expected behavior.  The car drives around, the particle image does not move, weight values are nonsense (avg: NaN, weight -1). 
- ran code and sim with particle_filter.cpp from your repo and observed the behavior we have been discussing.
- repeated previous step except for this time I turned off the particle filter by setting initialize to false (from true), which restored the behavior of the first step.

This leads me to believe is the filter implementation that is causing the issue, since turning it off restores function.   Does this make sense or am I missing something?  Either way, I will bring this up with the lead for the simulator.

**Comment by AWDun** [comment]
Hi Andrew, 

Thanks for getting back so quickly. 

It seems that the code does not behave the same way on your computer. Did you see the same error that I did when running code from my repo? 

When I run the binary, it says: “Listening to port 4567”

When I open the simulator, it says: “Connected!!!”

When I load the kidnapped simulation, and hit “run”, it says: "libc++abi.dylib: terminating with uncaught exception of type std::domain_error: type must be string, but is null
Abort trap: 6”

If the error on the console that you see is not what I see, then you’re not seeing the simulator issue, and you’re probably seeing the errors from the incomplete/unfinished code in my repo. It seems that the same issue is not occurring on other platforms. I’m running macOS 10.12.6. I have been trying to run it on a linux VM. But it’s a pain to setup the uWs, cmake, etc, that it’s taking me some time.

Andy

**Comment by baumanab** [comment]
I hadn't considered the system differences.  I'll pass this information on.  To clarify, this is what happens with the code from the repo, without any added code?

**Comment by AWDun** [comment]
Yes, no changes in the code. 

Sorry I am still trying to setup everything on ubuntu virtual machine. Having trouble with the uWebsocket setup. But it seems like both you and the forum mentor did not encounter this problem once the code and simulator is running on a different platform.

**Comment by baumanab** [comment]
When I run the code from your repository I get the following error after a few seconds:

```./run.sh: line 9:   210 Segmentation fault      (core dumped) ./particle_filter```

**Comment by AWDun** [comment]
Andrew, 

This whole time, I was running the wrong simulation for this project. That’s why I got the error. Apologies for wasting your time.

Andy

**Comment by baumanab** [comment]
No worries, I'm glad it got worked out.

**Comment by daHeik** [comment]
@AWDun : That was my mistake, too. Thank god I found this discussion :)
