### ISSUE TITLE
SDC term 2, no subtitles in many videos

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1117]
------------------
lesson 5, 
section 5, 8,9,13 and so on , all is missing english subtitles。
lesson 21 is like above。

**Comment by baumanab** [comment]
Sorry for the difficulties, per comments on other posts, it does look like subtitles are working for these videos.  I'm not sure what is happening.  Please see my other comments and let's discuss.

**Comment by baumanab** [comment]
This looks like it may be a larger issue and not SDC specific.  Would you mind contacting support@udacity.com?
