### ISSUE TITLE
term 2 forum " doesn’t exist or is private"

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1118]
inside course side bar I got a link for forum,
I'm now @ term2 , but I can't access its forum via this link
https://discussions.udacity.com/c/nd013-term2-sensor-fusion
I even can't find term2 forum by search

**Comment by baumanab** [comment]
This is likely a permissions issue.  Please contact selfdrivingcar-support@udacity.com.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
