### ISSUE TITLE
typo in miniflow

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#112]
To do so, I'll the learning rate as η, the Greek letter eta.

**Comment by giladgressel** [comment]
<img width="823" alt="screen shot 2016-11-05 at 4 44 34 pm" src="https://cloud.githubusercontent.com/assets/6275366/20034340/74c6879e-a377-11e6-919f-6dd967f3f514.png">

**Comment by domluna** [comment]
@giladgressel thanks again! Fixed.
