### ISSUE TITLE
Ipopt minimum version incorrect

### ISSUE THREAD

**Issue by patrickmpoon** [udacity/sdc-issue-reports#1120]
The README for the MPC Project specifies a minimum version of 3.12.1, but I got the errors below.  Using version 3.12.7 as specified in the Dockerfile worked.

Errors:
$ sudo bash install_ipopt.sh Ipopt-3.12.1
Building Ipopt from /home/pato/Downloads/Ipopt-3.12.1
Saving headers and libraries to /usr/local
install_ipopt.sh: line 17: ./get.Blas: Permission denied
install_ipopt.sh: line 19: ../configure: Permission denied
make: *** No rule to make target 'install'.  Stop.
install_ipopt.sh: line 24: ./get.Lapack: Permission denied
install_ipopt.sh: line 26: ../configure: Permission denied
make: *** No rule to make target 'install'.  Stop.
install_ipopt.sh: line 32: ./get.ASL: Permission denied
install_ipopt.sh: line 36: ./get.Mumps: Permission denied
install_ipopt.sh: line 40: ./configure: Permission denied
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'test'.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by baumanab** [comment]
Thanks for pointing this out.  We are currently revising the Ipopt install instructions and will update with the correct version.

**Comment by baumanab** [comment]
This has been corrected.
