### ISSUE TITLE
Display trajectories in the path planning simulator

### ISSUE THREAD

**Issue by YuryBrodskiy** [udacity/sdc-issue-reports#1121]
Display various trajectories in the Path Planning simulator.Similar as it was possible in in the MPC project. 
Basically add a field in the control message which would contain one or more arrays of points in global coordinates that would be displayed on the road, possibly with a selected color. Overall effect should be similar to  Junior video

**Comment by baumanab** [comment]
This is a very good suggestion.  Unfortunately, we won't be able to address this in the near term.
