### ISSUE TITLE
System Integration Project: outdated wording

### ISSUE THREAD

**Issue by overtane** [udacity/sdc-issue-reports#1122]
In the lesson 4 it says: "The /base_waypoints topic repeatedly publishes a list of all waypoints for the track,..."
Meanwhile in slack: Stephen Welch [3 days ago] 
Hi @horto, I've responded in a PM, but it seems like those would be near the minimum. However, please see the latest commit to https://github.com/udacity/CarND-Capstone. We've changed the publishing of /base_waypoints to happen only once, which should be much more efficient.

**Comment by baumanab** [comment]
Thanks for reporting this.  The classroom content is now aligned with the referenced commit.
