### ISSUE TITLE
Term3 Project 2 - Advanced Deep Learning Safari Browser

### ISSUE THREAD

**Issue by shorton47** [udacity/sdc-issue-reports#1123]
In trying to run jupyter notebook on an AWS instance following the Medium post https://medium.com/@GalarnykMichael/aws-ec2-part-4-starting-a-jupyter-ipython-notebook-server-on-aws-549d87a55ba9  which was recommended for the project, I was unable to get Safari to work (couldnt connect to the kernel) but the Chrome Browser worked for me. I suggest updating the instructions for students to note that you must use Chrome browser if running the jupyter notebook. I will try to write an updated post on step by step when I get a chance

**Comment by baumanab** [comment]
Thanks for letting us know. Would you mind trying this with Safari?

1.	Start Jupyter: jupyter notebook --ip=0.0.0.0 --no-browser
	2.	Look at the output in the window, and find the line that looks like the following: undefined	1.	Copy and paste the complete URL into the address bar of a web browser (Firefox, Safari, Chrome, etc). Before navigating to the URL, replace 0.0.0.0 in the URL with the "IPv4 Public IP" address from the EC2 Dashboard. Press Enter.

**Comment by baumanab** [comment]
The part that says undefined is referring to the instance ip, the same value used to ssh in.

**Comment by baumanab** [comment]
I've updated the AWS GPU instructions to reflect a strategy that should work for safari.  Please see here and let us know how this works out.

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/f6fccba8-0009-4d05-9356-fae428b6efb4#

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
