### ISSUE TITLE
Lesson 23: Package & Catkin Workspace

### ISSUE THREAD

**Issue by ancabilloni** [udacity/sdc-issue-reports#1124]
Lecture mentioned to use `$ rosdep install -i simple_arm` to install missing dependencies in `simple_arm` package. But this didn't work in the VM well, I and another person faced the same issue that nothing was installed using this `rosdep`. Probably worth to note there that if it's the case, then apply normal installation with `sudo apt-get ros-kinetic-gazebo-ros-control` will get this required dependency installed.

**Comment by baumanab** [comment]
Thanks for letting us know.  A note has been added to the classroom.
