### ISSUE TITLE
SDC-term2 lesson7, section 22 has no subtitles.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1125]

**Comment by asimay** [comment]
please update quickly. and check all the term's video's subtitles. I think this problem handled too slowly. I submit other subtitles problem, but till now still un-resolved.  it is greatly impact non-english language nation student to study.

**Comment by baumanab** [comment]
HI @asimay , the subtitles videos are hosted by YouTube.  I'm wondering if there is a geographical restriction.  If you don't mind my asking, from which country are you viewing?

**Comment by asimay** [comment]
hi, dearAndrew:
I'm viewing from china. attachment is one of problem screenshot. please check. thanks.




At 2017-09-24 11:34:55, "Andrew Bauman" <notifications@github.com> wrote:


HI @asimay , the subtitles videos are hosted by YouTube. I'm wondering if there is a geographical restriction. If you don't mind my asking, from which country are you viewing?

**Comment by baumanab** [comment]
Thanks for the updates.  All the videos mentions in all posts regarding subtitles have English Subtitles when I view (student account) except for the one mentioned here.  For whatever reason 22 has Dutch subtitles.  In any case, I'm not sure what is going on.  I will bring this to the attention of someone at Udacity with more domain knowledge.

**Comment by baumanab** [comment]
English subtitles have now been added to 22.  I can see them on youtube and my Udacity student account.  If they still aren't showing up on your system it is likely a larger issue.  Please contact support@udacity.com.  Sorry for these subtitle issues, I'm sure it can be frustrating.  I'll keep trying to find an answer as well.

**Comment by asimay** [comment]
hi, there is still no subtitle in section 22.. I check it.
![Screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ab0d78ebf77720002221c3/125516c66e82c728ace21e0d46db978826878dba87e6ab01e81fe086264c22703d46f96925ddb371ed1b23570c5e46f8455c0d44fcf9892da4b56e71984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85b0b5894ec8ed3e26ef889d02.png)
