### ISSUE TITLE
SDC-Term 2 lesson 5, section 10 variable definitions

### ISSUE THREAD

**Issue by fjp** [udacity/sdc-issue-reports#1126]
Regarding the variable definitions in the mentioned lesson I think there is a mistake in the third point:

What does the prime notation in the x vector represent? The prime notation like p​x​′ means you have already done the **update** step but have not done the measurement step yet.

Instead of update it should be prediction because update an measurement are the same.

**Comment by baumanab** [comment]
Good point!  This has been corrected.
