### ISSUE TITLE
SDC-term2 lesson7, section 25 has no subtitles.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1127]

**Comment by asimay** [comment]
section 28 also has no subtitles. 
these section are so important but no subtitles.

**Comment by baumanab** [comment]
Thanks for reporting this.  Subtitles have been enabled and when I run this video is my student account I definitely have subtitles.  Are you certain subtitles are on?  Would you mind watching the video here:

https://www.youtube.com/watch?time_continue=45&v=qDX8nL_OT60

and making sure subtitles are on?  What happens?

**Comment by asimay** [comment]
yes. I'm sure there is no subtitles.

**Comment by asimay** [comment]
![22](https://user-images.githubusercontent.com/8703449/30779353-b845cd3e-a120-11e7-841c-5082dfffa0e6.png)

**Comment by asimay** [comment]
all the subtitles problems I reported are like above.

**Comment by asimay** [comment]
section 33 also has no subtitle

**Comment by baumanab** [comment]
This looks like it may be a larger issue and not SDC specific. Would you mind contacting support@udacity.com?
