### ISSUE TITLE
SDC-term 2. code bug

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1128]
SDC-term 2, lesson 7, section 27, code bug  in Predict Radar Measurement Assignment 2.
in ukf.cpp, in line 83, Zsig(1,i) = atan2(p_y,p_x);  
because phi is known, it is yaw = Xsig_pred(3,i);,
if I replaced atan2(p_y,p_x) with yaw, means Zsig(1,i) = yaw, it produced different answer. why? 
please check.

**Comment by baumanab** [comment]
This sounds interesting.  Would you mind clarifying the bug? I don't quite understand why this is a bug.

**Comment by asimay** [comment]
the output value is totally different.
the origin answer:
z_pred: 
 6.12155
0.245993
 2.10313
S: 
   0.0946171 -0.000139448   0.00407016
-0.000139448  0.000617548 -0.000770652
  0.00407016 -0.000770652    0.0180917

the new answer with 'yaw':
z_pred: 
 6.12155
0.536853
 2.10313
S: 
   0.0946171 -0.000999061   0.00407016
-0.000999061      0.01223  -0.00573716
  0.00407016  -0.00573716    0.0180917

**Comment by asimay** [comment]
the bug is: why the result are different ? from the meaning, it can replaced by 'yaw'.

**Comment by baumanab** [comment]
I think I have it.  So what it sounds like is that when phi is known Zsig(1,i) == atan2(p_y,p_x); == yaw, is that correct?  The issue is at hand is that substituting in yaw is yielding a different result than expected if the equality holds.  Is that correct?

**Comment by asimay** [comment]
yes. you are right.

**Comment by baumanab** [comment]
Thanks for confirming.  We will look into this.

**Comment by baumanab** [comment]
Would you mind pointing me to the source that says that yaw can replace phi, and under what circumstances?  I sent values to stdout, and they are not equivalent.
 
atan2(p_y,p_x) | yaw
0.244289	0.5367
0.23371	0.47338
0.273165	0.67809
0.246166	0.55455
0.248461	0.64364
0.244289	0.54337
0.245307	0.5367
0.244289	0.53851
0.257001	0.60017
0.216927	0.39546
0.244336	0.519
0.241934	0.42991
0.244289	0.530188
0.245157	0.5367
0.245239	0.535048

**Comment by asimay** [comment]
ok. can you explain what's the difference between  yaw and phi? it seems they are same, angle with x axis.

**Comment by baumanab** [comment]
This may be a better question for mentors, since they are likely closer to the material.  Would you mind asking on the forums?
