### ISSUE TITLE
Default Arguments Should be Immutable

### ISSUE THREAD

**Issue by karlobermeyer** [udacity/sdc-issue-reports#1129]
Fix functions defined with mutable default arguments by changing lists to tuples. See http://docs.python-guide.org/en/latest/writing/gotchas/

In Part 15 "Explore Color Spaces", A
```
def plot3d(pixels, colors_rgb,
    axis_labels=list("RGB"), axis_limits=[(0, 255), (0, 255), (0, 255)]):...
```
Part 32 "Sliding Window Implementation"
```
def slide_window(img, x_start_stop=[None, None], y_start_stop=[None, None],
    xy_window=(64, 64), xy_overlap=(0.5, 0.5)):
```

**Comment by baumanab** [comment]
Thanks for letting us know.  The code has been updated to align with best practices.
