### ISSUE TITLE
term 2, lesson 8, P2, description error.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1130]
in project of UKF, section 2, File Structure, the file description is still about EKF, not UKF. they should be changed.

**Comment by asimay** [comment]
example:  main.cpp - reads in data, calls a function to run the Kalman filter, calls a function to calculate RMSE

**Comment by baumanab** [comment]
Thanks for the feedback.  It does seem like these are accurate descriptions of the files for the UKF and EKF projects.  Is there something, in particular, that should be changed to enhance this description?

**Comment by asimay** [comment]
main.cpp - reads in data, calls a function to run the Kalman filter, calls a function to calculate RMSE

this main file is run unscented Kalman filter, it is easy confused with standard Kalman filter.

**Comment by baumanab** [comment]
The language has now been changed to be Unscented Kalman filter specific.
