### ISSUE TITLE
Term 1 setup instructions for Windows

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1131]
Hi, I am a forum mentor for SDCND. [One of the students pointed out](https://discussions.udacity.com/t/windows-10-install-with-docker-python-console-clueless/374548/6?u=subodh.malgonde) that the setup instructions say Windows users need to use Docker. However they can use Anaconda as well to setup their development environment. The Anaconda instructions, from the Udacity starter kit, are clearer and help is much more easier to find for Anaconda issues on the forum. I would request you to update the setup instructions.

**Comment by baumanab** [comment]
Thanks for letting us know. This was likely written when docker was the only viable option for tensorflow on most windows systems. Since then Anaconda has become a good option. I will update the instructions. To clarify, are the instructions in question under the "Installing Tensorflow" concept?

**Comment by baumanab** [comment]
Installation instructions have been updated.
