### ISSUE TITLE
Term 3, p2: Need details on pretrained model

### ISSUE THREAD

**Issue by subhash** [udacity/sdc-issue-reports#1133]
We have been provided with a pretrained model based on VGG for the semantic segmentation project. The original VGG model has been modified (Conv2D instead of FC etc) and has been pretrained. The details of the modifications would be very useful for future projects. It would help if we could have access to the actual tensorflow code that produced the saved-model.

**Comment by baumanab** [comment]
This could be very useful for future work, good point.  The best way to learn about all the operations is to print them out using the guidance in this concept.  https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/595f35e6-b940-400f-afb2-2015319aa640/lessons/b6de6f99-281f-44e8-a9df-196577204638/concepts/7eb14e8c-2418-4ee1-855e-5dc832fce738
