### ISSUE TITLE
Term 1, Lesson 8.9 - Typo

### ISSUE THREAD

**Issue by var7** [udacity/sdc-issue-reports#1134]
The output width would be W_out = (W−F+2P)/S+1.

The output height would be H_out = (H-F+2P)/S + 1.

The notation used is confusing  it would be clearer that the "+ 1" is not in the denominator (specially in W_out) with either math notation or use of brackets.

**Comment by baumanab** [comment]
Thanks for letting us know about this.  Brackets have been added.
