### ISSUE TITLE
lesson 8, P2, in section 3 project code,

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1135]
the description: 
EKF Versus UKF Repositories
The EKF and UKF repositories are similar, but they also have small differences.

In the EKF project, there was a separate KalmanFilter class for storing variables and calling the predict and update steps. In this project all of the Kalman filter code will go in the ukf.cpp file.

Another difference is that main.cpp will output NIS (recall that NIS is a metric that helps with parameter tuning). Here is the code from main.cpp that outputs NIS:

-------
above I didn't see any code in main.cpp. This is missing. please check.

**Comment by asimay** [comment]
because the UKF calculation is waste time, the NIS file ouput must consider thread output, if simply output into a file, the UKF efficiency and results will be greatly damaged.

**Comment by baumanab** [comment]
Thanks for reporting this.  There does indeed seem to be a disconnect between the project and the project instructions.  We will work to resolve this.  The project is correct as is.  The instructions are outdated, currently, the code blocks mentioned in the instructions but not in the starter code, should be coded by students.

**Comment by baumanab** [comment]
The instructions have been updated.  Please let us know if you find any other discrepancies.
