### ISSUE TITLE
Missing directory in project smartcab MLND

### ISSUE THREAD

**Issue by fabienmorgan** [udacity/sdc-issue-reports#1139]
I wanted to start the smartcab project in MLND and in the description it is stated that there is a description where it is stated that there are 3 directories called logs, images and smartcab. In the Github project there is only images and smartcab and when you run the smartcab.ipynb there are syntax errors because the log directory doens't exist

**Comment by baumanab** [comment]
Thank you for letting us know about this. This is the issues queue for SDCND.  Would you mind contacting machine-support@udacity.com?
