### ISSUE TITLE
Quiz: TensorFlow Linear Function says Quiz Solution in the quiz.py

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#114]

**Comment by rm51** [comment]
The Quiz.py has

# Quiz Solution 
# Note: You can't run code in this tab

**Comment by rm51** [comment]
Actually I was mistaken. When I hit reset it showed the correct comment at the top. I probably copied from the solution before to run it.

**Comment by Brok-Bucholtz** [comment]
@rm51 

This was an easy issue to fix :D  Thanks Renee!
