### ISSUE TITLE
term 2, lesson 11,

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1141]
the markov localization's content is very Obscured, not very clearly, not like other lessons, full of funny and clearly. can you please augmented the lesson content? thanks.

**Comment by baumanab** [comment]
Thank you for the feedback.  We have been actively working on improving this content.  Do you have any specific suggestions on what could be improved?

**Comment by baumanab** [comment]
Closing this out as not actionable without specific information.  Feedback is really helpful on this lesson.  Please feel free to open additional issues with specific feedback and/or requests.
