### ISSUE TITLE
Allow choosing starting car coordinates in Term 3 simulator

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#1142]
Debugging certain issues require the car to be at a specific point along the track. For instance, right before the `s` coordinate wraps around its maximum and returns to 0. However, it takes several minutes to drive around the track, which makes that debugging very slow. 

I would like to be able to direct the simulator to start with the car in a specific position along the circuit; ideally in Frenet coordinates, but it could also be in Cartesian coordinates `(x, y, yaw)`. It could be a command line parameter, or a parameter configurable in the starting screen (the one with the "SELECT" button).

**Comment by baumanab** [comment]
Thank you for the feedback.  This is a good suggestion for an enhancement.  Unfortunately, we won't be able to add this feature at this time.
