### ISSUE TITLE
Term 3 Path Planning Project wrap around bug

### ISSUE THREAD

**Issue by ThomasK42** [udacity/sdc-issue-reports#1143]

**Comment by ThomasK42** [comment]
When working on the Term 3 Path Planning Project I encountered an issue with the sensor fusion data during the wrap around at max_s. There seems to be a bug in the simulator V 1.2:  on the wrap around of s at max_s some cars suddenly can have s AND d both equal 0 - so a car that actually is in the right lane is suddenly detected in the left lane and the right lane is considered free with could (and did for me) lead to a collision that's hard to explain otherwise. I attached an excerpt from my log file containing the raw data send by the simulator. Please look at position (s) and displacement (d) for the car with id 11 - whose values both suddenly jump to zero for a number of iterations and then back to plausible values. Please investigate and fix that bug for other students (I used a work around to submit the project).
Regards,
Thomas Kloeker

[log_wrap_around_bug_sensor_fusion.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d271c065d59c00139638c5/125516c66e82c728ace21e0d46e49b9d1c9591a89fd6be51ab48fe90164432741617a625638af117b957680800015cb053181d1ba6acda6fb4bc2e75825c02efd8655927c73545a8bcd01fbf01ba26894cd7b7ae965e82b96371b8d6d6056b5c17129bfe543fa19c4bce51f04fe74c53ac163171ab.txt)

**Comment by baumanab** [comment]
Thanks for reporting this.  This has also been reported in the issues below.  We are currently investigating the issue and testing fixes.  I'm closing this one out as we pursue the threads below.

#1169, #985, #939
