### ISSUE TITLE
Warning for Term2 / CarND-MPC project

### ISSUE THREAD

**Issue by tmandzak** [udacity/sdc-issue-reports#1147]
Since Term2 / CarND-MPC project is sensitive to latency I would suggest placing a warning about using virtual machines. The same code running on MacOS and on Ubuntu VM under Windows led to completely different behaviors of the simulator for me.

**Comment by baumanab** [comment]
Thank you for letting us know about this.  I'm not sure how common this is, but a warning has been added in the tips section.
