### ISSUE TITLE
Package location for "iou_metric" is Incorrect

### ISSUE THREAD

**Issue by fallrisk** [udacity/sdc-issue-reports#1148]
Term 3 - Lesson 10 Scene Understanding - 6. IoU Quiz

In the paragraph with heading "TensorFlow IoU" the location of "mean_iou" says it is located at "tf.metric.mean_iou." This is incorrect the correct location is "tf.metrics.mean_iou."

**Comment by baumanab** [comment]
Thank you for letting us know.  This has been corrected.
