### ISSUE TITLE
Term2 MPC: there is a room for simplification

### ISSUE THREAD

**Issue by pkol** [udacity/sdc-issue-reports#1149]
Hi,
As you know solution to MPC problem is to transform it into finding a minimum of function and then solve using Ipopt. That’s great.

It took me a while to understand how udacity did it. The main problem for me was that state space was so huge. It contains 8 variables for each time step (x, y, psi, v, cte, epsi, delta, a). Six of them are “state” and last two “actuators”. To make it consistent “state” variables must be heavily constrained so they follow the model of car driven by “actuators”.

I could not understand why Ipopt is bothered with those six “state” variables. The only two we care about are a and delta. So I’ve made a version of the code that has state (x for Ipopt) stripped down. It contains only delta and a. Knowledge about car model was moved from constraints to method run_car_model(). I think it has several advantages over solution proposed by Udacity:

    It’s simpler and easier to understand.
    Smaller state space means faster run for Ipopt (it should at least).

My code is in https://github.com/pkol/CarND-MPC-Quizzes/blob/master/mpc_to_line/src/MPC.cpp

**Comment by baumanab** [comment]
This is very insightful and helpful.  Thank you!  I'll bring this up with the team.

**Comment by subodh-malgonde** [comment]
@baumanab See this discussion from the forum -[Simplyfied state in MPC](https://discussions.udacity.com/t/simplyfied-state-in-mpc/382849). @pkol has posted the project using this approach. Works very well.

**Comment by baumanab** [comment]
I'll take a look.  Thank you!

**Comment by baumanab** [comment]
I'm working through this project next week and will consider the simplification during that time.

**Comment by baumanab** [comment]
The project video is impressive. What do you recommend in terms of changes to the quiz and project scaffolding code?

**Comment by baumanab** [comment]
If you are willing to put in a pull request for alternative scaffolding, we can test it and consider incorporating changes. Please make the pull on a branch other than main and @baumanab

**Comment by pkol** [comment]
It could try to do this, unfortunately I will not have time for this in a few weeks.

**Comment by baumanab** [comment]
I'm looking forward to it.  I'm going to close this out in lieu of a pull request on the repo make sure to @ me or I may not see it.  If you don't hear something back within a couple of day of making the pull request, please @ me on this thread.
