### ISSUE TITLE
miniflow -- bad coding practice

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#115]
I noticed another weird thing. 

we see the following in the SGD nn.py

```
w = np.array([[random.random(), random.random()], [random.random(), random.random()]])
b = np.array([random.random(), random.random()])
```

in the spirit of good code demonstration / modeling. 

I think
```
w = np.random(2,2)
b = np.random(2)
```

would demonstrate good code practice.

**Comment by domluna** [comment]
@giladgressel thanks for the suggestion, the code was updated to use `np.random.rand`.
