### ISSUE TITLE
Term 2 Simulator Locale Issue

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1150]
Hi, I am a forum mentor. A [student observed](https://discussions.udacity.com/t/datasets-seem-to-be-missing-in-simulator-v1-45-ubuntu-16-04/373597/23?u=subodh.malgonde) that the Term 2 simulator works only for the US locale. Or to be more accurate it works with the US locale and does not work for some other locales. You might want to add a warning about this when the simulator starts.

**Comment by baumanab** [comment]
Wow, this certainly is an unusual problem, thanks for reporting it.  I've read over the linked thread and it does sound like it is a locale issue.  At the very least we can let people know about this so they don't waste time trying to figure it out.  I'll bring this up with the team and get back on a path forward.

**Comment by subodh-malgonde** [comment]
@baumanab Another student faced this issue. Check [this forum post](https://discussions.udacity.com/t/term-2-simulator-not-working-properly/446386/5?u=subodh.malgonde). Luckily he/she figured it out quickly.

**Comment by baumanab** [comment]
Until we have a fix in the simulator I'm thinking about making students aware of the issue and the workaround.  Considering that this potentially impacts every term 2 and 3 projects that uses the simulator,  where do you think would be the most effective place(s) to add a note?

**Comment by baumanab** [comment]
I’m thinking of linking or posting simulator issues on the simulator download page. That way everyone will have a one stop shop for updates, workarounds, etc.

**Comment by subodh-malgonde** [comment]
I think thats a good place to put the links/workarounds. Can't think of any other better place.

**Comment by baumanab** [comment]
Thanks for the feedback.  The primary developer of the simulator agrees.
I'm going to create a document for the term 2 and 3 simulators that covers
some elements of issue status and workarounds.

<https://www.avast.com/en-us/lp-safe-emailing-3176-b?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-3176-b>
Virus-free.
www.avast.com
<https://www.avast.com/en-us/lp-safe-emailing-3176-b?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-3176-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by baumanab** [comment]
I added information and workarounds into the release.  A ticket has been opened in our internal system, so I'm closing this out.

https://udacity.atlassian.net/browse/DRIVE-4384
