### ISSUE TITLE
Path Planning Project: install_ubuntu.sh problem

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1151]
Hi, I reported an [issue on the Path Planning Project repo](https://github.com/udacity/CarND-Path-Planning-Project/issues/3). There is a problem with the file `install_ubuntu.sh`. Although its unlikely that students who have finished term 2 would need to use this file again, it should nevertheless be fixed.

**Comment by baumanab** [comment]
Thanks for letting us know, this has been addressed.
