### ISSUE TITLE
Short survey language validates as email

### ISSUE THREAD

**Issue by BenjaminPelletier** [udacity/sdc-issue-reports#1152]
On the short survey sent to new enrollees today, question 12 is a free-response question about the user's preferred language, but it is validated (or not) as an email.

**Comment by BenjaminPelletier** [comment]
![LanguageIsAnEmail.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d6ed06e8e66d0011921d3e/125516c66e82c728ace21e0d46c49594249782ae8ac0ac62aa78fd95204a653f6b14b1247a80e03cfd183954575f47ae48505917fdf1dd2fa2e43c708a5c0defd23f5e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d22e58e88483e1d05118ced10.png)

**Comment by baumanab** [comment]
Thanks for letting us know.  This has now been reported.  I'll update here when it has been resolved.

**Comment by baumanab** [comment]
Closed as this has been reported to survey admins.
