### ISSUE TITLE
Term 2, Lesson 7 section 4, missing info for the quiz

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1153]

**Comment by anasmatic** [comment]
- not mentioned in class that velocity is constant, so I can't answer Question 2
- not enough description when you chose wrong or even correct answer in Question 3
- for question 4, if I find a right reason for Question 2 and 3 , I'd definitely answer 4 ..

**Comment by baumanab** [comment]
Thanks for reaching out about this.  I try to address each point below.  I hope this is helpful.  

- Constant velocity and yaw are mentioned [here](https://www.youtube.com/watch?v=hLVz0YOhntA&feature=youtu.be&t=12).  This is actually how the model gets its name, though that isn't obvious until you have some experience applying it.
- For question 3 this term is in the state vector given in the previous lesson and shown in the pre-quiz video.  The intent is that if a student looks at the state vector (per the hint given on selecting the incorrect answer), this term will jump out.
- Question 4 is related to question 2.  Constant Yaw Rate is an assumption of the model, as mentioned in the video link above.

Would you mind letting us know how we can clarify these items without directly giving the answer?  Sometimes quizzes are designed in such a way as to prompt students to think about and review some of the material, and we try not to be so direct that review becomes unnecessary.  Does that make sense?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
