### ISSUE TITLE
Term3 Object Detection conda command is wrong!

### ISSUE THREAD

**Issue by dm1299** [udacity/sdc-issue-reports#1154]
conda create env -f environment.yml
should be changed to
conda env create -f environment.yml

**Comment by baumanab** [comment]
Good catch!  The command has been updated.

**Comment by dm1299** [comment]
The command in the lesson need be updated too.
https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/595f35e6-b940-400f-afb2-2015319aa640/lessons/69fe4a9c-656e-46c8-bc32-aee9e60b8984/concepts/4ab7a82d-2280-4e44-8b75-9a88b82fa8bb

**Comment by baumanab** [comment]
Changed, thank you.
