### ISSUE TITLE
no graph here.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1155]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/b7e42c04-8d1b-4631-a3ba-e74d4122cd59

Particle (blue dot) in Map Frame (grey) and Particle (blue dot) in Vehicle Frame (orange), no graph here.

**Comment by asimay** [comment]
and no subtitle here. can you please send me the youtube's link? thanks.

**Comment by baumanab** [comment]
Hello, sorry for the technical issues.  This video has subtitles on my end (verified on YouTube).  Here is the link https://www.youtube.com/watch?v=BrQfVd4JXpg.  I'm wondering if there is either a system or locale issue.  In terms of the graphs, there should be some orange and grey axis below the titles.  Do you see those?

**Comment by asimay** [comment]
Thank you for your link. I can see subtitle auto generated by youtube there.

nothing in graph. screenshot as below.



![2](https://user-images.githubusercontent.com/8703449/31325955-40aa875c-acf5-11e7-83ad-f4d5315503e2.png)

**Comment by baumanab** [comment]
Hmm, what browser are you using?

**Comment by asimay** [comment]
google chrome. v61.0

**Comment by asimay** [comment]
with other browser, screenshot like this:

![qq1](https://user-images.githubusercontent.com/8703449/31326872-9b6cc6fc-acfd-11e7-8bc0-5692b7ca0a00.png)

**Comment by baumanab** [comment]
If you look in developer tools (ctrl + j) do you see any error messages?

**Comment by baumanab** [comment]
It sounds like this is a local issue. Please let us know if are able to get error messages from the console/developer tools so that we can investigate.
