### ISSUE TITLE
Term1 Lesson 4.19 should use numpy.outer

### ISSUE THREAD

**Issue by yangchunluo** [udacity/sdc-issue-reports#1158]

**Comment by yangchunluo** [comment]
based on my discussion:
https://discussions.udacity.com/t/why-not-using-numpy-outer-a-b/391405

--------------------------
Hi, the course material spend a paragraph explaining this in 4.19 Backpropagation:

Also, wij is a matrix now, so the right side of the assignment must have the same shape as the left side. Luckily, NumPy takes care of this for us. If you multiply a row vector array with a column vector array, it will multiply the first element in the column by each element in the row vector and set that as the first row in a new 2D array. This continues for each element in the column vector, so you get a 2D array that has shape (len(column_vector), len(row_vector)).

hidden_error*inputs[:,None]
array([[ -8.24195994e-04, -2.71771975e-04, 1.29713395e-03],
[ -2.87777394e-04, -9.48922722e-05, 4.52909055e-04],
[ 6.44605731e-04, 2.12553536e-04, -1.01449168e-03],
[ 0.00000000e+00, 0.00000000e+00, -0.00000000e+00],
[ 0.00000000e+00, 0.00000000e+00, -0.00000000e+00],
[ 0.00000000e+00, 0.00000000e+00, -0.00000000e+00]])

Well, the simplest solution is numpy.outer(inputs, hidden_error), isn’t it?

I tried on the quiz, np.outer works just fine and it is much cleaner, code wise and conceptually.

I would advise the course staff update the lesson material.

**Comment by baumanab** [comment]
Thank you for the suggestion.  The `.outer` method would definitely work, and it's a clever implementation.  The material is presented as is to encourage thinking about the data structures and basic linear algebra.  Once the more manual method is understood, it's great to use methods such as np.outer.  I hope that makes sense.
