### ISSUE TITLE
Creating too many conda environments

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#116]
Hey, I'm just noticing.
We are asked to make a new conda env for tensorflow intro, which installs ALL of anaconda.

then in the tensorflow lab, there is ANOTHER env made.

I think there should be a "all packages you need for the entire SDC term1 file," and we setup a single env for the entire course.

**Comment by domluna** [comment]
I completely agree here. It would make much more sense to have a single env for the term than a new env for every project. @Brok-Bucholtz thoughts?

**Comment by Brok-Bucholtz** [comment]
@domluna @giladgressel 

Using a single environment would make installation simpler and easier to manage, but limits us from sharing our content with other teams.  For example, Artificial Intelligence, Machine Learning, Data Analyst, and this course all share content.  Using a modularized lessons allows us to share more easily, which gives us more time to do bigger and better things!

**Comment by giladgressel** [comment]
@Brok-Bucholtz 
I really disagree with this.  You are putting the companies needs over the students.
By having instructions for multiple installations, you are also demonstrating bad practice software management.  
Additionally you are creating extra work for the students, so that Udacity can share it's install information easily?  
Thousands of students should do extra work because there isn't enough resource at udacity to make seperate installation readme files?  I'm sorry I can't believe that is the logic here.

Gilad

**Comment by Brok-Bucholtz** [comment]
@giladgressel 

There might be a misunderstanding here.  I thought we were discussing the use of different environments for each project.  Can you go into more detail about your solution?  It should help clear things up.

**Comment by domluna** [comment]
I think listing the requirements for a project is enough to make it modular in the sense that someone looking to adapt it to their lesson has a clear starting point. 

What I'm arguing for here is having the student do `source activate CarND-Term1` and it'll work for the whole term.

**Comment by giladgressel** [comment]
Ya, I'm agreeing with Domluna.  One environment for the entire term.

It doesn't make sense to have students make a new environment for each project.  This is not good practice, because the tools we are using are the same across the environment and everytime you create a new environment it re-downloads all the packages necessary. 

Also the instructions for the introduction to  tensorflow have you create an environment with the **entire** anaconda distribution.  This hundreds of MB of unnecessary bloat.

So my point is env's are cool, and I use them.  I want one for the entire term.  With one set of instructions for installing _all_ the software for the entire term.  This way I don't have multiple copies of the exact same software laying around.  HD space is actually an issue for me, and so is internet speed.  I get 3Mbp/s at home.  Redownloading anaconda for no reason was not a smart move for me.

On a separate note: (and I think I opened an issue for this as well)
Additionally this readme.md should be available prior to starting the coursework.  I had one student spend 3 days trying to get things figured out. Then P1 was still due in 4 days later.   There is no reason not to release this information before the cohort launches.

**Comment by domluna** [comment]
@giladgressel When you get the chance could you see if https://github.com/domluna/CarND-Term1-Starter-Kit works as is with some of the projects?

**Comment by giladgressel** [comment]
hey cool!
Yea I can check but only late tonight.  on windows machine for now at
work.  Can't mess with docker anymore (did that already)

**Comment by domluna** [comment]
Gonna close this since https://github.com/domluna/CarND-Term1-Starter-Kit has made good progress and further discussion is on slack anyway.
