### ISSUE TITLE
Capstone: dbw_test

### ISSUE THREAD

**Issue by ra9hur** [udacity/sdc-issue-reports#1160]
The comment in the dbw_test refers to rosbag file in styx/data folder,
"You can use this file to test your DBW code against a bag recorded with a reference implementation.
The bag can be found in styx/data folder."

Cannot find this file.

Also, need steps to use dbw_test.

**Comment by baumanab** [comment]
Would you mind linking the page or file that contains this comment?

**Comment by ra9hur** [comment]
Here is the link:
https://github.com/udacity/CarND-Capstone/blob/master/ros/src/twist_controller/dbw_test.py

**Comment by baumanab** [comment]
Thank you, the team is looking into this.

**Comment by baumanab** [comment]
The file is too large to add to the repo, but can be downloaded from this public link.  https://drive.google.com/open?id=0B2_h37bMVw3iT0ZEdlF4N01QbHc

The comments have been updated with the link.

**Comment by CodingCanuck** [comment]
Can you please further update the comments with usage instructions? For example:

"To use the downloaded bag file, rename it to 'dbw_test.rosbag.bag' and place it in the CarND-Capstone/data folder."

**Comment by asimay** [comment]
they didn't update it till now. I came across same issue now.

**Comment by baumanab** [comment]
Thanks for letting us know.  I made an additional update to clarify use of the file.
