### ISSUE TITLE
SDC Term 2 Lecture 3 section 25 code bug - Quiz: Kalman Matrices

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1161]
The for loop in the sample code in the Kalman Matrices quiz is wrong: the return statement is over-indented.

This starting code:
def kalman_filter(x, P):
	for n in range(len(measurements)):
	
		# measurement update
	
		# prediction
	
		return x, P

incorrectly returns on the first iteration of the loop. The return statement should instead be less indented, as follows:

def kalman_filter(x, P):
	for n in range(len(measurements)):
	
		# measurement update
	
		# prediction
	
	return x, P

Note that the return statement is now less indented, which causes the loop body to run O(n) times before returning rather than just running once.

**Comment by baumanab** [comment]
Good catch!  This has been corrected.
