### ISSUE TITLE
missing content in Intro to Self Driving Cars

### ISSUE THREAD

**Issue by rickh87** [udacity/sdc-issue-reports#1163]

**Comment by rickh87** [comment]
In Intro to Self Driving Cars, Bayesian Thinking, Lesson 11, there appears to be a lot of content missing.  The lesson immediately starts with 1. Project Overview and tells us to build a two dimensional histogram filter without discussing how to build a histogram filter.

**Comment by baumanab** [comment]
Thanks for reporting this.  This is actually the issues repository for SDC, rather than intro to SDC.  I have let the team know about this.

**Comment by olegleyz** [comment]
is there a waffle board for the iSDC?

**Comment by baumanab** [comment]
Yes, https://waffle.io/udacity/isdc_issues_tracker
