### ISSUE TITLE
Term 2 Lesson 11.15 video visuals are incorrect

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1165]
At 3:45 in the video for lesson 11.15 Markov Assumption for Motion Model: Explanation, a line is removed from the diagram showing that there is no dependency between xt and z1:t-1. This is fine and correct.

The lecturer also correctly says that there is no dependency between xt and u1:t-1, and says "we can remove both of these connections", but the video's diagram does not remove the line between xt and u1:t-1.

Should we add a note to the lesson saying that the dependency between xt and u1:t-1 should be removed due to the markov assumption?

**Comment by baumanab** [comment]
Great catch!  Yes, this line should be removed and I can see where its inclusion creates confusion.  I'll let the production team know about this.

**Comment by baumanab** [comment]
https://youtu.be/THv0DDbsNcc?t=225

![image](https://user-images.githubusercontent.com/4316306/31734380-60184296-b3f3-11e7-9d57-f8d8699d8736.png)

**Comment by CodingCanuck** [comment]
That screenshot perfectly captures the line that should be removed, thanks!

(A fixed video would be ideal, but failing that a note explaining the video error would help)

**Comment by baumanab** [comment]
related to #832 (832 closed to remove duplicates)

**Comment by baumanab** [comment]
A new version has now been uploaded.

**Comment by CodingCanuck** [comment]
It looks like the line between xt and u1:t-1 has been removed entirely from the video starting at 2:50.

This is incorrect: the line should be present when the diagram is first presented at 2:50, and it should be removed at the same time as the line between xt and z1:t-1 at 3:45. (When the speaker says "we can remove both of these connections" at 3:45, two lines should be removed simultaneously)

**Comment by baumanab** [comment]
I watched the videos so many times I was still seeing the line.  I put the previous video up while we work on the new one.

**Comment by baumanab** [comment]
The video has now been corrected.
