### ISSUE TITLE
Term3 - Path Planning project - NextWaypoint code issue

### ISSUE THREAD

**Issue by PhilippeW83440** [udacity/sdc-issue-reports#1169]
There are 2 issues in this function that are especially problematic at wraparound of s:

    closestWaypoint++ may end up being equal to maps_x.size() instead of 0
    Related to angle > pi/4: angle should be corrected to: angle = min(2*pi() - angle, angle);
    to account for cases where you have theta close to 2pi e.g. 2pi-epsilon and heading slightly positive e.g epsilon. Delta is below pi/4, and equal to 2 epsilon, but with the provided code it will reported as above pi/4.

I’ve pasted my code with corrections below:
int NextWaypoint(double x, double y, double theta, const vector<double> &maps_x, const vector<double> &maps_y)
{

	int closestWaypoint = ClosestWaypoint(x,y,maps_x,maps_y);

	double map_x = maps_x[closestWaypoint];
	double map_y = maps_y[closestWaypoint];

	double heading = atan2( (map_y-y),(map_x-x) );

	double angle = fabs(theta-heading);
	angle = min(2*pi() - angle, angle); // XXX bug fix

	if(angle > pi()/4)
	{
		closestWaypoint++;
    if (closestWaypoint == maps_x.size())
    {
      closestWaypoint = 0; // XXX bug fix
    }
	}

	return closestWaypoint;
}

**Comment by PhilippeW83440** [comment]
The prototype of the function is unchanged. Error in above copy/paste. Vector of double for maps_x and maps_y

**Comment by PhilippeW83440** [comment]
`int NextWaypoint(double x, double y, double theta, const vector<double> &maps_x, const vector<double> &maps_y)
{

	int closestWaypoint = ClosestWaypoint(x,y,maps_x,maps_y);

	double map_x = maps_x[closestWaypoint];
	double map_y = maps_y[closestWaypoint];

	double heading = atan2( (map_y-y),(map_x-x) );

	double angle = fabs(theta-heading);
	angle = min(2*pi() - angle, angle); // XXX bug fix

	if(angle > pi()/4)
	{
		closestWaypoint++;
    if (closestWaypoint == maps_x.size())
    {
      closestWaypoint = 0; // XXX bug fix
    }
	}

	return closestWaypoint;
}
`

**Comment by PhilippeW83440** [comment]
`int NextWaypoint(double x, double y, double theta, const vector<double> &maps_x, const vector<double> &maps_y)`

**Comment by baumanab** [comment]
This has been fixed.  Thank you for your help!
