### ISSUE TITLE
Missing parenthesis in term 2 lesson 14.12 Calculating Error (minor)

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1170]
In the "Instructor Notes" section of term 2 lesson 14.12 Calculating Error, this equation at the end of the second sentence (excuse the pasted formatting):
 = √ ​(x ​v ​​ −x ​w ​​ ) ​2 ​​ +(y ​v ​​ −y ​w ​2 ​​ ​ ​​​​ 
​
is missing a closing parenthesis.​​

**Comment by CodingCanuck** [comment]
And note the closing parenthesis should be before the final "2" (square).

**Comment by baumanab** [comment]
Thanks for letting us know.  This has been corrected.
