### ISSUE TITLE
Term 2 lesson 14.18 Quiz: Particle Weights grader lists wrong number of decimal places

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1171]
The 2.14.18 quiz says:
"Write your answer in scientific notation with an accuracy of two decimal places"

If you enter the wrong answer, the grader says:
"Remember to round to 3 decimal places"

The grader error should be fixed ("2" not "3") since the grader actually expects 2 decimal places.

**Comment by baumanab** [comment]
Thanks for reporting this.  This has now been corrected.
