### ISSUE TITLE
Cannot access the course material.

### ISSUE THREAD

**Issue by ibrahim-mo** [udacity/sdc-issue-reports#1172]

**Comment by ibrahim-mo** [comment]
I get empty screen for all of the course lectures. This just started last night, and still happening! I tried both Chrome and Safari, and I restarted my laptop. I am stuck and cannot continue, so please fix ASAP.

**Comment by ibrahim-mo** [comment]
![empty-screen.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aa49d0e70ae01a008c7166/125516c66e82c728ace21e0d46ed998a379bceba8cfbba46aa1fbcd6395428792c07b7692ac7b670ef1b295857591dad490c5b40aef9892ba6b03e73d85d19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8249c0e83e2ce48c8c462c53.jpeg)

**Comment by baumanab** [comment]
Sorry for the technical issues.  It looks like this is going on system-wide and the classroom experience team is actively working on a solution.

**Comment by baumanab** [comment]
It looks like the issue has now been resolved.  Please let us know if this is not the case for you.

**Comment by ibrahim-mo** [comment]
It works now. Thanks a lot!
