### ISSUE TITLE
Term 3, Behavior Planner, invalid cost function

### ISSUE THREAD

**Issue by overtane** [udacity/sdc-issue-reports#1173]
This is from Python 3 solution - others may have the same problem: `change_lane_cost()` should according to comments  "Penalize lane changes AWAY from the goal lane and rewards lane changes TOWARDS the goal lane." Variable `proposed_lanes` is a delta of goal lane and trajectory target lane. However, `cur_lanes` which is used in comparison is an absolute lane number. It also should be a delta (of the goal lane and current lane).

**Comment by swwelch** [comment]
Thanks - the quiz has been largely rewritten last week, so that should be fixed now.
