### ISSUE TITLE
term 2 , PID-Control-Project

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1175]
I think there is some problem of this project design.
because there is no time interval in code. how to fetch of diff_cte? no time element in it, just though of it as 1 second. this is something not reasonable.

**Comment by baumanab** [comment]
Thanks for the feedback. I’m not sure what is meant by no time interval. Would you mind elaborating?

**Comment by asimay** [comment]
ok. I mean in code, we calculate diff_cte = (new_cte - old_cte)/delt_t . there is no description said the delt_t  is 1 in simulation.  actually 1 is we practice python supposed value. I think in simulation delt_t is much smaller than 1. so this is unreasonable.

**Comment by asimay** [comment]
no time value passed to  h.onMessage interface.

**Comment by asimay** [comment]
and in simulator, what's the CTE value stand for is ambiguous. the CTE value obviously is not equal to robot.y value, there is no description about it.

**Comment by baumanab** [comment]
Thank you for the additional information.  CTE is he cross track error, as discussed in the classroom and the project instructions:

> The simulator will provide you the cross track error (CTE) and the velocity (mph) in order to compute the appropriate steering angle.

We don't need to calculate CTE for this project (we will in the MPC project).  Instead, this value will be passed by the simulator.  The main focus here is developing around the PID terms, and then tuning their values.  Does this help clear things up?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.

**Comment by asimay** [comment]
hi, dear, sorry for late.
yes, we don't need to calculate CTE, but we need to calculate diff_cte , right? so the delt_t in diff_cte is not defined here. it's confused. i think we need to describe it in document or readme. there is also no readme doc about the message and its unit.

**Comment by baumanab** [comment]
I don't recall doing this when I completed this project.  This might be a question best posed on the forums or to a classroom mentor.  Would you mind using one or both of those resources?
