### ISSUE TITLE
Term2, reference to Eigen library 

### ISSUE THREAD

**Issue by ricardo-jmnez** [udacity/sdc-issue-reports#1176]
In lesson 5.6 of Term2 on Kalman filter equations C++ Part 1, it would be appropriate to reference the website of the Eigen library: http://eigen.tuxfamily.org  or/and state if the provided library is  different.
Currently it reads "Just for reference here is a download link to the Eigen (link to cloudfront.net/something) Library that is being used throughout the programming assignments."

**Comment by baumanab** [comment]
Good point, the link has been added.
