### ISSUE TITLE
Deep learning & CNN modules very abstract and low on details about implementation

### ISSUE THREAD

**Issue by thomasantony** [udacity/sdc-issue-reports#118]
Posted here:
https://carnd-udacity.atlassian.net/wiki/questions/10325561/deep-learning-cnn-lectures-very-abstract-and-low-on-details

**Comment by Brok-Bucholtz** [comment]
@thomasantony 

As you're aware, we are currently working on this and will continue to iterate on the DNN and CNN content.  If there's a specific issue, please let use know.
