### ISSUE TITLE
Term 3 - 5.30 Polynomial Trajectory Generation Playground default graph doesn't match screenshot in instructions

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1180]
When I run the "python evaluate_ptg.py" command recommended in the Polynomial Trajectory Generation Playground lesson, I see a graph that's different than the screenshot in the lesson.

My default graph's y-axis starts at 0 (unlike -2 in the screenshot) and the x-axis ends at 40 (unlike 60 in the screenshot).

I'm not sure if the graph's content is also different. It looks like the path of the other vehicle is also truncated, but it's hard to tell with the different axes.

**Comment by CodingCanuck** [comment]
Here's what I see when I run the provided code:
![figure_1](https://user-images.githubusercontent.com/19922103/32137383-918caa8c-bbd3-11e7-9938-d122f4884057.png)

vs. the screenshot provided in the lesson:
![figure_1](https://user-images.githubusercontent.com/19922103/32137389-afe182dc-bbd3-11e7-910d-baa6db4abfa6.png)

And the lesson instructions say "You should see a plot similar to the one" *before* recommending any code changes, implying that the graph screenshot should be what we start with and have to fix. But it looks like we're actually starting with something different.

**Comment by baumanab** [comment]
I think it may be axes settings.  Notice the differnec4 in axes in the two plots.  I ran the code on my system with no modifications, and here is what I get:

![image](https://user-images.githubusercontent.com/4316306/34322100-2c4598b0-e7d3-11e7-8d56-1a2b2134e61e.png)

**Comment by baumanab** [comment]
I'm going to close this out.  It may be worth taking this to the forums.  Please let us know if this doesn't resolve.
