### ISSUE TITLE
Term 3 - Path Planning Project readme and rubric disagree

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1181]
The readme located at https://github.com/udacity/CarND-Path-Planning-Project says the jerk limit is 50 m/s^3.

The project rubric https://review.udacity.com/#!/rubrics/1020/view says the jerk limit is 10 m/s^3.

One of these looks wrong :)

**Comment by baumanab** [comment]
The Readme has now been aligned with the rubric.  Thanks for catching this.
