### ISSUE TITLE
Term 2 ekf/ukf simulator not working unless system language is english, Ubuntu 16.04/17.10

### ISSUE THREAD

**Issue by Lede25** [udacity/sdc-issue-reports#1182]
When running the term2 ekf/ukf simulation while the system language is set to Finnish, the simulation won't start. This can be fixed by changing the system language to english.
![screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f5eec4a469a80012b65a3b/125516c66e82c728ace21e0d46fb978826878dba87e6ab01e81fe086264c22703d46f96925ddb371ed1b23570c5e46f8455c0d44fcf9892da4b56e71984019af80330b2b9b645bf9fa9015ad00bc2a8a4a85bfbe8245c9ed3c23e38c9d02.png) When the system language is finnish, the simulator just stays in the state that can be seen in the attached screenshot, pressing the buttons won't do anything. 

I noticed this behaviour in virtualbox with fresh 16.04 and 17.10 installations as well with my main system with 16.04. Changing the language to english fixed the issue. If I recall correctly, other simulations can be started, but not these ekf/ukf. No other than Finnish and English language were tested and I don't know what causes this behaviour.

**Comment by Lede25** [comment]
When running the term2 ekf/ukf simulation while the system language is set to Finnish, the simulation won't start. This can be fixed by changing the system language to english.
![screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f5eec4a469a80012b65a3b/125516c66e82c728ace21e0d46fb978826878dba87e6ab01e81fe086264c22703d46f96925ddb371ed1b23570c5e46f8455c0d44fcf9892da4b56e71984019af80330b2b9b645bf9fa9015ad00bc2a8a4a85bfbe8245c9ed3c23e38c9d02.png) When the system language is finnish, the simulator just stays in the state that can be seen in the attached screenshot, pressing the buttons won't do anything. 

I noticed this behaviour in virtualbox with fresh 16.04 and 17.10 installations as well with my main system with 16.04. Changing the language to english fixed the issue. If I recall correctly, other simulations can be started, but not these ekf/ukf. No other than Finnish and English language were tested and I don't know what causes this behaviour.

**Comment by baumanab** [comment]
related to #1150

**Comment by baumanab** [comment]
Thank you for reporting this.  This is now an issue in our internal system.  See #1150 for more detail.
