### ISSUE TITLE
Term 3, Lesson 9.5 quiz gives "Exception ignored" warnings

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1183]
A successful solution to the 3.9.5 quiz "1x1 Convolution Quiz" generates warnings like the following when running a correct solution that's accepted by the grader. Note that warnings are non-deterministic (they change from run to run, and sometimes to not appear).

Sample exception 1

Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f40dbf8c9b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 581, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
Dense Output = [[[[ 0.          4.71697187]
   [ 0.14247303  0.        ]]

  [[ 0.          0.62908524]
   [ 0.09633976  0.        ]]]]
Conv 1x1 Output = [[[[ 0.          4.71697187]
   [ 0.14247303  0.        ]]

  [[ 0.          0.62908524]
   [ 0.09633976  0.        ]]]]
Same output? = True

Sample exception 2

Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f4630f8d9b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 581, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'
Dense Output = [[[[ 0.          3.50791883]
   [ 0.55261326  0.        ]]

  [[ 0.          0.18028064]
   [ 0.19599456  0.        ]]]]
Conv 1x1 Output = [[[[ 0.          3.50791883]
   [ 0.55261326  0.        ]]

  [[ 0.          0.18028064]
   [ 0.19599456  0.        ]]]]
Same output? = True

**Comment by CodingCanuck** [comment]
I also see this in other quizzes, such as 3.9.8 Transposed Convolution Quiz

Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f1d9a4700b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 581, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'
    
Input Shape: (1, 4, 4, 3)
Output Shape: (1, 4, 4, 8)

(although this is from an incorrect solution)

**Comment by baumanab** [comment]
This is likely due to deprecations/version mismatch.  Ultimately we will update the TF version running in the classroom. In the meantime, I'll see if we can suppress the warnings.

**Comment by baumanab** [comment]
Warnings have been suppressed.
