### ISSUE TITLE
Term 3 Lab 10.11 Object Detection lab has bad link to mobilenet image

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1184]
The Object Detection Lab at the end of the Scene Understanding lecture links to this lab on github:
https://github.com/udacity/CarND-Object-Detection-Lab

The notebook in that lab has a section (just under "Resolution Multiplier") that links to a "MobileNets Graphic" with this url which 404's:
https://github.com/tensorflow/models/raw/master/slim/nets/mobilenet_v1.png

The image URL should instead be:
https://github.com/tensorflow/models/raw/master/research/slim/nets/mobilenet_v1.png

When I change/fix the URL for this image in the notebook, the image appears.

**Comment by baumanab** [comment]
Thanks for reporting this, the link has been updated.
