### ISSUE TITLE
Term 3 lesson 11.4 instructions prevent SSH connections

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1185]
The "Interlude: Using The AMI" lesson of term 3's advanced deep learning elective includes a video that recommends setting the default security group.

The default security group, if unedited, doesn't allow SSH connections from external IPs. Instead the security group for the spot request has to be updated to allow SSH connections as per https://discussions.udacity.com/t/aws-ami-setup-operation-timed-out-error/349017/13 : if students don't do this, their ssh connections will mysteriously time out.

Can the AWI setup instructions be updated to mention changing the security group, or maybe link to this forum post?

It would also be good to link to the excellent set of written steps in https://discussions.udacity.com/t/how-to-run-semantic-segmentation-on-aws/352069/4 in the setup instructions.

**Comment by baumanab** [comment]
Yes, I think we can accommodate sharing this information.  Thank you.

**Comment by baumanab** [comment]
The information has been added.
