### ISSUE TITLE
Term 3 AMI udacity-carnd-advanced-deep-learning tensorflow library possibly incompatible with some AWS instances

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1186]
See https://discussions.udacity.com/t/illegal-instruction-when-importing-tensorflow/343894/7

I get an "Illegal Instruction" error when importing tensorflow on the AMI udacity-carnd-advanced-deep-learning:
$ python -c 'import tensorflow as tf'
Illegal instruction (core dumped)

The error goes away when re-installing tensorflow on the AWS instance:

$ pip install tensorflow-gpu

Is it possible that the pre-installed version of tensorflow on the AMI is compiled with some flags that enable instructions sets that aren't supported by all AWS instances (particularly g2.2xlarge)?

**Comment by CodingCanuck** [comment]
Having debugged this further, I suspect that this AMI's pre-installed version of tensorflow is built with something like --copt=-march=broadwell . If so, the tensorflow binary won't work on any of any of amazon's g2 instances, it'll require a g3 instance to run. More details: https://discussions.udacity.com/t/illegal-instruction-when-importing-tensorflow/343894/7

**Comment by baumanab** [comment]
I actually had this same issue on another AMI, and solved it the same way.  I had not idea why it occurred, so thanks for figuring that out.  I'm going to flag this for a ticket into our central task system, and in the meantime, I'll leave a note in the instructions.

**Comment by baumanab** [comment]
A note has been added to the term 3 AWS GPU instance concept.
