### ISSUE TITLE
Term 3 12.2 Semantic Segmentation Project Walkthrough code error

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1188]
In the walkthrough video for the semantic segmentation project for the advanced deep learning elective, the code written at 7:36 on line 36 is:
tf.save_model.loader.load(sess, [vgg_tag], vgg_tag)

but should be:
tf.save_model.loader.load(sess, [vgg_tag], vgg_path)

with the last argument being vgg_path instead of vgg_tag.

**Comment by baumanab** [comment]
Thank you, a note has been added below the video.
