### ISSUE TITLE
Kidnapped Vehicle Project - .gitignore issue

### ISSUE THREAD

**Issue by vishalrangras** [udacity/sdc-issue-reports#1189]
The .gitignore file of Kidnapped Vehicle Project has a reference to particle_filter.cpp because of which the file does not get committed if we clone this repo and work on it.

As a result, after project submission, the reviewer rejects it and then we have to resubmit after committing that file. Please correct this.

**Comment by baumanab** [comment]
I hadn’t noticed this. I can see where this could become confusing. The ignore is only for a top level file. If particle_filter.cpp is in the src directory, it will commit. Would you mind giving that a try?

**Comment by baumanab** [comment]
I just tested this on my system and if the file is in src it commits but not if it is in the main project folder. Please let us know if this is not the case for you.

**Comment by vishalrangras** [comment]
Hi @baumanab,

I and one of my friend, we both this issue with TortoiseGIT client on Windows 10 machine. We had the file in src directory itself and we both committed everything in the repo and submitted the project thinking that everything was versioned, however, the particle_filter.cpp was left unversioned and hence did not got committed. We both got a project rejection for the same and had to resubmit again.

It may be issue with some GIT clients and may not be with others, but for TortoiseGIT client, it ignores the list in every sub-directory when the .gitignore file is in the top directory itself. I would suggest to remove the reference of particle_filter.cpp from the .gitignore altogether.

**Comment by baumanab** [comment]
That makes sense.  I've commented out line.  Please let us know if this doesn't solve the issue.
