### ISSUE TITLE
Miniflow/Linear Transform is inconsistent

### ISSUE THREAD

**Issue by dimakura** [udacity/sdc-issue-reports#119]
This section looks inconsistent.

It starts with the plan: ```In the old paradigm of neurons, a single output, o, is the result of summing n weighted inputs (x * w) with a bias, b. In the new paradigm of layers with multiple inputs and multiple outputs, Equation (1) needs revision with vectors and matrices.```

Then it continues:

`Consider a layer with n inputs and k outputs.`

What does that mean exactly? I can't figure out any explanation consistent with the following formulas.

**Comment by dimakura** [comment]
if `n` means "number of neurons in the layer" and `k` means "number of neurons in the next layer", then w can't be described by single row, as it's given in the text.

**Comment by domluna** [comment]
@dimakura the wording for that section is confusing, working on a better explanation. The quick fix is we're actually mapping from 1 to k not n to k. n just is the batch size in this scenario.

Also see #108

**Comment by dimakura** [comment]
@domluna I think the line is not the only confusing part. The middle of the section is also difficult to follow.
1. Why is `x` represented as a vector?
2. And how can `w` be a vector at all?
3. Also `xw` expression doesn't seem to represent anything meaningful.
Maybe just starting with `X` and `W` is less confusing and correct.

**Comment by domluna** [comment]
@dimakura Maybe, but I'm worried starting with `X` and `W` might be too big a jump. Or do you mean starting the notation with `X` and `W` right off the bat?

What if the batch size was ignored until the end?

So at first `x` is a single number or 1x1 (one example and one feature) and `w` is still 1xk. 1 to k mapping.

Then we generalize to `m` features, `x` is 1xm and `w` becomes and is `W` mxk. m to k mapping.

Then batch size is introduced and `x` becomes `X` and is nxm.

Do you think this is easier to follow?

**Comment by dimakura** [comment]
Yes, if it would be much easier to follow, i think.

**Comment by domluna** [comment]
Awesome, thanks for the feedback!

**Comment by ksakmann** [comment]
@domluna I agree, it makes sense now the way you wrote it above. But the example with the image is still confusing. batch size is 1 in that case. I has to work my way through the code to understand what was happening.

**Comment by domluna** [comment]
@ksakmann yeah writing that part a bit differently also. In process of pushing the fixes now (should be there very shortly). If it's still confusing after the changes let me know!

**Comment by domluna** [comment]
New version is up btw.

**Comment by ksakmann** [comment]
not confusing anymore, clear as daylight

**Comment by dimakura** [comment]
@domluna looks good to me
