### ISSUE TITLE
Term 2: CMakeLists.txt issue on Mac

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1190]
The CMakeLists.txt contains this line:

```
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin") 
...
link_directories(/usr/local/Cellar/libuv/1.11.0/lib)

endif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin") 
```

The version for `libuv` is hardcoded to 1.11.0, however the latest version is 1.15.0 and there will be a version mismatch when students run `brew install libuv`. So this line needs to be changed for the file `install-mac.sh` in all the project repositories.

**Comment by baumanab** [comment]
Wow, good catch.  I'll start making these changes shortly.

**Comment by baumanab** [comment]
I changed this to the following on my system:
```link_directories(/usr/local/Cellar/libuv/1*/lib)```

This seems to work.  Would you mind testing this on your system to confirm?

**Comment by baumanab** [comment]
The file has been updated.
