### ISSUE TITLE
Class mentorship - due date warning is incorrect

### ISSUE THREAD

**Issue by gpavlov2016** [udacity/sdc-issue-reports#1191]

**Comment by gpavlov2016** [comment]
![mentorship.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5819710c86304a0e003ad354/125516c66e82c728ace21e0d46e59194378d91ba87e0af01e81fe086264c22703d46f96925ddb371ed1b23570c5e46f8455c0d44fcf9892da4b56e71984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85bfbf8244c5eb3b24e78c9d02.jpg)

**Comment by baumanab** [comment]
Yes, either those are incorrect or I really need to get on top of my holiday shopping.  Thanks for letting us know.  I'll report this to the classroom experience team.

**Comment by baumanab** [comment]
Closing as this issue is now being tracked in another system.

https://udacity.atlassian.net/browse/GURU-1574
