### ISSUE TITLE
Term 3 22.10 Virtual machine file extension is wrong

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1192]
The instructions in the "Introduction to ROS" lecture "Your Virtual Machine" say:

Click the folder icon on the right and navigate to your unzipped image (the .ova file).

The zip contains an .ovf file, not a .ova file. Should the instructions say .ovf?

**Comment by baumanab** [comment]
Good catch!  This has been corrected.
