### ISSUE TITLE
Term 3 23.5 incorrect apt-get command

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1193]
The "rosdep" lecture suggests running this command:
sudo apt-get ros-kinetic-gazebo-ros-control

which should be:
sudo apt-get install ros-kinetic-gazebo-ros-control

**Comment by baumanab** [comment]
Thanks for letting us know.  I'm having some challenges finding this.  Would you mind providing a link?

**Comment by CodingCanuck** [comment]
https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/8793cdb1-ada4-4b1f-826d-50b4b5b78038/concepts/ad9785ee-a561-4a98-bf11-a8ef32d6fc75

The bad command is the third-last paragraph on the page, which ends with the following four paragraphs:


Issues with this command may arise when using a VM. If this is the case, please try:

sudo apt-get ros-kinetic-gazebo-ros-control

And there you have it, launch the simple_arm package again and your arm should no longer be swinging around!

With all packages properly installed, you will now learn more about ROS packages, in preparation for writing your own nodes in the next lesson!

**Comment by baumanab** [comment]
Thanks, this has been corrected.
