### ISSUE TITLE
Term 3 23.4/5 VM pre-installed packages don't match lesson videos/instructions

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1194]
The lesson videos where the speaker sets up and fixes ROS dependencies are confusing, and don't appear to match the VM.

The lessons suggest running the following commands:
sudo apt-get install ros-kinetic-controller-manager
sudo apt-get install ros-kinetic-gazebo-ros-control

But neither of these do anything because these packages appear to be pre-installed in the VM image Udacity_VM_Base_V1.0.0.zip (or the packages were already installed when I was following along with the lesson).

This is also confusing because the video in part 4 of section 23 shows the speaker fixing a compile error when building the cloned git repo, but I see no errors when building on the provided VM.

**Comment by baumanab** [comment]
My recollection is that this content was put in place during the beta phase and prior to VMs being full stable.  It seems like the video content is still useful but is understandably confusing when using a fully stocked and stable VM.  Do you think a note in the classroom would be sufficient?

**Comment by CodingCanuck** [comment]
Yes, I think a note in the classroom would help a lot, since a good portion of the video content is working through this build error.

Maybe something like "This course uses an updated version of the VM: you should expect your build to be error-free, and you shouldn't see the build errors the speaker is working through in the video"

**Comment by baumanab** [comment]
Thanks for the suggestion.  A note has been placed under the videos.
