### ISSUE TITLE
Incorrect statement in Capstone project lesson

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#1195]
With reference to Term 3, System Integration Project, [Sec. 5 DBW Node](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/877ed434-6955-4371-afcc-ff5b8769f0ce), there is this statement: 

> In the simulator, however, DBW is always enabled, so this is a difference between the simulator and Carla about which you should be careful."

I believe the statement is incorrect, as the simulator actually starts with DBW disabled, and it can be enabled/disabled ticking "Manual" in the simulator GUI.

**Comment by baumanab** [comment]
Thanks for letting us know.  I changed the sentence to a more generalized statement to let student's know they should check DBW status and toggle to the desired state.

> When operating the simulator please check DBW status and ensure that it is in the desired state.  DBW can be toggled by clicking "Manual" in the simulator GUI.
