### ISSUE TITLE
T2, 7.21 : Matrix dimensions

### ISSUE THREAD

**Issue by Jeremy26** [udacity/sdc-issue-reports#1197]
In the code :
Main.cpp has x_pred(15,5) while
ukf.cpp has function (5,15)

**Comment by baumanab** [comment]
Thank you for reporting this.  I looked at the ukf.cpp file and I'm not seeing 5,15 (even when searching) would you mind linking the content and also letting us know which line you see this at?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
