### ISSUE TITLE
Term 3 P Pathplanning 1

### ISSUE THREAD

**Issue by christianreiser** [udacity/sdc-issue-reports#1200]
The goal !in! this project is to build a path planner that !is! creates smooth, safe trajectories for the car to follow. The highway track has other vehicles, all going different speeds, but approximately obeying the 50 MPH speed limit.

**Comment by baumanab** [comment]
Thank you for posting an issue.  I'm not clear on the meaning of this particular post.  Is this calling out a typo in the path planning instructions?  Would you mind clarifying?

**Comment by baumanab** [comment]
Ah, I read the other posts.  I get it now.  Thank you.

**Comment by baumanab** [comment]
This has been updated.
