### ISSUE TITLE
term 2, lesson 19,  part 8.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1201]
Here in operator() you'll define the cost function and constraints. x is already completed:

for (int t = 1; t <= N; t++) {

----> the t <=N is error, should be t < N

and here:
fg[1 + x_start + i] = x1 - (x0 + v0 * CppAD::cos(psi0) * dt);

----> no i defined here, should be t.

**Comment by baumanab** [comment]
Great catch!  These have been corrected.
