### ISSUE TITLE
term 2, P5, env setup error.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1202]
IPopt setup in linux:

Linux:

sudo apt-get install gfortran

report error. and cannot download serials of related files.
please update.

**Comment by asimay** [comment]
this impact the Project plan.

**Comment by baumanab** [comment]
That is unusual. Would you mind sharing the error message?  Have you run sudo apt-get update?

**Comment by baumanab** [comment]
Thank you for the feedback.  I added a note regarding this.
