### ISSUE TITLE
term 2, P5, IPopt setup env script.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1203]
In p5, when setup IPopt, instruction said: ./install_ipopt.sh Ipopt-3.12.7

---> should add sudo, else compile and install is error.

**Comment by baumanab** [comment]
Thank you for letting us know. Would you mind sharing the error message?  It sounds like adding sudo eliminates the error. Where did you add sudo?

**Comment by asimay** [comment]
> sudo  ./install_ipopt.sh Ipopt-3.12.7

or else the install will not success, because it will automated make install much things on background if you noticed this.

**Comment by baumanab** [comment]
Thank you for clarifying.  I've added a note to the install instructions.

**Comment by Dios-Malone** [comment]
This issue is still there in 2019...
