### ISSUE TITLE
Capstone project: dbw_test brake values look incorrect

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1204]
I'm trying to figure out why my dbw controller's brake values don't match those produced by dbw_test.

Specifically in the bag file linked to from dbw_test.py, when I run the test I see brake values in brakes.csv that are only between 0 and 0.25.

Aren't brake values supposed to be torque in N*m for a multi-ton vehicle (as described in https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/877ed434-6955-4371-afcc-ff5b8769f0ce )? Shouldn't torque values be in hundreds or thousands of N*m to slow a heavy vehicle, rather than <1? Are these values correct?

**Comment by baumanab** [comment]
Thanks for letting us know about this.  We are looking into it.

**Comment by CodingCanuck** [comment]
Are the brake values in the bag file expressed as percentages, rather than absolute torque values?

**Comment by borisd13** [comment]
I think it would make sense to be in percentage. They seem very low and a bit strange though: 0.25 for brake and 0.025 for throttle, with not any variation except for on/off.

**Comment by srikantrao** [comment]
I am facing the same problem right now. We are asked to submit brake values in N*m but the rosbag's actual values are in fractions similar to the throttle value.

is the rosbag actual values correct or the instructions for calculating brake in torque ? 

It would be good to get clarification on what unit the brake value needs to be returned in.

**Comment by baumanab** [comment]
The file and instructions have been updated.
