### ISSUE TITLE
Term 2 Lesson 11.24 Video Repeat

### ISSUE THREAD

**Issue by SealedSaint** [udacity/sdc-issue-reports#1205]
The video has a portion that repeats itself starting around 2:30 until around 2:55

**Comment by baumanab** [comment]
As many times as I have watched that video, I hadn't noticed.  Thank you for letting us know.  We are actually in the process of refactoring the code and quizzes, which will come with new videos.  For that reason, I'm going to close this out (since this video will be retired).
