### ISSUE TITLE
T3 Capstone - Installation Instructions

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#1206]
1. For the github README, it would help if there was a simple way to clarify if the "Native Installation" and "Docker Installation" steps are not subsequent steps, but are alternatives to each other.

A small detail but it can be confusing and might seem to students both are required.

2. It would help to have a simple test to make sure that everything is downloaded and running properly (VM connecting to simulator and running without issues on different OS') before students start on the project. Some instructions on that would be good. So something where you can have the VM running, everything downloaded/installed, port forwarding setup, simulator downloaded on host, and then a basic connection test where some script could allow to display a message or move the car or something. The current section in the README on "USAGE" doesn't clarify that well right now I think. 

3. After the VM is running in virtualbox or vmware, it would help to know if it can be locally updated or not. After starting it up I got the "software update" option and I am unsure if that would help or break things.

**Comment by baumanab** [comment]
Thanks for suggesting these enhancements and points of clarification.  Item 1 has been addressed.  We will look into items 2 and 3.

**Comment by mvirgo** [comment]
Do we want to close this one out since the project is now in a workspace?

**Comment by baumanab** [comment]
Yes
