### ISSUE TITLE
Poor coding in term 2

### ISSUE THREAD

**Issue by OSR-raw** [udacity/sdc-issue-reports#1207]
I have been suggested to add comment about that.
Source: https://discussions.udacity.com/t/a-c-question-for-function-signatures/401764/4?u=oskravchuk

Point of content:
Lets take this function - Particle ParticleFilter::SetAssociations(Particle particle, std::vector<int> associations, std::vector<double> sense_x, std::vector<double> sense_y)
Here every param is sent by value meaning it is COPIED when function is called. Why would you do that?
Function itself:
{
	//particle: the particle to assign each listed association, and association's (x,y) world coordinates mapping to
	// associations: The landmark id that goes along with each listed association
	// sense_x: the associations x mapping already converted to world coordinates
	// sense_y: the associations y mapping already converted to world coordinates

	//Clear the previous associations
	particle.associations.clear();
	particle.sense_x.clear();
	particle.sense_y.clear();

	particle.associations= associations;
 	particle.sense_x = sense_x;
 	particle.sense_y = sense_y;

 	return particle;
}

So you effectively update 3 variables - associations, sense_x, sense_y.

Lets see what happens actually:
you copy whole structure when you call the function. You clear array and then assign them.
You return this new object.
And  later you have one more assignment.

What we got in the end:
- 3 copies of arrays
- 3 useless clear (you will reassign those values, they will be cleared anyway)
- 3 assigments
- 1 more assigment operator after function return. 

What could you do instead:
void ParticleFilter::SetAssociations(Particle& particle, const std::vector<int>& associations, const std::vector<double>& sense_x, const std::vector<double>& sense_y)
{
	//particle: the particle to assign each listed association, and association's (x,y) world coordinates mapping to
	// associations: The landmark id that goes along with each listed association
	// sense_x: the associations x mapping already converted to world coordinates
	// sense_y: the associations y mapping already converted to world coordinates

	particle.associations= associations;
 	particle.sense_x = sense_x;
 	particle.sense_y = sense_y;
}

Cost: 3 assigment.

**Comment by OSR-raw** [comment]
About pointers the original post on forum wraps this part up.

**Comment by baumanab** [comment]
Thanks for suggesting this. We have been looping back through several term 2 projects and changing pass by value and pass by pointer, where appropriate.  We definitely haven’t fully optimized projects for performance. If you are interested in a pull credit you can fork the repo and submit a pull request.  Otherwise we will make appropriate changes. Please let us know.

**Comment by baumanab** [comment]
The function has been tested and the code updated.  Thank you!
