### ISSUE TITLE
Behavioral Cloning - Running the Simulator instructions

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#121]
Running the Simulator instructions (https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/8c907d60-9e2a-4613-82ef-1ea3b2272e90) states that:
"When you first run the simulator, you’ll see a configuration screen asking what size and graphical quality you would like. "

But I can't see this configuration screen when I start Linux version of simulator (didn't check on other OS)

**Comment by Brok-Bucholtz** [comment]
@dalex01 

One of our developers ran the simulator on their Ubuntu computer using [this](https://d17h27t6h515a5.cloudfront.net/topher/2016/November/58197f38_simulator-linux/simulator-linux.zip) link and got the configuration screen:
![Config Scree](http://imgur.com/download/RWzOZX4)

Can you send me a screenshot when you run the simulation?

**Comment by dalex01** [comment]
When I reload app from the provided link everything works fine for me. The same is for link in the lesson.

It seems I've used some old version before - here is start of this old version:
![out](https://cloud.githubusercontent.com/assets/7311046/20073560/cc39b2e0-a53d-11e6-9c62-3deca1e79e71.gif)

Sorry that I didn't double-check the link before.

**Comment by Brok-Bucholtz** [comment]
@dalex01 

It's no problem.  I'm glad you're able to make progress on the project.  Let us know if you need anything else.
