### ISSUE TITLE
Term 1: Windows instructions for connecting to AWS instances

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1212]
The [classroom instructions](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/614d4728-0fad-4c9d-a6c3-23227aef8f66/concepts/f6fccba8-0009-4d05-9356-fae428b6efb4) for connecting to AWS instanaces are only for Mac/Linux. We need to have instructions for Windows as well. This was [pointed out by a student on the forum](https://discussions.udacity.com/t/aws-instance-using-windows/410582).

**Comment by baumanab** [comment]
Thanks for letting us know about this.  It's good to get multiple perspectives on instructions as there are some elements we take for granted.  Some information regarding Windows SSH clients has been added.
