### ISSUE TITLE
T3 Capstone - Incorrect TF version in Lesson

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#1213]
In the TF Light Detection Node Concept - https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/d58e2c6a-1fd2-4e33-8912-861051ab301b

The required TF version is 1.0.0 for Carla, but I believe this was changed to 1.3.0 recently. The github requirements.txt file mentions 1.3.0

**Comment by CodingCanuck** [comment]
I agree: this recent commit to the capstone project upgraded tensorflow to 1.3.0: https://github.com/udacity/CarND-Capstone/commit/4c437a3bf76d731befff938761039411b6156c4f

**Comment by baumanab** [comment]
Thanks for reporting and confirming.  The classroom has been updated.
