### ISSUE TITLE
Term 2 lesson 13 quiz 23, corrent answer gives wrong values

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1214]
correct answer should be only adding print(eval(p,r)) as the last line inside last for loop.
but values for printed are wrong

ex: 
13.396328737 
14.5042106027 
20.6750799264 
29.6970120635 
35.1257033852 
40.0600262597 
44.586007856 
48.9571994277 
47.0062944415 
43.3312222516

another ex:
23.7318503419 
26.6470126612 
31.0235826557 
35.9766905708 
40.8154430451 
45.6519104121 
50.5149231893 
47.6988385883 
43.8095832373 
40.4948067871

**Comment by baumanab** [comment]
Would you mind clarifying the issue?  When I use the approach presented in the solution video, which does add a print statement on the last line of the final for loop, I get the correct answer.  The resulting errors should be much smaller than those reported above.  They should be closer to those shown in the solution video.  Have you tried the instructor solution?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
