### ISSUE TITLE
Term1, Lesson 5, Section 13

### ISSUE THREAD

**Issue by Nabil-Abada** [udacity/sdc-issue-reports#1215]
In Lesson 5 "MiniFlow" at section "13. Backpropagation" it is stated that "Using the derivative, we can say how much a change in x effects f(x). For example, when x is 4, the derivative is 8 (2x=2∗4=8). This means that if x is increased or decreased by 1 unit, then f(x) will increase or decrease by 8." 

I think there is an error here, it should be like this: " ... This means that if x is increased or decreased by 1 unit, then f(x) will increase or decrease by 2 units."

**Comment by baumanab** [comment]
Thanks for catching this typo, it is now corrected.
