### ISSUE TITLE
term 2 lesson 14 quiz 17, wrong image

### ISSUE THREAD

**Issue by anasmatic** [udacity/sdc-issue-reports#1216]
I can't find the answers in the attached image
https://d17h27t6h515a5.cloudfront.net/topher/2017/August/598aa0c0_localization-map-concept-copy/localization-map-concept-copy.png

**Comment by baumanab** [comment]
Thank you for reaching out about this. This is a challenging question which asks to associate the transformed observations (observations in map coordinates), to the closest landmark.  The image is correct in that it contains the all the landmark observations.   The final step is to determine which of the landmarks is closest to each observation, in map coordinates.  I hope this is helpful.  Please contact mentor support if guidance is needed to solve this problem.  Please also let us know if there is something we can add to clarify what it is we are looking for (please open a new ticket for that).
