### ISSUE TITLE
Bug in Grader, SDC ND, Term 2, Lesson 7, Section 20

### ISSUE THREAD

**Issue by sebzi84** [udacity/sdc-issue-reports#1218]
https://discussions.udacity.com/t/sigma-point-prediction-assignment-1-same-result-as-should-be-but-not-passing-when-submitting/443695

**Comment by baumanab** [comment]
Thanks for letting us know about this.  I tried the code provided in the forum post.  When I run it, it produces the expected output (test) and passes the grader (submit).  Would you mind trying again and letting us know what happens?  If it doesn't pass, please paste the entire contents of ukf.cpp here or link from a repo or pastebin.  This will help with troubleshooting.

**Comment by baumanab** [comment]
Closed as not actionable without updated information
