### ISSUE TITLE
Errors during drive.py running in Behavioral Cloning project

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#122]
The following error appears in console when I run `drive.py` with command `python drive.py model.json`:
```
TypeError: connect() takes 1 positional argument but 2 were given
```

To resolve this problem line `def connect(sid, environ):` should be used instead of `def connect(sid):`

**Comment by dalex01** [comment]
`drive.py` is loaded from [this page](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/d76f87f5-f9d9-4d63-968a-99606fe90749)

**Comment by swwelch** [comment]
Thanks! drive.py has been updated on the site.
