### ISSUE TITLE
Lesson 14.Chapter 11 Update Step: Car orientation is wrong.

### ISSUE THREAD

**Issue by ranamanish** [udacity/sdc-issue-reports#1220]
At 2:04 second, either the orientation of geometric representation of co-variance matrices is wrong or Car direction needs to be updated. 
The X direction is in the direction of Car movement (as specified in the lecture), while the in this case it seems to be 90 degree to the right.

**Comment by baumanab** [comment]
You are correct regarding the orientation. Did the note below the video help clarify this?

**Comment by ranamanish** [comment]
Yes, it clarified. though I think correct orientation will help keep the context correct.

**Comment by baumanab** [comment]
I'm glad the notes helped.  For now, we are sticking with the current version, but we may change it in the future.  Changing the orientation may add its own element of confusion.
