### ISSUE TITLE
T3 Capstone Datasets Alternative Links Request

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#1221]
Currently, the datasets provided (the rosbag files) are uploaded on Google Drive. 

Those can be utilized for the TL detection/Classification part as part of the datasets for training (students have done so).

Could those be uploaded to AWS as well? It becomes difficult to try to download and then upload the datasets when trying to train a model on slow internet speeds. And it's complicated to download onto AWS via terminal from Google Drive links.

Thanks!

**Comment by baumanab** [comment]
Hi, we will look into this. In terms of internet connections, that shouldn’t be a large factor if students download from source to AWS instance. Are students transferring to their local system, then uploading to AWS?  If so, it may be worth trying wget or curl. I could be wrong, I’m just trying to understand the issue and potential work arounds. From my experience wget on AWS is pretty fast, even with slow connections, since everything but the command is happening server side. What do you think?

**Comment by sahiljuneja** [comment]
You can't use wget or curl directly with a google drive link. It's not a straightforward process. 

One solution is to download the data then locally and then transfer the files (after converting to images and zipping) to the AWS instance via SCP or WinSCP.  Which at slower internet speeds is problematic and time-consuming and not cost-effective for those relying on credits.

An alternative would be to download locally, convert to images and then upload them to an S3 bucket and use that link for AWS. I am not sure of any associated costs around this in AWS. But it's far easier if Udacity provides such a link if possible. I think for prior datasets or for datasets in other NDs data is uploaded onto AWS and a link is provided to the students.

Of course, this is more an edge case that I have come across personally. Since many students are adopting the Object Detection API approach now for the capstone it could potentially help the ones with slower internet speeds but  I might be in a minority on that front I guess.

**Comment by baumanab** [comment]
That makes sense. Thank you. I hadn’t realized that gdrive links were an issue with wget. I’ll look into options.

**Comment by baumanab** [comment]
One option aside from upload to AWS is storage on GitHub. This would allow straight forward wget. I’m not sure if this is the best option but I think it would work.

**Comment by sahiljuneja** [comment]
Github has file size limits. So GBs of data might not work. And there is a drawback on github that if you wish to try to remove the large files at some point, it still stays on in the history and removing those from there is a complicated process from what I gather. So the removed large file remains as a ghost in the repo and contributes to the large repo size. 

I also realized that for the above rosbag files to be useful for the DL training, they would need to be converted to images. Which I think can only be done via ROS packages. So that kind of beats the purpose of uploading the rosbags on AWS and makes my suggestion pointless.

**Comment by baumanab** [comment]
Thanks for doing the heavy lifting on this :). It sounds like we have come full circle.  I'll do some digging for a solution/workaround.  I'm going to close out, for now, I'll re-open if either of us finds something promising.
