### ISSUE TITLE
Error in cloning CarND-Transfer-Learning-Lab repo due to the large bottleneck files

### ISSUE THREAD

**Issue by wwymak** [udacity/sdc-issue-reports#1222]
When I do `git clone git@github.com:udacity/CarND-Transfer-Learning-Lab.git` it gives me an error saying
```Error downloading object: inception-cifar10-bottleneck-data.zip (09c25f5): Smudge error: Error downloading inception-cifar10-bottleneck-data.zip (09c25f5b9a56ebbee29981d7e4783f83670b8e8710244d50759c2492e63dc582): batch response: This repository is over its data quota. Purchase more data packs to restore access```

However, I can download the repo as a zip file. However, the bottleneck files cannot be unzipped

(and I do have git-lfts installed)

**Comment by baumanab** [comment]
Thanks for posting this.  It looks when storing the models using git-lfts, the model files will not unzip, when using the download zip option.  With respect to the error on clone.  I just tried this and it worked for me.  Would you mind trying one more time using the following command?

```git clone https://github.com/udacity/CarND-Transfer-Learning-Lab.git```

**Comment by baumanab** [comment]
A colleague pointed out this could be a git version issue.  Apparently, in older git versions git clone and git lfs clone, are not synonymous.  It may be worth updating your git version then using the clone command above.  If that isn't feasible it may be worth trying:

```git lfs clone https://github.com/udacity/CarND-Transfer-Learning-Lab.git```

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
