### ISSUE TITLE
fault - failure confustion: Functional Safety, lesson 14.10

### ISSUE THREAD

**Issue by olegleyz** [udacity/sdc-issue-reports#1223]
Fault->failure->hazard->risk were introduced in vocabulary section of 14.9.
in 14.9 also stated "Fault and malfunction are somewhat synonymous"
in 14.10 in the quiz there are fault and malfunction and no failure

**Comment by baumanab** [comment]
That does seem inconsistent, thank yo for reporting it.  We will review.

**Comment by baumanab** [comment]
I've changed the last option to failure, as it is more consistent with the vocabulary taught in 14.9.
