### ISSUE TITLE
Sound quality: Term2 Lesson 7.19

### ISSUE THREAD

**Issue by ricardo-jmnez** [udacity/sdc-issue-reports#1224]
Lesson 7.19 on Sigma point prediction. From my end, there is something wrong with the sound, please check sound quality.

**Comment by baumanab** [comment]
Yes, there is definitely something going on with the audio.  Thanks for bringing this to our attention.

**Comment by baumanab** [comment]
the concept is here:
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/0d0dc68e-f2db-4e23-8576-37f1186775ca

**Comment by baumanab** [comment]
This has now been corrected
