### ISSUE TITLE
confusing description, Term2: Lesson 7.22

### ISSUE THREAD

**Issue by ricardo-jmnez** [udacity/sdc-issue-reports#1225]
Your description of the EKF and UKF is fantastic. You put a lot of effort making sure to use the right notation and describing that notation. Your visuals are great and your insight into subtle issues such as noise calibration by means of the normalized-innovation-squared (NIS) is very useful. Here is only one issue on something was not clear to me, if you can check this and correct it if necessary (perhaps lectures notes) it would be great. Great work!  

In Lesson 7.22 your description on the propagation of the sigma points (referred as Calligraphic-X) is confusing. Right after showing the roadmap in the slides (approx.. at 0:13”) you say: “First, we generated the sigma-points, then we predicted them”. This does not make sense. I think what you mean is this: “First we generated the sigma points Calligraphic-X(k), then using the nonlinear transformation  f(x_k,nu_k) we propagate them to obtain the state of the system at time k+1, which we call the predicted sigma points denoted as Calligraphic-X(k+1).

**Comment by baumanab** [comment]
Great suggestion!  A note has been added beneath the video.
