### ISSUE TITLE
Implement Behavior Planner in C++ improvements

### ISSUE THREAD

**Issue by uvbakutan** [udacity/sdc-issue-reports#1227]
The global variable GOAL will not override the goal lane and distance because you don't use it in the main.

int goal_s = 300;
int goal_lane = 0;

it should be:

int goal_s = GOAL[0];
int goal_lane = GOAL[1];

Another issue is the state selection when the car is at the most left or most right lane.. If you are at lane 0 you can't go right any more so the state PLCL should not be reachable:

solution:

    if(state.compare("KL") == 0) {
        if (lane == 0)
            states.push_back("PLCL");
        else if (lane == lanes_available - 1)
            states.push_back("PLCR");
        else{
            states.push_back("PLCL");
            states.push_back("PLCR");
        }
    }

**Comment by swwelch** [comment]
Hi @uvbakutan, thanks! These have been fixed, and the quiz has been revised.
