### ISSUE TITLE
Term 1, Behavioral Cloning, BGR vs RGB color space reminder

### ISSUE THREAD

**Issue by viadanna** [udacity/sdc-issue-reports#1229]
Many students have trouble in this project not because the neural network was incorrectly implemented or trained but because the training images are loaded in BGR colorspace using cv2 while the drive.py load images in RGB to predict the steering angles.

I highly recommend reminding the students in the classroom about the color space used in drive.py as this has the potential of reducing the amount of resubmissions for this project.

**Comment by baumanab** [comment]
Thank you for letting us know about this.  A note has been added to the classroom as well as the project repo.
