### ISSUE TITLE
Traffic Signs Pickle Conflating 'coords'

### ISSUE THREAD

**Issue by mgruben** [udacity/sdc-issue-reports#123]
When loading the `train.p` pickle file, it appears that `train['coords']` actually contains a duplication of the information in `train['sizes']`.

That is, `train['coords']` contains a 2-tuple whose values match the 2-tuples of `train['sizes']`.  According to the `jupyter` notebook, it should instead contain a 4-tuple `(x1, y1, x2, y2)` of the location of the sign in the original, larger image.

Within the `jupyter` notebook, running `train['coords'] == train['sizes']` yields
```
array([[ True,  True],
       [ True,  True],
       [ True,  True],
       ..., 
       [ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)
```

**Comment by domluna** [comment]
Oops! I'll update the dataset, thanks @mgruben. Looks like `test.p` is fine.

**Comment by domluna** [comment]
New zip file https://d17h27t6h515a5.cloudfront.net/topher/2016/November/581faac4_traffic-signs-data/traffic-signs-data.zip

It should be fine now.

**Comment by Ahmedest61** [comment]
Can you share the code that takes the images with labels and generate pickle files?

**Comment by baumanab** [comment]
That sounds like something that would be helpful. Would you mind opening this under a new issue?

**Comment by Ahmedest61** [comment]
Of course :-)
