### ISSUE TITLE
Term2 Lesson 11.21 Coding II - compilation error

### ISSUE THREAD

**Issue by Gryton** [udacity/sdc-issue-reports#1230]
Coding II: Implement the Motion Model Part 1:
Test run returns compilation error (even if used code from Lesson 11.22 that contains solution to 11.21, replaced `bayesianFilter.cpp`, `bayesianFilter.h`, `main.cpp`). Probably that's wrong compilation/linking option.

Returned error:
```main.o: In function `main':
main.cpp:(.text+0x205): undefined reference to `bayesianFilter::bayesianFilter()'
main.cpp:(.text+0x261): undefined reference to `bayesianFilter::process_measurement(MeasurementPackage const&, map const&, help_functions&)'
main.cpp:(.text+0x33e): undefined reference to `bayesianFilter::~bayesianFilter()'
main.cpp:(.text+0x452): undefined reference to `bayesianFilter::~bayesianFilter()'
collect2: error: ld returned 1 exit status```

Next section works fine (Lesson 11.22), so probably it'll be enough to replace compilation options.

**Comment by baumanab** [comment]
Thank you for reporting this.  Functionality has been restored.
