### ISSUE TITLE
Clarifying Port Forwarding explanation for Term 2+3

### ISSUE THREAD

**Issue by AvnitMac** [udacity/sdc-issue-reports#1233]

**Comment by AvnitMac** [comment]
There is a need to specify explicitly the importance of setting the host ip.

Please see : "https://discussions.udacity.com/t/simulator-connecting-problem/457242"

**Comment by baumanab** [comment]
Thank you for letting us know about this.  We have added some tips to the mac and windows environment setup pages.  The instructions regarding port forwarding have also been clarified.
