### ISSUE TITLE
Search tool allows bypassing the paywall for term-1 students

### ISSUE THREAD

**Issue by vsingla2** [udacity/sdc-issue-reports#1234]
I'm not sure if I'm the only one to notice this but if you're enrolled in term-1, and have not started the later terms, the search tool still allows access to all the lesson materials. I just finished term-1 today and noticed this while monkeying around the website. For example a simple query "Welcome" will bare all the materials to user.

**Comment by baumanab** [comment]
Thank you for reporting this.  We have recently become aware of this issue and are actively working to correct it.  I'm closing this out since it is already open in our internal tracking system.
