### ISSUE TITLE
Videos Automatically Display Subtitles, and in Chinese

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#1235]
I've heard this from a few students and it took us a while to figure out how to reproduce on my machine, but here's how you do it.

1. Launch Chrome (also happens in Safari, maybe Firefox)
2. Go to Settings
3. Search for "Language"
4. Add the German language
5. Set the browser to the German language
6. Click the "Relaunch" link
7. Visit [this page|https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/4b4a01ce-9c10-46e2-a98a-55ece636e589]
8. The video should display with Chinese subtitles

**Comment by baumanab** [comment]
It looks like this doesn't happen anymore.  There were a number of subtitle anomalies occurring at the time this was noticed, all of which have resolved.
