### ISSUE TITLE
Save Udacity.com Language Preference

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#1236]
From a German student:

"everytime I visit udacity I get asked if I want to view udacity.com in German, which I don't. But I get asked every time. Would be nice to save the answer in a cookie or something like that"

**Comment by baumanab** [comment]
That sounds frustrating.  I'll contact classroom experience.

**Comment by baumanab** [comment]
I'm also wondering if it is cookie settings in the browser.

**Comment by baumanab** [comment]
It turns out this was a browser setting issue and is now resolved.
