### ISSUE TITLE
T3 Capstone: Car doesn't move (Windows sim + Virtualbox)

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#1238]
Hello,

This is an issue which many seem to have faced. I have Windows 10, on which I have the simulator and I have the VM on virtualbox with port forwarding set up. However, upon running the code the car doesn't move in the simulator. It moves without issues for my teammate who is working on a linux host. 

The only solution to this is presented here - 

https://discussions.udacity.com/t/car-freezes-in-simulator-solved/363942/12?

Adding those two lines fixes things. The car then starts to move forward in the simulator. 

I am not sure why this happens, but the main point of concern is that I don't know if adding those two lines affects anything else or not. 

Does it any way degrade any performance, or cause any issues/blocks with any nodes/services etc in ROS later on? 

Also, this affects sharing solutions or working via github with the team(s) since others don't seem to require this fix.

It would be helpful if this can be resolved in an official capacity and so that students are sure this solution doesn't cause problems till then.

Thanks!

**Comment by baumanab** [comment]
Hi Sahil,  Thanks for posting this.  The team is working on it.

**Comment by sahiljuneja** [comment]
Thanks 👍 !

**Comment by baumanab** [comment]
Closing as this project has moved to workspaces.
