### ISSUE TITLE
Term 3: AWS AMI problem

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1240]
Few students have been reporting problems with AWS and the advanced deep learning AMI. When they try to train their model it says - 'No GPU found'. Please see these posts:

1. https://discussions.udacity.com/t/how-to-run-semantic-segmentation-on-aws/352069/96?u=subodh.malgonde
2. https://discussions.udacity.com/t/no-gpu-found-semantic-segmentation-project/458766

One student suspected that AWS made some hardware changes due to which the AMI no longer works.

Another student seems to have fixed it, here - https://discussions.udacity.com/t/how-to-run-semantic-segmentation-on-aws/352069/98?u=subodh.malgonde

**Comment by subodh-malgonde** [comment]
I am on this project right now. Still having this problem. The suggested solution, linked above, does not work for me.

**Comment by mvirgo** [comment]
Updated AMI has now been built with an updated TensorFlow build that works with AWS's changes.
