### ISSUE TITLE
Term 3: Lesson 5. 12: Problem with c++ code

### ISSUE THREAD

**Issue by rpicatoste** [udacity/sdc-issue-reports#1242]
Please add to hybrid_breadth_first.cpp the following line in line 117:

  state.theta = theta;

As it is now, if someone copies the files as they are to compile in his/her computer, it may not work. In my case, not giving a value there, the compiler was using garbage for the uninitialized variable and preventing the code to work. In the website it works because it is zero when entering the function, even if not initialized. I use Eclipse CDT + MinGW GCC.

**Comment by baumanab** [comment]
This has been added, thank you!
