### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by fusheng1990** [udacity/sdc-issue-reports#1243]
When I running the project code of MPC, all codes looks good, but once I open the simulator, I got an error of 
Segmentation fault (core dumped)
my g++ version is Ubuntu/Linaro 6.3.0 and cmake version is cmake version 3.8.2.
I do not know what is the problem ? could you give me a favor?

Thanks

**Comment by baumanab** [comment]
Thanks for letting us know about this. If your code is on GitHub, would you mind sharing the link to the repository?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
