### ISSUE TITLE
Term 3 System Integration README

### ISSUE THREAD

**Issue by river-wind** [udacity/sdc-issue-reports#1244]
More clarity in the Readme would help.  

1) make it more clear that *Either* the native install or docker should be used.  As it is, it looks like you get the VM image, and then install docker into the VM image.  

2) The commands provided may fail at catkin_make if "git clone..." was not run from ~.  When following the steps explicitly for docker, the "git clone" command is actually being run from the root directory and not ~.    Add the command "cd ~" right before "git clone..." command to avoid this issue.  

3) Add port forwarding setup instructions to the VM setup section since that is required to use a host-based simulator, recommended by the lesson material.

**Comment by baumanab** [comment]
Thank you for letting us know about these ambiguities.  With respect to item 3, will the port forwarding instructions from term 2 be sufficient? 

[bottom of this page](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/16cf4a78-4fc7-49e1-8621-3450ca938b77)

**Comment by river-wind** [comment]
I think so; if a user is using docker, then the port forwarding is included in the docker run comment.  For using the VM, the instructions on that page look complete!   Port Forwarding Instructions

    First open up Oracle VM VirtualBox
    Click on the default session and select settings.
    Click on Network, and then Advanced.
    Click on Port Forwarding
    Click on the green plus, adds new port forwarding rule.
    Add a rule that assigns 4567 as both the host port and guest Port, as in the screenshot.

**Comment by baumanab** [comment]
Thanks again for suggesting these points of clarification.  I've updated the README with respect to items 1 and 3.  Since item 2 is not yet actionable I'm closing this issue.  When more information is available for item 2, it can be opened as a new issue.
