### ISSUE TITLE
Term1: P3 video.py problem on Mac

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1245]
On Mac OS, there’s a hidden file called [.DS_Store](https://apple.stackexchange.com/questions/69467/consequences-of-deleting-ds-store). `.DS_Store` files are only used by the Finder to hold custom view settings for that particular folder. The `video.py` script in the project reads in all the files from the particular folder to create the video. The script encounters an error due to this hidden file. We should have a way to ignore non-image files.

Please see [this forum post](https://discussions.udacity.com/t/error-in-video-py/240566/5).

**Comment by baumanab** [comment]
Thanks for pointing this out and linking the corresponding forum thread.  It looks like it is actually the call to ```ImageSequenceClip``` where the problem arises.  This makes it a little more challenging to ignore the file.  I'm thinking that a robust approach that may work is to add code into ```video.py``` that removes all files without a compatible image extension.  Does that sound reasonable?

**Comment by subodh-malgonde** [comment]
Yes. Even I had a look at the source code of `ImageSequenceClip` and figured out that is where the problem lies. Your workaround sounds good, however you might want to show a warning to the user before you remove those files. Instead of removing you can ask the user to remove/move those files before running the script.

**Comment by baumanab** [comment]
I gave this some thought.  If you notice [here](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ImageSequenceClip.py) the image files can be passed as a list.  In fact, if you pass them as a folder, ```ImageSequenceClip``` will just convert them to a list.  So, I think that we can create a list that is filtered to only contain files of allowable extensions, and then pass that.  In this way, the user will not have to make any changes.

**Comment by baumanab** [comment]
I made some changes to video.py and pushed to the project repo.  This works on my system with non-image files, including ```.DS_Store```

Here is the updated code:

```python
from moviepy.editor import ImageSequenceClip
import argparse
import os

IMAGE_EXT = ['jpeg', 'gif', 'png', 'jpg']


def main():
    parser = argparse.ArgumentParser(description='Create driving video.')
    parser.add_argument(
        'image_folder',
        type=str,
        default='',
        help='Path to image folder. The video will be created from these images.'
    )
    parser.add_argument(
        '--fps',
        type=int,
        default=60,
        help='FPS (Frames per second) setting for the video.')
    args = parser.parse_args()

    #convert file folder into list firltered for image file types
    image_list = sorted([os.path.join(args.image_folder, image_file)
                        for image_file in os.listdir(args.image_folder)])
    
    image_list = [image_file for image_file in image_list if os.path.splitext(image_file)[1][1:].lower() in IMAGE_EXT]

    #two methods of naming output video to handle varying environemnts
    video_file_1 = args.image_folder + '.mp4'
    video_file_2 = args.image_folder + 'output_video.mp4'

    print("Creating video {}, FPS={}".format(args.image_folder, args.fps))
    clip = ImageSequenceClip(image_list, fps=args.fps)
    
    try:
        clip.write_videofile(video_file_1)
    except:
        clip.write_videofile(video_file_2)


if __name__ == '__main__':
    main()
```
