### ISSUE TITLE
Lesson 24.5 - serviceClassNameResponse or serviceClassNameRequest ?

### ISSUE THREAD

**Issue by Daniel-Prado** [udacity/sdc-issue-reports#1247]
In lesson 24.5’s text, it says:

One way the ServiceProxy can then be used to send requests is as follows:

msg = serviceClassNameResponse()
#update msg attributes here to have correct data
response = service_proxy(msg)

Shouldn’t the first line be “msg = serviceClassNameRequest()” ?

**Comment by baumanab** [comment]
Would you mind linking the content?

**Comment by Daniel-Prado** [comment]
As I referenced, it's in Lesson 24, section 5. Link below:
https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/0bf289a5-8890-48f4-918a-bab4f49e0019/concepts/375eb9e3-2fd2-4fda-96c2-d5c88d382909

**Comment by baumanab** [comment]
It does seem like it should be request.  However, according to the ROS documentation, this is the correct pattern.  The name of the function could probably be more descriptive.
