### ISSUE TITLE
Term 3: OD Lab Error

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#1248]
In the Object Detection Lab, the link for the SSD graph is:

    SSD_GRAPH_FILE = 'ssd_mobilenet_v1_coco_11_06_2017/frozen_inference_graph.pb'

This would imply the `.tar.gz` file of the model would be named: `ssd_mobilenet_v1_coco_11_06_2017.tar.gz`

However in the [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) the file available for download is:

    ssd_mobilenet_v1_coco_2017_11_17.tar.gz

If you use this filename and try to load the model, then the following line throws an error:

    detection_graph = load_graph(SSD_GRAPH_FILE)

The error says:

>ValueError: No op named NonMaxSuppressionV2 in defined operations.

A [student pointed out](https://discussions.udacity.com/t/object-detection-lab-no-op-named-nonmaxsuppressionv2/446349/3?u=subodh.malgonde) that the models are built with tensorflow 1.4.0, whereas the lab environment uses 1.2. Upgrading to 1.4.0 fixes things

**Comment by baumanab** [comment]
It sounds like we should add a note advising students to upgrade tensor flow.  Is that correct?

**Comment by subodh-malgonde** [comment]
No, we need to update the version in the [environment.yml](https://github.com/udacity/CarND-Object-Detection-Lab/blob/master/environment.yml) file. Its `1.2` right now.

**Comment by baumanab** [comment]
Excellent point :)  The yml file has been updated.
