### ISSUE TITLE
subtitles always cover the lesson content,

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1249]
subtitles always cover the lesson content, and it's not convenient for study the course, every time need to remove the subtitle by hand to see what's the content under the subtitle. please consider.

**Comment by baumanab** [comment]
This is an unfortunate impact of subtitles.  We have very little control over where the subtitles are placed, as this is controlled by youtube.  I will mention this to the team in case anyone has a thought on mitigation.
