### ISSUE TITLE
TensorFlow version r0.11 doesn't work in Behavioral Cloning project

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#125]
It seems that tensorflow v0.9.0 or v0.10.0rc0 (v0.9.0 works for me) should be used in Behavioral Cloning project. But it is not specified anywhere in project lessons.

With newer versions I received the following error:
```
attributeError: module 'tensorflow.python' has no attribute 'control_flow_ops'
```

Here are appropriate discussions:
https://github.com/fchollet/keras/issues/3887
https://github.com/tensorflow/tensorflow/issues/4616

**Comment by thomasantony** [comment]
Add this to the top of your script before importing keras

`
import tensorflow as tf
tf.python.control_flow_ops = tf
`
This fixes the bug. I am now able to run Keras in TensorFlow 0.11

Source: [StackOverflow](http://stackoverflow.com/questions/40046619/keras-tensorflow-gives-the-error-no-attribute-control-flow-ops)

**Comment by dhruvp** [comment]
@Brok-Bucholtz could we add @thomasantony 's hint somewhere in our content in case anyone else hits this issue?

**Comment by Brok-Bucholtz** [comment]
@thomasantony and @dalex01,

I added @thomasantony's fix to Behavioral Cloning.  This will be added to the Keras lab this week or next week.
