### ISSUE TITLE
Lesson 11-32: Error in text for norm_pdf() call

### ISSUE THREAD

**Issue by LucFrachon** [udacity/sdc-issue-reports#1250]
The text in lesson 11-32 says that we should call
norm_pdf(obs_measurement - pseudo_range_estimate, observation_measurement, observation_stdev).

However looking at the quiz answers and the function definition, I believe we are actually calling
norm_pdf(pseudo_range_estimate, observation_measurement, observation_stdev).

Otherwise the first call would be norm_pdf(0.5, 5.5, 1) instead of norm_pdf(5, 5.5, 1), and the second call would be norm_pdf(0, 11, 1) instead of norm_pdf(11, 11, 1). Which obviously produces very different probabilities.

**Comment by baumanab** [comment]
Wow, great catch.  I'm glad we have such detail-oriented students.  I'm going to double check the content and make any necessary changes.

**Comment by baumanab** [comment]
I've actually corrected it to the following:

norm_pdf: ```norm_pdf(observation_measurement, pseudo_range_estimate, observation_stdev)```.   So, in this case, we are treating the estimate (it will actually be the minimum estimate in the estimate vector) as the parameter.  Since we are using symmetrical distributions, it doesn't actually matter in terms of the probability.
