### ISSUE TITLE
UKF CTRV Process Noise Position Equation Error

### ISSUE THREAD

**Issue by baumanab** [udacity/sdc-issue-reports#1252]
There is a mistake here:
![image](https://user-images.githubusercontent.com/4316306/33732557-c1dec71a-db3b-11e7-8c0c-d9b4fed0958e.png)

https://slack-redir.net/link?url=https%3A%2F%2Fclassroom.udacity.com%2Fnanodegrees%2Fnd013%2Fparts%2F40f38239-66b6-46ec-ae68-03afd8a601c8%2Fmodules%2F0949fca6-b379-42af-a919-ee50aa304e6a%2Flessons%2Fdaf3dee8-7117-48e8-a27a-fc4769d2b954%2Fconcepts%2F510295ae-5ede-47f5-b3aa-fafb997df074&v=3

The correct equation is here and should use `psi_dot * delta_t`
https://slack-redir.net/link?url=https%3A%2F%2Fclassroom.udacity.com%2Fnanodegrees%2Fnd013%2Fparts%2F40f38239-66b6-46ec-ae68-03afd8a601c8%2Fmodules%2F0949fca6-b379-42af-a919-ee50aa304e6a%2Flessons%2Fdaf3dee8-7117-48e8-a27a-fc4769d2b954%2Fconcepts%2F63674ce2-43ed-418c-bf8b-d16ae73dffc0&v=3

**Comment by mvirgo** [comment]
The two links - [1](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/510295ae-5ede-47f5-b3aa-fafb997df074) and [2](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/63674ce2-43ed-418c-bf8b-d16ae73dffc0)

**Comment by mvirgo** [comment]
Fixed :)
