### ISSUE TITLE
wrong equation in a solution

### ISSUE THREAD

**Issue by luqiang21** [udacity/sdc-issue-reports#1255]
class 25 of Markov Localization (Motion Model Probability II), in the question "Determine the belief state". 

In the solution
Rearranging yields:
2.42E-01/1.66E-03 = 6.86E-03

should be 1.66E-03/2.42E-01 = 6.86E-03, and the statement is correct, but the values are in opposite positions.

**Comment by baumanab** [comment]
**This has been corrected.  Thank you!**
