### ISSUE TITLE
Term-3 Capstone New Simulator Test Site bug.

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#1256]
Hey,

So in the latest simulator release you added a test site. But for this test site there's no "Camera" button like you have for the highway track. When I run the image viewer in ROS no image is being published to the camera topic and I think the missing "camera" button might be the case.

I am using the Windows version of the sim.

**Comment by baumanab** [comment]
It's true that there is no camera button.  Since there aren't any traffic lights on the test track, image data was omitted.  Does that make sense?

**Comment by sahiljuneja** [comment]
So it's just to make sure the car follows the track/waypoints? I guess this wasn't clarified in the announcement and was a bit confusing. Thanks for clarifying!

**Comment by baumanab** [comment]
No problem.  The classroom will be updated this week to clarify these and other potential issues.
