### ISSUE TITLE
Term 2: Mistake in CTE equation for MPC

### ISSUE THREAD

**Issue by edufford** [udacity/sdc-issue-reports#1257]
There is a mistake in the lesson's equation for CTE used for the MPC project that causes incorrect predicted CTE over the planned time horizon so the optimizer may not converge to the target path.

Original incorrect equation:
CTE = f(x) - y + (v * sin(epsi) * dt)

Corrected equation:
CTE = y - f(x) + (v * sin(epsi) * dt)

Please see this forum post for more details:
https://discussions.udacity.com/t/mistake-in-lessons-motion-equation-for-cte/458082

**Comment by edufford** [comment]
There is a mistake in the lesson's equation for CTE used for the MPC project that causes incorrect predicted CTE over the planned time horizon so the optimizer may not converge to the target path.

Original incorrect equation:
CTE = f(x) - y + (v * sin(epsi) * dt)

Corrected equation:
CTE = y - f(x) + (v * sin(epsi) * dt)

Please see this forum post for more details:
https://discussions.udacity.com/t/mistake-in-lessons-motion-equation-for-cte/458082

**Comment by baumanab** [comment]
This is interesting.  I implemented the corrected equation into my MPC project and it did seem to resolve some odd behavior.  We will look into this.

**Comment by baumanab** [comment]
Per our conversation [here](https://discussions.udacity.com/t/mistake-in-lessons-motion-equation-for-cte/458082/11) I will do some testing and then update the vehicle models and MPC content.

**Comment by edufford** [comment]
Thanks for checking into this!  I added some additional comments about switching the epsi equation instead of the CTE equation on the same forum thread [here](https://discussions.udacity.com/t/mistake-in-lessons-motion-equation-for-cte/458082/15).

**Comment by baumanab** [comment]
After reading over the entire thread and trying some different approaches to explanation. switching the y and f(x) terms is more practical to explain. It also is intuitive since what we really want is the y component.

**Comment by baumanab** [comment]
The content has been updated.
