### ISSUE TITLE
"Term 2, Markov Localization, 32. Obsvervation Model Probability" typo.

### ISSUE THREAD

**Issue by sunpochin** [udacity/sdc-issue-reports#1263]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/ad5439d9-cad4-447a-a6b4-6d3fc94186cd

quote: “if we have a high probability match (small difference between the pseudo range estimate and the observation measurement) and low probability match (small difference between the pseudo range estimate and the observation measurement),”

I think “low probability match” should be “LARGE” difference between the pseudo range estimate and the observation measurement?

**Comment by baumanab** [comment]
Thanks for catching this, it has now been corrected.
