### ISSUE TITLE
Term1 advanced lane finding lecture tracking visualization code bug

### ISSUE THREAD

**Issue by yangchunluo** [udacity/sdc-issue-reports#1264]
lecture link: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/c41a4b6b-9e57-44e6-9df9-7e4e74a1a49a

# Lecture code
In the following code after “And you’re done! But let’s visualize the result here as well”

```python
# Create an image to draw on and an image to show the selection window
out_img = np.dstack((binary_warped, binary_warped, binary_warped))*255
window_img = np.zeros_like(out_img)
# Color in left and right line pixels
out_img[nonzeroy[left_lane_inds], nonzerox[left_lane_inds]] = [255, 0, 0]
out_img[nonzeroy[right_lane_inds], nonzerox[right_lane_inds]] = [0, 0, 255]

# Generate a polygon to illustrate the search window area
# And recast the x and y points into usable format for cv2.fillPoly()
left_line_window1 = np.array([np.transpose(np.vstack([left_fitx-margin, ploty]))])  ## PROBLEM
left_line_window2 = np.array([np.flipud(np.transpose(np.vstack([left_fitx+margin, 
                            ploty])))])
left_line_pts = np.hstack((left_line_window1, left_line_window2))
```

# Problem
When generating the polygon, we should use the fitted X values based on the previous frame’s fit and ploty (plus and minus the margin), instead of the variable left_fitx, which denotes the area after the new fit in this frame.

# Correction
The correct code in the lecture should be (for left lane only):

```python
# Assume you now have a new warped binary image 
# from the next frame of video (also called "binary_warped")
# It's now much easier to find line pixels!
nonzero = binary_warped.nonzero()
nonzeroy = np.array(nonzero[0])
nonzerox = np.array(nonzero[1])
margin = 100
left_lane_inds = ((nonzerox > (left_fit[0]*(nonzeroy**2) + left_fit[1]*nonzeroy + 
left_fit[2] - margin)) & (nonzerox < (left_fit[0]*(nonzeroy**2) + 
left_fit[1]*nonzeroy + left_fit[2] + margin))) 

# Again, extract left and right line pixel positions
leftx = nonzerox[left_lane_inds]
lefty = nonzeroy[left_lane_inds] 
# Fit a second order polynomial to each
left_fit_new = np.polyfit(lefty, leftx, 2)    #### CHANGES HERE
# Generate x and y values for plotting
ploty = np.linspace(0, binary_warped.shape[0]-1, binary_warped.shape[0] )
left_fitx = left_fit_new[0]*ploty**2 + left_fit_new[1]*ploty + left_fit_new[2]
orig_left_fix = left_fit[0]*(ploty**2) + left_fit[1]*ploty + left_fit[2]
```

later the visualization code
```python
left_line_window1 = np.array([np.transpose(np.vstack([orig_left_fitx-margin, ploty]))])
left_line_window2 = np.array([np.flipud(np.transpose(np.vstack([orig_left_fitx+margin, 
                              ploty])))])
```

The result should be something like this picture:

<img src='https://cdn-enterprise.discourse.org/udacity/uploads/default/original/4X/0/c/1/0c1e7602742f17a67c739840425f2f2f71c6fcdf.jpg' />

You can see that the green search window is **not** parallel to the fitted curve.

**Comment by baumanab** [comment]
Thank you for investigating this.  Would you mind elaborating on why we should plot the fit from the previous frame?

**Comment by yangchunluo** [comment]
Sure. Let me explain. Here the goal is to track the lane line using the position (fitted curve coefficients) from the previous frame. The way tracking works is to search a window within a margin from such curve coefficients. We all know this.

The point for the visualization is to highlight such search window/area for diagnosis/debugging/illustration. Therefore, the green area should be based on previous frame's fit, not the current one. Otherwise, the green area would be exactly parallel to the current fitted curve, but it is not for the actual search window (which is based on the previous curve).

PS: here is the response from a forum mentor in response to the same issue on discussion board: https://discussions.udacity.com/t/a-bug-in-lecture-code-for-visualization-for-lane-tracking/486294/7 

Hope this helps.

**Comment by baumanab** [comment]
That makes sense, thanks for taking the time to explain it.  We can make some changes to in accordance with the above.

**Comment by mvirgo** [comment]
Just a quick note that this section has been changed into a quiz instead of just a code block on the related page. Still need to correct for the above though.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
