### ISSUE TITLE
error in markov equation

### ISSUE THREAD

**Issue by hacklavya** [udacity/sdc-issue-reports#1266]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/c12ca8a6-10d4-4f34-bcf6-6894fd9ceba2

**Comment by baumanab** [comment]
Thank you for reporting this. Would you mind specifying the error?

**Comment by hacklavya** [comment]
braces are like this in the equation:-
P()) = P()

**Comment by baumanab** [comment]
so they are :)  Thank you, this has now been corrected.
