### ISSUE TITLE
UDACITY Dataset1 Issue

### ISSUE THREAD

**Issue by rakeshakkineni** [udacity/sdc-issue-reports#1267]
The coordinates shared in the label.csv of UDACITY Dataset1(https://github.com/udacity/self-driving-car/tree/master/annotations) are not correct. 

Based on the coordinates shared i have plotted rectangles on the image. Following are results.

**Comment by rakeshakkineni** [comment]
Original Image: 1479498371963069978.jpg

![1479498371963069978.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a45ef731b8f0e0013421feb/125516c66e82c728ace21e0d46b9c0cd7ad6daf1dcbeee1af20ea0c2701f702b6b48e13b628ae92dbc56395b4d5a46ac485a564cfaaa8823f2b238228a5c0bedd76f5c26c72f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e68f894e361b051889ff5827ed.jpg)

Image with overlayed Rectangles:
![1479498371963069978_Mod.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a45ef731b8f0e0013421feb/125516c66e82c728ace21e0d46b9c0cd7ad6daf1dcbeee1af20ea0c2701f702b1629ac2f32c9a138ad4d71040c1b5ca6535d5744f5fb8023a0e53d78de580fbfd16d5f74c03f12feb99003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3f1a031981f95a32a09e49da15.jpeg)

Snapshot of Coordinates used for plotting the rectangles:
![Label.csv snapshot.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a45ef731b8f0e0013421feb/125516c66e82c728ace21e0d46c49598268ecdaa9cffff50aa5ce087214933316546b3397f8fe62bab0021435a574ea543515742aff8817fa2b26e708a5c0bebd36e0d75d42103eee9dc4be05ce36ade0d97bcae8b4bcae93824e38d8e47391c07118bfc4f78.JPG)

**Comment by mvirgo** [comment]
Thanks for point this out! The dataset isn't currently used in any projects, but we'll investigate how difficult it would be to update any inaccurate labels.

**Comment by mvirgo** [comment]
@rakeshakkineni Just to clarify - did you check out the revised version in the repository, as opposed to that in the zip file? The headers were the incorrect order.

**Comment by mvirgo** [comment]
Confirmed that the revised version in the repository [here](https://github.com/udacity/self-driving-car/blob/master/annotations/labels_crowdai.csv) is correct - I've now added a note right above the download link so that people will know.
