### ISSUE TITLE
Udacity - error in CarND

### ISSUE THREAD

**Issue by rjlutz** [udacity/sdc-issue-reports#1269]
I think there is a typo in Lesson 7 Module 9 (CTRV Process Noise Position). 

In question 2 of 2, shouldn't 
"Which of the above (👆) options represents the acceleration x offset of a car driving straight at time k+1?" 
be 
Which of the above (👆) options represents the acceleration **y offset** of a car driving straight at time k+1?

**Comment by baumanab** [comment]
Thanks for reporting this.  This has been corrected.
