### ISSUE TITLE
Udacity CarND typo

### ISSUE THREAD

**Issue by rjlutz** [udacity/sdc-issue-reports#1271]
In term2, Lesson 11, module 35, the source code in helpers.h has a comment:

	/*****************************************************************************
	 * normpdf(X,mu,sigma) computes the probability function at values x using the
	 * normal distribution with mean mu and standard deviation std. x, mue and 
	 * sigma must be scalar! The parameter std must be positive. 
	 * The normal pdf is y=f(x;mu,std)= 1/(std*sqrt(2pi)) e[ -(x−mu)^2 / 2*std^2 ]
	*****************************************************************************/

1) Shouldn't mue be mu?
2) Shouldn't y=f(x;mu,std) be y=f(x,mu,std)

**Comment by baumanab** [comment]
Yes, that is definitely the case, thanks for reporting.
