### ISSUE TITLE
Code Bug Report for Self-Driving Car ND Term 1 Project 5

### ISSUE THREAD

**Issue by Xiaohong-Deng** [udacity/sdc-issue-reports#1272]
In the sample code for 35 Hog Sub-sampling Window Search, in 44-45

    nxsteps = (nxblocks - nblocks_per_window) // cells_per_step
    nysteps = (nyblocks - nblocks_per_window) // cells_per_step

I think it should be

    nxsteps = (nxblocks - nblocks_per_window) // cells_per_step + 1
    nysteps = (nyblocks - nblocks_per_window) // cells_per_step + 1

I tried in my project 5 code, didn't give me index out of bound error, so I think I'm probably right.

**Comment by baumanab** [comment]
related to #819

**Comment by baumanab** [comment]
Thank you for letting us know about this.  This code was recently updated and the current code chunk in that region is:

`
 # 64 was the orginal sampling rate, with 8 cells and 8 pix per cell
    window = 64
    nblocks_per_window = (window // pix_per_cell) - cell_per_block + 1
    cells_per_step = 2  # Instead of overlap, define how many cells to step
    nxsteps = (nxblocks - nblocks_per_window) // cells_per_step + 1
    nysteps = (nyblocks - nblocks_per_window) // cells_per_step + 1
`
If this is not what you are seeing p;lease try refreshing your browser and resetting the quiz.  If that doesn't work, please let us know.
