### ISSUE TITLE
Improvements to instructions in new Markov Localization lessons in Term 2 lesson 11

### ISSUE THREAD

**Issue by CodingCanuck** [udacity/sdc-issue-reports#1275]
Copied from https://github.com/udacity/sdc-issue-reports/issues/1166#issuecomment-355839435

Minor nits in 2.11.23 Determine Probabilities:
1) The page references `norm_pdf` five times, and a comment in the code references `norm_pdf` once: these should be `normpdf` to match the code.

Minor nits in 2.11.25 Motion Model Probability II:
1) The Transition Probability quiz is a bit confusing: it references `norm_pdf` but doesn't say how/where to use it: I jumped back to the implementation in the prior lesson 2.11.23 before realizing that there was a fresh implementation at the bottom of the page. The implementation bellow on 2.11.25 is mentioned in the quiz grader, but not in the actual quiz instructions: maybe update the quiz instructions to say:
"Use `normpdf` (see implementation at the bottom of the page) to determine..."

2) The page references `norm_pdf` three times: this should be `normpdf` to match the code.

3) For the Reference Equations at the bottom of the page, the transition model equation is bulleted: it should probably not be bulleted to match the other 2 equations.

Minor nits in 2.11.26 Coding the Motion Model:

1) The instructions say "prints the results to standout": should "standout" be `stdout` or "standard output"? I've never heard the term standout used in this context before.

2) The default/empty implementation of motion_model has an extra closing curly brace, which doesn't compile:
```
float motion_model(float pseudo_position, float movement, std::vector<float> priors,
                   int map_size, int control_stdev) {

    //initialize probability
    float position_prob = 0.0f;
    
    //YOUR CODE HERE

    }  <----- this brace should be removed
    return position_prob;
}
```

**Comment by baumanab** [comment]
Wow, thanks for the thorough feedback.  We will start making changes shortly.

**Comment by baumanab** [comment]
Thanks again, these have all been addressed.
