### ISSUE TITLE
Link missing (404 error)

### ISSUE THREAD

**Issue by na6an** [udacity/sdc-issue-reports#1276]
T1, L2-Introduction, In sentence where it says "Backpropagation is the process by which neural networks update the weights of the network over time. (You may have seen it in >>>this video<<< earlier.)" Link to "this video" missing

**Comment by baumanab** [comment]
Thank you for reporting this.  Would you mind posting a link?  I wasn't able to find the link in question.

**Comment by na6an** [comment]
This is the [link to the lesson](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/c68259d2-7797-4fd3-b8f9-5936b2552ea4)

and this is the [link to the missing page](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/83a4e710-a69e-4ce9-9af9-939307c0711b/concepts/45cebfff-236d-453a-be24-7a179c1fa8ed) (pops up in address briefly and changes to "https://classroom.udacity.com/nodeNotFound")

**Comment by baumanab** [comment]
The link has been updated.
