### ISSUE TITLE
Lesson 18 (Vehicle Models) Part 10 (Errors)

### ISSUE THREAD

**Issue by mark5udacity** [udacity/sdc-issue-reports#1277]
The text is being displayed as plain-text, without any mathematical formatting applied, so it is somewhat hard to read, even having been familiar with LaTex, it's not clear what exactly is being said.

**Comment by mark5udacity** [comment]
This is for Term 2 under the Vehicle Model lectures. Actually, this is also found in Part 4 and several other lessons.

**Comment by kerys** [comment]
I noticed this too, it's also in some other lessons in term 2. I think something there broke recently, the math was displaying fine a few days ago.

**Comment by baumanab** [comment]
Wow, thanks for pointing this out.  Yes, this is happening in the localization lessons as well.  The classroom content has not changed, so it's possible something happened with the css.  We are now looking into it.

**Comment by baumanab** [comment]
This has now been corrected.
