### ISSUE TITLE
T2 L14 S18 Probability is Density

### ISSUE THREAD

**Issue by kerys** [udacity/sdc-issue-reports#1278]
The text mentions probability, but correct afaik is the term probability density. This may seem minor, but it confused me in the project since I was expecting a probability, i.e. a value between 0 and 1.

**Comment by baumanab** [comment]
Sorry for any confusion. A pdf also returns a value between 0 and 1 since the entire area under the curve of the pdf is unity. Typically the pdf is used to determine the probability between two bounds, that is, the probability of a slice.

**Comment by kerys** [comment]
> A pdf also returns a value between 0 and 1 since the entire area under the curve of the pdf is unity
You're right that the area is 1, but the probability density function P(x,y) as defined in the lecture may return values > 1, in particular for values close to mu and small sigma (as in the project). You can easily verify this by taking the weight quiz solution from the lecture and setting x_obs/y_obs to the mean, it will return 1.768 (see attached file).
The key point I want to make is that a probability density function returns a probability density, not a probability. For discrete random variables, this doesn't make a difference, but for continuous, it does.

[test.py.txt](https://github.com/udacity/sdc-issue-reports/files/1621472/test.py.txt)

**Comment by baumanab** [comment]
That is a very good point.  The language is the text and quizzes has been changed from probability to probability density.
