### ISSUE TITLE
Term 2 Lesson 15 Formula Mistakes

### ISSUE THREAD

**Issue by wkhattak** [udacity/sdc-issue-reports#1279]
Term 2: Lesson 5 > Part 14 on wards.

Various formulae are appearing in invalid format e.g. in part 14 :

"h(x')= \begin{pmatrix} \rho\\ \phi\\ \dot{\rho} \end{pmatrix} = \begin{pmatrix} \sqrt{ p{'}_x^2 + p{'}_y^2 }\\ \arctan(p_y' / p_x')\\ \frac{p_x' v_x' + p_y' v_y'}{\sqrt{p{'}_x^2 + p{'}_{y}^2}} \end{pmatrix}"

**Comment by wkhattak** [comment]
This is in the context of **Self-Driving Car Engineer** program.

**Comment by baumanab** [comment]
Thank you for reporting this.  It looks like something may have changed in the way equations and markdown are being rendered.  related to #1277

**Comment by baumanab** [comment]
All equations are now rendered.
