### ISSUE TITLE
Mentor Dashboard - Large time delay in sending messages

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#128]

**Comment by rm51** [comment]
I check messages in the mentor dashboard before I go to sleep and sometimes there are no messages. When I get up I check them again and I see sometimes that there are new messages that are over 10 hours old. But they weren't there when I went to sleep. This has happened several times. So it seems to me either the messages are being delayed when they're sent or else the time is wrong.

**Comment by swwelch** [comment]
Hi Renee! Is this still a problem for you?

**Comment by rm51** [comment]
No, it's working fine now. Thanks for checking.
