### ISSUE TITLE
T2 L14 S7: Unusual high velocity

### ISSUE THREAD

**Issue by kerys** [udacity/sdc-issue-reports#1280]
In the quiz, the car's velocity is 110 m/s which is around 400 km/h. Maybe you have some extra equipment in your Udacity car, but it seems pretty fast :-) I would suggest to stick to realistic values for quizzes. It doesn't make a mathematical difference, however I think it's important that students get a feeling for a reasonable range of domain specific variables.

**Comment by baumanab** [comment]
That is pretty fast.  Would you mind linking the content? I'm not finding this in T2 L14 S7.

**Comment by kerys** [comment]
Sure, it's in the Calculate Prediction Step Quiz at https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/ca98c146-ee0d-4e53-9900-81cec2b771f7

**Comment by baumanab** [comment]
This is a really high velocity, more like race car speed :) .  The point you make above is reasonable.  However, we are going to leave it for now, as this is a toy example to help students understand the particle filter approach.
