### ISSUE TITLE
Content in Term#3 lessons rendered incorrectly

### ISSUE THREAD

**Issue by dkhusial** [udacity/sdc-issue-reports#1283]
In Term #3, Lesson 4 part 12 (Example Cost Function), part 13 (Implement a Cost Function),  part 18 etc text is being rendered incorrectly, example as seen on part 13:
\text{cost} = 1 - e^{- \frac{|\Delta d|}{\Delta s}}

**Comment by baumanab** [comment]
Good catch, this has not been corrected.
