### ISSUE TITLE
Term 3: Lesson 3.10 (More on process models)

### ISSUE THREAD

**Issue by uppala75** [udacity/sdc-issue-reports#1284]
Formatting issue in lesson 3.10

**Comment by uppala75** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a58ffb1d56e120011b22cda/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb7b29d7ba70e9412a590b5b4afe41585f44fafb8a79a7a42062c80d55b98e30063e937f03a6aa8318b500bf218e488db4be8b49c6e83837aa.PNG)

**Comment by uppala75** [comment]
The content format is lost in lesson 3.10 in Term 3

**Comment by baumanab** [comment]
Thank you for reporting this, the equations are now rendered.
