### ISSUE TITLE
Term 3: Lesson 5.26 Equations not rendered correctly

### ISSUE THREAD

**Issue by fkeidel** [udacity/sdc-issue-reports#1285]
The equations in paragraph 'Tips' are not rendered correctly.
e.g.
s(t) = s_i + \dot{s_i}t + \frac{\ddot{s_i}}{2}t^2 + \alpha_3t^3 + \alpha_4t^4 + \alpha_5t^5

**Comment by baumanab** [comment]
Thank you for letting us know about this.  The equation now renders correctly.
