### ISSUE TITLE
T2, L18, S4: Lf defined incorrectly

### ISSUE THREAD

**Issue by kerys** [udacity/sdc-issue-reports#1288]
"Lf​ measures the distance between the front of the vehicle and its center of gravity. The larger the vehicle, the slower the turn rate."
This is not correct (some may say imprecise): It's not the distance to the front (as in bumper) of the vehicle, it's the distance between cog and the center of the front axle.

**Comment by baumanab** [comment]
Thanks for letting us know about this.  We were generalizing a little, I've updated with a more precise definition.
