### ISSUE TITLE
Typo in matrix element indices

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#129]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/8a3bfc88-5d3b-4003-a551-eda125c33995

There are mislabeled element indices in both X and W matrices in the lesson.

**Comment by domluna** [comment]
Sorry I'm not sure I follow. Which indices?

**Comment by gilcarmel** [comment]
The left column on both of these matrices. Unless I am missing something (wouldn't be the first time)!

![image](https://cloud.githubusercontent.com/assets/1276004/20068355/43065ed0-a4cd-11e6-9cee-e7d8c42ac4dc.png)

![image](https://cloud.githubusercontent.com/assets/1276004/20068373/5222269c-a4cd-11e6-8c19-58306cf33ad8.png)

**Comment by domluna** [comment]
Oops! You're right. Thanks!

**Comment by domluna** [comment]
Alright, should be good now.
