### ISSUE TITLE
MAC Simulator shows pink

### ISSUE THREAD

**Issue by hdelgado** [udacity/sdc-issue-reports#1290]
Whenever I ran the simulator I only see a pink screen after selecting the resolution. I downloaded the previous version and it works ok but does not have the second track.

**Comment by hdelgado** [comment]
![Screen Shot 2018-01-16 at 11.38.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5f65157b27df001280e4d8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f56b7191a379ee0c2859415c4bbc21254d58eeb9cb74fce36f34985619e8d96d5676cf3517ffb98a4bbb05e8208b4f85b0be891ec1fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae74f55a5113f63e6773e6e0a.png)

**Comment by hdelgado** [comment]
My MAC OS version

![Screen Shot 2018-01-17 at 10.03.55 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5f65157b27df001280e4d8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f46b7191a379ef0c2b52415a4bbc30254d58eeb9cb74fce36f34985619e8d96d5676cf3517ffb98a4bbb05e8208b4f85b0be891ec1fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae74f55a517336bee743f6e0a.png)

**Comment by baumanab** [comment]
hmm, that is unusual.  Does this occur for all resolutions?  Would you mind trying a few resolutions? In the meantime, I'll let the simulator lead know.

**Comment by hdelgado** [comment]
I tried with 3 at least with the same result, let me try all later on, I'll
ley you know

Thanks

**Comment by baumanab** [comment]
Thanks for checking. We are looking into this as well.

**Comment by hdelgado** [comment]
I tried with different combinations of resolution/quality with the same
result

**Comment by hdelgado** [comment]
Any updates? im still unable to do much

**Comment by baumanab** [comment]
I'm sorry, I don't have an update yet.  I'll check in again tomorrow.  Have you tried any of the vm/docker options?

**Comment by hdelgado** [comment]
I have the VM you provieded, but running the simulator inside the vm is not recommended by udacity ,due to  poor performance

**Comment by baumanab** [comment]
It sounds like you may not be the only one having this experience.  A colleague sent me this.  Would you mind trying to reset the shaders, per the link?

https://answers.unity.com/questions/639753/game-ok-in-editor-pink-screen-on-build.html

**Comment by baumanab** [comment]
after reading in a little more detail it sounds like this is something we will have to do on our side.

**Comment by hdelgado** [comment]
Ok, do you hace a rough estimate maybe? I have to work on my project before
the due date?

**Comment by hdelgado** [comment]
can I get a build with shaders reseted ?

**Comment by baumanab** [comment]
I don't think we have a build for that yet.  I neglected to ask, which version of the simulator is this?  Which term?

**Comment by hdelgado** [comment]
Hello

It's Term3 CarND-Capstone

**Comment by baumanab** [comment]
okay, that makes sense, thank you.

**Comment by baumanab** [comment]
The consensus here is that for the near term you probably won't be able to run the simulator and the ROS code within the vm. Some students have had luck with updating their OS.  I'm checking if it is necessary to use the second track.  If this is not necessary would it be possible to use the version of the simulator that does work, if the vm or OS update do not resolve the issue?

**Comment by baumanab** [comment]
the second track isn't necessary, and you don't need to use the latest simulator version if the old one works. Basically, the new simulator version just allows you to turn on/off the camera data (and provides a second track that is similar to the test lot). Are you in a team?

**Comment by aimllifetime** [comment]
having same issue here with same OS version OS X EI Capitan, version 10.11.6, I can run 
previous version of simulation v1.2 with no issue.

**Comment by aimllifetime** [comment]
meanwhile I try to upgrade OS to see if that works.

**Comment by aimllifetime** [comment]
upgrade to macOS High Sierra version 10.13.3 works

**Comment by baumanab** [comment]
Great, thank you for letting us know!  I'm going to close this issue out since upgrading appears to be the solution.  If that turns out not to be the case, we can re-open.
