### ISSUE TITLE
T2.L11.9 vector index out of bounds error in solution

### ISSUE THREAD

**Issue by kinergy** [udacity/sdc-issue-reports#1291]
The solution provided does not work in all cases. It works for landmark_positions {5, 10, 20}, but for example, it would break for landmark_positions {5, 10, 24} because 24+1 is an out of bounds index into the priors vector.

**Comment by baumanab** [comment]
Good catch!  In this case the map is size 25, which means our last index position is 24 and 24 + 1 does not exist. The solution was not meant to account for this as it is not the focus of this material. However, there are some options for extending functionality. Something that comes to mind is check the index + stdev against the map size and calling resize() in the map if we are out of bounds. Another option would be throwing a warning if the index + stdev is out of bounds. Does that make sense?
