### ISSUE TITLE
Lesson 1 Broken link in quiz

### ISSUE THREAD

**Issue by init27** [udacity/sdc-issue-reports#1292]
The link in the lesson 1 quiz on estimate of road vehicles by Business insider is giving a 404 error.

I tried to google for it and I believe they've removed the article. Even though you'd find links on google, they'd give the same 404 error.

**Comment by mvirgo** [comment]
Hello! What is the lesson and page name where this is occurring?

**Comment by init27** [comment]
Hey! 
It's in the Welcome section of the SDC-ND, at the the 11th part of it. 'Self Driving Car Quiz'

**Comment by baumanab** [comment]
Thanks for reporting this. The link is working or me, I'm wondering if this was a temporary outage or something having to do with locale.  Would you mind checking again?

**Comment by init27** [comment]
Nope, still doesn't work for me. 
Article:
https://www.businessinsider.in/report-10-million-self-driving-cars-will-be-on-the-road-by-2020-2015-5-6?r=US&IR=T
Classroom link:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/facdff19-61a5-47e4-8179-a6a5dc28987f/concepts/0d092adf-9f99-47c6-ac5f-a112fd238852

**Comment by baumanab** [comment]
This is the link I am getting. Does it work for you?


http://www.businessinsider.com/report-10-million-self-driving-cars-will-be-on-the-road-by-2020-2015-5-6

**Comment by init27** [comment]
<img width="1280" alt="screen shot 2018-01-23 at 8 49 19 pm" src="https://user-images.githubusercontent.com/16226196/35283699-fc2ece20-007e-11e8-9201-04c8398b83ea.png">
I'm getting a 404 error with this, please check this screenshot.

**Comment by baumanab** [comment]
If the link above doesn’t work it may be a system or locale issue. That is the link from the classroom and it resolved on my end on multiple computers and devices.

**Comment by init27** [comment]
I'm not sure. 
I tried with my phone and using different browsers Chrome+safari on both, didn't open. 
Might be a problem in India?

**Comment by baumanab** [comment]
It is likely locale then since it's hard to believe all those devices would have a system issue.  Sorry for this issue.  I'm going to close it out since it seems beyond our control
