### ISSUE TITLE
T1: L6: 33. Quiz: minibatch

### ISSUE THREAD

**Issue by DL-Floris** [udacity/sdc-issue-reports#1293]
not functioning properly. does not accept my solution (list comprehension) nor the solution given in quiz_solution.

**Comment by mvirgo** [comment]
Hi! Which quiz on this page are you referring to? I am unable to reproduce an error with these quizzes, including with the specific solutions provided. Please make sure you are setting the batch size in the second quiz.

**Comment by DL-Floris** [comment]
Hi

My mentor, sujay, was able to reproduce the error. It was in the first quiz, regarding the batch division.

Kind regards
Floris

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Jan 19, 2018 at 8:33 PM +0100, "Michael Virgo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! Which quiz on this page are you referring to? I am unable to reproduce an error with these quizzes, including with the specific solutions provided. Please make sure you are setting the batch size in the second quiz.

**Comment by baumanab** [comment]
Hi, thanks for following up on this.  I took a look at both coding quizzes and they are both accepting the solution from 'quiz_solution.py' It sounds like this hasn't been your experience.  Would you mind pasting the solutions you are using that are not working?  Would you mind elaborating on how your mentor reproduced the error?

**Comment by baumanab** [comment]
just to be sure, is the issue arising from the first coding quiz in the link below?

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/12ced01a-7de9-436b-9a7b-c13e67f2097b

**Comment by DL-Floris** [comment]
Hey Andrew

It seems like it was a temporary error. I have tried submitting my solution again and it works, as well as the provided solution in the solution.py file.

Maybe the compiler wasnt working properly for some time.

Here is my list comprehension by the way, if you're still interested (it's the same as the solution really.. )

output_batches = [[features[i:i+batch_size], labels[i:i+batch_size]]   \
                        for  i in range(0, len(features), batch_size)]

Thanks for looking to solve it.

Cheers
Floris
________________________________

**Comment by baumanab** [comment]
Thanks for letting us know, and I'm glad it worked out.
