### ISSUE TITLE
Linker error in c++ submission Behaviour Planner

### ISSUE THREAD

**Issue by kcjones99** [udacity/sdc-issue-reports#1294]

**Comment by kcjones99** [comment]
My test succeeds. When I submit the following error appears, there is a reference to a linker issue, but I'm not sure what the cause is for the error.

Try Again

File "", line 10, in 
  IndexError: list index out of range
  Environment: {'executor_result': {u'vm_time': 3.2474589347839355, u'stdout': u'', u'vm_creation_time': 6.9141387939453125e-05, u'test_results': [], u'stderr': u"vehicle.o: In function Vehicle::choose_next_state(std::map<int, std::vector<Vehicle, std::allocator<Vehicle> >, std::less<int>, std::allocator<std::pair<int const, std::vector<Vehicle, std::allocator<Vehicle> > > > >)':\nvehicle.cpp:(.text+0x6ce): undefined reference tocalculate_cost(Vehicle const&, std::map >, std::less, std::allocator > > > > const&, std::vector > const&)'\ncollect2: error: ld returned 1 exit status\n", u'exec_server_time': 3.2587580680847168, u'exec_status': u'ok'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'ok'}

**Comment by kcjones99** [comment]
Here is the code. The parameters are prioritizing reachgoal with 0.9 and the effeiciency with 0.1.
Thank you for the feedback.


    vector<string> possible_successors = successor_states();
    float c_cost, min_cost = 9998.0;
    vector<Vehicle> best_traj = generate_trajectory("KL", predictions);
    vector<Vehicle> traj;

    if (possible_successors.size() == 0) { return best_traj; }
    
    for (int i=0; i<possible_successors.size(); i++){
        //cout << possible_successors[i] << endl;
        traj = generate_trajectory(possible_successors[i], predictions);
        //cout << "traj size " << traj.size() << endl;
        Vehicle thisvehicle = *this;
        c_cost = 9999.0;
        if (traj.size()>0){
            c_cost = calculate_cost( thisvehicle, predictions, traj );
        }
      //cout << c_cost << endl;
        if (c_cost < min_cost) {
            min_cost = c_cost;
            best_traj = traj;
        }
    }

    return best_traj;

**Comment by baumanab** [comment]
Based on a review of the quiz, this does not appear to be a glitch.  All elements of the planner must be implemented (there are several files that need to be changed).  If you only do part of it the test will still run but the submission will not pass.  The output is the error message from the grader, which is in JSON format.  Would you mind taking another look and working with forum or classroom mentors to resolve?  If this does turn out to be an issue with the quiz, please let us know and we can reopen the ticket.

**Comment by rafahuaman** [comment]
I am getting a similar issue. My code is very similar in logic to the posted submission but it doesn't seem to matter. Copying the solution from the next section doesn't work either.
