### ISSUE TITLE
Loading protobuf files on Carla too slow

### ISSUE THREAD

**Issue by PhilippeW83440** [udacity/sdc-issue-reports#1295]
I have noticed that loading a protobuf file on Carla is very slow. Could you check this note/warning from Tensorflow: https://www.tensorflow.org/install/install_linux#python_36 (edited)
and upgrade this way:
   for Python 2.7:

 $ pip install --upgrade \
 https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.1.0-cp27-none-linux_x86_64.whl
Loading a pb file will be _much_ faster

**Comment by baumanab** [comment]
Thanks for letting us know about this.  We will review and will likely put a note in the classroom.

**Comment by mikkelkh** [comment]
@PhilippeW83440 suggests that you upgrade the protobuf package on the Carla vehicle.

Currently, loading a protobuf file takes so long that the car has already passed the traffic light (in the final project) when it's done initializing.
It would therefore help us and others if you upgraded the package instead of describing the limitations in the classroom.

**Comment by PhilippeW83440** [comment]
Please consider this as a bug fix: it is required to properly handle the submissions that are using protobuf format. It has no impact for people using other formats like hdf5, but today it is penalizing all submissions making use of .pb files. Loading the neural network is way too slow: it is still loading the .pb neural network while we are supposed to use it to detect the red light.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
