### ISSUE TITLE
T2_L18.11: Incorrect Link

### ISSUE THREAD

**Issue by vsingla2** [udacity/sdc-issue-reports#1296]
Below line mentions a paper, but is linked to another paper, I believe.

“Additional resources are linked to each lesson to encourage and enable more in-depth study. One of these resources makes a good case for the use of lower complexity kinematic models”

The correct link to paper in question is : http://www.me.berkeley.edu/~frborrel/pdfpub/IV_KinematicMPC_jason.pdf

**Comment by baumanab** [comment]
Thank you for noticing that, the link has been corrected.
