### ISSUE TITLE
Mistake in Term 3, Lesson 5, lecture 23 in video

### ISSUE THREAD

**Issue by volkodava** [udacity/sdc-issue-reports#1297]
There is a mistake in Term 3, Lesson 5, lecture 23 in final matrix equation: 6*T, 12T^2, and instead of 20T^5 should be 20T^3.

**Comment by baumanab** [comment]
Thank you for finding and reporting this error.  This has been added to our internal issue system (JIRA).

**Comment by mvirgo** [comment]
This is fixed now! Thanks again for the good catch.
