### ISSUE TITLE
T3, P1. frenet to xy is not as accurate when at curve turning place.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1298]
The original Frenet to x,y transform is not very accurate, vice versa. especially when car at curve turning place, the d will be on the lane line, rather that middle of lane.

**Comment by asimay** [comment]
![err.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ab0d78ebf77720002221c3/125516c66e82c728ace21e0d46ed868861cec1b99de6b546a749b2ce6b137f237056fa732686b270bb162f035f5f4eac475a5c16fdeb9539e4e76224d50152a7842f4d7ed43c18a6b9871eb808bc28894883b2bc8c5e8d.PNG)

**Comment by baumanab** [comment]
Thank you for pointing this out.  We may add a note in the classroom to let students know about this, so they are prepared to adjust.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
