### ISSUE TITLE
Term 1 Lesson 4 Section 29-30: Notation inconsistency

### ISSUE THREAD

**Issue by alex4men** [udacity/sdc-issue-reports#1299]
Please, fix the problem in the course materials, described in this forum discussion.
https://discussions.udacity.com/t/different-formula-in-4-30-and-4-29/496483

In T1L4S30 it is used completely different notation and formulas for the weight update, compared to the previous sections. And this transition is not obvious at all. 

Please, fix the formulas, or explain, where did they come from?

**Comment by alex4men** [comment]
Also in Section 30, why nn_output became equals sigmoid(x[0]*weights[0] + x[1]*weights[1])? Where is the b term?

**Comment by timeperceptron** [comment]
Same!

**Comment by Elgeweily** [comment]
Same here, wasted too much time trying to get my head around section 30, but I think there is a missing derivation there.

**Comment by mvirgo** [comment]
Hi all - 

We've updated this section to more clearly state the variables used, as well as the reason for the changes in the loss function. Let us know if you think it is still unclear!
