### ISSUE TITLE
Unclear answer in Hough Transform Quiz

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#13]
My photo is on the left. The only difference between my answer and that of the one of the right is that I am using a polygon instead of a trapezoidal region selection. It would be good if the answer could include more specific details about the trapezoidal region selection.

**Comment by rm51** [comment]
![houghlinesquiz](https://cloud.githubusercontent.com/assets/7563076/19628092/2bef3fd2-9924-11e6-96ad-ac628508cdd7.png)

**Comment by giladgressel** [comment]
actually what's more confusing is that the starter code in the quiz says "this time we are doing a polygon"  but in reality you need to change that code in order to mask it to a trapezoid, the way that is done in the answer

**Comment by rm51** [comment]
After adjusting the settings I was able to get it closer to the image on the right, but the answers for the other things specifically said the settings but not for that one. Yes I also agree with Gilad that part is unclear as well.

**Comment by ryan-keenan** [comment]
Thanks!  I've updated the quiz to be more clear (I hope!) and now in the answer text I specify the actual trapezoid I used.
