### ISSUE TITLE
Tensorflow lab - validation error (MR ready)

### ISSUE THREAD

**Issue by gawy** [udacity/sdc-issue-reports#130]

**Comment by gawy** [comment]
There is a validation error for labels array in TensorFlow lab

Current check does dimensionality check for None and 10, but that array can be either None or [None, 10]. Similar to how check is done for inputs.

I've created a MR on github to fix that issue

https://github.com/udacity/CarND-TensorFlow-Lab/pull/4

**Comment by Brok-Bucholtz** [comment]
@gawy 

Looks good!  I merged in the PR.
