### ISSUE TITLE
Update the Path Planning Project

### ISSUE THREAD

**Issue by beetleskin** [udacity/sdc-issue-reports#1300]
The current state of the Path Planning Project disappointed a lot of students. The [first Question in the Q&A of the walkthrough-video](https://youtu.be/7sI3VHFPP0w?t=3587) summarizes the main issues.

I suggest:
- clean up the starter code ([ref](https://github.com/sk-stm/CarND-Path-Planning-Project/commit/c6e38abef3fddb5f390ce772615c90bbdb35a964) for inspiration)
- link at least some topics from the lesson to the project by forcing the students to use some of the algorithms, e.g. 
-- behavior state machine
-- jerk minimizing trajectory
- give starter code for lesson topic algorithms (or update the quizzes such that one could use the code from there)

The experience of the other projects was much better as there was a seamless transition from the lessons to the project. That should be the goal here as well.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
