### ISSUE TITLE
Revise scikit-image HOG Quiz

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#1301]
This quiz (in the "Object Detection" lesson) has a solution that throws a deprecation warning. Also, the scaffolding and the solution are not DRY. Worth refactoring this into code that isn't largely repeated twice.

**Comment by baumanab** [comment]
Source of deprecation warning is fixed.

**Comment by baumanab** [comment]
The solution has been refactored and the scaffolding simplified.  Part of the challenge with this quiz is the library itself.  hog(...) returns either 1 or 2 elements, depending on params.  This makes incorporating it into robust functions a little clunky.  Addressing this is the main library sci-kit image library would be a great opportunity for some students to have a high impact pull request.
