### ISSUE TITLE
Update Color Classify Quiz

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#1303]
The Color Classify quiz (in the Object Detection lesson) should require finding the optimal set of parameters, using grid search.

**Comment by baumanab** [comment]
Hog classify should also be updated. The current quiz for each section encourages students to alter parameters to see the impact on metrics and training time. This is valuable and should be maintained. A separate quiz should be added to each to leverage grid search. Another approach would be randomized parameter search drawing from continuous distributions, which is a faster and more scalable approach.

**Comment by baumanab** [comment]
closed per https://udacity.atlassian.net/browse/DRIVE-4746
