### ISSUE TITLE
Search and Classify Quiz Error

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#1306]
This quiz throws an error due to `block_norm==L1` deprecation. Actually, several other quizzes in this lesson also throw this error.

**Comment by baumanab** [comment]
This comes from the default params of hog.py, on import:

```python
def hog(image, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(3, 3),
        block_norm=None, visualize=False, visualise=None, transform_sqrt=False,
        feature_vector=True, multichannel=None):
```

Working on a fix.

**Comment by baumanab** [comment]
Solution found.  Going to sweep the other quizzes for this issue and fix there as well.

**Comment by baumanab** [comment]
All quizzes fixed.  This deprecation warning can be addressed by changing all instances of hog(....) where a block_norm is not specified to `hog(...., block_norm= 'L2-Hys',.....)`
