### ISSUE TITLE
Perceptron lesson has logic error in explanation

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1309]
Lesson with title Perceptron II contains following text :

"These weights start out as random values, and as the neural network network learns more about what kind of input data leads to a student being accepted into a university, the network adjusts the weights based on any errors in categorization that results from the previous weights. "

In the example, the outcome of the NN is to decide if a student is accepted or not. The acceptation of the student is not however the criteria for success of that decision. It should be something like that student's success in university as a result of the decision taken by the NN. This doesn't make sense.

**Comment by EmilePapillon** [comment]
Lesson with title Perceptron II contains following text : 

"These weights start out as random values, and as the neural network network learns more about what kind of input data leads to a student being accepted into a university, the network adjusts the weights based on any errors in categorization that results from the previous weights. "

In the example, the outcome of the NN is to decide if a student is accepted or not. The acceptation of the student is not however the criteria for success of that decision. It should be something like that student's success in university as a result of the decision taken by the NN. This doesn't make sense.

**Comment by baumanab** [comment]
Hi, thank you for bringing this up.  Would you mind clarifying this assertion?  Are you saying that the NN only outputs classes "accepted", "not accepted" (or something similar), but that the NN tells us nothing about whether a student is successful at the University?  

The NN (actually a perceptron) is only designed to tell us about acceptance.  We don't have a data set that informs us on success of the student, only the acceptance decision.

**Comment by EmilePapillon** [comment]
I am sorry I had misread the text. Please close this issue. I thought the text was saying that the perceptron would adjust weights based on the student being accepted.

**Comment by baumanab** [comment]
Thanks for clarifying :)
