### ISSUE TITLE
miniFlow lesson 6 - linear node solution

### ISSUE THREAD

**Issue by bdholt1** [udacity/sdc-issue-reports#131]
In the provided solution

class Linear(Neuron):
    def __init__(self, inputs, weights, bias):
        Neuron.__init__(self, inputs)
        self.weights = weights
        self.bias = bias

    def forward(self):
        weighted_inputs = 0
        for n in range(len(self.inbound_neurons)):
            input_value = self.inbound_neurons[n].value
            weight = self.weights[n].value
            weighted_inputs += input_value * weight
        self.value = weighted_inputs + self.bias.value

the forward() pass is overly complex and not intuitive. Would you consider this alternative?

def forward(self):
        self.value = self.bias.value
        for w, x in zip(self.weights, self.inbound_neurons):
            self.value += w.value * x.value

**Comment by giladgressel** [comment]
love the alternative!

**Comment by domluna** [comment]
Updated to use your solution, much more concise :smile: . Thanks @bdholt1 !
