### ISSUE TITLE
Typeo in AOT & JIT Lessons

### ISSUE THREAD

**Issue by mark5udacity** [udacity/sdc-issue-reports#1310]
In Term 3, Lesson 11 Inference Performance, The 14th section on AOT & JIT compilation gives some code as an example.  

The code in error appears to be
config = tf.Config()

I believe tf.ConfigProto() is the correct method, particularly for the tensorflow version installed with the pre-built AMI.

**Comment by baumanab** [comment]
Thanks for the catch.  This has been corrected.
