### ISSUE TITLE
Lesson 6, part 6: typo

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1311]
In the "prediction step" part, the line:

"The update equation then becomes x′=F∗x"

should be:

"The PREDICTION equation then becomes x′=F∗x"

**Comment by baumanab** [comment]
Thank you for reporting this.  Would you mind linking the lesson?

**Comment by baumanab** [comment]
Nevermind, I found it.

**Comment by baumanab** [comment]
I think this was meant to say "the **updated** equation"  It has now been generalized to "the equation"
