### ISSUE TITLE
Expansion grid raises exception on submit

### ISSUE THREAD

**Issue by hvillanua** [udacity/sdc-issue-reports#1313]
In term 3, second lesson "Search", the expansion quizz grid reports "search raised an exception for:", even though the solution is the same as in the solution video.

**Comment by baumanab** [comment]
Sorry for the technical issues.  To help with troubleshooting, would you mind linking the quiz in question and posting the solution you submitted?

**Comment by hvillanua** [comment]
Quizz link: https://goo.gl/Ya9HHf
Solution (works when I press on test run, fails when submitting even using the same grid)
`
# -----------
# User Instructions:
# 
# Modify the function search so that it returns
# a table of values called expand. This table
# will keep track of which step each node was
# expanded.
#
# Make sure that the initial cell in the grid 
# you return has the value 0.
# ----------

from pprint import pprint

grid = [[0, 1, 1, 1, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 1, 0]]
        
init = [0, 0]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1

delta = [[-1, 0], # go up
         [ 0,-1], # go left
         [ 1, 0], # go down
         [ 0, 1]] # go right

delta_name = ['^', '<', 'v', '>']

def search(grid,init,goal,cost):
    # ----------------------------------------
    # modify code below
    # ----------------------------------------
    closed = [[0 for row in range(len(grid[0]))] for col in range(len(grid))]
    closed[init[0]][init[1]] = 1
    expand = [[-1 for y in range(len(grid[0]))] for x in range(len(grid))]

    x = init[0]
    y = init[1]
    g = 0
    visited = 1

    open = [[g, x, y]]

    found = False  # flag that is set when search is complete
    resign = False # flag set if we can't find expand

    while not found and not resign:
        if len(open) == 0:
            resign = True
        else:
            open.sort()
            open.reverse()
            next = open.pop()
            x = next[1]
            y = next[2]
            g = next[0]
            expand[x][y] = visited
            visited += 1
            
            if x == goal[0] and y == goal[1]:
                found = True
            else:
                for i in range(len(delta)):
                    x2 = x + delta[i][0]
                    y2 = y + delta[i][1]
                    if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                        if closed[x2][y2] == 0 and grid[x2][y2] == 0:
                            g2 = g + cost
                            open.append([g2, x2, y2])
                            closed[x2][y2] = 1
    return expand

pprint(search(grid,init,goal,cost))
`

**Comment by baumanab** [comment]
Thank you for providing more information.  I think the issue is related to this #896.  We are troubleshooting, but haven't been able to isolate and fix the issue with the grader.

**Comment by baumanab** [comment]
I’ve stepped through locally with a debugger, and tried to tie print statements to the debug outputs. They don’t reconcile. I’m wondering if there is layer we aren’t accounting for in the online (remote versions).

**Comment by baumanab** [comment]
This quiz has been moved into workspaces, and is now working.
