### ISSUE TITLE
Term2-Lesson12: Full Filter Solution bug

### ISSUE THREAD

**Issue by gandrein** [udacity/sdc-issue-reports#1314]
The solution provided for the 1D Full Bayes filter has a bug on line 86 in the else clause as shown below
```
        if (!sensor_obs[t].empty()) {
            observations = sensor_obs[t]; 
       } else {
            std::vector<float>observations {float(distance_max)};
       }
```

The newly created ```observations``` vector has local scope and is actually never passed to the ```observation_model``` function call on line 102. 

The correct usage would be
```
observations = std::vector<float>{float(distance_max)};
```

**Comment by baumanab** [comment]
Wow, great catch!  I did some debugging, and yes, the distance max was not being passed to the observation_model function.  Instead, 0 was being passed, which has a major impact on the results.  This was remedied by using:
```
observations = {float(distance_max)};
