### ISSUE TITLE
Suggested number of epochs takes too long to evaluate

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1315]
In item 15. of lesson 6. Miniflow, it is suggested that we try with 1000 epochs but 1000 epochs made the evaluation of my code fail because it took too long. I suggest reducing the number of suggested training epochs. I get error message "program shut down for using 13 CPU seconds."

**Comment by baumanab** [comment]
Good catch!  This section has been updated.
