### ISSUE TITLE
Term3 P2. testing data of different resolution.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1316]
there are about 23 pics of different resolutions with others, from um_000073.png to um_000095.png, they are not the same size with others. this will occur error in video clip. please see below.
clip pic error, it cannot show correctly, others are good.
![image](https://user-images.githubusercontent.com/8703449/36929203-8f9c191c-1ec8-11e8-9b36-7b168f03d217.png)

**Comment by baumanab** [comment]
Thanks for letting us know. We will take look and see how we can resolve.

**Comment by baumanab** [comment]
We aren’t sure this is a bug. Would you mind consulting forum mentors regarding this issue?  If the consensus is that it is a bug we will continue to pursue a resolution.
