### ISSUE TITLE
Term1 L5 P29 Lesson Grader Expects Array for Float Value

### ISSUE THREAD

**Issue by Rob-Crane** [udacity/sdc-issue-reports#1317]
Logistic Regression in module 29 of Lesson 5:

b, the bias term, is initialized as a float before becoming input to the gradient descent routine. However, if your implementation of gradientDescentStep returns it as a float, the code submission routine will fail. It has to become a 1x1 numpy array for the submission routine to accept. My line for updating b looks like:

b = b - steps[-1] #b is a numpy array, this code accepts
b = np.asscalar(b - steps[-1]) # b as a float, this code fails to accept
Both options work in the “Test Run” mode but the scalar will fail submission and give you an error about floats not having the __getItem__ attribute (and no stack trace…)

**Comment by baumanab** [comment]
Thanks for helping us troubleshoot. We will take a look at the grader code (test and grader code are not the same) to see what needs to be changed.

**Comment by baumanab** [comment]
Would you mind linking the quiz in question?

**Comment by Rob-Crane** [comment]
Strangely, I don't see the quiz anymore?  I looked all through the module to see if I reported the wrong lesson/module number.  I couldn't find anything that seems to match my memory.  It was an exercise to implement gradient descent for logistic regression.  Could the course material have changed?

**Comment by baumanab** [comment]
It's quite possible that the course content changed.  I looked for the quiz but was not able to locate it.  If you see this again, please post here and we will re-open.
