### ISSUE TITLE
Term1 L20  P12 Quiz Error message

### ISSUE THREAD

**Issue by na6an** [udacity/sdc-issue-reports#1319]
Error message "Oops, looks like you got an error!
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()" on the correct answer (double checked the error with provided solution)

The only possible location error is line 24 because that's the only place with if condition that could produce this type of error, but the logic on that line doesn't seem to be the problem.

**Comment by baumanab** [comment]
This is a common pandas error. I’m happy to help troubleshoot and to determine if this is a bug. Would you mind linking the quiz as well as posting the submitted code?

**Comment by na6an** [comment]
Link - https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/05b03f20-8c4b-453c-b41e-9fac590278c7/concepts/4f0692c6-e22d-4f28-b5d0-7990a4d8de86

Code (solution provided) -

import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

image = mpimg.imread('cutout1.jpg')

def color_hist(img, nbins=32, bins_range=(0, 256)):
    rhist = np.histogram(img[:,:,0], bins=nbins, range=bins_range)
    ghist = np.histogram(img[:,:,1], bins=nbins, range=bins_range)
    bhist = np.histogram(img[:,:,2], bins=nbins, range=bins_range)
    bin_edges = rhist[1]
    bin_centers = (bin_edges[1:]  + bin_edges[0:len(bin_edges)-1])/2
    hist_features = np.concatenate((rhist[0], ghist[0], bhist[0]))
    return rhist, ghist, bhist, bin_centers, hist_features
    
rh, gh, bh, bincen, feature_vec = color_hist(image, nbins=32, bins_range=(0, 256))

if rh is not None:
    fig = plt.figure(figsize=(12,3))
    plt.subplot(131)
    plt.bar(bincen, rh[0])
    plt.xlim(0, 256)
    plt.title('R Histogram')
    plt.subplot(132)
    plt.bar(bincen, gh[0])
    plt.xlim(0, 256)
    plt.title('G Histogram')
    plt.subplot(133)
    plt.bar(bincen, bh[0])
    plt.xlim(0, 256)
    plt.title('B Histogram')
    fig.tight_layout()
else:
    print('Your function is returning None for at least one variable...')

**Comment by baumanab** [comment]
I've done some reading on this as I'm accustomed to seeing this in pandas and numpy, but not matplotlib.  This is related to some strict rules in numpy, which come into play when using multiple plots (for example when all plots have the same label).  It's not clear what is causing the issue in this case, but we are looking into it.

**Comment by baumanab** [comment]
internal note: error has been isolated to execution code

**Comment by baumanab** [comment]
This was an interesting one, it turned out the following line was in the grading code:
`if  your_feature_vec == None:`

where `your_feature_vec` is an array generated from student code.  The comparison of a multi-element array to None is ambiguous.   Using this fixes the issue:

`if np.all(your_feature_vec == None):`
