### ISSUE TITLE
Send Response to Mentor button disabled

### ISSUE THREAD

**Issue by divya49** [udacity/sdc-issue-reports#132]
Send Response to Mentor button disabled is in login. I have not yet checked in with my mentor. I am not able to check in even after filling the questions

**Comment by swwelch** [comment]
Hi Divya, is this still a problem for you? There is a minimum character limit for messages to mentor, so that might be the cause of the problem. If you are still having problems, can you send a screenshot?

**Comment by dhruvp** [comment]
@divya49 checking in on this again. Is your problem still there?

**Comment by divya49** [comment]
Hi Dhuruv,

 The problem is resolved. I am able to send messages to my mentor now.

Divya

**Comment by dhruvp** [comment]
Great. Thanks for letting me know!
