### ISSUE TITLE
term 3, lesson 24, 12,

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1322]
look away node cannot run.

**Comment by asimay** [comment]
![image](https://user-images.githubusercontent.com/8703449/37080899-b0490a5a-2222-11e8-8423-39163647942c.png)

**Comment by baumanab** [comment]
That is a great suggestion, thank you @citlaligm.  @asimay , would you mind trying that?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
