### ISSUE TITLE
Term 3, L5, 6, A* Reminder Solution

### ISSUE THREAD

**Issue by stealthdaimma** [udacity/sdc-issue-reports#1323]
In Term 3 trajectory generation, 6. A* Reminder Solution, the instructor says that the solutions A* finds are always optimal.

HOWEVER, I've taken "AI for Robotics" course taught by Sebastian Thrun, and Sebastian said that  "A* may find a  suboptimal path" if the heuristic function h is not Admissible. 

https://classroom.udacity.com/courses/cs373/lessons/48532756/concepts/487024720923

This contradicts the answer given in the said Term 3 lesson. I think the answer should be corrected to false, and it should be mentioned that it may "not" be optimal if the heuristic function is Inadmissible.

**Comment by baumanab** [comment]
We should add that caveat, thank you!

**Comment by baumanab** [comment]
Changes have been made to the solution concept as well as the quiz, to clarify.
