### ISSUE TITLE
T1 L7 P33 Quiz doesn't verify training set and labels match

### ISSUE THREAD

**Issue by Rob-Crane** [udacity/sdc-issue-reports#1326]
Quiz is to define a function that produces batches of training and test data.  In keeping with spirit of good statistical practice, I shuffle the data before batching.  I noticed you can shuffle the features and labels separately (different shuffle orders) and still pass the quiz.

**Comment by baumanab** [comment]
This is a very good point.  I experimented with shuffling and tests for ensuring that features and labels align.  Ultimately it became computationally expensive to run the tests.  The best approach to this would probably be to create a new array and pass feature and label sets into that array, then shuffle.  This way the stay together.
