### ISSUE TITLE
T1 L7 P36 TensorFlow Conda Environment breaks TensorFlow import

### ISSUE THREAD

**Issue by Rob-Crane** [udacity/sdc-issue-reports#1327]
The environment.yml included in the TensorFlow Lab lists an old version of protobuf.  If this version is installed in the environment, then "import tensorflow" fails.  Removing the protobuf=... line from environment.yml fixes the problem.

**Comment by baumanab** [comment]
Thanks for reporting this, the issue has been fixed.
