### ISSUE TITLE
T1 L5.5: "Linear regression will lead to neural networks": replace with "logistic regression will lead to..."

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#1328]
Since the previous paragraph introduces logistic regression, and the previous page covered linear regression, I think the sentence:
>Linear regression will lead to neural networks, which is a much more advanced classification tool.

Means to say that logistic regression will lead to neural networks.  Also, logistic regression does classification, linear regression predicts a continuous value.

**Comment by e7dud7e** [comment]
Or, one can say "linear regression leads to logistic regression, which leads to neural networks..."

**Comment by baumanab** [comment]
This has been a very active area of discussion.  Would you mind reviewing the following posts and letting us know what you think?

#795 #1111 #943

**Comment by e7dud7e** [comment]
Oops, sorry I didn't find these other posts in my search.  I still think given that the topic of this page is "linear to logistic regression", it might help to say "linear regression leads to logistic regression, which leads to neural networks..." so that students can make that intuitive connection and see why they're learning these two concepts first, in this order.  Thanks!

**Comment by baumanab** [comment]
No worries on not researching other posts, I just wanted to loop you into the state of this discussion.  This is a good suggestion.  :)

**Comment by baumanab** [comment]
This has been updated.

**Comment by e7dud7e** [comment]
Cool, I see it. Looks good!
