### ISSUE TITLE
T1 L5.15: "Perceptron Algorithm": change video text from "Change w_i + ax_i" to "Change w_i to w_i + ax_i"

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#1329]
The text in the video says:

"Change w_i + ax_i".

I recommend this to match what Luis is saying in the audio.
"Change w_i to w_i + ax_i".

**Comment by e7dud7e** [comment]
same with the following line in the video:
"Change w_i - ax_i".

I recommend this to match what Luis is saying in the audio.
"Change w_i to w_i - ax_i".

**Comment by baumanab** [comment]
Good catch!  This is entered into our internal ticket system.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
