### ISSUE TITLE
Error in part 30 of Lesson 15: Advanced techniques for lane finding ( Term 1)

### ISSUE THREAD

**Issue by var7** [udacity/sdc-issue-reports#1330]
The current form of the code outputs a black image when run as in. 

import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

image = mpimg.imread('bridge_shadow.jpg')

# Edit this function to create your own pipeline.
def pipeline(img, s_thresh=(170, 255), sx_thresh=(20, 100)):
    img = np.copy(img)
    # Convert to HLS color space and separate the V channel
    hls = cv2.cvtColor(img, cv2.COLOR_RGB2HLS).astype(np.float)
    l_channel = hls[:,:,1]
    s_channel = hls[:,:,2]
    # Sobel x
    sobelx = cv2.Sobel(l_channel, cv2.CV_64F, 1, 0) # Take the derivative in x
    abs_sobelx = np.absolute(sobelx) # Absolute x derivative to accentuate lines away from horizontal
    scaled_sobel = np.uint8(255*abs_sobelx/np.max(abs_sobelx))
    
    # Threshold x gradient
    sxbinary = np.zeros_like(scaled_sobel)
    sxbinary[(scaled_sobel >= sx_thresh[0]) & (scaled_sobel <= sx_thresh[1])] = 1
    
    # Threshold color channel
    s_binary = np.zeros_like(s_channel)
    s_binary[(s_channel >= s_thresh[0]) & (s_channel <= s_thresh[1])] = 1
    # Stack each channel
    # Note color_binary[:, :, 0] is all 0s, effectively an all black image. It might
    # be beneficial to replace this channel with something else.
    color_binary = np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary)) * 255
    return color_binary

    
result = pipeline(image)

# Plot the result
f, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 9))
f.tight_layout()

ax1.imshow(image)
ax1.set_title('Original Image', fontsize=40)

ax2.imshow(result)
ax2.set_title('Pipeline Result', fontsize=40)
plt.subplots_adjust(left=0., right=1, top=0.9, bottom=0.)

Changing the line color_binary = np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary)) * 255
to color_binary = np.uint8(np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary)) * 255) works fine. Or removing the .astype(np.float) in the hls = cv2.cvtColor(img, cv2.COLOR_RGB2HLS).astype(np.float) works fine as well

**Comment by mvirgo** [comment]
Thanks for reaching out! As noted in the code comments therein `# Note color_binary[:, :, 0] is all 0s, effectively an all black image. It might be beneficial to replace this channel with something else.` Part of the point of the quiz is actually to have the student play around with this.

**Comment by var7** [comment]
I understand that. However, the code does not work in that form. Even if the first channel is all black, stacking all three of them should not produce a completely black image which is what it currently does. Please have a look in the forums as well, it wasn’t only me that had this problem.
