### ISSUE TITLE
T1 L5.23: error formula is missing horizontal division line between 1 and m

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#1332]
The error formula written in latex has 1/m written as 1 over an 'm'; i don't see the horizontal division line between them.

**Comment by mvirgo** [comment]
Nice catch! It's actually a display issue on our classroom backend with certain size of Latex equations not showing the division line - have passed onto our classroom team, but unfortunately not fixable on SDC's end.
