### ISSUE TITLE
term3 P4 launch styx.launch error.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1333]
roslaunch styx.launch

![image](https://user-images.githubusercontent.com/8703449/37454218-f5683e6e-2874-11e8-8fa3-51a09f4249ee.png)

**Comment by asimay** [comment]
the several files format seems wrong if I use git to download to windows platform.

**Comment by baumanab** [comment]
Hmm I’m wondering if these are larger files stored with LFS (won’t work with zip download). I’ll look into it.

**Comment by baumanab** [comment]
Does everything work if you clone the repo rather than downloading it?

**Comment by asimay** [comment]
still the same . I transform the file format to unix format, that works.

**Comment by asimay** [comment]
I think you need to transform all the file to unix format

**Comment by baumanab** [comment]
That is interesting.  I've seen this happen before with github repos and windows.  Would you mind describing the process you use to convert?

**Comment by baumanab** [comment]
Are you changing the [line endings](https://coderwall.com/p/dzdw_a/converting-line-endings-from-dos-carriage-returns-to-unix-line-feeds-using-git)?

**Comment by asimay** [comment]
yes. but i used other tools, dos2unix
