### ISSUE TITLE
Missing plt.show() in examples

### ISSUE THREAD

**Issue by amakukha** [udacity/sdc-issue-reports#1337]
This is a very minor bug, but might confuse some users.

Throughout the "Lesson 2: Computer Vision Fundamentals" code samples for "5. Region Masking", "6.Color and Region Combined" and others do not show the resulting images. Needed to add plt.show() in the end.

Only the "3. Color Selection Code Example" works just fine as is.

(I'm running Python 3.6.3 on Kubuntu 17.10 machine, matplotlib version 2.2.2)

**Comment by baumanab** [comment]
Thank you for reporting this.  Are these blocks not working on your system?

```python
# Display the image
plt.imshow(region_select)
```

```python
# Display our two output images
plt.imshow(color_select)
plt.imshow(line_image)
```

**Comment by amakukha** [comment]
These do not show the window, I needed to add plt.show() after each three of those to see a window with the images.

**Comment by baumanab** [comment]
Thanks for clarifying, we will update the classroom code.

**Comment by baumanab** [comment]
I've updated the code to include a comment regarding plt.show().  Out of curiosity are you using any particular IDE or shell?

**Comment by amakukha** [comment]
@baumanab , thanks.  I use Vim.

**Comment by baumanab** [comment]
vim and tmux FTW, I was just checking because some IDEs can cause plotting
issues.
