### ISSUE TITLE
First 2 quizzes in Lesson 9 (Fully convolutional Neural Networks don't work)

### ISSUE THREAD

**Issue by josealb** [udacity/sdc-issue-reports#1338]

**Comment by baumanab** [comment]
Thanks for reporting this. Would you mind linking the quizzes and describing what is wrong with them?

**Comment by baumanab** [comment]
I looked at the quizzes and they do appear to be working.  The quizzes I looked at are "number of parameters" and "convolution output shape".  Are these the quizzes you are referring to?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
