### ISSUE TITLE
sigmoid backpropogation solution does not match nn.py

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#134]
When I plug in the solution to Sigmoid.backward() from here:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/db18966a-23fa-4810-80b3-9ef1670f2d63

Into the previous quiz, the results do not match  what the comments in nn.py say they should be.

Comments say:
"""
You should see a list of gradients on the weights and bias that looks like:
[array([[  6.08973702e-08,   6.93800843e-02],
       [  1.21794740e-07,   1.38760169e-01]]), array([ -6.08973702e-08,  -6.93800843e-02])]
"""

Observed results:
[array([[  6.79488741e-18,  -2.67826355e-12],
       [  1.35897748e-17,  -5.35652711e-12]]), array([ -6.79488741e-18,   2.67826355e-12])]

**Comment by domluna** [comment]
Thanks @gilcarmel I'll look into it.

**Comment by domluna** [comment]
Updated to reflect what the actual values should be

```
[array([[ 6.08973702e-08, 6.93800843e-02],
[ 1.21794740e-07, 1.38760169e-01]]), array([ -6.08973702e-08, -6.93800843e-02])]
```

These values were calculated incorrectly. It's now 

```
[array([[  6.79488741e-18,  -2.67826355e-12],
       [  1.35897748e-17,  -5.35652711e-12]]), array([ -6.79488741e-18,   2.67826355e-12])]
```
