### ISSUE TITLE
Error in code in Lesson 15: Advanced Techniques for Lane Finding, #33. Finding the Lines

### ISSUE THREAD

**Issue by sameha** [udacity/sdc-issue-reports#1340]
In the code for 'Implement Sliding Windows and Fit a Polynomial':

histogram = np.sum(binary_warped[binary_warped.shape[0]/2:,:], axis=0)

should be:

histogram = np.sum(binary_warped[binary_warped.shape[0]//2:,:], axis=0)

**Comment by baumanab** [comment]
Thank you for reporting this. Which version of python are you using?

**Comment by sameha** [comment]
Python 3.6.4

**Comment by baumanab** [comment]
thanks for clarifying.  This is a python 2 vs. python 3 issue (they handle division differently).  We will update so that the code works in both 3.x and 2.x

**Comment by baumanab** [comment]
Division operators have been updated and should exhibit the same behavior in python 2 and 3.  [Here](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html) is a great article on differences in python 2 and 3, including the behavior of division operators.
