### ISSUE TITLE
Term 2, Lesson 12, Part 9, Solution Initialize Priors Function

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1342]
The given solution is not correct.

* First of all, it doesn't take any boundaries into account
* The function assumes that control_stdev == 1, because only the positions immediately next to a landmark are initialized with 1.0 / normalization_term
* No overlaps have been taken into account

A better solution would be:

std::vector<float> initialize_priors(
    int map_size, 
    std::vector<float> landmark_positions,
    float control_stdev) 
{
    std::vector<float> priors(map_size, 0);
//initialize priors assumimg vehicle at landmark +/- 1.0 meters position stdev

    const float landmark_prob = 1.f / (landmark_positions.size() * ((int) control_stdev * 2 + 1));

    for (const float landmark_position : landmark_positions)
    {
        const unsigned int control_stdev_min_idx =
            max(0, (int) (landmark_position - control_stdev));
        const unsigned int control_stdev_max_idx = 
            min(map_size - 1, (int) (landmark_position + control_stdev));
        for (unsigned int idx = control_stdev_min_idx; idx <= control_stdev_max_idx; ++idx)
        {
            priors[idx] += landmark_prob;
        }
    }
    
    return priors;
}

**Comment by baumanab** [comment]
Thank you for the very detailed feedback and solution suggestion!  The current quiz set (coding and concept quizzes) is intended to build familiarity with Bayesian filters through the combination of hand calculations and realization of those calculations in code.  As such we did not pursue overlap and boundaries.  It may be worth implementing at some point and we will consider that.

With respect to this item:

> The function assumes that control_stdev == 1, because only the positions immediately next to a landmark are initialized with 1.0 / normalization_term

The control_stdev is not an assumption but is rather defined 1.0 for purposes of this example.  That dictates initialization at a landmark +/- 1.0/normalization term.  Does tha make sense?

**Comment by benenaes** [comment]
OK, but maybe this could be pointed out in the comments. Because if control_stdev would be e.g. 2, then:

        priors[landmark_center] = 1.0f/normalization_term;
        priors[landmark_center - 1] = 1.0f/normalization_term;
        priors[landmark_center + 1] = 1.0f/normalization_term;

would have to become:

        priors[landmark_center] = 1.0f/normalization_term;
        priors[landmark_center - 2] = 1.0f/normalization_term;
        priors[landmark_center + 2] = 1.0f/normalization_term; 
        priors[landmark_center - 1] = 1.0f/normalization_term;
        priors[landmark_center + 1] = 1.0f/normalization_term;

**Comment by baumanab** [comment]
That is a good point.  A better approach for the solution would probably be initializing priors based on the control standard deviation.

**Comment by baumanab** [comment]
A note has been added to the quiz solution.
