### ISSUE TITLE
Term 2, Lesson 12, Part 36, Solution: Coding the Observation Model

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1343]
I think the approach of when there is no pseudo range available anymore to choose distance_max as a replacement, is not entirely well chosen.

Suppose there are a couple of observations around max_distance, but no pseudo_range elements are available. The provided solution will return a high probability for this situation.

Imho, a better approach would be to calculate a distance based on each pseudo_range and each observation and let that distance be max_distance if no pseudo_range is available.

The normpdf can then be used this way:

    float distance_prob = 1.f;

    //YOUR CODE HERE
    for (unsigned int i=0; i < observations.size(); ++i)
    {
        const float distance = (i < pseudo_ranges.size()) 
            ? pseudo_ranges[i]
            : distance_max;
        std::cout << i << " " << observations[i] << " " << distance << std::endl;
        distance_prob *= Helpers::normpdf(distance, observations[i], observation_stdev);
    }
       
    return distance_prob;

**Comment by benenaes** [comment]
The proposed solution should be:

    float distance_prob = 1.f;

    //YOUR CODE HERE
    for (unsigned int i=0; i < observations.size(); ++i)
    {
        const float distance = (i < pseudo_ranges.size()) 
            ? observations[i] - pseudo_ranges[i] 
            : distance_max;
        // std::cout << i << " " << observations[i] << " " << distance << std::endl;
        distance_prob *= Helpers::normpdf(distance, 0, observation_stdev);
    }
       
    return distance_prob;

**Comment by benenaes** [comment]
Also, the landmark that have been passed by (non-positive distances) should play a role.

**Comment by baumanab** [comment]
Thank you for troubleshooting.  This is a good point regarding no pseudo range and observations around distance max.  In terms of non-positive ranges, this is a constraint of the problem, it's fine to do either way.

**Comment by baumanab** [comment]
I'm looking into potential changes to the code now.  Yes, there are two additional probabilities in the current version.

**Comment by baumanab** [comment]
This is a good solution and it definitely works.  The classroom has been updated with a different approach:

``` //no or negative distances: set min distance to a large number:
    else {

        pseudo_range_min = std::numeric_limits<const float>::infinity();

    }
```
