### ISSUE TITLE
Term 2, Lesson 12, Part 37, Coding the full filter

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1344]
Regarding the following part of the given code:

if (!sensor_obs[t].empty()) 
        {
            observations = sensor_obs[t]; 
        } 
        else 
        {
            std::vector<float>observations {float(distance_max)};
        }

The else statement is useless here as it goes immediately out of scope.

**Comment by baumanab** [comment]
Thank you for input.  I'm not sure I completely follow, would you mind clarifying?  The observations vector from the else statement appears to be in scope and is passed to the `observation_prob` function.

**Comment by benenaes** [comment]
std::vector < observations > {float(distance_max)};

is defined locally in the else statement. Therefore, it goes immediately out of scope: it gets cleaned up after the curly brace of the else statement.

**Comment by baumanab** [comment]
Would you mind verifying this with cout statements? I did that last night, in the classroom, and `observations` exists outside the if else block, including the cases where observations is distance_max.

**Comment by benenaes** [comment]
There is already a std::vector<float> observations defined on line 71. It is perfectly possible to define a new variable with an existing variable name within a nested scope. But, it's lifeline will also cease when you leave the scope.
The one you have printed out, will be the one defined outside the else statement.

You can try this by initializing both variables with different values and printing out the values. Define the second one without the else statement, but just using a nested scope, so you're sure that the second variables is instantiated as well (regardless of the condition).

So:

    std::vector<float> observations(1, float(5));
    std::cout << "1:" << observations[0] << endl;
    
    //cycle through time steps
    for (unsigned int t = 0; t < time_steps; t++)
    {
        {
            std::vector<float>observations {float(distance_max)};
            std::cout << "2:" <<  observations[0] << endl;
        }

        std::cout << "3:" << observations[0] << endl;
   }

**Comment by baumanab** [comment]
I see the issue now and you are absolutely correct.  Thank you for your patience.  I had two versions of the code.  The solution code used `observations = {float(distance_max)};` which passe the value into the in scope vector from the loop.  The starter quiz code incorrectly used the code you posted above.  Nice catch!  The error has been corrected.
