### ISSUE TITLE
Term 1 - Miniflow - Under the Hood Part 2

### ISSUE THREAD

**Issue by tncalpmn** [udacity/sdc-issue-reports#1345]
I believe the matrix multiplication from G o W.T (where G:(2x1) and W.T:(1x2)) should result to a 2x2 matrix. However partial derivative of the gradient is shown as 2x1 Matrix = 
[(g1*w1 + g1*w2)
(g2*w1 + g2*w2)]

I think the plus signs "+" there needs to be changed with comma ",". So the resulting matrix would result 2x2?

**Comment by mvirgo** [comment]
Nice catch - you're correct. Updated!
