### ISSUE TITLE
Term 1 - Lesson 5 - 25 Cross-Entropy 2 - Incorrect probabilities

### ISSUE THREAD

**Issue by miguelangel** [udacity/sdc-issue-reports#1346]
Hi,

I think I have caught a small type in this video:

https://youtu.be/1BnhC6e0TFw?t=5m14s.

I think that the correct formula for the second example should be:
> CE[0,0,1), (0.2,0.3,0.1)] = 5.12
instead of:
> CE[0,0,1), (0.8,0.7,0.1)] = 5.12

Hope it helps!

Miguel Ángel

**Comment by baumanab** [comment]
Thanks for reporting this. We will flag the video for correction.

**Comment by mvirgo** [comment]
This video is actually correct - remember, you use the *1-p* where *y=0*, so effectively you are actually taking the ln of 0.2, 0.3 and 0.1 when the y values are 0, 0, 1, even though the probabilities are 0.8, 0.7 and 0.1. Thanks again for the report!
