### ISSUE TITLE
term 3 capstone project

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#1348]
I noticed there are walkthrough video add in. but no english subtitle in it. could you add it? thanks.

**Comment by baumanab** [comment]
Thank you for reporting this.  It does look like some of the walkthrough content is missing English subtitles.  We are working to add these in.

**Comment by baumanab** [comment]
We now have English subtititles for all but one video.  For some reason, that one is taking longer.

**Comment by baumanab** [comment]
All English subtitles are now ready.
