### ISSUE TITLE
ROS look_away script

### ISSUE THREAD

**Issue by hvillanua** [udacity/sdc-issue-reports#1349]
Script doesn't work as explained in the lesson. Arm stays pointing to ceiling, it appears to be a timing issue as described here (workaround included): https://discussions.udacity.com/t/look-away-not-executing-automatically-with-roslaunch/360557/4

**Comment by baumanab** [comment]
Thanks for reporting this and for the work-around. We will update the classroom accordingly.

**Comment by baumanab** [comment]
The classroom has been updated with information from the thread and a link to the thread.
