### ISSUE TITLE
Sigmoid backpropogation quiz always passes

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#135]
When I submit the quiz from this page, it always passes - there doesn't seem to be a real test running on it:

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/8f123f20-56b2-46c0-ae0b-8761e12a10a6

**Comment by cameronwp** [comment]
Thanks for reporting! I believe the issue stemmed from changes I made to `miniflow` that were not copied correctly here. Whoops.

Should be fixed now.
