### ISSUE TITLE
parse error in T3 simulator

### ISSUE THREAD

**Issue by danieledema** [udacity/sdc-issue-reports#1351]
Hello,
while trying to run the PathPlanning project, I get the arror:
```bash
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected number literal; expected string literal
Aborted (core dumped)
```

This happens running the simulator with the just cloned code.
I experienced locale problems in the last projects, but setting the locale to US does not fix the issue.

Besides, here is the first and last message I receive from the simulator:
```
"telemetry",{"d":164833,"end_path_d":0,"end_path_s":0,"previous_path_x":[],"previous_path_y":[],"s":8336,"sensor_fusion":[[0,775,99,1421,6,0,0,6721,839,-277,6729],[1,775,8,1425,2,0,0,6719,219,-280,1494],[2,775,8,1429,0,0,6716,599,-282,9019],[3,775,8,1432,9,0,0,6713,911,-285,7268],[4,775,8,1436,3,0,0,6711,566,-288,1896],[5,775,8,1441,7,0,0,6661,772,-291,7797],[6,762,1,1421,6,0,0,6711,778,-268,964],[7,762,1,1425,2,0,0,6709,296,-270,7039],[8,762,1,1429,0,0,6663,543,-273,1828],[9,762,1,1432,9,0,0,6660,444,-275,5511],[10,762,1,1436,3,0,0,6657,743,-277,6157],[11,762,1,1441,7,0,0,6653,453,-280,8947]],"speed":0,"x":48,"y":67,"yaw":0}]
```

Thank you very much,
Daniele

**Comment by baumanab** [comment]
Sorry for the technical issues and thanks for reporting this.  This is unusual.  The JSON object certainly looks correct.  I've let the team know and we will look into it.

**Comment by danieledema** [comment]
Small update: running the simulator inside the same docker container (udacity/control_kit) seems to solve the issue, although my laptop is not performant enough to let it run smoothly or even closer in that way.

**Comment by baumanab** [comment]
closing issue for now since there is a solution.  We can investigate further with os and other information.
