### ISSUE TITLE
Term 2, Lesson 15, Part 11: Update Step

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1352]
The yellow ovals in the video (around 2:20) are not correct (the ones depicting the uncertainty of the measurements). If the sigma_xx is large, then the uncertainty in the x direction should be large. As the video explains, the x axis points to the heading of the car. The middle oval (where sigma_xx is large than sigma_yy) has a semimajor axis in the y direction: thus more uncertainty in the y direction. This is contradictory.

**Comment by baumanab** [comment]
Thank you for letting us know about this.  You are correct in this assertion.  Essentially, the point of view is that of the map.  Does the note below the video help clarify at all?  That note was entered after another student pointed this out.

**Comment by benenaes** [comment]
OK, this is fine. I didn't notice this.
