### ISSUE TITLE
Term 2 , Lesson 15 : Implementation of particle filter :Converting Landmark Observations

### ISSUE THREAD

**Issue by Nk911** [udacity/sdc-issue-reports#1354]
Description in Footnote and the image shown below footnote are conflicting in lesson 
 Implementation of particle filter chapter Converting Landmark Observations https://classroom.udacity.com/nanodegrees/nd013-connect/parts/7dc7c9b7-2884-4e43-bf15-2d1e1a121081/modules/9688ee0e-ef68-4a26-ae60-c4b24eae8e6f/lessons/e235f8c9-e3ab-472f-be41-bc4b04b27dbf/concepts/b7e42c04-8d1b-4631-a3ba-e74d4122cd59

**Comment by Nk911** [comment]
![Term2_SDC_Issue.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf13a2e0b6c200104a7ad6/125516c66e82c728ace21e0d46dc91882ed0bc9aabca806ab74ee5916b0a65633b0ba92e7391a172fd172351565d47a4470b5e4ca8fd8d79a6b63c708c5e08bfd07f4366846c4ff8e7df46f554f832815d84b0b68b49c2eb3827e78d894e3718000ac4.JPG)
![Term2_SDC_Issue_2_Image.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf13a2e0b6c200104a7ad6/125516c66e82c728ace21e0d46dc91882ed0bc9aabca806ab74ee5911614185a2405a42e32c9a138ad4d71040c1b5ca6535d5744f5fb8023a0e53d78de580fbfd16d5f74c03f12feb99003ad43eb7edf10d8eff6df0ed2e22f27e6818e4a3c1d001a89f85e33a49d4cda15.JPG)

**Comment by baumanab** [comment]
Nice catch!  We will correct this.

**Comment by baumanab** [comment]
This has been corrected.
