### ISSUE TITLE
Video in ODlab does not work Windows10

### ISSUE THREAD

**Issue by rameshmisra** [udacity/sdc-issue-reports#1357]
Perhaps a codec issue, but did not have a problem with videos in term1. The driving.mp4 file did not run in firefox or MS Edge (from the AWS link), nor did the downloaded file run in Windows Media Player, etc.

**Comment by baumanab** [comment]
Would you mind linking the video in question?

**Comment by rameshmisra** [comment]
It is the driving.mp4 file here: https://github.com/udacity/CarND-Object-Detection-Lab

**Comment by baumanab** [comment]
does it work from within the notebook?  I don't recall the video needing to run in media player etc. to complete the project, but please correct me if I am wrong.

**Comment by rameshmisra** [comment]
No, does not run in notebook either (in Firefox or Edge). 
(That was the reason I tried view it on media player). I don't remember if I mentioned that only way I could watch it is in the Chrome browser (so I presume a Jupyter NB in chrome would also work).

**Comment by baumanab** [comment]
Thanks for clarifying. Would you be able to complete the lab in chrome?

**Comment by baumanab** [comment]
Thank you for investigating this.  I'm glad you were able to complete the lab.  I have added a note to the project repo.
