### ISSUE TITLE
Issue 1354 : Not corrected properly

### ISSUE THREAD

**Issue by Nk911** [udacity/sdc-issue-reports#1358]
Term 2 , Lesson 15 : Implementation of particle filter :Converting Landmark Observations

**Comment by Nk911** [comment]
![Term2_SDC_Issue_2_2_Image.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf13a2e0b6c200104a7ad6/125516c66e82c728ace21e0d46dc91882ed0bc9aabca806ab74ee59116141821162dae2a7780a164fd52690e050a1de853524d41f4f98029afbe3a238b545fe9d53f5f74c63d17aebbd01ead1da862da11d1e9e1d30695aa2f2ff58a88453f1b071c8cfa5d36a1914bc95ee406.JPG)

Please make corrections properly , I have raised Issue # 1354, half of the fixes were done , but it still not fixed completely even after commenting on that Issue , please refer the attached picture

**Comment by baumanab** [comment]
This is now updated
