### ISSUE TITLE
Issue 1355 : Not corrected properly

### ISSUE THREAD

**Issue by Nk911** [udacity/sdc-issue-reports#1359]
Please make corrections properly , I have raised Issue # 1355, half of the fixes were done , but it still not fixed completely even after commenting on that Issue , please refer the attached picture and comment on 1355

**Comment by Nk911** [comment]
![Term2_SDC_Issue_error.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf13a2e0b6c200104a7ad6/125516c66e82c728ace21e0d46dc91882ed0bc9aabca806ab74ee591164335612616e1673295f127b54778154d555ca949585646f5f18f78a7be68748e0e0bedd16d5976c56f10bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8d4b3b1b051c80fe5d33a98b06.JPG)

also include the definition of control stddev wherever applicable, Please take the confirmation before closing the issue

**Comment by baumanab** [comment]
Good catch. The quiz has been updated. Alignment with other quizzes as well as additional explanation will take place this week.

**Comment by Nk911** [comment]
Thanks
