### ISSUE TITLE
Improve Polynomial Function Concept - Advanced Lane Finding

### ISSUE THREAD

**Issue by mvirgo** [udacity/sdc-issue-reports#1360]
From Slack:

"You may have already heard this, but I find the part of the advanced lane finding videos where it tells you how to find the points to plug into the polynomial fit function to be very confusing. There’s simply a silent video describing peaks on histograms, sliding along the image, etc., with no mention of code to actually implement this. I’ve recently learned, after trying to do this for a few days, that there are numpy functions that are really helpful for this. They weren’t mentioned in the videos or instructor notes, so I was totally in the dark. I feel like the rest of this unit is much better with code examples and quizzes etc. But this part has no mention at all for how to actually execute the theory."

**Comment by baumanab** [comment]
I'm wondering if we can leverage a solution to this with the control unit polynomial functions.
