### ISSUE TITLE
T1 - L15.30 (Color And Gradient) misleading code

### ISSUE THREAD

**Issue by MC-8** [udacity/sdc-issue-reports#1361]
The code at the end of the pipeline (lines 29-31) mentions that 

>   Note color_binary[:, :, 0] is all 0s, effectively an all black image. It might
>   be beneficial to replace this channel with something else. "

While is true that the image is all black, it is because some coding issue earlier on.
In line 13:
>   hls = cv2.cvtColor(img, cv2.COLOR_RGB2HLS)**.astype(np.float)**

the float conversion is not present in the lesson code.

Removing the floating conversion allows obtaining a non-black image at the end of the pipeline.
The alternative is to return an uint8, that is changing line 32 to 
>     return color_binary.astype(np.uint8)

**Comment by baumanab** [comment]
Thanks for troubleshooting this.  The quiz has been updated.
