### ISSUE TITLE
iSDC-P1-Implement-Matrix-Class Project

### ISSUE THREAD

**Issue by DeniseJames** [udacity/sdc-issue-reports#1362]
The iSDC-P1-Implement-Matrix-Class project instructions does not require the student to show the outputs of the functions defined in matrix.py

The rubric for iSDC-P1-Implement-Matrix-Class project does require the output of the functions created in matrix.py

The student usually fails the first project submission because they do not show the output of the created functions in matrix.

**Comment by baumanab** [comment]
Thank you for reporting this, it has been reported to iSDC.  They will likely open this as an internal issue or in the iSDC issues repo.
