### ISSUE TITLE
Term 1 - Lesson 19 - 9. Quiz: Decision tree accuracy

### ISSUE THREAD

**Issue by miguelangel** [udacity/sdc-issue-reports#1364]
Hi!

There is a comment at the bottom of the Term 1 - Lesson 19 - 9. Quiz: Decision tree accuracy chapter that I am not 100% sure is correct.

I am referring to this:

> NOTE: You might get an accuracy of 91.2% instead of 90.8%, not to worry. If you run the quiz a few times you'll see that either result is possible, apparently a minor instability in the DecisionTreeClassifier().

I think that the differences are due to do not explicitly setting a random seed.

I have tested quiz multiple times using the Classifier initialization below, and always returns the same value (0.912).

clf = DecisionTreeClassifier(random_state=23)

Might I suggest to change that paragraph to describe the use of random_state (mainly used for reproducibility purposes) and it's implications in the results of this quiz?

Hope it helps!

Miguel Ángel

**Comment by baumanab** [comment]
There is now a note in the classroom.  Thanks again for the insightful observation.
