### ISSUE TITLE
final project incorrect waypoints

### ISSUE THREAD

**Issue by stealthdaimma** [udacity/sdc-issue-reports#1365]
On the test track of the final project, it seems that some of the waypoints around the Valley are incorrect in that they are far away from the center of the lane. It occurs at around 2:50 if we don't stop for traffic lights. Due to these incorrect waypoints, our controller either touches or goes out of lane 2-3 times around this area. Please upload the updated waypoints soon.

please see the attached images:
https://imgur.com/a/WC6QzK8

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
