### ISSUE TITLE
Miniflow Lesson 13 - Math Mistake

### ISSUE THREAD

**Issue by mvpcom** [udacity/sdc-issue-reports#137]
There is a mathematical mistake in representation of partial for Z_il with respect to X_ij.

**Comment by mvpcom** [comment]
Actually d(Z_il)/d(X_ij)=d(X_ijW_jl+b_l)/d(X_ij)=W_jl and there is some misunderstanding with your current approach which is d(Z_il)/d(X_ij)=X_ijW_jl+b_l=W_jl.

**Comment by domluna** [comment]
Hi @mvpcom, thanks for bringing this up. My intention was to show the steps to get to W_jl but I should have been more explicit with the notation. I'll update this.

**Comment by mvpcom** [comment]
Thanks @domluna
