### ISSUE TITLE
cppad installation fails on bash for windows 

### ISSUE THREAD

**Issue by jumanamp** [udacity/sdc-issue-reports#1370]
apt-get install cppad shows no repo found error. Building from source looks painful process, as there are many parameters to be filled in for cmake. Any help in this regard? 

I tried checking all apt repos, they seem to be in there. It seems like the apt repo that is required is universe.

**Comment by baumanab** [comment]
This is unusual.  I just tried this in Linux and in Ubuntu Bash for windows and it worked.  Would you mind trying again?

**Comment by jumanamp** [comment]
I tried but always the same. I had to build from source, dont know what is
going on. It is strange indeed.

**Comment by baumanab** [comment]
Nice work!  I'm glad it worked out and sorry for the difficulties.  I'm going to close this out since it seems isolated and has been worked around.  We will re-open if we start to see similar issues/reports.
