### ISSUE TITLE
Incorrect use of tf.Variable on input features

### ISSUE THREAD

**Issue by mvirgo** [udacity/sdc-issue-reports#1371]
From post here: https://knowledge.udacity.com/questions/2536

Looks like we incorrectly use tf.Variable for input features that should be tf.Placeholder. I am following up to find what exact quiz this is.

**Comment by baumanab** [comment]
I looked for this, but didn't find it.  Any idea what quiz?

**Comment by mvirgo** [comment]
Figured out that this was the TensorFlow ReLU quiz in the Deep Neural Networks lesson. I updated my response on Knowledge to be more clear on this.
