### ISSUE TITLE
Markov localization distance

### ISSUE THREAD

**Issue by baumanab** [udacity/sdc-issue-reports#1372]
From student feedback. 

> In section 36, the instructions show: if the pseudo range vector does not exist, pass the maximum distance to norm_pdf

> However in the code instead of passing the distance_max to pseudo_range_min, it passes std::numeric_limits::infinity(). Could you please verify if the "maximum distance" showed in instructions refer to maximum distance in the given map or the maximum value numerically?

**Comment by mvirgo** [comment]
Related Knowledge post - 

"https://knowledge.udacity.com/questions/13854"

**Comment by mvirgo** [comment]
Fixed
