### ISSUE TITLE
Add link to waffle.io/udacity/sdc-issue-reports

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1375]
Feature request:

Add a link to waffle.io in the side pane of the Udacity courses. This site is really hard to find: probably a lot of issues were not reported, because people didn't bother to look for the link.

**Comment by baumanab** [comment]
Links have been added throughout the ND.

**Comment by benenaes** [comment]
Can you post a screenshot ? I still don't see in the side pane.

**Comment by baumanab** [comment]
We couldn’t do a side pane at this point so we added a note and link in most lessons.
