### ISSUE TITLE
Term 3, Lesson 3, Session 16: Typos

### ISSUE THREAD

**Issue by benenaes** [udacity/sdc-issue-reports#1376]
Issues:
1. Numbering
2. Formula
3. Fix the issue with istringstream (also the comment itself contains a typo)

**Comment by baumanab** [comment]
Thank you for reporting this. Is this referring to implementing naive Bayes in the prediction lesson?Would you mind providing additional detail to help identify the issues?

**Comment by baumanab** [comment]
closed as not actionable without updated information.
