### ISSUE TITLE
Term 1, Project Traffic_Sign_Classifier, No instruction for project and data repository

### ISSUE THREAD

**Issue by deidaraho** [udacity/sdc-issue-reports#1378]
Hello all, 
Though I found the link through Google, there are no clue about the link to the project or data repositories. How can I check whether the link from Google is official or latest? 

Thanks,

**Comment by baumanab** [comment]
Thanks for contacting us. Are you using a workspace to complete this project?

**Comment by baumanab** [comment]
Also what link did you find?

**Comment by mvirgo** [comment]
Local instructions were hidden accidentally; they are back to public.
