### ISSUE TITLE
SDC-Term2 Can not open the links

### ISSUE THREAD

**Issue by xfxh** [udacity/sdc-issue-reports#1379]
I can not open the below links in second lesson "Intro" in  "Lidar and Radar Fusion with Kalman Filters in C++" of SDC-term2 in China.

1: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/4c4f9180-7ab8-42ba-a1bd-24b17fcf2178/concepts/3d7a14af-6afa-446e-9399-622360eddd6c

2: http://www.mathwarehouse.com/trigonometry/inverse-sine-cosine-tangent/

**Comment by baumanab** [comment]
Thank you for reporting this.  I am also not able to see this on my student account.  We are looking into the issue.  Suffice it to say, i don't think it has anything to do with your location.

**Comment by baumanab** [comment]
The links should now resolve.  Please let us know if that is not the case.
