### ISSUE TITLE
Term 3 -> Lesson 3 "Prediction -> Concept 16. Implementing Naïve Bayes -> Equation "y"

### ISSUE THREAD

**Issue by selyunin** [udacity/sdc-issue-reports#1383]
**Where:**
Term 3 -> Lesson 3 "Prediction -> Concept 16. Implementing Naïve Bayes -> Equation "y"

**What:**
Ill-formatted LaTeX equation "y" at the bottom of the page. 

**Suggestion:**
Please fix the equation "y" -> take a look how your LaTex web-rendering engine outputs the equation and fix the formatting accordingly. For long underscores use $A_{ i am long underscore }$

**Comment by jacobnzw** [comment]
You wanna you this code! (force persuade)

```
\[
y = \underset{k \in \{1, \ldots, k\}}{\operatorname{argmax}}\: p(C_k) \prod_{i=1}^{n} p(x_i = v_i \mid C_k)
\]
```

**Comment by jacobnzw** [comment]
Further issues on the same page ("Implementing Naive Bayes in C++")

1. Instructions mention functions with Pythonic signatures, that is, they involve `self`, but the quiz is supposed to be primarily in C++ (even though python is an option too).
2. The bullet points under second bullet point "2." are not indented properly. Namely, the bullet points _"2. Use the conditional probabilities in a Naive Bayes classifier."_ and _"3. When you want to test your classifier, ..."_

**Comment by mvirgo** [comment]
Fixed this equation. Our classroom doesn't use actual LaTex under the hood which makes this a little frustrating, but got it working.

Also, removed `self` from the instructions - definitely makes sense to not have these when we're directly talking about the .cpp files.

Lastly, the bullet points should be indented properly now.
