### ISSUE TITLE
T3.L2.11

### ISSUE THREAD

**Issue by jmorilloe** [udacity/sdc-issue-reports#1384]
Solution video is wrong, it is the same video as the problem formulation.

**Comment by baumanab** [comment]
Thanks for letting us know. Would you mind linking the lesson?

**Comment by jmorilloe** [comment]
Sure:

https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/583195d4-9e88-4414-acb8-734ab78f9b16/concepts/112e9f79-63cd-44ee-883f-652677e64d31

Regards,

2018-07-25 8:48 GMT+02:00 Andrew Bauman <notifications@github.com>:

**Comment by baumanab** [comment]
Very good catch!  The solution video is now live in the classroom.
