### ISSUE TITLE
Term 1 - Lesson 13 - Keras version?

### ISSUE THREAD

**Issue by BScottHenderson** [udacity/sdc-issue-reports#1385]
I just completed the Jupyter Notebook exercises in Term 1 - Lesson 13 - Keras. The online notebooks were fine. However, I usually try to follow along in a stand-alone Python code file on my local machine. I found that the version of Keras included with (?) the "carnd-term1" Anaconda environment is 1.2.1 whereas the online Jupyter Notebook was using version 2.*  The syntax is more than a little different in Keras 2.*

So I attempted to resolve the issue by installing Keras in my "carnd-term1" environment - oddly it had not been installed before even though it had been used - probably a lack of understanding on my part about how Python packages interact with the Anaconda environment. In any case installing Keras directly caused other things in TensorFlow to stop working - I think Anaconda installed a patch or some such thing for TensorFlow.

So this might all be an issue just for me but it seems worth noting at least.

**Comment by mvirgo** [comment]
Hi there! We recently updated the starter kit and classroom to be Keras v2.0.9 and TensorFlow v1.3.0, which is the likely cause of the difference you are seeing.

The best option you have here is probably to remove the old `carnd-term1` environment and re-install it with the updated version on [that repository](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment.yml) - the version of Tensorflow (0.12.1) from the old environment is incompatible with the newer version of Keras.

**Comment by mvirgo** [comment]
Glad to hear it! Thanks for keeping us updated on the results.
