### ISSUE TITLE
opencv errors when in workspace

### ISSUE THREAD

**Issue by uv1000** [udacity/sdc-issue-reports#1387]

**Comment by uv1000** [comment]
Dear scd-nd-supporters,

as confirmed with your Mentor Ayush  opencv does not work out of the box in the workspace.  E.g. (code snippets from) https://github.com/udacity/CarND-Camera-Calibration.git using cv2.- commands will trigger the error. Screen dump of the error see below. I got the same errors  in my local install. 

a) Ayush suggested as a workaround:
pip3 install opencv-python
This works for the workspace, which is very good, because otherwise I would be stuck with my project ...
-> Could you try to fix this globally for all workspaces? I think we all expect the workspace to be fully configured with the right packages ...

b)Unfortunately Ayush's suggestion: does not fix the error in my local install (vanilla Ubuntu 16.04 with anaconda). May I ask you for help  on setting up local installs? How can I "clone" the environment of the workspace? Is ist possible to include some sort of (conda-*) configuration file with the workspace, perhaps plus a little readme on how to use it?

Thanks a million,
Ulrich  

-------------------------
  ---> 53         cv2.imshow('img', img)
     54         #plt.imshow(img) #cv2.imshow('img', img)
     55         #cv2.waitKey(500)

error: OpenCV(3.4.1) /opt/conda/conda-bld/opencv-suite_1527005194613/work/modules/highgui/src/window.cpp:636: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

**Comment by baumanab** [comment]
Thank you for letting us know about this.  To help our investigation, would you mind linking the workspace where you encountered the error?  It sounds like the local and workspace error are identical.  Is that correct?

**Comment by uv1000** [comment]
I had to apply the fix in the workspace again after having been idle for a while (in the notbook: "restart Kernel and clear Output".    In my local install even rebuilding opencv from scratch as suggested by Ayush https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html
did not help. Any advice welcome. I am hoping for the https://github.com/udacity/CarND-Term1-Starter-Kit but I have lost a lot of time already, must carry on completing the project due the day after tomorrow. Thank you for your support!

**Comment by uv1000** [comment]
ps: ah maybe that is what you were asking for - I was not checking out (ok cloning) the aforementioned repo into my workspace. Just copying code from the .ipynb there into the notebook for generating the writeup

**Comment by uv1000** [comment]
Try computing the calibration and undistortion in the exercise below, and if you want to play with extracting object points and image points yourself, fork the Jupyter notebook and images in this repository.

https://classroom.udacity.com/nanodegrees/nd013/parts/edf28735-efc1-4b99-8fbb-ba9c432239c8/modules/5d1efbaa-27d0-4ad5-a67a-48729ccebd9c/lessons/78afdfc4-f0fa-4505-b890-5d8e6319e15c/concepts/5415176a-d615-49af-8535-53a385768a23

**Comment by uv1000** [comment]
https://view5639f7e7.udacity-student-workspaces.com/tree
this is another attempt of linking to my workspace 
(note that I - temporarily see above - fixed the prob by applying Ayush's fix)

**Comment by uv1000** [comment]
downloaded, ok pulled,  your docker Image from the primer repository. Same error!!! At least at first
-> rebooted the linux-machine I am running on
now: 
  docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit
gives my an .ipynb in a browser but this dies on me with the error message below when I try to execute the cell containing the cv2. commands 

You are welcome to have a look at https://github.com/uv1000/P2/P2_[].ipynb
can you reproduce the error in the docker container?

what on earth is going on there? 

the same notebook (I am pretty sure ...) works in 

https://classroom.udacity.com/nanodegrees/nd013/parts/edf28735-efc1-4b99-8fbb-ba9c432239c8/modules/5d1efbaa-27d0-4ad5-a67a-48729ccebd9c/lessons/7cb63828-36aa-4cea-9239-700b5ea41f0b/concepts/0a96d23f-6c22-4053-a7f6-83e12ce5a6ec

with the added twist that one has to apply Ayush's trick and then restart the kernel, before executing cell 2 

To spell it out very explicitely: the same procedure in the Docker container leads to the crashing kernel as described above 

--------------
Kernel Restarting

The kernel appears to have died. It will restart automatically.

**Comment by uv1000** [comment]
the following is the linux console output while the kernel dies as described above ... maybe this gives  us a hint. giving up for now ....

Thanks for your support!
----------------
voll (master *) P2 $ docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit
[I 21:30:32.111 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 21:30:32.140 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 21:30:32.148 NotebookApp] Serving notebooks from local directory: /src
[I 21:30:32.148 NotebookApp] 0 active kernels 
[I 21:30:32.148 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=25a6ab0493e49584e9e5a4ea56f7f1b0876588a1dfea94f5
[I 21:30:32.148 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:30:32.148 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=25a6ab0493e49584e9e5a4ea56f7f1b0876588a1dfea94f5
[I 21:30:44.750 NotebookApp] 302 GET /?token=25a6ab0493e49584e9e5a4ea56f7f1b0876588a1dfea94f5 (172.17.0.1) 0.48ms
[I 21:30:49.027 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 21:30:49.028 NotebookApp] Notebook P2_SDC_Ulrich_Voll.ipynb is not trusted
[I 21:30:49.245 NotebookApp] Kernel started: d20b8c24-2fea-4bdc-988b-5507e680d6d1
[I 21:30:49.754 NotebookApp] Adapting to protocol v5.1 for kernel d20b8c24-2fea-4bdc-988b-5507e680d6d1
Fontconfig warning: ignoring C.UTF-8: not a valid language tag

(img:42): Gtk-WARNING **: cannot open display: 
[I 21:31:13.246 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel d20b8c24-2fea-4bdc-988b-5507e680d6d1 restarted

**Comment by baumanab** [comment]
Since this workspace wasn’t intended for the described use and there is another ticket open that speaks more directly to the environment issue, I’m closing this. We are in the process of clarifying what is supported for workspace use.
