### ISSUE TITLE
tensorflow lecture 19 

### ISSUE THREAD

**Issue by ksakmann** [udacity/sdc-issue-reports#139]
tf.log() implements the natural logarithm, not the logarithm to the base 10 as implied in the lecture notes, i.e. tf.log(100) is not 2

**Comment by Brok-Bucholtz** [comment]
@ksakmann 

Good catch.  I've changed the concept to indicate `tf.log()` is for natural log and changed the `2` to `4.60517`.  I used `4.60517`, since we are dealing with `tf.float32` type.
