### ISSUE TITLE
Term2 lesson 11 On Markov Localization has typo in text

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1393]
In quiz question number 2, text reads : "What is the raw posterior probability P(location) for x = 2?"

Should be :
What is the raw posterior probability P(location | observation) for x = 2?

Isn't P(location) called the Prior probability of the location ? Or am I confused ??

**Comment by baumanab** [comment]
Great catch, I think you are correct.  We will fix this soon.

**Comment by mvirgo** [comment]
Yep, you were correct here. Now fixed!
