### ISSUE TITLE
crashing kernel in carnd-docker container

### ISSUE THREAD

**Issue by uv1000** [udacity/sdc-issue-reports#1394]

**Comment by uv1000** [comment]
Dear sdc supporters,

this is related to #1387 but I think it is better to put this in a separate issue. (Even!) the docker solution does not work on my local machine. 
 
Problem description: After having seen multiple issues with running my project .jpynb locally, I downloaded your docker container. I was putting a lot of faith in the docker solution, but unfortunately I get an error message "kernel crashed" when trying to run my .jpynb, even though the same .jpynb is functioning fine in the workspace

What I did/how to reproduce:

 In my local repository https://github.com/uv1000/P2
(say commit d12a5b2c6dabc9c445fa9066ae8e120fdd56831f , functioning in the workspace)
on my ubuntu 16.04 with docker installed and running, I did the following: 

1. docker pull udacity/carnd-term1-starter-kit

2) docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit
Name of the .jpyng causing the crash: P2_SDC_Ulrich_Voll.jpyng

What errors do I see:

a) in the notebook
"Kernel Restarting The kernel appears to have died. It will restart automatically."

b) on the linux console:
(see below) 

Can you reproduce this problem? It seems that many others have no problems with local installs. Is this because they are using Windows? Should I change to windows in order  to avoid problems working on my local install?
 

------------------
docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit
[I 08:32:39.598 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 08:32:39.628 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 08:32:39.635 NotebookApp] Serving notebooks from local directory: /src
[I 08:32:39.635 NotebookApp] 0 active kernels 
[I 08:32:39.635 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=58c323cbc81a702e9bdcd73feef48e4b01112f0524e956e6
[I 08:32:39.636 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:32:39.636 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=58c323cbc81a702e9bdcd73feef48e4b01112f0524e956e6
[I 08:32:59.376 NotebookApp] 302 GET /?token=58c323cbc81a702e9bdcd73feef48e4b01112f0524e956e6 (172.17.0.1) 0.36ms
[I 08:33:03.896 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 08:33:03.903 NotebookApp] Notebook P2_SDC_Ulrich_Voll.ipynb is not trusted
[I 08:33:04.721 NotebookApp] Kernel started: b0526eb4-a7d1-40b9-9cc8-6714c299298d
[I 08:33:05.219 NotebookApp] Adapting to protocol v5.1 for kernel b0526eb4-a7d1-40b9-9cc8-6714c299298d
Fontconfig warning: ignoring C.UTF-8: not a valid language tag

(img:41): Gtk-WARNING **: cannot open display: 
[I 08:34:07.722 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel b0526eb4-a7d1-40b9-9cc8-6714c299298d restarted

**Comment by uv1000** [comment]
the docker container I considered as a last resort for getting a well defined environment up and running on my local machine. (So I am slightly reluctant to "go back to plain conda", since this is the battleground I have given up on ... I would not mind to have a working conda env, but nothing worked including the one suggested in carnd-term1-starter-kit -> always errors/crashes due to opencv ... )

this is a general problem,  i cannot run my .ipynb files in my local install(s) I tried a lot, conda environments plenty of them, always got  error messages concerning opencv not working.

even in the workspace I had to mess around with conda/pip in order to make things work. se #1387. However Ayush's fix "pip3 install opencv-python" fixes the issue for me *in the workspace* In my local install problems persist. 

-> Am I the only one to experience this specific workspace problem? 

I presently working on project "advanced lane finding" right now.  Above I linked to a specific github commit of my present projects. In order to give you something specific to reproduce the error.  Things are functioning in the workspace, but not locally ...

Thanks for your support! Yours , Ulrich

**Comment by mvirgo** [comment]
Hi Ulrich - were you activating the conda environment (i.e. `source activate carnd-term1`) when running into the cv2 issue? That's a fairly common first library to run into issues with if the environment was not activated.

**Comment by baumanab** [comment]
If env activation does not work there is one more thing we can try, so let us know if the activation works or not.

**Comment by uv1000** [comment]
great, thanks a lot!!

Using conda is indeed the preferred option (but since it could not make it work despite of a lot of efforts I thought docker would mean playing safely - I have a docker server up and running)
-> yes I am pretty sure that I activated the environment (would be pretty stupid not to, but I agree these things happen ...)
Therefore I will go through the entire setup again, that ist the setup for the conda version of https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

**Comment by uv1000** [comment]
I followed the setup howto painstakingly and this time my notebook P2_SDC_Ulrich_Voll.ipynb  in my local repository (-> https://github.com/uv1000/P2 if you want to try for yourself) is *partly working*. (note that it is fully working in the workspace provided the fix from mentor Ayush describee in #1387 is applied) 

I am pretty sure it was not lacking activation alone, possibly I gave the env another name last time.  I did not clone the respective git-repo then, only downloaded the  environment.yml config file.  Maybe the environment generation process is somewhat brittle w.r.t. names and possibly other seemingly minor details ...  never mind

Specifically I took the following steps:
pwd    (output: /home/voll/sdc_playground)
git clone https://github.com/udacity/CarND-Term1-Starter-Kit.git
cd CarND-Term1-Starter-Kit/
conda env create -f environment.yml
 source activate carnd-term1
cd ../P2/
git pull
jupyter notebook P2_SDC_Ulrich_Voll.ipynb

Notebook is now starting up but with issues, see below

Anyway, we are much closer but not where we want to be

Two errors see below, the second causes the kernel to die. 

----------------
Imageio: 'ffmpeg.linux64' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg.linux64 (27.2 MB)
Downloading: 8192/28549024 bytes (0.01081344/28549024 bytes (3.8%4702208/28549024 bytes (16.59084928/28549024 bytes (31.812984320/28549024 bytes (45.5%17211392/28549024 bytes (60.3%21512192/28549024 bytes (75.4%24821760/28549024 bytes (86.9%28549024/28549024 bytes (100.0%)
  Done
File saved as /home/voll/.imageio/ffmpeg/ffmpeg.linux64.

----------
[If I click the following modal dialogue away, the kernel dies. There was an image opening outside the browser, different from the behavior in the workspace, maybe related to that image. ]

img is not responding.

You may choose to wait a short while for it to continue or force the application to quit entirely.

**Comment by uv1000** [comment]
Hey guys thanks for nudging me in the right direction.
I was now able to fix the issues.

-  Installed the gpu-version (Remark R1: conflicts with the non-gpu version, as they have the same name. Great to have a GPU version, thanks to you for providing this.)
- had to update pip and conda (R2: you seem to be shipping with very old versions ... possibly on purpose ...)
- removed a cv2.imshow('img', img) in one of the first cells (withot a %matplotlib inline pragma ...) this seems to have solved the crashing window issue. (R3 maybe this will also help for the docker container I will try this asap)
- had to install  " conda install requests" that fixed the error when starting to create the video.   (R4: the ffmpeg error did not come up in the GPU version of the conda env)

Now it is flying, particularly when creating the videos ... i have a NVidia GForce 1070 ... 

Many thanks indeed!

I will keep you posted on the docker issue.

**Comment by baumanab** [comment]
Nice work!  I’m closing since the is resolved. Docker should not be necessary on Linux, but let us know what happens.

**Comment by uv1000** [comment]
Thanks a million for your patient support. 

As promised my comments on docker-setup.  short: Docker CPU running locally, Docker GPU I do not know yet

Docker image now working, too,  after fixing the plots without using a
%matplotlib inline pragma 
(I think the setup can not handle the creation of windows outside the browser, maybe these are x11 windows) 
But I am unsure if this is making proper use of my gpu. 
Your "Docker GPU" instructions in the term1-github  seem to be primarily for AWS and not for a local GPU  ...

**Comment by uv1000** [comment]
Docker on local GPU
a) is this the right place to ask/discuss the issue?
b) I can replace  "docker" by "nvidia-docker" but  I do not see any speedup on the P2 video processing.  Is this the right way? I feels too naive ...  please find details below

 nvidia-docker run --rm nvidia/cuda nvidia-smi  
shows my GTX 1070 all right.

Is it as simple as running 

nvidia-docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit

(instead of the same without the prefix "nvidia-")

**Comment by mvirgo** [comment]
For Advanced Lane Lines, there won't be any significant speed-up from using GPU, unless you used a deep learning-based approach here.
