### ISSUE TITLE
VM for ROS is corrupt

### ISSUE THREAD

**Issue by chmod600** [udacity/sdc-issue-reports#1395]
I'm trying to download the VM image from 

https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/7e3627d7-14f7-4a33-9dbf-75c98a6e411b/concepts/8c742938-8436-4d3d-9939-31e40284e7a6?contentVersion=1.0.0&contentLocale=en-us

using this link - 

https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/Udacity_VM_Base_V1.0.0.zip

But I keep getting a corrupt image. The MD5 does not match. Not sure if it's me or there's a issue with the VM.

I tried multiple times using browser, wget from terminal, etc. Still getting a corrupt image. Help!

**Comment by baumanab** [comment]
Sorry for the technical issues.  To be sure we are looking at the same thing, would you mind sending me the download link you are using?

**Comment by chmod600** [comment]
@baumanab  It's the same link in the OP - 

https://s3-us-west-1.amazonaws.com/udacity-selfdrivingcar/Udacity_VM_Base_V1.0.0.zip

Screenshots for reference - 

![screen shot 2018-08-02 at 12 24 18 pm](https://user-images.githubusercontent.com/19159143/43606039-19a78468-964f-11e8-8ddc-69ff2a69acab.png)
![screen shot 2018-08-02 at 12 24 30 pm](https://user-images.githubusercontent.com/19159143/43606040-19beaa58-964f-11e8-91c1-011dafeea0f9.png)

**Comment by baumanab** [comment]
We determined that the issue is that we had not updated the checksum.  We downloaded and verified the integrity of the VM.  Please let us know if you have any issues using it.

**Comment by chmod600** [comment]
@baumanab  Thats not all. Virtual box cannot import the VM and gives this error stating that the VM is corrupt - 

![screen shot 2018-08-02 at 1 03 55 pm](https://user-images.githubusercontent.com/19159143/43607929-a0e1fa08-9654-11e8-9b43-ede30bd376dc.png)

Are you able to import the VM into virtual box on a Mac OS X machine?

**Comment by chmod600** [comment]
@baumanab Following up.
