### ISSUE TITLE
Lesson 10: TensorFlow: 16. Linear Update

### ISSUE THREAD

**Issue by CyberAMS** [udacity/sdc-issue-reports#1396]
The paragraph "We can take advantage of an operation called broadcasting used in TensorFlow and Numpy. This operation allows arrays of different dimension to be multiplied with each other. For example:" should rather talk about arrays of different dimensions being added to each other.

**Comment by mvirgo** [comment]
It actually does allow for multiplication, although we show addition in the example. I have now changed it to "... allows arrays of different dimension to be added or multiplied with each other." Good catch.
