### ISSUE TITLE
Corrupt VM for ROS

### ISSUE THREAD

**Issue by chmod600** [udacity/sdc-issue-reports#1398]
This is related to https://waffle.io/udacity/sdc-issue-reports/cards/5b628c697c6ff2001b662441
but that issue has been moved to the done state.

Here are more screenshots from today - 

![screen shot 2018-08-05 at 4 03 25 pm](https://user-images.githubusercontent.com/19159143/43691004-7ec56528-98c9-11e8-8e2d-817bd1797f37.png)

![screen shot 2018-08-05 at 4 03 12 pm](https://user-images.githubusercontent.com/19159143/43691006-80552806-98c9-11e8-81fb-97bdc72133a6.png)

I am on a mac. There is certainly something wrong with the VM.

**Comment by baumanab** [comment]
Sorry for the confusion. I moved the issue to the done state since it we thought the issue was due to an outdated checksum. I’m not sure what is causing the issue. We had two team members successfully install the VM on Mac. What version are you on?

**Comment by chmod600** [comment]
No problem :) Thanks for writing back. This is my mac version - 

![screen shot 2018-08-05 at 7 40 08 pm](https://user-images.githubusercontent.com/19159143/43694281-6dea093e-98e7-11e8-9f16-a5f50a91a0ab.png)

I wonder if I am doing anything wrong? These are the steps I am following - 

1. Download Zip file
2. run `unzip <zip file>` or double click 
3. Import new application, using`.ovf` file into newly installed Virtual Box.

**Comment by chmod600** [comment]
Virtual Box version - 

![screen shot 2018-08-05 at 7 48 11 pm](https://user-images.githubusercontent.com/19159143/43694516-8e609f1a-98e8-11e8-90f0-d15a990894e9.png)

**Comment by baumanab** [comment]
Thanks for the detail. This sounds right but I will verify.

**Comment by chmod600** [comment]
Thanks you!

**Comment by baumanab** [comment]
Sorry for the delay, it could be the iOS version.  Have you tried the workspace in the classroom for the system integration project?

**Comment by baumanab** [comment]
closing in the absence of updated information

**Comment by chmod600** [comment]
@baumanab  Sorry for the delayed response, but I ended up running it using Docker.

**Comment by baumanab** [comment]
no worries, I'm glad it worked out
