### ISSUE TITLE
Term 2, P10 MPC-Project，Mac install Ipopt error

### ISSUE THREAD

**Issue by linghuchong9981** [udacity/sdc-issue-reports#1399]
- I install Ipopt through brew command，However There was a mistake , If there any suggestion for me to handle this ? Thanks

==> Installing ipopt from udacity/carnd-mpc-project
Error: No available formula with the name "scotch5" (dependency of udacity/carnd-mpc-project/ipopt)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by baumanab** [comment]
I’m looking into other solutions. In the meantime, this may help. 

https://github.com/udacity/CarND-MPC-Project/issues/24

**Comment by baumanab** [comment]
This may help as well. 

https://github.com/Homebrew/brew/issues/829#issuecomment-243006354

**Comment by alexcthompson** [comment]
I have the same issue as @linghuchong9981 .

**Comment by alexcthompson** [comment]
@linghuchong9981 - here's a workaround that worked for me. Essentially I found another homebrew tap that had both `ipopt` and `scotch5` (which was also a problem for me), and used that tap to install them both.  Below is the sequence of commands I used.  Keep in mind that for some of these installs, homebrew insisted on upgrading `gcc`, `openssl`, `open-mpi`, which took more than 3 hours on my laptop, much of it at 95+% CPU.  So have access to power!

```shell
$ brew untap udacity/carnd-mpc-project
$ brew tap dpo/homebrew-openblas
$ brew install ipopt --with-openblas
```

**Comment by baumanab** [comment]
Nice work and thank you for sharing this.

**Comment by baumanab** [comment]
@linghuchong9981 would you mind trying this and letting us know if it works?

**Comment by mvirgo** [comment]
I've updated the repository to instead use this tap - [brewsci/science](https://github.com/brewsci/homebrew-science), as it actually holds all the deprecated homebrew/science formulas.

**Comment by baumanab** [comment]
Closing for now. Please let us know if there are further issues.
