### ISSUE TITLE
Get Started instructions are off in Lab: TensorFlow Neural Network

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#14]
It says
 sudo pip3 install -r CarND-TensorFlow-L2/requirements.txt 

instead of sudo pip install ...

Also there is no answer to the solutions as mentioned:
This is a self-assessed lab. Compare your answers to the solutions here

**Comment by Brok-Bucholtz** [comment]
@rm51 

I'm in the process of moving the lab from pip to [conda](http://conda.pydata.org/docs/).  I'll update this issue when I've replace pip with conda.

I added the solutions link to the the [page](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/b619c2f0-24e3-4529-aa48-9bcdba47cd08).  Thanks for letting us know :)

**Comment by Brok-Bucholtz** [comment]
@rm51 

I added Anaconda to the lab, which makes installation easier.  Let me know if you need anything else :)
