### ISSUE TITLE
Workspace checkpoint lost

### ISSUE THREAD

**Issue by feiliangli** [udacity/sdc-issue-reports#1400]
The latest checkpoint of my P1 and P2 **workspace** are lost. They are now reverted to checkpoints in July. All my works also the submitted ones in August are lost. Please help to fix it, so that I can continue my work.

**Comment by baumanab** [comment]
We are still working on this issue, thank you for your patience.  We should have an update later today.

**Comment by baumanab** [comment]
sorry again, update postponed until tomorrow

**Comment by baumanab** [comment]
Would you mind checking to see if your workspace checkpoint etc has been restored.

**Comment by feiliangli** [comment]
Yes, my workspace is restored. Thanks a lot.


Andrew Bauman <notifications@github.com> schrieb am Do., 30. Aug. 2018,
23:10:

**Comment by baumanab** [comment]
I’m really glad it worked out!
