### ISSUE TITLE
Term 2: Initilize Belief State.

### ISSUE THREAD

**Issue by jacobnzw** [udacity/sdc-issue-reports#1403]
When I give the right answer in the second box on the Initialize Belief State section of Term2, SDC nanodegree, the system won't accept. The right answer is 4.0E-02, copied and pasted, answer not accepted.

**Comment by baumanab** [comment]
Thanks for reporting this. Would you mind linking the content

**Comment by jacobnzw** [comment]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/b04b578e-ac58-4012-a7ec-0fba40fe1558

The error is in the second box.

**Comment by mvirgo** [comment]
I've updated the solution to include two decimal places (was also mentioned in the quiz text, although not sure if that was added before or after this ticket). Also, added a quick note next to the solution to note that two decimal places are necessary here for the quiz to accept the answer.
