### ISSUE TITLE
ROS VM drive size not enough

### ISSUE THREAD

**Issue by Fadi88** [udacity/sdc-issue-reports#1404]
when using the VM for the system integration project it was found that the allocated disk size (15 GB) is not enough.
especially after downloading and trying to extract the final rosbag and doing

**Comment by cielsys** [comment]
I second this! And once you run out of disk bad stuff happens and it's not always clear why. And if you restart the VM it is an ordeal to get back in and fix it. And resizing a VM partition is not trivial.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
