### ISSUE TITLE
MPC-quizzes mpc_to_line solution code yields runtime error

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1406]
I have build and run the solution code - untouched - and got this error: 

`Iteration 0
Cost 1.4822e-323
cppad-20180000.0 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 476 in the file 
    /usr/local/include/cppad/utility/vector.hpp
Assertion failed: (false), function Default, file /usr/local/include/cppad/utility/error_handler.hpp, line 206.
fish: './mpc' terminated by signal SIGABRT (Abort)
`

**Comment by EmilePapillon** [comment]
This error was due to improper library installation, but this was not very obvious (see error report above). Solving library install issue resolved the problem.

**Comment by baumanab** [comment]
I'm glad you were able to solve the issue.  Thanks for letting us know.

**Comment by colinmccormick** [comment]
I have this same error. What did you do to fix your library installation?

**Comment by colinmccormick** [comment]
Hm, never mind. Followed [this work-around](https://github.com/udacity/CarND-MPC-Project/issues/34) regarding scotch.rb and scotch5.rb, and that fixed the problem.

**Comment by EmilePapillon** [comment]
Glad to year that !

TBH, I don’t really remember the steps it took to get it working.


Le 6 oct. 2018 à 20:01, Colin McCormick <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hm, never mind. Followed this work-around<https://github.com/udacity/CarND-MPC-Project/issues/34> regarding scotch.rb and scotch5.rb, and that fixed the problem.
