### ISSUE TITLE
Term 2 simulator causes the core to run hot in Windows 10

### ISSUE THREAD

**Issue by JohnMansell** [udacity/sdc-issue-reports#1408]
When I run the term 2 simulator the core temp on my computer goes from about 25 on all 4 cores to about 80 on all the cores. Even if I'm not running a simulation, if the simulator is just open it runs really hot. The cores stay hot until I close out the simulator.

I have a core i7 6700K, 32GB of ram, running windows 10 64bit with an NVidia GTX 1060. I have a Hyper 212 evo cooler which usually keeps everything below 30c. I have to imagine if my system is getting so close to over heating, a lot of other students must be facing similar issues. Is there a way to make the simulator not take up so many resources? Especially when idling?

Also, my simulator is connected to the Ubuntu Bash on windows. Am I doing something wrong? Is there a setting I should change so the simulator doesn't take so much of the cpu?

Thanks.
John Mansell

**Comment by mvirgo** [comment]
This has been a somewhat re-occurring issue across platforms. Usually has been related to out-dated display drivers, but not always; we have still been unable to identify whether this is just an overall Unity issue or specific to something in the simulators. Will keep open for further investigation.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
