### ISSUE TITLE
Term 1-Traffic Sign Classifier [Error 28] No space left on device

### ISSUE THREAD

**Issue by SunshengGu** [udacity/sdc-issue-reports#1409]
I'm working on the SDC ND right now and I'm encountering an issue with Jupyter notebook. When I was training and saving a LeNet model, notebook would not save the file and gave me an error: [Error 28] No space left on device
I deleted the previous checkpoint files for the model (yes, it was working before!). But the error still exists. Do you know how I may solve this problem?

**Comment by mvirgo** [comment]
Hi Sunsheng - 

Please ask questions of this type in Knowledge or Study Groups - this is for bugs, fixes or content improvements to the program.
