### ISSUE TITLE
Miniflow - From Neurons to Layers - Possible Bug

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#141]
The following code snippet is present in the forward method of the layer:

```
outputs = self.inbound_layer.outputs

for n in range(len(outputs)):           
            weight = self.weights[n]
            input = outputs[n]
            self.outputs.append(do_math(input, weight))
```
This sort of implies that the number of outputs from a layer is always equal to the number of inputs. This doesn't seem right.

**Comment by domluna** [comment]
Thanks for the report @Deborah-Digges. I'll look more into it, but you're right it doesn't seem right.

**Comment by domluna** [comment]
@Deborah-Digges, very sorry for the delay! Forgot about this one. I added a note to the page:

"Here, Layer has an output list and accepts another layer as an input. It iterates through the inbound layer's outputs and produces its own list of outputs."

->

"Here, `Layer` has an output list and accepts another layer as an input. It iterates through the inbound layer's outputs and produces its own list of outputs. In this case, `Layer` has the same number of inputs and outputs. Generally the number of inputs and outputs vary based on the layer implementation."
