### ISSUE TITLE
Term 1: Behavioral Cloning  Can't open simulator

### ISSUE THREAD

**Issue by SunshengGu** [udacity/sdc-issue-reports#1410]
I enabled GPU mode and opened the simulator VM, but I don't see the simulator icon on the desktop of the VM. I searched in other places on the VM, couldn't find it either. Also, when i opened the VM, i got his error: No session for pid 58. Any thing I can do to fix this?

**Comment by baumanab** [comment]
Which browser are you using?

**Comment by SunshengGu** [comment]
I'm using Chrome. Tried Safari as well, but it doesn't even load the VM after like 4 mins.

**Comment by baumanab** [comment]
That’s unusual. I’ve seen that message and issue on non chrome browsers, but not chrome.

**Comment by mvirgo** [comment]
Please make sure to open the terminal within the desktop itself (not just the terminal in the primary workspace) first, then let us know if the simulator appears.

**Comment by SunshengGu** [comment]
@mvirgo Thanks for the tip! I've opened the terminal in the VM, and the simulator did appear. However, when I clicked on it, a window opened and closed, then nothing happened. I right-clicked and tried a bunch of "open with" options, nothing really worked.

**Comment by SunshengGu** [comment]
@baumanab I've tried Chrome, edge, Firefox, none of them worked for me...

**Comment by SunshengGu** [comment]
@mvirgo This is the message I got when I opened the terminal in the VM. 
ln: failed to create symbolic link 'CarND-Behavioral-Cloning-P3/data': No such file or directory
sh: 0: Can't open end_process.sh

**Comment by mvirgo** [comment]
Have you changed otherwise changed anything related to the location of the data (in `drive.py` or in your own files)? It may be that it is trying to look for data in the opposite location of where it resides (here, appears to be the repository folder, while the workspace has a different folder where the data is put by default).

**Comment by mvirgo** [comment]
Hi @SunshengGu - 

Apologies on the delay. After entering your workspace and noting I was also not able to access the simulator, I've reset the workspace, and it appears to now allow the simulator to open. Please let me know if it still does not work for you.

**Comment by SunshengGu** [comment]
@mvirgo Hi, thanks for doing so! And I just completed this project!

**Comment by mvirgo** [comment]
Great, glad to hear it! :)
