### ISSUE TITLE
Lesson 23: EKF - Step 13: answer not accepted when using pow from <cmath>

### ISSUE THREAD

**Issue by LinasKo** [udacity/sdc-issue-reports#1413]
// Accepted answer uses:
float dt_2 = dt * dt;
float dt_3 = dt_2 * dt;
float dt_4 = dt_3 * dt;

// The following is not accepted
#include <cmath>
...
float dt_2 = pow(2.0, dt);
float dt_3 = pow(3.0, dt);
float dt_4 = pow(4.0, dt);

**Comment by mvirgo** [comment]
Hi Linas - 

You need to use the appropriate ordering for `pow()` - `dt` comes first, then the exponent, i.e.
`float dt_2 = pow(dt, 2.0);`

**Comment by LinasKo** [comment]
Ah, my apologies. Good point.
