### ISSUE TITLE
Can not open link

### ISSUE THREAD

**Issue by ahmedmbakr** [udacity/sdc-issue-reports#1415]
I cannot open the [following link for important gemometry options](https://classroom.udacity.com/nanodegrees/nd013/parts/edf28735-efc1-4b99-8fbb-ba9c432239c8/modules/49d8fda9-69c7-4f10-aa18-dc3a2d790cbe/lessons/9a4b3954-7958-4dc3-bf73-552e191615d3/concepts/47044b2a-a577-4769-8072-89c22b00e3e0).
when I try to open it, it says that I am not subscribed to this nano degree program, and navigates me back to my home screen.

**Comment by mvirgo** [comment]
Merging into #1414
