### ISSUE TITLE
No resources for Lesson 23: extended Kalman filter

### ISSUE THREAD

**Issue by ahmedmbakr** [udacity/sdc-issue-reports#1416]
In [Lesson 23: extended Kalman filter](https://classroom.udacity.com/nanodegrees/nd013-ent/parts/f114da49-70ce-4ebe-b88c-e0ab576aed25/modules/75324158-265f-4b73-bedc-2c30a7ac4db6/lessons/3c8b9b95-78f3-4231-b524-e2d8d387ffb0/concepts/af06ec7e-e32a-441a-b39f-6a3f5c3bcf85) you mentioned that there is a cheat sheet for Sensor Fusion EKF Reference.pdf which I can find in the resources section, but when I opened the resources section I can not see anything.

**Comment by mvirgo** [comment]
Looks like this wasn't added in the Enterprise version of SDC - should be there now :)

**Comment by ahmedmbakr** [comment]
It exists now. Thanks a lot.
