### ISSUE TITLE
Extended Kalman Filter project lecture 9 has a broken link

### ISSUE THREAD

**Issue by ahmedmbakr** [udacity/sdc-issue-reports#1418]
When I open [lesson 9 in extended Kalman filter project](https://classroom.udacity.com/nanodegrees/nd013-ent/parts/f114da49-70ce-4ebe-b88c-e0ab576aed25/modules/75324158-265f-4b73-bedc-2c30a7ac4db6/lessons/5b02bb87-caf5-43c0-b45a-599792af53a1/concepts/f1e4ef0e-dff1-4b0e-b623-30cbacd6aad7) I can not access the [workspaces link](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/ec7a3d6d-24a6-4dad-9f5c-aacd29763e0b/concepts/54aad67c-95ab-44c0-b16e-f92dd377137c). When I open it, it redirects me to my own home page with the error message: "You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?".

**Comment by mvirgo** [comment]
Thanks for noting. These links don't work across different versions of the Nanodegree, so I have removed and otherwise just now note the lesson is found earlier in the program.
