### ISSUE TITLE
Term1-Extended Kalman Filter project not showing RMSE

### ISSUE THREAD

**Issue by SunshengGu** [udacity/sdc-issue-reports#1419]
When I followed the instructions for the EKF project (referring to section 9 in the project lesson), I couldn't display the estimated states (green dots) and the RMSE values to show in the simulator. I have already filled out all the TODO's for this project, including the RMSE function in tools.cpp. What could I be doing wrong here? Below are some information that may point out where I made a mistake:

1. I got the following error message when I ran this line "./install-ubuntu.sh": 
`ln: failed to create symbolic link '/usr/lib/libuWS.so': File exists`

2. When I ran "cmake .. && make" after I made and entered the "build" directory, I got this message:
`CMakeFiles/ExtendedKF.dir/build.make:86: recipe for target 'CMakeFiles/ExtendedKF.dir/src/tools.cpp.o' failed
make[2]: *** [CMakeFiles/ExtendedKF.dir/src/tools.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ExtendedKF.dir/all' failed
make[1]: *** [CMakeFiles/ExtendedKF.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

3. Then when I ran this line "./ExtendedKF", I received this message:
`bash: ./ExtendedKF: No such file or directory`

**Comment by mvirgo** [comment]
Hi Sunsheng,

Please make sure to post this in either your Study Group or Knowledge - Waffle is for bugs in the code included in lessons themselves, not for bugs in your own code or set-up.

The first error will prevent the rest of the program from ever being compiled, so there is not a point to running cmake until after this has fixed. Until it is compiled, the executable file ExtendedKF will not be created.

It sounds like you have previously installed uWebSockets, which is causing a conflict in your libraries. You will want to remove any related files for that and try it again.
