### ISSUE TITLE
Unable to access courses on Udacity

### ISSUE THREAD

**Issue by AbhayKela** [udacity/sdc-issue-reports#1420]
Unable to access any course material at Udacity. It gives an "500 Internal Server Issue"

**Comment by mvirgo** [comment]
Please write into selfdrivingcar-support@udacity.com, this is not the appropriate venue for this.

**Comment by AbhayKela** [comment]
Sorry my bad.
Actually somehow I was directed to Github while raising issue report.
I will keep in mind next time onwards.

Regards
Abhay Kela
+1(585)-642-8338
