### ISSUE TITLE
Link broken inside Kalman filter project READ_ME

### ISSUE THREAD

**Issue by ahmedmbakr** [udacity/sdc-issue-reports#1422]
In the read me file in the kalman filter [project repo in Git Hub](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/blob/master/README.md) there is a broken link in this paragraph:
Please see [this concept in the classroom](https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/16cf4a78-4fc7-49e1-8621-3450ca938b77) for the required version and installation scripts.
When I try to access it, it says "You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?"

**Comment by mvirgo** [comment]
Thanks for pointing this out - we'll have to remove it, as the link actually has to be different between various versions of the program (three term vs. two term version as well as some other types).

**Comment by mvirgo** [comment]
Removed!
