### ISSUE TITLE
How to keep the Session active in the workspace

### ISSUE THREAD

**Issue by Yunying-Chen** [udacity/sdc-issue-reports#1423]
Workspaces automatically disconnect after 30 minutes of inactivity. However, I was running my project on the terminal workspace which took more than 30 minutes but it kept disconnecting in 30 minutes. How to solve this problem?

**Comment by mvirgo** [comment]
Hi Yunying - 

Which project workspace is this for?

**Comment by Yunying-Chen** [comment]
Self-Driving Engineer ND, Term 3, Semantic Segmentation Project.

**Comment by mvirgo** [comment]
In the short-term, I'd suggest trying to run with smaller batch sizes and less epochs, and perhaps saving down the model and re-loading it to continue training. I can also add a script to help keep the workspace open a little longer, although that might take a until next week for me to add.

I'll keep you updated once it's placed in!

**Comment by mvirgo** [comment]
Finally have this added in! If you are still working on this project, we've added a `keep_alive.py` script into the workspace (note you'd have to `reset data` to pull this update - it will delete any code you have worked on, so make sure to save it down or commit it somewhere externally before doing so). This script will keep the workspace alive until killed.
