### ISSUE TITLE
Integral area under a curve: typo

### ISSUE THREAD

**Issue by tarunbelagodu** [udacity/sdc-issue-reports#1427]
(Lesson 2) The answer for question 3 when you click submit shows incorrect calculation. It indicates -2 - -6 = -4
Instead it should read -2- -8 = 6

**Comment by tarunbelagodu** [comment]
Intro SDC ND

**Comment by mvirgo** [comment]
Please open a ticket on the [correct board](https://waffle.io/udacity/isdc_issues_tracker).
