### ISSUE TITLE
Conversion of CNN architecture into image

### ISSUE THREAD

**Issue by vaidhin** [udacity/sdc-issue-reports#1428]
If we wants to convert our custom CNN architecture into image(for  project writeup) like what we see in research papers , here is a online tool which can generate CNN image with your inputs.

http://alexlenail.me/NN-SVG/LeNet.html

it would be really great if you can include this link in project rubrick or may be in project or writeup template. Thank you.

**Comment by mvirgo** [comment]
Nice! Looks like a great visualization tool. I've added it into the rubric as an example.

**Comment by vaidhin** [comment]
Thank you.

Cheers
Vaidhin.
