### ISSUE TITLE
Behavioral Cloning: Keras version of  Car simulator and workspace are not compatible.

### ISSUE THREAD

**Issue by vaidhin** [udacity/sdc-issue-reports#1429]
For Behavioural Cloning project,I trained my model in workspace and opened simulator in GPU enabled work space. 
When I entered command python "drive.py model.h5" , I got this error "You are using Keras version b'2.0.8' , but the model was built using b'2.0.9' Segmentation fault (core dumped).

After having few discussions with mentors it was concluded that workspace is not compatible to test our trained model in the Behavioural cloning project. Fix would be appreciated.

**Comment by mvirgo** [comment]
Hello,

It looks like the classroom is currently using 2.0.9 on jupyter workspaces but 2.0.8 on GPU terminal workspaces. I'll flag for the workspaces team to look into. Thanks for noting!

**Comment by vaidhin** [comment]
Now I got the point......I havent use any pre trained or presaved models.... BUT I trained network without GPU in workspace.. then I enable GPU and tested it. Thanks for your reply.. It saved lot of my effort

**Comment by mvirgo** [comment]
Ah gotcha! Glad that helped. I'd suggest using the GPU to train (even outside of this particular compatibility difference) - it should be 20-30X faster depending on your network! You only want it shut off during the actual coding of the network so as to avoid using up your hours when the GPU isn't actively needed.
