### ISSUE TITLE
Confusing range notation

### ISSUE THREAD

**Issue by rdhelli** [udacity/sdc-issue-reports#1430]
@ Term2/Lesson11/Concept8
There should be a better notation for the position ranges, as it was confusing to read "4 - 6" (as in 4 minus 6). My suggestion is this instead:
"Accounting for a position precision of +/- 1.0 meters, this places our car at an initial position in the range [4..6] (5 +/- 1), [9..11] (10 +/- 1), or [19..21] (20 +/- 1)."

**Comment by mvirgo** [comment]
Valid point. I'm actually changing it to [4, 6] to follow interval notation,  but achieves the same clarifications as you've noted. Thank you!
