### ISSUE TITLE
Dead Links - Lesson12: Tensorflow - 39.Lab Neural Network

### ISSUE THREAD

**Issue by yujika** [udacity/sdc-issue-reports#1431]
Following are dead links
Lesson12: Tensorflow - 39.Lab Neural Network
## Problem 2
 float32 - https://www.tensorflow.org/resources/dims_types.html#data-types
 `tf.truncated_normal()` documentation  - https://www.tensorflow.org/api_docs/python/constant_op.html#truncated_normal
 `tf.zeros()` documentation - https://www.tensorflow.org/api_docs/python/constant_op.html#zeros

**Comment by mvirgo** [comment]
Nice catch! Have now updated these (note that you'd need to `reset data` in the workspace for them to show up)
