### ISSUE TITLE
Incorrect lesson on Extended Kalman filter

### ISSUE THREAD

**Issue by elim1234** [udacity/sdc-issue-reports#1435]
The lesson quoted below indicates that nu was just an alternate notation for u and is therefore zero. This is incorrect. u is an external input to the dynamic model that has nothing to do with process noise.

In fact, the correct equation is X' = Fx + Bu + \nu

Clarification of u = 0
In the above image, the prediction equation is written as x' = Fx + ux 
′
 =Fx+u and x' = f(x,u)x 
′
 =f(x,u). Previously the equation was written x' = Fx + \nux 
′
 =Fx+ν.

It is just a question of notation where \nuν is the greek letter "nu" and "u" is used in the code examples. Remember that \nuν is represented by a gaussian distribution with mean zero. The equation x' = Fx + ux 
′
 =Fx+u or the equivalent equation x' = Fx + \nux 
′
 =Fx+ν calculates the mean value of the state variable xx; hence we set u = 0. The uncertainty in the gaussian distribution shows up in the QQ matrix.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
