### ISSUE TITLE
Typo in term3 capstone project part 7

### ISSUE THREAD

**Issue by EmilePapillon** [udacity/sdc-issue-reports#1436]
On the page, we can read : 

-lowpass.py
A generic low pass filter that can be used in lowpass.py.

It should be :
-lowpass.py
A generic low pass filter that can be used in twist_controller.py.

or something else. But lowpass.py will not be used in itself ...

**Comment by mvirgo** [comment]
It's turtles all the way down.

Fixed :) You are correct that it should instead say `twist_controller.py`.
