### ISSUE TITLE
Car Simulator

### ISSUE THREAD

**Issue by nandG** [udacity/sdc-issue-reports#1437]
Car simulator shortcut not available on desktop

**Comment by mvirgo** [comment]
Hi there, which workspace is this for? 

Have you followed the instructions in the classroom to open up a terminal window on the desktop first?

**Comment by nandG** [comment]
Hi,

Thanks for the prompt response. I did the same and it's working now. Sorry
for the inconvenience.

Thanks & Regards,
Nandita

**Comment by mvirgo** [comment]
No worries, glad it's working for you now :)
