### ISSUE TITLE
MiniFlow - Cost - Cost calculated incorrectly

### ISSUE THREAD

**Issue by sridhar912** [udacity/sdc-issue-reports#144]
It seems the way in which cost function is calculated in wrong. 

cost = MSE(output, ideal_output, 1) # there's only 1 input

It should be rather

cost = MSE(output, ideal_output, 4) # there's only 1 input

**Comment by HaiShaw** [comment]
Folks,

I think the number of samples is 2, given:
x = np.array([[-1., -2.], [-1, -2]])
w = np.array([[2., -3], [2., -3]])
b = np.array([-3., -5])

Should it be:
cost = MSE(output, ideal_output, 2)

**Comment by domluna** [comment]
Thanks for catching this guys, as @HaiShaw brings up the number of samples is 2, each row is a sample. Should also remove the use of the word input here since its use doesn't line up with what is actually meant. 

I'll make an update.

**Comment by domluna** [comment]
`ideal_output` should be a two element vector as well (one result for each example). In addition there should another Linear layer to reduce the output size from 2 to 1.

**Comment by domluna** [comment]
Unfortunately editing quizzes is not a easy as editing other content so I won't be able to fix this right away. Hopefully won't be too long though!

**Comment by sridhar912** [comment]
@domluna yes agreed. It should be 2.

**Comment by giladgressel** [comment]
hey @domluna this came up again today, confused 3 of us for awhile and we went to make a waffe and found this.   Can you at least add instructor notes or something simple/quick and dirty to alert people for the time being until you can edit the quiz directly?

**Comment by domluna** [comment]
The new quiz fixes this.
