### ISSUE TITLE
Bugs in 2019 Term2, Lesson 11, Trajectory Generation, Hybrid A* C++ implementation solution

### ISSUE THREAD

**Issue by wpiHWzhao** [udacity/sdc-issue-reports#1448]
The solution provided seems has bug,in which if I modify the map to block the path to the goal, the solution would still report "Success" in some cases

**Comment by wpiHWzhao** [comment]
![hbastar_problem.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc11f6decd7860013b4e64c/125516c66e82c728ace21e0d46e0969b309682bbb0f9ad4ca651f5996b0a65633b0ba92e7391a172fd172351565d47a4470b5e4ca8fd8d79a6b63c708c5e08bfd07f4366846c4ff8e7df46f554f832815d87b7b68b49c4e13b21e48f8b4f381e000ac4.png)

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
