### ISSUE TITLE
No keras module found in the workspace

### ISSUE THREAD

**Issue by david89** [udacity/sdc-issue-reports#1449]
I have been able to train my model for the behavioral cloning project just fine. However, yesterday when I tried to do so, I found out that the keras and tensorflow modules are no longer installed in the workspace.

**Comment by rcwang128** [comment]
same here...

**Comment by HenryHXYao** [comment]
same for me

**Comment by mvirgo** [comment]
Thanks for noting this, looking into today with a fix hopefully by tomorrow.

**Comment by mvirgo** [comment]
Hi all - 

The issue with the Behavioral Cloning project should now be resolved - you should be able to get the corrected environment by *refreshing* your workspace, although you may need to *reset data* if that does not work (make sure to save down your project prior to doing so!).

Please let me know here if you continue to experience this issue.

**Comment by rcwang128** [comment]
Thank you very much.
