### ISSUE TITLE
miniFlow Lesson 13 code error in 2nd code snippet

### ISSUE THREAD

**Issue by HaiShaw** [udacity/sdc-issue-reports#145]
The line below:

        for n in self.outbound_nodes:

 should be 

        for n in self.outbound_layers:

--------------------------------
class Linear(Layer):
    def __init__(self, inbound_layer, weights, bias):
        Layer.__init__(self, [inbound_layer, weights, bias])

    def forward(self):
        inputs = self.inbound_layers[0].value
        weights = self.inbound_layers[1].value
        bias = self.inbound_layers[2].value
        self.value = np.dot(inputs, weights) + bias

    def backward(self):
        # Initialize a partial for each of the inbound_layers.
        self.gradients = {n: np.zeros_like(n.value) for n in self.inbound_layers}
        # Cycle through the outputs. The gradient will change depending
        # on each output.
        for n in self.outbound_nodes:
            # Get the partial of the outbound layer with respect to this layer.
            grad = n.gradients[self]
            # Set the partial of the loss with respect to this layer's inputs.
            self.gradients[self.inbound_layers[0]] += np.dot(grad, self.inbound_layers[1].value.T)
            # Set the partial of the loss with respect to this layer's weights.
            self.gradients[self.inbound_layers[1]] += np.dot(self.inbound_layers[0].value.T, grad)
            # Set the partial of the loss with respect to this layer's bias.
            self.gradients[self.inbound_layers[2]] += np.sum(grad, axis=0, keepdims=False)

**Comment by domluna** [comment]
Thanks @HaiShaw. Fixed.
