### ISSUE TITLE
No Keras and Tensorflow modules anymore

### ISSUE THREAD

**Issue by rcwang128** [udacity/sdc-issue-reports#1450]
Have been using Workspace for CarND term1 Behavioral Cloning project and everything seems fine working under GPU mode. Starting from today,  Keras and Tensorflow modules are no longer there. Tried to install them manually but failed by missing other libraries. Non-GPU mode seems fine.

**Comment by rcwang128** [comment]
Even I installed CarND-Term1-Starter-Kit, there's no Keras and Tensorflow anymore... PLEASE HELP

**Comment by mvirgo** [comment]
Duplicate issue of #1449
