### ISSUE TITLE
Confusing equations for Distortion correction

### ISSUE THREAD

**Issue by dalmia** [udacity/sdc-issue-reports#1451]
In the Camera Calibration part of Term 1, the equations given in the notes for Lecture 7 are pretty confusing. Some of the variables used are have not been defined earlier, which makes the equations ambiguous and unclear. This link provides a better explanation: https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

It would be helpful for students to add this change.

**Comment by mvirgo** [comment]
Hi Aman! Can you please be specific about which variables are used that have not been defined before?

Thank you!

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
