### ISSUE TITLE
Error: Linking of CarND-Kidnapped-Vehicle-Project fails without GPU mode on Udacity workspace

### ISSUE THREAD

**Issue by einrob** [udacity/sdc-issue-reports#1453]
Changing to GPU Mode (+ cleanup.sh) + build.sh results in a successful build.

https://knowledge.udacity.com/questions/34179

Thus development of the project is only possible in GPU mode, forcing students to burn unnecessary GPU time without need.  

Compile output: 

./build.sh 
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /opt/conda/bin/cc
-- Check for working C compiler: /opt/conda/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/conda/bin/c++
-- Check for working CXX compiler: /opt/conda/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/workspace/CarND-Kidnapped-Vehicle-Project/build
[ 33%] Linking CXX executable particle_filter
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_want@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_set_connect_state@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSLv23_server_method@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_pending@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSLv23_client_method@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SHA1@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_set_accept_state@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_CTX_set_default_passwd_cb@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/lib/libuWS.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
CMakeFiles/particle_filter.dir/build.make:120: recipe for target 'particle_filter' failed
make[2]: *** [particle_filter] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/particle_filter.dir/all' failed
make[1]: *** [CMakeFiles/particle_filter.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mvirgo** [comment]
Hi there! We are closing down this Waffle board, so please do not post new items here.

**Comment by einrob** [comment]
Hi Michael,


Best,
R

**Comment by einrob** [comment]
Hi Michael,

ok, I followed a link in the knowledge base.

The Issue still remains. Do you transferred the ticket to your new issue
tracker or just closed it?


Best,
Robert
