### ISSUE TITLE
bugs in CarND term2 lesson3,40.Solution:coding the full filter

### ISSUE THREAD

**Issue by henryhxyao** [udacity/sdc-issue-reports#1454]
Solution:coding the full filter. line 159-184. The input variables "landmark_positions" and "distance_max" are not actually used in the function "observation_model". It should be updated to avoid misleading to students

**Comment by HenryHXYao** [comment]
![lines159-184](https://user-images.githubusercontent.com/2600730/56213487-b3392500-608e-11e9-8cb7-7b4f12a1cad0.JPG)

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms.

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
