### ISSUE TITLE
Miniflow Section 13 backpropagation - possible unnecessary step

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#148]
I see that there is an unnecessary step of computing the partial derivative of the cost with respect to the input vector X. This derivative is never used and is logically never needed as we only care about how the cost changes in response to the weights(and biases).

Code:
```
 # Set the partial of the loss with respect to this layer's inputs.
            self.gradients[self.inbound_layers[0]] += np.dot(grad_cost, self.inbound_layers[1].value.T)
           
```

**Comment by domluna** [comment]
It might not be used directly in the lesson right now, but, if we had additional layers it would be used since `X` would not be the data in this case, but rather the output from the previous layer. So, we would need to calculate this gradient to propagate backwards through that layer(s).

**Comment by domluna** [comment]
Also some quizzes will be updated to have 2 Linear layers so it will actually come into play.
