### ISSUE TITLE
Dashboard shows "Project Due 8 days ago" although I have finished it

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#149]

**Comment by Deborah-Digges** [comment]
<img width="872" alt="screen shot 2016-11-12 at 6 16 48 pm" src="https://cloud.githubusercontent.com/assets/3866405/20237864/68cedc56-a904-11e6-81ce-7ebbac1f013e.png">

**Comment by dhruvp** [comment]
@deborah-digges can you confirm that you have passed the project?

**Comment by Deborah-Digges** [comment]
Hi Dhruv. This issue no longer happens. It used to happen in the first few weeks of the nano-degree

**Comment by dhruvp** [comment]
Great. Thanks for letting me know!
