### ISSUE TITLE
confusing wording in "hough transform to find lanes"

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#15]
the way the page is structured, you get some code, with BAD parameters, then you see a picture that is the product of GOOD parameters and then you see the following text.

"Here I have chosen some good parameters for HoughLinesP (different from those listed above) and applied a region of interest mask"

I almost didn't read the text, I pretty (naturally I think) assumed the code produced the picture.  It was only on a careful re-reading that I realized the picture was not produced by the code.

This is a very unintuitive presentation.  Would be better to show a bad picture and say "these parameters dont' work" you need to find the good parameters so you can make THIS picture and show the good picture.

i foresee student confusion here

**Comment by ryan-keenan** [comment]
Great point!  I changed it now to reflect your suggestion, i.e., the messy result is shown after the code example.  Thanks!

**Comment by giladgressel** [comment]
update looks great! much more clear
