### ISSUE TITLE
Less Magic Numbers

### ISSUE THREAD

**Issue by hkorre** [udacity/sdc-issue-reports#151]
Having less magic numbers in code (lessons & assignments), will make learning much easier.

Example: Convolutional Neural Networks > 6. TensorFlow Convolution Layer

There are all these magic numbers for shape. You try to explain them below but it would be much easier to follow if those numbers were just defined as variables with comments next to them.

**Comment by Brok-Bucholtz** [comment]
@hkorre 

I removed all the magic numbers for _[TensorFlow Convolution Layer](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/601ae704-1035-4287-8b11-e2c2716217ad/concepts/0377449f-ce0f-436b-8e11-2cdfefe20995)_, except I kept the stride numbers to make it easier to talk about.  I'm planning on doing the same for all the assignments and lessons, but I want to make sure this is what you're looking for.
