### ISSUE TITLE
refactor instructions for running tensorflow lab

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#158]
in the current incarnation it can be a little confusing which instructions to follow in the tensorflow lab.  Windows is listed twice, as in mac OSX.  Some users have gotten confused and skipped a few steps as result.

It would most likely be better to have the instructions in 3 ( perhaps 2) categories.  Windows --> all instructions for windows
mac/linux --> all instructions for mac/linux

even if this creates redundant instructions it will add clarity and reduce user confusion.  A user only has to follow one set of instructions, they look for their heading (OS) and follow this.

**Comment by Brok-Bucholtz** [comment]
@giladgressel 

We're planning on using a single docker image for all our projects and labs for term 1.  When this is out and fully tested, we'll change the instructions for using the docker image.
