### ISSUE TITLE
p2 traffic signs - data visualization

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#159]
current instructions are
### Feel free to use as many code cells as needed.

this is pretty brief and non informative.  Especially since this course has no pre-reqs, students without a strong data science / ML background may be unsure what to do here

**Comment by domluna** [comment]
Step 1: Dataset Exploration
Visualize the German Traffic Signs Dataset. This is open ended, some suggestions include: plotting traffic signs images, plotting the count of each sign, etc. Be creative!

Is at the start of the section.

Maybe adding suggestions for plotting libraries and such would be helpful.

**Comment by domluna** [comment]
There's more detail in this section now, various links to matplotlib and a code cell with matplotlib inline plotting ready to go. Longer term an entire concept on visualisations and plotting would be really nice.
