### ISSUE TITLE
TensorFlow documentation was not enough for me to install docker and run TensorFlow on Windows

### ISSUE THREAD

**Issue by swwelch** [udacity/sdc-issue-reports#16]
[Filed on behalf of Alex]. Classroom link here: https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a8adf8ea-39b6-4fa3-ac26-0870f1ef6ae8

For some reason shell was not started after I run docker. The following command:
docker exec -it <mycontainer> bash
from link: 
http://stackoverflow.com/questions/30172605/how-to-ssh-into-a-docker-container
helps me.

**Comment by joshuacook** [comment]
I agree with the above, but I don't believe the submitted solution is sufficient. I actually see an issue both with building a valid image and with having good documentation. I have submitted a PR to address the first. Once we get that resolved, documentation will fall out of that.

**Comment by Brok-Bucholtz** [comment]
@swwelch 

The instructions to install the dependencies have been removed, instead we are using a docker image with everything already setup!  This will make setup/installation a lot easier.
