### ISSUE TITLE
Add section on saving/restoring models to Deep Learning section

### ISSUE THREAD

**Issue by thomasantony** [udacity/sdc-issue-reports#161]
It is very easy to get unusable checkpoint files when using tf.train.Saver to save trained models from Jupyter notebooks. Each time we run the cell defining the network, the internal variable names change (unless the 'name=' parameter is used). This results in checkpoint files that are unable to correlate with the graph defined by Tensorflow once the notebook is restarted. 

this can be solved to some extent by calling tf.reset_default_graph() before defining the variables, placeholders etc. 

A comprehensive section on this topic would be very useful as students will then have the option of tinkering with multiple architectures without fear of losing networks they spent hours training.

**Comment by Brok-Bucholtz** [comment]
@thomasantony 

This content is currently in beta testing and should be out this week.

**Comment by Brok-Bucholtz** [comment]
@thomasantony 

The loading and saving content has been added:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/b516a270-8600-4f93-a0a3-20dfeabe5da6/concepts/ef0cdafb-57ec-497b-8f45-11c142c367d7
