### ISSUE TITLE
MiniFlow - SGD Solution: Recommended epochs doesn't lead loss to zero

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#164]
I am not sure if this is an error or not. But it says 

"I'm putting the same quiz below again. If you haven't already, set the number of epochs to something like 1000 and watch as the loss decreases to nearly 0!"

Setting the epochs to 1000 results in loss going till 15/16 only and not nearly 0.

**Comment by domluna** [comment]
Thanks @sahiljuneja! That's a leftover from the old quiz. Updated the text.

**Comment by sahiljuneja** [comment]
Thanks!
