### ISSUE TITLE
Quiz: Tensor Flow Linear Function - Typos and [possible] bugs

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#168]
This quiz was added recently, today I believe.

Noticed the following problems

1. sandbox and sandbox_solution line 42/43 state `# Linear Function WX + b` but it should be `# Linear Function XW + b`

2. quiz_solution has the output for linear function `return tf.matmul(input, w) + b`. Shouldn't it be `return tf.add(tf.matmul(input, w), b)`? The former works as a solution, but in the lesson where we were introduced to Math in tensorflow, it wasn't mentioned if we could still use normal arithmetic operations. So either the solution should be edited or the TesorFlow Math quiz should mention that arithmetic operations are valid, perhaps?

3. If in quiz.py the output of the linear function is set as `return tf.add(tf.matmul(input, w), b)`, there are times when the test run produces the following error.

```
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7fcc731a9048>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 532, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'
```

**Comment by Brok-Bucholtz** [comment]
@sahiljuneja 

Thanks for letting us know!  I made the changes to the quiz for issue 1 and 2.  You'll have to click "Reset Quiz" in order to see the changes.  We are currently looking into the 3rd issue.

**Comment by sahiljuneja** [comment]
@Brok-Bucholtz Thank you!

The "Quiz: TensorFlow ReLUs" in the "Deep Neural Networks" lecture has the same issue as Point 2. above. The quiz's solution has the arithmetic implementation rather than tensorflow one.

**Comment by Brok-Bucholtz** [comment]
@sahiljuneja 

I replaced `+` with `tf.add()` in "Quiz: TensorFlow ReLUs", "Deep Neural Network in TensorFlow", and "TensorFlow Dropout".  I created a task for issue 3 and I'm talking with the appropriate team to fix it.  Let use know if you see anything else.
