### ISSUE TITLE
simulator csv log file decimal mark comma

### ISSUE THREAD

**Issue by merriaux** [udacity/sdc-issue-reports#170]
With the simulator (on a french ubuntu installation), in the generated csv log file the decimal mark is a comma (',') not a point ('.'). And the separator to split the colons are also comma (',').

Did you do this on purpose ? or this using of french ubuntu installation ? Because it isn't convenient to parse the file !

 Few lines of obtained log file :

/home/merriaux/udacity/lesson14/simulator-linux/data/IMG/center_2016_11_24_08_11_00_780.jpg, /home/merriaux/udacity/lesson14/simulator-linux/data/IMG/left_2016_11_24_08_11_00_780.jpg, /home/merriaux/udacity/lesson14/simulator-linux/data/IMG/right_2016_11_24_08_11_00_780.jpg, -0,08581576, 0,1286689, 0, 12,1822
/home/merriaux/udacity/lesson14/simulator-linux/data/IMG/center_2016_11_24_08_11_00_884.jpg, /home/merriaux/udacity/lesson14/simulator-linux/data/IMG/left_2016_11_24_08_11_00_884.jpg, /home/merriaux/udacity/lesson14/simulator-linux/data/IMG/right_2016_11_24_08_11_00_884.jpg, -0,08581576, 0,1286689, 0, 12,67823

**Comment by domluna** [comment]
@merriaux was the issue that was solved by setting the language to UTF-8? In general I'm not sure if something can be done in simulator to alleviate this. Doing the `export LC_ALL=en_US.UTF-8` trick might be the best option.
