### ISSUE TITLE
quiz tensorflow linear function - A critique

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#171]
instructions have errors.  Gonna add to this issue with pics etc.  so if it looks empty, it's cause i just started it as a place to jot down what I see as I do this quiz
<img width="880" alt="screen shot 2016-11-25 at 4 24 58 pm" src="https://cloud.githubusercontent.com/assets/6275366/20636923/ba2eeac4-b32b-11e6-98b7-c6b3ad6faf9e.png">
So this picture doesn't make much sense to me.  What does it mean to add the X's and Y's together? and why doesn't it work?  Drawing the lines visually doesn't teach the student anything, you need to spell out what the computation would be.

Saying "turns out this doesn't work" doesn't mean anything.  It doesn't cause any thinking.  It just says "don't do this", so why then did you even show it to me??

<img width="843" alt="screen shot 2016-11-25 at 4 26 54 pm" src="https://cloud.githubusercontent.com/assets/6275366/20636930/fa7e7a9a-b32b-11e6-8322-fd468623bf81.png">
This picture has some error. Your matrix doesn't line up with your weights. In the graph you have W12, in the matrix you have W21.

I think in an MxN matrix, we'd have [[(1,1),(1,2),(1,3)][(2,1),(2,2),(2,3)]]

Your notation doesn't make any sense to me.  In the bottom row you have (2,1),(2,2)(3,2)  the bottom left is (2,1) so it's 2nd row, 1st column.  The bottom right is (3,2) so it's 3rd column , 2nd row.
be consistent.  This is wrong.

<img width="857" alt="screen shot 2016-11-25 at 4 32 42 pm" src="https://cloud.githubusercontent.com/assets/6275366/20636963/cdc31294-b32c-11e6-84b2-9f1128af7bbc.png">

What?  What line?  What are you talking about?  I think an example with points in a graph showing the line wx+b wouldn't hurt.  I know that sounds obvious, but trust me, I doubt it is for a lot of students.
Students will not easily make the connection between graph form (cicles and lines) and actual equations which is what they associate with "lines"

<img width="877" alt="screen shot 2016-11-25 at 4 36 13 pm" src="https://cloud.githubusercontent.com/assets/6275366/20636977/4f3bdc16-b32d-11e6-8269-772241ff61b2.png">

I think you need to teach _why_ a lot more in these quizes.  WHY are we switching forms?  Otherwise whats the point of telling me?  Just saying "we do this" doesn't teach anything, it still requires students to go outside and learn the _reasons_ for things. 

<img width="799" alt="screen shot 2016-11-25 at 4 46 22 pm" src="https://cloud.githubusercontent.com/assets/6275366/20637034/c16f8fde-b32e-11e6-8730-55e43c8ca6a5.png">

Again, _why_ is the bias simpler?  Why do you use random weights but don't need to randomize the bias?  Teach don't tell!

**Comment by dhruvp** [comment]
@Brok-Bucholtz can you please take a look at this?

**Comment by dhruvp** [comment]
@dsilver829 also ^^

**Comment by Brok-Bucholtz** [comment]
@giladgressel 

Thanks for all the feedback!  Here's a quick update:
1) I replaced the `y = x` graph with text that better transitions to `y = Wx`.  I need to add some labels to the graph.
2) I changed the "W21" to "W12"
3) Currently working on this one
4) Writing this one up
5) I explained why bias doesn't need to be randomized.  I need to add why 0 over other other numbers like 0.1

**Comment by dhruvp** [comment]
@Brok-Bucholtz is this closed?

**Comment by ChrisShepherd81** [comment]
The typo with the matrix value W21 instead W12 still exits in the picture with bias.

**Comment by mdesksmartin** [comment]
in the section tf.truncated_normal(), the variable n_features is not explained and "features" doesn't appear anywhere else on the page.  would be great to have a sentence about why that is there.  what is the shape of 'weights'?  (of course i could go to the tensorflow docs and look up that method but would be nice to have it explained in the flow of the page)

**Comment by Brok-Bucholtz** [comment]
The major issues have been fixed. I created JIRA tasks for items that we still need to work on.  We will work on these for an upcoming sprint.
