### ISSUE TITLE
Change in order of couple of lectures in Deep Neural Networks.

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#172]
In the lesson "Deep Neural Network"

We have "5. Network of ReLUs" followed by a TensorFlow quiz.

Then a few lectures later we have "10. 2-Layer Neural Network" which essentially explains the network introduced in "5. Network of ReLUs"

So shouldn't the 2-layer NN lecture be right after Network of ReLUs? 

It seems out of place otherwise, and changing that order to have them one after the other will help solidify something right after it was introduced perhaps?

**Comment by Brok-Bucholtz** [comment]
@sahiljuneja,

Good idea changing the order.  I moved the 2-layer NN section right after the "Network of ReLUs".  Let us know if you see anything else.
