### ISSUE TITLE
CNN in depth sectin

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#173]
I think this section has a very good grounding.  I like that it shows how a golden retriever would be classified by humans.  However I think the following is very misleading and perhaps even incorrect

<img width="833" alt="screen shot 2016-11-27 at 4 23 10 am" src="https://cloud.githubusercontent.com/assets/6275366/20648365/7f4323b0-b459-11e6-926e-0d87721e3d9f.png">

>It breaks up an image into a hierarchy of more and more complex objects and finally attempts to classify an image by combining the larger, more complex objects in the image.

This line isn't really true in a strict sense.  This is true in the sense that the sentence describes the _result_ of a CNN, however it's not what a CNN is doing.  It is the amazing result of what a CNN produces, but we don't _intend_ this result, we are simply happy to receive it.

Basically I think the idea of a CNN is to incorporate the location of pixels in relationship to each other when using an NN.  In a traditional feed-forward NN, the image is flattened and the information encoded by the  location of pixels which are adjacent or perhaps diagonal to each other, is essentially lost.
CNN's make up for this loss of data by using the sliding filter in order to capture adjacency of pixels.

however these sliding windows have weights which are _initialized_ randomly by the CNN!!!  This is extremely important!  The sentence/section which I am concerned about does _not_ make this clear.  A CNN is not designed to find anything in reality.  It's just designed to have a sliding window which we _hope_ will find something useful.  

this line here
>The first layer is the lowest level in the hierarchy where we classify very small parts of the image into simple shapes like horizontal and vertical lines and simple blobs of colors.

Makes it sound we somehow intentionally architecht this into a CNN.  In fact, we don't do anything except run the code, then sit back and be amazed that a CNN is doing this really cool behavior.  We aren't intentionally creating this system, it's just happening on it's own, which is why we call it artificial intelligence.

I think this entire point is lost here, and people will have the wrong intuition of what CNN's do.

In reality a CNN is just a NN with a lot of of sliding windows that keep pixel information.  It gets initialized with random weights and those weights are optimized using SGD.  The entire learning process happens because of this, and when successful we see these layers of learning. 

This needs to be stressed, the result of a CNN, the special cool learning, it all falls out of SGD and backprop.  It happens by itself!! This is what makes DNN's so powerful.

I think this point is entirely lost in the current explanation

again, we have a slightly misleading statement here

>But why connect a single patch to multiple neurons in the next layer? Isn’t one neuron good enough?

>We need multiple neurons because a patch can have multiple interesting characteristics that we want to capture, and having multiple neurons per patch allows us to capture these different characteristics. These characteristics include different shapes within a patch and different colors within a given patch.

The reality is, "we do use multiple neurons because we _hope_ to find interesting characteristics"   Let's not pretend we know what we are looking for, in fact it's as stupid as it sounds.  Trial and Error, guess and check.

**Comment by ravindar** [comment]
For example this is a better format and explanation i found. http://cs231n.github.io/convolutional-networks/

**Comment by dhruvp** [comment]
I agree with your point that we should make it clear that a CNN isn't "designed" to do something like this but that it learns this on its own. I've gone through and changed the language and made sure to iterate a few times that the behavior we see is not intentional but learned. Thanks for your link @ravindar as well.

**Comment by dhruvp** [comment]
Example of some changes:

````This is intuitively what a CNN learns to do. It learns to break up an image into a hierarchy of more and more complex objects and finally classify an image by combining the larger, more complex objects in the image. In our case, the levels in the hierarchy are:```

```However, it's important to note that the CNN isn't programmed specifically to do something like this. Rather, it learns on its own to recognize such objects through simple trial and error with gradient descent! What's amazing is how this mirrors our own intuition for recognizing objects even though we never program a CNN with such information.```

```What's important here is that we are grouping together adjacent pixels and treating them as a collective. In a simple, dense non-convolutional network, we would have simply ignored this adjacency and connected every pixel in the input to a neuron in the next layer. In doing so, we would not have taken advantage of the fact that pixels in an image are close together for a reason and have special meaning. By taking advantage of this local structure, we allow our CNN to learn on its own to take advantage of local patterns like shapes and objects in an image.```

```These characteristics include different shapes within a patch and different colors within a given patch. However, note once more that the CNN isn't programmed to capture multiple characteristics per patch. Rather, it once again learns on its own to do this just by gradient descent.```
