### ISSUE TITLE
CNN in depth continued

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#174]
>If we want a dog that’s in a top left patch to be classified in the same way as a dog in the bottom right patch, we need the weights corresponding to those patches to be the same so that they are classified the same way. This is exactly what we do in CNNs. The weights we learn for a patch are shared across all patches in a given layer.

it's not clear if the weights are being shared across a single patch that is being slid across the picture, or if the weights are being shared against all patches used on the picture.  I.E. we often use multiple filters, which as far as I understand is redundant patches, in hopes of finding different features.

**Comment by dhruvp** [comment]
Agreed. I changed it to the following:

he weights and biases we learn for a given output layer are shared across all patches in a given input layer. Note that as we increase the depth of our filter, the number of weights and biases we have to learn still increases as the weights aren't shared across the output layers.
