### ISSUE TITLE
visualizing CNN's -- language is strange/misleading

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#175]
I find the language style used in this section also a bit misleading / strange.

>The third layer is going to pick out a combination of features in layer 2 that are even more complex. These include things like grids, and honeycombs (top left), wheels (second row, second column), and even faces (third row, third column).

"This layer _is_ going to,"  this again makes this sound like some sort of plan that was pre-ordained.  

My concern is that students will think you can decide ahead of time what each layer will be classify or discover.  Students may ask questions like "how do you know that this layer will grab these features" or "how can you architect your layers so you can get X Y Z features?"  Unless I'm entirely wrong, we don't have this ability

In general these quizes use words like "indeed, finally, going to" and all them write a narrative instead of a scientific explanation of what is happening.  In my best understanding the Author is trying to simplify CNN's with a narrative so the student can easily grasp what is happening.  However, the larger truth is being obfuscated and I believe this is a very very grave mistake and disservice to our students.  Can you imagine a student getting hired and not really understanding what a DNN does?

**Comment by dhruvp** [comment]
This feedback is very fair and I appreciate your point that we should make it clear that the CNN behavior is learned. I've gone through and tweaked the language to address that.
