### ISSUE TITLE
weekly checkin was borked

### ISSUE THREAD

**Issue by ravindar** [udacity/sdc-issue-reports#176]
<img width="294" alt="screen shot 2016-11-27 at 10 16 09 am" src="https://cloud.githubusercontent.com/assets/423903/20649305/9fa238cc-b48a-11e6-8969-e5220747a3d9.png">

The weekly checkin was borked earlier. I submitted my feedback and there was no response and when i went back in, i had to resubmit it. i kept doing this, only to come in next day to find a thousand responses in the screen. 

now i can't get my mentor to respond, coz he probably thinks i am crazy

**Comment by swwelch** [comment]
Hi Ravindar, I think this is fixed now. Let me know if you still see this problem!
