### ISSUE TITLE
Error in ConvolutionalNetwork in TensorFlow

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#177]

**Comment by rm51** [comment]
A student noticed that it is conv3=maxpool2d(conv2) instead of conv3=maxpool3d(conv3)

**Comment by Brok-Bucholtz** [comment]
@rm51 

Thanks for letting us know.  I changed "conv3=maxpool2d(conv2)" to "conv3=maxpool3d(conv3)".
