### ISSUE TITLE
Convolutional Neural Networks: Visualizing CNNs issues

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#178]
For Layer 1 we have the caption 
```

The first layer of the example CNN. The top left grid (to the left of the Layer 1 text) represents the shapes and gradients that are being classified in the first layer. Each set of 9 squares in the lower grid represent images that are classified by the corresponding square in the top left grid (to the left of the Layer 1 text).

```

Isn't the last line the other way around? Shouldn't each set of 9 squares in the lower grid lead to the classified image in the top left grid? The text above implies that the set of 9 squares represents images that get classified based on the square in the top left grid. 

Plus the text below that states 

```
The 3x3 cluster of squares below the top most square represent example image patches that led to the given classification
```

which seems to be the opposite of the image caption.
[Or am I getting confused because of the phrasing here?]

For Layer 2 (and also 3),

The two images that we have shouldn't have the same dimensions. Based on the information provided from the first layer, a single square gets classified because of a set of 3x3 images. So the second image in Layer 2 should have more images (each square in the first image should have corresponding 3x3 squares in the second image, which isn't so), right? [This is difficult to explain for me because the course page doesn't have appropriate terminology for these squares]

**Comment by sahiljuneja** [comment]
cc - @dhruvp

**Comment by dhruvp** [comment]
@sahiljuneja I reworked this page and hopefully that clarifies some of this. Can you take a look and let me know?

**Comment by sahiljuneja** [comment]
@dhruvp Yes, the edit helps explain my first query here. Thank you for that.

Although, regarding the second question above.

The layers 2,3, and 5. This is the slight confusion I have - 

In the edited text for Layer 1, you write

```
The below grid of images all activated the -45 degree line.
```

So that grid activates that one square showing the -45 degree line. When we look at Layers 2 to 5, the second image in all of those have the same dimensions where 1 square in the image of patterns, corresponds to 1 square in the image with the objects. Instead of how we showed that a 3x3 grid of images corresponded to 1 square with the line pattern. So are those images just to show the pattern and the original object, are those to show that the second grid of images actually causes the layer to activate resulting in the patterns?

[Did the above help to explain my point better?]

**Comment by dhruvp** [comment]
Yeah - it's a weird issue with the source images. The first layer has 3 example images per square but the other ones have only one example image per square.

So it's exactly as you pointed out - "1 square in the image of patterns, corresponds to 1 square in the image with the object".
