### ISSUE TITLE
Convolutional Neural Networks: TensorFlow Convolution Layer issues

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#179]
We are provided the code but introduced new concepts which aren't explained at all.

1. Selecting the weights and bias. There is not intuitive explanation for how and why we are selecting those. 

2. We are given this text 
```
The code above uses the tf.nn.conv2d() function to compute the convolution with weight as the filter and [1, 2, 2, 1] for the strides. TensorFlow uses a stride for each input dimension, [batch, input_height, input_width, input_channels].
```

This is completely new. We covered strides across one layer. Why all of a sudden do we have multiple strides for different dimensions, and what does that imply?

**Comment by sahiljuneja** [comment]
cc - @dhruvp

**Comment by dhruvp** [comment]
@domluna could you help here?

**Comment by domluna** [comment]
> We covered strides across one layer. Why all of a sudden do we have multiple strides for different dimensions, and what does that imply?

It's a nuance of the TensorFlow API. Generally we only care about strides in height and width dimensions so we can safely set the stride of `batch` and `input_channels` to 1. The API isn't all that intuitive, took me a while to realize what was going on.

**Comment by sahiljuneja** [comment]
@domluna Thanks for the explanation.  That was helpful! If possible please consider adding these smaller details in the course as well.

**Comment by dhruvp** [comment]
We added a bit of this information in the page. Closing as a result!
