### ISSUE TITLE
Convolutional Neural Networks: CNNs in Depth issues

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#180]
1. We are introduced to output depth (k). But no explanation on how and why we select a specific k value. Even in the code in the TensorFlow lesson later, we set k to 64 with no explanation why.

2. We are introduced to strides, and then in another lecture we related how increasing the stride affects the dimensions of the output. But there is no explanation on how those reduced dimensions actually make a difference. Why a stride of 1 is different than a stride of 2.

3. In the subsection "Dimensionality" something called "Volume" is talked about, and we are given a formula. I don't know what the significance of this is and how it is useful. I am not sure of what Volume implies in this context.

**Comment by sahiljuneja** [comment]
cc - @dhruvp

**Comment by dhruvp** [comment]
Added the following for 3:

```
Given what we've learned so far, how can we easily calculate the volume (i.e. the number of neurons) of each layer in our CNN? Given our input layer has a volume of W, our filter has a volume (height * width * depth) of F, we have a stride of S, and a padding of P, the following formula gives us the volume of the next layer: (W−F+2P)/S+1. Knowing the dimensionality of each additional layer helps us understand how large our model is and how our decisions around filter size and stride affect the size of our network.
```

**Comment by dhruvp** [comment]
Added this for 2
```
In practice, the stride tends to be a hyperparameter you tune. Increasing the stride can reduce the size of your model by reducing the number of total patches each layer observes. However, this naturally can come with some accuracy costs.

```

Does that help?

**Comment by sahiljuneja** [comment]
@dhruvp Thank you! Yes, that was extremely helpful.

**Comment by sahiljuneja** [comment]
Hey @dhruvp Just checked one of the lessons corresponding to the above. The "Dimensionality" part wasn't updated.
