### ISSUE TITLE
Udacity Classroom Interface Feature Request

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#181]
Currently, the interface has a search option, but it seems the search feature doesn't actually search through each individual lesson. 

For example, I wanted to find a lecture which might have mentioned "Fully Connected Layer", but I can't easily search for it, so I now might have to go through multiple lessons to find it. 

I think such a feature might be useful. And perhaps, for lessons with only videos, a few keyword could be defined by Udacity's content creators to make them searchable? Although I understand how time consuming that might be.

**Comment by dhruvp** [comment]
We're working on this! We have this issue filed in our UI board so going to remove it from here. Thanks for the suggestion!
