### ISSUE TITLE
Convolutional Neural Networks: Convolutions Continued Issues

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#182]
The video talks about connecting the Deep Regular Neural Net to "Fully Connected Layers". 

I hope I am not mistaken, but I don't recall any lecture discussing fully connected layers before this. (Another issue I added a while back mentions how a search feature would be helpful). Even in my own personal notes for this course, I can't find any reference. 

Perhaps that should be explained?

**Comment by sahiljuneja** [comment]
cc - @dhruvp

**Comment by dhruvp** [comment]
Added an instructor note addressing this. Thanks for the feedback!
