### ISSUE TITLE
Enrollments during Woodstock

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#183]
A lot of my Mentees seem to have enrolled with Udacity in the wild year 1969.

![screen shot 2016-11-26 at 12 24 50](https://cloud.githubusercontent.com/assets/12371494/20667028/8dccf0c8-b567-11e6-8fc1-e406e2f91f56.png)

Either there's some weird time travel incident going on, I have a uniquely and un-probabilistic shuffle of senior students, or something is off with recording the enrollment dates. :wink:

**Comment by swwelch** [comment]
Hi! I think this has been resolved now.
