### ISSUE TITLE
Incomplete instructions in Training the Network and Validating Your Model

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#188]

**Comment by rm51** [comment]
The instructions say:
Install Python Dependencies (conda install …)

But for keras it should be 

pip install keras. 

If you try 

conda install keras you get 

PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - keras

You can search for packages on anaconda.org with

    anaconda search -t conda keras

**Comment by dsilver829** [comment]
Done! Thanks for the report.
