### ISSUE TITLE
Traffic Sign Classification, data preprocess notebook page not found

### ISSUE THREAD

**Issue by psleang** [udacity/sdc-issue-reports#19]
https://github.com/udacity/traffic-signs/blob/master/Process-Traffic-Signs.ipynb

**Comment by domluna** [comment]
Are you following from the README in the repo or from the classroom? The README in the repo wasn't updated it looks like, I'll do that now.

**Comment by psleang** [comment]
I couldn't have access to the classroom, so do a few of the other mentors.

**Comment by psleang** [comment]
I meant I couldn't access the content, when I open up the classroom, it is blank, there is no content listed.

**Comment by domluna** [comment]
Hmm, I updated the udacity traffic-signs repo so it should be the same as the classroom now.

**Comment by domluna** [comment]
Closing this since it's no longer applicable with the new version.
