### ISSUE TITLE
Mentor panel is stuck on "Check In"

### ISSUE THREAD

**Issue by gpavlov2016** [udacity/sdc-issue-reports#190]
There are two subproblems here:
1. When filling up the text in Check In edit boxes and clicking "Send Responses to Mentor" there is no feedback whether the message was sent. My expectation would be either get out of the "check in" mode automatically or display a message that the text was sent.
2. No way to get out of "Check In" mode. For example I opened the mentor panel because I have new messages from my mentor however "Check In" mode is displayed and I can't see my mentor's messages. Doesn't make sense to do actual check-in in this situation - need a way to close the checkin mode.

**Comment by dhruvp** [comment]
I believe this should be fixed now @gpavlov2016. Can you please confirm?

**Comment by gpavlov2016** [comment]
I didn't see the check in dialog since issue submission so can't check it
