### ISSUE TITLE
Pandas are needed for Lab: Feature Extraction

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#191]

**Comment by rm51** [comment]
If you try to run the lab: Feature Extraction you get 
ImportError: No module named 'pandas'

It would be good to include that as things that need to be installed in the installation instructions.

**Comment by domluna** [comment]
The [starter kit concept](https://github.com/udacity/CarND-Term1-Starter-Kit) will be published soon which has software for all the projects/labs, that'll fix this. However, I'll look into using the `csv` package instead of `pandas` for this particular script.
