### ISSUE TITLE
My Output looks nothing like the sample output in Lab: Feature Extraction

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#192]

**Comment by rm51** [comment]
I would like to delete this. I just saw below. 

It's unlikely your output will be exactly the same as shown here.

My output was almost for the other ones, so that's why I was confused.

**Comment by domluna** [comment]
Yeah, it's because depending on how you define the layer the output will change. Setting the random seed explicitly doesn't really help either since if you use a different initializer the weight will be different anyway.

**Comment by domluna** [comment]
Notice without making the random seed static the output will change each time you run the program.
