### ISSUE TITLE
Lesson 2. Finding Lane, 4 Quiz: Color selection

### ISSUE THREAD

**Issue by fabricemineit** [udacity/sdc-issue-reports#193]
img = (mpimg.imread('test.png')*255).astype('uint8')

should be

image = (mpimg.imread('test.png')*255).astype('uint8')

**Comment by muddassir235** [comment]
+1

**Comment by muddassir235** [comment]
'img' causes error.

**Comment by joejanuszk** [comment]
Seconded. Changing `img` to `image` fixes it.

On another note, the line `plt.imshow(color_select)` occurs twice.

**Comment by ryan-keenan** [comment]
Thanks for catching this!  The change has been made
