### ISSUE TITLE
Lesson 2. Finding Lane, 3. Color Selection Code Example

### ISSUE THREAD

**Issue by lapolonio** [udacity/sdc-issue-reports#194]
Change existing comment: 
# Define our color selection criteria

to:

# Define our color selection criteria
# Note: if you run this code, you'll find these are not sensible values!!
# But you'll get a chance to play with them soon in a quiz

**Comment by mdesksmartin** [comment]
+1

**Comment by ryan-keenan** [comment]
Thanks for the suggestion!  This change has been made
