### ISSUE TITLE
Nitpicking:  Miniflow - Lesson 10 Python Quiz.  Wrong feedback text.

### ISSUE THREAD

**Issue by RWMostert** [udacity/sdc-issue-reports#195]
In Lesson 10, where we implement the code for the mean square error calculation, the feedback given on a correct/working submission reads: 
"Great job!  Your Sigmoid layer looks good :)"

This refers to a previous lesson (the programming quiz on the sigmoid layer) and isn't applicable to the current quiz (which is on the MSE and implementing MSE).

Tiny error.

**Comment by domluna** [comment]
Fixed. Thansk @RWMostert !
