### ISSUE TITLE
Traffic Sign Classifier Project steps do not work on Windows

### ISSUE THREAD

**Issue by MaximeLeclerc** [udacity/sdc-issue-reports#2]

**Comment by MaximeLeclerc** [comment]
I've tried to make the project work on Windows for a few hours now without success.

**Comment by dalex01** [comment]
The same is for me. See just a black screen.

**Comment by domluna** [comment]
@MaximeLeclerc can you provide more details? Is the problem installing something or does the code not run? Problem loading data? I'm not familiar with Windows so anything would be helpful!

**Comment by dalex01** [comment]
I see only black screen after I load app:
https://gyazo.com/97f1510beae7bf1a02826c11681aad13

**Comment by MaximeLeclerc** [comment]
I'm currently trying to complete the project with Ubuntu, I'll give more details about this attempt once I'm done

**Comment by domluna** [comment]
@dalex01 it looks like that's the behaviour cloning project.

**Comment by dalex01** [comment]
Yep, my mistake. 
Should I open separate issue on it?

**Comment by domluna** [comment]
If one is not already open sure.

**Comment by swwelch** [comment]
Since there is another issue already open for the behavioral cloning project, I'm going to close this issue.
