### ISSUE TITLE
quiz : pooling layer 4 mean pooling

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#202]
correct answer is 

1.375, .875, 5, 4

however I'm getting "wrong answer" on submit, when viewing answer, it shows me the above

**Comment by domluna** [comment]
might be due to the space in between commas?

**Comment by giladgressel** [comment]
oh ok.. so I removed comma's and I added `0` so it became `0.875` and that was accepted.
sort of silly

**Comment by domluna** [comment]
you're right, need to make the answer regex more robust.

**Comment by domluna** [comment]
Brushed up on regex. This now accepts all the issues described here and more! (along with the other pooling quiz)
