### ISSUE TITLE
In the Keras lab, float should not be compared using ==

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#203]
I am getting the following message with keras lab `AssertionError: The range of the input data is: -0.5 to 0.5`. It looks like we are comparing floats with `==` not with `abs(a - b) < 1e-10`. Here is the correct assert:

assert(abs(np.min(X_train) + 0.5) < 1e-10 and abs(np.max(X_train) - 0.5) < 1e-10), "The range of the input data is: %.1f to %.1f" % (np.min(X_train), np.max(X_train))

**Comment by domluna** [comment]
The latest notebook uses this type of assertion, `math.isclose` specifically.
