### ISSUE TITLE
Requirement to have both zero mean and -0.5 -> 0.5 range is confusing

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#205]
It looks like data is centered, so we get zero mean for free. Which is what forums tell me. However not knowing that data is zero centered, it was a challenge for me to come up with a method that will get me both zero mean and -0.5 0.5 range. It should not mention zero mean.

**Comment by deniskrut** [comment]
Sorry for confusion - I am talking about Keras lab here

**Comment by avs20** [comment]
This may be confusing and a clear wording can be like input data has zero mean and the input values range  from -0.5 to 0.5

**Comment by domluna** [comment]
The zero mean requirement has been removed in the latest notebook, the test for it was broken. It's now just getting the input in between -0.5 and 0.5.
