### ISSUE TITLE
We are trying to print history.history['acc'] as float in Keras lab

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#206]
What we have:

assert(history.history['acc'][0] > 0.5), "The training accuracy was: %.3f" % history.history['acc']

What it should be:

assert(history.history['acc'][0] > 0.5), "The training accuracy was: %.3f" % history.history['acc'][0]

**Comment by domluna** [comment]
This should be fixed in the latest version of the notebook. Also the assertion is now for all the last history value, which makes more sense.
