### ISSUE TITLE
convolution in TF

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#207]
this bit makes no sense to me
<img width="838" alt="screen shot 2016-11-29 at 10 30 40 pm" src="https://cloud.githubusercontent.com/assets/6275366/20742164/93608f32-b683-11e6-94dd-1ed8f7cc7c3c.png">

First, the stride has already been defined as 4 parameters in an array in previous slides, so I'm guessing this content was written earlier and not edited when the other content was added after.

but more confusing is really this line 
"it's good practice to remove the images or features you want to skip from the dataset than to use stride"

wut?  Sounds like the author is suggesting we _might_ want to consider using stride to skip data for testing or something?  images _or_ features?  Those aren't really apples to apples are they?

so confused here.

**Comment by Brok-Bucholtz** [comment]
Hey @giladgressel,

You are correct.  Content was added after this which mention the 4 parameters.  We're working on replacing this with smaller sections.  Thanks for letting us know!

I removed the line "Previously I talked about..." and made it more clear what the text is suggesting.  Let me know if I should add more clarification.
