### ISSUE TITLE
In AlexNet lab, traffic_sign_inference.py should extract features

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#208]
traffic_sign_inference_solution.py:
probs = AlexNet(resized)

traffic_sign_inference.py by in the following way:
probs = AlexNet(resized, feature_extract=False)

I assume the solution is correct and task is not, since there is no mentioning of feature_extract flag in the lab.

**Comment by domluna** [comment]
The `feature_extract` argument is by default `False` so the two lines of code you have there are technically the same thing. But it should be consistent, I'll make the change and add a note about the `feature_extract` argument.
