### ISSUE TITLE
Alt path suggestion in 'Keras -> Install Keras (Step 4)'

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#209]
Current: 'Create `~/.keras/keras.json` to configure Keras to use TensorFlow.'
Suggestion: change path to `~/anaconda/envs/keras/keras.json`.
The instructions previously asked students to install Keras in a conda environment. In that case, the path would be `~/anaconda/envs/keras/keras.json`. The previous path is not valid because `~/.keras` would not exist unless the student had installed Keras separately and not only in the conda environment.

**Comment by domluna** [comment]
I think `~/.keras/keras.json` would still work though.

**Comment by domluna** [comment]
Also, Keras has been using TensorFlow by default for a while now. So this might not even be necessary anymore.
