### ISSUE TITLE
Mini-Flow Lab Typo in Implement Linear Node

### ISSUE THREAD

**Issue by deanofthewebb** [udacity/sdc-issue-reports#21]
The Implement Linear Node section has a typo in the variable Z. First, it says Z is an n x p matrix, then it says that Z is a m x p matrix. I think the first variable is supposed to be W.

**Comment by deanofthewebb** [comment]
Link: https://drive.google.com/open?id=0B58rHqPbkpjwbGY1WXRYYWpWV1k

**Comment by Brok-Bucholtz** [comment]
@deanofthewebb 

Hey Dean, this has been fixed in the newest version of the class.  Thanks for letting us know!
