### ISSUE TITLE
Typo: Capitalize Session

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#210]
Here:

![screen shot 2016-11-24 at 09 23 31](https://cloud.githubusercontent.com/assets/12371494/20802354/14b34eb2-b7ec-11e6-9659-91ad4bc3a254.png)

**Comment by Brok-Bucholtz** [comment]
@martin-martin 

Good job spotting this!  I change "tf.session()" to "tf.Session()".  Let use know if you see anything else.
