### ISSUE TITLE
Mentor-Dashboard Progress Bug

### ISSUE THREAD

**Issue by Seananigans** [udacity/sdc-issue-reports#211]
The progress area in my dashboard is oscillating between different amounts of progress in the nanodegree.
ie. Sometimes the student is shown to have completed the Lane Lines project, while other times they are shown to be done almost through the entire course.

**Comment by swwelch** [comment]
Hi! Could you please file this on Christine's Trello board if it isn't there already? Since this isn't a student facing problem, I'm going to close it here. Thanks!
