### ISSUE TITLE
Error in Miniflow lecture 12

### ISSUE THREAD

**Issue by ajsmilutin** [udacity/sdc-issue-reports#212]
Equations 10, 11, and 12 of Miniflow lecture 12 are wrong.

If you look at the equation 10, the gradient of C, can not be multiplied with  delta w nor delta b. The matrix multiplication cannot  be used, neither can element-wise multiplication be used, since they are trying to multiply. Also, the equations 11 and 12 are wrong because we are trying to subtract two vectors with different lengths.

There are more details on this forum post:
https://carnd-udacity.atlassian.net/wiki/questions/20743390/there-seems-to-be-an-error-in-miniflow-lecture-12

**Comment by domluna** [comment]
Hi @ajsmilutin this section has been redone from the ground up so this is not longer an issue. Thanks for the report though!
