### ISSUE TITLE
Finding Lanes: clearer instructions on setting python environment

### ISSUE THREAD

**Issue by CassLamendola** [udacity/sdc-issue-reports#213]
In instructions for setting up python 3 environment in conda, it says to run source command to enable the environment. It doesn't mention that every time a new terminal session is created, the source command needs to be executed again in order to properly set the environment.

**Comment by domluna** [comment]
@CassLamendola It'll be added as documentation to the starter kit which you could find [here](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/8c82408b-a217-4d09-b81d-1bda4c6380ef/concepts/4f1870e0-3849-43e4-b670-12e6f2d4b7a7). Thanks for the issue.
