### ISSUE TITLE
Convolutional Neural Networks: Matching Correct Output Shape

### ISSUE THREAD

**Issue by blackelectricity** [udacity/sdc-issue-reports#214]
Convolutional Neural Networks, Part 30:

Input is shape 1,4,4,1 and the desired output shape is 1,2,2,3.  The goal of the lab is to enter a padding type, strides shape, and filter shape to get it to output the correct shape.

The correct answer accepted is filters sized 2,2,1,3 with SAME padding and 1,2,2,1 strides. 

Another model with filters sized 3,3,1,3 with VALID padding and 1,1,1,1 strides also produces the correct output shape of 1,2,2,3 - however, it is not accepted by the internal submission unit tests which run some other shape checks which do not allow this answer to pass.

**Comment by domluna** [comment]
Thank for posting this @blackelectricity. It should be fixed now.

**Comment by blackelectricity** [comment]
Great, Thanks!
