### ISSUE TITLE
Lesson 8 - 13 (Quiz: TensorFlow Linear Function) text issues

### ISSUE THREAD

**Issue by ibrasho** [udacity/sdc-issue-reports#216]
> where the weights, `W`, determine the influence of `x` at **prediction** each `y`.

Should be:
> where the weights, `W`, determine the influence of `x` at **predicting** each `y`.

Or:
> where the weights, `W`, determine the influence of `x` at **the prediction of** each `y`.

**Comment by Brok-Bucholtz** [comment]
@ibrasho 

Thanks again for spotting these errors!  I changed "prediction" to "predicting".
