### ISSUE TITLE
show time estimate for each lesson on home page

### ISSUE THREAD

**Issue by xysun** [udacity/sdc-issue-reports#219]
Right now I can only see time estimate for next lesson upon finishing the last section of previous lesson.

Is it possible to show time estimate for each lesson on home page? It'll make easier for me (and I believe for others) to come up with study schedules.  

Thanks.

**Comment by dhruvp** [comment]
@xysun I think this could be cool. Let me see what we can do on our end and thank you for the suggestion!

**Comment by jessluls** [comment]
Hi there! This is actually a known issue in the Car classroom. Our engineering team is working on an update that will allow times to be published in the syllabus, as they are in other NDs. Thanks for the suggestion!
