### ISSUE TITLE
The order of RGB is wrong in Exercises of Canny Edges and Hough Transform lessons in P1

### ISSUE THREAD

**Issue by Harry-Zhi** [udacity/sdc-issue-reports#220]
In these two exercises, we want to change the given RGB color image to gray image through the built-in function "cv2.cvtColor" in OpenCV. 
The default codes in the exercises are as below: 
`import matplotlib.image as mpimg

import cv2

image = (mpimg.imread('exit_ramp.png')*255).astype('uint8')

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)`

However, we should notice that the matplotlib save the RGB image's three channels as (R,G,B) but the opencv save the color image as (B,G,R).

So, instead of using the code above ,we should use the parameter 'COLOR_RGB2GRAY' instead of  'COLOR_BGR2GRAY)'.

Or, we can use opencv built-in function to read in images and then use the mode COLOR_BGR2GRAY.

Either way is okay but the default codes in not proper.

Hope someone can check this issue.

**Comment by ryan-keenan** [comment]
Thanks for noticing this!  It's been changed now
