### ISSUE TITLE
Comment bug in lesson 7.6 miniflow.py

### ISSUE THREAD

**Issue by qz2** [udacity/sdc-issue-reports#221]
In line 51, inbound_nodes should be inbound_neurons.

**Comment by domluna** [comment]
Can you provide more info? Maybe a screenshot. I can't seem to find that line.

**Comment by blackelectricity** [comment]
In MiniFlow - Forward Propagation
Inside the Quiz Coding Box for "miniflow.py", in the code that's already provided.
In the "Add" python class, in the constructor:

   class Add(Neuron):
       def __init__(self, x, y):
           # You could access `x` and `y` in forward with
           # self.inbound_nodes[0] (`x`) and self.inbound_nodes[1] (`y`)      <---------------------
           Neuron.__init__(self, [x, y])

That should say self.inbound_neurons[0] and self.inbound_neurons[1]   
it's "neurons" not "nodes"

**Comment by domluna** [comment]
Thanks @blackelectricity. Made the fix, might have to reset the quiz to see it.
