### ISSUE TITLE
Moviepy Anaconda Kernel Death

### ISSUE THREAD

**Issue by JonathanCMitchell** [udacity/sdc-issue-reports#222]
Conda list provides
moviepy                   0.2.2.11                  <pip>

When I run the following command in jupyter notebook:
```
from moviepy.editor import VideoFileClip
```
My kernel dies

**Comment by JonathanCMitchell** [comment]
When I go into the terminal and activate my python3 environement and run the following command:
``` 
import moviepy
```
I do not get an error. But when I run
```
from moviepy.editor import VideoFileClip
```
I get the following error:
```
>>> from moviepy.editor import VideoFileClip
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

**Comment by JonathanCMitchell** [comment]
I believe it has something to do with ffmpeg.osx. 

When I ran it on my mac it said:
```Imageio: ffmpeg.osx was not found on your computer; downloading it now.```

**Comment by JonathanCMitchell** [comment]
I have tried reinstalling numpy, upgrading pip and reinstalling moviepy. I have two versions of pip.....pip and pip3. Pip simply saves stuff to my local machine and pip3 saves stuff to my conda environment.

**Comment by ryan-keenan** [comment]
Is this still a problem for you?

**Comment by JonathanCMitchell** [comment]
Solved. I updated conda using the command:
I had to delete mkl and numpy and re-install them
Then update all anaconda plugins (conda update --all)
Then update anaconda itself (conda update anaconda)
I can't say which piece actually solved it but it works now.

**Comment by domluna** [comment]
@JonathanCMitchell I'm curious what instructions you followed to install this all in the first place. Was it https://github.com/udacity/CarND-LaneLines-P1 or https://github.com/udacity/CarND-Term1-Starter-Kit or something else?

**Comment by JonathanCMitchell** [comment]
@domluna I don't run the docker environment. I used the first link: https://github.com/udacity/CarND-LaneLines-P1
I am running Ubuntu 16.04

**Comment by domluna** [comment]
Gotcha. Although the starter kit isn't just for Docker, it has a version for plain Anaconda as well https://github.com/udacity/CarND-Term1-Starter-Kit#anaconda.
