### ISSUE TITLE
Grey overlay on top of content when font size is increased

### ISSUE THREAD

**Issue by html5cat** [udacity/sdc-issue-reports#226]
Latest Safari on macOS Sierra
Screenshot:
https://www.dropbox.com/s/czk55gd6xhacud0/Screen%20Shot%202016-12-06%20at%204.26.15%20PM.png?dl=0

**Comment by dhruvp** [comment]
Hey Yuriy,

We do that to make it clear you need to dismiss the left bar to free up the real estate you need. Just collapse the left bar by clicking the left arrow in the top left of your screen and you'll see the grey overlay disappear.

**Comment by html5cat** [comment]
There's plenty of padding on the right so I'd rather you get rid of that. 
Really hard to read otherwise - fonts are too small so I end up clicking menu on and off a lot.
I think users should be in control of that rather than forced.
