### ISSUE TITLE
Tensorflow class is using a soon to be deprecated method

### ISSUE THREAD

**Issue by blackelectricity** [udacity/sdc-issue-reports#228]
The Tensorflow module uses:
`   init = tf.initialize_all_variables()`
I believe this will be deprecated soon and replaced by:
`   init = tf.global_variables_initializer()`

**Comment by blackelectricity** [comment]
This would be a larger change and I think this update would require the quiz interpreters to run a newer version of Tensorflow. 

Since this is a new nano-degree though, it might just be worth simply mentioning it in the learning materials.

**Comment by Brok-Bucholtz** [comment]
@blackelectricity 

As you mentions, this requires us to upgrade our in class quiz back-end to TensorFlow r0.12.  Once, this is done, we'll update rest of the content to r0.12.  I'll keep you in the loop.

**Comment by Brok-Bucholtz** [comment]
@blackelectricity,

We've updated the classroom quizzes to TensorFlow 12.1 and changed all instances of `tf. initialize_all_variables()` to `tf. global_variables_initializer()`.
