### ISSUE TITLE
Unused, unexplained code line in lesson Adv.Lane Finding / 9. Finding Corners

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#229]
Hi,

in lesson Adv.Lane Finding / 9. Finding Corners there is a Python code where line 9 seems to be unnecessary, unused and unexplained. It should be deleted or explained if we will need it later. Also an explanation needed why its 2nd dimension is 3 (and not 2 as we are operating on 2D image).

Code line 9:
objp = np.zeros((nx*ny,3), np.float32)

Regards, 
BartMate

PS: It seems it is explained in one of the next videos.
So please, at least, add a comment that it will be explained and used later.

**Comment by ryan-keenan** [comment]
Thanks for catching this!  That line has now been removed
