### ISSUE TITLE
Possible issue with video file solidWhiteRight.mp4 in Project 1

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#23]
I and another person had problems with that video file. Is it possible that there's something wrong with it in GitHub. The issue went away though after redownloading so maybe it just downloaded incorrectly to our machines even though everything else downloaded ok?

**Comment by rm51** [comment]
https://carnd-udacity.atlassian.net/wiki/display/CAR/questions/4784375/getting-os-error-for-regionofinterest-function

https://carnd-udacity.atlassian.net/wiki/questions/4784166/quicktime-cant-open-the-white.mp4-file

**Comment by ryan-keenan** [comment]
Thanks for the report!  I just tried downloading it and it worked ok, so for now we'll keep an eye on it but not change anything just yet.
