### ISSUE TITLE
Possible error in the description of 6. Pinhole Camera Model of lesson Advanced Lane Finding

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#230]
Hi,

there are some formulas in the description part of "6. Pinhole Camera Model" in lesson "Advanced Lane Finding". 

* I think it needs more explanation: e.g. the formula which computes the corrected (undistorted) image coordinates needs 'r' which is defined on the corrected(undistorted) image coordinates. If we know 'r' already, with some angle-computation we get the result, we do not need the formula. So how we get 'r'???

* Maybe the reason that it is not understandable is that it has a mistake (I am not expert of the area, I just tried to check it on the internet like widipedia [https://en.wikipedia.org/wiki/Distortion_(optics)] ):
I think the formulas given in the description is the formula for getting the distorted image from the undestorted one, i.e. this is the model of distortion. To get the undistorted image we have to apply the inverse of this formula (which is not trivial, according some papers sometimes an iterative algorithm is used, in some other cases a (reverse) mapping is stored).

So either make the description clearer, or correct it if it has really a mistake. 

Anyway, as we use built-in functions for undistortion, this part can be skipped as well.

Regards,
  BartMate

**Comment by ryan-keenan** [comment]
Thanks for reporting this issue!  We have added some text explaining "r" and giving more details on the distortion correction.  Hopefully this clears up any confusion!
