### ISSUE TITLE
inconsistent naming convetion for googlenet vs inception

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#233]
the slide is called GoogLeNet, the discussion is about GoogLeNet and that it uses inception.

David says "get your hands dirty with googlenet"

next page calls it inception.  I think this is pretty confusing.
![image](https://cloud.githubusercontent.com/assets/6275366/21032941/ed04de6e-bd61-11e6-810c-cc0e2d5c6044.png)

**Comment by domluna** [comment]
In the title it's now Inception (GoogLeNet). It's much more commonly known as Inception.
