### ISSUE TITLE
Threshold-inconsistency in lesson Advance Lane Finding

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#235]
Hi,

In my understanding the function 

cv2.threshold(img,thr,max,cv2.THRESH_BINARY) 

works as follows: It goes through each pixels of img, compares it with thr. If the pixel value <= thr, it will be 0, otherwise max.

In '27. HLS Quiz', it sounds like the 3rd parameter is an upper threshold, like in previous parts (like '20.Magnitude of gradient') where this type of code was used:

binary_output[(gradabs > mag_thresh[0]) & (gradabs < mag_thresh[1])] = 1

These two codes are not equivalent. The first gives back image with values 0 or 255 using only one threshold, this latter one gives back 0 or 1 with two thresholds.

Therefore I think in 27. the check is errornous, because it expect a result which was created cv2.threshold which considers only the lower threshold. Moreover it is not binary in a sense that in the result images there are 255-s instead of 1-s.

Please correct the quiz, the expected image (i.e. the checking codes), and make the different quizes consistent with each other.

Thanks,
  BartMate

**Comment by ryan-keenan** [comment]
Thanks for reporting this.  Indeed it looks like we were using `cv2.threshold()` incorrectly.  I have changed the quizzes accordingly and replaced the code walkthrough video with text in the Sobel Operator section that refers to this function.  I will also pull the HLS color selection code walkthrough once a suitable text replacement has been made.
