### ISSUE TITLE
Underdefined quizes in lesson Advanced Lane Finding

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#236]
Hi,

in those quizes where we should use lower and upper threshold it is not defined in the text if we should include or exclude the given values (i.e. if < or <=; > or >= should be used). In python often we use left-closed, right-open intervals, so some intuition can be that we should use thr0<=x<thr1. But this is not the case.

Nevertheless, please, define the missing info in the description of the quiz.

Thanks,
  BartMate

**Comment by ryan-keenan** [comment]
Thanks for catching this!  I have now included instructions to either use `cv2.threshold()` or, if thresholding with Boolean operators, to use an exclusive lower (`>`) and inclusive upper (`<=`) threshold for consistency with the `cv2` function.
