### ISSUE TITLE
Mentor Panel shows after every page change

### ISSUE THREAD

**Issue by pcarney8** [udacity/sdc-issue-reports#238]
Any time i move around in a Lesson, or in the Term or back and forth, the Mentor Panel shows and I have to click keep hiding it after every page switch

**Comment by pcarney8** [comment]
not sure if this has anything to do with it, but i'm getting a few warnings: 

[Amplitude] WARNING: Property key "courseKey" with invalid value type undefined, ignoring amplitude-3.4.0-min.gz.js:2 
[Amplitude] WARNING: Property key "courseKey" with invalid value type undefined, ignoring amplitude-3.4.0-min.gz.js:2 
[Amplitude] WARNING: Property key "conceptKey" with invalid value type undefined, ignoring amplitude-3.4.0-min.gz.js:2 
[Amplitude] WARNING: Property key "partKey" with invalid value type undefined, ignoring amplitude-3.4.0-min.gz.js:2 
[Amplitude] WARNING: Property key "moduleKey" with invalid value type undefined, ignoring amplitude-3.4.0-min.gz.js:2
[Amplitude] WARNING: Property key "lessonKey" with invalid value type undefined, ignoring

**Comment by swwelch** [comment]
Thanks for filing this! I've passed the bug information on to our engineering team, and I'll update this ticket when I know more.
