### ISSUE TITLE
Hello Tensor World: comment and code don't match

### ISSUE THREAD

**Issue by skh** [udacity/sdc-issue-reports#239]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a8adf8ea-39b6-4fa3-ac26-0870f1ef6ae8 and https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/83f16208-ff1a-4179-aef7-c3f079bb5f9c have this code snippet:
```
# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')
```
The comment is wrong, the object that's being created is called `hello_constant`, not `tensor`. It is just a minor thing, but can really confuse people who are confronted with a lot of new stuff to learn.

**Comment by skh** [comment]
Similar on https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a222f778-c0aa-45f0-97bc-7b3caf940f5b

The comment in `quiz.py` says:
```
# ToDo: Feed the x tensor "Hello World"
```
but the instructions say that the integer `123` should be used.

**Comment by Brok-Bucholtz** [comment]
@skh,

Thanks for the feedback.  I changed `# Create TensorFlow object called tensor` to `# Create TensorFlow object called hello_constant`.  As for the comment in "quiz.py" was also changed.  You need to click the "Reset Quiz" button to see the changes in the quiz.  Let use know if there is anything else.
