### ISSUE TITLE
Non-deterministic TensorFlow bug in Lesson 8.8 quiz

### ISSUE THREAD

**Issue by ghost** [udacity/sdc-issue-reports#242]
Error message:
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f0fc85c19b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 532, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'

Steps to reproduce:
- Go to Introduction to TensorFlow
- Go to 8. Quiz: TensorFlow Math
- Click Test Run multiple times

**Comment by Brok-Bucholtz** [comment]
@qz2 

We're currently looking into this.

**Comment by Brok-Bucholtz** [comment]
@ghost

Thanks for reporting this.  We've finally fixed this in all the quizzes.  It took a lot of debugging, but we got it!
