### ISSUE TITLE
Standford should be Stanford in Lesson 8.11

### ISSUE THREAD

**Issue by qz2** [udacity/sdc-issue-reports#243]
Go to Introduction to TensorFlow
Go to Let's make a deal
"Standford's Deep Learning Tutorial" should be "Stanford's Deep Learning Tutorial"

**Comment by Brok-Bucholtz** [comment]
@qz2,

I changed "Standford's" to "Stanford's".  Thanks for spotting this.  Let us know if you see anything else.
