### ISSUE TITLE
"the a normal" should be "a normal" in Lesson 8.13

### ISSUE THREAD

**Issue by qz2** [udacity/sdc-issue-reports#244]
Go to Introduction to TensorFlow
Go to 13. Quiz: TensorFlow Linear Function
"random numbers from the a normal distribution" should be "random numbers from a normal distribution"

**Comment by Brok-Bucholtz** [comment]
@qz2,

I changed "the a normal distribution" to "from a normal distribution".  Thanks for letting us know.
