### ISSUE TITLE
P1. Wrong RGB order in helper function

### ISSUE THREAD

**Issue by SergeyBykov1** [udacity/sdc-issue-reports#247]
Both matplotlib.image.imread and moviepy.editor use RGB order for images. But your first helper function is
def grayscale(img):
cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

This is misleading and can hugely affect the quality of all pipeline.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  This color conversion was  a remnant of a previous incarnation of the project.  I have now changed the default grayscaling in the helper function to be `cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)`
