### ISSUE TITLE
Lesson 2 Exercise Image Location

### ISSUE THREAD

**Issue by da7th** [udacity/sdc-issue-reports#251]
the code uses a png image, while trying to R+Click and save as gives a jpg image, i've tried downloading and running on the jpg locally and the answer of[200,200,200] did not work, it completely removed the lane lines from the slightest changes

**Comment by ryan-keenan** [comment]
The quiz uses a png and does `image = (mpimg.imread('test.png')*255).astype('uint8')` but if you use a jpg you can just say `image = (mpimg.imread('test.png')`.   By default the pngs get read in on a scale of 0 to 1 (hence the multiply by 255) but jpgs come straight in as 8 bit images.
