### ISSUE TITLE
No licenses for confluence.

### ISSUE THREAD

**Issue by mihirrajput** [udacity/sdc-issue-reports#252]

**Comment by asheeshv** [comment]
I just signed up and observed the same issue.

**Comment by ashoni** [comment]
Same issue for me

**Comment by praphullpaliwal** [comment]
Same issue for me

**Comment by swwelch** [comment]
Hi! This has been resolved now; there is a new forum instance. If you haven't already, please make an account here: https://carnd-forums.udacity.com/signup.action

Thanks for your patience!
