### ISSUE TITLE
There are no available licenses for Confluence

### ISSUE THREAD

**Issue by rioffe** [udacity/sdc-issue-reports#253]
I am getting the following error when trying to create a Confluence account: "We are currently unable to complete your sign up. There are no available licenses for Confluence"

**Comment by timtobey** [comment]
I have the same problem

**Comment by arsalanrahi92** [comment]
Same error here

**Comment by doublebind** [comment]
Same here!

**Comment by RameshIyer2016** [comment]
I have the same issue.

**Comment by sstuteja** [comment]
I have this issue as well

**Comment by swwelch** [comment]
Hi All! Thanks, we are working with Confluence to figure out why this is happening. I'll update here as we know more!

**Comment by joas77** [comment]
Same problem here

**Comment by hannaraenam** [comment]
Is there a way we can follow backlogs and get updates as there are updates?

**Comment by minakian** [comment]
Same problem here.

**Comment by cafmenace** [comment]
I am having the same issue

**Comment by renjibijoy** [comment]
Same.

**Comment by aaraadhya** [comment]
I have the same issue

**Comment by praphullpaliwal** [comment]
I am also facing the same problem

**Comment by micronix** [comment]
same

**Comment by sachitv** [comment]
same

**Comment by arunesh** [comment]
Any updates ?

**Comment by swwelch** [comment]
Hi! This has been resolved now; there is a new forum instance. If you haven't already, please make an account here: https://carnd-forums.udacity.com/signup.action

Thanks for your patience!
