### ISSUE TITLE
Confluence Sign Up

### ISSUE THREAD

**Issue by bingo9** [udacity/sdc-issue-reports#255]
Confluence sign up page says it's all out of licenses and cannot sign up

**Comment by anageswa** [comment]
I've observed the similar issue as well.

**Comment by aghasd5** [comment]
got the same erorr.

**Comment by AhmedElshaarany** [comment]
Yup, same here

**Comment by brahmwindeler** [comment]
Same here. :(

**Comment by konstmsu** [comment]
Same here: "We are currently unable to complete your sign up. There are no available licenses for Confluence."

**Comment by anuj123** [comment]
I had same issue

**Comment by nkhori** [comment]
Same issue here

**Comment by fiibbb** [comment]
Same issue here.

**Comment by ChrisHuie** [comment]
Same here

**Comment by RobinD89** [comment]
same here

**Comment by halolee** [comment]
Same here. 

When try to signup with confluence, it shows:

"We are currently unable to complete your sign up. There are no available licenses for Confluence."

**Comment by paramaggarwal** [comment]
In Slack it was updated that the Confluence limit on number of users has been reached, so they will be setting up a self-hosted version. Till then you can access via the credentials shared in the #announcements channel.

**Comment by swwelch** [comment]
Hi! This has been resolved now; there is a new forum instance. If you haven't already, please make an account here: https://carnd-forums.udacity.com/signup.action

Thanks for your patience!
