### ISSUE TITLE
Confluence sign-up

### ISSUE THREAD

**Issue by qhommes** [udacity/sdc-issue-reports#256]
I cannot sign up for confluence.

**Comment by paramaggarwal** [comment]
In Slack it was updated that the Confluence limit on number of users has been reached, so they will be setting up a self-hosted version. Till then you can access via the credentials shared in the #announcements channel.

**Comment by swwelch** [comment]
Hi! This has been resolved now; there is a new forum instance. If you haven't already, please make an account here: https://carnd-forums.udacity.com/signup.action

Thanks for your patience!
