### ISSUE TITLE
image type and typo

### ISSUE THREAD

**Issue by da7th** [udacity/sdc-issue-reports#257]
image = mpimg.imread('exit_ramp.jpg')
the file on the site is "exit-ramp.png"

**Comment by ryan-keenan** [comment]
thanks for reporting this!  we are porting these quizzes / exercises over to Python 3 presently and we'll get the image inconsistencies cleaned up.

**Comment by ryan-keenan** [comment]
This should be all taken care of now.  Thanks again.
