### ISSUE TITLE
Quiz question from step six should offer an alternative option instead of yes only

### ISSUE THREAD

**Issue by cosmin-cojocar** [udacity/sdc-issue-reports#258]
Right now, the quiz question from Welcome section at step 6 has only a "Yes" as an option. I'm thinking that is we add a "No - I couldn't do it" we will catch all this bugs that are added to Waffle and save some user time & dev time also. What do you think? Thanks!

**Comment by ryan-keenan** [comment]
Good idea.  Changed to radio buttons and added a "no" option that prompts students to scroll back up and follow the links to get signed up.
