### ISSUE TITLE
No available licenses for Confluence

### ISSUE THREAD

**Issue by stathopoan** [udacity/sdc-issue-reports#259]
When creating account in Confluence an error is displayed: 

"We are currently unable to complete your sign up. There are no available licenses for Confluence."

**Comment by xmfcx** [comment]
Same error here.

**Comment by wewtaco** [comment]
I got the same error.

**Comment by swwelch** [comment]
Hi! This has been resolved now; there is a new forum instance. If you haven't already, please make an account here: https://carnd-forums.udacity.com/signup.action

Thanks for your patience!
