### ISSUE TITLE
Typo: MiniFlow / 2. Playing with Networks - (again?) wrong # of iterations

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#26]
A 2nd time the use of "500,000 iterations" further down in "Building a Classifier" Point 3.

I am not completely sure that this is a typo, since it comes back, but 500,000 iterations would take extremely long and I don't believe students would make it run, especially because 500 iterations bring already to a reasonable result.

?

**Comment by Brok-Bucholtz** [comment]
@martin-martin 

Yea, I changed both to 500 iterations.  Thanks for pointing it out.
