### ISSUE TITLE
import cv2 error

### ISSUE THREAD

**Issue by LeotisBuchanan** [udacity/sdc-issue-reports#261]

**Comment by LeotisBuchanan** [comment]
I get following error for color selection quiz (section). when I follow the instructions to install anaconda and install opencv. When I enter the command import cv2 at the python prompt i get the following error:

ImportError: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: FcWeightToOpenType

This error can be fixed by doing 

conda install -c asmeurer pango

**Comment by ryan-keenan** [comment]
Interesting.  So this happens on your local machine?  Are you running Python 2?
