### ISSUE TITLE
moviepy installation on python3

### ISSUE THREAD

**Issue by alemelis** [udacity/sdc-issue-reports#263]
If you have two Python installations in your computer (both 2.7.x and 3.x), the 
`
pip install moviepy`

command would install moviepie only (?) for the 2.7.x version. To force the installation for Python3, type 

`python3 -m pip install moviepy`

[source](http://stackoverflow.com/questions/34052714/installing-running-modules-in-python-3-beginner)

Is there another way to fix this starting from the [docker environment installation](https://github.com/udacity/CarND-Term1-Starter-Kit)? Otherwise, I would add that line to the project description

**Comment by domluna** [comment]
@alemelis https://github.com/udacity/CarND-Term1-Starter-Kit#anaconda should get you up and running with an Anaconda environment for all the projects/labs in the term. Hoping to get the starter kit concept in the classroom this week.
