### ISSUE TITLE
Course UI "Tick Marks" don't indicate if the quiz has been completed or not.

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#27]
Currently, just watching the video puts a "tick mark" next to the lecture name in the UI.

If the video has an accompanied quiz, the UI should somehow indicate that without having to check the lectures individually. 

I saw some lectures on the App, but couldn't attempt the quizzes there. So when I started on the course today on desktop, the lectures were all ticked off, but I hadn't attempted any of the quizzes. 

Such a change might help a lot I believe.

[Also, I am new to this, so please let me know of a better way of reporting such issues. If any.]

**Comment by Brok-Bucholtz** [comment]
@sahiljuneja 

If you have any feedback for the course, this is a good place.  If it's not specific to the Self Driving Car Nanodegree program, check out [this page](https://www.udacity.com/contact) for contact information.  Thank you for your feedback, I've added this to the product backlog.

**Comment by sahiljuneja** [comment]
Thanks @Brok-Bucholtz !

**Comment by Brok-Bucholtz** [comment]
@sahiljuneja 

Welcome!

**Comment by paolodoors** [comment]
I hope this feature can be implemented soon as it's very useful
