### ISSUE TITLE
Unable to register for confluence

### ISSUE THREAD

**Issue by jjjcoutu** [udacity/sdc-issue-reports#271]
Out of licenses error:

https://gyazo.com/ecbae07c5fd198f0ebf61a6de610c9fa

**Comment by jatindhankhar** [comment]
Seems like this issue surfaced again :sweat_smile: 

Screenshot :arrow_down: 
![screenshot from 2016-12-19 21-29-49](https://cloud.githubusercontent.com/assets/2412081/21319304/b44230fc-c632-11e6-9554-51b1659b9c7f.png)
