### ISSUE TITLE
Term 1 Lesson 13 Deep Learning Typo

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#273]
Term 1>  Lesson 13 Deep Learning > 12. Lab feature extraction

end of page commented paragraph:
# Returns the second final layer of the AlexNet model,
# this allows us to redo the last layer for the specifically for 
# traffic signs model.

should be 
# this allows us to redo the last layer specifically for the traffic signs model.

**Comment by domluna** [comment]
@GemmaLaraSavill thanks for the issue, typo has been fixed.
