### ISSUE TITLE
Finding Lane Lines - 7. Quiz: Color Region error

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/sdc-issue-reports#276]
Having trouble submitting quiz. Getting the following error:

File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
  Environment: {'executor_result': {u'vm_time': 0.62183690071105957, u'stdout': u'image type:   image dimensions:  (540, 960, 3)\n{"is_correct": true, "feedback": "Nice work!", "values": [], "comment": "Looks good!", "error": false, "output": ""}\n', u'vm_creation_time': 0.00010991096496582031, u'test_results': [], u'stderr': u'', u'exec_server_time': 0.79996585845947266, u'exec_status': u'ok'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'ok'}
  Submission: {'_operation': 'REGRADE', u'color_region.py': u'import matplotlib.pyplot as plt\nimport matplotlib.image as mpimg\nimport numpy as np\n\n# Read in the image and print out some stats\n# Note: in the previous example we were reading a .jpg \n# Here we read a .png and convert to 0,255 bytescale\nimage = (mpimg.imread(\'test.png\')255).astype(\'uint8\')\n\nprint(\'image type: \', type(image), \'image dimensions: \', image.shape)\n\n# Grab the x and y size and make a copy of the image\nysize = image.shape[0]\nxsize = image.shape[1]\n# print(xsize, ysize)\ncolor_select = np.copy(image)\nline_image = np.copy(image)\n\n# Define color selection criteria\n# MODIFY THESE VARIABLES TO MAKE YOUR COLOR SELECTION\nred_threshold = 200\ngreen_threshold = 200\nblue_threshold = 200\n\nrgb_threshold = [red_threshold, green_threshold, blue_threshold]\n\n# Define the vertices of a triangular mask.\n# Keep in mind the origin (x=0, y=0) is in the upper left\n# MODIFY THESE VALUES TO ISOLATE THE REGION \n# WHERE THE LANE LINES ARE IN THE IMAGE\nleft_bottom = [60, 539]\nright_bottom = [830, 539]\napex = [472, 320]\n\n# Perform a linear fit (y=Ax+B) to each of the three sides of the triangle\n# np.polyfit returns the coefficients [A, B] of the fit\nfit_left = np.polyfit((left_bottom[0], apex[0]), (left_bottom[1], apex[1]), 1)\nfit_right = np.polyfit((right_bottom[0], apex[0]), (right_bottom[1], apex[1]), 1)\nfit_bottom = np.polyfit((left_bottom[0], right_bottom[0]), (left_bottom[1], right_bottom[1]), 1)\n# print(fit_bottom)\n# Perform a "bitwise or" to mask pixels below the threshold\ncolor_thresholds = (image[:,:,0] < rgb_threshold[0]) | \\n                    (image[:,:,1] < rgb_threshold[1]) | \\n                    (image[:,:,2] < rgb_threshold[2])\n\n# Find the region inside the lines\nXX, YY = np.meshgrid(np.arange(0, xsize), np.arange(0, ysize))\n# print(XX.shape)\n# print(YY.shape)\nregion_thresholds = (YY > (XXfit_left[0] + fit_left[1])) & \\n                    (YY > (XXfit_right[0] + fit_right[1])) & \\n                    (YY < (XXfit_bottom[0] + fit_bottom[1]))\n# print(region_thresholds)                    \n# Mask color and region selection\ncolor_select[color_thresholds | ~region_thresholds] = [0, 0, 0]\n# Color pixels red where both color and region selections met\nline_image[~color_thresholds & region_thresholds] = [255, 0, 0]\n\n# Display the image and show region and color selections\nplt.imshow(image)\nx = [left_bottom[0], right_bottom[0], apex[0], left_bottom[0]]\ny = [left_bottom[1], right_bottom[1], apex[1], left_bottom[1]]\nplt.plot(x, y, \'b--\', lw=4)\nplt.imshow(color_select)\nplt.imshow(line_image)\n'}

Link to quiz:

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/8c82408b-a217-4d09-b81d-1bda4c6380ef/concepts/42ea7858-34b1-4e28-89c9-50afaa6d36fd

**Comment by matthewzimmer** [comment]
Also, note, when commenting out the lines to plot towards bottom of quiz, an image is still rendered to screen.

**Comment by ryan-keenan** [comment]
I think this was being triggered from a print statement in a previous version of the quiz.  Please refresh and try again, just fixed it I think!

**Comment by lethargicpanda** [comment]
Yes, it works now. Thanks!
