### ISSUE TITLE
Submission issue for "Color Selection Quizz"

### ISSUE THREAD

**Issue by lethargicpanda** [udacity/sdc-issue-reports#279]
In the "Finding Lane Lines" lesson, the Color selection quizz doesn't let you submit the code. 

It returns:

"File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded") ..."

**Comment by ryan-keenan** [comment]
Thanks for filing this report!  I can't seem to reproduce the error could you paste your code so I can look into it further?

One thing that can trigger this is if you added print statements to the quiz code.  The evaluator doesn't like that for some reason!

**Comment by domluna** [comment]
The older version of the quiz had a print statement so it's probably that.

**Comment by ryan-keenan** [comment]
Ok, updated now to handle print statement errors going forward.  Please refresh and try again!
