### ISSUE TITLE
Confusing representation of an image as a function in "Canny Edge Detection"

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#28]
In the second video of "Canny Edge Detection", the image is represented as a function of (x,y).
![image](https://cloud.githubusercontent.com/assets/12501638/19778197/70a98204-9c30-11e6-8840-56db6beb3081.png)

The image axis shows (0,0) at lower left corner (like a normal graph). 

However, in the "Color Region" Quiz, we are working with matrices/arrays, therefore we start (0,0) at upper left. Following is a test image from the quiz.

![image](https://cloud.githubusercontent.com/assets/12501638/19778283/e4000a48-9c30-11e6-89a1-27a9b25550a7.png)

Perhaps that image could be consistent with how it works while coding? Maybe not required, but might be less confusing for students.

**Comment by sahiljuneja** [comment]
Similar image on "Hough Transform" video lecture.

**Comment by ryan-keenan** [comment]
Thanks! this has been changed now
