### ISSUE TITLE
Path error in "Introduction to TensorFlow" section, part 33, Mini Batch Quiz

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#280]
Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

This gives a permission error.

Changing it to this

mnist = input_data.read_data_sets('datasets/ud730/mnist/', one_hot=True)

made it work for me

**Comment by Brok-Bucholtz** [comment]
@GemmaLaraSavill 

This has been changed.  Click "Reset Quiz" to see the changes.

**Comment by beatrupp** [comment]
@Brok-Bucholtz FYI I still see the original error and had to fix it manually.
