### ISSUE TITLE
Filter height/width formula on CNN lectures

### ISSUE THREAD

**Issue by aditbiswas1** [udacity/sdc-issue-reports#281]
in the CNN lecture we are told that the formula for calculating the height/widths of the convolutions is:
new_height = (input_height - filter_height + 2 * P)/S + 1

but when using tensorflow we find that the calculation is dependant on the padding algorithm chosen
in case of "VALID" :
new_height = in_height - filter_height / stride_height

in case of "SAME":
new_height = in_height / stride_height

**Comment by domluna** [comment]
@aditbiswas1 There's no one correct way to do padding. As you mentioned TensorFlow does padding slightly differently than the formula presented in the lectures. It's good to keep in mind padding can be done in a variety of ways.
