### ISSUE TITLE
Jupyter notebook shows 'Autosave Failed' on windows 8

### ISSUE THREAD

**Issue by shankyjari** [udacity/sdc-issue-reports#283]

**Comment by shankyjari** [comment]
Cannot able to modify .ipyb file. Which I have downloaded for project 1. 
I cannot able to save it manually either. 
It keeps saying 'Autosave Failed'. Also I see Error tag.But not saying which error. 

Also, I am using windows 8. I tried to run jupyter using administrator command line. But no effect.

**Comment by jessluls** [comment]
Are you still having this issue? It sounds like it might be something isolated to your machine so not sure how we can help. We have not been able to reproduce the issue.

**Comment by ThusithaDeepal** [comment]
I had the same issue,i tried these methods unfortunately it doesn't work.
At last i found a method 

1. Copy your filename.ipynb file manully to same directory
 
2. Rename it with filename at about 5 characters. Then open it in jupyter notebook , and it can be saved successfully .

 
3. After that you can rename it to any name you want !

**Comment by PoojaG20** [comment]
I am also experiencing same issue. I also tried what @ThusithaDeepal has tried and its not working.

**Comment by ThusithaDeepal** [comment]
View hidden files and delete checkpoints folder ..Do stepa as above..

**Comment by PoojaG20** [comment]
> View hidden files and delete checkpoints folder ..Do stepa as above..

For me I had to create a new file with some memory less to be used else it shows same error storage error.Its cz the outputs of cell are huge might be.
