### ISSUE TITLE
Instructions On GitHub inaccurate

### ISSUE THREAD

**Issue by bjhaglind** [udacity/sdc-issue-reports#284]

**Comment by domluna** [comment]
Could you elaborate? What are the specific instructions?

**Comment by bjhaglind** [comment]
Hello Dominque:

I will have a chance to get back to you in detail Friday evening.  However
one minor issue that stuck in my head was the frequent reference to Ctrl-D
to exit Python.  That does not work with the Anaconda Python 3.5 on Windows
and I have always seen it as Ctrl-Z, which does, in fact, work.  Ctrl-Z and
then press enter and Python interpreter will exit in the command terminal
window.

I have not tried the directions with Mac OSX, or Linux.

I will get you more detailed information on Friday as I also had trouble
with pip install vs conda install (some things labeled pip install did not
install unless I did a conda install).

The directions also do not mention anaconda search -t <thing you are
looking for>.

I am a firm believer in directions which include troubleshooting, and are
not just simple, tried them once, happy path install instructions.

Later,

Barbara (Bj) Haglind

**Comment by bjhaglind** [comment]
My prior email is about the Readme instructions provided in the GitHub

Bj Haglind

**Comment by domluna** [comment]
Ctrl-C or Ctrl-D tend to work, never tried Ctrl-Z but if that works then I guess that's fine.

**Comment by bjhaglind** [comment]
What system are you running on.  Neither of those have ever been an option
for the Python Interpreters I have used over the last 8 years.  Please help
satisfy.my curiousity.

Thank you,

Bj Haglind

**Comment by domluna** [comment]
MacOS, Linux, Windows. Depending on the shell ctrl-C or ctrl-D might not work in Windows but 1 of them does. Maybe it's your keyboard? Do you use a non English keyboard or language setting?

**Comment by bjhaglind** [comment]
Very interesting.  Always use English and this is across multiple different
computers in the last 8 years.  The one I am on now is a Samsung, running
Windows 8.1 US English.  I will test the Ctrl-C on Friday evening, but I am
perplexed as I have only ever successfully exited various Python
Interpreters using Ctrl-Z.

To be clear this is a Python 2.3, 2.7, or 3.5 interactive interpreter
running in the Windows Terminal window.

I wonder what the difference is?  This is going to bug me.  I will probably
wind up google searching this so I know why my experience is so.different
from yours.

Paint me puzzled!

Bj

**Comment by domluna** [comment]
Since this doesn't look like a general issue I'm going to close this. Oddly enough Ctrl-Z doesn't work for me :-(

**Comment by bjhaglind** [comment]
Dominique that isn't the oly problem but if you aren't interestwd i hearing
the remaining issues that's a pity.

I had told.you that was just ONE of the issues I found and that I would
give you more details when I had time to sit down and write them up on
Friday evening.  I am really sorry that you aren't interested in helping to
improve the process.

Other people in the forums have also.tried to adrress.the deficiencies in
the directions as well.

you have a good night, but know the impressio. you have left me is not a
really good one.

Bj

**Comment by domluna** [comment]
@bjhaglind I'm happy to hear the rest of the issues, just open up a separate Github issue for each one, it's hard to keep track otherwise. Sorry if you feel I wasn't interested, that's very much not the case.
