### ISSUE TITLE
Typo in Deep Neural Network in TensorFlow

### ISSUE THREAD

**Issue by qz2** [udacity/sdc-issue-reports#285]
"The variable n_hidden_layer determine the size of the hidden layer in the neural network. This is also know as the width of a layer." should be "The variable n_hidden_layer determines the size of the hidden layer in the neural network. This is also known as the width of a layer."

**Comment by Brok-Bucholtz** [comment]
@qz2,

Thanks for spotting the grammar errors!  I changed "determine the size" to "determines the size" and "know" to "known.
