### ISSUE TITLE
Mentor Dashboard Chat - type field disappears when receiving a message (Firefox)

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#29]
I got this feedback from a student:

> sorry if my answers are delayed, I am having a problem with the chat.. each time that I receive a message I loose the box in which I can type, and I need to zoom out before i can see it again
> I am using firefox, shall i use another browser?

**Comment by christinehall** [comment]
We're not able to duplicate this behavior on Firefox. Maybe ask what version they're using and if they're browser is normally zoomed at 100%?

**Comment by martin-martin** [comment]
Hei @christinehall I double-checked with the student and it was indeed a zooming issue on his side.
Resolved now! : )
