### ISSUE TITLE
Project submission Error

### ISSUE THREAD

**Issue by da7th** [udacity/sdc-issue-reports#293]
Ive submitted and passed my project and everyday i get a notification the it is due, i went back to check and it says i haven't submitted, but clicking submit takes me to my review...
heres a link to the screen shots:

https://drive.google.com/open?id=0B9LQ9yhAwa4tZ1Z0VGE2U3JJT0k

**Comment by mxbi** [comment]
I also get this issue, and I know at least 2 other students affected.

**Comment by thanhcs** [comment]
Yes, I also got this issue.

**Comment by mxbi** [comment]
The first time I load the webpage, all my projects are shown as not submitted. However, upon refreshing, they load correctly and show the correct status. Refreshing the page fixes it for other students too

**Comment by da7th** [comment]
Thing is it does, but again today it's back and in red saying i've missed the deadline....=L

**Comment by swwelch** [comment]
Hi All, thanks for reporting this. I've checked in with the engineering team about this, and I'll update this ticket when I find out more.

**Comment by swwelch** [comment]
Hi All, I think this has been resolved now. Please let us know if you are still having trouble!
