### ISSUE TITLE
Display suggested lengths of each lesson

### ISSUE THREAD

**Issue by bautista-ian** [udacity/sdc-issue-reports#294]

**Comment by bautista-ian** [comment]
In each terms' lessons timeline page, it'd be great if you could display a suggested length of time that it should take to complete each lesson in order for us to schedule our week accordingly.

**Comment by jessluls** [comment]
Thanks for the suggestion! This is something we're looking into (see https://github.com/udacity/sdc-issue-reports/issues/219 for more info).
