### ISSUE TITLE
Duplicate messages in mentor dashboard

### ISSUE THREAD

**Issue by deniskasyanov** [udacity/sdc-issue-reports#296]
I'm mentor, and I experienced strange behaviour of mentor dashboard. First, I typed in a message and pressed Enter to send it. The message was sent (bubble appeared), but text entry field wasn't cleared. So I cleared it manually. After that I wasn't able to send another message because Enter key seemed to have no effect. I reloaded mentor dashboard and realised I sent the same message 7 times
Ubuntu 16.04
Chrome 54.0.2840.100 (64-bit)

**Comment by swwelch** [comment]
Hi @deniskasynov, this waffle board is for student-facing issues. For issues with the mentor tool backend, can you please use Christine's Trello board or email mentorship-support@udacity.com?
