### ISSUE TITLE
ffmpeg installation problem

### ISSUE THREAD

**Issue by eoguzinci** [udacity/sdc-issue-reports#299]
Is there anybody having trouble installing ffmpeg via writing the code below to anaconda?

import imageio imageio.plugins.ffmpeg.download()

**Comment by domluna** [comment]
@eoguzinci what's the error you're getting?

**Comment by domluna** [comment]
@eoguzinci bump?

**Comment by eoguzinci** [comment]
yes it is still an issue. but I solved it with my new laptop, it didn't give error with that one. I don't know why and how? I will write the error message when I check the old laptop.

**Comment by eoguzinci** [comment]
For this command:

import imageio
imageio.plugins.ffmpeg.download()

Here is the error message that I got:

File "<ipython-input-2-d8ecfdab7e3c>", line 1, in <module>
    runfile('C:/Users/znm4sv/CARND/Project-1/eoip1.py', wdir='C:/Users/znm4sv/CARND/Project-1')

  File "C:\Users\znm4sv\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\znm4sv\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/znm4sv/CARND/Project-1/eoip1.py", line 270, in <module>
    imageio.plugins.ffmpeg.download()

AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'

**Comment by domluna** [comment]
That's weird, how did you install Python and the libraries?

**Comment by eoguzinci** [comment]
i solved in my new computer. I don't why it is not working in the previous one. anyway, you can label it as solved.
