### ISSUE TITLE
TensorFlow Neural Network Lab requirements error

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#3]
After I run the following command:
pip3 install -r assignment/requirements.txt
receive this issue in console:
"  Could not find a version that satisfies the requirement tensorflow==0.11.0rc0 (from -r requirements.txt (line 12)) (from versions: )
No matching distribution found for tensorflow==0.11.0rc0 (from -r requirements.txt (line 12))"

Tried both on Win and Linux

**Comment by dalex01** [comment]
I've updated my local repo and installation completes successfully with new `requirements.txt`. It is on Linux. 

Didn't check it on Windows, but it seems issue can be closed if someone else didn't add something here.

**Comment by GemmaLaraSavill** [comment]
I also updated my repo and I can install on Windows
The installation instructions tells you to open

jupyter notebook CarND-TensorFlow-L2/assignment_1.ipynb

but in the new repo I only see a notebook named  lab_1.ipynb, so it should be

jupyter notebook CarND-TensorFlow-L2/lab_1.ipynb

**Comment by Brok-Bucholtz** [comment]
@GemmaLaraSavill 
Thanks for the feedback.  I renamed assignment_1.ipynb to  lab_1.ipynb

**Comment by Brok-Bucholtz** [comment]
@dalex01 
I removed tensorflow from the requierments.txt.  You should be able to do a pip install successfully.
