### ISSUE TITLE
Mentor Dashboard Chat - Read / Not yet Read msgs inconsistent

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#30]
Some messages write they have been read while others (which were sent before them) are still shown as unread.

![screen shot 2016-10-27 at 20 16 15](https://cloud.githubusercontent.com/assets/12371494/19779832/1423cf3c-9c83-11e6-9c57-04df6a09e157.png)

Some messages have however been read (because the student responded to the content).

![screen shot 2016-10-27 at 20 22 40](https://cloud.githubusercontent.com/assets/12371494/19779850/27597174-9c83-11e6-9d1f-967bcc4edfa3.png)

Student also mentioned that chat messages turn up delayed.

**Comment by christinehall** [comment]
Thanks for flagging, we're looking into a fix and have identified whats causing the issue.

**Comment by Brok-Bucholtz** [comment]
@martin-martin 

This has been added to the sprint backlog.  I'll update this issue when it's fixed.
