### ISSUE TITLE
Unable to register on http://carnd-udacity.atlassian.net/

### ISSUE THREAD

**Issue by rigved** [udacity/sdc-issue-reports#300]
When I try to register on http://carnd-udacity.atlassian.net/ by clicking on the confirmation link in my email, I get an error message saying:

We are currently unable to complete your sign up. There are no available licenses for Confluence.

**Comment by swwelch** [comment]
Hi @rigved, 

That instance of the forums was deprecated, and all Q & A takes place on https://carnd-forums.udacity.com/ now. If you have trouble signing up on the new forums, please let us know!

**Comment by crazypecker** [comment]
This is also inaccessible now?
