### ISSUE TITLE
Lesson 9. 30. Issues with convnet model example

### ISSUE THREAD

**Issue by SergeyBykov1** [udacity/sdc-issue-reports#301]
Your current convnet examples fails to optimize. It always gets 10-20% accuracy.

On the other hand, the similar example from here:
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/convolutional_network.py

easily gets 96-98%

1) Most crucial issue: replace 
fc1 = tf.nn.tanh(fc1)
to
fc1 = tf.nn.relu(fc1)

2) Minor: Use AdamOptimizer. It usually does better than SGD

3) Calculating accuracy on whole test set fails to allocate 3Gb memory on GPU (if gpu version of tensorflow is used).

print(
        "Accuracy:",
        accuracy.eval({x: mnist.test.images, y: mnist.test.labels}))

The example above uses a subset of test data: mnist.test.images[:256]

**Comment by Brok-Bucholtz** [comment]
@SergeyBykov1,

Thanks for your feedback!  I changed the tanh to relu.  I'm leaving out AdamOptimizer, since it hasn't been mentioned in a previous lesson.  The accuracy is now being calculated on a subset of the data to avoid running out of memory.  Let us know if you see anything else.
