### ISSUE TITLE
Incorrect definition of the Layer.forward() method in lesson 6.12 (Cost)

### ISSUE THREAD

**Issue by zayfod** [udacity/sdc-issue-reports#302]
The method forward() of the Layer class in miniflow.py, line 28 seems to be missing the instance reference argument - usually "self",

While this does not change the behavior of the code, it feels wrong.

**Comment by zayfod** [comment]
Similar for the forward() and backward() methods in lesson 6.15 (Backpropagation).

**Comment by domluna** [comment]
Fixed, thanks for reporting this. You'll probably have to reset the quiz to see the change.
