### ISSUE TITLE
Fixing sklearn.model_selection error for 35. lab section of "Intro. to Tensorflow"

### ISSUE THREAD

**Issue by jinchenglee** [udacity/sdc-issue-reports#309]
Following this [issue](https://github.com/udacity/sdc-issue-reports/issues/308). Found another problem on my system (Ubuntu 16.04 LTS, native installation of python3.5) when executing

_from sklearn.model_selection import train_test_split_

It complains: 

_ImportError                               Traceback (most recent call last)
<ipython-input-2-1d6cd43825c4> in <module>()
      6 import numpy as np
      7 from PIL import Image
----> 8 from sklearn.model_selection import train_test_split
      9 from sklearn.preprocessing import LabelBinarizer
     10 from sklearn.utils import resample

ImportError: No module named 'sklearn.model_selection'_

Fixed by changing the path as:

from sklearn.cross_validation import train_test_split

**Comment by ryan-keenan** [comment]
I believe this is a version issue with sklearn... if you have version <= 0.17 you need to import from `sklearn.cross_validation` but with sklearn version 0.18 and above it's `sklearn.model_selection`.

**Comment by jinchenglee** [comment]
I see. Thanks for ackcing. 

My installation of ROS kinetic ruined my python 3 packages, :(
