### ISSUE TITLE
Link not working in AWS GPU Instance Lecture

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#310]

**Comment by ChrisShepherd81** [comment]
The link below "13. Launch a Jupyter Notebook" is not working.
https://github.com/udacity/CarND-LeNet-Lab/blob/master/LeNet%20Lab%20Solution.ipynb

**Comment by awbrown90** [comment]
@ChrisShepherd81 fixed the link issue, thanks.
