### ISSUE TITLE
General remarks (problems) with Lesson 15 (ML & Stanley)

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#311]
1) I do not think that after four relatively complex assignments written in Python it should be explained how IMPORT statement works in Python
2) In one of the last videos you say that we should understand how an algorithm works so that we could decide which one to choose for a specific problem. But you say not a word how Naive Bayes classification works...

**Comment by ryan-keenan** [comment]
Thanks for the feedback here!  As for the first point, we're likely going to move this section to before deep learning for future cohortsd, so this will be coming in the first few weeks of Term 1, and maybe the reminder about import statements won't seem so weird.  As to the second point, I've added a task for myself to create some content describing what's actually going on in Naive Bayes.  I agree it's annoying that it's not covered in more detail!
