### ISSUE TITLE
SVM-11: objective is differently said compared to the previous videos

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#313]
Here it is said that the margin is the distance btw boundary line and misclassified points and this is maximized, earlier it was the minimal distance btw boundary line and well-classified points and it was maximized. First makes no sense as we should move the decision boundary line to the infinity to get it infinite...

**Comment by ryan-keenan** [comment]
Great catch, thanks for pointing this out!  Katie definitely made an error there.  It looks like the lesson overall does not suffer without this short video so I have removed it.
