### ISSUE TITLE
SVM 20: what are kernels, other than linear

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#314]
There is a video about parameter C, Gamma. But there is no info about non-linear kernels. At least there should be some info about the default value (rbf).

**Comment by ryan-keenan** [comment]
Thanks for identifying this!  I see what you're saying. but at this point I don't think I'm going to add any content here.  Katie at least mentions the other kernels when going over the documentation and that the strange decision boundary in one of the previous examples was  due in part to an rbf kernel.
