### ISSUE TITLE
Project: Behavioral Cloning link error after Forum change

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#315]
Paul Heraty, a student in the October cohort, has written this incredibly helpful guide for those of you looking for some hints and advice.

guide links to:
https://carnd-udacity.atlassian.net/wiki/questions/26214464/answers/26215455 
Page not found

I think the correct link is now this one:
https://carnd-forums.udacity.com/questions/26214464/answers/26215455

**Comment by Sadrpour** [comment]
both links say page not found ..

**Comment by awbrown90** [comment]
@GemmaLaraSavill just checked and the page is now using the correct link and it works.
