### ISSUE TITLE
Quiz:TensorFlow Input - explain the first param to session.run when using feed_dict

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#316]
in the example with x, y, and z placeholders, it's not clear from the statement:

output = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})

...why only 'x' is passed in.  why x and not [x,y,z] or None?  

as a newbie, the tensorflow documentation's explanation about 'fetches' doesn't quite make sense yet so a more simple explanation of that argument would be valuable.

**Comment by Brok-Bucholtz** [comment]
@mdesksmartin,

We've added this to our JIRA board and will be working on it in a future sprint.
