### ISSUE TITLE
Links in Forum Messages broken

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#317]
After porting to the new Forum, the links within a message still point to the old Forum. This results in "Page Not Found", which decreases the usefulness of the posts considerably.

Maybe the administrators who were porting the messages could run over the message bodies and replace the initial parts of the link URLs, so that they would direct to the ported posts in the new forum.

**Comment by jessluls** [comment]
Unfortunately we don't have the ability to do this. I am looking into a re-direct.
