### ISSUE TITLE
Decision Tree - 9 (DT Accuracy): The success message is wrong

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#318]
In lesson DT, section 9 (DT Accuracy):
The accuracy is 0.908, and it is also said in the after video of the quiz. But in the success-popup it is said that it is 0.912. For some reason, also the result in the background changes (i.e. the success message is a modal popup, and during submit the background, which contained the result of Test Run, changes, and also writes 0.912).

**Comment by ryan-keenan** [comment]
I just took a look at this and it seems the discrepancy is an `sklearn` thing.  If you run the quiz a few times you'll see it sometimes gives a score of 0.912 and sometimes 0.908.   I added a comment in the instructor notes to this effect.  Thanks!
