### ISSUE TITLE
Issue with tensorflow Installation, reported by a student

### ISSUE THREAD

**Issue by ajitmotra** [udacity/sdc-issue-reports#321]
Hi, I'm having a problem on a Lab:LeNet In TensorFlow, when I run the third command: conda env create -f environment.yml, there is an error: Collecting tensorflow>=0.12.0rc1 Could not find a version that satisfies the requirement tensorflow>=0.12.0rc1 (from versions: ) No matching distribution found for tensorflow>=0.12.0rc1 Error: pip returned an error.
I noticed that the version of tensorflow installed by conda is 0.11.0, so I tried modify the last line in environment.yml to - tensorflow >= 0.11.0, and the error message becames: Could not find a version that satisfies the requirement tensorflow>=0.11.0 (from versions: ) No matching distribution found for tensorflow>=0.11.0 Error: pip returned an error. I also tried to update my tensorflow to 0.12.0 this error still exists
I tried to setup the environment manually, and it worked

**Comment by dsilver829** [comment]
Sorry for the outdated instructions! 

We're now encouraging students to use the [CarND Starter Kit](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/8c82408b-a217-4d09-b81d-1bda4c6380ef/concepts/4f1870e0-3849-43e4-b670-12e6f2d4b7a7) for all labs and projects. 

We've updated the LeNet Lab to this effect.
