### ISSUE TITLE
Error in example code - Vehicle Detection & Tracking - Explore Color Spaces

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#322]
For the line beginning so:
img_small = cv2.resize(img, (img.shape[1] / scale, img.shape[0] / scale)...

I got this error:
TypeError: integer argument expected, got float

To correct it I used // in this and the previous lines.

**Comment by ryan-keenan** [comment]
Thanks for pointing this out!  I got this error too, and was not able to get rid of it replacing `/` with `//` so I added `np.int()` (and the `numpy` import) to get rid of it
