### ISSUE TITLE
save and restore tensorflow models: clarify

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#323]
in the section "saving variables", the text says "Later examples will show you how to save entire models."  as far as i can tell, in both the first and 2nd examples, the call to saver.save(sess, save_file) doesn't change all whether we are "saving variables" or "saving entire models".  the text would be clearer if it indicated that in call cases we are saving the model-whatever is in it at the time.  if we have just variables, that's what gets saved. if we have more than that, then more gets saved.

the way it's written initially seems to imply that there are different ways to save the model or parts of the model when there appears to be just one.

**Comment by mdesksmartin** [comment]
additional comments:  is the point of this section to illustrate how you can save different components of a tensorflow model (just variables, an entire trained model, etc) and then use those saved bits together later?  if so, it should try to set the stage for that at the beginning.

**Comment by Brok-Bucholtz** [comment]
@mdesksmartin,

I clarified the sentence about saving model the entire model. It now says "Later examples will show you how to save all the weights in the model."
