### ISSUE TITLE
Keras code crashes ipython notebook

### ISSUE THREAD

**Issue by Sadrpour** [udacity/sdc-issue-reports#325]

**Comment by Sadrpour** [comment]
During training of model : jupyter notebook traffic-sign-classification-with-keras.ipynb
My ipython session freezes and times out "WebSocket ping timeout".

**Comment by domluna** [comment]
@Sadrpour Seems to be related to this https://github.com/jupyter/notebook/issues/1474.

**Comment by domluna** [comment]
Going to close this since it looks like an issue with Jupyter and not SDC content specific. The forums or carnd slack could be helpful in this regard as well.

**Comment by bstriner** [comment]
The PR by @007 should help fix this issue. Alternatively, you could use something like this to make pretty widgets.

https://github.com/bstriner/keras-tqdm

![Jupyter](https://github.com/bstriner/keras-tqdm/raw/master/docs/images/leave_inner_True.png)

Cheers
