### ISSUE TITLE
Missing parameter in Plot3D call - Vehicle Detection & Tracking - Explore Color Spaces

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#327]
I think that in the 2nd (last) call of plot3d the axis_labels parameter is missing, because in the 2nd call we use the HSV color space and not RGB. So I think it should be:

plot3d(img_small_HSV, img_small_rgb, axis_labels=list("HSV")).

**Comment by ryan-keenan** [comment]
Thanks for reporting, now fixed!
