### ISSUE TITLE
axis in 13 hough transform quiz 4/5 mislabeled

### ISSUE THREAD

**Issue by giladgressel** [udacity/sdc-issue-reports#33]
![capture](https://cloud.githubusercontent.com/assets/6275366/19787103/d185b5dc-9c55-11e6-8a4b-8ad013ac5fa5.PNG)

The image space axis should be labeled in X and Y
hat-tip to student Henry X

**Comment by Brok-Bucholtz** [comment]
@giladgressel 

Hey Gilad, we are planning on fixing this issue next week.  I'll let you know when it's fixed.

**Comment by Brok-Bucholtz** [comment]
@giladgressel 

We applied an x and y axis to the Image Space.  Sorry it took us so long to update this.  Let us know if you need anything else.
