### ISSUE TITLE
Bug in code - Vehicle Det.&Tr. - Sliding Window Implementation

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#330]
Hi,

The example solution has the following bug:
the window size is given in parameter xy_window, so the result boxes should have the shape according to xy_window. 

But in the code their width and height are: 
nx_pix_per_step times nx_pix_per_step which is not necessarily the same.

The wrong code (line 35 & 37):
            endx = (xs+1)*nx_pix_per_step + x_start_stop[0]
            endy = (ys+1)*ny_pix_per_step + y_start_stop[0]

The fixed code:
            endx = xs*nx_pix_per_step + xy_window[0]
            endy = ys*ny_pix_per_step + xy_window[1]

If the built-in checker is based on this wrong code, then the expected solution is also wrong.

Regards,
  BartMate

**Comment by ryan-keenan** [comment]
Hey, thanks for reporting this!  I definitely see your point but I think the fixed version should look a little different.  Here's what I've got in there now: 

```
startx = xs*nx_pix_per_step + x_start_stop[0]
endx = startx + xy_window[0]
starty = ys*ny_pix_per_step + y_start_stop[0]
endy = starty + xy_window[1]
```

I also noticed I had another error above (missing a -1), now corrected to: 

```
nx_windows = np.int(xspan/nx_pix_per_step) - 1
ny_windows = np.int(yspan/ny_pix_per_step) - 1
```
