### ISSUE TITLE
LeNet Lab clarification - mu/sigma purpose and define variablesw

### ISSUE THREAD

**Issue by jeremy-shannon** [udacity/sdc-issue-reports#332]
I feel the LeNet Lab could benefit from a little clarification in:
1. the purpose of mu and sigma - it currently says simply "hyperparameters" but I think it would be more clear to state that they're meant as arguments for tf.truncated_normal
2. the need to define variables for the weights and biases for each layer

**Comment by awbrown90** [comment]
Hi @jeremy-shannon I made the change to add more clarification to the mu and sigma parameters, thanks.

**Comment by jeremy-shannon** [comment]
Hooray! Thanks Aaron. I appreciate the work you do!
