### ISSUE TITLE
Display link to new Forum in dead links

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#334]
There are still some students who didn't catch the transition to the new Forum (some don't work on the ND all the time).

It would be useful to simply direct them to the new Forum with a default link on the "Not Found" pages of the old Forum.

**Comment by jessluls** [comment]
Hi there - unfortunately there isn't a way to redirect so our best effort at a work around is to put up a welcome message after log-in that tells you to go to the new forums.
