### ISSUE TITLE
Miniflow - From Neurons To Layers. Incorrect example

### ISSUE THREAD

**Issue by Helen1987** [udacity/sdc-issue-reports#335]
When we move from Neurons to matrix we have this confusing example when outbound layer is just scalar operation between single input and weight (xi*wi) what can not be the truth. Outbound layer must be x1*w1+x2*w2...+xn*wn.
def forward():
        outputs = self.inbound_layer.outputs
        for n in range(len(outputs)):
            weight = self.weights[n]
            input = outputs[n]
            self.outputs.append(do_math(input, weight))

**Comment by Helen1987** [comment]
[link](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/a0a7aeb8-67e3-46ae-b0f0-168c5f9b76df) to the lesson

**Comment by domluna** [comment]
@Helen1987 The `Layer` class there is simply to illustrate having multiple inputs and outputs, it's not meant to be an example of a Linear layer.

**Comment by domluna** [comment]
Good point @Helen1987, I've updated the code based on your suggestion.
