### ISSUE TITLE
Minor bug in P4: Lecture 23

### ISSUE THREAD

**Issue by thomasantony** [udacity/sdc-issue-reports#336]
The short code snippet that performs the thresholding on the HLS image does not work if my source image is a PNG. For some reason mpimage gives me a normalized array (0 to 1) when reading in a PNG, and hence thresholding doesn't work.

**Comment by ryan-keenan** [comment]
Thanks for reporting!  This is actually just the difference between pngs and jpgs.  We've tried to do the lessons with jpgs to keep the 8-bit color channels intuition going, but indeed, you need to either change your thresholds or multiply by 255 when dealing with pngs
