### ISSUE TITLE
Lesson 6 p.6 clarity and typo

### ISSUE THREAD

**Issue by shkabko** [udacity/sdc-issue-reports#337]
1. Its not clear if x+y or (x+y)+y should be submitted
2. There is unnecessary "." in "The topological_sort() function implements topological sorting using Kahn's Algorithm. The details of this method are not important, the result is. topological_sort() returns "

**Comment by domluna** [comment]
Thanks for reporting these @shkabko.

1) Either way it'll pass as long as the `forward` method for `Add` is implemented correctly. I added an extra sentence stating all that's required to pass the quiz is the correct implementation of `forward` for `Add`. (stated in the setup section prior to the quiz and in the quiz itself)
2) Edited the punctuation.
