### ISSUE TITLE
Figure with f, f'x for Lesson 6 p. 15

### ISSUE THREAD

**Issue by shkabko** [udacity/sdc-issue-reports#338]
You did really well by numbering some of the formulas but not Figures. In scientific publications you normally put Figure number with a caption. But that's not what Im really wondering. On the figure itself might be something but not x^2 and 2*x. 

For the reference http://mathinsight.org/derivative_quadratic_function 

Would be great to know F(x) and F'(x) formulas

**Comment by domluna** [comment]
@shkabko f(x) is x^2 here, might not be easiest to see since the graph is zoomed. f'(x) here is incorrect since f'(x) is 2x and the tangent line in this case is 2x - 16. I'll update the figure and surrounding text such that all of this is clear. Thanks for bringing this up 👍

**Comment by domluna** [comment]
Added a new graphic which should make this clearer.
