### ISSUE TITLE
Fix axis label to Finding Lane Lines 13. Hough Transform qizz 4/5

### ISSUE THREAD

**Issue by HaiShaw** [udacity/sdc-issue-reports#34]
The axis labels of Image space to the right is the confusing, should be 'x' and 'y'.

**Comment by giladgressel** [comment]
same as the issue I opened #33 but @HaiShaw is the one who spotted it 👍

**Comment by Brok-Bucholtz** [comment]
@HaiShaw @giladgressel 

Closed this issues, since it's a duplicate of #33.
