### ISSUE TITLE
Move information about AWS instance activation

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#340]
Suggestion from a student (Thanks, Philipp!):

![image](https://cloud.githubusercontent.com/assets/12371494/21638692/b42de0d4-d26c-11e6-8fa5-1763655274d0.png)

Since activation takes a few days, it would be more useful to learn about that earlier!

**Comment by jeremy-shannon** [comment]
+1

**Comment by awbrown90** [comment]
@martin-martin @dsilver829  would it be a good idea then to take the first portion of AWS GPU Instances and put it at the end of Convolutional Neural Networks in a section maybe called Preparing for the Traffic Sign Classification Project?
