### ISSUE TITLE
Inconsistency between instructions on udacity and in code

### ISSUE THREAD

**Issue by mikkelkh** [udacity/sdc-issue-reports#341]
In "Convolutional Neural Networks" -> "35. Lab: LeNet In TensorFlow" -> "Specs"
there are only 2 full connected layers, whereas in the provided code "LeNet-Lab.ipynb" there are 3 fully connected layers.

**Comment by domluna** [comment]
@mikkelkh  I'm updated the section such that there are 3 FC layers instead of 2. Thank you for reporting this 👍
