### ISSUE TITLE
incorrect new width formula provided in Quiz: Pooling Mechanics

### ISSUE THREAD

**Issue by tsekityam** [udacity/sdc-issue-reports#342]
If we submit a number, such as `20`, the a dialog comes out and show formulas to calculate the shape.

One of the formulas shown is that: 
```
new_width = (input_width - filter_width)/stride_height + 1
```

However, I believe that the `stride_height` should be `stride_width` because height should not be involved in width calculation.

**Comment by awbrown90** [comment]
@tsekityam I agree and made the change. thanks
