### ISSUE TITLE
Wrong number of epochs in keras lab

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#343]
In traffic-sign-classification-with-keras.ipynb:
"Compile and train the network for 2 epochs." should be "Compile and train the network for 20 epochs."

**Comment by Brok-Bucholtz** [comment]
@WolfgangSteiner,

We just updated the Keras Lab.  We changed the number of epochs to 10 in the description and the solution along with a whole bunch of changes.  Check it out!
