### ISSUE TITLE
download links dont work

### ISSUE THREAD

**Issue by kevinyh** [udacity/sdc-issue-reports#344]
Term 1 Online Course  - Keras - 5.Lab: Keras, all download links seems to have problems , such as:"the Jupyter notebook, training data, test data", as well as Supporting Materials download, indcluding:
Train
Test
Traffic Sign Classification With Keras
Traffic Sign Classification With Keras Solution

Could you please double check?

**Comment by Brok-Bucholtz** [comment]
@kevinyh,

I just tried the links, they seam to work.  Can you try again?
