### ISSUE TITLE
Check-In message blocks viewing of other messages

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#346]
Got this feedback from a student (thanks Michael!):

> the check-in box supercedes the messages you've sent, so I can't actually read any of those even though I know they're there, until after I submit the check-in.

Can this be uncoupled somehow, so that older messages can still be read? There can be related information in the DMs, that might actually change the focus of the student's check-in.

**Comment by swwelch** [comment]
Hi @martin-martin,

Thanks for letting us know! I've added this to the Mentorship trello board.

**Comment by swwelch** [comment]
I'm going to close the issue on this board for now.
