### ISSUE TITLE
TensorFlow - Windows installation instructions

### ISSUE THREAD

**Issue by DavidObando** [udacity/sdc-issue-reports#347]

**Comment by DavidObando** [comment]
In the lesson "Introduction to TensorFlow", page 5 (Installing Tensorflow), you can update the instructions to be the same, or similar, to Linux. There's no need to run tensorflow in a docker container (and some folks might not even have a virtualization-compatible processor for it).
The only difference between Linux and Windows is that where in Linux you do:
```
conda install -c conda-forge tensorflow
```
In Windows you do:
```
pip install tensorflow
```
For all purposes you have tensorflow working in your anaconda environment now.

**Comment by Brok-Bucholtz** [comment]
Since we got so many issues related to TensorFlow 0.12.x, I've created a single issue to find out when this will be resolved.  You can follow issue #353.
