### ISSUE TITLE
CNN: confusion in use of filter term

### ISSUE THREAD

**Issue by Helen1987** [udacity/sdc-issue-reports#348]
Initially in part **6. Filters** we start from the statement that filter is the same as patch:
>We do this by selecting a width and height that defines a filter, or patch.

In the middle of the article we claim that filter is some patch of the output layer:

>That’s dependent on our filter depth. If we have a depth of k

We stick to this version till the end of the article. But later we return to the initial idea.
**Quiz 12, 14**:

>...each neuron in the output layer must connect to each neuron in the filter..
>..So the number of parameters is equal to the number of neurons in the filter...

So, filter is the same as patch again.
It is confusing and took me a lot of time switching between topics to understand what's going on. Definition of the filter is not clear. Is it something in the middle?

**Comment by 007** [comment]
:+1: to this, please be more consistent in naming. I had the same confusion in this section around "channel", which is actually referring to depth.

**Comment by sstormm** [comment]
+1

**Comment by domluna** [comment]
Rewrote some parts of the section. Hopefully difference between patch and filter is more obvious. Patch referring to a subsection of the image and not a synonym for filter.
