### ISSUE TITLE
Lesson 8 - 14.Finetuning typo

### ISSUE THREAD

**Issue by earlbread** [udacity/sdc-issue-reports#349]
Hi,

Thank you for your job.

I found a typo in lesson8.14.

The last output is now

> Save Weights: Variable_1:0
> 
> Save Bias: bias_0:0
> 
> Load Weights: Variable_1:0
> 
> Load Bias: bias_0:0
> 
> Loaded Weights and Bias successfully.

But it should be

> Save Weights: weights_0:0
> 
> Save Bias: bias_0:0
> 
> Load Weights: weights_0:0
> 
> Load Bias: bias_0:0
> 
> Loaded Weights and Bias successfully.

Thank you!

**Comment by Brok-Bucholtz** [comment]
@earlbread,

Thanks for noticing.  I've changed the output from "Variable_1" to "weights_0".
