### ISSUE TITLE
Quiz: Classification or Regression has Try again - Yes! when the answer is wrong

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#35]

**Comment by rm51** [comment]
In  quiz for Regression and Classification I got answer wrong and it said Try again with the message Yes! Another message might be better.

**Comment by rm51** [comment]
<img width="586" alt="screen shot 2016-10-27 at 7 18 03 pm" src="https://cloud.githubusercontent.com/assets/7563076/19789016/3a672b7a-9c7a-11e6-92ae-0eb33bd61141.png">

**Comment by rm51** [comment]
<img width="844" alt="screen shot 2016-10-27 at 7 22 00 pm" src="https://cloud.githubusercontent.com/assets/7563076/19789118/09de16de-9c7b-11e6-8b7e-0620d4d6cc4d.png">

**Comment by dhruvp** [comment]
Fixed now!
