### ISSUE TITLE
Typo in Lesson 9 Instructions:

### ISSUE THREAD

**Issue by MikeZhu92** [udacity/sdc-issue-reports#350]
Intro to CNN:
Instructions:
Set up your development environment with the CarND Starter Kit
git clone https://github.com/udacity/CarND-LeNet-Lab.git
cd CarND-LeNet-Lab
juypter notebook
Finish off the architecture implementation in the LeNet function. That's the only piece that's missing.
----------------------------------------
Typo: juypter notebook
Correct: jupyter notebook

**Comment by domluna** [comment]
@MikeZhu92 Thanks for reporting this. The typo has been corrected.
