### ISSUE TITLE
tf.initialize_all_variables() is IS DEPRECATED

### ISSUE THREAD

**Issue by MikeZhu92** [udacity/sdc-issue-reports#351]
## THIS FUNCTION IS DEPRECATED. It will be removed after 2017-03-02. Instructions for updating: Use tf.global_variables_initializer instead.
###sess.run(tf.global_variables_initializer())
AttributeError: 'module' object has no attribute 'global_variables_initializer'
##tf.global_variables_initializer() is not supported

**Comment by Brok-Bucholtz** [comment]
Since we got so many issues related to TensorFlow 0.12.x, I've created a single issue to find out when this will be resolved.  You can follow issue #353.
