### ISSUE TITLE
Can't download jupyter notebook for Keras lab

### ISSUE THREAD

**Issue by CassLamendola** [udacity/sdc-issue-reports#354]
content-disposition: attachment header needed on ipynb files

**Comment by Brok-Bucholtz** [comment]
@CassLamendola,

What browser are you using and what's the version of the browser?

**Comment by CassLamendola** [comment]
I'm using the latest version of chrome (55.0.2883.95)

**Comment by Brok-Bucholtz** [comment]
@CassLamendola,

We've moved the the Keras lab into a Github repository just like all the other labs and projects.  The repo is located at https://github.com/udacity/CarND-Keras-Lab.  Let us know if see anything else.
