### ISSUE TITLE
L9 (CNN): Quiz: Feature Map Size - Stride 2

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#355]
In the quiz about CNN output dimensions, the dimensions for Valid padding is asked for both a stride of 1 and 2
Input = 28x28
Kernel = 3x3
Stride = 1 and 2
The equation for the size of the output is: (Input - Kernel) / Stride + 1
For the stride of 1, this comes out to an even number: ((28 - 3) / 1) + 1 = 25 + 1 = 26
For the stride of 2, this is not an even number: ((28 - 3) / 2) + 1 = (25 / 2) + 1 = 12.5 + 1 = 13.5
The accepted answer was 13, explaining that the the number is half of 26. However, it does not mention that there are inputs left over from this stride. I'm assuming in practice that some care would be necessary in choosing an appropriate stride length to avoid the situation where this information is dropped. It would be good to have this explained in the lesson or video.

**Comment by domluna** [comment]
@brahmwindeler The equation for `'VALID'` padding is:

```python
out_height = ceil(float(in_height - filter_height + 1) / float(strides[1]))
out_width  = ceil(float(in_width - filter_width + 1) / float(strides[2]))
```

Taken from https://www.tensorflow.org/api_docs/python/nn/convolution. If you plug in the values you'll see it comes out to 13. 

From what I can see these equations aren't shown on the quiz page so I'll add them there.

**Comment by brahmwindeler** [comment]
I was using the equation I found provided in the Stanford CS231n course (under the Spacial Arrangement section): https://cs231n.github.io/convolutional-networks/#conv

(W−F+2P)/S+1

Where W is the "width" of the input, F is the filter size, P is the padding size, S is the stride size.

The way that TensorFlow calculates it is a little different though apparently in an acceptable way. If you perform it by hand, you'll see that in this case there is, in fact, an extra pixel left over after the 13.

Regardless, I guess my concern is that since this lesson it teaching the theory behind it, regardless of how a specific library calculates it, there should be some mention about what to do when the math doesn't lead to a clean answer. As someone who is new to all of this, unanswered questions like this can be easy to get hung up on even if they are trivial because I don't know enough yet to know they are trivial. Does it matter that there are leftover pixels? Can they be ignored (since maxpooling afterward would be lossy anyway and/or there is rarely important information at the edges [though this may be application-specific])? Should an extra stride be made with padding? Does care need to be made to make sure to preprocess the input to certain dimensions or choose certain filter parameters to insure there are no leftover pixels? What exactly does TensorFlow do for these non-exact situations?

**Comment by brahmwindeler** [comment]
I put together a quick and dirty illustration using a spreadsheet: http://imgur.com/a/9YJ6w

Rows represent the dimension of the input. Columns represent the filter as it moves across the input.

**Comment by domluna** [comment]
Nice visualization! 

> Does it matter that there are leftover pixels? 

Probably not, unless there many of leftover pixels. Most likely though you'll only miss the very outermost of the image which probably doesn't contain much information anyway. If my math is right from this example there are 28x28 = 784 pixels total so VALID padding we're skipping 28 + 28 -1 = 55 pixels or 7% of the image. The 7% might seem like a lot but remember it's pixels on the very edge of the image.

> Should an extra stride be made with padding?

Depends on the padding formula. In the SAME case zero padding is added to the top and left of the image.

> Does care need to be made to make sure to preprocess the input to certain dimensions or choose certain filter parameters to insure there are no leftover pixels?

Up to you. This goes back to whether or not for the application you think leftover pixels would be an issue. I don't think it's thought about much.

> What exactly does TensorFlow do for these non-exact situations?

In the case of VALID it ignores the leftover pixels as you would think

I made a little program -> https://gist.github.com/domluna/8808192b38194f2b210ec3d6459824bc

I set the 3x3 filter to be 

```
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
```

and the leftmost and rightmost 3x3 blocks to 1s, except the last column which is set to 2s. With VALID padding the result of the conv with the leftmost block is 45 and the conv with the rightmost block 33 (the first column of the filter is be multiplied by 0s). This verifies the rightmost column with 2s is ignored.

**Comment by brahmwindeler** [comment]
Thanks for answering the questions! I actually meant them to be more rhetorical to illustrate the questions that were raised in my mind when I came across this. But I definitely appreciate you taking the time to answer them. Maybe some of that could be integrated into the lesson, perhaps in the same place you added the TensorFlow equations.
