### ISSUE TITLE
Quiz: TensorFlow ReLUs

### ISSUE THREAD

**Issue by da7th** [udacity/sdc-issue-reports#356]
shouldnt the example code distinguish between the variable names for layer1 and layer2
like weights1 & weights2

# Hidden Layer with ReLU activation function
hidden_layer = tf.add(tf.matmul(features, weights), biases)
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, weights), biases)

**Comment by Brok-Bucholtz** [comment]
@da7th,

Yea, they should be different.  I change the code to the following:
```python
# Hidden Layer with ReLU activation function
hidden_layer = tf.add(tf.matmul(features, hidden_weights), hidden_biases)
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, output_weights), output_biases)
```
Thanks for letting us know.
