### ISSUE TITLE
fix the link to Confluence in lesson 1

### ISSUE THREAD

**Issue by Sadrpour** [udacity/sdc-issue-reports#359]

**Comment by Sadrpour** [comment]
in lesson one resources there is a link to Confluence ... the link ends in an error for me "Your license has expired"

this is so annoying
i still can't access the forum pages, it says : Page Not Found
when i use the link below:
https://carnd-forums.udacity.com/questions/33787620/behavioral-cloning---generators-questions
and i think i am using the page that was suggested

the website is also confusing https://carnd-forums.udacity.com/#all-updates
i am not even sure what i am looking at ...

.... why can't we have something like stack-overflow ... simple forum for Q/A ?

**Comment by swwelch** [comment]
Hi @Sadrpour, sorry for the trouble! I've tried the link above, and it seems to be working now. Can you check it now?

Although all updates are listed on the #all-updates page, generally, important content is in the Questions area:
https://carnd-forums.udacity.com/questions?&filter=recent
Or the CarND space:
https://carnd-forums.udacity.com/display/CAR
