### ISSUE TITLE
Stuck on onboarding flow

### ISSUE THREAD

**Issue by dyelax** [udacity/sdc-issue-reports#36]
I can’t click through finish on the final “The best companies know…” page, so I can't access any of the course material.

**Comment by dyelax** [comment]
I get these errors in my js console when I click finish:

[Log] [Amplitude] WARNING: Property key "courseKey" with invalid value type undefined, ignoring (amplitude-3.0.2-min.gz.js, line 2)
[Log] [Amplitude] WARNING: Property key "conceptKey" with invalid value type undefined, ignoring (amplitude-3.0.2-min.gz.js, line 2)
[Log] [Amplitude] WARNING: Property key "partKey" with invalid value type undefined, ignoring (amplitude-3.0.2-min.gz.js, line 2)
[Log] [Amplitude] WARNING: Property key "moduleKey" with invalid value type undefined, ignoring (amplitude-3.0.2-min.gz.js, line 2)
[Log] [Amplitude] WARNING: Property key "lessonKey" with invalid value type undefined, ignoring (amplitude-3.0.2-min.gz.js, line 2)
[Log] No message (1) (app.a7504.js, line 2)
t — api-error.js:2(anonymous function) — api-service.js:52a — bluebird.js:5119_settlePromiseFromHandler — bluebird.js:3144_settlePromise — bluebird.js:3201_settlePromise0 — bluebird.js:3246_settlePromises — bluebird.js:3325_drainQueue — bluebird.js:190_drainQueues — bluebird.js:200drainQueues — bluebird.js:69(anonymous function) — bluebird.js:4381

**Comment by Brok-Bucholtz** [comment]
@dyelax 

Hey Matt,

Sorry you're having issues with onboarding.  I'm going to look into this.  Are you able to get to [this link](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/facdff19-61a5-47e4-8179-a6a5dc28987f/concepts/5b8dcedc-49cf-4d8f-8139-9b2023f1ce8d)?

**Comment by Brok-Bucholtz** [comment]
@dyelax 

We fixed the issue, so you should be able to get past onboarding.  If it's not, let use know!
