### ISSUE TITLE
Project 2 (sign classifier) feedback

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#360]
having struggled through project 2 (in a mostly good way), i think the following would help future students who, like me, haven't worked with ML or neural networks before:
* clearly state whether or not accuracy is a goal when working through the project.  if it is, what is the range that the student should be shooting for.
* clearly state what range of accuracies are reasonable to expect.  i wasn't sure if 0.91 accuracy meant that i wasn't "getting it" or if that was acceptable.  i spent a lot of time trying to boost it.
* provide some boundaries around the types of changes to the network that the student should be attempting.  should he/she try to remake LeNet?  would 50 epochs be a reasonable thing to try?  how about many more layers?  fewer?  what number of filters is reasonable?  i am glad that i put in the time to experiment but i think that some of the time was wasted because i was just flying blind with some of it and getting frustrated that nothing i tried increased the accuracy.  should the student be able to get a decent result on a current desktop PC or is it required to use amazon EC2?  for example, after failing to really make things "work" (i.e., get an accuracy of 0.97 because i thought that was what i was supposed to do), i wasn't sure if i just needed "more power" or something.
* some references to normalization for images would helpful.

**Comment by domluna** [comment]
@mdesksmartin Thanks for the feedback! Providing an accuracy range for the project is something we're looking into. We've recently released a new dataset where the validation data distribution resembles the test distribution better. So there shouldn't be large gaps in validation -> test accuracy anymore. 

GPU isn't required for the project although having a GPU allows for much quicker iteration.
