### ISSUE TITLE
Lab: Keras Traffic Sign Classification - notebook crashes

### ISSUE THREAD

**Issue by mdesksmartin** [udacity/sdc-issue-reports#361]
i am using windows 10 and chrome for jupyter notebook.  the keras notebook crashes when it begins training because of the progress bar trying to update 30 thousand times.  i had to add the argument verbose=2 to just print out the results at the end of each epoch and then the notebook would run from top to bottom.

the "crash" was that the chrome tab would hang and eventually the jupyter web server/service would time out.

**Comment by Brok-Bucholtz** [comment]
@mdesksmartin,

Are you using the [CarND-Term1-Starter-Kit](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/README.md)?

**Comment by mdesksmartin** [comment]
I am using the anaconda environment that I set up following the instructions in in the “finding lane lines” read me in the github repo.  Those instructions indicate anaconda instead of miniconda but other than that, I believe that I am set up according to the instructions.

As I said in my post related to this crash, I think that the issue is caused by the rapid updating of the status bar in the notebook.  Everything else about jupyter notebook, python, tensorflow, tensorflow-gpu, etc, works fine on my (windows) machine.

**Comment by Brok-Bucholtz** [comment]
I haven't seen this problem before.  Why do you think it's the keras progress bar?

**Comment by mdesksmartin** [comment]
Because when I change verbosity to 2 in the method, it runs fine.  I think it’s the progress bar because the browser freezes (indicating to me that it is overwhelmed with something) and the jupyter notebook web service looks like it freaks out and then just times out.

**Comment by domluna** [comment]
@mdesksmartin Might be of relevance https://github.com/udacity/sdc-issue-reports/issues/325.

**Comment by MikeZhu92** [comment]
@Brok-Bucholtz 

@mdesksmartin is correct, I come up with the same issue.
Then I convert the code to .py and run the code in cmd `python carnd-keras.py`, it works fine.

But it will give you **tons of messages** in the cmd window when doing `fit.model` without `verbose=2`. Because of that, Jupyter notebook is not able to handle so many information (capture the message to the browser in very short time) which cause the Jupyter notebook page crash.

>My Laptop Info:
>* Win 8.1
>* RAM: 8G
>* GPU: GT 750M 4G

**Comment by domluna** [comment]
Added verbose statements to all the fit functions should work fine now. Ideally Jupyter should be able to handle the animation on its own.
