### ISSUE TITLE
Advanced Lane Lines: 21. Applying Sobel quiz error/issue

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#362]
The quiz has a bug in it. Maybe 2.

1. Clicking on "Test Run" for my code, and for the solution code doesn't do anything. As soon as I click on "Test Run" it reverts to it's clickable position again. 

2. I add my code to the text editor. I go check out another lecture and come back to add more code. The editor is reset again. I don't recall that happening earlier I belive.

**Comment by ryan-keenan** [comment]
Hi Sahil!  Thanks for reporting this.  I'm unable to reproduce this error, perhaps it was just a transient bug?  Please re-open this issue if this behavior persists.
