### ISSUE TITLE
Traffic Sign Classifier Lesson - AWS GPU - Step 13 incorrect

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#365]
Step 13. Launch a Jupyter Notebook is incorrect:
1) There is no environment.yml in CarND-LeNet-Lab (I presume because it was moved to the CarND-Term1-Starter-Kit repository.
2) The carnd-term1 environment is already set up in the AMI, so there is no need to create one just for the lab anyway.
3) tensorflow-gpu is already installed in the AMI.

The steps can be simplified to:
1) Clone the LeNet lab
2) Enter the directory
3) Activate the carnd-term1 environment
4) Run the notebook

**Comment by Brok-Bucholtz** [comment]
@brahmwindeler,

I removed the instructions for creating an environment and installing tensorflow-gpu.  I changed the conda environment to used the term 1 starter kit.  Thanks for letting us know, this should prevent any headache for other students.
