### ISSUE TITLE
suggestion: hint for feature_extraction

### ISSUE THREAD

**Issue by jeremy-shannon** [udacity/sdc-issue-reports#366]
On Transfer Learning -> 12. Lab - Feature Extraction, it would be helpful (maybe too helpful?) to put a hint in the TODO: of feature_extraction.py like "Hint: your code should be very similar to layer 8 in alexnet.py"

**Comment by domluna** [comment]
@jeremy-shannon I like the suggestion, added a hint to the file.

**Comment by jeremy-shannon** [comment]
😁👍🏾
