### ISSUE TITLE
Kernel dies always

### ISSUE THREAD

**Issue by eoguzinci** [udacity/sdc-issue-reports#368]
Hello, I am trying to run the working code in at the Intro to Tensorflow 13. Quiz: Tensorflow Linear Function in Spyder but the Kernal always die and need to restart. I have installed all the necessary libraries and it did not make any problem until so far about TensorFlow. Do you have any idea what would be the cause of it?

**Comment by Brok-Bucholtz** [comment]
@eoguzinci,

Have you tried using [CarND-Term1-Starter-Kit](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/README.md)?
