### ISSUE TITLE
Udacity Atlassian site

### ISSUE THREAD

**Issue by Ch3ck** [udacity/sdc-issue-reports#369]
I get the following error accessing the udacity questions forum: 

There's an issue with your site
Your billing contact will need to log in to resolve this issue.
Resolve issue
Need help? Contact us.

**Comment by swwelch** [comment]
Hi @Ch3ck,

I've just checked here: https://carnd-forums.udacity.com/

It seems to be working now. Can you also check there and let us know if you are still having problems?
