### ISSUE TITLE
a typo in class material 1.11 "Canny to Detect Lane Lines"

### ISSUE THREAD

**Issue by dolaameng** [udacity/sdc-issue-reports#37]
It probably won't affect the result too much, but is the parameter `cv2.COLOR_BGR2GRAY`  in the line
`gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)`
supposed to be '`cv2.COLOR_RGB2GRAY` since the `image` was loaded by `mpimg.imread`, which gives you an RGB (rather than BGR) image?

**Comment by ryan-keenan** [comment]
Thanks!  now fixed
