### ISSUE TITLE
Missing coding exercise

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#372]
(thanks to **Liu** for spotting the following):

In _Vehicle Detection and Tracking_ / _33. False Positives_ the instructor mentions a coding exercise to detect false positives.

The following video congratulates on finishing the exercise, but there is none there.

Please add. : )

**Comment by philbort** [comment]
Can we get this issue fixed soon? It's a critical function for Project 5.

**Comment by ryan-keenan** [comment]
Sorry for the delay!  This should be in there tomorrow

**Comment by ryan-keenan** [comment]
Just added content around combining multiple detections and rejecting false positives.  Sorry for the delay!  https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/fd66c083-4ccb-4fe3-bda1-c29db76f50a0/concepts/de41bff0-ad52-493f-8ef4-5506a279b812
