### ISSUE TITLE
Vehicle Detection & Tracking: Lesson 9 on Template Matching

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#373]

**Comment by gtg162y** [comment]
I cannot find the links to download the template images (cutout1.jpg, cutout2.jpg, ..., cutout6.jpg)

Can you please post a link to download them individually?
Thanks

**Comment by ryan-keenan** [comment]
Sorry for the delay on this issue!  I have now added a link to those images.
