### ISSUE TITLE
There is no mention of Confluence in Lesson 1

### ISSUE THREAD

**Issue by fallrisk** [udacity/sdc-issue-reports#374]

**Comment by fallrisk** [comment]
I just read "6. Nanodegree Support". Confluence is only mentioned once on the page. It is only mentioned in the quiz at the end. This is confusing because you ask if I signed up for Confluence, yet it was never mentioned.

**Comment by robdoll** [comment]
you are right. I habe the same problem. 
Confluence is different to waffle.io

**Comment by vishalrangras** [comment]
To go to confluence, all you have to do is click on the Forums link on left and then sign up there. Hope this helps for the time being. I know they haven't explicitly mentioned it anywhere so it is difficult to figure out.

**Comment by swwelch** [comment]
Hi all,

Sorry for the confusion here! If you are in January cohort or after, we will no longer be using Confluence. The forums for your cohort will be at discussions.udacity.com, which should be linked from the classroom correctly now. Please let us know if you are still having trouble here!
