### ISSUE TITLE
firefox on Mac - no video

### ISSUE THREAD

**Issue by polycopter** [udacity/sdc-issue-reports#375]
Safari on my Mac mini works fine, Firefox FAILS to display the video content (just a black space where it should be).

**Comment by dm1299** [comment]
I got an error when I play the video using Safari,  chrome works fine for me.
302 GET /notebooks/test_output.mp4 (::1) 0.95ms

**Comment by jessluls** [comment]
Unfortunately we can't help troubleshoot non-content specific tech issues. Feel free to write to support@udacity.com for more assistance if necessary. Thanks!
