### ISSUE TITLE
Suggestion to switch two sections of course material

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#376]
Change the order of P4 _Advanced Lane Finding_ and P5 _Vehicle Detection and Tracking_.

Suggested by one of my mentees, Jakob, with the following thoughts:

>I suggest the inversion, as that would allow us to 'prune' the cars from the lane recognition algo, and so car wheels and features, for example striped of white in a white car, can be substracted from the image, so we have only the 'static' part of the road left.

Passing this on to the content team for consideration.

**Comment by ryan-keenan** [comment]
Thanks for passing this on!  We may change the ordering of lessons in the future (like putting all of CV before DL) so we'll keep this in mind at that time.
