### ISSUE TITLE
Wron docker command

### ISSUE THREAD

**Issue by adai183** [udacity/sdc-issue-reports#377]

**Comment by adai183** [comment]
Finding Lane Lines:

I am not sure about this.
But the docker command gives me an error.
The text says :
# Docker
docker run -it --rm -p 8888:8888 -v ${pwd}:/src udacity/carnd-term1-starer-kit test.ipynb
# OR
docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starer-kit test.ipynb

I get this error:
Unable to find image 'udacity/carnd-term1-starer-kit:latest' locally
Pulling repository docker.io/udacity/carnd-term1-starer-kit
docker: Error: image udacity/carnd-term1-starer-kit:latest not found.

This command works for me:
docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starter-kit

**Comment by birdchan** [comment]
I am not sure why I keep getting the 'Unable to find image' error. Anyone has any ideas? 

Brians-MBP:CarND-Term1-Starter-Kit-Test brian$ docker pull udacity/carnd-term1-starter-kit
Using default tag: latest
latest: Pulling from udacity/carnd-term1-starter-kit
Digest: sha256:5a5e231a5542728dcfe128ea3ea94ddabfa21fd5cae44d9f73ac4704cbcf70e6
Status: Image is up to date for udacity/carnd-term1-starter-kit:latest

Brians-MBP:CarND-Term1-Starter-Kit-Test brian$ 
Brians-MBP:CarND-Term1-Starter-Kit-Test brian$ docker run -it --rm -p 8888:8888 -v `pwd`:/src udacity/carnd-term1-starer-kit test.ipynb 
Unable to find image 'udacity/carnd-term1-starer-kit:latest' locally
docker: Error response from daemon: repository udacity/carnd-term1-starer-kit not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by domluna** [comment]
@adai183 @birdchan Looks like a typo change `starer` to `starter`.  I've correctly the typo on the page. Thanks for reporting this 👍

**Comment by birdchan** [comment]
thx @domluna !

**Comment by farhanhubble** [comment]
`docker run -it --rm -p 8888:8888 -v ${pwd}:/src udacity/carnd-term1-starer-kit test.ipynb` 
should be changed to
 `docker run -it --rm -p 8888:8888 -v $(pwd):/src udacity/carnd-term1-starer-kit test.ipynb` 
or to 
`docker run -it --rm -p 8888:8888 -v ${PWD}:/src udacity/carnd-term1-starer-kit test.ipynb`

pwd is the shell command and PWD the shell variable that prints the current working directory. If you want to substitute the output of the command use `$(pwd)` (lower case, inside parentheses). For substituting  the shell variable's value `${PWD}` (upper case, within braces).
