### ISSUE TITLE
Mentor name is showing up incorrectly on web and iOS

### ISSUE THREAD

**Issue by georgebabu** [udacity/sdc-issue-reports#379]
My mentor's name is Lance (confirmed by him, and as stated in the mentor bio). However, the mentor name under their avatar shows up as Rajeev

**Comment by georgebabu** [comment]
Screenshot available here: https://www.dropbox.com/s/94vx45pazd4wkfj/IMG_0004.PNG?dl=0

**Comment by swwelch** [comment]
Hi George, the mentorship team fixed an error on Friday related to Lance's account. They'll look into his profile today to double check. I'm going to close this bug now, but please let me know if it is still a problem!
