### ISSUE TITLE
Problem Accessing the course content for SDC NanoDegree

### ISSUE THREAD

**Issue by raghavendrabathula** [udacity/sdc-issue-reports#38]
When I sign I am redirected to a five page slide show.URL directly goes to  https://classroom.udacity.com/nanodegrees/nd013 and I cannot come out of it.

**Comment by raghavendrabathula** [comment]
https://classroom.udacity.com/nanodegrees/nd013/syllabus is the page it is opening. It is a slide show with 5 pages. And I am unable to access the course content

**Comment by Brok-Bucholtz** [comment]
@raghavendrabathula 

Hey Raghavendra,
I'm sorry you're having trouble accessing the NanoDegree.  I'm looking into this and I'll let you know what I find.  Can you access [this link](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/facdff19-61a5-47e4-8179-a6a5dc28987f/concepts/5b8dcedc-49cf-4d8f-8139-9b2023f1ce8d)?

**Comment by Brok-Bucholtz** [comment]
@raghavendrabathula 

We fixed the issue, so you should be able to access the content.  If it's not, let use know!
