### ISSUE TITLE
Lesson 18 Advanced Lane Finding code typo

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#380]
Lesson 28. HLS and Color Thresholds

First code block, line

gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

should be

gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

**Comment by ryan-keenan** [comment]
Thanks for catching this!  Fixed now.
