### ISSUE TITLE
Mentor checkin reminders make mentor communication impossible temporarily

### ISSUE THREAD

**Issue by zayfod** [udacity/sdc-issue-reports#381]
Mentor checkin reminders show up 5 days before chekins are due. These reminders "replace" the regular mentor communication panel and make communication with the mentor impossible until a checkin is submitted.

While checkins are fairly simple there are situations in which one may want to communicate with a mentor, intentionally delaying a checkin for some time.

I have experienced this a few times already but here is my latest situation:
- the due date for P2 and the next mentor checking coincide - next Monday
- I know that I am close to completing the project, want to focus on it and report the P2 submission as part of my next checkin
- I have a topic that I want to discuss with my mentor but I have to make a choice - either do the mentor checking now (before completing the project) to unblock the interface or accept that there will be no mentor communication until P2 is submitted.

**Comment by swwelch** [comment]
Hi @Zayfod,

Thanks for letting us know! I've filed a bug report with the Mentorship operations team, and they'll look into this further. I'll close the issue on this board for now.
