### ISSUE TITLE
Video 4: Music too loud.

### ISSUE THREAD

**Issue by SherylHohman** [udacity/sdc-issue-reports#382]
Very Difficult to hear Sebastian over the music. Distracting, and in some places, I cannot even make out what he's saying. Lower Volume Music, Less of a Beat in the music, or even: No music! We're pretty hyped already. We really just want to hear what Sebastian has to say :-)

**Comment by justineudacity** [comment]
@jessluls do you have a link to this video?

**Comment by jessluls** [comment]
@sherylhohman - can you link us to the video you were referencing in this ticket? sorry - know it's been awhile :)
