### ISSUE TITLE
Lessons 18 and 20: Vehicle Detection and Tracking

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#384]
For lessons 18 and 20, there is no link to download the test images so that I can try out the  code on my own. Please post them.

**Comment by ryan-keenan** [comment]
sorry for the delay on this issue!  I believe you're referring to the "SciKit Image HOG" and "Combine and Normalize Features" exercises.  I've now moved the "Data Exploration" exercise before these and you can find the links to the data there.  https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/fd66c083-4ccb-4fe3-bda1-c29db76f50a0/concepts/8c5ca570-3888-459b-9189-94cbfb8ef02c
