### ISSUE TITLE
Lesson 2 Run Some Code Troubleshooting

### ISSUE THREAD

**Issue by dm1299** [udacity/sdc-issue-reports#386]
The following code did't work for Mac OS
import imageio
imageio.plugins.ffmpeg.download()
Traceback (most recent call last):
File "", line 1, in 
AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'

**Comment by dm1299** [comment]
The following code did't work for Mac OS
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  This issue has been addressed on the [forums](https://carnd-forums.udacity.com) if you search something like "import imageio" you'll see discussions and solutions for this issue.
