### ISSUE TITLE
Slack only holds 3 days worth of messages

### ISSUE THREAD

**Issue by hkorre** [udacity/sdc-issue-reports#387]
The slack account has so many messages for this TEAM that it's deleting messages that are only 3 days old

For instance, p-vehicle-detection won't show messages older than Jan 19th (on Jan 22nd). This is making it difficult to learn from the other students, as their insights disappear after only 3 days.

You're currently using the free plan. Could Udacity upgrade to one that will hold more messages?

**Comment by pcs42** [comment]
My slack is not even showing that channel :O Was looking for some channel to discuss classifier training/settings since mine is crappy, although validation is solid with >98%.

**Comment by jessluls** [comment]
We have implemented paid Slack!
