### ISSUE TITLE
Fix Conda4.2 "PaddingError" on Windows machines

### ISSUE THREAD

**Issue by SherylHohman** [udacity/sdc-issue-reports#389]
For windows machines, a downdgade to conda 4.1.1 and/or a meta.yml file with the code `build:
  ignore_prefix_files: True` may fix issues with anaconda/miniconda/conda and package issues on some windows machines.

PR #54 in CarND-Term1-Starter-Kit addresses this. see (2nd set of) comments in PR for details on the cause and alternate solutions.

**Comment by domluna** [comment]
Accepted the PR.
