### ISSUE TITLE
Typo: 7. Nanodegree Support > Feedback

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/sdc-issue-reports#39]
If you find an error, check there to see if it has already been filed. If hasn't, you can file an issue by clicking on the "Add issue" button, adding a title, and entering a description in the details (you will need at GitHub account for this).

Typos:

1. "if hasn't"
2. "need at Github"

should read:

If you find an error, check there to see if it has already been filed. If it hasn't, you can file an issue by clicking on the "Add issue" button, adding a title, and entering a description in the details (you will need a GitHub account for this).

**Comment by Brok-Bucholtz** [comment]
@matthewzimmer 

Hey Matthew!  Thanks for spotting the typo.  I added your suggestions and now it looks great!
