### ISSUE TITLE
transform_sqrt parameter in scikit-image Quiz

### ISSUE THREAD

**Issue by thomasantony** [udacity/sdc-issue-reports#390]
In Lesson 19 in the Vehicle tracking module, the solution code uses a parameter called 'transform_sqrt=True' when calling the hog() function. This parameter is never explained in the notes above the quiz and the quiz cannot be passed without this parameter.

**Comment by ryan-keenan** [comment]
Thanks for reporting this and sorry for the delay!  I added mention of this keyword in the text before the quiz now and explicitly say to not change it from the default value of `transform_sqrt=False` for the quiz.  Solution and grading code also updated accordingly.
