### ISSUE TITLE
Lesson 2 Finding Lane Lines, missing matplotlib show() call

### ISSUE THREAD

**Issue by RNabel** [udacity/sdc-issue-reports#391]
In order to display the filtered image I had to add the line `plt.show()` after the provided code.

System info:
IDE: PyCharm
OS: Linux Mint 18

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  I added the `plt.show()` at the end of the code snippet (assuming you're referring to "Color Selection Code Example")

**Comment by RNabel** [comment]
Yep, that's the one - thank you for adding the line!
