### ISSUE TITLE
Miniflow: Linear Transform

### ISSUE THREAD

**Issue by adai183** [udacity/sdc-issue-reports#392]
the video for "animated example emphasizing a pixel is a feature" does not show up.

**Comment by domluna** [comment]
@adai183 This video doesn't appear?

![image](https://www.dropbox.com/s/s4erurzz68ilhew/Screenshot%202017-01-24%2012.42.33.png?dl=1)

It shows up when I visit it.

**Comment by adai183** [comment]
Exactly. It doesn't show up. I am using chrome.

I see this:
<img width="1440" alt="screen shot 2017-01-24 at 18 50 14" src="https://cloud.githubusercontent.com/assets/13679375/22259532/fb3eaac2-e265-11e6-93f2-4a9596e2dec0.png">

**Comment by domluna** [comment]
Can you access this link https://s3.amazonaws.com/content.udacity-data.com/courses/carnd/videos/hawk-zoom1.mp4?

Check the console to see if anything matching that link has an error.

**Comment by adai183** [comment]
Yes. The link works

I get 2 error in the console:

Failed to load resource: the server responded with a status of 429 (Too Many Requests)

f6fccba8-0009-4d05-9356-fae428b6efb4:1 Uncaught (in promise) {"type":"error.list","request_id":"apq6g7nj6tfi7t4ekk60","errors":[{"code":"rate_limit_exceeded","message":"More than 999 requests received in 1 minute"}]}

**Comment by domluna** [comment]
Try refreshing the page now.

**Comment by adai183** [comment]
It works. Awesome.
