### ISSUE TITLE
MiniFlow Cost Quiz

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#395]
Students reporting in the forum that there is an error
"'Input' object has no attribute 'outbound_layers'" when you submit at haven't changed any code.
Link to forum post
https://discussions.udacity.com/t/seeing-some-wrong-info-when-submitting-answer/214168

**Comment by domluna** [comment]
Thanks @GemmaLaraSavill the issue should be fixed, made a post in the forums as well 🙂 .
