### ISSUE TITLE
Inconsistent Class names in MiniFlow section

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#397]
e.g. _4. Forward Propagation_ and _6. Learning and Loss_ call the Class `Node`,
while _5. Forward Propagation Solution_ calls it `Neuron`.

Gets confusing when writing the code yourself outside of the Udacity interpreter.

I think it would make sense to switch them to `Neuron`.

**Comment by domluna** [comment]
@martin-martin Try refreshing the page, it should all read `Node`. There was a recent change to use `Node` instead of `Neuron` or `Layer`.

**Comment by martin-martin** [comment]
It's still `Neuron` in the code in _5. Forward Propagation Solution_

![image](https://cloud.githubusercontent.com/assets/12371494/22391904/cc13f404-e4b9-11e6-9bbe-b73fbd3709e1.png)

**Comment by domluna** [comment]
Reset the quiz and `Node` should appear.

**Comment by martin-martin** [comment]
Gotcha, that worked!
All set now : )
