### ISSUE TITLE
Inconsistent label names on Confluency

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#40]
I noticed there was a tag/topic called "houghtransformp" Not sure what the p here stands for. 

Also, the naming convention also goes against the other label names like "finding-lane-lines".

Could we have more consistent naming conventions generated by the moderators/admins?

**Comment by swwelch** [comment]
Hi! houghtransformp probably refers to the HoughTransformP function in the lane lines project (the probablistic hough transform). 

I believe that any student can create tags, but we can definitely look into consolidating similar tags!

**Comment by sahiljuneja** [comment]
Hey  @swwelch , yeah i noticed the probabilistic HT later through another question on the forums. But the primary tag should cover what the lecture or topic is about. The lectures are about Hough Transforms (in general) and not about probabilistic HT because the latter is not actually explained in the lecture videos. It sneaked into the code.

But yes, more consistency would be appreciated. Thank you!

**Comment by swwelch** [comment]
Hi! I changed the houghtransformp label to hough-transform on those posts, and deleted the houughtransformp label. Also did the same for the region-of-interest posts. Thanks for reporting!
