### ISSUE TITLE
Submission Tips Video Did Not Play

### ISSUE THREAD

**Issue by wfs** [udacity/sdc-issue-reports#400]
At the bottom of my submission review there was an image of a guy and a link to watch a 3 min video on how to review and resubmit your project 2 work. When I clicked it, just showed black box with horizontal progress bar and play / pause button.

I'm using chrome on ubuntu 16.04 64-bit.

**Comment by swwelch** [comment]
Hi @wfs,

Thanks for letting us know! A bug report has been filed with the reviews team.
