### ISSUE TITLE
Vehicle Detection and Tracking - Quiz Lesson 19

### ISSUE THREAD

**Issue by ksakmann** [udacity/sdc-issue-reports#404]
The quiz checker only returns a positive result if 
` transform_sqrt=True`
is included in the parameter list for `hog(...)`. But transform_qrt is not discussed.
If it's important it should be mentioned in the material beforehand.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  I've added mention of this keyword now but explicitly said to leave it at the default value of `transform_sqrt=False` for the quiz, and changed the solution and grading code accordingly.
