### ISSUE TITLE
Typo in Code in L21.14 Vehicle Tracking -> Explore Color Spaces

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#405]
Explore Color Spaces code snippet second-to-last line is currently
```
plot3d(img_small_HSV, img_small_rgb, , axis_labels=list("HSV"))
```
which returns Syntax Error because there is an extra comma after `img_small_rgb`. The code should be
```
plot3d(img_small_HSV, img_small_rgb, axis_labels=list("HSV"))
```

I have tested this (the snippet using the second line) in an ipynb.

**Comment by ryan-keenan** [comment]
thanks for pointing this out Jessica!  Fixed now.
