### ISSUE TITLE
Typo in Vehicle Detection and Tracking

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#406]
Lesson 18: Data Exploration

"These datasets are comprised of **a** images taken from the GTI vehicle image database, the KITTI vision benchmark suite,"

Should be

"These datasets are comprised of images taken from the GTI vehicle image database, the KITTI vision benchmark suite"

**Comment by ryan-keenan** [comment]
Thanks for catching this Deborah!  Fixed now.
