### ISSUE TITLE
scikit-image HOG quiz

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#407]
The scikit-image HOG Quiz in the Vehicle Detection and Tracking(Lesson #19) only passes if 
`transform_sqrt=True` is passed to the hog function. This was nowhere specified as a requirement to pass the quiz and should perhaps be revised.

The following invocation of hog causes the quiz to be marked as failed. However, adding the above flag causes it to be passed.

```
features = hog(img, orientations=orient, 
                                  pixels_per_cell=(pix_per_cell, pix_per_cell), 
                                  cells_per_block=(cell_per_block, cell_per_block), 
                                  visualise=vis, feature_vector=feature_vec)
```

**Comment by ryan-keenan** [comment]
Thanks for reporting this Deborah!  I've added a mention of the `transform_sqrt` keyword to the text before the quiz but explicitly noted that it's not necessary here and changed the solution to reflect that.
