### ISSUE TITLE
Miniflow / 4. Theory... - formatting of file name

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#41]
Here: http://bit.ly/2dSaah5 in "Quiz 1 - Passing Values forward" point 2:

`miniflow.py` is not formatted as code.

**Comment by Brok-Bucholtz** [comment]
@martin-martin 

Filenames shouldn't be formatted as code.  The code formatting for the filenames was removed.  Thanks for letting us know!
