### ISSUE TITLE
Finding Corners exercise -- clearer setup / instructions

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#412]
1st sentence:  "...to automatically find and draw corners in your image."  what is my image? it's not clear what image is going to be used.  the big heading "you're going to a result like this:" still doesn't clearly say that that image is actually the sample image.
it would be clearer if it read "...to automatically find and draw corners in a sample image.  The sample image we're going to be using is shown below with the output of drawChessboardCorners() superimposed on top:"
[ image ]

"Your assignment is to enter the number of corners in each row of the image as it appears above and enter that value in nx. ..."

In general, at this point in the course, this exercise is so trivial in terms of what it is asking the student to do (count and enter integers in placeholders) that I question whether it would be better as just an overview of the chessboard methods that it recommends the student look up (why not just put that information in the page?).  That or make the coding part more challenging.

**Comment by ryan-keenan** [comment]
Thank you for this feedback!  I made changes to the text to add clarity.  I agree the exercise is trivial so I'll see if I can make it more interesting or just swap out the quiz for more discussion / text / images
