### ISSUE TITLE
Completed Project 1 & 2 now showing "Project Due"

### ISSUE THREAD

**Issue by wfs** [udacity/sdc-issue-reports#413]
This is for my account "andrew.d.wilkie@gmail.com". I really don't want to have to resubmit them both just to try to fix the status.

**Comment by wfs** [comment]
Now showing as Completed, so appears to be fixed. Thanks.

**Comment by MIC7** [comment]
I was having the same issue, which also now appears to be fixed.

**Comment by wfs** [comment]
fyi, issue is showing again for my Project 1 status. I'm going to ignore it this time.
