### ISSUE TITLE
Blank feedback pages

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#415]
Is the feedback page for SVM in the course supposed to be blank? All it says is "Please tell us what you think..." and then only the Next button there.

Similar for Decision Trees lesson.

**Comment by ryan-keenan** [comment]
@awbrown90 when we spoke before I didn't realize there is actually a comment box that appears when someone provides a 0-10 rating so "tell us what you think" is not necessarily the wrong wording.  But some explanation to provide a rating in the tab at the lower-right and suggestions for improvement either there or in the waffle board would be great.   Also, the classroom team just rolled out a feedback modal that comes at the end of each lesson and might make these feedback pages redundant (and extra annoying) so let's be sure to figure out where the new feedback modals are popping up and how to pipe that data into our dashboard if we're removing the 0-10 ratings.

**Comment by baumanab** [comment]
Closed since this has been resolved via changes to modal.
