### ISSUE TITLE
SVM Lesson, Lecture 22

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#416]
Shouldn't the lecture "SVM Gamma Parameter" be before the quiz in lecture 20 on Kernel and Gamma.

The explanation for Gamma is after the quiz which asks about how the parameters affect the output.

**Comment by ryan-keenan** [comment]
Please have a look at this @awbrown90

**Comment by awbrown90** [comment]
@sahiljuneja I think the placement of these concepts are ok, the quiz introduces the idea of parameters and has a short quiz aiming more towards a linear kernel that can be answered without understanding gamma. The later Gamma section goes into more detail about gamma after the quiz introduced it.
