### ISSUE TITLE
Vehicle Detection and Tracking: Lecture 15. Spatial Binning of Color

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#418]
We talk about getting a feature vector. 

I don't think till then it was properly explained what a feature vector really is.

Plus, the coding quiz, outputs a plot for "Spatially Binned Features". But there's no explanation of what that plot really represents clearly. I think some more details could help more since it helps develop an intuition for data analysis.

**Comment by ryan-keenan** [comment]
@awbrown90 please have a look and see where you think we should insert a sort of formal definition of "feature vector".  I think that phrase is used earlier in the lesson, so maybe somewhere near the beginning.

**Comment by awbrown90** [comment]
@sahiljuneja added a link to a definition of feature vectors  in the section 15, which was the first time feature vectors were mentioned. I thought the previous concepts about features described the basic idea behind using multiple features well.
