### ISSUE TITLE
Vehicle Detection and Tracking: Lecture 12. Histogram of Color

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#419]
This lecture made me think if the course ever covered a proper explanation on what a histogram really is and how it's helpful. Correct me if I am wrong here.

It's good to have code that helps us print out these histograms, but the lecture doesn't really help interpret those plots. Mentioned this before, but having more explanations on how the plot can be used to actually analyze the data is extremely important. 

This is a personal opinion - there is no intuition being developed here. At times I am not sure how much you expect us to discover and learn ourselves (which is great) and how much you want to explain through the lectures (like how you did with Project 2 by releasing videos to somewhat walk through the project). But there seems to be more importance on the code than developing strong concepts and intuition. 

You guys add amazing content, but SVM, DT, and this project's lessons seem more high-level overviews to me. [Again, open for discussion, since I don't notice other student's raising an issue which is equally surprising honestly]

**Comment by sahiljuneja** [comment]
@ryan-keenan Hope you don't mind me tagging you here. Would like to know what you think for this particular problem.  Thanks again for all your work!

**Comment by ryan-keenan** [comment]
Thanks for your feedback!  All valid points for sure and I'll look into how we can make this better ;)

**Comment by ryan-keenan** [comment]
@awbrown90, perhaps you could add an example showing histograms of two very different colored images (or cutouts from the previous exercises) and add a little explanation of what's going on.  Here's the current concept: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/fd66c083-4ccb-4fe3-bda1-c29db76f50a0/concepts/4f0692c6-e22d-4f28-b5d0-7990a4d8de86
