### ISSUE TITLE
Unclear instructions on "Extract HOG features just once"

### ISSUE THREAD

**Issue by philbort** [udacity/sdc-issue-reports#426]
In "37. Tips and Tricks for the Project" of the "Vehicle Detection and Tracking" module, the instructions of "Extract HOG features just once for the entire region of interest in each full image / video frame" are very vague. Can we get a clearer and more detailed update? Thank you.

**Comment by ryan-keenan** [comment]
@awbrown90 This should definitely be added as soon as possible to the Vehicle Detection lesson "Tips and Tricks" concept.   I explained it and walked through the code I use to do this in last night's livestream.  You can find the explanation starting at 46:50 in the video: https://www.youtube.com/watch?v=P2zwrTM8ueA&feature=youtu.be and I can send you the code from the notebook if you want.

**Comment by awbrown90** [comment]
@philbort just created a new concept that goes over hog subsampling and should be made public soon
