### ISSUE TITLE
Runtime bug on Vehicle Detection: Search and Classify

### ISSUE THREAD

**Issue by ckirksey3** [udacity/sdc-issue-reports#428]
I get a value error when I run the included code in the Search and Classify lab. Here's the output: File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
  Environment: {'executor_result': {u'vm_time': 3.3284709453582764, u'stdout': u'', u'vm_creation_time': 0.0024061203002929688, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n  File "vm_main3.py", line 47, in <module>\n    import main\n  File "/tmp/vmuser_tzggbeawkw/main.py", line 2, in <module>\n    import aiMain\n  File "/tmp/vmuser_tzggbeawkw/aiMain.py", line 113, in <module>\n    my_windows = slide_window(image, x_start_stop=[None, None], y_start_stop=[None, None], \nNameError: name \'slide_window\' is not defined\n', u'exec_server_time': 6.2914590835571289, u'exec_status': u'error'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'error'}
  Submission: {'_operation': 'REGRADE', u'solution.py': u"# Define a function to extract features from a single image window\n# This function is very similar to extract_features()\n# just for a single image rather than list of images\ndef single_img_features(img, color_space='RGB', spatial_size=(32, 32),\n                        hist_bins=32, orient=9, \n                        pix_per_cell=8, cell_per_block=2, hog_channel=0,\n                        spatial_feat=True, hist_feat=True, hog_feat=True):    \n    #1) Define an empty list to receive features\n    img_features = []\n    #2) Apply color conversion if other than 'RGB'\n    if color_space != 'RGB':\n        if color_space == 'HSV':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)\n        elif color_space == 'LUV':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2LUV)\n        elif color_space == 'HLS':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2HLS)\n        elif color_space == 'YUV':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2YUV)\n        elif color_space == 'YCrCb':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2YCrCb)\n    else: feature_image = np.copy(img)      \n    #3) Compute spatial features if flag is set\n    if spatial_feat == True:\n        spatial_features = bin_spatial(feature_image, size=spatial_size)\n        #4) Append features to list\n        img_features.append(spatial_features)\n    #5) Compute histogram features if flag is set\n    if hist_feat == True:\n        hist_features = color_hist(feature_image, nbins=hist_bins)\n        #6) Append features to list\n        img_features.append(hist_features)\n    #7) Compute HOG features if flag is set\n    if hog_feat == True:\n        if hog_channel == 'ALL':\n            hog_features = []\n            for channel in range(feature_image.shape[2]):\n                hog_features.extend(get_hog_features(feature_image[:,:,channel], \n                                    orient, pix_per_cell, cell_per_block, \n                                    vis=False, feature_vec=True))      \n        else:\n            hog_features = get_hog_features(feature_image[:,:,hog_channel], orient, \n                        pix_per_cell, cell_per_block, vis=False, feature_vec=True)\n        #8) Append features to list\n        img_features.append(hog_features)\n\n    #9) Return concatenated array of features\n    return np.concatenate(img_features)\n\n# Define a function you will pass an image \n# and the list of windows to be searched (output of slide_windows())\ndef search_windows(img, windows, clf, scaler, color_space='RGB', \n                    spatial_size=(32, 32), hist_bins=32, \n                    hist_range=(0, 256), orient=9, \n                    pix_per_cell=8, cell_per_block=2, \n                    hog_channel=0, spatial_feat=True, \n                    hist_feat=True, hog_feat=True):\n\n    #1) Create an empty list to receive positive detection windows\n    on_windows = []\n    #2) Iterate over all windows in the list\n    for window in windows:\n        #3) Extract the test window from original image\n        test_img = cv2.resize(img[window[0][1]:window[1][1], window[0][0]:window[1][0]], (64, 64))      \n        #4) Extract features for that window using single_img_features()\n        features = single_img_features(test_img, color_space=color_space, \n                            spatial_size=spatial_size, hist_bins=hist_bins, \n                            orient=orient, pix_per_cell=pix_per_cell, \n                            cell_per_block=cell_per_block, \n                            hog_channel=hog_channel, spatial_feat=spatial_feat, \n                            hist_feat=hist_feat, hog_feat=hog_feat)\n        #5) Scale extracted features to be fed to classifier\n        test_features = scaler.transform(np.array(features).reshape(1, -1))\n        #6) Predict using your classifier\n        prediction = clf.predict(test_features)\n        #7) If positive (prediction == 1) then save the window\n        if prediction == 1:\n            on_windows.append(window)\n    #8) Return windows for positive detections\n    return on_windows\n    ", u'lesson_functions.py': u"import matplotlib.image as mpimg\nimport numpy as np\nimport cv2\nfrom skimage.feature import hog\n# Define a function to return HOG features and visualization\ndef get_hog_features(img, orient, pix_per_cell, cell_per_block, \n                        vis=False, feature_vec=True):\n    # Call with two outputs if vis==True\n    if vis == True:\n        features, hog_image = hog(img, orientations=orient, \n                                  pixels_per_cell=(pix_per_cell, pix_per_cell),\n                                  cells_per_block=(cell_per_block, cell_per_block), \n                                  transform_sqrt=True, \n                                  visualise=vis, feature_vector=feature_vec)\n        return features, hog_image\n    # Otherwise call with one output\n    else:      \n        features = hog(img, orientations=orient, \n                       pixels_per_cell=(pix_per_cell, pix_per_cell),\n                       cells_per_block=(cell_per_block, cell_per_block), \n                       transform_sqrt=True, \n                       visualise=vis, feature_vector=feature_vec)\n        return features\n\n# Define a function to compute binned color features  \ndef bin_spatial(img, size=(32, 32)):\n    # Use cv2.resize().ravel() to create the feature vector\n    features = cv2.resize(img, size).ravel() \n    # Return the feature vector\n    return features\n\n# Define a function to compute color histogram features \n# NEED TO CHANGE bins_range if reading .png files with mpimg!\ndef color_hist(img, nbins=32, bins_range=(0, 256)):\n    # Compute the histogram of the color channels separately\n    channel1_hist = np.histogram(img[:,:,0], bins=nbins, range=bins_range)\n    channel2_hist = np.histogram(img[:,:,1], bins=nbins, range=bins_range)\n    channel3_hist = np.histogram(img[:,:,2], bins=nbins, range=bins_range)\n    # Concatenate the histograms into a single feature vector\n    hist_features = np.concatenate((channel1_hist[0], channel2_hist[0], channel3_hist[0]))\n    # Return the individual histograms, bin_centers and feature vector\n    return hist_features\n\n# Define a function to extract features from a list of images\n# Have this function call bin_spatial() and color_hist()\ndef extract_features(imgs, color_space='RGB', spatial_size=(32, 32),\n                        hist_bins=32, orient=9, \n                        pix_per_cell=8, cell_per_block=2, hog_channel=0,\n                        spatial_feat=True, hist_feat=True, hog_feat=True):\n    # Create a list to append feature vectors to\n    features = []\n    # Iterate through the list of images\n    for file in imgs:\n        file_features = []\n        # Read in each one by one\n        image = mpimg.imread(file)\n        # apply color conversion if other than 'RGB'\n        if color_space != 'RGB':\n            if color_space == 'HSV':\n                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)\n            elif color_space == 'LUV':\n                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2LUV)\n            elif color_space == 'HLS':\n                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)\n            elif color_space == 'YUV':\n                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2YUV)\n            elif color_space == 'YCrCb':\n                feature_image = cv2.cvtColor(image, cv2.COLOR_RGB2YCrCb)\n        else: feature_image = np.copy(image)      \n\n        if spatial_feat == True:\n            spatial_features = bin_spatial(feature_image, size=spatial_size)\n            file_features.append(spatial_features)\n        if hist_feat == True:\n            # Apply color_hist()\n            hist_features = color_hist(feature_image, nbins=hist_bins)\n            file_features.append(hist_features)\n        if hog_feat == True:\n        # Call get_hog_features() with vis=False, feature_vec=True\n            if hog_channel == 'ALL':\n                hog_features = []\n                for channel in range(feature_image.shape[2]):\n                    hog_features.append(get_hog_features(feature_image[:,:,channel], \n                                        orient, pix_per_cell, cell_per_block, \n                                        vis=False, feature_vec=True))\n                hog_features = np.ravel(hog_features)        \n            else:\n                hog_features = get_hog_features(feature_image[:,:,hog_channel], orient, \n                            pix_per_cell, cell_per_block, vis=False, feature_vec=True)\n            # Append the new feature vector to the features list\n            file_features.append(hog_features)\n        features.append(np.concatenate(file_features))\n    # Return list of feature vectors\n    return features\n    \n# Define a function that takes an image,\n# start and stop positions in both x and y, \n# window size (x and y dimensions),  \n# and overlap fraction (for both x and y)\ndef slide_window(img, x_start_stop=[None, None], y_start_stop=[None, None], \n                    xy_window=(64, 64), xy_overlap=(0.5, 0.5)):\n    # If x and/or y start/stop positions not defined, set to image size\n    if x_start_stop[0] == None:\n        x_start_stop[0] = 0\n    if x_start_stop[1] == None:\n        x_start_stop[1] = img.shape[1]\n    if y_start_stop[0] == None:\n        y_start_stop[0] = 0\n    if y_start_stop[1] == None:\n        y_start_stop[1] = img.shape[0]\n    # Compute the span of the region to be searched    \n    xspan = x_start_stop[1] - x_start_stop[0]\n    yspan = y_start_stop[1] - y_start_stop[0]\n    # Compute the number of pixels per step in x/y\n    nx_pix_per_step = np.int(xy_window[0]*(1 - xy_overlap[0]))\n    ny_pix_per_step = np.int(xy_window[1]*(1 - xy_overlap[1]))\n    # Compute the number of windows in x/y\n    nx_windows = np.int(xspan/nx_pix_per_step) - 1\n    ny_windows = np.int(yspan/ny_pix_per_step) - 1\n    # Initialize a list to append window positions to\n    window_list = []\n    # Loop through finding x and y window positions\n    # Note: you could vectorize this step, but in practice\n    # you'll be considering windows one by one with your\n    # classifier, so looping makes sense\n    for ys in range(ny_windows):\n        for xs in range(nx_windows):\n            # Calculate window position\n            startx = xs*nx_pix_per_step + x_start_stop[0]\n            endx = startx + xy_window[0]\n            starty = ys*ny_pix_per_step + y_start_stop[0]\n            endy = starty + xy_window[1]\n            \n            # Append window position to list\n            window_list.append(((startx, starty), (endx, endy)))\n    # Return the list of windows\n    return window_list\n\n# Define a function to draw bounding boxes\ndef draw_boxes(img, bboxes, color=(0, 0, 255), thick=6):\n    # Make a copy of the image\n    imcopy = np.copy(img)\n    # Iterate through the bounding boxes\n    for bbox in bboxes:\n        # Draw a rectangle given bbox coordinates\n        cv2.rectangle(imcopy, bbox[0], bbox[1], color, thick)\n    # Return the image copy with boxes drawn\n    return imcopy\n", u'search_classify.py': u'import matplotlib.image as mpimg\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport cv2\nimport glob\nimport time\nfrom sklearn.svm import LinearSVC\nfrom sklearn.preprocessing import StandardScaler\nfrom skimage.feature import hog\nfrom lesson_functions import *\n# NOTE: the next import is only valid for scikit-learn version <= 0.17\n# for scikit-learn >= 0.18 use:\n# from sklearn.model_selection import train_test_split\nfrom sklearn.cross_validation import train_test_split\n\n# Define a function to extract features from a single image window\n# This function is very similar to extract_features()\n# just for a single image rather than list of images\ndef single_img_features(img, color_space=\'RGB\', spatial_size=(32, 32),\n                        hist_bins=32, orient=9, \n                        pix_per_cell=8, cell_per_block=2, hog_channel=0,\n                        spatial_feat=True, hist_feat=True, hog_feat=True):    \n    #1) Define an empty list to receive features\n    img_features = []\n    #2) Apply color conversion if other than \'RGB\'\n    if color_space != \'RGB\':\n        if color_space == \'HSV\':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)\n        elif color_space == \'LUV\':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2LUV)\n        elif color_space == \'HLS\':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2HLS)\n        elif color_space == \'YUV\':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2YUV)\n        elif color_space == \'YCrCb\':\n            feature_image = cv2.cvtColor(img, cv2.COLOR_RGB2YCrCb)\n    else: feature_image = np.copy(img)      \n    #3) Compute spatial features if flag is set\n    if spatial_feat == True:\n        spatial_features = bin_spatial(feature_image, size=spatial_size)\n        #4) Append features to list\n        img_features.append(spatial_features)\n    #5) Compute histogram features if flag is set\n    if hist_feat == True:\n        hist_features = color_hist(feature_image, nbins=hist_bins)\n        #6) Append features to list\n        img_features.append(hist_features)\n    #7) Compute HOG features if flag is set\n    if hog_feat == True:\n        if hog_channel == \'ALL\':\n            hog_features = []\n            for channel in range(feature_image.shape[2]):\n                hog_features.extend(get_hog_features(feature_image[:,:,channel], \n                                    orient, pix_per_cell, cell_per_block, \n                                    vis=False, feature_vec=True))      \n        else:\n            hog_features = get_hog_features(feature_image[:,:,hog_channel], orient, \n                        pix_per_cell, cell_per_block, vis=False, feature_vec=True)\n        #8) Append features to list\n        img_features.append(hog_features)\n\n    #9) Return concatenated array of features\n    return np.concatenate(img_features)\n\n# Define a function you will pass an image \n# and the list of windows to be searched (output of slide_windows())\ndef search_windows(img, windows, clf, scaler, color_space=\'RGB\', \n                    spatial_size=(32, 32), hist_bins=32, \n                    hist_range=(0, 256), orient=9, \n                    pix_per_cell=8, cell_per_block=2, \n                    hog_channel=0, spatial_feat=True, \n                    hist_feat=True, hog_feat=True):\n\n    #1) Create an empty list to receive positive detection windows\n    on_windows = []\n    #2) Iterate over all windows in the list\n    for window in windows:\n        #3) Extract the test window from original image\n        test_img = cv2.resize(img[window[0][1]:window[1][1], window[0][0]:window[1][0]], (64, 64))      \n        #4) Extract features for that window using single_img_features()\n        features = single_img_features(test_img, color_space=color_space, \n                            spatial_size=spatial_size, hist_bins=hist_bins, \n                            orient=orient, pix_per_cell=pix_per_cell, \n                            cell_per_block=cell_per_block, \n                            hog_channel=hog_channel, spatial_feat=spatial_feat, \n                            hist_feat=hist_feat, hog_feat=hog_feat)\n        #5) Scale extracted features to be fed to classifier\n        test_features = scaler.transform(np.array(features).reshape(1, -1))\n        #6) Predict using your classifier\n        prediction = clf.predict(test_features)\n        #7) If positive (prediction == 1) then save the window\n        if prediction == 1:\n            on_windows.append(window)\n    #8) Return windows for positive detections\n    return on_windows\n    \n    \n# Read in cars and notcars\nimages = glob.glob(\'*.jpeg\')\ncars = []\nnotcars = []\nfor image in images:\n    if \'image\' in image or \'extra\' in image:\n        notcars.append(image)\n    else:\n        cars.append(image)\n\n# Reduce the sample size because\n# The quiz evaluator times out after 13s of CPU time\nsample_size = 500\ncars = cars[0:sample_size]\nnotcars = notcars[0:sample_size]\n\n### TODO: Tweak these parameters and see how the results change.\ncolor_space = \'RGB\' # Can be RGB, HSV, LUV, HLS, YUV, YCrCb\norient = 9  # HOG orientations\npix_per_cell = 8 # HOG pixels per cell\ncell_per_block = 2 # HOG cells per block\nhog_channel = 0 # Can be 0, 1, 2, or "ALL"\nspatial_size = (16, 16) # Spatial binning dimensions\nhist_bins = 16    # Number of histogram bins\nspatial_feat = True # Spatial features on or off\nhist_feat = True # Histogram features on or off\nhog_feat = True # HOG features on or off\ny_start_stop = [None, None] # Min and max in y to search in slide_window()\n\ncar_features = extract_features(cars, color_space=color_space, \n                        spatial_size=spatial_size, hist_bins=hist_bins, \n                        orient=orient, pix_per_cell=pix_per_cell, \n                        cell_per_block=cell_per_block, \n                        hog_channel=hog_channel, spatial_feat=spatial_feat, \n                        hist_feat=hist_feat, hog_feat=hog_feat)\nnotcar_features = extract_features(notcars, color_space=color_space, \n                        spatial_size=spatial_size, hist_bins=hist_bins, \n                        orient=orient, pix_per_cell=pix_per_cell, \n                        cell_per_block=cell_per_block, \n                        hog_channel=hog_channel, spatial_feat=spatial_feat, \n                        hist_feat=hist_feat, hog_feat=hog_feat)\n\nX = np.vstack((car_features, notcar_features)).astype(np.float64)                        \n# Fit a per-column scaler\nX_scaler = StandardScaler().fit(X)\n# Apply the scaler to X\nscaled_X = X_scaler.transform(X)\n\n# Define the labels vector\ny = np.hstack((np.ones(len(car_features)), np.zeros(len(notcar_features))))\n\n\n# Split up data into randomized training and test sets\nrand_state = np.random.randint(0, 100)\nX_train, X_test, y_train, y_test = train_test_split(\n    scaled_X, y, test_size=0.2, random_state=rand_state)\n\nprint(\'Using:\',orient,\'orientations\',pix_per_cell,\n    \'pixels per cell and\', cell_per_block,\'cells per block\')\nprint(\'Feature vector length:\', len(X_train[0]))\n# Use a linear SVC \nsvc = LinearSVC()\n# Check the training time for the SVC\nt=time.time()\nsvc.fit(X_train, y_train)\nt2 = time.time()\nprint(round(t2-t, 2), \'Seconds to train SVC...\')\n# Check the score of the SVC\nprint(\'Test Accuracy of SVC = \', round(svc.score(X_test, y_test), 4))\n# Check the prediction time for a single sample\nt=time.time()\n\nimage = mpimg.imread(\'bbox-example-image.jpg\')\ndraw_image = np.copy(image)\n\n# Uncomment the following line if you extracted training\n# data from .png images (scaled 0 to 1 by mpimg) and the\n# image you are searching is a .jpg (scaled 0 to 255)\n#image = image.astype(np.float32)/255\n\nwindows = slide_window(image, x_start_stop=[None, None], y_start_stop=y_start_stop, \n                    xy_window=(96, 96), xy_overlap=(0.5, 0.5))\n\nhot_windows = search_windows(image, windows, svc, X_scaler, color_space=color_space, \n                        spatial_size=spatial_size, hist_bins=hist_bins, \n                        orient=orient, pix_per_cell=pix_per_cell, \n                        cell_per_block=cell_per_block, \n                        hog_channel=hog_channel, spatial_feat=spatial_feat, \n                        hist_feat=hist_feat, hog_feat=hog_feat)                       \n\nwindow_img = draw_boxes(draw_image, hot_windows, color=(0, 0, 255), thick=6)                    \n\nplt.imshow(window_img)\n\n\n'}

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  It was an error in the evaluation code.   Fixed now.
