### ISSUE TITLE
CarND-Behavioral-Cloning-P3 writeup_template.md typos

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#429]
There are a number of typos in the writeup_template.md file:

9c9
< **Behavrioal Cloning Project**
---
> **Behavioral Cloning Project**
11a12
>
43c44
< ####2. Submssion includes functional code
---
> ####2. Submission includes functional code
49c50
< ####3. Submssion code is usable and readable
---
> ####3. Submission code is usable and readable
55c56
< ####1. An appropriate model arcthiecture has been employed
---
> ####1. An appropriate model architecture has been employed

**Comment by domluna** [comment]
@brahmwindeler thanks, fixed the typos.
