### ISSUE TITLE
typo in tensorflow installation description

### ISSUE THREAD

**Issue by skh** [udacity/sdc-issue-reports#43]
In the sentence 'If you don't meet all of these requierments, please install the appropriate package(s).' the word 'requierments' should be 'requirements'.

Introduction to TensorFlow > 5. Installing TensorFlow

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a8adf8ea-39b6-4fa3-ac26-0870f1ef6ae8

**Comment by Brok-Bucholtz** [comment]
@skh 

Thanks for spotting the typo.  I change it from "requierments" to "requirements".
