### ISSUE TITLE
advanced lane finding - provide all sample images

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#430]
i think that for pretty much all of the coding exercises in this module, there should always be a link to download the sample image that will be loaded from the server when you run the code input into the browser.  2 reasons:  1) this module seems to be all about building the pipeline that will be used in the project and 2) i can write better code and iterate faster on my own machine.  i would prefer to download the sample image and work on the code locally and when i'm done, paste into the browser and submit my answer.

**Comment by ryan-keenan** [comment]
Thanks for the feedback!  We'll try to go through and put some more links in but keep in mind that in many cases the sample image is the one displayed in the browser so you can right-click on it and choose to download it directly.

**Comment by ryan-keenan** [comment]
@awbrown90 for this I was planning to put these images in the s3 bucket and add links to them.

**Comment by aikonbrasil** [comment]
Hi, I am looking for the same sample image. Is there any news ?
best,

**Comment by mvirgo** [comment]
All of these are now added for the Advanced Lane Finding section.
