### ISSUE TITLE
Beta Simulator: Fix Controller Input (P3: Behavioral Cloning)

### ISSUE THREAD

**Issue by pierluigiferrari** [udacity/sdc-issue-reports#434]
In the stable version I can use my Xbox 360 or PS3 controllers to steer the car, but in the beta version of the simulator this does not work, regardless of how you change the input settings in the simulator's input menu.

I can accelerate and brake with the joystick on my Xbox 360 controller, but I can not steer left or right.

I find it hard to record good training data with the keyboard or mouse (mouse works even worse for me than keyboard). The problem with the keyboard is that it's impossible to record smooth curves since you can't actually control the steering angle, but rather the change of the steering angle. So you end up just giving a few too strong steering commands per curve and the majority of the images recorded has steering angle zero even in curves. The mouse would theoretically take care of that issue, but if you've tried using the mouse you realize that it's hard to input really precise steering commands with the mouse, at least for me :). I always either over- or understeer because I move the mouse too far or not far enough. It's really hard to get it right.

**Comment by pierluigiferrari** [comment]
Not to make it sound too drastic above: It is of course possible to record usable training data with the keyboard, but it's a lot more annoying than with a game pad and the data will be of lower quality.

**Comment by awbrown90** [comment]
@pierluigiferrari thanks for the input, there has been a lot of changes to the steering commands, and it was the mouse addition I believe that knocked off the possibility of using the universal steering controller. I am confident I can get the joy stick control added back in. Yeah in fairness its not impossible at all to record good data using the mouse and keyboard, I was able to do it and got my bot running laps around the Jungle track. I did have a lot of practice using the mouse though :)

**Comment by domluna** [comment]
@awbrown90 Would it be possible to release the data you recorded for the jungle track? I think It would make it more accessible 🙂 .

**Comment by awbrown90** [comment]
@domluna yeah for sure

**Comment by pierluigiferrari** [comment]
Thanks @awbrown90!

**Comment by awbrown90** [comment]
Created a new branch 'extras' in https://github.com/udacity/self-driving-car-sim that includes the option of using the joystick again.

**Comment by autonomobil** [comment]
It this 'extras' still available? I don't find it at https://github.com/udacity/self-driving-car-sim/branches/all
