### ISSUE TITLE
mentor messages before check-in

### ISSUE THREAD

**Issue by caje731** [udacity/sdc-issue-reports#435]
I see that my mentor has sent me 5 messages as replies to my last check-in. I know this because the chat pop-up has a bubble with the number 5. However, since it's time for check-in once again, all I can see is the button to check-in. There's no way to see the previous messages my mentor sent me, before I actually do a check-in for this week.

**Comment by swwelch** [comment]
Hi @caje731,

Thanks for bringing this up! The mentorship team is aware of this issue, and will be looking into design changes to address it.
