### ISSUE TITLE
drive.py missing environment.yml / requirements.txt

### ISSUE THREAD

**Issue by 007** [udacity/sdc-issue-reports#436]
Need to add a package file for `drive.py`, missing at least socketio and eventlet, should probably also include PIL, flask, etc.

**Comment by domluna** [comment]
The starter kit has these packages https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment.yml

**Comment by 007** [comment]
My Readme was 2 weeks old, made no reference to starter project. Looks like docs are updated now, along with newer version of `drive.py`.
