### ISSUE TITLE
Instruction for P3 concerning local system settings

### ISSUE THREAD

**Issue by albert-killer** [udacity/sdc-issue-reports#437]
In order to avoid corrupted output using the simulator in project no. 3 (behavioral cloning) I had to change my system's local settings to US. Set to "german" before the result was getting only steering angles bouncing from 25° or -25° in autonomous mode, eventhoug getting appropriate predicted steering angles from my trained model. My system is ubuntu/linux mint. I added "export LANG=en_US.utf8" to the bashrc file. 
(cp.: https://carnd.slack.com/archives/p-behavioral-cloning/p1486939894021921=)

**Comment by awbrown90** [comment]
@albert-killer we could add some instructions in P3 that this is a known problem and then show how it can be addressed by adding "export LANG=en_US.utf8" to the bashrc file

**Comment by awbrown90** [comment]
@albert-killer this known issue along with the instructions for the fix has been added to the P3 README. Thanks
