### ISSUE TITLE
Suggest to add more AWS information in lesson

### ISSUE THREAD

**Issue by zhaotzheng** [udacity/sdc-issue-reports#438]
Dear Sir or Madam,

I enrolled in Self Driving Nanodegree on Udacity. I suggest to add more information about AWS for Project 2 in Term 1. Since I used Windows system and I'm new for AWS, I used two days to search how to upload dataset to AWS and tried different options. Otherwise, I couldn't train my model. So I suggest to add that information in the lesson, which would benefit future students.

Thanks. Have a good day!

Tiezheng Zhao

**Comment by jessluls** [comment]
Thanks for your feedback, we'll look into it!
