### ISSUE TITLE
typo: tf.placholder()

### ISSUE THREAD

**Issue by skh** [udacity/sdc-issue-reports#44]
tf.placholder() should probably be tf.placeholder()

It is mistyped more than once on Introduction to TensorFlow > 7. Quiz: TensorFlow Input

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a222f778-c0aa-45f0-97bc-7b3caf940f5b

**Comment by Brok-Bucholtz** [comment]
@skh 

Thanks for all your help Sonja!  I changed all the `tf.placholder()`'s to `tf.placeholder()`
