### ISSUE TITLE
alexnet.py needs updating to replace non public function

### ISSUE THREAD

**Issue by boulderZ** [udacity/sdc-issue-reports#442]
In alexnet.py there are two lines using tf.nn.relu_layer(). I can not find any documentation on this. Can someone show me what this function is and what the arguments are?

    # fc(4096, name='fc6')
    fc6W = tf.Variable(net_data["fc6"][0])
    fc6b = tf.Variable(net_data["fc6"][1])
    fc6 = tf.nn.relu_layer(tf.reshape(maxpool5, [-1, int(np.prod(maxpool5.get_shape()[1:]))]), fc6W, fc6b)

    # fc7
    # fc(4096, name='fc7')
    fc7W = tf.Variable(net_data["fc7"][0])
    fc7b = tf.Variable(net_data["fc7"][1])
    fc7 = tf.nn.relu_layer(fc6, fc7W, fc7b)

    if feature_extract:
        return fc7

I finally found this: https://github.com/tensorflow/tensorflow/issues/811
It says this function is not supposed to be public and should be deprecated.

And this: https://github.com/tensorflow/tensorflow/pull/828 which links to https://github.com/tensorflow/tensorflow/pull/828/commits/ed74b7d2c98a9a463f37dc9998fe99585f308081

This basically states that

    local3 = tf.nn.relu_layer(reshape, weights, biases, name=scope.name)
    is equivalent to:
    local3 = tf.nn.relu(tf.matmul(reshape, weights) + biases, name=scope.name)

The alexnet.py code should be updated with this change to avoid further confusion by students.

**Comment by boulderZ** [comment]
This function also in alexnet.py is also not documented. see:  https://github.com/tensorflow/tensorflow/issues/1434

tf.nn.xw_plus_b()
it is equivalent to:
tf.matmul(x, w) + b

this should also be changed.

**Comment by domluna** [comment]
@boulderZ I've updated alexnet.py to just use tf.nn.relu and tf.nn.matmul in these cases.
