### ISSUE TITLE
No mentor button for Feb class.

### ISSUE THREAD

**Issue by josemacenteno** [udacity/sdc-issue-reports#443]

**Comment by josemacenteno** [comment]
I started my Self Driving Car nanodegree class today.

I finished the Welcome class but I don't see the mentor button anywhere in the interface.

**Comment by josemacenteno** [comment]
https://www.dropbox.com/s/203gx4wczawo8zm/Mentor_waffle_board.JPG?dl=0

**Comment by mreichelt** [comment]
Yep, same issue here! No mentor button :-/

**Comment by rmic** [comment]
same thing here ...

**Comment by maciag** [comment]
The same here

**Comment by anuragreddygv323** [comment]
I dont have the mentor button on my Udacity course.

**Comment by jwcrawf** [comment]
+1

**Comment by jafcristobal** [comment]
also i don't have that mentor button!!!

**Comment by railsnoob** [comment]
Me too handle:viveksf on Udacity.

**Comment by KenOverholt** [comment]
Mine is missing too.

**Comment by quangnamee91** [comment]
Mine is missing too

**Comment by PaulAquila** [comment]
same here....

**Comment by railsnoob** [comment]
Me too ... Udacity handle: viveksf

**Comment by josemacenteno** [comment]
I refreshed a few minutes ago, My mentor is there :) yay!

**Comment by vinny-palumbo** [comment]
same here

**Comment by praneethsusarla** [comment]
I am able to talk to my mentor as I got a message from him. A message box got popped up and I interacted with him. but I didn't find any mentor button in the interface after I close the messaging box

**Comment by railsnoob** [comment]
Hi the Mentorship button is moved to the leftmost sidebar below the link for "Profile" . 

Thanks.

**Comment by rmic** [comment]
Everything is working fine for me now. I probably should just have waited a bit.

**Comment by jafcristobal** [comment]
i've it also. all corrected. Thanks.
