### ISSUE TITLE
Incorrect Docker image link

### ISSUE THREAD

**Issue by loshkovskyi** [udacity/sdc-issue-reports#445]
In the task description Docker image name should be changed from carnd-term1-starter-kit-test to carnd-term1-starter-kit.

There is no such image as "*-test" on public Docker Hub.

Issue on forums:
https://carnd-forums.udacity.com/display/CAR/questions/36914457/answers/38543553?flashId=1422938696

**Comment by swwelch** [comment]
Hi @loshkovskyi, I think this has been resolved, but if not, could you provide a link to where you are seeing that description?

**Comment by loshkovskyi** [comment]
@swwelch looks like it's still there: Lesson 2 Finding Lane Lines - Run Some Code!
I should have been more clear where I saw the issue.

**Comment by cameronwp** [comment]
Wow, can't believe this sat there for a month. I ran across it yesterday and updated the link. Should be good now!
