### ISSUE TITLE
[HIDDEN] Project: Traffic Sign Classifier

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#45]
It seems there is a redundant HIDDEN word in the title of the following page:

https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/614d4728-0fad-4c9d-a6c3-23227aef8f66/project

**Comment by domluna** [comment]
Thanks for the report, fixed!
