### ISSUE TITLE
Project 1 Lane Finding Videos not showing in Safari

### ISSUE THREAD

**Issue by michaelschleiss** [udacity/sdc-issue-reports#450]

**Comment by michaelschleiss** [comment]
When I run the Jupyter Notebook from the CarND-Term1-Starter-Kit-Test or from CarND-LaneLines-P1 videos are not playing within the notebook. There is only a white background in the size of the video and a text saying 'loading'. From the following forum post you can see, that there are other users with the same problem.

https://discussions.udacity.com/t/carnd-term1-starter-kit-test-video-wont-play-in-jupyter/214056/8

**Comment by ibrahim-mo** [comment]
I have the same issue too.

**Comment by jessluls** [comment]
Unfortunately it seems folks have trouble with Safari for this - we suggest using another browser. We recommend using Chrome (https://www.udacity.com/tech-requirements).
