### ISSUE TITLE
Lesson 2 - 18. Run Some Code! - Missing Dependencies

### ISSUE THREAD

**Issue by npadgett** [udacity/sdc-issue-reports#451]

**Comment by npadgett** [comment]
I'm on a mac and had to run the code below to get https://github.com/udacity/CarND-Term1-Starter-Kit-Test.git working properly.

conda install -c conda-forge tensorflow
python3 -m pip install moviepy

**Comment by domluna** [comment]
@npadgett did tensorflow and moviepy not install properly when you created the environment?

https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

**Comment by npadgett** [comment]
When I ran "conda env create -f environment.yml", I saw the error:

        Collecting tensorflow==0.12.1

          Could not find a version that satisfies the requirement
tensorflow==0.12.1 (from versions: )

        No matching distribution found for tensorflow==0.12.1

        CondaValueError: Value error: pip returned an error.

When I ran "import tensorflow as tf", I saw the error:

        ---------------------------------------------------------------------------
       ImportError                               Traceback (most
recent call last)        <ipython-input-5-41389fad42b5> in <module>()
      ----> 1 import tensorflow as tf
        ImportError: No module named 'tensorflow'


See below for all commands:

======================================================================


C02M50JYFD57:foo NPadgett$ conda -V

conda 4.3.11

C02M50JYFD57:foo NPadgett$ git clone
https://github.com/udacity/CarND-Term1-Starter-Kit.git

Cloning into 'CarND-Term1-Starter-Kit'...

remote: Counting objects: 203, done.

remote: Compressing objects: 100% (10/10), done.

remote: Total 203 (delta 3), reused 0 (delta 0), pack-reused 193

Receiving objects: 100% (203/203), 2.07 MiB | 1.04 MiB/s, done.

Resolving deltas: 100% (102/102), done.

Checking connectivity... done.

C02M50JYFD57:foo NPadgett$ cd CarND-Term1-Starter-Kit

C02M50JYFD57:CarND-Term1-Starter-Kit NPadgett$ conda env create -f
environment.yml

Fetching package metadata .............

Solving package specifications: .

ca-certificate 100% |################################| Time: 0:00:00   1.04
MB/s

icu-54.1-0.tar 100% |################################| Time: 0:00:00  36.03
MB/s

jpeg-9b-0.tar. 100% |################################| Time: 0:00:00   1.04
MB/s

libffi-3.2.1-3 100% |################################| Time: 0:00:00   1.62
MB/s

libgfortran-3. 100% |################################| Time: 0:00:00   1.99
MB/s

libsodium-1.0. 100% |################################| Time: 0:00:00   3.01
MB/s

ncurses-5.9-10 100% |################################| Time: 0:00:00   4.24
MB/s

pandoc-1.19.2- 100% |################################| Time: 0:00:02  13.25
MB/s

sqlite-3.13.0- 100% |################################| Time: 0:00:00  14.13
MB/s

tbb-4.3_201410 100% |################################| Time: 0:00:00  22.13
MB/s

tk-8.5.19-1.ta 100% |################################| Time: 0:00:00  11.20
MB/s

xz-5.2.2-0.tar 100% |################################| Time: 0:00:00  33.22
MB/s

yaml-0.1.6-0.t 100% |################################| Time: 0:00:00  18.32
MB/s

zlib-1.2.11-0. 100% |################################| Time: 0:00:00  21.50
MB/s

hdf5-1.8.17-9. 100% |################################| Time: 0:00:00  24.24
MB/s

libpng-1.6.28- 100% |################################| Time: 0:00:00  40.08
MB/s

libtiff-4.0.6- 100% |################################| Time: 0:00:00  37.37
MB/s

openblas-0.2.1 100% |################################| Time: 0:00:00  27.41
MB/s

openssl-1.0.2h 100% |################################| Time: 0:00:00  30.89
MB/s

qt-5.6.2-0.tar 100% |################################| Time: 0:00:01  41.51
MB/s

readline-6.2-0 100% |################################| Time: 0:00:00   1.02
MB/s

zeromq-4.2.1-1 100% |################################| Time: 0:00:00   2.10
MB/s

blas-1.1-openb 100% |################################| Time: 0:00:00   1.65
MB/s

freetype-2.7-1 100% |################################| Time: 0:00:00   3.21
MB/s

python-3.5.2-5 100% |################################| Time: 0:00:01   7.05
MB/s

appnope-0.1.0- 100% |################################| Time: 0:00:00   8.32
MB/s

certifi-2017.1 100% |################################| Time: 0:00:00  27.58
MB/s

click-6.7-py35 100% |################################| Time: 0:00:00  39.19
MB/s

cloudpickle-0. 100% |################################| Time: 0:00:00  32.62
MB/s

decorator-4.0. 100% |################################| Time: 0:00:00  10.40
MB/s

entrypoints-0. 100% |################################| Time: 0:00:00  12.73
MB/s

greenlet-0.4.1 100% |################################| Time: 0:00:00   7.61
MB/s

idna-2.1-py35_ 100% |################################| Time: 0:00:00  12.25
MB/s

ipython_genuti 100% |################################| Time: 0:00:00  13.26
MB/s

itsdangerous-0 100% |################################| Time: 0:00:00  29.48
MB/s

jsonschema-2.5 100% |################################| Time: 0:00:00  20.88
MB/s

locket-0.2.0-p 100% |################################| Time: 0:00:00   6.39
MB/s

markupsafe-0.2 100% |################################| Time: 0:00:00  10.20
MB/s

mistune-0.7.3- 100% |################################| Time: 0:00:00  21.25
MB/s

numpy-1.12.0-p 100% |################################| Time: 0:00:00  14.45
MB/s

olefile-0.44-p 100% |################################| Time: 0:00:00  26.10
MB/s

pandocfilters- 100% |################################| Time: 0:00:00  14.51
MB/s

pickleshare-0. 100% |################################| Time: 0:00:00  10.53
MB/s

ptyprocess-0.5 100% |################################| Time: 0:00:00  15.21
MB/s

pyasn1-0.1.9-p 100% |################################| Time: 0:00:00   4.83
MB/s

pycparser-2.17 100% |################################| Time: 0:00:00   4.98
MB/s

pyparsing-2.1. 100% |################################| Time: 0:00:00   5.37
MB/s

pytz-2016.10-p 100% |################################| Time: 0:00:00   5.08
MB/s

pyyaml-3.12-py 100% |################################| Time: 0:00:00   6.26
MB/s

pyzmq-16.0.2-p 100% |################################| Time: 0:00:00   5.63
MB/s

requests-2.13. 100% |################################| Time: 0:00:00   6.23
MB/s

simplegeneric- 100% |################################| Time: 0:00:00   3.45
MB/s

sip-4.18-py35_ 100% |################################| Time: 0:00:00   7.32
MB/s

six-1.10.0-py3 100% |################################| Time: 0:00:00   6.96
MB/s

testpath-0.3-p 100% |################################| Time: 0:00:00   7.33
MB/s

toolz-0.8.2-py 100% |################################| Time: 0:00:00   8.81
MB/s

tornado-4.4.2- 100% |################################| Time: 0:00:00   7.88
MB/s

wcwidth-0.1.7- 100% |################################| Time: 0:00:00   9.00
MB/s

werkzeug-0.11. 100% |################################| Time: 0:00:00   9.83
MB/s

cffi-1.7.0-py3 100% |################################| Time: 0:00:00   8.22
MB/s

cycler-0.10.0- 100% |################################| Time: 0:00:00  10.47
MB/s

h5py-2.6.0-np1 100% |################################| Time: 0:00:00   4.49
MB/s

html5lib-0.999 100% |################################| Time: 0:00:00  30.67
MB/s

networkx-1.11- 100% |################################| Time: 0:00:00   5.67
MB/s

opencv3-3.1.0- 100% |################################| Time: 0:00:02  15.88
MB/s

partd-0.3.7-py 100% |################################| Time: 0:00:00  15.48
MB/s

pexpect-4.2.1- 100% |################################| Time: 0:00:00  17.67
MB/s

pillow-4.0.0-p 100% |################################| Time: 0:00:00  46.37
MB/s

pyqt-5.6.0-py3 100% |################################| Time: 0:00:00  39.83
MB/s

python-dateuti 100% |################################| Time: 0:00:00  10.25
MB/s

python-enginei 100% |################################| Time: 0:00:00  26.54
MB/s

scipy-0.18.1-n 100% |################################| Time: 0:00:00  17.45
MB/s

setuptools-33. 100% |################################| Time: 0:00:00  43.56
MB/s

terminado-0.6- 100% |################################| Time: 0:00:00   4.29
MB/s

traitlets-4.3. 100% |################################| Time: 0:00:00  43.07
MB/s

bleach-1.5.0-p 100% |################################| Time: 0:00:00  13.63
MB/s

cryptography-1 100% |################################| Time: 0:00:00  35.62
MB/s

imageio-2.1.2- 100% |################################| Time: 0:00:00   7.51
MB/s

jinja2-2.8-py3 100% |################################| Time: 0:00:00  10.16
MB/s

jupyter_core-4 100% |################################| Time: 0:00:00   9.41
MB/s

matplotlib-2.0 100% |################################| Time: 0:00:00  12.04
MB/s

pandas-0.19.2- 100% |################################| Time: 0:00:00  16.16
MB/s

patsy-0.4.1-py 100% |################################| Time: 0:00:00  14.39
MB/s

pygments-2.2.0 100% |################################| Time: 0:00:00  19.36
MB/s

python-socketi 100% |################################| Time: 0:00:00  22.76
MB/s

scikit-learn-0 100% |################################| Time: 0:00:00  20.58
MB/s

wheel-0.29.0-p 100% |################################| Time: 0:00:00  22.44
MB/s

bokeh-0.12.4-p 100% |################################| Time: 0:00:00  42.07
MB/s

flask-0.11.1-p 100% |################################| Time: 0:00:00  14.35
MB/s

jupyter_client 100% |################################| Time: 0:00:00   2.16
MB/s

nbformat-4.2.0 100% |################################| Time: 0:00:00   7.69
MB/s

pip-9.0.1-py35 100% |################################| Time: 0:00:00   4.57
MB/s

prompt_toolkit 100% |################################| Time: 0:00:00   6.27
MB/s

pyopenssl-16.2 100% |################################| Time: 0:00:00  27.83
MB/s

statsmodels-0. 100% |################################| Time: 0:00:00   9.81
MB/s

dask-0.13.0-py 100% |################################| Time: 0:00:00   4.99
MB/s

eventlet-0.19. 100% |################################| Time: 0:00:00  12.24
MB/s

flask-socketio 100% |################################| Time: 0:00:00  39.66
MB/s

ipython-5.2.2- 100% |################################| Time: 0:00:00   8.29
MB/s

nbconvert-5.1. 100% |################################| Time: 0:00:00   9.83
MB/s

seaborn-0.7.1- 100% |################################| Time: 0:00:00  13.33
MB/s

ipykernel-4.5. 100% |################################| Time: 0:00:00  10.83
MB/s

scikit-image-0 100% |################################| Time: 0:00:01  15.66
MB/s

jupyter_consol 100% |################################| Time: 0:00:00  13.52
MB/s

notebook-4.4.1 100% |################################| Time: 0:00:00  13.50
MB/s

qtconsole-4.2. 100% |################################| Time: 0:00:00   1.77
MB/s

widgetsnbexten 100% |################################| Time: 0:00:00  16.69
MB/s

ipywidgets-5.1 100% |################################| Time: 0:00:00 834.59
kB/s

jupyter-1.0.0- 100% |################################| Time: 0:00:00   3.65
MB/s

Collecting git+https://github.com/fchollet/keras.git

  Cloning https://github.com/fchollet/keras.git to
/private/var/folders/7k/b__p7qnd0zlg1x9brm7t3_880000gp/T/pip-xqe4hol9-build

Collecting moviepy

Collecting tensorflow==0.12.1

  Could not find a version that satisfies the requirement
tensorflow==0.12.1 (from versions: )

No matching distribution found for tensorflow==0.12.1



CondaValueError: Value error: pip returned an error.



C02M50JYFD57:CarND-Term1-Starter-Kit NPadgett$ conda info --envs

# conda environments:

#

carnd-term1              /Users/NPadgett/miniconda3/envs/carnd-term1

root                  *  /Users/NPadgett/miniconda3


C02M50JYFD57:CarND-Term1-Starter-Kit NPadgett$ conda clean -tp

Cache location: /Users/NPadgett/miniconda3/pkgs

Will remove the following tarballs:


/Users/NPadgett/miniconda3/pkgs

-------------------------------

appnope-0.1.0-py35_0.tar.bz2                   6 KB

blas-1.1-openblas.tar.bz2                      1 KB

bleach-1.5.0-py35_0.tar.bz2                  468 KB

bokeh-0.12.4-py35_0.tar.bz2                  4.6 MB

ca-certificates-2017.1.23-0.tar.bz2          166 KB

certifi-2017.1.23-py35_0.tar.bz2             222 KB

cffi-1.7.0-py35_0.tar.bz2                    196 KB

click-6.7-py35_0.tar.bz2                     104 KB

cloudpickle-0.2.2-py35_2.tar.bz2             224 KB

cryptography-1.7.1-py35_0.tar.bz2            479 KB

cycler-0.10.0-py35_0.tar.bz2                  13 KB

dask-0.13.0-py35_0.tar.bz2                   969 KB

decorator-4.0.11-py35_0.tar.bz2               13 KB

entrypoints-0.2.2-py35_1.tar.bz2             451 KB

eventlet-0.19.0-py35_0.tar.bz2               356 KB

flask-0.11.1-py35_0.tar.bz2                  276 KB

flask-socketio-2.7.1-py35_0.tar.bz2          215 KB

freetype-2.7-1.tar.bz2                       771 KB

greenlet-0.4.12-py35_0.tar.bz2                17 KB

h5py-2.6.0-np112py35_7.tar.bz2               877 KB

hdf5-1.8.17-9.tar.bz2                        4.0 MB

html5lib-0.999-py35_0.tar.bz2                175 KB

icu-54.1-0.tar.bz2                          10.9 MB

idna-2.1-py35_0.tar.bz2                      299 KB

imageio-2.1.2-py35_0.tar.bz2                 3.2 MB

ipykernel-4.5.2-py35_0.tar.bz2               1.8 MB

ipython-5.2.2-py35_0.tar.bz2                 1.5 MB

ipython_genutils-0.1.0-py35_0.tar.bz2         34 KB

ipywidgets-5.1.5-py35_0.tar.bz2               61 KB

itsdangerous-0.24-py35_0.tar.bz2             193 KB

jinja2-2.8-py35_1.tar.bz2                    303 KB

jpeg-9b-0.tar.bz2                            243 KB

jsonschema-2.5.1-py35_0.tar.bz2               58 KB

jupyter-1.0.0-py35_0.tar.bz2                   3 KB

jupyter_client-4.4.0-py35_0.tar.bz2          304 KB

jupyter_console-5.1.0-py35_0.tar.bz2         477 KB

jupyter_core-4.2.1-py35_0.tar.bz2            502 KB

libffi-3.2.1-3.tar.bz2                        40 KB

libgfortran-3.0.0-0.tar.bz2                  465 KB

libpng-1.6.28-0.tar.bz2                      319 KB

libsodium-1.0.10-0.tar.bz2                   494 KB

libtiff-4.0.6-7.tar.bz2                      556 KB

locket-0.2.0-py35_1.tar.bz2                    6 KB

markupsafe-0.23-py35_1.tar.bz2               237 KB

matplotlib-2.0.0-np112py35_2.tar.bz2         6.7 MB

mistune-0.7.3-py35_1.tar.bz2                  24 KB

mock-2.0.0-py35_0.tar.bz2                    101 KB

nbconvert-5.1.1-py35_0.tar.bz2               857 KB

nbformat-4.2.0-py35_0.tar.bz2                579 KB

ncurses-5.9-10.tar.bz2                       1.1 MB

networkx-1.11-py35_0.tar.bz2                 1.7 MB

notebook-4.4.1-py35_0.tar.bz2                6.2 MB

numpy-1.12.0-py35_blas_openblas_200.tar.bz2     3.9 MB

olefile-0.44-py35_0.tar.bz2                   51 KB

openblas-0.2.19-1.tar.bz2                   17.2 MB

opencv3-3.1.0-py35_0.tar.bz2                37.9 MB

openssl-1.0.2h-3.tar.bz2                     3.3 MB

pandas-0.19.2-np112py35_1.tar.bz2            8.7 MB

pandoc-1.19.2-0.tar.bz2                     32.2 MB

pandocfilters-1.4.1-py35_0.tar.bz2           451 KB

partd-0.3.7-py35_0.tar.bz2                    31 KB

patsy-0.4.1-py35_0.tar.bz2                   511 KB

pbr-1.10.0-py35_0.tar.bz2                     99 KB

pexpect-4.2.1-py35_0.tar.bz2                  67 KB

pickleshare-0.7.3-py35_0.tar.bz2               9 KB

pillow-4.0.0-py35_2.tar.bz2                  496 KB

pip-9.0.1-py35_0.tar.bz2                     1.8 MB

prompt_toolkit-1.0.13-py35_0.tar.bz2         341 KB

protobuf-3.2.0-py35_0.tar.bz2                6.6 MB

ptyprocess-0.5.1-py35_0.tar.bz2               19 KB

pyasn1-0.1.9-py35_0.tar.bz2                  236 KB

pycparser-2.17-py35_0.tar.bz2                362 KB

pygments-2.2.0-py35_0.tar.bz2                1.3 MB

pyopenssl-16.2.0-py35_0.tar.bz2               72 KB

pyparsing-2.1.10-py35_0.tar.bz2              275 KB

pyqt-5.6.0-py35_2.tar.bz2                    4.5 MB

python-3.5.2-5.tar.bz2                      11.8 MB

python-dateutil-2.6.0-py35_0.tar.bz2         440 KB

python-engineio-1.0.0-py35_0.tar.bz2         218 KB

python-socketio-1.5.1-py35_0.tar.bz2         979 KB

pytz-2016.10-py35_0.tar.bz2                  369 KB

pyyaml-3.12-py35_0.tar.bz2                   156 KB

pyzmq-16.0.2-py35_1.tar.bz2                  399 KB

qt-5.6.2-0.tar.bz2                          66.1 MB

qtconsole-4.2.1-py35_0.tar.bz2               136 KB

readline-6.2-0.tar.bz2                       311 KB

requests-2.13.0-py35_0.tar.bz2               816 KB

scikit-image-0.12.3-np112py35_1.tar.bz2     18.0 MB

scikit-learn-0.18-np112py35_blas_openblas_204.tar.bz2     5.0 MB

scipy-0.18.1-np112py35_blas_openblas_201.tar.bz2    13.0 MB

seaborn-0.7.1-py35_0.tar.bz2                 469 KB

setuptools-33.1.0-py35_0.tar.bz2             506 KB

simplegeneric-0.8.1-py35_0.tar.bz2             7 KB

sip-4.18-py35_1.tar.bz2                      451 KB

six-1.10.0-py35_1.tar.bz2                    219 KB

sqlite-3.13.0-1.tar.bz2                      1.4 MB

statsmodels-0.8.0-np112py35_0.tar.bz2        6.6 MB

tbb-4.3_20141023-0.tar.bz2                   1.6 MB

tensorflow-1.0.0-py35_0.tar.bz2             32.7 MB

terminado-0.6-py35_0.tar.bz2                  18 KB

testpath-0.3-py35_0.tar.bz2                  544 KB

tk-8.5.19-1.tar.bz2                          2.1 MB

toolz-0.8.2-py35_0.tar.bz2                   293 KB

tornado-4.4.2-py35_0.tar.bz2                 778 KB

traitlets-4.3.1-py35_0.tar.bz2               330 KB

wcwidth-0.1.7-py35_0.tar.bz2                  22 KB

werkzeug-0.11.10-py35_0.tar.bz2              585 KB

wheel-0.29.0-py35_0.tar.bz2                   82 KB

widgetsnbextension-1.2.3-py35_1.tar.bz2      1.1 MB

xz-5.2.2-0.tar.bz2                           288 KB

yaml-0.1.6-0.tar.bz2                          82 KB

zeromq-4.2.1-1.tar.bz2                       545 KB

zlib-1.2.11-0.tar.bz2                         95 KB


---------------------------------------------------

Total:                                     342.2 MB


Proceed ([y]/n)? y


Removing appnope-0.1.0-py35_0.tar.bz2

Removing blas-1.1-openblas.tar.bz2

Removing bleach-1.5.0-py35_0.tar.bz2

Removing bokeh-0.12.4-py35_0.tar.bz2

Removing ca-certificates-2017.1.23-0.tar.bz2

Removing certifi-2017.1.23-py35_0.tar.bz2

Removing cffi-1.7.0-py35_0.tar.bz2

Removing click-6.7-py35_0.tar.bz2

Removing cloudpickle-0.2.2-py35_2.tar.bz2

Removing cryptography-1.7.1-py35_0.tar.bz2

Removing cycler-0.10.0-py35_0.tar.bz2

Removing dask-0.13.0-py35_0.tar.bz2

Removing decorator-4.0.11-py35_0.tar.bz2

Removing entrypoints-0.2.2-py35_1.tar.bz2

Removing eventlet-0.19.0-py35_0.tar.bz2

Removing flask-0.11.1-py35_0.tar.bz2

Removing flask-socketio-2.7.1-py35_0.tar.bz2

Removing freetype-2.7-1.tar.bz2

Removing greenlet-0.4.12-py35_0.tar.bz2

Removing h5py-2.6.0-np112py35_7.tar.bz2

Removing hdf5-1.8.17-9.tar.bz2

Removing html5lib-0.999-py35_0.tar.bz2

Removing icu-54.1-0.tar.bz2

Removing idna-2.1-py35_0.tar.bz2

Removing imageio-2.1.2-py35_0.tar.bz2

Removing ipykernel-4.5.2-py35_0.tar.bz2

Removing ipython-5.2.2-py35_0.tar.bz2

Removing ipython_genutils-0.1.0-py35_0.tar.bz2

Removing ipywidgets-5.1.5-py35_0.tar.bz2

Removing itsdangerous-0.24-py35_0.tar.bz2

Removing jinja2-2.8-py35_1.tar.bz2

Removing jpeg-9b-0.tar.bz2

Removing jsonschema-2.5.1-py35_0.tar.bz2

Removing jupyter-1.0.0-py35_0.tar.bz2

Removing jupyter_client-4.4.0-py35_0.tar.bz2

Removing jupyter_console-5.1.0-py35_0.tar.bz2

Removing jupyter_core-4.2.1-py35_0.tar.bz2

Removing libffi-3.2.1-3.tar.bz2

Removing libgfortran-3.0.0-0.tar.bz2

Removing libpng-1.6.28-0.tar.bz2

Removing libsodium-1.0.10-0.tar.bz2

Removing libtiff-4.0.6-7.tar.bz2

Removing locket-0.2.0-py35_1.tar.bz2

Removing markupsafe-0.23-py35_1.tar.bz2

Removing matplotlib-2.0.0-np112py35_2.tar.bz2

Removing mistune-0.7.3-py35_1.tar.bz2

Removing mock-2.0.0-py35_0.tar.bz2

Removing nbconvert-5.1.1-py35_0.tar.bz2

Removing nbformat-4.2.0-py35_0.tar.bz2

Removing ncurses-5.9-10.tar.bz2

Removing networkx-1.11-py35_0.tar.bz2

Removing notebook-4.4.1-py35_0.tar.bz2

Removing numpy-1.12.0-py35_blas_openblas_200.tar.bz2

Removing olefile-0.44-py35_0.tar.bz2

Removing openblas-0.2.19-1.tar.bz2

Removing opencv3-3.1.0-py35_0.tar.bz2

Removing openssl-1.0.2h-3.tar.bz2

Removing pandas-0.19.2-np112py35_1.tar.bz2

Removing pandoc-1.19.2-0.tar.bz2

Removing pandocfilters-1.4.1-py35_0.tar.bz2

Removing partd-0.3.7-py35_0.tar.bz2

Removing patsy-0.4.1-py35_0.tar.bz2

Removing pbr-1.10.0-py35_0.tar.bz2

Removing pexpect-4.2.1-py35_0.tar.bz2

Removing pickleshare-0.7.3-py35_0.tar.bz2

Removing pillow-4.0.0-py35_2.tar.bz2

Removing pip-9.0.1-py35_0.tar.bz2

Removing prompt_toolkit-1.0.13-py35_0.tar.bz2

Removing protobuf-3.2.0-py35_0.tar.bz2

Removing ptyprocess-0.5.1-py35_0.tar.bz2

Removing pyasn1-0.1.9-py35_0.tar.bz2

Removing pycparser-2.17-py35_0.tar.bz2

Removing pygments-2.2.0-py35_0.tar.bz2

Removing pyopenssl-16.2.0-py35_0.tar.bz2

Removing pyparsing-2.1.10-py35_0.tar.bz2

Removing pyqt-5.6.0-py35_2.tar.bz2

Removing python-3.5.2-5.tar.bz2

Removing python-dateutil-2.6.0-py35_0.tar.bz2

Removing python-engineio-1.0.0-py35_0.tar.bz2

Removing python-socketio-1.5.1-py35_0.tar.bz2

Removing pytz-2016.10-py35_0.tar.bz2

Removing pyyaml-3.12-py35_0.tar.bz2

Removing pyzmq-16.0.2-py35_1.tar.bz2

Removing qt-5.6.2-0.tar.bz2

Removing qtconsole-4.2.1-py35_0.tar.bz2

Removing readline-6.2-0.tar.bz2

Removing requests-2.13.0-py35_0.tar.bz2

Removing scikit-image-0.12.3-np112py35_1.tar.bz2

Removing scikit-learn-0.18-np112py35_blas_openblas_204.tar.bz2

Removing scipy-0.18.1-np112py35_blas_openblas_201.tar.bz2

Removing seaborn-0.7.1-py35_0.tar.bz2

Removing setuptools-33.1.0-py35_0.tar.bz2

Removing simplegeneric-0.8.1-py35_0.tar.bz2

Removing sip-4.18-py35_1.tar.bz2

Removing six-1.10.0-py35_1.tar.bz2

Removing sqlite-3.13.0-1.tar.bz2

Removing statsmodels-0.8.0-np112py35_0.tar.bz2

Removing tbb-4.3_20141023-0.tar.bz2

Removing tensorflow-1.0.0-py35_0.tar.bz2

Removing terminado-0.6-py35_0.tar.bz2

Removing testpath-0.3-py35_0.tar.bz2

Removing tk-8.5.19-1.tar.bz2

Removing toolz-0.8.2-py35_0.tar.bz2

Removing tornado-4.4.2-py35_0.tar.bz2

Removing traitlets-4.3.1-py35_0.tar.bz2

Removing wcwidth-0.1.7-py35_0.tar.bz2

Removing werkzeug-0.11.10-py35_0.tar.bz2

Removing wheel-0.29.0-py35_0.tar.bz2

Removing widgetsnbextension-1.2.3-py35_1.tar.bz2

Removing xz-5.2.2-0.tar.bz2

Removing yaml-0.1.6-0.tar.bz2

Removing zeromq-4.2.1-1.tar.bz2

Removing zlib-1.2.11-0.tar.bz2

WARNING: /Users/NPadgett/.conda/pkgs does not exist

Cache location: /Users/NPadgett/miniconda3/pkgs

Will remove the following packages:

/Users/NPadgett/miniconda3/pkgs

-------------------------------


blas-1.1-openblas                              2 KB

ca-certificates-2017.1.23-0                  327 KB

cycler-0.10.0-py35_0                          14 KB

jupyter-1.0.0-py35_0                           6 KB

libgfortran-3.0.0-0                          1.5 MB

mock-2.0.0-py35_0                            523 KB

pbr-1.10.0-py35_0                            442 KB

protobuf-3.2.0-py35_0                       35.4 MB

pyopenssl-16.0.0-py35_0                      1.0 MB

tensorflow-1.0.0-py35_0                    196.4 MB


---------------------------------------------------

Total:                                     235.5 MB


Proceed ([y]/n)? y


removing blas-1.1-openblas

removing ca-certificates-2017.1.23-0

removing cycler-0.10.0-py35_0

removing jupyter-1.0.0-py35_0

removing libgfortran-3.0.0-0

removing mock-2.0.0-py35_0

removing pbr-1.10.0-py35_0

removing protobuf-3.2.0-py35_0

removing pyopenssl-16.0.0-py35_0

removing tensorflow-1.0.0-py35_0

C02M50JYFD57:CarND-Term1-Starter-Kit NPadgett$ source activate carnd-term1

(carnd-term1) C02M50JYFD57:CarND-Term1-Starter-Kit NPadgett$ cd ..

(carnd-term1) C02M50JYFD57:foo NPadgett$ git clone
https://github.com/udacity/CarND-Term1-Starter-Kit-Test.git

Cloning into 'CarND-Term1-Starter-Kit-Test'...

remote: Counting objects: 15, done.

remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15

Unpacking objects: 100% (15/15), done.

Checking connectivity... done.

(carnd-term1) C02M50JYFD57:foo NPadgett$ cd CarND-Term1-Starter-Kit-Test

(carnd-term1) C02M50JYFD57:CarND-Term1-Starter-Kit-Test NPadgett$ source
activate carnd-term1

(carnd-term1) C02M50JYFD57:CarND-Term1-Starter-Kit-Test NPadgett$ jupyter
notebook test.ipynb

[I 01:05:52.353 NotebookApp] Serving notebooks from local directory:
/Users/NPadgett/Documents/projects/cse6242/foo/CarND-Term1-Starter-Kit-Test

[I 01:05:52.353 NotebookApp] 0 active kernels

[I 01:05:52.353 NotebookApp] The Jupyter Notebook is running at:
http://localhost:8888/?token=93f6a9eabab31a37f84898991365f37c6f326579eb1d3b4f

[I 01:05:52.353 NotebookApp] Use Control-C to stop this server and shut
down all kernels (twice to skip confirmation).

[C 01:05:52.354 NotebookApp]



    Copy/paste this URL into your browser when you connect for the first
time,

    to login with a token:


http://localhost:8888/?token=93f6a9eabab31a37f84898991365f37c6f326579eb1d3b4f

[I 01:05:52.654 NotebookApp] Accepting one-time-token-authenticated
connection from ::1

[W 01:05:53.132 NotebookApp] Notebook test.ipynb is not trusted

[I 01:05:53.469 NotebookApp] Kernel started:
cfcf65b5-2e6f-4145-ba77-a560a0a6a8a8

**Comment by domluna** [comment]
I just reran the setup and everything downloaded and I was able to run the test notebook just fine. I had to download ffmpeg but I also did that via `imageio.plugins.ffmpeg.download`. What OS are you running?

**Comment by npadgett** [comment]
OS X Yosemite, Version 10.10.5 (14F1912)

**Comment by domluna** [comment]
@npadgett Sorry this feel through the cracks on my end, is it still an issue? I'm unable to reproduce it on Sierra 10.12.3

**Comment by npadgett** [comment]
feel free to close
