### ISSUE TITLE
Sliding Window Implementation - Solution

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#452]

**Comment by ChrisShepherd81** [comment]
nx_buffer = np.int(xy_window[0]*(xy_overlap[0]))
    ny_buffer = np.int(xy_window[1]*(xy_overlap[1]))
    nx_windows = np.int((xspan-nx_buffer)/nx_pix_per_step) 
    ny_windows = np.int((yspan-nx_buffer)/ny_pix_per_step) 

The last line in the cutting from solution should be:
    ny_windows = np.int((yspan-ny_buffer)/ny_pix_per_step)

**Comment by ChrisShepherd81** [comment]
Same in the lesson_functions.py file within "Search and Classify" in the Vehicle  Detection and Tracking lesson

**Comment by awbrown90** [comment]
@ChrisShepherd81 thanks for catching that
