### ISSUE TITLE
Clarifying CarND-LaneLines-P1 README.md

### ISSUE THREAD

**Issue by czakon** [udacity/sdc-issue-reports#454]
I found the extra installation information confusing.

**Comment by czakon** [comment]
I know that the instructions are written clearly and unambiguously,  but the titles "Step 1, Step 2, etc.." in the "The Project" section sounded like they were part of the project, not the exception for people who didn't have the starter kit installed. 

I think it would have been easier to get students to install the starter kit first and then introduce P1. If you want to keep the alternative installation information, I would suggest splitting this off into a different topic so people don't accidentally read it.

**Comment by czakon** [comment]
Ok, I see that a lot of this is explained in further lessons. I got distracted and started the project a little too soon. Maybe you should point people back to the lessons in Udacity?

**Comment by andrewpaster** [comment]
This is a good point. The README file now directs students to install the carnd starter kit
