### ISSUE TITLE
Spatial Binning of Color doesn't accept a valid quiz answer

### ISSUE THREAD

**Issue by Alexspayne** [udacity/sdc-issue-reports#455]
I wrote code that produced the same result as the solution.
However, it wasn't accepted as a valid answer.

I used this code:

def bin_spatial(img, color_space='RGB', size=(32, 32)):
    # Convert image to new color space (if specified)
    # Use cv2.resize().ravel() to create the feature vector
    
    color = cv2.cvtColor(img, getattr(cv2, "COLOR_BGR2" + color_space))
    color_resized = cv2.resize(color, size)
    features = color_resized.ravel()
    # Return the feature vector
    return features

**Comment by Alexspayne** [comment]
This is in section 15 of  Vehicle Detection and Tracking in Term 1

**Comment by awbrown90** [comment]
@Alexspayne the solution graphically looks the same but the vector produced by your method and the solution method are just slightly different, and np.allclose is catching this in the quiz grader. The main difference is being produced by the line color = cv2.cvtColor(img, getattr(cv2, "COLOR_BGR2" + color_space)), if you take that out then it will pass. I think converting an already RGB to RGB is creating a tiny mismatch and hence the error.
