### ISSUE TITLE
cv2 problem with carnd-term1 starterkit?

### ISSUE THREAD

**Issue by ryan-keenan** [udacity/sdc-issue-reports#456]
Denise James reports the following: ```cv2 is not working with carnd-term1 with the latest miniconda3 nor anaconda, the previous ways of installing cv2 is not working either. ``` she put this on the forum https://carnd-forums.udacity.com/questions/38549050/ubuntu-help-cv2-does-not-work-with-the-carnd-term1-with-the-latest-miniconda3-nor-the-latest-anaconda3

**Comment by domluna** [comment]
I replied in the forums and also added a note in the starter kit docs. It looks like 4.3.13 has problems creating environments.
