### ISSUE TITLE
HOG Tutorial Link

### ISSUE THREAD

**Issue by jwdunn1** [udacity/sdc-issue-reports#457]
In the Vehicle Detection and Tracking module, section 19. scikit-image HOG: The link to "a brief explanation of the algorithm and tutorial" in the first paragraph leads to a 404.

**Comment by jwdunn1** [comment]
Found the correct path: http://scikit-image.org/docs/dev/auto_examples/features_detection/plot_hog.html

**Comment by awbrown90** [comment]
@jwdunn1 just updated it, thanks
