### ISSUE TITLE
MNIST Tutorial data timeout

### ISSUE THREAD

**Issue by swwelch** [udacity/sdc-issue-reports#459]
The following code from the course timed out:
```
from tensorflow.examples.tutorials.mnist import input_data 
mnist = input_data.read_data_sets("MNIST_data/", reshape=False)
```
Although this is not currently happening, it seems like this [has been a problem for others previously](https://github.com/tensorflow/tensorflow/issues/209).

It would be helpful to have a try/except block with useful information (e.g. link to a Udacity-hosted mirror) in case this happens again.

**Comment by josci** [comment]
+ mirror

It is down again.

**Comment by yenif** [comment]
And it's down again

**Comment by swwelch** [comment]
Looks like this was fixed in the latest version of tf: https://github.com/tensorflow/tensorflow/issues/9031
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/mnist.py
