### ISSUE TITLE
Traffic Signs Classifier has [HIDDEN] in the title

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#46]
On the Traffic Signs project 

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/614d4728-0fad-4c9d-a6c3-23227aef8f66/project

It says [HIDDEN] Project Traffic Signs Classifier

**Comment by rm51** [comment]
<img width="1150" alt="screen shot 2016-10-28 at 3 14 18 pm" src="https://cloud.githubusercontent.com/assets/7563076/19819139/4569cf3a-9d21-11e6-97d4-55a231bf008a.png">

**Comment by dalex01** [comment]
See issue #45 in Done column :)
