### ISSUE TITLE
Error in chain rule

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#464]
In the chain rule section of the miniflow backpropagation lesson on this page:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/bd8f6ba2-8231-4cf5-9a94-12a5f77ad6e3

it says
df/dx = (df/dg)(dg/dx).
I believe this should be 
d/dx f(g(x)) = (df/dg) (dg/dx).

The text needs to be adjusted as well, e.g. "In order to know the effect x has on f..." I think you mean "in order to know the effect x has on f(g(x))..."

**Comment by swwelch** [comment]
Thanks for reporting this. It has been updated to be clearer now.

**Comment by troyjlee** [comment]
Thanks for addressing this.  I think the text below the formula still needs to be changed: In order to know the effect x has on f... -> In order to know the effect x has on f circ g...
