### ISSUE TITLE
typo in variable name

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#466]
Just before the quiz here
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/05277d53-b528-4a5b-a2aa-909b4fa3d92d

it says: "Print the cross entropy using softmax_data and one_hot_encod_label."  in the code the variable name is one_hot_data

**Comment by swwelch** [comment]
Thanks for reporting! This is fixed now.
