### ISSUE TITLE
typo in video

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#469]
There is a typo in this video from around minute 1:10.
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/b516a270-8600-4f93-a0a3-20dfeabe5da6/concepts/64370585660923

It says W_2 = W_2 - alpha W_2, the last W_2 is missing a Delta.

**Comment by justineudacity** [comment]
new version is uploaded to coco
