### ISSUE TITLE
changelog.docx is placed inside traffic-sign-data.zip

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#47]
Not sure is it correct or not but there is a changelog.docx file in traffic-sign-data.zip here:
https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/614d4728-0fad-4c9d-a6c3-23227aef8f66/concepts/afbc686c-42ad-4f0a-9e8e-4f8d22defc3e

As for me this file is redundant in archive.

**Comment by domluna** [comment]
I updated the zip file in the resources tab but forgot to change the link. Just says to download the data from the resources tab now.
