### ISSUE TITLE
Quiz: Parameter Sharing

### ISSUE THREAD

**Issue by TheAisBack** [udacity/sdc-issue-reports#471]
In the Quiz about Parameter Sharing the answer is 3880 not 3860. Thanks.
((8 x 8 x 3 + 1) x 20 ) + 20 = 3880 not 3860.

**Comment by troyjlee** [comment]
I think this one is actually correct.  Each filter has 8 x 8 x 3 weights, and one bias parameter.  So in total there are 8 x 8 x 3 + 1 parameters for each filter, and there are 20 filters.

**Comment by TheAisBack** [comment]
Hi, I just looked at this closed issue, it's still not resolved. I don't know where Troyjlee is getting his answer from. but if you look at the Solution: Parameter Sharing. it's clearly 3880. Not 3860. it is wrong. (8 * 8 * 3 + 1) * 20 = 3840 + 20 = 3860 this is what udacity has. Please tell me I'm wrong thanks. It should be (8 * 8 * 3 + 1) * 20 = 3860 + 20 = 3880. Thank you.
