### ISSUE TITLE
tensor flow installation on Mac OS X

### ISSUE THREAD

**Issue by ibrahim-mo** [udacity/sdc-issue-reports#475]
After installing tensorflow as per the 'Intro to TensorFlow' lesson instructions and running the Hello World example, I get these annoying warnings:
(IntroToTensorFlow) MacBook-Pro-6:tf ibrahim$ python tf_test.py 
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
b'Hello World!'

Have anyone encountered this issue. I looked online and found people talking about installing tensorflow from source code. Is this the only option? Or can we suppress these messages?

FYI, I am using Mac OS X 10.12.3.

Thanks,
Ibrahim

**Comment by cameronwp** [comment]
As far as I can tell, there's no way to suppress these warnings. This is TF trying to be helpful by telling you that it could be running faster if you install it from source.

The bad news is that it's really hard to install from source.
The good news is that these warnings don't matter and you can safely ignore them.

Sorry!
