### ISSUE TITLE
Two broken links in Convolutional Neural Networks

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#476]
In Lesson 31. TensorFlow Convolution Layer

the text says 
"Here are a few things worth reviewing:-
TensorFlow Variables.
Truncated Normal Distributions in TensorFlow (you'll want to initialize your weights with a truncated normal distribution)."

When I click on the hyper links I am taken to the Udacity Home page and get a "Not allowed to access this Nanodegree" banner error.

Student reported this in the forum and I get the same.

**Comment by dsilver829** [comment]
Good catch! Fixed. Sorry!
