### ISSUE TITLE
Bad formula for output volume

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#478]
In the convolutional network section, lesson 9, it says "Given our input layer has a volume of W, our filter has a volume (height * width * depth) of F, we have a stride of S, and a padding of P, the following formula gives us the volume of the next layer: (W−F+2P)/S+1."  

This is not the correct formula for the output volume.

**Comment by andrewpaster** [comment]
Hey thanks for flagging this. That formula is for the width of the output layer! I've updated the concept to show what the volume would be.
