### ISSUE TITLE
misuse of hyperplane

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#479]
In the Miniflow section, lesson 11, it says "A network with m parameters would be a hyperplane of m dimensions."  

I think "vector" is more appropriate here.

Later in the section it says "Then it uses the gradient to modify the weights such that the next forward pass through the network moves the output lower in the hyperplane."  The cost function does not in general define a hyperplane, and is not one in the picture given.  I think it would be better to use "surface" here.

**Comment by swwelch** [comment]
Thanks! This has been corrected. For the first part, a network with m parameters should determine a m-dimensional surface (e.g. a network with 2 parameters determines a 2D surface in 3D space where the surface is defined by the cost function).

**Comment by troyjlee** [comment]
The comment here makes sense to me, but I still find the change to the text confusing: "A network with m parameters would be a hypersurface of m dimensions."

From your comment I take it you are referring to the cost function of the network, not the network itself.  Why not say: "the cost function of a network with m parameters is a hypersurface of m dimensions".  

I hope you understand what I mean: I consider the "network" to be independent of the cost function, e.g. we could use the same network with mean squared error or cross entropy, and use the same network on different data sets.
