### ISSUE TITLE
Color selection image type

### ISSUE THREAD

**Issue by sirpsycho85** [udacity/sdc-issue-reports#48]

**Comment by sirpsycho85** [comment]
The image type in the code example in color selection assumes a png. The file given is a jpg, and you need to install the Pillow module to support jpgs.

**Comment by ryan-keenan** [comment]
This is true, and is due to the fact that we are running Python 2 without Pillow for the quizzes and Python 3 for projects.  I've added comments to the code to mention the switch from jpg to png.  Hopefully the quiz environment will be upgraded soon and we can do everything with jpg
