### ISSUE TITLE
C++ Checkpoint: problems not showing errors

### ISSUE THREAD

**Issue by ckirksey3** [udacity/sdc-issue-reports#480]
If I run .cpp code with a syntax error in one of the C++ challenges, I get this Python error instead of the error for my code: Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_asialywbax/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_asialywbax/studentMain.py", line 15, in <module>
    student_out = falcon_output['student_out']
TypeError: string indices must be integers

**Comment by cameronwp** [comment]
are you still seeing this? I believed I've fixed it. if you're still seeing the same error, please paste your code here

**Comment by ckirksey3** [comment]
Nope! Looks great. Thanks 👍
