### ISSUE TITLE
Outdated screenshot about using Mentorship Dashboard

### ISSUE THREAD

**Issue by deniskasyanov** [udacity/sdc-issue-reports#481]
After mentorship dashboard icon was moved, the first screenshot in "Nanodegree Support" sections in Term 1 and Term 2 is no longer relevant.
Links to these pages:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/facdff19-61a5-47e4-8179-a6a5dc28987f/concepts/22ca3e01-0da9-4013-9534-77137083e607
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/8c90e918-2bad-4d4f-8ed4-648de3025c11/lessons/603fab74-4c59-47a3-ab71-5d9c51b3927a/concepts/22ca3e01-0da9-4013-9534-77137083e607

**Comment by jessluls** [comment]
Thanks for flagging! This should be updated now with a better screenshot of the classroom.
