### ISSUE TITLE
T2 - Kalman Filter - Missing and required content

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#484]
1. Quiz: Measurement and Motion refers to content corresponding to the "Localization" class in the AI in Robotics course. That hasn't been covered in this lesson and makes the quiz unhelpful.

2. No Bayes Rule explanation but mentioned in a quiz.

3. No formal definition of "Prior" but mentioned multiple times in some lectures. Same for "Posterior"

**Comment by bartmate** [comment]
+1

**Comment by cameronwp** [comment]
Thanks! This is a known problem. We're already working on a fix on this content. Closing for now.
