### ISSUE TITLE
T2 - Kalman Filter - Covariance and Variance

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#485]
The two words, covariance and variance have been used interchangeably throughout the lesson in several videos.

I though their definitions were distinguishable and not to be interchanged. A clarification would help.

Also, while discussing covariance/variance in some lectures, the "peak" of the Gaussian is discussed instead of the "spread". Does that imply that for a Guassian function a larger spread means a smaller peak, and a smaller spread means a higher peak? If so, then a clarification pointing this out might help?

**Comment by cameronwp** [comment]
looking into it

**Comment by cameronwp** [comment]
Could you give us an example of a situation where the wrong term is used?
