### ISSUE TITLE
T2 L5/8 - Wrong block framed in video

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#486]
In Term 2 Lesson 5 Section 8 - Process Covariance Matrix: the video shows that we are setting up laser matrices, though covariance matrix belong to prediction part.

**Comment by cameronwp** [comment]
what's the timestamp?

**Comment by bartmate** [comment]
0:00-0:10

**Comment by cameronwp** [comment]
Thanks. Looking into it.

**Comment by cameronwp** [comment]
Submitted video change request

**Comment by justineudacity** [comment]
new version is uploaded to coco

**Comment by cameronwp** [comment]
New version is live in the classroom! Thanks again for submitting, @bartmate!
