### ISSUE TITLE
"estimation problem refresh" quiz

### ISSUE THREAD

**Issue by philbort** [udacity/sdc-issue-reports#489]
In Lesson 5 Lidar and Radar Fusion with Kalman Filters in C++ part 4 "estimation problem refresh" quiz, the provided correct answer 

> Predict the state to k+3 then use either one of the sensors to update. Then predict the state to k+3 again and update with the other sensor measurement

is incorrect in my opinion. After first prediction we are already in k+3 and the second prediction doesn't make sense since propagation time is zero. In my opinion the correct answer should be phrased as something like:

> Predict the state to k+3 then update with both sensor measurements sequentially. The order of the sequential measurement update doesn't matter.

**Comment by philbort** [comment]
I understand in the very next lecture it says

> Because we have already run a prediction-update iteration with the first sensor at time k+3, the output of the second prediction at time k+3 will actually be identical to the output from the update step with the first sensor. So, in theory, you could skip the second prediction step and just run a prediction, update, update iteration.

But this is very misunderstanding. We are not skipping the second prediction step. We are separating one measurement update step sequentially to two sensor measurement update. If we have n measurements, doing one measurement update with a n-d measurement vector is equivalent to doing 1-d scalar measurement n times. This is the mathematic equivalence of sequential process and batch process and it should not be mistaken as skipping prediction.

**Comment by cameronwp** [comment]
thanks! I'm checking with Andrei
