### ISSUE TITLE
Comment error in region masking code example

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#49]
On this page:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/8c82408b-a217-4d09-b81d-1bda4c6380ef/concepts/a26d7fdd-291e-46f4-b3eb-01189cbb8afa#

"# Find where image is both colored right and in the region" should say "# Find where image is in the region"

**Comment by ryan-keenan** [comment]
Thanks for catching that!  changed now
