### ISSUE TITLE
T1 L5 Introduction to Neural Networks - Videos Zip File - Some videos missing

### ISSUE THREAD

**Issue by frankkanis** [udacity/sdc-issue-reports#492]
The videos "1. Introduction", "2. Linear Regression Quiz" and "22.Summary"  
are not included in the videos zip file

Logistic Regression Quiz video is maybe an older version in the zip file.

**Comment by jessluls** [comment]
Hi! Can you write in to support@udacity.com? They should be able to point you in the right direction.
