### ISSUE TITLE
Lesson 5 Completion Reset

### ISSUE THREAD

**Issue by SealedSaint** [udacity/sdc-issue-reports#493]
I had previously completed Lesson 5 (in term 1). I just logged on and the progress has been reset to 0%. Even after a refresh, the problem persists.

**Comment by sahiljuneja** [comment]
They have modified the lesson with different content and that's why you see 0%. 

This was recently also announced in the Slack. They unfortunately got delayed with the announcement for this, but you can check that out.

So, not an issue :)
