### ISSUE TITLE
T2 L2.4 Quiz Typo

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#494]
In L2.4 Introduction and Sensors -> Live Data Walkthrough:
> QUIZ QUESTION
> 
> Here are a few properties of lidar and radar sensors. Drag and drop the properties to the sensor that they describe.

-> Should be e.g. 'Drag and drop the sensor labels to match the properties they have.'

**Comment by cameronwp** [comment]
whooops! those instructions describe the quiz as it was written originally, but we swapped what got matched with what in the classroom without updating the instructions. good catch! fixed!
