### ISSUE TITLE
advance lane finding - finding corners exercise open cv error

### ISSUE THREAD

**Issue by neurodrive1** [udacity/sdc-issue-reports#497]
this error happens when nothing is done and I hit test_run

OpenCV Error: One of arguments' values is out of range (Both width and height of the pattern should have bigger than 2) in cvFindChessboardCorners, file /home/vagrant/vm/opencv-3.1.0/modules/calib3d/src/calibinit.cpp, line 268
Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_qsxjkrwmnt/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_qsxjkrwmnt/studentMain.py", line 118, in <module>
    import find_corners
  File "/tmp/vmuser_qsxjkrwmnt/find_corners.py", line 18, in <module>
    ret, corners = cv2.findChessboardCorners(gray, (nx, ny), None)
cv2.error: /home/vagrant/vm/opencv-3.1.0/modules/calib3d/src/calibinit.cpp:268: error: (-211) Both width and height of the pattern should have bigger than 2 in function cvFindChessboardCorners

**Comment by baumanab** [comment]
Sorry for any confusion. This is an expected error since the initial values (0) or values >=2 are not physically possible for this pattern.
