### ISSUE TITLE
Term 2: Subtitles not clear in Kalman Filter lesson

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#498]
<img width="946" alt="screen shot 2017-03-04 at 4 25 19 pm" src="https://cloud.githubusercontent.com/assets/3866405/23578206/5e6d7164-00f7-11e7-9793-d65f3617e797.png">

**Comment by cameronwp** [comment]
Is the issue that the subtitles are white on a white background?

**Comment by cameronwp** [comment]
what browser are you using? looks like Chrome?

**Comment by Deborah-Digges** [comment]
Yes, Chrome on Mac OS Sierra

**Comment by cameronwp** [comment]
This video comes from an older lesson built for an older version of the Udacity site. We're slowly but surely updating our old content to look (and behave) nicely in the new classroom. Really appreciate your feedback! We'll keep this in mind as we continue to improve our older videos.
