### ISSUE TITLE
T2 L5/5 - Sentence doesn't make sense

### ISSUE THREAD

**Issue by Alexspayne** [udacity/sdc-issue-reports#499]
In the second to last paragraph, last sentence:

"It's not required to view or understand this material however in order to complete the assignments."

It seems that it was intended to say:

"It's not required to view or understand this material however *it is required* in order to complete the assignments."

**Comment by cameronwp** [comment]
Ewww. Bad sentence. It's been removed altogether as it's unnecessary.
