### ISSUE TITLE
Link to Linear Regression Review.pdf

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#5]
Link to Linear Regression Review.pdf in supporting materials does not work for me. I see the following response: 
)]}'
{"status": 403, "cause": "perms", "error": "Unauthorized: Not allowed to allow view and/or download of paid-only supplemental media: Key('Node', 438108634)"}

https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/a50b7f46-794e-4a71-97cc-741927965176/concepts/4381086340923

**Comment by swwelch** [comment]
I think this should be fixed now, so I'm going to move this issue to the done category.
