### ISSUE TITLE
P1 hough_lines() helper function creates grayscale image, but should create RBG image

### ISSUE THREAD

**Issue by georgesung** [udacity/sdc-issue-reports#50]
In project 1 (https://github.com/udacity/CarND-LaneLines-P1/blob/master/P1.ipynb), the helper function "hough_lines()" creates a single-channel image via the following line of code:

line_img = np.zeros(img.shape, dtype=np.uint8)

However, when passing line_img into draw_lines(), I assume draw_lines() expects an RGB image, because it's trying to draw a red line. Thus I propose the following code to replace the above line of code:

line_img = np.zeros((*img.shape, 3), dtype=np.uint8)

**Comment by ryan-keenan** [comment]
I agree! nice catch, I've made the change to the notebook. Thanks
