### ISSUE TITLE
T2 L5/12 Video - Measurement Covariance Matrix referred as Process Covariance Matrix

### ISSUE THREAD

**Issue by anupriyachhabra** [udacity/sdc-issue-reports#501]
In L5/ 12 Laser measurements part 4, video explanation time(0:55 - 1:00) Andrew refers to Measurement Covariance Matrix(R) as Process Covariance Matrix

**Comment by cameronwp** [comment]
@justineudacity what do you think? can we grab a clip of Andrei saying the right thing?

**Comment by justineudacity** [comment]
@cameronwp @jessluls can you link to the classroom? I'm looking at L4 13_l Laser measurements but don't see the part mentioned here.

**Comment by jessluls** [comment]
@justineudacity https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/3612b91d-9c33-47ad-8067-a572a6c93837/concepts/252f0093-48ac-4122-aaae-f10214d30320

**Comment by justineudacity** [comment]
@cameronwp @jessluls this needs a re-record.

**Comment by justineudacity** [comment]
Good news! Managed to fix it with previous audio. It has been uploaded to coco
https://coco.udacity.com/media/upload/files/54072
