### ISSUE TITLE
T2 Kalman Filter Derivation

### ISSUE THREAD

**Issue by ksakmann** [udacity/sdc-issue-reports#502]
Would it be possible to add a mathematically sound derivation of the Kalman filter, even in its simplest form with zero mean uncorrelated noise terms? I think many would appreciate a common reference for this course.

**Comment by cameronwp** [comment]
Looking into this!

**Comment by cameronwp** [comment]
We're considering revamping some aspects of the KF lessons. I'm closing this for now but I want you to know that your feedback has been noted.
