### ISSUE TITLE
UKF - 20./21. abs vs fabs

### ISSUE THREAD

**Issue by HTuennermann** [udacity/sdc-issue-reports#505]
the results in sigma point predictions are wrong because of a subtle abs vs fabs bug.

It can be fixed either by adding 
using namespace std; 
(which enables overloads the abs function) or by changing 
//avoid division by zero
    if (abs(yawd) > 0.001) { 

to 
//avoid division by zero    
 if (fabs(yawd) > 0.001) {   …

Also, this changes the resulting values for the sample solution and therefore should be fixed as soon as possible.

**Comment by cameronwp** [comment]
@awbrown90 you mind looking into this?

**Comment by awbrown90** [comment]
@HTuennermann thanks for that subtle catch
