### ISSUE TITLE
T1 L5/16 Typo in word "Fill"

### ISSUE THREAD

**Issue by Alexspayne** [udacity/sdc-issue-reports#506]
In the task list description, the 'i' in the word "Fill" is capitalized where it should be lowercase.

**Comment by swwelch** [comment]
@Alexspayne I'm having trouble tracking this down. Do you have a link?

**Comment by Alexspayne** [comment]
I can't find it either.  The lesson numbers must have changed or this was already fixed.

**Comment by Alexspayne** [comment]
Maybe you could do a grep search for "FIll" for all the files in the source or something.

**Comment by swwelch** [comment]
Unfortunately, I'm not able to search all source files at once. I think this might already have been fixed, so I'm closing for now, but if you run across it again, I'd happily change it!
