### ISSUE TITLE
T2.L03.t08 Measurement and Motion

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#507]
This quiz seems to depend on familiarity with content that is not in the SDC lessons.  If that is true, it would be nice to have a notice (preferably above the video instead of below) for SDC students saying "if you haven't taken the class referred to in the quiz, take your best guess or just skip to the answer."

**Comment by cameronwp** [comment]
Right. This is part of a more systemic problem of the flow of the AI4R lesson in the middle of SDC. We're working on rearranging and re-editing material to smooth this out.

**Comment by cameronwp** [comment]
tagging @awbrown90 as he's working on improving this lesson

**Comment by awbrown90** [comment]
Yeah decided it would be best just to create a new concept for this one and try to summarize what the last lessons went over briefly to cover it.
