### ISSUE TITLE
GENERAL: convention for specifying feedback topic

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#508]
This may exist and I just am not aware of it but it would be really helpful to have a standard convention for referencing the Term/Lesson/Topic that we are providing feedback on.  Maybe some sort of readme or content that is emailed when you submit an issue?

**Comment by jessluls** [comment]
It's most helpful to just provide us a direct link to what you're referencing. But if you're looking for a title convention, most people (if you look through the board) use T# L# # (Term, Lesson, Concept) format.
