### ISSUE TITLE
Solution does not work

### ISSUE THREAD

**Issue by adai183** [udacity/sdc-issue-reports#509]
Lesson "The Simplest Neural Network" - [link](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/83a4e710-a69e-4ce9-9af9-939307c0711b/concepts/8477d2a8-951d-4c93-abe3-650440fd9442#).

**Comment by awbrown90** [comment]
@adai183 seems correct, what wrong with it?
