### ISSUE TITLE
Traffic Signs Project Notebook fails to load with "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by MatthewZhou** [udacity/sdc-issue-reports#51]

**Comment by domluna** [comment]
What part of the code produces the error?

**Comment by MatthewZhou** [comment]
![image](https://cloud.githubusercontent.com/assets/14878419/19831188/e4034d64-9dd1-11e6-85aa-73dd97d7a5b9.png)
This is the error that comes up as soon as I open the notebook -- I've been able to open up the SDC P1 project without any issues.

**Comment by domluna** [comment]
Should be fixed now, pull the latest commit.

**Comment by MatthewZhou** [comment]
Yes the error is gone. Thank you!
