### ISSUE TITLE
T1-L5-Ch10: Truth table for OR gate is wrong. It's XOR instead

### ISSUE THREAD

**Issue by mohankarthik** [udacity/sdc-issue-reports#510]
In the image in Term 1, Lesson 5 (Intro to Neural Networks), Tab 10 (OR & NOT Perceptron Quiz), the image shows a truth table for OR gate, but it's instead actually for XOR.

**Comment by baumanab** [comment]
Thanks for reporting this.  The figure is now consistent with the depiction of AND & OR truth tables.
