### ISSUE TITLE
Jupyter notebook uses outdated Tensorflow API

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#512]
Two source files for student practice use an API of Tensorflow that has been changed since rel. 1.0 of Tensorflow, therefore the source files generate an error.

Source files are: 

https://github.com/udacity/CarND-LeNet-Lab/blob/master/LeNet-Lab.ipynb

https://github.com/udacity/CarND-LeNet-Lab/blob/master/LeNet-Lab-Solution.ipynb 

Error is:
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

To fix the error, need to replace the line:

cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits, one_hot_y)

with the line:
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=one_hot_y)

**Comment by mvirgo** [comment]
Aaron fixed this in March '17 with commit `f24919e068691502b79e27eb47e87e8c8376c788` - thanks for pointing this out!
