### ISSUE TITLE
T2 - L5/8. Process Covariance Matrix

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#515]
At the end of the lecture, they say - "See below for more information". But the context of that statement (regarding Q matrix and confusion around that) and the content below the video are not related. 

Also, in the video, the term "Expectation Value" is used multiple times. But there's no clear explanation of what that is, and how it's significant to the derivation. The entire derivation infact doesn't focus on developing an intuition around Process Covariance Matrix, it just mostly walks through the math.

**Comment by cameronwp** [comment]
Hmmm, looking back through the script, I can't find what we were going top to give as extra info. Pinging Andrei to find a resource.

Re: math: yes. I'll pass the feedback along and see if we can get something written up about covariance.

**Comment by cameronwp** [comment]
Finally fixed the text here.
