### ISSUE TITLE
Advanced Lane Finding Code Clarificatioin

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#517]
Hello, 
 
On the quiz code in slide 30.Color and Gradient
A student has suggested this through the forum:

Small typos in the example code. They have:

hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HLS).astype(np.float)
l_channel = hsv[:,:,1]
s_channel = hsv[:,:,2]

But they are using HLS, so jit would be more clear if they replace hsv with 'hls`

**Comment by swwelch** [comment]
Hi! It looks like there is a conversion to hsv right before the two channel variables are created, but let me know if I'm missing something!
