### ISSUE TITLE
T2 - P2 - Missing file from the repo

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#518]
Hi,
the file ground_truth_package.h is missing from the repo, though it is included in UKF.h.
BartMate

**Comment by andrewpaster** [comment]
Hi, thanks for bringing this up. The include statement for ground truth was removed in the last repository update. 

I've made a pull request that adds ground truth back in along with some extra helper functions that were in the EKF project. The team is discussing whether or not to accept the pull request or to keep the project as is where students need to figure out how to get ground truth into the project.
