### ISSUE TITLE
Term 2 - resuming where I left off

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#519]
In term 1, when i would launch the udacity site, it would automatically take me to where i left off.  now that term 2 has started, that behavior doesn't seem to be happening anymore and i have to manually select "term 2" on the left and then scroll down to whichever lesson i was looking at last.  is there anything i can do on my end to make this work again?

**Comment by jessluls** [comment]
thanks for reporting. can you go to udacity.com/contact to report the bug? remember to include your system information in your report! this is a classroom issue, not a CarND issue.
