### ISSUE TITLE
Behavioral Cloning: Even More Powerful Network doesn't work

### ISSUE THREAD

**Issue by HenryDev** [udacity/sdc-issue-reports#521]
I have been following the model building through all previous videos, and I've been adding the different sections onto my model, but the model in this video raises error:
`Negative dimension size caused by subtracting 3 from 2 for 'Conv2D_4' (op: 'Conv2D') with input shapes: [?,2,18,64], [3,3,64,64].`
If I change the stride for the last layer from 64,3,3 to 64,2,2 then it gives another error:
`ValueError: Error when checking model input: expected lambda_input_1 to have 4 dimensions, but got array with shape (48216, 1)`
There could be changes in how the data is being loaded but that is not being shown in the video.

**Comment by baumanab** [comment]
Thank you for reporting this. It looks like this is an issue with the implementation rather than the grader. You have probably sorted this out by now but please reach out to mentors for help if it isn’t clear.
