### ISSUE TITLE
T1 L20/33 - Not sufficient an explanation

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#522]
For the lesson "Hog Sub-sampling Window Search" the explanation for the code isn't too helpful. Actually, there isn't any explanation.

It might be helpful if the conceptual part of it could be explained better because I have had some mentees face confusion over that piece of code. 

For example, what exactly does "scale" do visually and how does it actually compare with setting window sizes in the prior approach (based on Ryan's project video).

The current text above the code states - 
```Each window is defined by a scaling factor where a scale of 1 would result in a window that's 8 x 8 cells then the overlap of each window is in terms of the cell distance. This means that a cells_per_step = 2 would result in a search window overlap of 75%```

But how is it 75%? How does a scale of 1 result in 8x8 cells? 

I think providing a better explanation will help students not rely on code (I noticed some students use the code directly without understanding it) and be able to write their own code and experiment better.

Thank you.

**Comment by SiddharthSingi** [comment]
I had the same confusion over that lesson, can someone please send a better explanation for the "Hog Sub-Sampling Window Search"

**Comment by baumanab** [comment]
Thank you for the feedback.  I also had some challenges understanding this at first.  I have added some information to address most of the concerns above.  Hopefully, it will be helpful.  The code is being revised as part of #1307.  Any changes that impact the text explanation will be reconciled as part of this process.
