### ISSUE TITLE
T2.L05.S6 - quiz question about "process noise" -- should the student know what this is?

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#523]
in the topic "Kalman Filter Equations in C++ Part 2" the video asks why there is no "process noise in the state prediction line here".  As a student going through this section, the phrase "process noise" hasn't been covered in the material (or at least it didn't sink in for me).  the question and quiz don't seem to be supported by the preceding material.

**Comment by sstormm** [comment]
additional comment--up to this point, the message i have recieved about the Kalman filter math details is "don't worry to much about the details with the math and the gory details--just learn the concepts and trust the code that is provided" which i am more than happy to do.  if you answer the quiz question right, though, the answer is really mathy--should the learner be able to recognize Q*N(0,Q) on sight at this point?

**Comment by sstormm** [comment]
followup to my additional comment--re-watching the video from "kalman filter equations in c++ part 1", the instructor mentions "nu noise and omega noise" in the context of the stochastic part of the model.  this mention in passing doesn't cover "process noise" or "measurement noise".

**Comment by andrewpaster** [comment]
Hey, thanks for bringing this up. I added some more info about process noise and measurement noise that hopefully clears some of this up.
