### ISSUE TITLE
T2.L05.S10 - Laser Measurements Part 2 - improve writing

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#526]
"So we have to find out what is our H matrix so that by multiplying it with the state vector we obtain the measurement which is x and y."  maybe change this to "In order to obtain our measurement (x and y) we need to determine the H matrix".  i had to read the original sentence many times to try to understand what it was trying to say.

**Comment by sstormm** [comment]
actually, this entire section should be reviewed to see if it can be clearer.  the paragraph referencing matrices and their sizes would be much easier to understand if equations were used instead of phrases like "m by n H matrix".

**Comment by sstormm** [comment]
...and the quiz...about the dimensionality of the noise covariance matrix, R.  What is the expectation for how the student would know the answer to this question?  By looking the PDF of equations that was provided?  R is not shown or referenced on this page at all.

**Comment by awbrown90** [comment]
@sstormm thanks added a little more detail on that concept.

**Comment by sstormm** [comment]
what about the question about how a student is supposed to know the dimensionality of the noise covariance matrix, R?  are these issue reports restricted to typographical fixes?
