### ISSUE TITLE
T2.L07.S23 - Formatting in formula for covariance matrix

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#527]
Indices are not formatted correctly:
https://www.dropbox.com/s/4px1ntjh5sc9nv8/Bildschirmfoto%202017-03-09%20um%2010.12.25.png?dl=0

**Comment by swwelch** [comment]
Hi! It looks like this has been fixed now, but if you still see it, please send me a link, and I'll correct it.
