### ISSUE TITLE
T2.L07.S23/24 Mistake in formula for weights

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#528]
Formulas for the weights, as given in S23:
https://www.dropbox.com/s/qexpx9couli5ttl/Bildschirmfoto%202017-03-09%20um%2010.55.19.png?dl=0

Here n_sigma = 2*n_aug + 1. 

But in the programming exercise n_aug is used to calculate the weights:

w(0) = lambda / (lambda + n_aug);

**Comment by awbrown90** [comment]
@WolfgangSteiner this formula looks correct. Remember first element here is 1 not 0 but in the quiz the first element is 0.

**Comment by WolfgangSteiner** [comment]
Please double check this formula:
n_sigma is defined as 2 * n_aug + 1.
n_aug = 7
n_sigma = 2*n_aug + 1 = 15

In the solution for the exercise:
w(0) = lambda / (lambda + n_aug)
w(i) = 0.5/(n_aug+lambda)

and not w(0) = lambda / (lambda + 2*n_aug + 1).
and w(i) = lambda / (lambda + 2*n_aug + 1)

**Comment by awbrown90** [comment]
I see what you mean now, it should be n_a instead of n_sigma, thanks for catching that. Will also need to make a note to get the equation in the video fixed.


________________________________

**Comment by awbrown90** [comment]
@cameron looks like in Unscented Kalman Filters video concept 22 has a typo in the weight equation where n_sigma should actually be n_a. Just corrected the classroom equation in concept 23.

**Comment by cameronwp** [comment]
I've checked in with Dominik about this. @justineudacity, looks like we might need a video edit if you guys have any bandwidth.

**Comment by cameronwp** [comment]
@awbrown90 I'm going to need your help identifying what needs to change in the video.

**Comment by awbrown90** [comment]
@cameronwp this is actually a duplicate task with #589 so going to close this one
