### ISSUE TITLE
Quiz: TensorFlow Linear Function - Wrong Data Dimensions

### ISSUE THREAD

**Issue by pkern90** [udacity/sdc-issue-reports#53]
In the second part of the quiz "TensorFlow Linear Function" in the "Introduction to Tensorflow" lesson seems to be an error regarding die input data. The shape differs between the quiz and the solution tab. Assertion seems to expect a 2x2 matrix but the given data results in a 3x3 matrix.

**Comment by Brok-Bucholtz** [comment]
@pkern90 

Thanks for letting us know.  I changed the quiz to use the solution's matrices.  Let us know if we can help with anything else.
