### ISSUE TITLE
T2.L07.S26 Reformat the expected results.

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#532]
The expected results should be formatted as a 3x1 and 3x3 matrix so that it is easier for the student to compare the solutions.

**Comment by awbrown90** [comment]
@WolfgangSteiner which module lesson and concept was this for?

**Comment by WolfgangSteiner** [comment]
Term 2 Lesson 7 Section 26 (T2.L07.S26)

**Comment by WolfgangSteiner** [comment]
But it also applies to all of the exercises. Example from S26:

<img width="1012" alt="bildschirmfoto 2017-03-09 um 20 47 19" src="https://cloud.githubusercontent.com/assets/1871474/23767683/c3c9f0bc-0509-11e7-9c4d-96757b0684c4.png">
