### ISSUE TITLE
EKF - Add namespace to .cpp files

### ISSUE THREAD

**Issue by jimwinquist** [udacity/sdc-issue-reports#533]

**Comment by jimwinquist** [comment]
After removing namespaces from header files in 
commit 3641e338a163a1405c8a8fef1d1dffd1e6c35798
.cpp files are broken, and should either include the namespaces or have the fully qualified class names for Eigen::VectorXd and Eigen::MatrixXd

**Comment by jimwinquist** [comment]
Also using std namespace should be added to tools.cpp

**Comment by jimwinquist** [comment]
Seems like FusionEKF.h should also include the Eigen/Dense library

**Comment by awbrown90** [comment]
@jimwinquist all current dependencies seem ok is there any specific problems running?

**Comment by jimwinquist** [comment]
@awbrown90 I am getting errors when trying to compile kalman_filter.cpp, tools.cpp, and FusionEKF.cpp after the recent update. The main error I'm getting is that there are undefined identifiers present for VectorXd and MatrixXd and I think it is because it isn't using the Eigen namespace in the header files anymore. My assumption is that  the namespace needs to be added to the .cpp files or it needs to fully qualify the class names. i.e. Eigen::VectorXd, Eigen::MatrixXd. I am fairly new to C++ so I may be missing something about C++ resolution order, but it seems like if the namespace is removed from the header files it needs to be added to the .cpp files or all of the class names need to be full paths.

As an example, since the Eigen namespace has been removed from kalman_filter.h I would expect that kalman_filter.cpp would need to define the namespace:
`using Eigen::VectorXd;`
`using Eigen::MatrixXd;`

or lines 7 and 8 would need to be changed to
`void KalmanFilter::Init(Eigen::VectorXd &x_in, Eigen::MatrixXd &P_in, Eigen::MatrixXd &F_in,
	Eigen::MatrixXd &H_in, Eigen::MatrixXd &R_in, Eigen::MatrixXd &Q_in) {`
instead of the current version
`void KalmanFilter::Init(VectorXd &x_in, MatrixXd &P_in, MatrixXd &F_in,
	MatrixXd &H_in, MatrixXd &R_in, MatrixXd &Q_in) {`

I may be totally missing something though, so sorry in advance if that's the case. Thanks for taking a look.

**Comment by baumanab** [comment]
Thanks for helping us troubleshoot.  It looks like this has been corrected (namespaces are currently present).
