### ISSUE TITLE
T2 L6/10 - "R" Quiz introduced before defining R

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#536]
Not sure what the intention was here, so could be wrong. 

But we go trying to find out what H would be along with the dimensions, and then to a Quiz on dimensions of R, the covariance matrix. 

There wasn't any information before that on what R actually is. It's introduced in the next lesson. I know it can be extrapolated from the Process Covariance Matrix lecture, but it would help to have them in order perhaps.

**Comment by andrewpaster** [comment]
I see your point. I think the intention was to get people to try to think about the answer since the answer is at the top of the next page. I changed some of the wording to segue better between the different topics.
