### ISSUE TITLE
T2.P2 data format

### ISSUE THREAD

**Issue by fscbr** [udacity/sdc-issue-reports#538]
input and data output data format contains 
px, py, vx, vy estimation and ground truth columns, but should be something like  px,py,v,yaw,dyaw.

**Comment by andrewpaster** [comment]
The input data for the unscented kalman filter project and scented kalman filter is the same. I believe the last four columns from the input file represent ground truth data px, py, vx and vy. In the current version of unscented kalman filter main.cpp, the output file will contain px, py,v, yaw, dyaw estimates as well as sensor data. We're discussing adding additional code that will output ground truth like in project one but it will just be the ground truth as given in the input files: px, py, vx, vy. Let me know if I've addressed your concerns.

**Comment by fscbr** [comment]
yes, in the output file the estimates should be  px,py,v, yaw, dyaw. The ground truth could be as in project one, but for me it would make more sense to have  px,py,v, yaw, dyaw as well to avoid additional conversion for quality checks or  RMSE calculation.

**Comment by andrewpaster** [comment]
ah ok. We'll definitely keep this feedback in mind as we revise the project in the future.
