### ISSUE TITLE
Email in Before we begin video is different than below

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#54]
In Lesson 1 
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/facdff19-61a5-47e4-8179-a6a5dc28987f/concepts/879b439d-1acd-48fe-9207-3c554f735df8

David says the email is support@udacity.com But below it says it is selfdrivingcar-support@udacity.com Which one is better?

**Comment by dhruvbaldawa** [comment]
hey @Brok-Bucholtz, you probably wanna assign these tickets to @dhruvp instead :)

**Comment by Brok-Bucholtz** [comment]
@dhruvbaldawa 

Yea, wrong Dhruv.  Thanks for reassigning the issues.

**Comment by Brok-Bucholtz** [comment]
@rm51 

Thanks for letting us know.  I've added this to the product backlog.
