### ISSUE TITLE
Typo in Unscented Kalman Filter Weight Equation

### ISSUE THREAD

**Issue by awbrown90** [udacity/sdc-issue-reports#540]

**Comment by awbrown90** [comment]
The weight equation in T2:L7:22 video should be n_a instead of n_sigma. Just corrected the classroom weight equation in 23 to fix this but noticed the video had this typo as well. @cameron would you mind taking a look.

**Comment by cameronwp** [comment]
Just asked Dominik to double check.

**Comment by cameronwp** [comment]
I've added a note below the video. Calling this done for now because I don't think Justine will have time to reedit this any time soon.
