### ISSUE TITLE
T1 L20.9 Unnecessary lines

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#542]
In the template_match.py file that we need to complete, there are a couple of extraneous lines in the find_matches() function:

def find_matches(img, template_list):
    # Make a copy of the image to draw on
    draw_img = np.copy(img)
    # Define an empty list to take bbox coords
    bbox_list = []
    ...

There is no need to make a copy of the image to draw on since no drawing happens in that function. The first two lines can be removed like so:

def find_matches(img, template_list):
    # Define an empty list to take bbox coords
    bbox_list = []
    ...

**Comment by baumanab** [comment]
Thank you for letting us know about this.  I was not able to locate T1 L20.9  It looks like there are currently only 19 lessons in T1.  The number has probably changed since this was posted.  Would you mind linking to the content?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
