### ISSUE TITLE
Sliding Window Search example code has error

### ISSUE THREAD

**Issue by boulderZ** [udacity/sdc-issue-reports#543]
I tried running the example code on a thresholded image and it plotted the windows but did not show the original thresholded image. It was all black because the line: warpage = np.array(cv2.merge((warped,warped,warped)),np.uint8) # making the original road pixels 3 color channels does not seem to do what they say. If I use: warpage=np.dstack((warped, warped, warped))*255 it works as expected. Not sure how they get the demo code to run in the lecture. I think this should be corrected. Perhaps an older version of cv2 worked when they made the demo example.

**Comment by boulderZ** [comment]
There is even a bigger problem with this code. It has `image` in the function def , but inside the code it uses `warped` and never uses `image`

**Comment by boulderZ** [comment]
One other issue I just found that should be fixed as well. The values for xm_per_pix and ym_per_pix are not correct for the example image size being used. The code has ym_per_pix = 30/720.  It should be half of that. The xm_per_pix shows 3.7/700 and it should be twice that. So correct values are ym_per_pix = 3/144 and xm_per_pix = 3.7/350 for an image of size (720,1280). It might be better to show  how to calculate the values rather than giving hard conversion factors in the code.

**Comment by boulderZ** [comment]
My last comment should be a separate issue. I will post separately, sorry. The example code that is in error is in a different lecture and file. Please look for 'xm_per_pix' in a new issue.

**Comment by asimay** [comment]
yes. I mentioned this in slack. *255 is critical.

**Comment by baumanab** [comment]
Great comments.  All items have been addressed.
