### ISSUE TITLE
Jacobian for F

### ISSUE THREAD

**Issue by bdholt1** [udacity/sdc-issue-reports#545]
In https://discussions.udacity.com/t/why-do-we-need-to-compute-jacobian-for-f/227492/6 we discuss lesson 5, ch 18 where Andrei says that we need to use the Jacobian for F.  There is some confusion about that, because the EKF generally handles a linear motion model and where necessary, a Jacobian is used to linearise H (e.g. for handling radar measurements).  The way this is worded should change to make clear that *if* you had a non-linear motion model, you *should* linearise it by using the Jacobian as you *need* to do for H for radar.  As it stands, there is no need to linearise F for the project because the motion model is already linear.

**Comment by andrewpaster** [comment]
That's a good point. The video isn't clear that he's giving general equations for extended kalman filters but for the model used in this project, only radar sensors have non-linear equations.

 This part of the lecture was updated with some extra info. Let me know if something is still unclear in the "EKF Algorithm Generalization" lecture.
