### ISSUE TITLE
Lesson 8: "Convolutional Neural Networks", L16: "Visualizing CNNs": minor text edit

### ISSUE THREAD

**Issue by SherylHohman** [udacity/sdc-issue-reports#546]
Lesson 8: "Convolutional Neural Networks", L16: "Visualizing CNNs"
Minor text edit: re-order text to reflect logical progression of concept presented, and improve reading flow.

**move**: 
`We'll skip layer 4, which continues this progression, and jump right to the fifth and final layer of this CNN.`
from Layer 5 section (sandwiched between two sentences talking about layer 5)

**to just after**:
` The third layer picks out complex combinations of features from the second layer. These include things like grids, and honeycombs (top left), wheels (second row, second column), and even faces (third row, third column).`

Where it is now is out of order, and does not flow well.

Moving it keeps Layer 3, Layer 4, and Layer 5 in order. 
The layer 4 sentence references what was just don in Layer 3 (a continuation of layer 3..),
and acts as a transitional sentence leading into the nest section, Layer 5.

It just flows better, and makes more sense. 
No back-and-forth mental shifts between which layer we are talking about.
No contextual shift to what sentence the one in question is referring to / referencing. 
(OK. I just realized that part of the contextual switching is a result of the text under the image reads as though it is part of the text, rather than part of the image. Either way, the image separates two sentences that are connected. Instead the image should follow the transition sentence, and the back reference to Layer 4 should not be After the transition to Layer 5 (via Layer 5 title, Layer 5 image and Layer 5 image-description).
Pro-actively prevents our internal dialog to ask if we just skipped Layer 4. (yes we did, here's why)

Result:
```
 The third layer picks out complex combinations of features from the second layer. These include things like grids, and honeycombs (top left), wheels (second row, second column), and even faces (third row, third column).

We'll skip layer 4, which continues this progression, and jump right to the fifth and final layer of this CNN.

Layer 5

(image)

A visualization of the 5th Layer...

The last layer picks out the highest order ideas that ..

```

**Comment by baumanab** [comment]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/601ae704-1035-4287-8b11-e2c2716217ad/concepts/05f91f07-6de6-4b6b-b989-6112802e09a4#

**Comment by baumanab** [comment]
This does flow much better, thanks for the suggestion.  The content has been updated.
