### ISSUE TITLE
T2 EKF L13 Radar Measurements

### ISSUE THREAD

**Issue by ksakmann** [udacity/sdc-issue-reports#548]
All calculations are done in the common  righthanded coordinate system, both in the lectures and quizzes and as far as I can tell also in the project. phi goes in the mathematically negative sense and one would have

px =  rho cos(phi)
py = -rho sin(phi)
 
based on the figure as opposed to the usual 

px = rho cos(phi)
py = rho sin(phi)

The figure is misleading here.

**Comment by cameronwp** [comment]
Looking into this

**Comment by cameronwp** [comment]
Thanks for bringing this up. Let me sync with the team to see if there is an easy way to fix the video.

**Comment by awbrown90** [comment]
Hi @ksakmann, I agree that the video is a little confusing showing the angle arrow pointing in the negative direction but I think this notation is just showing that x-axis is the reference as usual, so the angle in the video would be NEGATIVE. Nothing in the video indicates that angle notation is actually reversed and the car coordinate system should still be a right handed system. Maybe I can add a note about how  conventions are handled through out the material to help with confusion.
