### ISSUE TITLE
T2 UKF - Wrong output description

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#550]
In the T2 UKF repo, the main.cpp generates the output which is not same format, which is written either in 
Docs/Data_Flow_Doc.txt or 
Docs/Input_Output File Format.txt.

**Comment by cameronwp** [comment]
Oooh good point. I actually think those docs are specific to EKF but let me check.

**Comment by cameronwp** [comment]
Yep, wrong project. They've been removed.
