### ISSUE TITLE
Lesson 8: "Convolutional Neural Networks" L31: "Tensor Flow Convolution Layer": unclear reference

### ISSUE THREAD

**Issue by SherylHohman** [udacity/sdc-issue-reports#551]
In Convolutional Neural Networks Lesson, L31: "Tensor Flow Convolution Layer" Concept:  
unclear what material is being referenced below: 
```
Here are a few more things worth reviewing:  

1. Introduction to TensorFlow -> TensorFlow Variables.
```

I do not find a Concept titled "TensorFlow Variables" in the  "Introduction to TensorFlow" Lesson. 
Nor in any of several other Lessons.   I'm actually not sure what idea you suggest we refresh our memories about.
Also, it would be wonderful if the reference could be turned into an active Link :-)

**Comment by baumanab** [comment]
Thanks for letting us know about this, a link has been added.
