### ISSUE TITLE
Beta Simulator doesn't connect on Windows when using Docker

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [udacity/sdc-issue-reports#552]
when executing the docker command to runs drive.py with model.h5 the simulator doesn't connect

but when I used Anaconda it connects properly

I have been stuck on this for 3 weeks before I realized it wasn't my mistake, so please inform other students so they don't feel frustrated

**Comment by baumanab** [comment]
Closed as issues addressed in the current (non-beta) simulator releases.
