### ISSUE TITLE
EKF Project Typo

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#557]
From a student: "Those are outputs of measurements, not estimations, right? Just want to make sure I understand what each class is used for, thanks in advance!"

https://drive.google.com/file/d/0B0Hd8k-wUrTsb2hNZ0FsYWY0X00/view?usp=sharing

**Comment by andrewpaster** [comment]
That code outputs lidar and radar measurements, so the "output the measurements" seems like an appropriate comment. 

A few code lines above the estimations get outputted and the comments say "output the estimations".  

I don't think there's a typo.
