### ISSUE TITLE
links in nd013 Measurement and Motion lesson is 404'ing

### ISSUE THREAD

**Issue by ranakhalil** [udacity/sdc-issue-reports#560]

**Comment by ranakhalil** [comment]
here is the link https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/b3ebef23-64b7-4821-8809-05705165f829/concepts/08c5d7f0-cc4a-4ceb-9ee8-6424d19e0d25

**Comment by cameronwp** [comment]
Thanks for the heads up. Looks like those links were directed to the wrong version of the lesson. I've updated them. Let me know if you're still unable to access them.
