### ISSUE TITLE
Link to Wrong Docker Image

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#562]
in term1, lesson about tensor flow, topic  "Lab: TensorFlow Neural Network" docker is suggested only for windows. And even here wrong docker image is mentioned. It's said that you should use docker image udacity/carnd-tensorflow-lab but this image contains TF 0.11 and TF 1.0 is required by notebook in this lab. So you should recommend using udacity/carnd-term1-starter-kit

**Comment by domluna** [comment]
Fixed, removed all that and just refer back to the starter kit page earlier on in the ND.
