### ISSUE TITLE
Merge "Project Instructions" and "Project: Traffic Sign Classifier"

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#563]
One student reported significant frustration with all the different places he had to look in order to figure out the project instructions.

One easy is step is to merge the "Project Instructions" concept with the "Project: Traffic Sign Classifier" description.

**Comment by andrewpaster** [comment]
ok, I consolidated the two concepts, and I put the "Project Instructions" concept as hidden for now. 

Wasn't sure about carnd-starter kit and environment setup if students have a GPU that can use. Does carnd starter kit come with GPU support or would students need to set up tensorflow-gpu package separately?
