### ISSUE TITLE
Numbering Error in Traffic Sign Classifier Project

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#565]
In Project 2 Github repository -> Ipython Notebook, at the end of the file appears Question 9 but there are no Questions 1 to 8. I believe there might be updates in the P2 repository and other questions would have been removed but the last one is still there. You can change its numbering to 1 now I suppose. Request you to please look into that.

**Comment by baumanab** [comment]
Closing as this appears to have been addressed.
