### ISSUE TITLE
Project 5 confusion

### ISSUE THREAD

**Issue by megan-powell** [udacity/sdc-issue-reports#567]
From a student support ticket: 

Project 5, unit 34 "Hog Sub-sampling Window Search" is thoroughly confusing and partially incorrect.

I have been trying to get my head around this unit for days. Only when I realized that the statement "The find_cars only has to extract hog features once" should have the addendum "for each of a small set of predetermined window sizes" added to it did the pieces fall into place. Students should be encouraged to ignore the text and try to understand the code. I haven't understood the sentence "Each window is defined by a scaling factor where a scale of 1 would result in a window that's 8 x 8 cells then the overlap of each window is in terms of the cell distance" until now. Grammar?

Also, the fact that this code does not support students' choices for window positions but more or less comes with its own set is not really mentioned anywhere. In the code itself a number of 'pickles' show up whose significance I fortunately know from my other degree, or I'd be lost.

**Comment by baumanab** [comment]
Thanks for this. Hopefully, some recent changes in the content will clear up confusion.  Code elements will be addressed as part of #1307
