### ISSUE TITLE
T2.L05.S08 Process Covariance Matrix

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#568]
As a learner who is totally new to the Kalman filter and the matrix math behind it, the video on this page has almost no educational value for me.  It's not really clear what the point of the video is and it's essentially a spoken description of a math proof that doesn't tie in to concepts that have been "taught" in the content.  The intro talks about the "process covariance matrix" but, having watched this lesson multiple times there isn't sufficient explanation prior to this for the student to have an idea what this thing is or why it even matters.

The video seems like a mathematical proof of an equation (and concepts) that haven't been adequately covered in the preceding material.  I have spent many hours reading other content on other sites about the Kalman filter to try to fill in the gaps and can now watch most of this video and follow what Andrei is saying.  As someone not fluent in linear algebra, it's impossible to follow the last half of the video--it moves too quickly and it's not clear what I am supposed to be learning.

**Comment by cameronwp** [comment]
Thanks for the feedback! Sorry you've been frustrated by the EKF lesson.

We understand that there are some large conceptual leaps here and we're working on new content to improve understanding of the various matrices and transforms involved in EKFs. Keep an eye out for improvements to this lesson in the near-ish future.
