### ISSUE TITLE
T2.L05.S11 Laser Measurements Part 3

### ISSUE THREAD

**Issue by sstormm** [udacity/sdc-issue-reports#569]
This section (like most others in this lesson) should have a "sebastian-style" explanation.  There really isn't adequate treatment of the material prior to this to justify the statement in the text, "You have all you need for laser-only tracking!"

This page is very math heavy (light on explanation of the concepts) and relies on the student being able to on-sight recall the variables in the equations.  This whole lesson reminds me of my least pleasant experiences at university where a research assistant was tasked with trying to teach.

**Comment by cameronwp** [comment]
Thanks for your feedback! We're working on a few improvements with more "Sebastian-style" discussions. We'll definitely take your feedback into account.
