### ISSUE TITLE
Accuracy in Tensor Flow Lab Question 3 doesn't change sometimes

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#57]
I varied the inputs and several times I kept getting an accuracy of 0.10119298100471497. I had to keep running it to get it to show something different though I was varying the inputs.  Other people have also mentioned this issue 

https://carnd-udacity.atlassian.net/wiki/display/CAR/questions/6522855/answers/6522983?flashId=1cac4a5a71ea40d59c37bb100c21113282b91911

https://carnd-udacity.atlassian.net/wiki/questions/6521426/test-accuracy-over-80-in-question-3-tensorflow-lab

https://carnd-udacity.atlassian.net/wiki/display/CAR/questions/4784422/answers/5505593

With the same inputs it would stay at 0.10119298100471497 then I would have to run it several time to get it to change to another number. I had to do that for quite a number of variables. This especially happened when using the variables in configuration 2.

**Comment by Brok-Bucholtz** [comment]
@rm51 

Can you push your code to a Github repository?  This would help me out a lot.

**Comment by rm51** [comment]
This is my GitHub file https://github.com/rm51/selfdrivingcars/blob/master/lab.ipynb
The other student's GitHub is https://github.com/pkern90/CarND-TensorFlow-L2 The other student "ran the test in a loop 50 times with an max accuracy of 0.2904 and a mean of 0.19186"

**Comment by Brok-Bucholtz** [comment]
@rm51 

Thanks Renee!  I'm going to look these over.

**Comment by rm51** [comment]
I figure out what was going on in my case. I was hitting Ctrl +S to save but it wasn't saving it. After hitting the Disk button, it saved it and I could get the correct results every time. I'm not sure what the other people were doing, but it might have been something similar.

**Comment by rm51** [comment]
I found out more about this. I'm using a Mac so it's Command +S to save. Ctrl +S doesn't do anything. Now that I'm saving correctly everything looks fine.

**Comment by Brok-Bucholtz** [comment]
@rm51 

Awsome!  That solves that problem.

**Comment by giladgressel** [comment]
@Brok-Bucholtz 
I don't think this problem is solved.  I seriously doubt saving the file has anything to do with the results changing, it seems to be some kind of bug with the tensorflow lab.  I had a student today with this problem, the only thing that fixed it was wiping the repo and re-doing it.  The results get frozen on 10% somehow.

**Comment by rm51** [comment]
@giladgressel 
A new issue 110 was opened. It seems to have something to do with bad data and reloading the pickle file seems to help.
