### ISSUE TITLE
Update to Keras 2.0.0

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#574]
Term 1/Lesson 10, "Keras" relies on Keras 1.2.1 to run Python code in the browser, which is confusing: Keras documentation documents release 2.0.0, and the name of some classes and their constructor parameters have changed. E.g. Convolution2D has become Conv2D, with different ctor parameters naming. The lesson content and the automated unit-test running in the browser need to be updated for Keras 2.0.0.

**Comment by cameronwp** [comment]
Good point. It takes us a bit of time to upgrade our programming quizzes. We'll catch up as quickly as we can.

**Comment by andrewpaster** [comment]
Thanks for letting us know. I'm updating things to Keras 2.0 this week!

**Comment by baumanab** [comment]
Thank you for letting us know about this.  This is being closed out since upcoming changes to the classroom should resolve this issue.

**Comment by fantauzzi** [comment]
The issue was closed, but the lesson is still running Keras 1.2.2.

**Comment by baumanab** [comment]
Sorry for any confusion. This issue was rolled into upcoming classroom maintenance and closed a separate entity.
