### ISSUE TITLE
Provide link to download dataset for Keras exercise

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#575]
Term1, Lesson 10, Keras, has an exercise program running in the browser, loading a dataset from file "small_train_traffic.p" . Please provide the dataset file for download, so students can also run the exercise in their development environment, with debugger, etc..

**Comment by cameronwp** [comment]
Thanks for your feedback! We'll see what we can do.

(also, the cake is a lie!)

**Comment by ktepe** [comment]
is there any links to this data set?

**Comment by domluna** [comment]
A link to the dataset has been added to the page.
