### ISSUE TITLE
Add Encapsulation to EKF Starter Code

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#578]
I see that the Kalman filter in the `Laser Measurement Part 3` Quiz uses a lot of public variables which are freely modified in other classes.

Wouldn’t it be a good idea to demonstrate encapsulation early on and allow these fields to only be set using the constructor or a setter method so that they could be made private?

**Comment by cameronwp** [comment]
This is a good point, however, I'm going to prioritize this below the other work being done to improve programming quizzes.

I'll see what I can do, though, next week.
