### ISSUE TITLE
Unscented Kalman Filter Lesson 6 Quiz

### ISSUE THREAD

**Issue by ksakmann** [udacity/sdc-issue-reports#579]
Question 1: v_k is missing as a prefactor to the integral

**Comment by ksakmann** [comment]
same  for Question 2

**Comment by cameronwp** [comment]
You know, I had never heard the term 'prefactor' before, even after majoring in physics for undergrad. Thanks for the new word!

In this case, these questions are about the integral specifically, not the whole element in the state matrix. No need to include the prefactor as it is a constant and outside the integral.

**Comment by ksakmann** [comment]
Sorry, but the equation is not correct as it written now.  If you take the time derivative of answer B in question 1 you do not get the integrand that is written right above it (the line with the "???"). You get the integrand ***without v_k***. No big deal, I just noticed it.
![image](https://cloud.githubusercontent.com/assets/8419371/24061300/3023bb6e-0b57-11e7-8052-6fe09eaca2de.png)
