### ISSUE TITLE
Miniflow SGD quiz returns an error

### ISSUE THREAD

**Issue by MaximeLeclerc** [udacity/sdc-issue-reports#58]
The quiz:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/db18966a-23fa-4810-80b3-9ef1670f2d63#

Returns this when hitting submit:

Try Again
Something went wrong with your submission:
name 'forward_and_backward' is not defined

However, the instructions specify that 'I'm changing MiniFlow again so that your network can run more than once. This time, forward_and_backward turns into train_SGD.'

**Comment by DreSimpelo** [comment]
+1

**Comment by dolaameng** [comment]
+1

**Comment by bartmate** [comment]
+1

**Comment by cameronwp** [comment]
Sorry guys! A lot went wrong here. I'm blaming it on poor copy/pasting with a lack of sleep. I believe I've fixed it. Let me know if you're still seeing weird errors.
