### ISSUE TITLE
Student Manual would be better as Google Doc

### ISSUE THREAD

**Issue by benjaminsoellner** [udacity/sdc-issue-reports#580]
I think the Student Handbook, which is provided in a PDF/presentation format, could be better provided as Google docs, so people can more easily copy & paste links from there to their own scratchpad-like documents

This one: 
https://s3-us-west-2.amazonaws.com/udacity-email/Documents/Self-Driving+Car+Nanodegree+Handbook.pdf?utm_medium=email&utm_campaign=2017-03-16_carnd_march_term1_firstday&utm_source=blueshift&utm_content=2017-03-16_carnd_firstday_march&bsft_eid=4e53e27f-c6f3-4c3e-941b-c64061a308bc&bsft_clkid=95d74df9-11dd-45c2-b9c6-6ccc210694f4&bsft_uid=80aad2e4-4b0a-4fc1-bfa8-a9be4bf316c9&bsft_mid=33fd9f5f-b427-4d33-9b26-8496c6b93fab

**Comment by cameronwp** [comment]
Thanks for your feedback!

We generally try to stay away from Google docs in situations like this for a few reasons, namely that getting formatting to look nice is difficult and Google is inaccessible in some countries.

We've noted your feedback and may make changes to the handbook's format in the future.

**Comment by benjaminsoellner** [comment]
Then more on spot would be to use some more accesible technology, perhaps a plain HTML page or something. Just something where I can easily extract the URLs of additional ressources from.
