### ISSUE TITLE
Term 2 EKF Algorithm Generalization

### ISSUE THREAD

**Issue by gungorbasa** [udacity/sdc-issue-reports#581]
In EKF Algorithm Generalization equation under "More Details About Calculations with Radar Versus Lidar" title, equation is wrong. P prime - P x prime. h(x') equation

**Comment by cameronwp** [comment]
Thanks for the feedback. I'm not 100% sure what change you're suggesting. Could you be more specific about the equation?

**Comment by gungorbasa** [comment]
I think it is already fixed on another thread. Right now, it looks correct.
