### ISSUE TITLE
Inconsistent Notation for h(x') in Multivariate Taylor Series Expansion

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#584]

**Comment by dsilver829** [comment]
We're not putting the apostrophes in the right places. See the PDF cheatsheet.

**Comment by dsilver829** [comment]
From Slack: It might be better to explicitly specify `x` and `x'` as `(px, py, vx, vy)` and ` (p'x, p'y, v'x, v'y)` respectively using latex in the preceding description paragraph.

**Comment by andrewpaster** [comment]
Ok I made the changes. I copied those from the radar measurements lecture, so I've also copied and pasted how that lecture explained the equations, which is essentially what you are saying: "Recall from the Radar Measurements lecture that the h function is composed of three equations that show ...
