### ISSUE TITLE
Missing Subtitles for ReLU Lesson

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#585]
Network of ReLUs, term1 class,  chapter deep neutral network,  there is no subtitles in this section,. please check. thanks!

**Comment by justineudacity** [comment]
@dsilver829 can you link to the actual content in the classroom? kim can take care of it

**Comment by baumanab** [comment]
Thanks for reporting this.  It looks like the subtitles have been added.
