### ISSUE TITLE
Add Dates to Unpublished Modules

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#587]
Everyone can understand if not all lesson material is ready when a term starts, especially when talking about an all new ND like CarND. However, I have one suggestion. Instead of having lessons as “Coming soon!”, would be more student friendly to give an exact date, when the material will be available.

**Comment by jessluls** [comment]
Exact dates are difficult to give. Students can assume material will be released at or before the due date for the previous project (hopefully before). We will make announcements once stuff is live in Slack.
