### ISSUE TITLE
Bug in 33 Finding the Lines

### ISSUE THREAD

**Issue by MikeZhu92** [udacity/sdc-issue-reports#588]
The first code:
```
import numpy as np
histogram = np.sum(img[img.shape[0]/2:,:], axis=0)
plt.plot(histogram)
```
Can't be executed.

Should be
'''
histogram = np.sum(img[int(img.shape[0]/2):,:], axis=0)
'''

**Comment by swwelch** [comment]
Hi @MikeZhu92, thanks. I've changed it to use Python 3 floor division (//), which will return an int.
