### ISSUE TITLE
UKF slide 22, n_sigma used in weight equations instead of n_a

### ISSUE THREAD

**Issue by kejarowe** [udacity/sdc-issue-reports#589]
The equations for the weights used to calculate the estimate for the state mean and covariance have n_sigma instead of what I think should be n_a (the number of states in the augmented state matrix). On the next slide, the equations for the weights use n_a, but the script is so small that its is hard to tell n_a rather than n_sigma

**Comment by awbrown90** [comment]
Hi Kejarowe, yes you are correct that it should be n_a instead of n_sigma in the video. In the classroom slide you can use ctrl+scroll to zoom in and see the text better. I will add @cameron as a note that the video equation should be edited.

**Comment by justineudacity** [comment]
@awbrown90 can you link to the video in the classroom?

**Comment by awbrown90** [comment]
@justineudacity https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/a54c336a-9004-4006-b6b5-3f3959f203fc and the equation first shows up at 0:53

**Comment by awbrown90** [comment]
​​ https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/bf42ab6c-89db-4459-898f-4f270162edc0 contains the correct equation

**Comment by justineudacity** [comment]
new version is uploaded to coco

**Comment by cameronwp** [comment]
New version is live in the classroom! Thanks again for submitting this!
