### ISSUE TITLE
Minor spelling fix (MiniFlow)

### ISSUE THREAD

**Issue by DreSimpelo** [udacity/sdc-issue-reports#59]
On lesson 13 of MiniFlow: 
# 

self.gradients = {
    inbound_layer_n: partial_loss_with_respect_to_iinbound_layer_n,
    ...
}
# 

should be without the extra "i" in inbound:
# 

self.gradients = {
    inbound_layer_n: partial_loss_with_respect_to_inbound_layer_n,
    ...
}
# 

Very minor.

**Comment by Brok-Bucholtz** [comment]
@DreSimpelo 

Thanks for letting us know.  The extra "i" has been removed.
