### ISSUE TITLE
Typo in video equation

### ISSUE THREAD

**Issue by andrewpaster** [udacity/sdc-issue-reports#592]
Lesson: Lidar and Radar Fusion with Kalman Filters C++
Concept: State Prediction

Video: 1:25

The video has equation x' = F(subscript)x + v but the equation should be x' = F*x + v.

**Comment by justineudacity** [comment]
@andrewpaster @jessluls can you link to the classroom

**Comment by jessluls** [comment]
@justineudacity  https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/3612b91d-9c33-47ad-8067-a572a6c93837/concepts/49cd09a0-08b0-4123-9843-560098e6b219

**Comment by justineudacity** [comment]
new version is uploaded to coco
