### ISSUE TITLE
"Run Some Code!" in starter lesson should show not "localhost" but the docker URL

### ISSUE THREAD

**Issue by benjaminsoellner** [udacity/sdc-issue-reports#593]
If you run the starter code in a docker container, you are not accessing localhost:8888 but the docker-ip:8888 - accessing the IP that docker reports on start-up. This might confuse newbies to docker (like me). :)

**Comment by cameronwp** [comment]
Hmmm, we'll need to triage this. `localhost` works for me and I haven't seen any other complaints. You 100% sure you ran the commands as is?

**Comment by cameronwp** [comment]
`-p` should publish the container's port 8888 to the host.
