### ISSUE TITLE
T1 P3 Behavioral Cloning: Simulator not converting steering commands correctly

### ISSUE THREAD

**Issue by raketenolli** [udacity/sdc-issue-reports#594]
If I send any value < 0 to the simulator (in autonomous mode) using drive.py, the car will steer 25° to the left, if I send any value > 0, it will steer 25° to the right. This is true for both versions of the simulator downloaded on Feb 5 and Mar 20.

**Comment by baumanab** [comment]
Sorry for this technical issue.  Is this still an issue in the most recent version of the simulator?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
