### ISSUE TITLE
Car simulator in Ubuntu

### ISSUE THREAD

**Issue by fernandodamasio** [udacity/sdc-issue-reports#595]
I'm a Forum Mentor and there are a lot of student complaining that the simulator crashes after choosing graphics selection. Here is the link to the discussion: https://discussions.udacity.com/t/p3-simulator-is-not-able-to-run-in-linux-machine/223520/11

**Comment by Eng-Mo** [comment]
Hi I have the same issue as I cant run the simulator on ubuntu , it terminates after configuration window

**Comment by baumanab** [comment]
Does this continue to be an issue?  I'm guessing yes, given this possibly related to #843.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
