### ISSUE TITLE
carnd starter kit add an environment.yml for Mac install

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#596]
When installing the anaconda environment from [carnd-term1-starter-kit](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md)

The following command fails for Mac OS users:
conda env create -f environment.yml

Other students using Mac OS posted a fix on the forums.

I suggest adding a file "environment_mac.yml" with the following line:
```
    - pip:
        - moviepy
        - tensorflow==0.12.1
```

replaced with this:
```
    - pip:
        - moviepy
        -https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl
```

See [forum post](https://discussions.udacity.com/t/tensorflow-module/212640/11)

**Comment by cameronwp** [comment]
Very weird. I'm seeing our version work just fine with a fresh install. You mind pointing me to the forum post where y'all are discussing this?

**Comment by cameronwp** [comment]
What version of MacOS are you using?

**Comment by e7dud7e** [comment]
Hi!  The forum where others showed the fix is found [here](https://discussions.udacity.com/t/tensorflow-module/212640/11)  

I'm using Mac OS X Yosemite Version 10.10.5

Thanks!

**Comment by e7dud7e** [comment]
Hi, when I run
```
pip3 --version
```

I get:
```
pip 1.5.6 from /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (python 3.4)
```

**Comment by e7dud7e** [comment]
I just updated my pip, and I'll try re-install the carnd-term1  environment with the original environment.yml.
```
pip install --upgrade pip
Successfully installed pip-9.0.1
```

**Comment by e7dud7e** [comment]
After I upgraded pip to version 9.0.1, I removed the carnd-term1 environment and tried to re-install with the original environment.yml.  I still get the error when it tries to install tensorflow:
```
Collecting tensorflow==0.12.1
  Could not find a version that satisfies the requirement tensorflow==0.12.1 (from versions: )
No matching distribution found for tensorflow==0.12.1

CondaValueError: Value error: pip returned an error.
```

**Comment by e7dud7e** [comment]
When I modify environment.yml as specified in the forum post, the install is successful, and the output message is:
```
Collecting tensorflow==0.12.1 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl
  Using cached https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl
```

**Comment by cameronwp** [comment]
could you run `wget https://pypi.python.org/packages/b9/dd/18e6b098ecf7934a9ed16bd589d7ce239b3c57341a3153b93010bca8f63e/tensorflow-1.0.1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=7ad9a72ad38d8eddd9daaf33efaa8b74`. does it actually download a .whl file?

**Comment by e7dud7e** [comment]
I installed wget using [GNU Wget](http://rudix.org/packages/wget.html) and then ran:
```
wget --no-check-certificate https://pypi.python.org/packages/b9/dd/18e6b098ecf7934a9ed16bd589d7ce239b3c57341a3153b93010bca8f63e/tensorflow-1.0.1-cp35-cp35m-macosx_10_11_x86_64.whl#md5=7ad9a72ad38d8eddd9daaf33efaa8b74
```

it downloads the file:
```
(carnd-term1) edude temp $ ls -l
total 77408
-rw-r--r--  1 edude  staff  39628801 Mar  7 19:52 tensorflow-1.0.1-cp35-cp35m-macosx_10_11_x86_64.whl
```

**Comment by cameronwp** [comment]
So you can access the whl PyPI is hosting. Hard to say what else is going on here. I'll do some research and leave a note in the instructions.

**Comment by e7dud7e** [comment]
neat ^_^

**Comment by cameronwp** [comment]
Added a note to the installation [README](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md). I'm going to close this for the time being as we need to focus on other tasks. We'll be upgrading to TensorFlow v1.0 in the near-ish future. We think the issue will resolve then.
