### ISSUE TITLE
Code error in Term1- Advanced Land Finding lesson 10

### ISSUE THREAD

**Issue by YabinHu** [udacity/sdc-issue-reports#597]
There is an error in the page of lesson 10 'Calibrating Your Camera' (twice). Using gray.shape[::-1] to retrieve image height and width is incorrect. Should be instead of using gray.shape[:-1].

**Comment by baumanab** [comment]
Good catch!  Yes, [::-1] would reverse the array rather than extracting all but the last element.  This has been corrected.
