### ISSUE TITLE
kalman simulator linux issue

### ISSUE THREAD

**Issue by alexxucui** [udacity/sdc-issue-reports#599]

**Comment by alexxucui** [comment]
have downloaded the Kalman Filter Tracker for Linux OS. There are two files in the directory.

I tried the following commands:
./kalman_tracker_linux.x86_64
./kalman_tracker_linux.x86_64 ../data/

I get a message on the terminal saying - 
Set current directory to my working directory; 
Found path to the executable;
There is no data folder.

It stops after that. I think I may be missing something.

Can anyone please guide as to how to run the simulator?

**Comment by awbrown90** [comment]
@alexxucui recently fixed the download link for this
