### ISSUE TITLE
Typo in labs/miniflow.py

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#6]
There is "...respect to respect to..." phrase in miniflow.py lines 29-30: " 2. Multiply the above by the derivative of the each output node with respect to
    respect to the current node."

https://github.com/domluna/labs/blob/master/miniflow.py

**Comment by Brok-Bucholtz** [comment]
@dalex01 

Thanks for the feedback Alex!  This is fixed in Miniflow.
