### ISSUE TITLE
Miniflow Lesson # 10 - Cost

### ISSUE THREAD

**Issue by deanofthewebb** [udacity/sdc-issue-reports#60]
It appears the "Cost" quiz to find the MSE disassociated with the solution found in #11 - Gradient Descent 1.

The method signature for the quiz: def MSE(actual_output, ideal_output, feed_dict):

The method signature of the solution: def MSE(computed_output, ideal_output, n_inputs):

This is causing errors associated with submitting our answers e.g. ("The object 'Int' has no attribute keys()"). 

Looks like the method signature for the solution was updated but the miniflow.py was not

**Comment by cameronwp** [comment]
I believe this has been fixed. Try refreshing the page and clicking "Reset Quiz" to see the newest version of the code. (You will lose your work when you click "Reset Quiz", so make sure you copy it elsewhere first!)
