### ISSUE TITLE
Broken link in Convolutional Neural Networks lesson

### ISSUE THREAD

**Issue by Pepperrs** [udacity/sdc-issue-reports#600]
in Convolutional Neural Networks on page 30 (Convolutional Network in TensorFlow) there is a link to https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/ca299d5f-35f6-4520-a2b0-74c6878008b3/lessons/bd73c076-7661-4947-9f73-7020d313eb6f/concepts/83a3a2a2-a9bd-4b7b-95b0-eb924ab14432 which does not work (anymore?)

**Comment by jessluls** [comment]
I clicked all the links in that concept and none of them seem to go to the link you sent. Can you double check where you got that link?
