### ISSUE TITLE
Example code in lecture 35 measuring curvature has wrong  (xm_per_pix)

### ISSUE THREAD

**Issue by boulderZ** [udacity/sdc-issue-reports#601]
The example code from lecture 35 on  measuring curvature has incorrect values for xm_per_pix and ym_per_per_pix for the image size given. They should be as follows:
xm_per_pix = 3.7/350 and ym_per_pix = 3.0/144 meters per pixel. Probably should update the example to show how to derive the correct values for any image size.

**Comment by baumanab** [comment]
Thank you for bringing this to our attention.  Would you mind explaining how the values above were determined?

**Comment by baumanab** [comment]
closed as not actionable without updated information.
