### ISSUE TITLE
CTRV Integral 2

### ISSUE THREAD

**Issue by Javier-Galvez** [udacity/sdc-issue-reports#602]
In the Unscented Kalman Filters in questions related to "6. CTRV Integral 2" have two mistakes:

1. In both questions need to add the Vk (velocity at times k) in the question of the integral in order be correlated with the answer. For example Question 1: Vk integral of ... dt ???

2. In the second question, the correct answer should begin with Vk /ψk instead of Vk/DeltaT.

**Comment by Javier-Galvez** [comment]
Sorry, I didn´t add a description. But is as follow: 
In the Unscented Kalman Filters in questions related to "6. CTRV Integral 2" have two mistakes:
1. In both questions need to add the Vk (velocity at times k) in the question of the integral in order be correlated with the answer. For example Question 1: Vk integral of ... dt ???
2. In the second question, the correct answer should begin with Vk /ψk instead of Vk/DeltaT.

**Comment by cameronwp** [comment]
Checking.

**Comment by Javier-Galvez** [comment]
Sorry, the second mistake is as follow:

2. In the second question, the correct answer should begin with Vk /ψk instead of Vk/​​Vx dot.
