### ISSUE TITLE
T2 L10/25 - Entropy works the other way round as stated in the video.

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#605]
In the video it is said (1:12-1:21) that during the move step entropy goes down and during the measurement step the entropy goes up.
 
I think it is the other way round: increasing entropy means increasing uncertainty, i.e. the move step increases the entropy; decreasing entropy means less uncertainty, i.e. the measurement step decreases entropy.

**Comment by bartmate** [comment]
Hm. It seems that lesson 10 disappeared since my last visit.
The lesson I commented was about probability, bayes rule, etc.

**Comment by cameronwp** [comment]
Weird. I'm not 100% where you found this, actually. Please resubmit if shows up again.
