### ISSUE TITLE
suggestion to rubric

### ISSUE THREAD

**Issue by alexxucui** [udacity/sdc-issue-reports#608]
From student: Can you please update the February class's project description to include this on the "Project Submission" page? If this is not an appropriate place you can also update the Project Rubric instead. Specifically:

Tell students that the quality setting is not merely a way of running the project on less powerful machines, but also a way of reducing the difficulty of the assignment. Lower quality => easier assignment.
Regardless of the quality/difficulty setting, students can submit a video, model, and conditions under which the model is successful, and will not be penalized by reviewers who attempt to run the model under different conditions. Of course if the student does not state at such conditions then their submission can be considered a failure, they should have discovered the failure modes.

https://discussions.udacity.com/t/quality-level-for-project-submission/231730/5

**Comment by swwelch** [comment]
Hi @alexxucui,

The project submission page does now indicate that a video is required, and the nodes leading up the project submission page indicate that it will be used by reviewers. I'm not sure that we want to say that lower quality => easier assignment explicitly, although higher quality might present different challenges for a student.
