### ISSUE TITLE
Tensorflow Installation approach

### ISSUE THREAD

**Issue by vishalrangras** [udacity/sdc-issue-reports#609]
I would like to recommend an approach to install tensorflow on Windows 7 and other versions of Windows with Anaconda environment where students might not prefer to use Docker.

pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

This command works for Anaconda environment. It would be beneficial to be added to the installation approach so that students can take benefit of it.

**Comment by vishalrangras** [comment]
I would like to recommend an approach to install tensorflow on Windows 7 and other versions of Windows with Anaconda environment where students might not prefer to use Docker.

pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

This command works for Anaconda environment. It would be beneficial to be added to the installation approach so that students can take benefit of it.

**Comment by baumanab** [comment]
Thanks for this suggestion.  conda/anaconda tensorflow installation  is now stable.  We have added  notes to the installation instructions to emphasize this over docker.
