### ISSUE TITLE
Accessing AWS through MAC or SSH Secure Shell Client

### ISSUE THREAD

**Issue by vishalrangras** [udacity/sdc-issue-reports#610]
Some students have encountered a problem in connecting to AWS instance through MAC terminal or SSH Secure Shell Client where it gives error of setting up private key.

The solution to this is to use another open source SSH client to connect. You can add this note in the AWS setup video.

**Comment by baumanab** [comment]
Thank you for letting us know about this.  There are some occasional issues with Windows SSH as well, deploying client such as WinSCP works most of the time.  What do MAC equivalents you think should be included in the setup?

**Comment by vishalrangras** [comment]
@baumanab Sorry but I don't use MAC so I am not able to provide any clients for MAC. WinSCP provides only File Transfer Protocol as per my understanding, I am not sure if we can execute SHELL commands through WinSCP. For Windows though, Putty worked fine for me.

**Comment by baumanab** [comment]
Thanks for clarifying.   I misinterpreted the issue.  Putty can be used within WinSCP, in case that comes in handy.  Is this error occurring even when following step 9 here: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/f6fccba8-0009-4d05-9356-fae428b6efb4#

I haven't encountered this issue with various flavors of BASH (Ubuntu BASH, MinGW, Git-BASH). 

Would you mind clarifying which video you refer to above?

**Comment by vishalrangras** [comment]
@baumanab No, I am not talking about Step 9. I am talking about Step 11. This is mentioned on Step 11:

> From a terminal, SSH to that address as user “carnd”:

But windows user don't have a terminal. They don't even have any SSH client by default. And not all students are aware about how to use Putty or WinSCP for the same.

So I am suggesting that you can add detailed description of Step 11 for all the platforms i.e. Windows, MAC and Linux.

I personally don't use MAC but some students asked me for help when they tried to do step 11 through MAC. So providing detailed steps for MAC will be helpful.

On windows, I have experienced that Putty works fine but there is a client called **SSH Secure Shell Client** which doesn't work sometimes. So providing details about how to download and setup putty and then SSH to cloud instance using Putty Terminal will be useful.

**Comment by vishalrangras** [comment]
I checked, git bash also works fine. No issues there.

**Comment by vishalrangras** [comment]
Also, there is no issue with Step 9 as per my experience. I had used Proceeding without a key pair option and other students did the same thing. Not sure why the issue was been faced. One ancillary finding which I experienced was that when we are on any particular VPN, we are not able to connect with this AMI, but you can ignore that.

Only laying out the detailed steps in lecture about how to connect the AMI with a client in different OS environments will be helpful and you can close this issue.

**Comment by baumanab** [comment]
Thank you for helping us troubleshoot.  A note has been added to step 11 regarding using different clients.  The current instructions should work for bash and putty, independent of OS.
