### ISSUE TITLE
term1, lesson 8,the 9 section: parameters, are described wrong

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#613]
in 9 section: parameters, it described:
and a filter depth of K,
And the output depth would be equal to the filter depth D_out = K.

but in section 10's example description: 20 filters of shape 8x8x3 (HxWxD)

if D is depth, the filter depth is 3, not 20. but actually the  filter depth is 20. the depth is filter's total number ,not D parameter. it  is confused.

**Comment by awbrown90** [comment]
@asimay thanks for catching that, yeah it should be the number of filters being used instead of the individual depth of the filter
