### ISSUE TITLE
Should use argparse instead of tf.app.flags.FLAGS  in feature_extraction.py

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#616]
In source file https://github.com/udacity/CarND-Transfer-Learning-Lab/blob/master/feature_extraction.py
you use Keras to make things easier, then resort to Tensorflow to read command line arguments, which is a contradiction. Consider using Python's standard library instead, that is package argparse. Also, something like

if __name__ == '__main__':
    main()

does the trick and is simpler than:

if __name__ == '__main__':
    tf.app.run()

**Comment by awbrown90** [comment]
@fantauzzi thanks for the feedback. We will see if we cant make it cleaner by using that.
