### ISSUE TITLE
Broken Link at L3 Karlman Filer - Measurement and Motion

### ISSUE THREAD

**Issue by qqquan** [udacity/sdc-issue-reports#617]
The page has following text:
"The first cycle is the Measurement Update.
requires a product"

The link to "product" is broken. It shows "404

Sorry, we can't seem to find 
the page you are looking for."

**Comment by qqquan** [comment]
The link to the lesson with the broken link is as following. 
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/b3ebef23-64b7-4821-8809-05705165f829/concepts/08c5d7f0-cc4a-4ceb-9ee8-6424d19e0d25

**Comment by jessluls** [comment]
Thanks! I updated this a couple days ago - should work now.
