### ISSUE TITLE
Predict Radar Measurement Assignment 1 - error tolerance

### ISSUE THREAD

**Issue by gpavlov2016** [udacity/sdc-issue-reports#619]
The following code produces results that are almost identical to the correct answer but not exact:
`//transform sigma points into measurement space
  for (int i=0; i<2*n_aug+1; i++) {
      float px  = Xsig_pred.col(i)(0);
      float py  = Xsig_pred.col(i)(1);
      float v   = Xsig_pred.col(i)(2);
      float psi = Xsig_pred.col(i)(3);
      
      float rho = sqrt(px*px + py*py);
      float phi = atan(py/px);
      float rho_dot = (px*cos(psi)*v+py*sin(psi)*v)/rho;
      
      Zsig.col(i)(0) = rho;
      Zsig.col(i)(1) = phi;
      Zsig.col(i)(2) = rho_dot;
  }
  //calculate mean predicted measurement

  z_pred.fill(0.0);
  for (int i = 0; i < 2 * n_aug + 1; i++) {  //iterate over sigma points
    z_pred +=  weights(i) * Zsig.col(i);
  }

  MatrixXd R = MatrixXd(3,3);
  R.fill(0.0);
  R(0,0) = std_radr*std_radr;
  R(1,1) = std_radphi*std_radphi;
  R(2,2) = std_radrd*std_radrd;
  
  //predicted state covariance matrix
  S.fill(0.0);
  for (int i = 0; i < 2 * n_aug + 1; i++) {  //iterate over sigma points

    // state difference
    VectorXd x_diff = Zsig.col(i) - z_pred;
    //angle normalization
    //while (x_diff(3)> M_PI) x_diff(3)-=2.*M_PI;
    //while (x_diff(3)<-M_PI) x_diff(3)+=2.*M_PI;

    S += weights(i) * x_diff * x_diff.transpose() ;
  }
  
  S += R;`

Results:
z_pred: 
 6.12155
0.245993
 2.10313
S: 
   0.0946171 -0.000139447   0.00407016
-0.000139447  0.000617548 -0.000770652
  0.00407016 -0.000770652    0.0180917

Correct results:
expected result z_out:
 z_pred =
6.12155

0.245993

2.10313

expected result p:
 S =
0.0946171 -0.000139448 0.00407016

-0.000139448 0.000617548 -0.000770652

0.00407016 -0.000770652 0.0180917

**Comment by awbrown90** [comment]
@gpavlov2016 thanks for the feedback on that, I will see if I can lower the tolerance from the quiz grader on that.

**Comment by awbrown90** [comment]
@gpavlov2016, now the grader for that concept will accept results up to 3 decimal places for correctness.
