### ISSUE TITLE
UKF data files - ground truth values

### ISSUE THREAD

**Issue by khalilia2000** [udacity/sdc-issue-reports#620]
the ground truth values included in the data files for the UKF project only have 4 components (i.e. presumably px, py, px_dot and py_dot). would be better to have all 4 components of the state vector for ground truthing.

**Comment by awbrown90** [comment]
@khalilia2000 actually the 4 ground truth values are still px,py,vx,vy since the data files are identical to the EKF project. Maybe I can make a note about that to clear things up.
