### ISSUE TITLE
C++ For Programmers: Cin and Strings Programming Quiz

### ISSUE THREAD

**Issue by techmarco** [udacity/sdc-issue-reports#621]
Answer submission results in "Try Again" pop-up instead of "Great Job" when correct answer is provided.

**Comment by jessluls** [comment]
Can you link to the quiz?

**Comment by schrezraoeder** [comment]
I believe this has been fixed: https://classroom.udacity.com/courses/ud999/lessons/1343a461-102f-41e1-b505-bf9ec62f427b/concepts/52490677-24dd-4d8d-9b42-efbcb40b5ffd#

**Comment by jessluls** [comment]
thanks!
