### ISSUE TITLE
Term1/Lesson 12/Section 7 BGR loading, RBG predicting

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#623]
At around the 1min mark of the video, the dataset images are read in using cv2.imread.  This will load images in BGR order.  However, drive.py uses PIL to load video images, which loads in RBG order.  The predictions are thus being done on RBG order for a model trained on BGR order.

**Comment by troyjlee** [comment]
oops, the RBG above should be RGB.

**Comment by awbrown90** [comment]
@troyjlee thanks for the feedback, I added a note
