### ISSUE TITLE
Error in T2 L7.3 Unscented Kalman Filters -> The State Vector (Quiz Q2 answer pop-up)

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#625]
The answer pop-up to Q2 says 

> Of course, this also means that state vector 3 represents the largest turning radius.

But State Vector 2 represents a car moving in a straight line, so it has infinite turning radius, which is greater than State Vector 3's finite turning radius. So this statement seems incorrect.

State vectors given are:
<img width="184" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24356716/0a13a4f4-12f3-11e7-9eff-312bead05ecd.png">

**Comment by awbrown90** [comment]
@jessicayung good point! I removed that phrase.
