### ISSUE TITLE
Typo in T2 L7.7 Unscented Kalman Filters -> CTRV Zero Yaw Rate

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#626]
In Question 1, the question in the box states:

> 1) Which of the above (☝) options gives the change in x-position over time when the **raw** rate is 0?
 
-> 1) Which of the above (☝) options gives the change in x-position over time when the **yaw** rate is 0?

**Comment by jessicayung** [comment]
Likewise for question 2:
2) Which of the above (☝) options gives the change in y-position over time when the **raw[-> yaw]** rate is 0?

**Comment by jessluls** [comment]
Thanks for catching that! Should be correct now.
