### ISSUE TITLE
Lesson 3 (Kalman Filters)

### ISSUE THREAD

**Issue by haribalan** [udacity/sdc-issue-reports#627]
Hi,

There is a issue on the study material.

On the Self Driving car nanodegree -> Term 2 -> Lesson 3 (Kalman Filters) -> Unit 8.Measurement and Motion there are few reference links for study which are broken.
When clicked on the links, I receive: 
404
Sorry, we can't seem to find 
the page you are looking for

**Comment by jessluls** [comment]
Hi! Thanks for reporting - we updated this a couple days ago so you should be seeing a working link now.
