### ISSUE TITLE
Wrong karnaugh map for OR in T1 L4/11

### ISSUE THREAD

**Issue by Gryton** [udacity/sdc-issue-reports#632]
Karnaugh map for OR is really a XOR map in graphic in lesson 11. OR & NOT Perceptron Quiz
![image](https://cloud.githubusercontent.com/assets/6225948/24424504/1c68ca30-1401-11e7-9e6b-c6379bd48ec3.png)

**Comment by awbrown90** [comment]
@Gryton thanks just got the graphic updated
