### ISSUE TITLE
D Silver misspeaks

### ISSUE THREAD

**Issue by properGrammar** [udacity/sdc-issue-reports#633]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/4b26b52d-8eed-4b04-91a6-f1d421bb04f1

In the video (at 1:20) he says the image is 160 pixels wide x 320 pixels high. This is an interpolation. Maybe add an Instructor's note?

**Comment by properGrammar** [comment]
Seems to be another example of this at (https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/b3883cd8-f915-46e1-968a-e935323e749b) ?? 

At the bottom of the page: input_shape=(160,320,3)

**Comment by properGrammar** [comment]
And here?... https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/0487ab4d-5550-4921-b3f0-5a9f1e4f9e93  (at 0:18 in the video) 

I suspect that all of these issues are interrelated? Perhaps I have the standard interpolated in my mind?.. Is it in fact H x W x D??? Hope I'm not wrong! 😂

**Comment by troyjlee** [comment]
I agree, in the first one he misspoke.  The others look correct.  In numpy the shape is given in the usual matrix way, with #rows first, i.e. the height, then # cols.

**Comment by properGrammar** [comment]
Right. I presume that's where David's misspeaking originated... Hard to keep the different standards straight, I suppose.

**Comment by properGrammar** [comment]
More data points : )

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/d76493fa-8061-44ab-b122-bc7fa25cd270 
"The cameras in the simulator capture 160 pixel by 320 pixel images."

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/b602658e-8a68-44e5-9f0b-dfa746a0cc1a
"The images captured in the car simulator are... a size of 320 x 160 x 3"

Lol

**Comment by awbrown90** [comment]
@properGrammar just added some notes and re-edits to help clear things up should be HxWxD so 160x320x3

**Comment by properGrammar** [comment]
Radical, thanks!
