### ISSUE TITLE
T2 L9/25 - Entropy works the other way round as stated in the video.

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#634]
Term 2 - Lesson 9 (Localization Overview) - Entropy works the other way round as stated in the video.

In the video it is said (1:12-1:21) that during the move step entropy goes down and during the measurement step the entropy goes up.

I think it is the other way round: increasing entropy means increasing uncertainty, i.e. the move step increases the entropy; decreasing entropy means less uncertainty, i.e. the measurement step decreases entropy. (Maybe the absolute value is meant or the minus sign was missed.)

**Comment by bartmate** [comment]
This is the same as report 605, which was closed because the lesson disappeared temporarily.

**Comment by andrewpaster** [comment]
Hey, thanks for pointing this out and for your persistance with getting this on the waffleboard. You're right, and I added a clarification underneath the video: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/48739381/concepts/486928090923
