### ISSUE TITLE
Project 3 - Behavioral Cloning: Keyboard vs Mouse Inputs

### ISSUE THREAD

**Issue by enest** [udacity/sdc-issue-reports#637]
As those who are familiar with project might know, keyboard inputs are too sensitive in comparison to the mouse inputs. Therefore I would suggest to add a sliding bar for the input sensitivities of keyboard/mouse to the simulator.

P.s: I've mistakenly created another post with the # 636. I couldn't delete it. Sorry

**Comment by awbrown90** [comment]
@enest thanks for the feedback and we will take that into consideration as a future update.
