### ISSUE TITLE
A number of minor English typos...

### ISSUE THREAD

**Issue by properGrammar** [udacity/sdc-issue-reports#638]
Boy, somebody was rushing to crank this one out! Lol..

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/055bb6e0-b941-491b-b42a-81a04208f799

"The fourth argument run1 is the directory to save the images seen by the agent to." Ends in a dangling participle; could be more clearly phrased. Perhaps, "The fourth argument, run1, is the directory to which to save the images seen by the agent" ?

"If the directory already exists it'll be overwritten." Missing a comma. Should be, "If the directory already exists, it'll be overwritten."

"The image file name is a timestamp when the image image was seen." Missing an "of", and says "image" twice. Should be, "The image file name is a timestamp of when the image was seen."

"Create a video based on images found in the run1 directory." Should be, "Creates..."

"The name of the video will be name of the directory following by '.mp4', so, in this case the video will be run1.mp4." Missing "the", "following" should be "followed", missing comma. Should be, "The name of the video will be the name of the directory followed by '.mp4', so, in this case, the video will be run1.mp4."

"Optionally one can specify the FPS (frames per second) of the video:" Missing comma. Should be, "Optionally, one can specify the FPS (frames per second) of the video:"

"The video will run at 48 FPS." Case incorrect. Should be, "Will run the video at 48 FPS."

**Comment by properGrammar** [comment]
Just noticed that a number of these errors also exist in https://github.com/udacity/CarND-Behavioral-Cloning-P3 under Details About Files In This Directory

**Comment by jessluls** [comment]
thanks for these edits. I've updated the classroom content. Not sure on the case for the last sentence though. 

@swwelch can you update github?

**Comment by swwelch** [comment]
Ok, fixed in Github as well!
