### ISSUE TITLE
Extended Kalman filter process covariance matrix

### ISSUE THREAD

**Issue by philbort** [udacity/sdc-issue-reports#641]
In Term 2 "Lidar and Radar Fusion with Kalman filters in C++" class Section 8 "Process covariance matrix", The derivation of the Q matrix is very different from what I read from literature. All the books I could find have the same way to derive the Q matrix for a constant velocity model such as Eq. (43) from:
`http://www.robots.ox.ac.uk/~ian/Teaching/Estimation/LectureNotes2.pdf`

The way the course derived assuming the noise term is the acceleration term, which I don't think is a valid assumption. Would you please provide a reference for the way you derived the Q matrix?

**Comment by ricardo-jmnez** [comment]
To the best of my knowledge the process covariance matrix derived in the lecture is correct. Keep in mind that this is just one of the many available model for vehicle motion (for more kinematic models see the first lessons in the UKF section of term 2).  The model presented in class is the so called "constant velocity model", where the velocity is assumed constant during the time between consecutive samples. It is derived directly in discrete time. Please see Bar-Shalom et al. ( Estimation with applications to tracking and navigation, John Wiley year 2001) section 6.3 Direct Discrete-time kinematic models.
