### ISSUE TITLE
Behavioral Cloning #12: Multiple Cameras

### ISSUE THREAD

**Issue by vishalrangras** [udacity/sdc-issue-reports#643]
In this topic, in the code, following is written:

directory = "..." # fill in the path to your training IMG directory

img_center = process_image(np.asarray(Image.open(path + row[0])))

In 2nd line, "path" is used and in 1st line, "directory" is used. These are misleading. Can you please make it similar in both the lines.

**Comment by baumanab** [comment]
Thanks for reporting this, it has been corrected.
