### ISSUE TITLE
CarND-Alexnet - Incorrect link

### ISSUE THREAD

**Issue by loshkovskyi** [udacity/sdc-issue-reports#644]
Where: `Lesson 11 - Transfer Learning - Lab: AlexNet`. Section: `Getting Started`.
Please change:
```
git clone https://github.com/udacity/CarND-Alexnet-Feature-Extraction
```
to:
```
git clone https://github.com/udacity/CarND-Alexnet-Feature-Extraction.git
```
otherwise it won't clone.

**Comment by baumanab** [comment]
Thank you for bringing this to our attention.  The clone command in this lesson now appears to be working.
