### ISSUE TITLE
Unscented Kalman Filters: Lesson 7, CTRV Integral 2 Quiz

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#645]
The quiz shows two options and A is accepted as the right option. However, the denominator in A should be psi-dot-k and not v-dot-k.

<img width="894" alt="screen shot 2017-04-01 at 4 16 10 pm" src="https://cloud.githubusercontent.com/assets/3866405/24578088/d99a16ac-16f6-11e7-904c-2863432b3d92.png">

**Comment by ancabilloni** [comment]
The question equation is also missing the v_k multiply before integral sign for both questions.

**Comment by baumanab** [comment]
Thank you for reporting this.  The inconsistencies have been addressed.
