### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by properGrammar** [udacity/sdc-issue-reports#647]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/f0f5ee98-0a73-40cb-8f58-3b0bd16a9ec7/lessons/50b60126-22fc-47ce-aed4-c3b6ce68e8eb/concepts/7d005194-3d9b-42f5-a026-72620cc22d2b

Says "Resume Refection" under the video. Should be "Resume Reflection"

**Comment by jessluls** [comment]
fixed! thank you!
