### ISSUE TITLE
Add Eigen Cheat Sheet

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#648]
“Eigen Cheat Sheet” link is missing from _UKF > 14. Generating Sigma Points Assignment 1_. Its referred to in the video here (t=119):
https://youtu.be/TIc3n-cxTqc?t=119

**Comment by ChrisShepherd81** [comment]
It's probably this link: https://eigen.tuxfamily.org/dox/group__QuickRefPage.html

**Comment by baumanab** [comment]
Thanks for reporting this.  The quick reference guide link has been added.
