### ISSUE TITLE
Update Behavioral Cloning Project Rubric

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#649]
Chris X Edwards [9:30 PM] 
https://review.udacity.com/#!/rubrics/432/view Rubric for project 3 says "The submission includes a model.py file, drive.py, model.h5 a writeup report and video.mp4" under "required files" section, but later goes on to say "examples of images from the dataset should be included". I would make that "should" say "must" and/or add "example training set images" to the list of required files.

**Comment by swwelch** [comment]
The images are supposed to be part of the writeup, so I've added that to the description of the writeup, and changed the rubric to say "must".
