### ISSUE TITLE
Dimension-problem in chapter Miniflow - Linear Transform

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#65]
Maybe I am not aware some kind of convention (e.g. having an implicit transpose operation somewhere). 

Though, if there is such a convention I am not aware of, I think, that the problem written in the 2nd half of 2) below still exists. 

The convention I know is that we can multiply 2 matrices if their dimension are: n(rows)xk(columns) and kxm and the resulted matrix will have dimension nxm (no implicit transpose anywhere). This is the same as in Wikipedia: https://en.wikipedia.org/wiki/Matrix_multiplication .

1)
Equation (1) implies that we multiply x and w in this order to calculate one output. If we preserve the order, for calculating all outputs at once, x should be a row-vector (with n values, i.e 1xn) and W should have the dimension nxk (n rows, k columns) and so the result will be a row-vector with k values which fits to the dimension of the output layer. While in the text W has k rows and n columns (kxn).

2)
Equation (2) is o = XW + b, where the variables have the following dimensions based on the text:
X: nxm (n rows, m columns)
W: kxn
To be able to multiply X and W (in this order), the 2nd dim of X should be the same as the 1st dim of W. 

I think, here we have a more serious issue: Typically the first layer (the left-most vertical thing on the figure) represents one input data with all of its features. And the generalization (mentioned just above the dog image) should be that we do our calculations for all input data at once. (And not that we calculate all features at once instead of just calculating one feature at a time. This would mean that the corresponding layer has only one neuron in it...) 

So n should be the number of features (which is the same as the number of neurons in the first layer) and m should be the number of input data. Also W should be transposed, i.e. it should have dimension nxk.

If we do this way, everything is OK: For one data we have vector x with n values in it (of course it should be a row-vector [1xn] for the multiplication with W [nxk]). For m data we would have X with dimension mxn and it would be multiplied by W [nxk]. The result is a matrix with dimension mxk, because for each separate input data we have a different result vector with k values. (This means that 'o' should be written in uppercase format to show that it is a matrix and not just a vector.)

**Comment by bartmate** [comment]
Maybe I am not aware some kind of convention (e.g. having an implicit transpose operation somewhere). 

Though, if there is such a convention I am not aware of, I think, that the problem written in the 2nd half of 2) below still exists. 

The convention I know is that we can multiply 2 matrices if their dimension are: n(rows)xk(columns) and kxm and the resulted matrix will have dimension nxm (no implicit transpose anywhere). This is the same as in Wikipedia: https://en.wikipedia.org/wiki/Matrix_multiplication .

1)
Equation (1) implies that we multiply x and w in this order to calculate one output. If we preserve the order, for calculating all outputs at once, x should be a row-vector (with n values, i.e 1xn) and W should have the dimension nxk (n rows, k columns) and so the result will be a row-vector with k values which fits to the dimension of the output layer. While in the text W has k rows and n columns (kxn).

2)
Equation (2) is o = XW + b, where the variables have the following dimensions based on the text:
X: nxm (n rows, m columns)
W: kxn
To be able to multiply X and W (in this order), the 2nd dim of X should be the same as the 1st dim of W. 

I think, here we have a more serious issue: Typically the first layer (the left-most vertical thing on the figure) represents one input data with all of its features. And the generalization (mentioned just above the dog image) should be that we do our calculations for all input data at once. (And not that we calculate all features at once instead of just calculating one feature at a time. This would mean that the corresponding layer has only one neuron in it...) 

So n should be the number of features (which is the same as the number of neurons in the first layer) and m should be the number of input data. Also W should be transposed, i.e. it should have dimension nxk.

If we do this way, everything is OK: For one data we have vector x with n values in it (of course it should be a row-vector [1xn] for the multiplication with W [nxk]). For m data we would have X with dimension mxn and it would be multiplied by W [nxk]. The result is a matrix with dimension mxk, because for each separate input data we have a different result vector with k values. (This means that 'o' should be written in uppercase format to show that it is a matrix and not just a vector.)

**Comment by domluna** [comment]
@bartmate thanks for bringing this up. There is indeed an error here. X should be nxm and W mxk or X is mxn and W is nxk (stay the same), n is the number of features instead of m in this case. I'll make a fix.

**Comment by domluna** [comment]
I updated the section, should make sense now but let me know if something is unclear!
