### ISSUE TITLE
Review C++ Typing

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#650]
Andrey Glushko [2:30 PM] 
Term2, "Laser Measurements Part":  Please review your C++ code and replace 'long' by 'int64_t' or add cross-platform deftype for any variables used for saving int64-values like timestamp in  Laser Measurements Part. Your C++ code works on Linux but doesn't work on Windows for example. The type 'long' is int32 on Windows  :slightly_smiling_face:

**Comment by baumanab** [comment]
timestamp variable type declarations have been updated to int64_t.
