### ISSUE TITLE
Emphasize Eigen Non-Initialization

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#653]
Kelly Smith [6:28 PM] 
For the EKF Project in Term 2, I'd recommend that the project emphasizes that the `Eigen` library does not initialize `VectorXd` or `MatrixXd` objects with zeros upon creation.  This led to a lot of headaches when I attempted the project (output randomly changed from run to run with same executable).

**Comment by baumanab** [comment]
A note has been added to the readme and comment to the code.
