### ISSUE TITLE
Term2 Lessons are not saving user progress

### ISSUE THREAD

**Issue by jtryan** [udacity/sdc-issue-reports#658]
The lessons are not tracking when a lecture has been played. No checkmark or star. Additionally quiz answers are not being saved after leaving the lesson. They are reset upon entering the lesson a gain.

**Comment by jessluls** [comment]
thanks for reporting. can you go to udacity.com/contact to report the bug? remember to include your system information in your report! this is a classroom issue, not a CarND issue.
