### ISSUE TITLE
Kalman Filter Equations in C++ Part 1

### ISSUE THREAD

**Issue by andrewpaster** [udacity/sdc-issue-reports#660]
In the video, there is an equation at 0:21

x' = Fx + Bu + v

and then u gets crossed out to leave:
x' = Fx + v

Then at 1:36 the equation is
x' = Fx + u

I think 1:36 is supposed to be x' = Fx + v

the video also doesn't explain what Bu is and why it gets crossed out

**Comment by jessluls** [comment]
@andrewpaster can you work with @justineudacity to fix this?

**Comment by andrewpaster** [comment]
I'm not sure what the video is trying to show

**Comment by justineudacity** [comment]
@andrewpaster can you link to the vid in classroom?

**Comment by justineudacity** [comment]
@cameronwp can you take a look at this?
i think this is the vid in frame.io
https://app.frame.io/?v=sO5UMmeK

**Comment by cameronwp** [comment]
I apparently no longer have access to frame.io :( Send me another link?
What am I supposed to be looking for?

**Comment by justineudacity** [comment]
@cameronwp https://www.youtube.com/watch?v=WrP_hsvS-Ko this video!

andrew isn't sure why the Bu is crossed out and at 1:36 the v is a u.

**Comment by cameronwp** [comment]
Honestly, I have no idea. I'd go with what Andrew thinks.

**Comment by andrewpaster** [comment]
It's this video: https://www.youtube.com/watch?v=WrP_hsvS-Ko

I don't actually know what to do about it if anything. Mercedes would have to give us more explanation, and they're hard to get a hold of these days.

**Comment by justineudacity** [comment]
@andrewpaster any update on this? I know that you  met with Dominik/Andrei a few weeks ago.

**Comment by andrewpaster** [comment]
Oh hi there. Yeah, I added a text node to explain the Bu thing. So that is fine. 

Didn't I put a notes about the other part x' = Fx + v in frame.io?

**Comment by justineudacity** [comment]
video is uploaded
