### ISSUE TITLE
Wrong comment in project Kidnapped Vehicle

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#662]
In file particle_filter.h in the comment above method updateWeights(...) the following is written for parameter std_landmark:
 
	 * @param std_landmark[] Array of dimension 2 [standard deviation of range [m],
	 *   standard deviation of bearing [rad]]

This is not consistent with main.cpp where this method is called and the parameter is substituted with local variable sigma_landmark which has this comment in its declaration: 

	double sigma_landmark [2] = {0.3, 0.3}; // Landmark measurement uncertainty [x [m], y [m]]

I think this 2nd comment is the right one.

**Comment by eminnett** [comment]
I created a [PR](https://github.com/udacity/CarND-Kidnapped-Vehicle-Project/pull/2) for this when the question was first raised on Slack. I think it is just waiting to be reviewed and merged.

**Comment by baumanab** [comment]
Thanks for helping with this, then change makes sense.  I wasn't able to merge the PR but I did make the change and noted your contribution in the commit comments.
