### ISSUE TITLE
Wrong integral equations for UKF

### ISSUE THREAD

**Issue by UsmanIjaz** [udacity/sdc-issue-reports#663]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/6eacabfa-d0df-411e-9f3a-5a6d4ab68637

I think the equations (correct solutions) are wrong and it should be corrected. The problem with both questions is that vk is not part of the question but correct answers are as if vk is part of question which was taken out as constant in the video and not part of the integral for which answer is expected...
Also, for the second question, denominator for the correct solution should be change in yaw rate not change in speed which would result in divide by zero in this case..
The results are corrected in next video. So my points can be confirmed by comparing to the next video..

**Comment by baumanab** [comment]
Thank you for pointing this out.  These items have been addressed.
