### ISSUE TITLE
Udacity Profile: Not Possible to Update Resume

### ISSUE THREAD

**Issue by avshepelev** [udacity/sdc-issue-reports#664]

**Comment by avshepelev** [comment]
On the Udacity "My Profile" page, the Upload Resume function does not work when replacing an existing resume with a new one. Even when a new resume is selected and the changes are saved, the old resume opens when clicking the Resume button. In addition to this, two identical windows pop up when viewing a resume.

**Comment by avshepelev** [comment]
Forgot to mention that the issue occurs when using Mozilla Firefox

**Comment by jessluls** [comment]
Hi there! Can you write into career-support@udacity.com to report this issue? We're only able to resolve content issues here :). Thanks!
