### ISSUE TITLE
Kidnapped Vehicle: Error in error calculation -> Grader does not work well (in certain cases)

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#666]
During the error calculation the angles difference is wrong, so the distance of 0.1 radian and 2\*pi-0.1 radian is not 0.2 but 2\*pi-0.2.

The code is in the helper_functions.h:

    inline double * getError(double gt_x, double gt_y, double gt_theta, double pf_x, double pf_y, double pf_theta) {
        static double error[3];
        error[0] = fabs(pf_x - gt_x);
        error[1] = fabs(pf_y - gt_y);
        error[2] = fabs(pf_theta - gt_theta); <----- This should be fixed
        return error;
    }

**Comment by bartmate** [comment]
My fix is something like this:
    
    error[2] = fabs(pf_theta - gt_theta);
    fmod(error[2],2.0*M_PI);
    if (error[2]>M_PI) {
        error[2] = 2.0*M_PI - error[2];
    }

**Comment by baumanab** [comment]
Thanks for letting us know about this.  It looks like the code was updated some time ago.
