### ISSUE TITLE
Incorrect Function Calls in UKF

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#667]
In the unscentedKalmanFilter code, I noticed that in many instances function calls were made with pointer. These were then assigned memory addresses of variables inside the function. AFAIK, this is incorrect.

[9:48]  
the variables inside a function (in C/C++) are created on stack which is then destroyed. The right way to do it is to call new and create the objects on a heap. I might be missing something - its been many years since I wrote any code in C/C++

**Comment by baumanab** [comment]
closing per conversations noted in JIRA ticket here:

https://udacity.atlassian.net/browse/DRIVE-4264
