### ISSUE TITLE
EKF Starter Code: previous_timestamp_ should be "long long"

### ISSUE THREAD

**Issue by keerthi2kiran** [udacity/sdc-issue-reports#669]
In the EKF project starter code, file FusionEKF.h line 39, 
Issue: long previous_timestamp_;
Fix: long long previous_timestamp_;
On windows machine, long is 32-bit and lead to truncation of the timestamp.

**Comment by baumanab** [comment]
Good catch!  It looks like the code has been updated to correct this issue.
