### ISSUE TITLE
Misstatement about Image Edges

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#672]
In the Hough transform lession you say: " we are operating on the image edges (the output from Canny)" when you in fact are not only doing that. You are operating on the exstracted lines form canny by doing this; `masked_edges = cv2.bitwise_and(edges, mask)`. A bit misleading there, was coding this on my own, and hit a bump here x)

When you are calling the `cv2.HoughLinesP` you are working on masked_edges, not edges

**Comment by baumanab** [comment]
Thanks for reporting this.  This has been corrected.
