### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/sdc-issue-reports#673]
Hello, 

I'm not reporting any bug. I'm just here asking if you guys can put up external resource links for Term 2 materials and also C++ materials that are specific to help us out in the lesson quizzes/Project?

I was told to put this request here. Thanks!

**Comment by baumanab** [comment]
Thank you for posting this reminder.  We now have a class specifically for this purpose, c++ for programmers.  https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/09c2b224-0a3d-412e-9cda-46d2d724b695/concepts/72087112-7f6d-4ef6-9017-06476df9c8b1
