### ISSUE TITLE
shouldn't px,py,vx,vy all have the apostrophe after them

### ISSUE THREAD

**Issue by pcarney8** [udacity/sdc-issue-reports#677]
In term 2, Lesson: EKF Algorithm Generalization -> shouldn't px,py,vx,vy all have the apostrophe after them? in the line reads: "The predicted measurement vector x​′ is a vector containing values in the form [​p​x,p​y,v​x,v​y]."

**Comment by swwelch** [comment]
Hi @pcarney8, thanks for pointing. I asked the course developer, and the vector is just supposed to indicate a general form as including both position and velocity, so the apostrophes were not included.
