### ISSUE TITLE
T1 5.13 Python3 causes raise ValueError("No JSON object could be decoded")

### ISSUE THREAD

**Issue by Gryton** [udacity/sdc-issue-reports#679]
When I use python3 print("var: ", variable) in submission when pressing TEST RUN works just fine, but using SUBMIT ANSWER I receive: Try Again
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded

**Comment by swwelch** [comment]
Hi @Gryton, I'm looking into this now. Do you have a link to the quiz? It seems like the numbering may have changed.

Also, could you include other code that you have used here? From the error, it looks like the grading code is using Python 2.7.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
