### ISSUE TITLE
P1 submission instructions a bit unclear

### ISSUE THREAD

**Issue by skh** [udacity/sdc-issue-reports#68]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/83ec35ee-1e02-48a5-bdb7-d244bd47c2dc/lessons/8c82408b-a217-4d09-b81d-1bda4c6380ef/project

One of my mentees was unsure after reading this what to submit -- just the notebook, or all images and videos as well?

I advised to submit the whole project folder (that's what I did) but actually don't really know either.

**Comment by Brok-Bucholtz** [comment]
@skh 

We added clarification to what needs to be submitted.  You only need to submit the Jupyter notebook.  This was a good question, thanks you for submitting it.
