### ISSUE TITLE
Markov Localization Lecture #6 and 7

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#681]
In the Markov localization for term 2, in lessons 6 and 7, there is no link to get the map, controls, and observations data files. Can you guys please share those links?

**Comment by jessluls** [comment]
hi there - can you link to the classroom so we know exactly what you're referencing? our numbering is sometimes different internally.

**Comment by gtg162y** [comment]
Hi,

Here's the link to the sections with the missing data:

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/a0e564bf-1a4c-4cc3-9de7-8671d44655db

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/59c0f32a-7be2-4864-b4e9-58c9bd993635

Amit

**Comment by swwelch** [comment]
Hi, we don't generally make the data files for quizzes available in the classroom, but this has been a popular request, and it is definitely something we will be working on including in the future. There are some workarounds which have been posted here: https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750/3
