### ISSUE TITLE
Behavioral Cloning - broken link

### ISSUE THREAD

**Issue by loshkovskyi** [udacity/sdc-issue-reports#682]
Related to: https://github.com/udacity/sdc-issue-reports/issues/315

Apparently, the link to the "helpful guide" changed again. It's currently:
https://carnd-forums.udacity.com/questions/26214464/behavioral-cloning-cheatsheet

As far as I remember the forums have been replaced.

**Comment by ibrahim-mo** [comment]
I too noticed the same thing.

**Comment by swwelch** [comment]
It looks like the link here points to a .pdf file now: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/project
