### ISSUE TITLE
Term 2 - Lesson 3 (Kalman Filters) - Lecture 8 (Measurement and Motion) - Hangs and does not load

### ISSUE THREAD

**Issue by mukilk7** [udacity/sdc-issue-reports#684]

**Comment by mukilk7** [comment]
I saw that this particular lecture has been reported before for 404 error but this time the page just hangs and no video or text content shows up.

**Comment by mukilk7** [comment]
BTW, I also checked with folks on the facebook group, and it doesn't load for them either.

**Comment by mihirrajput** [comment]
For me the page is completely blank.

**Comment by sunnychugh87** [comment]
same here...not loading

**Comment by jessluls** [comment]
hi there - this is loading for me, can you send me a screenshot?

**Comment by mukilk7** [comment]
@jessluls - I don't have this problem anymore. I can see the lecture. So I'll go ahead and close this out.
