### ISSUE TITLE
Unscented Kalman filter quizz not showing options

### ISSUE THREAD

**Issue by rkorach** [udacity/sdc-issue-reports#685]
The quizzes in Term 2 lesson 7 (unscented kalman filters) from section 3 and upwards don't show the options we should select the answer from. Only the radiobuttons are present to choose, but nothing above !

screenshot: https://cl.ly/1u1U1v441a3a

link: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/a104551c-4b77-4cb6-9cb8-3fb1ddad8b97

**Comment by rkorach** [comment]
Weirdly enough, it works well today. (I did experience the bug on multiple browsers yesterday). So fine, I guess.

**Comment by jessluls** [comment]
strange! let us know if you encounter this again. looks like some of the text nodes weren't showing up. glad to know it's fine now.
