### ISSUE TITLE
Term 2 - EKF - #17 | Expected result missing a row

### ISSUE THREAD

**Issue by jpthalman** [udacity/sdc-issue-reports#686]
The expected result only has 6 rows, when it should have 7.

**Comment by andrewpaster** [comment]
Hi, I realize you posted this awhile back. 

Can you send a link or mention the specific concept title? 

EKF #17 for me is the "Multivariate Taylor Series Expansion", which doesn't seem to be the part you're referring to.

**Comment by andrewpaster** [comment]
Oh nevermind, I see what you're referring to. It's in the UKF lecture.

**Comment by andrewpaster** [comment]
Okay, it's fixed. The last row in expected results had row 6 and row 7 combined onto one line. Now they're separated.
