### ISSUE TITLE
Bug in HOG subsampling.

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#687]
A student pointed this out on the forum. I haven't verified it. See this post https://discussions.udacity.com/t/hog-sub-sampling-window-search/235413/12

Apparently this,

nblocks_per_window = window // pix_per_cell - 1

needs to be changed to:

nblocks_per_window = window // pix_per_cell - cells_per_block + 1

**Comment by boulderZ** [comment]
I think it should be `cell_per_block` not `cells_per_block`.  `cells_per_block' is a tuple argument for the hog function = `(cell_per_block,cell_per_block)`

**Comment by LucFrachon** [comment]
I originally suggested the correction in the forum post linked above. boulderZ is right, the correct code is 
`nblocks_per_window = window // pix_per_cell - cell_per_block  + 1`

Apologies for the typo.

This code is located is project 5,  lecture 35 "Hog sub-sampling window search" (https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/fd66c083-4ccb-4fe3-bda1-c29db76f50a0/concepts/c3e815c7-1794-4854-8842-5d7b96276642#) in the code terminal, `hog_subsample.py`, line 41.

**Comment by advaitha** [comment]
I changed the line to nblocks_per_window = window // pix_per_cell - cell_per_block + 1 but setting a start and stop value for x is not working after the change also

**Comment by swwelch** [comment]
Hi All,

It looks like the code there was written to work with block size of 2 and not with other block sizes. I've corrected that code and also changed the following two lines:
```
    nxblocks = (ch1.shape[1] // pix_per_cell) - cell_per_block + 1
    nyblocks = (ch1.shape[0] // pix_per_cell) - cell_per_block + 1 
```
