### ISSUE TITLE
Provide resources to run exercise locally

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#688]
Please consider providing necessary files so we can also run the exercise in our own environment: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/ae58b4d0-b909-4f4b-9332-67d80a1b4029

e.g. on GitHub. Running the program in the web interface is great to have an automated unit test, but there is no debugger, and trying to debug in the web interface is very inefficient and frustrating.

Of course we can copy and paste the source code, but we need additional resources, i.e. wide_dist_pickle.p and test_image2.png

**Comment by jessluls** [comment]
Thanks for raising this - we're looking into it.
