### ISSUE TITLE
Error in video Advanced Lane Finding > 10. Calibrating Your Camera

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#689]
I believe there is an error in the video at 1:27, bottom-right coordinates should read (6,4,0) instead of (7,5,0).

Link to the lesson: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/a30f45cb-c1c0-482c-8e78-a26604841ec0

Link to the video: 
https://www.youtube.com/watch?v=lA-I22LtvD4

**Comment by baumanab** [comment]
Thank you for bringing this up.  This looks correct to me as the point is 7 corners over and 5 corners down from the origin.  The confusion may be that the corner is one move away from the edge.  We don't count the edges, just the corners.   Does that make sense?  If this doesn't seem correct or if I missed something, we can discuss further and potentially re-open the issue.

**Comment by baumanab** [comment]
Actually, I now realize I am mistaken.  If we are using 0 indexing (which we are in the origin corner), the final corner is (6,4,0).  I will make a note of this.
