### ISSUE TITLE
Add clarification for value returned by cv2.findChessboardCorners()

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#690]
In lesson Advanced Lane Finding > 10. Calibrating Your Camera, consider adding some information on how 

ret, corners = cv2.findChessboardCorners(gray, (8,6), None)

returns the list of found corners, as it is not  intuitive, and OpenCV 3.2 documentation doesn't detail it. Variable corners has shape (48, 1, 2); one could do 

corners = np.squeeze(corners)

and obtain an array of shape (48,2), which now  has one entry per corner, each entry with the (x,y) coordinates of the corner.

**Comment by jessluls** [comment]
Thanks for the suggestion but we want students to know how to use the OpenCV functions directly so we'll leave it as is.
