### ISSUE TITLE
Term2 KF: material from AI for Robotics have severe visualization issues in quizzes

### ISSUE THREAD

**Issue by ricgu8086** [udacity/sdc-issue-reports#691]
It's almost impossible to complete these quizzes with this bug.

https://s17.postimg.org/i7ut3kk67/bug1.png
https://s2.postimg.org/5ni9zpduh/bug2.png

**Comment by baumanab** [comment]
Thank you for reporting this.  It looks like all the quiz images are resolving.  If this is not the case please let us know.  If you do find these or other issues, would you mind linking the pages in question?
