### ISSUE TITLE
Do not use `unsigned int` as loop variable in C++ code exercises

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#693]
In the coding exercises of the "Markov Localization" lesson, e.g. "20. Coding II: Implement the Motion Model" the loop variable in for loops is often declared as `unsigned int`. I think this teaches students a bad practice, as the use of `unsigned` for "non-negative integers" can lead to subtle and hard to find bugs. 

From the google code style guide:
"You should not use the unsigned integer types such as uint32_t, unless there is a valid reason such as representing a bit pattern rather than a number, or you need defined overflow modulo 2^N. In particular, do not use unsigned types to say a number will never be negative. Instead, use assertions for this."

Reference:
- http://wesmckinney.com/blog/avoid-unsigned-integers/
- https://google.github.io/styleguide/cppguide.html

**Comment by awbrown90** [comment]
@WolfgangSteiner I agree with that style and made the modifications in the quiz
