### ISSUE TITLE
T2:L11:S13: Wrong formatting in equations

### ISSUE THREAD

**Issue by WolfgangSteiner** [udacity/sdc-issue-reports#694]
In 13. Markov Assumption for Motion Model: Quiz:
It should be z_{1:t-1}, u_{1:t-1} etc.

<img width="983" alt="bildschirmfoto 2017-04-09 um 20 06 51" src="https://cloud.githubusercontent.com/assets/1871474/24840184/b53bc616-1d68-11e7-8d1e-ca934a3aa423.png">

**Comment by swwelch** [comment]
Thanks, should be fixed now!
