### ISSUE TITLE
No access to Carnd discussion group

### ISSUE THREAD

**Issue by jtryan** [udacity/sdc-issue-reports#695]
I cannot access this URL: https://discussions.udacity.com/t/numerical-instability-of-the-implementation/230449.

I should have access to a self driving car Nd group at discussions.udacity.com yet I do not. This is a problem.

**Comment by swwelch** [comment]
Hi @jtryan, it looks like you have access now. If that is not the case, please email selfdrivingcar-support@udacity.com, and they should be able to help you with account problems.
