### ISSUE TITLE
t2.l07.s20 subscript

### ISSUE THREAD

**Issue by babo** [udacity/sdc-issue-reports#697]
At the Helpful Equations part the subscript of ν
​ψ ,k is not formatted properly.

**Comment by brahmwindeler** [comment]
There are a few issues. The 'k' in νa,k is not subscripted in the 6 instances, and the 'ψ,k' is not subscripted for νψ,k in the 4 instances.

Additionally, the dot over the ψ in vk/ψk is so close to the fraction divider that it is easy to miss.

<img width="609" alt="udacity-carnd-t2-l7-s20" src="https://cloud.githubusercontent.com/assets/1576588/25775885/cd138a60-327d-11e7-819f-1e187fbecb76.png">

**Comment by swwelch** [comment]
Thanks, should be fixed now!
