### ISSUE TITLE
Lesson 5(Radar Measurements) mistake

### ISSUE THREAD

**Issue by tralpha** [udacity/sdc-issue-reports#698]
- Meanwhile, there is a couple of typos at the link https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/3612b91d-9c33-47ad-8067-a572a6c93837/concepts/f4a8731d-ed4e-4f54-9ca4-6c5a5b9b3d34 . The first sentence that begins "The range, (ρ), is the distance to the pedestrian is..." ends with py ​2). The "y" should be a subscript instead of a multiplier.
- The second typo on the same page.  In the sentence near the end that begins with "The scalar projection of the velocity vector" the equation shows product of vectors v and p. Since they both have dimension 2x1, they cannot be multiplied. Instead the first vector must be transposed. Is there a better way to report typos? Let me know you have any questions.

**Comment by andrewpaster** [comment]
Hey, thanks for catching these. Yes, waffle board is the place to report typos. 

I fixed the issues:
- incomplete sentence
- subscript y
- transposed the v matrix
