### ISSUE TITLE
Quiz: TensorFlow Input clarification

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#7]
In this lesson it is said: "If the tensor data type does not match the data type in feed_dict, then TensorFlow will throw the error “ValueError: invalid literal for...”."
Actually error will not be raised if data type in feed_dict can be casted to tensor data type. For example "123" value will work in example provided in this lesson.

At least in my configuration.

https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/a222f778-c0aa-45f0-97bc-7b3caf940f5b

**Comment by rm51** [comment]
Also it says Change line 6, so that the code returns the number 123. But it is line 10 that should be changed.

**Comment by Brok-Bucholtz** [comment]
@dalex01 

That's a very good point.  I changed the sentence to:
> If data passed to the feed_dict doesn’t match the tensor type and can’t be casted into the tensor type, you’ll get the error “ValueError: invalid literal for...”.

@rm51 

I changed the sentence to call out the correct line number and added a comment to the code for clarification.

Thanks for your help!
