### ISSUE TITLE
Unclear what KooDNN is in Transfer learning

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#70]
In this video they mention KooDNN or something similar. I turned on subtitles for that part but the subtitles gave a different word each time. Perhaps a note below could be added with the name so we could read more about it. 
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/e12c47b6-316e-4a0b-aae5-2f2c5fcd99f5/concepts/8802cd58-405c-4059-9d77-de446949ad91

**Comment by Brok-Bucholtz** [comment]
@rm51 

Good idea!  I added a link to the official page underneath the video.
