### ISSUE TITLE
Term 1 Project 3 Behavioral Cloning broken link to old forum

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#700]
In the Project:Beharvioral Cloning section:
In the "Further help" section:
Paul Heraty, a student in the October cohort, has written a helpful guide for those of you looking for some hints and advice.

The link to this guide is now broken as there is no access to the old Atalassian forums.

There is a new post in the new forums inspired in the old one that we are using to guide students:

https://discussions.udacity.com/t/cant-access-helpful-guide-from-paul-heraty-oct-cohort/217945/2

**Comment by swwelch** [comment]
Hi! We have the guide saved now as a .pdf, and it is available on the project submission page here: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/project
