### ISSUE TITLE
Term2 Motion Models - Quizz Odometry

### ISSUE THREAD

**Issue by Mornor** [udacity/sdc-issue-reports#701]
In the Quizz, I think the answer: 
"On a road with a lots of turns" should be considered as valid, because due to the differential of the cars, the inners wheels will move slower than the outters wheels, creating error when measuring speed/distance.

**Comment by andrewpaster** [comment]
Hi, I see your point. Thanks for bringing this up. 

A counter argument would be that each wheel as its own odometer sensor. Odometer sensors generally measure the number of times the wheel spun around and then multiply by the tire circumference to figure out distance.

As long as the car doesn't slip on the curves, then the actual distance measured by each wheel will match the actual distance traveled by each wheel. If the left wheel travels a relatively larger distance than the right wheel in time delta_t, then we know the vehicle made a sharp turn to the right. If the left wheel travels a larger distance than the right wheel but not that much greater, then the turn isn't as sharp. 

The number of times each wheel spun around should match the actual distance each wheel traveled. One wheel will spin more times than the other wheel, which is an accurate reflection of how far each wheel traveled.
