### ISSUE TITLE
Content unavailable: behavioral-cloning-cheatsheet

### ISSUE THREAD

**Issue by elfausto** [udacity/sdc-issue-reports#702]
https://carnd-forums.udacity.com/questions/26214464/behavioral-cloning-cheatsheet

**Comment by elfausto** [comment]
Lesson 12: Behavioral Cloning. Item: "Project Behavioral cloning" (last). Link does no longer exist: https://carnd-forums.udacity.com/questions/26214464/behavioral-cloning-cheatsheet

**Comment by swwelch** [comment]
Hi! The content still exits as a .pdf on the project page here: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/project

(see the "Helpful Guide" link)
