### ISSUE TITLE
Need sigmoid_prime derivation in notes

### ISSUE THREAD

**Issue by Azam77** [udacity/sdc-issue-reports#703]
For the sake of clarity for the students, I highly recommend we post the derivation in the course notes to help explain how sigmoid_prime appears the way it does in the code-form.

**Comment by Azam77** [comment]
A good derivation of sigmoid_prime is here:

link: http://math.stackexchange.com/questions/78575/derivative-of-sigmoid-function-sigma-x-frac11e-x/1225116#1225116

**Comment by jessluls** [comment]
Thanks for the feedback! we'll take it into consideration.
