### ISSUE TITLE
Rubric Missing for Project Unscented Kalman Filters

### ISSUE THREAD

**Issue by kegan** [udacity/sdc-issue-reports#705]
The project rubric for Term 2 - Project 2 (Unscented Kalman Filters) is no longer available or accessible.

Student unable to check if they pass the rubric or  not, if they cannot see the rubric.

**Comment by jwdunn1** [comment]
Is this the missing link? UKF rubric link: https://review.udacity.com/#!/rubrics/783/view

**Comment by kegan** [comment]
The link is accessible. But it is not found in the project page in Udacity classroom (or anywhere else).

**Comment by jwdunn1** [comment]
The link is now back on the project page. This item should be closed.
