### ISSUE TITLE
T2.L7.14 Several Subscripts Incorrect

### ISSUE THREAD

**Issue by jwdunn1** [udacity/sdc-issue-reports#707]
In the Helpful Equations: third, and fourth lines:
The subscript should read x, not k.
"is the second through n​<sub>k</sub>+1 column."
should be:
"is the second through n​<sub>x</sub>+1 column."

and

"is the n<sub>k</sub>+2 column through 2n<sub>k</sub>+1 column."
should be:
"is the n<sub>x</sub>+2 column through 2n<sub>x</sub>+1 column."

Finally, 

on the first, third, and fourth lines, all instances of λ + nx need the x subscripted to read λ + n<sub>x</sub>

**Comment by andrewpaster** [comment]
Hi, thanks for catching these and also being really clear about what needed changes. You can see the changes here: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/daf3dee8-7117-48e8-a27a-fc4769d2b954/concepts/0b64ec4f-eea0-47b5-9111-365eb7f71f89
