### ISSUE TITLE
Intro to NN 19.Backprop: auto-grader should accept column vector for delta_w_h_o

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#708]
In the back propagation quiz (section 19 of Intro to Neural Networks), the grader accepts this as correct:
```
delta_w_h_o = learnrate * del_err_output * hidden_layer_output
```
but flags this as incorrect:
```
delta_w_h_o = learnrate * del_err_output * hidden_layer_output[:,None]
```

The output is:
```
Change in weights for hidden layer to output layer:
[[ 0.00804047]
 [ 0.00555918]]
Change in weights for input layer to hidden layer:
[[  1.77005547e-04  -5.11178506e-04]
 [  3.54011093e-05  -1.02235701e-04]
 [ -7.08022187e-05   2.04471402e-04]]

delta_w_h_o is wrong. delta_w_h_o should be [0.00804047, 0.00555918]
```

I suggest changing the grader to accept the column vector too.  

I think using the same code format (converting the input to the layer into a column vector) even when the `del_err_output` is just a vector of length 1, makes the notation more consistent, so it should also be accepted as a correct answer.

**Comment by jessluls** [comment]
Thanks for the feedback! We'll look into it.
