### ISSUE TITLE
Intro to NN 19. back prop: w and x are flipped when formula is written out with real numbers

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#709]
The first line in the example:
h=∑iwixi
​​ =0.1×0.4−0.2×0.3=−0.02

Should be written as weight * input for both terms, so it should be:
h=∑iwixi
​​ =0.4×0.1−0.2×0.3=−0.02

**Comment by andrewpaster** [comment]
Thanks for catching this and letting us know. I fixed it in the classroom.
