### ISSUE TITLE
Term 2 Deadline is No Longer Shown in New Udacity Classroom

### ISSUE THREAD

**Issue by kegan** [udacity/sdc-issue-reports#710]
The new Udacity Classroom does not show Term 2 end date.

**Comment by jessluls** [comment]
Thanks for the feedback! We're hoping to get this resolved soon. In the mean time, you can reference deadlines here: https://docs.google.com/spreadsheets/d/12ipd3BmKD5aaCaKOtuBsQ6Bh6yM7TQ99uO5SxxawoQo/edit#gid=0
