### ISSUE TITLE
Miniflow: 6. Forward Prop solution: discussion of initialization of non-Input Nodes shows initialization of Input Nodes

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#711]
In the Miniflow 6 "Forward Propagation solution", the text says that Node subclasses that are not of type Input are not set using the forward method, but within topological sort.  It follows this statement with a section of code that checks if a Node is an instance of Input, and if true, sets its value using the feed_dict dictionary.

I think the piece of code doesn't answer the question of how non-Input Node subclasses get their values set, because the code only sets the Node's value if it is an instance of subclass Input.  Here's the original text below:
***********************************************************
For the Input node, the forward method appears to set the value.

That's not the case with other node subclasses, though. For those subclasses, the value is set when you run topological_sort. See here:
```
def topological_sort(feed_dict):
    ...
    if isinstance(n, Input):
        n.value = feed_dict[n]
    ...
```

**Comment by baumanab** [comment]
Thank you for reporting this.  It looks like the content has been updated since this issue was opened.
