### ISSUE TITLE
Miniflow: 7. Learning and Loss: refers to Charles and Michael

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#712]
This text may need to be updated, since I don't see Charles and Michael (Georgia Tech professors) in previous lessons of the SDC.

"Think back to Neural Networks lesson with Charles and Michael. "

**Comment by e7dud7e** [comment]
Maybe replace with "Luis and Matt"?

**Comment by baumanab** [comment]
Thank you for bringing this to our attention.  This content has been updated.
