### ISSUE TITLE
Kalman Tracker Tool Not Working: no realtime simulation - only one step displayed

### ISSUE THREAD

**Issue by qqquan** [udacity/sdc-issue-reports#713]

**Comment by qqquan** [comment]
please refer to the following link for description:
https://discussions.udacity.com/t/visualization-tool-not-working-no-realtime-simulation-only-one-step-displayed/237547

**Comment by qqquan** [comment]
Following the instruction at the 4th step, I expected an 8-pattern displayed, but I only saw a dot drawn.
The record folder is the same as the python script and the compiled file. 
In that folder, there are data_in.txt and data_out.txt. Both text file have only one line of data inside.

**Comment by jwdunn1** [comment]
What platform are you on? It works perfectly on Windows 10.

**Comment by awbrown90** [comment]
@qqquan are you sure that the path is correct for kalman_tracker.py? python kalman_tracker.py <path_to_compiled_executable> (which will be ./build/ExtendedKF with the current cmake config)
