### ISSUE TITLE
SDC nanodegree: glossary / lesson summaries / cheat sheets

### ISSUE THREAD

**Issue by tsekulski** [udacity/sdc-issue-reports#714]
Not sure if this is the right place to raise this topic, but could you guys consider to add lesson summaries / cheat sheets / term glossary to the SDC nanodegree program? Now when I come across a term (e.g. "loss" or "cross entropy") and I don't exactly remember its definition / formula, then I need to (1) try to remember when the term was introduced for the first time and (b) very often watch an entire video to find that one slide with the formula. Obviously this is not efficient. A glossary or even better short lesson summaries with key concepts would be extremely helpful!

**Comment by sunflora** [comment]
Great idea!  I'd love to see some kind of summaries / cheat sheets / term glossary as well!

**Comment by jessluls** [comment]
Thanks for the feedback! We'll consider it.
