### ISSUE TITLE
Miniflow 13. backprop code comment: replace "insures" with "ensures"

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#716]
In the MSE class, forward function, the comment:
```
 # Making both arrays (3,1) insures the result is (3,1) and does
```
Replace "insures" with "ensures".

from (translegal site)[https://www.translegal.com/common-mistakes/ensure-vs-insure]

To ensure that something will be done means to make it certain to happen. “When amending the contract, the lawyer ensured that her client received a better deal.” To insure someone or something means to protect the person or object against risk by regularly paying an insurance company a sum of money.

**Comment by baumanab** [comment]
Thanks for pointing this out and for explaining the differences in usage.  The comment has been updated to use "ensures."
