### ISSUE TITLE
Calculate Error section in Implementation on Particle Filter doesn't provide the correct formula

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#718]
It looks like error_best = sqrt(magnitude(pi* - g)) is the combination of sqrt((xi* - xg)^2 + (yi* - yg)^2) and sqrt((theta_i* - theta_g)^2) = abs(theta_i* - theta_g). However it was not clear from the lesson.

**Comment by awbrown90** [comment]
Thanks for the feedback @deniskrut, I got that added in.
