### ISSUE TITLE
Transformations and Associations in the Implementation of Particle Filter does not clarify where the car is

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#719]
The task instructs to convert observations from the car coordinate system to the map coordinate system. Car is drawn in red (as marked on image), so I was trying to convert from red particle position coordinate system to the map coordinate system. In actuality I had to convert from blue P particle coordinate system to the map coordinate system. This was not clear form the instruction.

**Comment by awbrown90** [comment]
@deniskrut thanks for the feedback I will see if I can't help clear that up
