### ISSUE TITLE
Miniflow lecture notes, error in gradient descend 2.

### ISSUE THREAD

**Issue by vxy10** [udacity/sdc-issue-reports#72]
In the gradient descent 2, the variable names are mixed up. In equation 5, x stands for input, and output y is a function of W and b. In the following equations, the notation is changed and x- is taken as the parameters that is varied. So equation 9 onwards, derivative must be taken with respect to W and b, not x. Equations 9, 10, 11 and 12 are incorrect because it assumes x is the parameter we are optimizing for, not W or b. 

Link: https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/f511ba3f-3262-4bc2-98c8-61d38a7114fe

**Comment by llSourcell** [comment]
Thanks!

**Comment by vxy10** [comment]
Are you siraj from sirajology

**Comment by domluna** [comment]
Made a fix.
