### ISSUE TITLE
RMSE(theta) = pi/8 is incorrect in the Calculating error section of Implementation of Particle filter

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#720]
It looks like correct answer says that RMSE(theta) = pi/8. However, this seem to be incorrect, and the correct answer meant to be pi/16. https://discussions.udacity.com/t/implementation-of-a-particle-filter-calculate-error-answer-incorrect/237043

**Comment by awbrown90** [comment]
@deniskrut yes you are right. I  corrected the answer in the classroom
