### ISSUE TITLE
Formula for Particle's Final weight in Transforms and Associations in Implementation of particle filter is incorrect

### ISSUE THREAD

**Issue by deniskrut** [udacity/sdc-issue-reports#721]
Standard deviation subscript should be x rather then z.

**Comment by deniskrut** [comment]
If formula is correct, then what does standard deviation of z means?

**Comment by awbrown90** [comment]
Hi @deniskrut, where are you seeing the z notation, I only see x and y in the formual

**Comment by deniskrut** [comment]
@awbrown90 formula indeed has an X there, however it is not visible on conventional monitor with ~96 dots per inch. Maybe you can make formula a little bigger?

See a screen shot below. Subscript in the first denominator is easy to confuse with z.
![Screen shot](https://cloud.githubusercontent.com/assets/183481/25465459/3b362774-2ab7-11e7-9d44-32d1e69b5e9f.png)

**Comment by ChrisShepherd81** [comment]
Besides the display problem there's might be still an error in evaluating the correct values.

Kostas Oreopoulos 1:15 PM
In Lesson 14... Calculating Final Weights...
I am doing something wrong and I cannot find whatCalculating OBS1 Multivariate-Gaussian ProbabilityTOBS1 (6,3)... associated landmark L1(5,3)so P(6,3) = 1/(2pi*0.3^2) * exp(- [(6-5)^2/2*0.3^2 + 0]) = 0.00683So I enter 6.83E-3 and it says wrong.What am I doing wrong...?

https://carnd.slack.com/archives/C4TSP7BFU/p1492686938037418
