### ISSUE TITLE
Allow Header File Submission for Localization Project

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#725]
for the localization project it doesn’t make sense that only particle_filter.cpp can be submitted. I changed the method signature for dataAssociation and so I modified particle_filter.h. I understand that I shouldn’t modify the other files, or need to add new files, but shouldn’t I be able to modify the header for a function that isn’t even evaluated?

**Comment by baumanab** [comment]
Thanks for the enhancement suggestion.  This has been addressed and students can now submit multiple files and/or a repo.
