### ISSUE TITLE
UKF Augmentation Assignment 1 typo

### ISSUE THREAD

**Issue by agileminor** [udacity/sdc-issue-reports#726]
In term 2, Lesson7, step 17 Augmented Assignment 1, the cheat sheet has "x.topLeftCorner( (y_size, y_size) )", so an example would be "x.topLeftCorner( (7,7) )". That is incorrect - correct call is "x.topLeftCorner( y_size, y_size)", i.e. "x.topLeftCorner( 7, 7)" - one set of brackets, not two.

**Comment by hq-jiang** [comment]
Also, I think the head() function only applies to vectors.

**Comment by baumanab** [comment]
Good catch!  This has been updated.
