### ISSUE TITLE
Strange behavior of visualization tool

### ISSUE THREAD

**Issue by YCSU** [udacity/sdc-issue-reports#727]
Visualization tool gives wrong result with the measurements from Radar

please check the discussion for details: 

https://discussions.udacity.com/t/weird-behavior-of-visualization-tool/240945

My platform is lubuntu 16.10 with make 4.1, cmake 3.5.2, g++ 6.2.0.

**Comment by awbrown90** [comment]
@YCSU if you could send me your kalman filter code to aaron.brown@udacity.com I could investigate this issue further. Thanks

**Comment by YCSU** [comment]
I sent the code. Hope it helps! Thanks

**Comment by awbrown90** [comment]
Thanks, YCSU, I will try it out. I also wanted to let you know that the latest visualizer updates have been posted here, https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/6b343866-ff39-4ab7-9c1e-281214df6099. I think this will fix a number of bugs that the first visualizer was having.
