### ISSUE TITLE
Extended Kalman Filter Project Dependencies for Windows

### ISSUE THREAD

**Issue by avshepelev** [udacity/sdc-issue-reports#728]
The instructions
https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/blob/master/README.md
specify make version >= 4.1, However, the Windows instruction link points to an installation file for version 3.81

**Comment by baumanab** [comment]
duplicated in #836

**Comment by baumanab** [comment]
Thanks for pointing this out.  A note has been added to EKF and UKF resources pages and repository READMEs.
