### ISSUE TITLE
Term 2: Markov Localization

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#729]
There is no data to implement the coding exercises. Can you put the data for examples 01/02/03/04 so we can implement the coding exercises?

I submitted this request a couple weeks ago too but no avail.

Amit

**Comment by baumanab** [comment]
Thank you for helping us track this.  Currently, the only practical workaround is the solution provided [here](https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750).  Please let us know if this does not work for you.
