### ISSUE TITLE
Cholesky Decomposition

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/sdc-issue-reports#730]
Please provide more info on Cholesky decomposition and calculate square root of P MatrixXd A = P.llt().matrixL(); in the UKF lessons.

**Comment by ricardo-jmnez** [comment]
I agree with this. Particularly: 

1.	Lesson 7.14 Generating Sigma points. In the Instructor Notes’ section Helpful Equations and resources: it would be helpful to add a link to a reference explaining the Cholesky decomposition, Wikipedia may be just fine, and another one for the  Eigen Library reference to Cholesky: https://eigen.tuxfamily.org/dox/classEigen_1_1LLT.html

It would also be useful, but not necessary, to note that the algorithm used in the quiz ( P.llt().matrixL() )produces the lower triangular matrix L of the matrix P such that P = L*L^. This may be useful for people who know what the decomposition does or/and want to code the function using a different library.

**Comment by baumanab** [comment]
The instructor notes have been updated, thanks for help.
