### ISSUE TITLE
Quiz-Answer

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/sdc-issue-reports#731]
I have noticed there's no reset button for term 2's quizzes. Is it possible for the multiple choice quiz's answer to be reset automatically or have reset button? Whenever I revisit the lessons, quizzes are already marked with answer, that means I see the answer without even trying to solve after the first sitting.

**Comment by jessluls** [comment]
Thanks for the feedback! We'll file your feature request with our classroom team.
