### ISSUE TITLE
Transformations and Associations Probability Answer Check is Wrong

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#732]
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/1da01dfe-6653-4d2d-b2e4-325740fc7156#

For multivariate gaussian distirbution for OBS1 it needs to be 6.8364E-3 but says my answer is wrong. I think there is a mistak. Same for OBS2/3 and their product.

**Comment by Deborah-Digges** [comment]
+1. This is really frustrating. Please fix it

**Comment by jessluls** [comment]
According to the quiz, you'll need to write your answer in scientific notation with an accuracy of two decimal places, for example 3.14E-15. This is why your answer isn't being accepted.
