### ISSUE TITLE
Two different orders to row, col, ch

### ISSUE THREAD

**Issue by properGrammar** [udacity/sdc-issue-reports#733]
Order of the arguments of input_shape change from (160, 320, 3) to (3, 8, 320).

former 
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/d76493fa-8061-44ab-b122-bc7fa25cd270

latter 
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/46a70500-493e-4057-a78e-b3075933709d/concepts/b602658e-8a68-44e5-9f0b-dfa746a0cc1a

**Comment by baumanab** [comment]
Thanks for letting us know about this.  The first instance has been updated to (ch, row, col), per Keras requirements.
