### ISSUE TITLE
Lesson 14 (Particle Filter) - lecture 13

### ISSUE THREAD

**Issue by mcavaioni** [udacity/sdc-issue-reports#734]
When calculating the OBS1 Multivariate-Gaussian Probability the value I get (and many other students get) is 6.84E-03 but when clicking "submit" it says "wrong answer".
Please verify that the message is correct

**Comment by jwdunn1** [comment]
I can confirm this issue. I am unable to enter the correct answer stated above. The system responds with "Try Again"

**Comment by awbrown90** [comment]
@mcavaioni thank you for catching that, no was a mix up between * and / in the script that did the calculations and all 4 answers have now been corrected

**Comment by mvpcom** [comment]
This error is still there, what is the problem now?

**Comment by awbrown90** [comment]
I believe it should be correct now, in which part of the calculation is the error being seen?

**Comment by mvpcom** [comment]
For OBS1, OBS2 Multivariate-Gaussian Probability and Particle's Final weight the same error "Try Again" is still there for the correct answer. 
![1](https://cloud.githubusercontent.com/assets/3529325/26101937/36dde388-3a48-11e7-9a47-28fef0ec8681.jpg)

**Comment by awbrown90** [comment]
The grader was only accepting 6.84E-3, I just changed it so it now accepts both 6.84E-03 and 6.84E-3. Thanks for catching that.
