### ISSUE TITLE
Add block-norm parameter to prevent deprecation warnings

### ISSUE THREAD

**Issue by chrisxed** [udacity/sdc-issue-reports#736]

**Comment by chrisxed** [comment]
P5:Lesson 20 "scikit-image HOG" - I think it would be good to break up the long line demonstrating the hog() function. It goes way off the screen for me. Especially since you should also add block_norm='L2-Hys' as one of the parameters to the function. This will prevent annoying deprecation warnings. :

**Comment by baumanab** [comment]
Thank you for the feedback.  This has now been addressed.
