### ISSUE TITLE
Self-Driving Car Engineer Nanodegree Free Preview

### ISSUE THREAD

**Issue by Kjeanclaude** [udacity/sdc-issue-reports#737]
Just a typo.
In the Lesson2 : Finding lane lines, part11: Canny to Detect Lane Lines lesson
28 = 256 should be 2^8 = 256
in the line "an 8-bit image, so each pixel can take 28 = 256 possible values.".

**Comment by jessluls** [comment]
Thanks! What's weird is our markdown is working in our classroom backend, but doesn't display on the front end. So I just changed it to 2^8 as you suggested and removed the superscript :).
