### ISSUE TITLE
Duplicated Text in T2 L11 Markov Localisation Part 11

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#738]
Section: Term 2 L11 Markov Localisation -> 11. Applying Law of Total Probability

> Applying Law of Total Probability
> What kind of rule or law can we use for: p(x_t...m) to help us with the fact that we have no prior information about where the car was at the previous time step x_t-1?
> **to help us with the fact that we have no prior information about where the car was at the previous time step x_t-1?**

The last line is a repeat of the latter part of the first paragraph.

**Comment by jessluls** [comment]
fixed! Thanks!
