### ISSUE TITLE
Video and audio out of sync (T2 L11 Markov Localisation Part 17)

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#739]
https://www.youtube.com/watch?v=29Dzn6DsfKY 
The video appears to be 6 seconds ahead of the audio.

Watch from 0:10+: the cars move before Maximilian says 'the car could be here, here, here and so on.'

**Comment by jessluls** [comment]
thanks for the heads up! reporting to our video team to help edit the animations.

**Comment by justineudacity** [comment]
video fixed and uploaded.
