### ISSUE TITLE
Miniflow: Implementing backpropogation quiz: Error in expected output

### ISSUE THREAD

**Issue by vxy10** [udacity/sdc-issue-reports#74]
The part where it says, you should see an output, the true gradient is different. Infact the different gradient solution is accepted as correct solution by the quiz. 

"""
You should see a list of gradients on the weights and bias that looks like:
[array([[  6.08973702e-08,   6.93800843e-02],
       [  1.21794740e-07,   1.38760169e-01]]), array([ -6.08973702e-08,  -6.93800843e-02])]
"""

'''
[array([[ 6.79488741e-18, -2.67826355e-12], [ 1.35897748e-17, -5.35652711e-12]]), array([ -6.79488741e-18, 2.67826355e-12])]
'''

**Comment by cameronwp** [comment]
The grading code uses random inputs, weights and biases. The gradients should look totally different :)
