### ISSUE TITLE
T1.AdvancedLaneFinding.10 (x,y) coords off

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#740]
In lesson 10 of advanced lane finding, in the video at minute 1:25 the bottom right coordinate is labeled as (7,5,0).  However, given the position of (0,0,0) it should be (6,4,0).  

The range of x at the top of the image should also be -1 through 7 and range of y be -1 through 5.

**Comment by jessluls** [comment]
Can you send us a link?

**Comment by troyjlee** [comment]
http://www.youtube.com/watch?v=lA-I22LtvD4&t=1m25s

**Comment by baumanab** [comment]
Thanks for reporting this.  If we are using 0 indexing (which we are in the origin corner), the final corner is (6,4,0).  I will make a note of this.
