### ISSUE TITLE
T1.AdvancedLaneFinding.10 height width issue

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#741]
In the text for lesson 10 it says: "The shape of the image, which is passed into the calibrateCamera function, is just the height and width of the image. One way to retrieve these values is by retrieving them from the grayscale image shape array gray.shape[::-1]. This returns the image height and width in pixel values like (960, 1280)."

gray.shape[::-1] will return (width,height) of an image, not (height,width).  I think it would be good to be more explicit here why you use gray.shape[::-1], i.e. because calibrateCamera expects (width, height) instead of (height,width).

(Is this true?  The docs weren't explicit and I tried passing both (width, height) and (height,width) as arguments to calibrateCamera and they gave the same answer).

The text below this also needs to made consistent: img.shape[0:2] will not return the same answer as gray.shape[::-1], perhaps you want img.shape[1::-1].

**Comment by jessluls** [comment]
Can you send us a link?

**Comment by troyjlee** [comment]
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/a30f45cb-c1c0-482c-8e78-a26604841ec0

**Comment by baumanab** [comment]
Thanks for pointing this out.  I'm looking into this.  It looks like the function actually needs the image size (total pixels) and so it shouldn't matter which order the height and width are passed.  The documentation is not clear.  

# related to #793

**Comment by baumanab** [comment]
Per comments in #793 

> It's not clear from the [documentation and examples](http://docs.opencv.org/trunk/dc/dbb/tutorial_py_calibration.html) why the reversed array is used.  The errors above are corrected.  We are staying with the reversed array, for now, to maintain alignment with the documentation and examples.

Regarding img.shape[0:2] this is referring to a 3D image and slicing out depth (last element of the shape array) and yes, this would not give the equivalent to gray.shape[::-1], it would be the reverse.  I've updated the text to the reversed slice you suggested.  Thank you!
