### ISSUE TITLE
T2 L14.12 Implementation of a Particle Filter: Error in Quiz Answer

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#743]
**Section**: Term 2 L14.12 Implementation of a Particle Filter -> Calculating Error:

The correct quiz answer is given as RMSE(x, y)=.63 RMSE(theta) = **pi/8**. But in the question the ground truth is pi/16 and the best particle's position is pi/8. RMSE(theta) is thus sqrt((pi/8-pi/16)^2)) = (pi/8-pi/16) = pi/16, not pi/8. 

So it seems that the answer should be RMSE(x, y)=.63 RMSE(theta) = **pi/16**.

**Comment by awbrown90** [comment]
Hi @jessicayung, yes you are right. I corrected the answer in the classroom
