### ISSUE TITLE
C++ Programming: Lesson 1-24 to 1-26 formatting using setw function

### ISSUE THREAD

**Issue by gmpatil** [udacity/sdc-issue-reports#744]
Lesson and quizzes gives the impression that setw function expression are applied from left to right. 
In below examples, "Ints" column does not use all 15 character width. Misalignment can be easily seen by adding 99 to int variable aaa instead of 9. Which causes 3rd row columns to mis-align due to 3rd row int column taking additional character. 

lesson 24
`std::cout<<"Ints"<<std::setw(15)<<"Floats"<<std::setw(15)<<"Doubles"<< "\n";`  

Lesson 26.
`     std::cout<< aaa;
     std::cout<< std::setw(12)<< bbb;
     std::cout<< std::setw(10)<< ccc << "\n\n"; `

`int aaa = aa + 99;`

Solution should have setw expression appear left of the expression who's width being set.
May be something like below:
`    cout << setw(10) << "Ints" << setw(10) << "Floats" << setw(10) << "Doubles" << endl; `
`    cout << setw(10) << a << setw(10) << b << setw(10) << c << endl;`
`    cout << setw(10) << aa << setw(10) << bb << setw(10) << cc << endl;`
`    cout << setw(10) << aaa << setw(10) << bbb << setw(10) << ccc << endl;`

**Comment by baumanab** [comment]
Thank you for letting us know. We will bring this to the attention of the content developers for that course.
