### ISSUE TITLE
lesson 14 implementation of a particle filter

### ISSUE THREAD

**Issue by andrewpaster** [udacity/sdc-issue-reports#745]
In "Calculating Error" concept at 1:12. 
https://www.youtube.com/watch?v=HiRrJYZr-0I
https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/cbefd618-0857-4d83-84c8-426662b5f9aa

Students says, "I do not understand this formula. I get the accepted answer by solving the problem myself. The sqrt() needs to be removed for it to make sense to me. In saying that I understand |pi - g| to be the euclidian distance from pi to g".

**Comment by baumanab** [comment]
Thanks for pointing this out.  I can see the source of confusion regarding vector notation and the use of |v|.   We will clarify the intent.

**Comment by baumanab** [comment]
Instructor notes have been added to clarify.
