### ISSUE TITLE
T2.udacity/CarND-Kidnapped-Vehicle-Project C++ compatibility problems

### ISSUE THREAD

**Issue by AndrewGls** [udacity/sdc-issue-reports#747]
Hi, It would be very nice fix the udacity/CarND-Kidnapped-Vehicle-Project project code - to add the #define _USE_MATH_DEFINES before including <math.h> in helper_functions.h file to use the definition of M_PI as minimum. The current version is not cross-platform and is not compiled in VisualStudio. Its is better to replace <math.h> to <cmath> for compatibility with C++.

**Comment by baumanab** [comment]
noting related issues:  https://github.com/udacity/sdc-issue-reports/search?utf8=%E2%9C%93&q=m_pi&type=Issues

**Comment by baumanab** [comment]
Thank you for reporting this.  The following has been added ```helper_functions.h```

```
// for portability of M_PI (Vis Studio, MinGW, etc.)
#ifndef M_PI
const double M_PI = 3.14159265358979323846;
#endif
```
