### ISSUE TITLE
Typo in Backprop video 8.8

### ISSUE THREAD

**Issue by hulleywood** [udacity/sdc-issue-reports#75]
About 1:05 into the Deep Neural Network Backprop video (Lesson 8, Video 80), the update formula at the bottom of the image for w2 should read "w2 <- w2 - a * delta_w2" instead of "w2 -< w2 - a * w2".

**Comment by Brok-Bucholtz** [comment]
@hulleywood 

Thanks for letting us know about the missing delta!  I added this to our sprint backlog and I'll update this issue when it's fixed.

**Comment by Brok-Bucholtz** [comment]
@hulleywood 

I've made a temporary note at the bottom about the missing delta until a new version of the video is uploaded.
