### ISSUE TITLE
Term 1 P2

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/sdc-issue-reports#750]
In term 1's P2, students should be told why the validation accuracy with 93% has been set as the requirement of the project but not the test set.

**Comment by baumanab** [comment]
Thank you for the feedback.  Scoring based on validation is standard ML practice and is covered in the supporting courses.  We could add a note about this if it would be helpful.  Where do you think this would be most effective (where do you think we should add the note)?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
