### ISSUE TITLE
Typo in Correcting for Distortion Lesson

### ISSUE THREAD

**Issue by SealedSaint** [udacity/sdc-issue-reports#751]
In the Advanced Lane Finding project, lesson 11 (Correcting for distortion), there is this typo: "use chessboard images to image points and object points".

It's the second sentence. I assume is should read: "use chessboard images to GET/FIND/OBTAIN image points and object points"

**Comment by baumanab** [comment]
This has been corrected.  Thanks for bringing this to our attention!
