### ISSUE TITLE
Suggestion: Add Confirmation to "Reset Quiz" Button

### ISSUE THREAD

**Issue by ExCodeCowboy** [udacity/sdc-issue-reports#752]

**Comment by ExCodeCowboy** [comment]
Working on the newer C++ coding windows I have lost my work more than once by accidentally clicking on the "reset quiz" button instead of the same colored "test run" button that is directly next to it. I think it needs a confirmation dialog.

**Comment by baumanab** [comment]
I've done this a few times myself.  It's possible that a dialogue box may also become irritating for some students.  Would it be helpful to change one of the button colors?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
