### ISSUE TITLE
More efficient way to measure curvature in meters

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#753]
With reference to

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/40ec78ee-fb7c-4b53-94a8-028c5c60b858/concepts/2f928913-21f6-4611-9055-01744acc344f

to measure the curvature radius you propose to scale every point based on the meters/pixel ratio, and then interpolate those points again. That is unnecessarily complicated and computationally expensive.

Instead, once you have the parabola coefficients in pixels, you can just convert them into meters.

Say the parabola is `x= a*(y**2) +b*y+c`; say `mx` and `my` are the scale for the `x` and `y` axis respectively (in meters/pixel); then the scaled parabola is `x= mx / (my ** 2) *a*(y**2)+(mx/my)*b*y+c`

Much faster and simpler.

**Comment by baumanab** [comment]
That is very clever.  The suggestion has been added to the classroom.
