### ISSUE TITLE
Wrong comments in code for Kidnapped Vehicle Project

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/sdc-issue-reports#754]
particle_filter.h:
-Line 44: @param M is not existent -> remove

main.cpp:
-Line 99: // Predict the vehicle's next state (noiseless) -> Remove "noiseless", since it actually IS with noise - we use the std_pos argument.

particle_filter.cpp
-Line 49: need to switch the minus sign
This comment is misleading. Remove or clarify which coordinate system (left or right handed) is being used for the map and the car.

**Comment by baumanab** [comment]
Thanks for finding and reporting these.  

- particle_filter.h has been updated
- particle_filter.cpp has been updated
- The current state of main.cpp does contain a code block that predicts from noisless control data if the particle filter is not initialized.
