### ISSUE TITLE
Update Lab11.25 solution code to match Keras version in starter kit

### ISSUE THREAD

**Issue by cadenzasong** [udacity/sdc-issue-reports#755]
model.fit(X_train, y_train, epochs=FLAGS.epochs, batch_size=FLAGS.batch_size, validation_data=(X_val, y_val), shuffle=True)

should be

model.fit(X_train, y_train, nb_epoch=FLAGS.epochs, batch_size=FLAGS.batch_size, validation_data=(X_val, y_val), shuffle=True)

**Comment by subodh-malgonde** [comment]
The starter kit has keras `1.2.1` whereas the code in the Lab is according to Keras 2.x API. The argument `epochs` passed to `model.fit` is called `nb_epoch` in Keras 1.2.1.

**Comment by tsekulski** [comment]
...Otherwise when executing python throws the following error (just ran into the same issue):
---------
model.fit(X_train, y_train, batch_size=FLAGS.batch_size, epochs=FLAGS.epochs, validation_data=(X_val, y_val), shuffle=True)
TypeError: fit() got an unexpected keyword argument 'epochs'
---------

**Comment by mvirgo** [comment]
Looks like this actually got fixed back in August with commit `76c362b9ad49e01788365c90864a024f80812818`
