### ISSUE TITLE
L14: Particle Filter - Pseudo code, wrong indexer

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#757]
Within the pseudocode in the video for the second for-loop 'm' is used within the initalization but in the body 'i' is used.

**Comment by baumanab** [comment]
Thanks for letting us know.  This is the resampling step.  The resampling step actually has an outer loop over all particles (range of 0 to length_of_particleArray) and an inner loop that steps through an index (initial index:index_selected).  So, this is actually two different variables.  Does that make sense?  We plan on clarifying elements of this section soon.

**Comment by baumanab** [comment]
We made some changes to clarify this.  We would really appreciate some feedback on how effective the changes are.

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/aeeb6438-ace6-42dc-b26c-629d8d3df9c3

**Comment by ChrisShepherd81** [comment]
Yes, thank you.
