### ISSUE TITLE
Term2 KF: kalman-tracker.py

### ISSUE THREAD

**Issue by pabasarak** [udacity/sdc-issue-reports#758]
there is a typo error in the example code given in the project details.

The name of the pyton file is kalman-tracker.py with a dash"-"

In the example code it mentions the file as
python kalman_tracker.py with an underscore "_"

If you use the example code as it is, python cannot find the py file.

**Comment by baumanab** [comment]
Thank you for bringing this to our attention.  Would you mind clarifying where this error is? I have not yet been able to find it.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
