### ISSUE TITLE
Still getting popup your project is due in one day

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#76]
I already submitted and passed my project. I'm still seeing that popup though. Is that because specifically because I'm a mentor so we're seeing what our students are seeing? Or is it not checking whether we've submitted or not. The popup occurs when looking at the classroom syllabus.

**Comment by swwelch** [comment]
Thanks! I've forwarded this to the engineering team.

**Comment by Brok-Bucholtz** [comment]
Students are also getting an email reminder about project being due despite already completing the project.

**Comment by swwelch** [comment]
Thanks, this has been forwarded to the engineering team and is under investigation.

**Comment by Brok-Bucholtz** [comment]
@rm51 

This is part of the sprint backlog.  I'll update this issue when it's fixed.
