### ISSUE TITLE
Kalman Filter simulator won’t show green markers for UKF

### ISSUE THREAD

**Issue by seya-zero2one** [udacity/sdc-issue-reports#760]

**Comment by seya-zero2one** [comment]
I don't see green markers (triangle icons) on the simulator screen when I run it with UKF with the following command, "python kalman-tracker.py ./UnscentedKF". I see the markers when I run it with EKF with the command, "python kalman-tracker.py ./ExtendedKF".

I found the output format was the issue. Removing the timestamp as the first value solves the problem. If you comment out a line of code in main.cpp like below, it works like a charm.

// timestamp
//out_file_ << measurement_pack_list[k].timestamp_ << "\t"; // pos1 - est

* Note:
  You can find the discussion about this issue on the Self-Driving-Car Forum:
https://discussions.udacity.com/t/kalman-filter-simulator-wont-show-green-markers-for-ukf/243760/3

**Comment by baumanab** [comment]
It looks like this issue has been addressed via updates to the repo and simulator.  Please let us know if this is not the case.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
