### ISSUE TITLE
rsme improve

### ISSUE THREAD

**Issue by youngkil9999** [udacity/sdc-issue-reports#761]
how to improve

**Comment by youngkil9999** [comment]
what value should I change
could I change P or Q,R.
or what should I change.

**Comment by ricgu8086** [comment]
Q and R are given... I would go for P.

Another tip is to try with the 2 datasets provided ("obj_pose-laser-radar-synthetic-input.txt", "sample-laser-radar-measurement-data-1.txt"). Maybe your implementation work better in the other.
