### ISSUE TITLE
Formula is too small to read

### ISSUE THREAD

**Issue by kegan** [udacity/sdc-issue-reports#763]
Some of the formula in Term 2 is too small to read. For example:

![formula](https://cloud.githubusercontent.com/assets/21737/25608547/d7cca8e8-2f4d-11e7-9ff8-2cb62e70524a.png)

**Comment by baumanab** [comment]
Thank you for the suggestion.  Currently, formulas are styled in a consistent manner throughout the classroom and NDs.  Formulas are of sufficient resolution that zooming should be possible without major distortion.   Does that seem like a reasonable work-around?
