### ISSUE TITLE
T2:L14:11 Quiz Transformations and Associations

### ISSUE THREAD

**Issue by kegan** [udacity/sdc-issue-reports#764]
The result for OBS1 Multivariate-Gaussian Probability should be 6.83E-3.

But when submit, it keep saying "Try Again".

Refer also to discussion on this: https://discussions.udacity.com/t/for-the-question-in-lesson14-13-obs1-multivariate-gaussian-probability/239934/12

**Comment by baumanab** [comment]
Thanks for letting us know.  It looks like your result in the discussion is correct 6.84E-3 and this result now passes the quiz.
