### ISSUE TITLE
Gaussian noise to the velocity and the yaw rate aren't taken into an account for localization project.

### ISSUE THREAD

**Issue by jjaviergalvez** [udacity/sdc-issue-reports#765]
On the Term 2, Localization, Lesson 14.6: Prediction Step, Tiffany said: "to account for uncertainty in the control input, you will also add Gaussian noise to the velocity and yaw rate". 

However, in the code of the project, specifically in the `prediction()` function, we are using uncertainty related to GPS instead of uncertainty related to control input. 

Is it an error?

**Comment by baumanab** [comment]
It looks like we are adding noise as described in the video, here:

```c
void ParticleFilter::prediction(double delta_t, double std_pos[], double velocity, double yaw_rate) {
	// TODO: Add measurements to each particle and add random Gaussian noise.
	// NOTE: When adding noise you may find std::normal_distribution and std::default_random_engine useful.
	//  http://en.cppreference.com/w/cpp/numeric/random/normal_distribution
	//  http://www.cplusplus.com/reference/random/default_random_engine/
```

Does that make sense?

**Comment by jjaviergalvez** [comment]
Thanks for the reply. Unfortunately, I still have my doubts, so let me try to explain me better. I agree that we could consider the function that you describe as correct, but the problem comes around the parameter `std_pos[]`. In the particle_filter.h file you can find the description:
```
* @param std_pos[] Array of dimension 3 [standard deviation of x [m], standard deviation of y [m]
     *   standard deviation of yaw [rad]]
```
and the only array that matches this description in the main file is this one:
```
double sigma_pos [3] = {0.3, 0.3, 0.01}; // GPS measurement uncertainty [x [m], y [m], theta [rad]]
```
So, we are using the GPS measurement uncertainty to make the prediction step of the algorithm. I have two reasons to believe that this is wrong. First, remembering a lesson of Sebastian (lesson 10.3) where he introduces an example of robot localization. After the robot moves, the bumps are a little bit flatter because of the uncertainty of the movement due to mechanical issues or road conditions, **not because of the measurement (GPS in the project)**. Secondly, because the statement of Tiffany: "to account for uncertainty in the control input, you will also **add Gaussian noise to the velocity and yaw rate**".

Therefore, I consider that the param `std_pos[]` need to be renamed as `std_ctrl[]` or something like that and in the main.cpp a variable like
```
double sigma_ctrl [2] = {0.3, 0.01};
```
should be provided.

So, or Tiffany statement is wrong, or that code section of the project is wrong or I'm totally confused ;)

Hope this helps.

**Comment by baumanab** [comment]
Thanks for your patience with this.  The reason for adding GPS noise is explained here:  

https://m.youtube.com/watch?v=-3HI3Iw3Z9g&feature=youtu.be&t=1367

Essentially we need to add jitter in the initialization and prediction steps.  Jitter adds noise to a discretized continuous variable to better represent is actual distribution.  This allows us to get a good initial sampling estimate on initialization and to repopulate candidate particles during the resampling step.  This is similar to what we do in Sebastian's lesson (after resampling etc. we still have the same size array, 1000, after we resample), but with GPS noise as the mechanism.  If we didn't add jitter we would end up with copies of the same particle.  Does that help? 

It may be best to continue this conversation with forum mentors.  Does that sound reasonable?

**Comment by sohonisaurabh** [comment]
Hi @baumanab,

I am still not clear on the explanation involving 'jittery'. I watched the project walk through and basically your explanation is the transcript of what said in the video. So didn't help much. Can you share some article, paper on why to add the jittery and what happens if we don't add?

Thanks,
Saurabh

**Comment by baumanab** [comment]
Hi,  sorry I wasn't able to clarify.  The most effective way of getting further explanation for this would be the forums or live help.  Would you mind trying those resources and letting us know how it goes?

**Comment by jjaviergalvez** [comment]
Sorry for the late response. 

I'm in the same situation. The answer didn't help much. 

The question has already been posted ([here](https://discussions.udacity.com/t/gaussian-noise-to-the-velocity-and-the-yaw-rate/244262)) before I opened this issue report. But by the lack of answers and the suggestion of a forum mentor, I asked the question here.

I'm going to share your answer on the forum and perhaps other students can understand from the video and provide a better explanation to others.

Thank you.

**Comment by sohonisaurabh** [comment]
Thanks @baumanab! @jjaviergalvez called out that there was lack of answers and help from mentors in the forums. This was the reason I also thought of connecting with you. Anyway, I hope there will be some explanation in the forums in upcoming days.

Thanks,
Saurabh

**Comment by baumanab** [comment]
Happy to offer whatever help I can.  I'm working on a more cogent explanation that relates directly to the project code.

**Comment by subodh-malgonde** [comment]
@sohonisaurabh Can you check [this post](https://discussions.udacity.com/t/gaussian-noise-to-the-velocity-and-the-yaw-rate/244262/7?u=subodh.malgonde)?

**Comment by sohonisaurabh** [comment]
Thanks @subodh-malgonde! 

@baumanab - We have had a lot of discussion in [this ](https://discussions.udacity.com/t/need-some-conceptual-understanding-w-r-t-introduction-of-noise-in-particle-filters/363981/6 )and [this ](https://discussions.udacity.com/t/gaussian-noise-to-the-velocity-and-the-yaw-rate/244262/7 )post and the doubt is currently settled. However, an update/explanation in the specification w.r.t. noise in prediction step of project code may avoid some confusion.

Thanks for your help!

**Comment by baumanab** [comment]
Sorry I haven't found a solid answer to this yet.  I'm going to speak to a subject matter expert about this next week.  Reopening the issue so it doesn't slip through the cracks.

**Comment by baumanab** [comment]
Hopefully, the response here will be more satisfying. https://discussions.udacity.com/t/need-some-conceptual-understanding-w-r-t-introduction-of-noise-in-particle-filters/363981/7

**Comment by jjaviergalvez** [comment]
Thank you so much @baumanab. It does!
