### ISSUE TITLE
Part 14/Lesson 14 of Term2 (Transformations and Associations) missing solutions

### ISSUE THREAD

**Issue by agileminor** [udacity/sdc-issue-reports#767]
Part 14/Lesson 14 of Term2 (Transformations and Associations) quiz does not give the correct answers, and does not seem to accept any of my guesses.

**Comment by awbrown90** [comment]
@agileminor I just changed the grader so it now accepts a couple of different versions of the answers, such as both 6.84E-3 or 6.84E-03
