### ISSUE TITLE
aws ami missing libgtk2.0-0

### ISSUE THREAD

**Issue by adriantorrie** [udacity/sdc-issue-reports#768]
When attempting

`import cv2` the following error occurs:
> ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Resolution required:
`sudo su -`
`apt-get install libgtk2.0-0`

Others in the forum [have mentioned the issue also](https://discussions.udacity.com/t/importerror-libgtk-x11-2-0-so-0/244471)

**Comment by adriantorrie** [comment]
`source activate carnd-term1`
`conda install opencv`

The above lines fixed it without having to run `apt-get`, so it looks like the module wasn't installed.

    $ conda install opencv
    Fetching package metadata .......
    Solving package specifications: ..........

    Package plan for installation in environment /home/carnd/anaconda3/envs/carnd-term1:

    The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-5.2.0               |                0         1.1 MB
    libxcb-1.12                |                1         1.5 MB
    glib-2.50.2                |                1         5.6 MB
    libxml2-2.9.4              |                0         3.7 MB
    freetype-2.5.5             |                2         2.5 MB
    fontconfig-2.12.1          |                3         429 KB
    pillow-3.4.2               |           py35_0         885 KB
    cairo-1.14.8               |                0         609 KB
    opencv-3.1.0               |      np112py35_1        36.6 MB
    qt-5.6.2                   |                2        44.2 MB
    harfbuzz-0.9.39            |                2         1.2 MB
    pyqt-5.6.0                 |           py35_2         5.4 MB
    matplotlib-2.0.0           |      np112py35_0        10.9 MB
    pango-1.40.3               |                1         938 KB
    ------------------------------------------------------------
                                           Total:       115.5 MB

    The following NEW packages will be INSTALLED:

    dbus:             1.10.10-0                    
    expat:            2.1.0-0                      
    gst-plugins-base: 1.8.0-0                      
    gstreamer:        1.8.0-0                      
    jbig:             2.1-0                        
    libgcc:           5.2.0-0                      
    libxcb:           1.12-1                       
    opencv:           3.1.0-np112py35_1            

    The following packages will be UPDATED:

    cairo:            1.14.6-4          conda-forge --> 1.14.8-0         
    pyqt:             4.11.4-py35_2     conda-forge --> 5.6.0-py35_2     
    qt:               4.8.7-7           conda-forge --> 5.6.2-2          

    The following packages will be SUPERCEDED by a higher-priority channel:

    fontconfig:       2.12.1-4          conda-forge --> 2.12.1-3         
    freetype:         2.7-1             conda-forge --> 2.5.5-2          
    glib:             2.51.4-0          conda-forge --> 2.50.2-1         
    harfbuzz:         1.4.3-0           conda-forge --> 0.9.39-2         
    icu:              58.1-1            conda-forge --> 54.1-0           
    jpeg:             9b-0              conda-forge --> 8d-2             
    libtiff:          4.0.6-7           conda-forge --> 4.0.6-2          
    libxml2:          2.9.4-4           conda-forge --> 2.9.4-0          
    matplotlib:       2.0.0-np112py35_2 conda-forge --> 2.0.0-np112py35_0
    pango:            1.40.4-0          conda-forge --> 1.40.3-1         
    pillow:           4.1.0-py35_0      conda-forge --> 3.4.2-py35_0     

    Proceed ([y]/n)? y

    Pruning fetched packages from the cache ...
    Fetching packages ...
    libgcc-5.2.0-0 100% |##########################################################################################################################################| Time: 0:00:00  46.51 MB/s
    libxcb-1.12-1. 100% |##########################################################################################################################################| Time: 0:00:00  48.29 MB/s
    glib-2.50.2-1. 100% |##########################################################################################################################################| Time: 0:00:00  50.42 MB/s
    libxml2-2.9.4- 100% |##########################################################################################################################################| Time: 0:00:00  50.07 MB/s
    freetype-2.5.5 100% |##########################################################################################################################################| Time: 0:00:00  49.26 MB/s
    fontconfig-2.1 100% |##########################################################################################################################################| Time: 0:00:00  41.20 MB/s
    pillow-3.4.2-p 100% |##########################################################################################################################################| Time: 0:00:00  46.19 MB/s
    cairo-1.14.8-0 100% |##########################################################################################################################################| Time: 0:00:00  44.71 MB/s
    opencv-3.1.0-n 100% |##########################################################################################################################################| Time: 0:00:00  38.91 MB/s
    qt-5.6.2-2.tar 100% |##########################################################################################################################################| Time: 0:00:00  48.19 MB/s
    harfbuzz-0.9.3 100% |##########################################################################################################################################| Time: 0:00:00  46.97 MB/s
    pyqt-5.6.0-py3 100% |##########################################################################################################################################| Time: 0:00:00  48.40 MB/s
    matplotlib-2.0 100% |##########################################################################################################################################| Time: 0:00:00  48.87 MB/s
    pango-1.40.3-1 100% |##########################################################################################################################################| Time: 0:00:00  45.82 MB/s
    Extracting packages ...
    [      COMPLETE      ]|#############################################################################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|#############################################################################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|#############################################################################################################################################################| 100%

**Comment by Azam77** [comment]
Thank you so much for the post! i spent a few hours messing with installing/making opencv on ubuntu and still no luck and now ran into your post and it resolved it!

**Comment by Azam77** [comment]
thanks for posting i was trying to figure this out for 3 hours

**Comment by baumanab** [comment]
Thank you for this information, I have added some notes to the AWS GPU page.

**Comment by yangchunluo** [comment]
have encountered exactly the same problem. thanks for the solution!
