### ISSUE TITLE
T1.AdvancedLaneFinding.L6 Camera Matrix

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#769]
At minute mark 1:04 in the video at the top of the screen it says P ~ Cp.

Usually the camera matrix is taken to map 3D world points to 2D image points, so C should act on P instead of p.   I'm not sure what you wanted to say here, but CP ~ p would make sense, or 
P -> CP ~ p would fit with the 3D versus 2D text below this.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
