### ISSUE TITLE
Miniflow SGD quiz test run does not work

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#77]
I got this error message (earlier the test run worked):

Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_suzpowyqta/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_suzpowyqta/studentMain.py", line 1
SyntaxError: Non-ASCII character '\xe2' in file /tmp/vmuser_suzpowyqta/studentMain.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by cameronwp** [comment]
You should be good now! Something weird happened with copy and paste. Just finished patching it. Let me know if it's still broken.
