### ISSUE TITLE
section 11 transfer learning video 6: "late ott's" meaning is unclear

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#774]
At the start of the video, He says "by the late ott's, the internet...".  I wasn't sure what word he was using.  I am guessing he's referring to the late 2000s time period, but I've never heard the term "ott's" before.  I think this could be clarified with some text at the bottom.  This would help make the lecture more friendly for an international audience.

**Comment by baumanab** [comment]
Thanks for sharing your perspective on this, a note has been added.
