### ISSUE TITLE
T2 Kidnapped Vehicle: vectors passed by value

### ISSUE THREAD

**Issue by cs4nd13** [udacity/sdc-issue-reports#775]
In the ParticleFilter::updateWeights function, a vector and a Map are passed by value.  This means that every time the function is called, the entire vector and the entire Map are copied.  It would be more efficient to pass these by reference (or const reference if appropriate), not by value.

**Comment by baumanab** [comment]
Thanks for letting us know about this.  Considering how many times this function is called it would likely represent a large efficiency gain.  I'm trying to think of whether or not passing the original vector and Map (reference) vs. passing a copy (value) would create an issue.  We can definitely test this out in the near future.

**Comment by cs4nd13** [comment]
You're welcome!  Issue #940 is similar, by the way.

**Comment by baumanab** [comment]
The changes have been made.  Thanks for suggesting this improvement!
