### ISSUE TITLE
T2.L7.S13,16 Sigma point typos

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#776]
Sigma point notation typos in the videos. The last xk should be xk|k.

This equation may need to be corrected in a few places. Here is an example from sections 13 and 16.

Section 13 video:
<img width="786" alt="udacity-carnd-t2-l7-s13" src="https://cloud.githubusercontent.com/assets/1576588/25775973/cf2d9ac8-327f-11e7-8680-2d5272141f1a.png">

Section 16 video:
<img width="855" alt="udacity-carnd-t2-l7-s16" src="https://cloud.githubusercontent.com/assets/1576588/25775974/d1f0c942-327f-11e7-93e6-01c0691b2977.png">

**Comment by baumanab** [comment]
Noting as duplicate

**Comment by mvirgo** [comment]
Fixed!
