### ISSUE TITLE
Advanced lane finding - Code too long to display

### ISSUE THREAD

**Issue by davinderc** [udacity/sdc-issue-reports#777]
In term 1, in the Advanced Lane Finding lesson, in node 33, the code is so long that it doesn't get displayed properly. there is a left/right scrollbar at the bottom, but there is so much whitespace on either side of the code box that could be used to display the code better (or otherwise split long lines into two lines. I'm using firefox 53.0 on ubuntu 14.04, not sure if that's useful info

**Comment by baumanab** [comment]
Thanks for reporting this.  The long lines have been split.
