### ISSUE TITLE
T2.L11.6-7 : Missing data files makes it impossible to run code locally

### ISSUE THREAD

**Issue by wfs** [udacity/sdc-issue-reports#778]
https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750/3

**Comment by baumanab** [comment]
Thank you for letting us know.  Currently, the only practical workaround is the solution provided [here](https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750), the forum thread linked above.  Please let us know if this does not work for you.
