### ISSUE TITLE
Inconsistent info in Program Syllabus and Term overview

### ISSUE THREAD

**Issue by robocar** [udacity/sdc-issue-reports#779]

**Comment by robocar** [comment]
The info in the Program Syllabus overview seems off: it seems to add up the number of projects across all parts of the Extracurricular section (7), yet this sits inconsistent with the "5 Projects" note at the top of the Core Curriculum section (should probably be 15, that is the sum of all projects of all parts of this section).

https://files.slack.com/files-tmb/T2HQV035L-F585EHV1B-7f94adc26b/pasted_image_at_2017_05_03_04_18_pm_1024.png

Also, the "This term ends on ..." date seems off in both Extracurricular parts. It is an older date than the individual Due dates. For example "This term ends on Feb 5th" as you can see in the screenshot for the first part (or, if it is meant to be Feb 5th the following year, this should be indicated better).

Also, this:

https://files.slack.com/files-tmb/T2HQV035L-F580UF2FM-7123e27224/pasted_image_at_2017_05_03_04_33_pm_1024.png

**Comment by jessluls** [comment]
Thanks for the heads up - looking into it!

**Comment by baumanab** [comment]
It appears these items have been reconciled.
