### ISSUE TITLE
11: Transfer Learn: 15: Lab Solution: tf.global_variables_initializer is deprecated

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#780]
The solution uses tf.initialize_all_variables, which is deprecated.  I suggest changing to tf.global_variables_initializer.

https://www.tensorflow.org/api_docs/python/tf/initialize_all_variables

**Comment by baumanab** [comment]
Thanks for letting us know.  We may be able to address this in the future when the classroom versions are updated.
