### ISSUE TITLE
Lesson 16: PID Control/7 PD controller quiz submission wrong

### ISSUE THREAD

**Issue by agileminor** [udacity/sdc-issue-reports#782]
When you submit the code, it complains if "tau" isn't defined, but "tau" isn't used in the program, just tau_p and tau_d.

**Comment by jwdunn1** [comment]
Confirmed. I added "tau = 0.1" on the last line of the quiz code to get the grader to pass. Perhaps there is a reference to tau in the wrapper.

**Comment by pcarney8** [comment]
+1 this is still happening

**Comment by domluna** [comment]
@pcarney8  If you reset the quiz does it still happen?

**Comment by pcarney8** [comment]
appears to be gone now!
