### ISSUE TITLE
T2L7: equation index wrong

### ISSUE THREAD

**Issue by albert-killer** [udacity/sdc-issue-reports#783]
Lesson 7 of Term 2 Lecture 22 "Predicted Mean and Covariance"... at approx. 1 min in the video... within the weights equation: 

n_sigma should actually be n_a as later shown correctly at Lecture 23 under "Helpful Equations".

**Comment by albert-killer** [comment]
Can be confusing for the subsequent coding quiz!

**Comment by baumanab** [comment]
https://youtu.be/Dr6B_9K-AMM?t=60
