### ISSUE TITLE
Term 2 Lidar Coverage

### ISSUE THREAD

**Issue by jovialio** [udacity/sdc-issue-reports#785]
Much of Term 2 coverage uses Lidar as sensor but there was no mention in the course of how Lidar point cloud can be converted to trackable features. Would appreciate if this could be covered in the course as well.

**Comment by awbrown90** [comment]
@jovialio I would love to see that as well. I hope to work on a special elective in Term 3 for doing advanced sensor fusion and covering clustering algorithms in the simulator environment.

**Comment by jovialio** [comment]
@awbrown90 Thank you for the response and definitely looking forward to the coverage. Thanks!
