### ISSUE TITLE
All projects suddenly PAST DUE in the Extracurricular overview

### ISSUE THREAD

**Issue by robocar** [udacity/sdc-issue-reports#786]
The due date, which has been Jul or Aug until now is suddenly Jan or Feb, and all the projects are PAST DUE. Although this would mean all the projects were due a few days right after the first term started. (This is for the January cohort)

**Comment by jessluls** [comment]
Thanks for the heads up! I'm looking into it.

**Comment by baumanab** [comment]
It sounds like there was some odd behavior regarding due dates.  I think this has been resolved since this ticket was posted.  Did this resolve in your classroom?  Please let us know.
