### ISSUE TITLE
The execution environment for C++ may not be able to support large amount of code or memory requirement

### ISSUE THREAD

**Issue by yubrshen** [udacity/sdc-issue-reports#787]
Here is the link that I reported my observation, and experiment of the problem: 

https://discussions.udacity.com/t/program-seemed-aborted-without-any-error-message-lesson-11-session-26/244290

**Comment by baumanab** [comment]
Thank you for letting us know about this.  When you run the instructor's solution, does that work?

**Comment by yubrshen** [comment]
Running the instructor's code may work. 
As my report in the link: https://discussions.udacity.com/t/program-seemed-aborted-without-any-error-message-lesson-11-session-26/244290
even my code would work as long as I commented out some of the code segment. I concluded that it might be related to resource constraint.

**Comment by baumanab** [comment]
Ah, thank you for clarifying. We will look into this.

**Comment by baumanab** [comment]
When I run this code, I get the following return:

```c++
bayesianFilter.cpp: In constructor ‘bayesianFilter::bayesianFilter()’:
bayesianFilter.cpp:25:2: error: ‘observation_std’ was not declared in this scope
  observation_std = 1.0f;
  ^
bayesianFilter.cpp: In member function ‘void bayesianFilter::process_measurement(const MeasurementPackage&, const map&, help_functions&)’:
bayesianFilter.cpp:167:40: error: ‘observation_std’ was not declared in this scope
                                        observation_std);
                                        ^
g++: error: bayesianFilter.o: No such file or directory
```

Is this running for you?

**Comment by baumanab** [comment]
I have an update.  The solution code is not working in concept 25 either.  I ran your code in 26 and was able to reproduce your results.  It does look like there may be some manner of bug.

**Comment by baumanab** [comment]
I broke down the quiz and re-initialized the code for each part.  When I remove the comment symbols // for the code block highlighted in your forum post, output is produced for each part.  It's not clear what the bug was, but it appears to be gone.
