### ISSUE TITLE
T2 Project 2 UKF kalman-tracker.py data_out.txt parsing issue

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#788]
The format of the data_out.txt produced for the UKF project changed. A timestamp column was added as the first column. Therefore, the kalman-tracker.py script from the first project is not properly extracting the x and y values of the location of the vehicle and the green triangle markers are not showing up in the visualizer app.

The arrays in the lines:
		x_markers = lastrow[0]
		y_markers = lastrow[1]

need to have their indexes changed to:
		x_markers = lastrow[1]
		y_markers = lastrow[2]

**Comment by baumanab** [comment]
Sorry for this technical issue. Is this still a relevant and persistent bug?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
