### ISSUE TITLE
Error Installing OpenSSL on Windows 10

### ISSUE THREAD

**Issue by dehavenm** [udacity/sdc-issue-reports#789]
I've started work on the PID Controller project, and I'm trying to install OpenSSL so that I can install uWebSockets (which is required for the project). Yet when I try to follow the instructions for installing OpenSSL on Windows (I'm running Windows 10), I keep getting errors. I'm using Visual Studio 2015, I open a VS2015 x64 Native Tools Command Prompt, and I enter the following commands as per the instructions:

perl Configure VC-WIN64A

nmake

These commands appear to run successfully, but when I run the next command listed in the instructions:

nmake test

That's when it fails with the following error:

#   Failed test at test\recipes\99-test_fuzz.t line 37.
# Looks like you failed 148 tests of 148.
Failed test 'Fuzzing ct'
test\recipes\99-test_fuzz.t ................ 11/11 # at test\testlib/OpenSSL/Test.pm line 1163.

Looks like you failed 11 tests of 11.
test\recipes\99-test_fuzz.t ................ Dubious, test returned 11 (wstat 2816, 0xb00)
Failed 11/11 subtests

Test Summary Report

test\recipes\99-test_fuzz.t (Wstat: 2816 Tests: 11 Failed: 11)
Failed tests: 1-11
Non-zero exit status: 11
Files=126, Tests=773, 167 wallclock secs ( 1.45 usr + 0.23 sys = 1.69 CPU)
Result: FAIL
Failed 1/126 test programs. 11/773 subtests failed.
NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0xb'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

The official installation instructions offer no troubleshooting advice for this sort of error.

**Comment by baumanab** [comment]
Sorry for any confusion surrounding installation.  I recently stepped through the windows install of uWebsockets and term 2 projects.  If you are still encountering issues it may be best to use Ubuntu Bash on Windows.  Would you mind trying that?  Instructions and other information are linked here: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/16cf4a78-4fc7-49e1-8621-3450ca938b77

You may still encounter some errors.  Please let me know if that occurs and we can try to resolve.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
