### ISSUE TITLE
Due date for Extra Curricular in SDCND changed to Jan 20th from Aug 2017

### ISSUE THREAD

**Issue by ajeet-repos** [udacity/sdc-issue-reports#790]
Hi

I am  in Jan 2017 cohort for the Seld Driving Nano Degree. Till yesterday my due date for extracurricular activities like resume reviewing, etc was showing as Aug 2017. But, today after I made the payment for Term - 2 through the link provided in the reply to a query I sent few days back, my due dates are showing as Jan 20th.

Please help in resetting it back to earlier date.

**Comment by baumanab** [comment]
Apologies for any confusion.   The most effective way to resolve this is to contact selfdrivingcar-support@udacity.com.  Would you mind sending them a note about this?
