### ISSUE TITLE
SDC- Add review result page into project or personal profile or course information.

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#792]
It's a good way to add project review result page into project info or sidebar's list or personal profile or course info so that it's easy to find, because the review still has lots of very useful information, it is worth to read and easy find. but now it's very hard to find where it is and not very clear..

**Comment by baumanab** [comment]
Thanks for suggesting this feature, it's certainly something worth considering. Currently, the following may serve as a workaround.  

Reviews can be accessed via the classroom and the link can be kept anywhere, including a personal site or GitHub repo.  All previous reviews can be accessed via the notes tab.  The review link can also be added to a project in a profile.
