### ISSUE TITLE
Term2 - Localization - Helper_functions.h:63:34: error: ‘M_PI’ was not declared in this scope in windows

### ISSUE THREAD

**Issue by sookinoby** [udacity/sdc-issue-reports#794]
Hi,
In windows (MinGW) the math.h does not define the constant M_PI. So we get an error as M_PI was not declared in the scope in windows.
To fix this add

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

helper_functions.h file

**Comment by baumanab** [comment]
Thank you for reporting this.  The following has been added ```helper_functions.h```

```
// for portability of M_PI (Vis Studio, MinGW, etc.)
#ifndef M_PI
const double M_PI = 3.14159265358979323846;
#endif
```
