### ISSUE TITLE
Provide .jpeg files for download to run exercise in Project: Vehicle Detection and Tracking

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#796]
Please provide .jpeg files (and any other resource) to allow to run the exercises locally, on one's PC. 

E.g. for this exercise https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/2b62a1c3-e151-4a0e-b6b6-e424fa46ceab/lessons/fd66c083-4ccb-4fe3-bda1-c29db76f50a0/concepts/40ac880a-7ccc-4145-a864-6b0b99ea31e9

Experimenting with the code, and debugging it, in the web browser is frustrating, and a massive waste of time.

**Comment by mvirgo** [comment]
Jpeg, pickle files, etc. used in quizzes are now linked to in the classroom.
