### ISSUE TITLE
a bug in P4, Color and Gradient section

### ISSUE THREAD

**Issue by asimay** [udacity/sdc-issue-reports#797]
a bug in P4, Color and Gradient,
 the code of course has some small bug. 
color_binary = np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary))

it should multiply 255. 
color_binary = np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary))*255,
or else it is totally black image.

thanks. I'll report the issue on feedback

**Comment by baumanab** [comment]
Thank you, this has been corrected.
