### ISSUE TITLE
T2 7.20 Visualization issue in Sigma Point Prediction Assignment 1

### ISSUE THREAD

**Issue by ricgu8086** [udacity/sdc-issue-reports#798]
In section "Helpful Equations", the quotient between v_k and psi_dot_k is very small and error prone and seems that the denominator is psi_k instead of psi_dot_k . A note to pay attention to this detail or the increase in the font will avoid many computing issues (I spend too much time debugging the code)

**Comment by baumanab** [comment]
Thanks for pointing this out.  That was definitely not easy to read.  I have increased the font size, I hope this clarifies symbols.
