### ISSUE TITLE
Term 2 EKF simulator

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#799]
The code to run the code with the new term 2 simulator is not in the 'master' branch of the repo. This code is in a different branch 'project_v2'. The master branch still assumes that the code is to be run with the old simulator. This causes a lot of confusion to new students starting with the project.

**Comment by subodh-malgonde** [comment]
Just want to let you guys know that the '2-D Unity Visualizer' section (old simulator) in the classroom has been replaced with the 'Kalman Filter Project Visualizer' section (new simulator). Whereas the project's README and source code does not contain anything on the new simulator. 

The 'Tips and Tricks' section of the project still contains this:

> Download the Kalman filter visualizer. You can find more information about the visualizer the in the "2-D Unity Visualizer" lecture notes.

Further adding to the confusion.

**Comment by awbrown90** [comment]
@subodh-malgonde The change has been made and now the EKF simulator code is in the master branch and the project description has details for using it.
