### ISSUE TITLE
Console command correction in TensorFlow lab

### ISSUE THREAD

**Issue by dalex01** [udacity/sdc-issue-reports#8]
`cd Ud-DL-L1/assignment` should be used instead of `cd assignment`

https://classroom-sdc.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/b619c2f0-24e3-4529-aa48-9bcdba47cd08

**Comment by Brok-Bucholtz** [comment]
@dalex01 

The repo folder has been added to the setup instructions.  Thanks for letting us know!
