### ISSUE TITLE
Adjust the project submission dates

### ISSUE THREAD

**Issue by divya49** [udacity/sdc-issue-reports#80]
The project submission dates are on Fridays i.e Nov 25th and Dec 9th. Please note that many of us taking the Nanodegree have full time jobs. Its very difficult to meet the project submission timeline. Can the project submission dates be moved to Mondays - so that we can work on Saturday and Sunday. 
I see that the Project 2 submission dates have been changed. 
Earlier the Project 2 submission date was Dec 2nd, now it is advanced to Nov 25th. Also project 3 submission dates have changed from Jan 14th to Dec 9th. This is difficult to achieve for people with full time jobs.  The time between Project 2 and Project 3 submission dates are very less.  Please consider people with full time jobs when deciding on the project due date. Also if the project due dates are on Monday or after holidays, it is better!!

**Comment by rm51** [comment]
I also agree with this. In addition to many people working full time, there are others who are full time students. No one so far that I've talked to has just been working on the nanodegree. And quite a number of them are doing most of the studying on the weekend.

**Comment by dhruvp** [comment]
We'll work on making this change!

**Comment by saurabhsoodpec** [comment]
We got an email that the project dates have moved to Mondays, but the project 2 shows "Submit Today" i.e. Sunday. Can you fix that too.

**Comment by JimHaughwout** [comment]
Agreed. All submissions should be Mondays, considering people who are in time zones far behind UTC
