### ISSUE TITLE
Term 2, Lesson 5, 18 - Jacobian Matrix Part 1: Incorrect Statement

### ISSUE THREAD

**Issue by pierluigiferrari** [udacity/sdc-issue-reports#800]
In term 2, lesson 5, 18 "Jacobian Matrix Part1", there is an incorrect statement at the end of the video:

At 1:59 Andrei says, "you have to check that neither x nor y is zero", which is incorrect. x or y can be zero as long as not both are zero.

The correct statement should be, "you have to check that x and y are not both zero".

This has important implications: If a student would implement the algorithm in a way that py can't be zero, then you wouldn't be able to track objects that are exactly in front of the car.

**Comment by pierluigiferrari** [comment]
The code is correct in the subsequent unit, "Jacobian Matrix Part 2", but it should still be clarified in the above unit.

**Comment by baumanab** [comment]
Thank you for reporting this.  A note has been added below the video.
