### ISSUE TITLE
new EKF simulator: term2_sim_linux and dataset2 in simulator

### ISSUE THREAD

**Issue by parthasen** [udacity/sdc-issue-reports#802]
It's difficult to match different instruction with new link for [simulation](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/tree/project_v2).Again two dataset options ( Dataset1 and Dataset2) are available for simulation in that simulator but we have one [dataset ](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/blob/master/data/obj_pose-laser-radar-synthetic-input.txt)here. 
New link with old instruction and two dataset options cause confusion.

**Comment by baumanab** [comment]
Sorry for the confusion. The project now uses the simulator rather than data files and instructions have been updated to reflect this.
