### ISSUE TITLE
Term 2 Lession 18 Quiz: Which equation correctly models x?

### ISSUE THREAD

**Issue by jbi35** [udacity/sdc-issue-reports#803]

**Comment by jbi35** [comment]
The answer options and the correct answer all seem wrong to me: 
Which equation correctly models x? 
x =x+v*cos(phi)
An addition of an position (unit [m]) with a velocity (unit [m/s]) is IMO not possible.

**Comment by domluna** [comment]
You're right the units don't match up, \* *dt* has been added to to the answer options. Thanks for the reporting the issue.
