### ISSUE TITLE
Term 1/ Lesson 8 - CNNs/ 2. Color : Incorrect quiz answer

### ISSUE THREAD

**Issue by lealldiogo** [udacity/sdc-issue-reports#806]
Quiz answer doesn't match the correct answer as explained in the video played after the quiz.

**Comment by lealldiogo** [comment]
![screenshot from 2017-05-17 10-08-37](https://cloud.githubusercontent.com/assets/25007408/26155469/a49f6f76-3ae9-11e7-8023-fb5dd2ec764c.png)
![screenshot from 2017-05-17 10-09-28](https://cloud.githubusercontent.com/assets/25007408/26155468/a49b6958-3ae9-11e7-8204-9d4cb3ee3244.png)

**Comment by baumanab** [comment]
Thank you for reporting this, it has been corrected.
