### ISSUE TITLE
Term 1 Lesson 5 Miniflow broken video link

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#807]
2. Introduction

"Backpropagation is the process by which neural networks update the weights of the network over time. (You may have seen it in this video earlier.)"

 'this video' link is broken
I think it should point to the video of Lesson 4 Introduction of Neural Networks / 19. Backpropagation

**Comment by dsilver829** [comment]
Fixed! Good catch.
