### ISSUE TITLE
Term 2, EKF uWebSockets Installation

### ISSUE THREAD

**Issue by MatthewYounkins** [udacity/sdc-issue-reports#812]
Some of the details are discussed here:

https://discussions.udacity.com/t/problem-compiling-the-project-uws-uws-h-no-such-file-or-directory/248608/28

But we're having to fight through changes in operating systems, uWS not installing correctly, cmake not installing correctly, etc., etc.

A step by step instruction to correctly operating uWebSockets would be nice - so far I've spent 12 hours on changing operating systems, installing and setting up Linux, copying uWS to a variety of random places, etc., and 0 hours working on Kalman filters.

Thanks!

**Comment by JacquesRoth** [comment]
I am finding it impossible to install this uWS nonsense on Windows Home 10.  Many posts on the forums about how to do it, forum mentors trying to help, but nothing works, just many hours of time wasted.  Will not be able to continue this course if this is not fixed.

**Comment by baumanab** [comment]
Sorry for the frustration.  I recently went through the installation on windows and made notes of issues encountered and now to resolve them.  Have you been able to get started on the project?  If not, what error(s) are you encountering?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
