### ISSUE TITLE
C++ For Programmers

### ISSUE THREAD

**Issue by cvetakg** [udacity/sdc-issue-reports#813]
In chapter Classes in lesson 11: there are many spelling errors, and some functional errors. E.g. getLicenseNumber and licenseNumberIn are seated as string, while licenseNumber is int.t.

**Comment by baumanab** [comment]
refers to https://classroom.udacity.com/courses/ud210/lessons/e90ff59d-4e98-4ebf-9da7-8d28ed7636a3/concepts/3d498c07-2107-44d4-a41c-4a48d5bd4597

**Comment by baumanab** [comment]
Thanks for letting us know about this, the errors have been corrected.
