### ISSUE TITLE
C++ bug (without error)

### ISSUE THREAD

**Issue by fernandodamasio** [udacity/sdc-issue-reports#815]
In Lesson 7 (Unscented Kalman Filters) 21. Sigma Point Prediction Assigment 2. For these following codes, I find it is very interesting.

In main.cpp, 

MatrixXd Xsig_pred = MatrixXd(15, 5);  // line 20
In ukf.cpp

int n_x = 5; // line 24
int n_aug = 7; // line 27
MatrixXd Xsig_pred = MatrixXd(n_x, 2 * n_aug + 1); // line 41
*Xsig_out = Xsig_pred; // line 101:
Why is the last assignment valid? Because *Xsig_out and Xsig_pred have different dimensions.

To my surprise, if I change the line 20 of main.cpp as follow initialization, the code give me the same final output.

MatrixXd Xsig_pred = MatrixXd(5, 15);

https://discussions.udacity.com/t/why-the-sample-code-initialize-the-matrix-wrongly-transposed-but-still-gives-correct-results/249159

**Comment by baumanab** [comment]
Thanks for reporting this.  This issue and its solution have been noted in the classroom.
