### ISSUE TITLE
Unable to connect simulator 1.3 to project V2 on Windows 10

### ISSUE THREAD

**Issue by fernandodamasio** [udacity/sdc-issue-reports#816]
We are having a lot of discussions about it...

https://discussions.udacity.com/t/unable-to-connect-simulator-1-3-to-project-v2-on-windows-10/249197

**Comment by baumanab** [comment]
Sorry for the difficulties. Is this issue still occurring?

**Comment by fernandodamasio** [comment]
Hi!

I don't know, sorry. I'm using Ubuntu now.


Atenciosamente,


FERNANDO DAMASIO

CEO @CashFlix & Mentor @Udacity

t. +55 (31) 998319747

e. fernandodamasio@hotmail.com<mailto:fernandodamasio@hotmail.com>

in. linkedin.com/in/fernando-damasio<http://www.linkedin.com/in/fernando-damasio>

________________________________

**Comment by baumanab** [comment]
Thanks for letting us know. I'm going to clise this out fir now.
