### ISSUE TITLE
advanced lane finding: 30: color and gradient quiz, comments may need updating

### ISSUE THREAD

**Issue by e7dud7e** [udacity/sdc-issue-reports#818]
In the code, the comment says:
```
# Convert to HSV color space and separate the V channel
```
But this is followed by code to convert rgb to HLS:
```
hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HLS).astype(np.float)
```

Also, 
```
# Note color_binary[:, :, 0] is all 0s, effectively an all black image. It might
    # be beneficial to replace this channel with something else.
    color_binary = np.dstack(( np.zeros_like(sxbinary), sxbinary, s_binary))
```
The comment that color_binary is an all black image does not seem to match the code, since color_binary is not an all black image.

**Comment by baumanab** [comment]
related to  #797

**Comment by baumanab** [comment]
Thank you for reporting this.  The code and comment has been updated for HLS.  The other item seems accurate since it is saying that color binary with all 0's is black.
