### ISSUE TITLE
GitHub project submission doesn't list my repos

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/sdc-issue-reports#82]
I authenticated without error. However, once I was redirected, I was presented with the "link to github" button again. 

I cleared cache, launched an incognito window, even signed out and back in to no avail. 

I submitted it as an attachment just to get the project in to review process but I wanted you to know about my experience in case there actually is a glitch somewhere.

Mac OS X 10.11.6
Chrome Version 54.0.2840.71 (64-bit)

Please let me know how I can assist you in testing in any way. Thanks!

**Comment by swwelch** [comment]
Hi! Thanks for reporting this. I've forwarded it to the engineering team, and they are looking into it!

**Comment by Brok-Bucholtz** [comment]
@matthewzimmer 

This is part of the sprint backlog. I'll update this issue when it's fixed.
