### ISSUE TITLE
Quiz: Color Region > Test Run not working

### ISSUE THREAD

**Issue by sebzi84** [udacity/sdc-issue-reports#820]

**Comment by sebzi84** [comment]
When I press Test Run in "7.Quiz: Color Region", nothing shows up in neither IE nor Firefox. 
The quiz before worked without issues.

**Comment by sebzi84** [comment]
After navigating back and forth in the menu on the right side, it suddenly works. No idea why.

**Comment by sebzi84** [comment]
Same problem with the Canny Edge Detection Quiz. However, this time I did not yet manage to get some output from test run. Can it be some timing issue because I am doing this out of China?

**Comment by sebzi84** [comment]
Trying a long time and leaving it in a background image and now it works. However, also when it did not work, it finished loading. Was it running into a timeout the times before?

**Comment by baumanab** [comment]
This is certainly odd behavior.  It's not clear what caused this since it isn't reproducible.  Please let us know if this occurs again and/or persists so that we can investigate further.
