### ISSUE TITLE
Term 1: Starter Kit: Anaconda

### ISSUE THREAD

**Issue by john-chan-k7** [udacity/sdc-issue-reports#821]
There are confusing instructions on this page:
https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

The instructions say to download the Miniconda version for Python 3.5.

However, the latest version of Miniconda (pointed to by the links) and a suggested version (4.3.11) use Python 3.6.

Also the warning about version 4.3.13 is unnecessary because that version is not available anymore.

I'm guessing that using the latest version of Miniconda is fine because what matters is the Python version for the course environment, and that's specified in a config file.

**Comment by domluna** [comment]
@john-chan-k7 Python 3.6 should work fine. Thanks for bringing this up though.
