### ISSUE TITLE
CarND-Term2-Lesson5-#8 - Notation Error

### ISSUE THREAD

**Issue by chrisxed** [udacity/sdc-issue-reports#825]

**Comment by chrisxed** [comment]
Minor notation inconsistency? Term2-Lesson5-#8 - The state transition matrix has subscripts sometimes, but not consistently. Compare with the video at 53s.

**Comment by baumanab** [comment]
Thank you for reporting this.  It appears that subscripts are now aligned.  Please let me know if this isn't the case.
