### ISSUE TITLE
Terrm2-Proj1 Code minor formatting

### ISSUE THREAD

**Issue by chrisxed** [udacity/sdc-issue-reports#826]
The Term2 Project1 code has a main.cpp with about 85 blank lines at the end of the file. Also this file, but none of the others, _sometimes_ uses hard tabs instead of spaces. And of course everyone who doesn't agree that Tabs are evil, is wrong. ;-)

**Comment by baumanab** [comment]
Thank you for letting us know, the white space has been removed.
