### ISSUE TITLE
mpc_to_line running issue

### ISSUE THREAD

**Issue by AhmedElshaarany** [udacity/sdc-issue-reports#827]
When I try to run the mpc executable on ubuntu, I get the following error:

Iteration 0
cppad-20160000.1 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 488 in the file 
    /usr/include/cppad/utility/vector.hpp
mpc: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
Aborted (core dumped)

**Comment by domluna** [comment]
@AhmedElshaarany Looks like an out of bounds error.

**Comment by AhmedElshaarany** [comment]
Thanks @domluna , figured it out! You can close the issue now :)

**Comment by crazypecker** [comment]
I have the same problem, @AhmedElshaarany can you share your solution. Thanks

**Comment by AhmedElshaarany** [comment]
@crazypecker 
If I remember correctly, I think the problem was not using CppAD namespace when defining the values for the vector of costs and constraints "fg"
For example, I stored the cost as 
`fg[0] += pow(vars[cte_start + i] - ref_cte, 2);`
when it should have been
`fg[0] += CppAD::pow(vars[cte_start + i] - ref_cte, 2);`

Checking out the solution to the quiz helped out a lot.

**Comment by crazypecker** [comment]
I already have
fg[0] += CppAD::pow(vars[cte_start + i] - ref_cte, 2);

so I don't think this is creating problem in my case.

**Comment by AhmedElshaarany** [comment]
No worries! Your best bet is to compare your solution to the solution provided by Udacity

**Comment by zeeshananjumjunaidi** [comment]
I also have same problem. even I am using CppAD::pow instead of pow. My solution.x variable is empty.

**Comment by naveed087** [comment]
Not sure but apparently it seems your variable `solution.x` itself or any of the variables in the  equation

`fg[0] += CppAD::pow(vars[cte_start + i] - ref_cte, 2);`

is not properly computed.

If none of this works, please share your code.

**Comment by bflyth** [comment]
I'm having the same issue, but all my namespaces are in place. `solution.x` is still empty

**Comment by baumanab** [comment]
Sorry about this issue.  Would you mind opening a new issue?  It will be easier for us to track.

**Comment by bflyth** [comment]
@baumanab I think I actually just figure out part of it

**Comment by baumanab** [comment]
Nice, thanks for letting me know.

**Comment by EmilePapillon** [comment]
I am getting this error when running the code in the "solution" folder, untouched. 

`Iteration 0
Cost 1.4822e-323
cppad-20180000.0 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 476 in the file 
    /usr/local/include/cppad/utility/vector.hpp
Assertion failed: (false), function Default, file /usr/local/include/cppad/utility/error_handler.hpp, line 206.
fish: './mpc' terminated by signal SIGABRT (Abort)
`

**Comment by haopo2005** [comment]
> @nahmed086 i am struck on this as well.....code reviews do not seem to reveal any out of bound error
> 
> cppad-20160000.1 error from a known source:
> vector: index greater than or equal vector size
> Error detected by false result for
> i < length_
> at line 477 in the file
> /usr/include/cppad/utility/vector.hpp

reinstall the ipopt with "install_ipopt.sh" and "install-ubuntu-MPC.sh" will solve your problem.
