### ISSUE TITLE
Term2-Lesson3-#25 Not Python3

### ISSUE THREAD

**Issue by chrisxed** [udacity/sdc-issue-reports#828]
Since Term 1 was a wake-up call for Py3, why not some consistency? The great program at #25 just needs some minor work. 3 print statements need (). And some raise statements need fixing. Then it is a useful program to keep around locally for reference and testing.

**Comment by chrisxed** [comment]
Oh, and I just noticed that in the `__mul__()` method that the comment incorrectly says "subtract if correct dimensions". It should say, I presume, "multiply".

**Comment by domluna** [comment]
@chrisxed could you link the lesson you're referring to, it's not very clear.

**Comment by chrisxed** [comment]
Sorry for any confusion. I tried to be clear with the title of this thread which starts with "Term2-Lesson3-#25". Ah, maybe there's confusion because I typed shift-3 then a "2" and then a "5". For some reason it tried to auto link to some incorrect lesson. I don't know about why that happened (not a GitHub user). Thanks.

**Comment by chrisxed** [comment]
Yup. Ignore the #25 link. I don't know why it must do that or how to suppress it.

**Comment by baumanab** [comment]
Thanks for the feedback.  Print statements and the multiply comment have been addressed.  Raise exception syntax is being retained for now.
