### ISSUE TITLE
Mentor Dashboard Chat - Code Snippet formatting

### ISSUE THREAD

**Issue by martin-martin** [udacity/sdc-issue-reports#83]
It's very non-intuitive to add longer code snippets because that requires to have the three backticks in separate lines from the code.

However - **pressing enter sends the message**, so currently it is necessary for proper code block formatting to add the backticks in a text editor.

(obviously most students don't do that - even if they know about using the backticks).

Another reason why **Shift + Enter** for linebreaks would be great!

**Comment by MaximeLeclerc** [comment]
+1

**Comment by Brok-Bucholtz** [comment]
@martin-martin 

Thanks for letting us know.  I've passed this off to the team responsible for the dashboard.  I don't have a date when they will be able to work on this, but I'll update this issue when I find out.
