### ISSUE TITLE
Term 2 Simulator 1.4 display bug

### ISSUE THREAD

**Issue by maschult** [udacity/sdc-issue-reports#831]
I can run the simulator and I see the car moving, but all the blue and red marks for the sensor data are not shown. The vicinity around the car remains simply white. If I also run my EKF-Code, I get a connection to the simulator but the symbols of my output are also not shown.

I'm using Debian Jessie (stable) with Xorg 7.7 and the proprietary Nvidia driver. Simulator version is 1.4. If you need further information, please let me know.

**Comment by awbrown90** [comment]
Hi maschult, that is very strange indeed. Can you please confirm if this issue happened on the term1 simulator as well? So you are not trying to run through a virtual machine, correct?

**Comment by maschult** [comment]
Hi, with the term 1 simulator I had no problems. I am running directly on my hardware and don't use a virtual machine .

**Comment by J-Rojas** [comment]
I have the same problem with the Kidnapped Vehicle. I can't see the blue or red lines. I'm running on Mac Sierra.

**Comment by baumanab** [comment]
Sorry for the technical difficulties. Is this bug still occurring?

**Comment by J-Rojas** [comment]
No, I believe I solved the issue - it was user error, but I can't recall what the solution was. I would have closed the bug myself but I don't have that option. Thanks for following up.

**Comment by baumanab** [comment]
Thanks for letting us know!

**Comment by Thyrland** [comment]
Hi, it seems that I've got the exact same problem. Haven't found the solution so far however. Could anyone of you help me out? Thank you!!!

**Comment by J-Rojas** [comment]
It was user error on my part... print out the values just before sending them to the simulator and double check that they are correct.
