### ISSUE TITLE
T2-L11-S14 Markov Assumption video error

### ISSUE THREAD

**Issue by brahmwindeler** [udacity/sdc-issue-reports#832]
At around 3:46 in the video, the narrator indicates that the z1:t-1 and u1:t-1 terms can be ignored for the xt term. The video has the arrow from z1:t-1 disappear, but the u1:t-1 arrow remains when it should disappear as well. Also, it would be helpful if the disappearing arrows were highlighted with the yellow circle momentarily first to draw attention to them, similar to what is done at 4:48 when talking about the relationship between ut and xt-1.

ees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/c12ca8a6-10d4-4f34-bcf6-6894fd9ceba2

**Comment by baumanab** [comment]
Thanks for the report and suggestion, our team is looking into it.

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/47f9b7a1-317f-4fab-88d3-bb3ce215d575/concepts/c12ca8a6-10d4-4f34-bcf6-6894fd9ceba2

**Comment by baumanab** [comment]
#1168 is similar, closing this out for information in 1168.
