### ISSUE TITLE
No normalization done in LeNet-Lab code

### ISSUE THREAD

**Issue by AnsgarNell** [udacity/sdc-issue-reports#834]

**Comment by AnsgarNell** [comment]
In section 35 from Lesson 8 they say: 
"Preprocessing An MNIST image is initially 784 features (1D). We reshape this to (28, 28, 1) (3D), normalize such that the values are between 0-1 instead of 0-255, and finally, pad the image with 0s such that the height and width are 32 (centers digit further). Thus, the input shape going into the first convolutional layer is 32x32x1." 

But in the solution the pixels values aren't changed, they remain 0-255.

**Comment by baumanab** [comment]
Thanks for posting about this. The data set imported from tensorflow is already normalized.
