### ISSUE TITLE
Term 2, Lesson 16: Slide 12: PID Implementation, can't use sum()

### ISSUE THREAD

**Issue by pcarney8** [udacity/sdc-issue-reports#835]
setting int_cte = sum(y_trajectory) does not return correct results. Could you potentially check for both answers (the one from int_cte += cte and using sum()) it appears to be a very minute difference

**Comment by domluna** [comment]
@pcarney8  `int_cte` is used at each step to compute the steering value. I'm a little confused how  you're using `sum` here. Could you post your solution?

**Comment by domluna** [comment]
I changed the error tolerance from 1e-8 to 1e-5 so it might accept it now.

**Comment by pcarney8** [comment]
```
def run(robot, tau_p, tau_d, tau_i, n=100, speed=1.0):
    x_trajectory = []
    y_trajectory = []
    # TODO: your code here
    prev_cte = robot.y
    for i in range(n):
        cte = robot.y
        cte_d = cte - prev_cte
        prev_cte = cte
        sum_cte = sum(y_trajectory) + cte
        steer = -tau_p * cte - tau_d * cte_d - tau_i * sum_cte
        robot.move(steer, speed)
        x_trajectory.append(robot.x)
        y_trajectory.append(robot.y)
    return x_trajectory, y_trajectory
```

which i realize is more expensive computationally because it's calculating the full sum each iteration rather than just a single addition as with `int_cte`

**Comment by pcarney8** [comment]
ah, I think i'm actually double counting cte in the first step

**Comment by domluna** [comment]
So is there still an issue?
