### ISSUE TITLE
Error in 9. Perceptron topic of Lesson 4 (Introduction to Neural Networks in Self Driving Car Nanodegree

### ISSUE THREAD

**Issue by ramkumarkoppu** [udacity/sdc-issue-reports#838]
where the paragraph says, 
In this example, we'll use w
​grades
​​  for the weight of grades and w
​test
​​  for the weight of test. For the image above, let's say that the weights are: w_grades​​ =−1, w_test​​  =−0.2. You don't have to be concerned with the actual values, but their relative values are important. w_grades​​ is 5 times larger than w_​test , which means the neural network considers grades input 5 times more important than test in determining whether a student will be accepted into a university.

Mathematically -0.2 is 5 times larger than the -1.0 not other way around as their sign is negative.

**Comment by baumanab** [comment]
You are correct.  The algorithm is impacted by the magnitude of the difference, which is what it sounds like the author is referring to.  Does that make sense?
