### ISSUE TITLE
wrong figure in lesson 4, unit 10 (AND perceptron quiz)

### ISSUE THREAD

**Issue by fkeidel** [udacity/sdc-issue-reports#840]
There is a wrong figure in lesson 4, unit 10 (AND perceptron quiz).

The figure at the top of the text doesn’t correspond to the text below it:
“…Set the weights (weight1, weight2) and bias bias to the correct values that calculate AND operation as shown above.”

I assume that the correct figure should look like that in unit 11 on the left side (AND)
 
Regards,
Frank

**Comment by matthewsommer** [comment]
Student here, noticed this as well. You can figure it out by looking at the code but this definitely takes away from learning how to decipher a table to understand the sensitivity to adjusting the weights and bias. Really wish the graphic wasn't wrong when I went through this section.

**Comment by Jonathan-James** [comment]
I am on this quiz right now and I am super confused on how to get through this quiz, any help would be well appreciated. Are you guys in the slack?

**Comment by fkeidel** [comment]
The correct figure is on the next page (page 11) on the left side (AND).
I did the quiz just by trial and error. I set weight 1 = weight 2 und tried some values and then figured out how much bias to subtract to get the correct outputs.

**Comment by baumanab** [comment]
Thanks for reporting this.  The correct figure has now been added.

**Comment by nickguimaraes** [comment]
weight1 = 1.0
weight2 = 1.0
bias = -1.1

**Comment by AyonzOnTop** [comment]
It more like adjusting the weights such that the difference between the total of the weights and the bias is small

**Comment by AhmedSalam22** [comment]
> weight1 = 1.0
> weight2 = 1.0
> bias = -1.1

Can you explain how you do it?

**Comment by AyonzOnTop** [comment]
if weight1 + weight2 = 2.0 and bias= -1.1, difference is about 0.9 (ignoring the negative sign). so adjust the weights in a way the difference is as small as 0.9, you can also toy with the negative sign, by placing it beside weight 1 or 2 or bias or 1&bias or 1&2 or 2&bias, you get the gist, right. Apply theory as intuition leads
