### ISSUE TITLE
T2L14-11: mixed up ovals?

### ISSUE THREAD

**Issue by albert-killer** [udacity/sdc-issue-reports#841]
In lesson L14 "Implementation of a particle filter". Video in step No. 11 at approx. 2 min 12 sec: If a large diameter in one dimension represents a large variance / uncertainty the ovals should be the other way round. This is because the x axis is meant to be in the direction of the car's heading, which is from bottom to top in the video, not from left to right.

**Comment by baumanab** [comment]
Good catch.  It looks like the video is presenting the x and y error using cartesian coordinates in the most classic orientation, the map orientation.  A note has been added.
