### ISSUE TITLE
Simulator for Term 2 not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by avshepelev** [udacity/sdc-issue-reports#843]

**Comment by avshepelev** [comment]
I am using Ubuntu 16.04 and am unable to run the Simulator. After selecting the Screen Resolution and Graphics Quality in the graphics setup window and clicking ok, the window closes permanently and the simulator does not open. Below is the output when running the simulator from a shell.
![Screenshot from 2017-06-06 17-43-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e59efd02bec2001a6ea329/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f37d3dd5b568ee1536555c424fa853444d06ada7dd74fbef7625c84e01ffd36b5575c23417abb0871bbd00ba29835d99a4fcc8139abd6e61f5819d4a361e0c1a80f75b66a1911fcc5ca44be14d55a2113531e7647b.png)

**Comment by avshepelev** [comment]
I should have mentioned that I am running a standard laptop with a single screen. Despite this, the error I see says that "client has 2 screens".

**Comment by baumanab** [comment]
Sorry for the technical issues. Is this bug still persistent?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.

**Comment by IanBoyanZhang** [comment]
I still see this issue with newest term3 simulator. Exact same error ouput.

**Comment by steffens21** [comment]
Still have the same issue in on AWS machine with Ubuntu 16.04.

**Comment by baumanab** [comment]
Are you unable to run the simulator and complete projects?

**Comment by steffens21** [comment]
I have a workaround but it's messy.  I would rely like to just work on
Ubuntu and not need a second machine for the simulator.

**Comment by laygond** [comment]
hello steffens21 can you please share with us how you managed to run it. I was not able to run the term2 simulator. However I ran another version of the simulator from: 
https://d17h27t6h515a5.cloudfront.net/topher/2016/November/5831f0f7_simulator-linux/simulator-linux.zip
with no luck in the communication part. It would be cool to see your workaround.

This happens with the older version simulator:
Listening to port 4567
Connected!!!
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be array, but is null
Aborted (core dumped)

**Comment by steffens21** [comment]
Well the workaround was to run the simulator on my desktop and have that communicate with the AWS Ubuntu.  Sorry, but I don't know the details of the port forwarding anymore.  I found the workaround by searching in the udacity forum.

**Comment by laygond** [comment]
I see. My problem is that my machine only has ubuntu I guess I can try installing a windows VM to run unity and then use your technique.

**Comment by saurabhrb** [comment]
I successfully got it working on Ubuntu with unty3d. The problem with std::domain_error is the simulator(new ones) are sending images instead of x,y pts. This particular simulator [https://github.com/udacity/self-driving-car-sim/releases/tag/v1.45] worked properly and was returning ptsx and y in the json.

**Comment by baumanab** [comment]
@saurabhrb it sounds like this is working in your Ubuntu environment with the latest term 2 simulator release. Is that correct?  What version of Ubuntu are you running?

**Comment by saurabhrb** [comment]
Yes i am using term 2 simulator on Ubuntu 16.04. I resolved it, it was
mumps wget url for ipopt, I changed it, rebuilt ipopt and my solver started
giving me solutions.

Thank you.

Regards,
Saurabh

**Comment by saurabhrb** [comment]
Yes they are accurate. It was just my ipopt build which had a problem.

**Comment by baumanab** [comment]
Thank you for confirming!
