### ISSUE TITLE
Quiz Wrong Answer

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#845]
Term 1, Lesson 8: CNN, Sub-lesson 2: Color.

The right answer shown for this quiz is incorrect. 

According to the accompanying video the right answer should be `(R + G + B)/3`, however the right answer is shown to be `R, G, B`. The reason being its easier for the classifier to learn from grayscale images, since it can then classify letters from any color, even ones it hasn't seen before.

**Comment by baumanab** [comment]
Thanks for letting us know.  The quiz solution and video solution have been aligned.
