### ISSUE TITLE
Term2 - Localization, Lesson 11.14: Incorrect Markov-Assumption in Video

### ISSUE THREAD

**Issue by pierluigiferrari** [udacity/sdc-issue-reports#846]
In term 2, in the video of unit 14 of lesson 11, the mathematical formulation of the first order Markov assumption is incorrectly stated:

Scroll the video to around 1:00. The Markov assumption in the video is stated as:

p(x_t | x_1:t-1) = p(x_t | x_t-1, x_t-2, ..., x_0)

This is a tautology, it is not the first order Markov assumption. The correct first order Markov assumption is:

p(x_t | x_t-1) = p(x_t | x_t-1, x_t-2, ..., x_0)

Note the difference in the left part of the equation.

**Comment by pierluigiferrari** [comment]
My bad, I should have continued watching the video a bit longer ;). The line I quoted above was only the first line in the box titled "First order Markov assumption", the second line was shown a minute later. You can close this.

**Comment by baumanab** [comment]
Thanks for following up on this!
