### ISSUE TITLE
MPC Simulator path colors

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#847]
Can you please change the colors in the simulator to some that "differs" some more. The choosen colors yellow and bright green are difficult to distinguish for people with color vision deficiencies.

**Comment by baumanab** [comment]
Thanks for letting us know about this.  What would be a better choice of colors?

**Comment by ChrisShepherd81** [comment]
Some that differs more. As bigger the distance between two colors in any color space is as easier it gets. A darker green for example.

**Comment by baumanab** [comment]
Thanks for following up.  We do want to maximize access. This request has been loaded into our internal tracking system, so I'm closing it out here.

- internal system link: https://udacity.atlassian.net/browse/DRIVE-4141
