### ISSUE TITLE
Ubuntu 16.04 uWebSockets fix

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#849]
A [student reported](https://discussions.udacity.com/t/unable-to-build-on-ubuntu-14-04/249704/6?u=subodh.malgonde) that he gets this error when he tries to compile the project after running `./install-ubuntu.sh`.

> /usr/include/uWS/Group.h:69:10: note: no known conversion for argument 1 from ‘main()::<lambda(uWS::WebSocket<true>, char*, size_t, uWS::OpCode)>’ to ‘std::function<void(uWS::WebSocket<true>*, char*, long unsigned int, uWS::OpCode)>

The fix, apparently, is to change pass by value references ie `w` to pointers that pass by address `*w`. And if you are using a member such as .send you should wrap the pointer ie `(*w).send`.

**Comment by domluna** [comment]
@subodh-malgonde In v0.14 of uWebSockets some function signatures have changed. If uWebSockets is checked out to the commit [here](https://github.com/udacity/CarND-MPC-Project/blob/master/install-ubuntu.sh#L6) the installation should work fine. 

https://github.com/udacity/CarND-MPC-Project/pull/3 also had a similar issue. It's a small change either way but I'll add something to the README regarding this.

**Comment by baumanab** [comment]
Closed as uWebsockets version information has been added.
