### ISSUE TITLE
Typo in Intro to TF -> Quiz: TensorFlow Input

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#85]
Typo in word 'available' in first line of quiz.py at the bottom.
Current: # Solution is avaialbe in the other "solution.py" tab

Should be: # Solution is available in the other "solution.py" tab

**Comment by jessicayung** [comment]
Also in Line 10 of quiz.py it says 
        # ToDo: Feed the x tensor "Hello World"

when it should be
# TODO: Feed the x tensor 123

**Comment by jessicayung** [comment]
Same typo in 'quiz.py' for Intro to TF -> Quiz: TensorFlow Math
# Solution is avaialbe in the other "solution.py" tab

**Comment by Brok-Bucholtz** [comment]
@jessicayung 

I've fixed the typos with "available" and changed "Hello World" to 123.  Keep giving us great feedback!
