### ISSUE TITLE
C++ Define Constants

### ISSUE THREAD

**Issue by hmaleman** [udacity/sdc-issue-reports#851]
"With this statement we have set the integer weightGoal to 100. It cannot be changed during the program. If you want to change the value of weightGoal, you will have to edit the source code and recompile it."

The course note is not entirely correct.
Constant variables values can be changed during runtime through pointer and casting.

**Comment by baumanab** [comment]
Thanks for pointing this out.  Would you mind linking the page where this statement is made?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
