### ISSUE TITLE
Update C++ used in web interface to C++ 14

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#852]
The C++ compiler used in exercises in the web interface cannot compile contemporary C++ code, such as 
`auto int {0};`

C++ has been adopted in Term 2 because it is demanded by the automotive industry. Students should be allowed to practice with a recent definition of the language, not the one from 1998.

Consider moving to at least GCC 5 or Clang 3.4. If you are using one of those already, it is probably matter of providing the right switches to the compiler.

**Comment by baumanab** [comment]
Thank you for the feedback.  Our near future plans are to use c++ 11 as the default version.
