### ISSUE TITLE
Term 1 Project 1 Broken Link

### ISSUE THREAD

**Issue by johangithub** [udacity/sdc-issue-reports#853]
In P1.ipynb, the link to the forum for troubleshooting is broken. Right above the first python cell.

https://carnd-forums.udacity.com/cq/viewquestion.action?spaceKey=CAR&id=29496372&questionTitle=finding-lanes---import-cv2-fails-even-though-python-in-the-terminal-window-has-no-problem-with-import-cv2

**Comment by baumanab** [comment]
Thanks for reporting this.  The link does not resolve since it points to a version of the forums that no longer exists.  The broken forum links have been removed.  One link was updated with a relevant post.
