### ISSUE TITLE
Better compilers support in 12. Laser Measurements part 3

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#854]
With reference to the code at: https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/3612b91d-9c33-47ad-8067-a572a6c93837/concepts/f1cef488-6a2d-484d-a30d-8caa4fd082fd

The program malfunctions with  architectures with a `long` data type of 4 bytes only (Visual C++).

To fix the issue, consider changing line 40 in `main.cpp` to

`long long timestamp;`

I.e. change the type of `timestamp` from `long` to `long long`.

**Comment by baumanab** [comment]
Thanks for pointing this out.  Line 40 was changed to ```int64_t timestamp;```
