### ISSUE TITLE
Particle Filter Quiz needs view answer options

### ISSUE THREAD

**Issue by ahsteven** [udacity/sdc-issue-reports#857]

**Comment by ahsteven** [comment]
It is very difficult to understand what is being asked and there are no other similar examples given in the lectures. Once I understood what was being asked it was a trivial problem. I wasted so much time having to post on discussion forums. It would have saved me an hour or so if you simply had the answer there. It was not worth my time figuring this out. I have done this many times before with a proper rotation matrix. The way the problem is setup is confusing and it needs the solution posted.

**Comment by baumanab** [comment]
Sorry for any frustration.  It looks like many of the quizzes do have posted solutions.  Would you mind linking the quiz discussed here so that we can determine if this has been updated with a solution and determine actions, if not?

**Comment by ahsteven** [comment]
The quiz I was referring to is in Lesson 14: Implementation of a Particle
Filter. Part 13. Transformations and Associations.

https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/5c50790c-5370-4c80-aff6-334659d5c0d9/concepts/1da01dfe-6653-4d2d-b2e4-325740fc7156


Thanks,

Adam

**Comment by baumanab** [comment]
Thanks for clarifying.  We are actively working updating this content.  Would you mind letting us know some specific things we can add that would have made for a better experience?

**Comment by baumanab** [comment]
We added some content to concept 13 (implementation of a particle filter quizzes).  We are starting with this and ultimately plan to replace some of the text with an animation/explanation of coordinate transforms.  Would you mind taking a look and giving us some feedback?

**Comment by ahsteven** [comment]
Hi Andrew,

Sorry for not getting back to you sooner. The content added will be helpful
for some. I already knew rotation matrices going in so it probably would
not have helped me. I think the thing that would have helped the most would
have been having a view answer button that showed exactly what was being
asked. It was the wording of the description and the question that I had
trouble deciphering. Seeing the answer would have cleared things up a bit.

There is a post in the discussion forum where I explained my questions
concerning the problem and then I give a description of how I would have
worded the question to clear things up. Here is an excerpt from the forum.

"Thank you everyone for your explanations. I think this lesson needs to be
redone using rotation matrices and translation vectors or something
similar. It would be much easier and practical that way.

The way I would explain it now that I think I understand would be as
follows:

The sensor on you car senses an object at coordinate (2,2) relative to the
car. If the car is located in the pose of the particle at (4,5, -pi/2) then
the objects location in the global coordinate frame would be calculated by
the following translation and rotation:

[x_w, y_w]' = [4, 5]'+ [cos(-pi/2), -sin(-pi/2); sin(-pi/2), cos(pi/2)] *
[2, 2]' = [6, 3]'

I have done this many times before but the way it was presented in the quiz
left me totally confused as to what I was supposed to be doing and took me
a long time to figure out. It would really help if there was a view answer
button so I could try to decipher what is being asked. Sometimes an example
is the best explanation."

You can also take a look at the posts to see what the other students and
myself were confused about. I got in to the discussion around Jun 11.

https://discussions.udacity.com/t/l14-transformations-and-associations/239879/11

Best,

Adam

**Comment by baumanab** [comment]
Thank you for your feedback.  We are still working on concept 13 and will consider this as we make more changes.  I'll let you k now when we have the next iteration.

**Comment by baumanab** [comment]
We have now broken up the quizzes and added solutions.  We would appreciate any feedback you are willing to offer.  We plan on adding in an animation of the rotation/transformation in the near future.
