### ISSUE TITLE
Simulator for Term 2 fills up file-system with huge log file

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#859]
I let the simulator run, and it filled up my file-system, it keeps writing to this log file:

/home/fanta/.config/unity3d/Udacity/self_driving_car_nanodegree_program/Player.log

It keeps writing an error message like
`11/06/2017 20:12:48|Fatal|WebSocket.acceptException|System.Net.Sockets.SocketException: Connection refused`
followed by a stack trace.

The file made it past 28 GB in minutes. 

I am running it under Ubuntu 16.04 64-bit. The issue is systematic.

Steps to reproduce:

* clone the project repository
* download and install the simulator
* run install-ubuntu.sh in the project directory
* build the project as per provided instructions
* start the simulator, keep the default options, click OK, make sure "Project 1/2: EKF and UKF" is selected and click SELECT
* start ExtendedKF
* stop ExtendedKF (CTRL+C)
* leave the simulator running
* after a while, Ubuntu reports that the file system root is about to be full.

**Comment by fantauzzi** [comment]
Probable duplicate of https://github.com/udacity/sdc-issue-reports/issues/811

**Comment by baumanab** [comment]
Thank you for letting us know.  A note has been added to the EKF project instructions and repo, which includes a workaround.
