### ISSUE TITLE
Typo in Intro to TF -> Transition to Classification

### ISSUE THREAD

**Issue by jessicayung** [udacity/sdc-issue-reports#86]
Bullet point 3: 'Used tf.placholder() and feed_dict to get input.'

-> should be tf.placeholder()
(missing an 'e')

**Comment by Brok-Bucholtz** [comment]
@jessicayung 

I added the missing 'e' to tf.placeholder().  BTW, telling us where the problem is, like "TF -> Transition to Classification" is super helpful!  Most people don't don't do that.  So, thank you! :)

**Comment by jessicayung** [comment]
Fab, thanks for sorting this out so quickly Brok! :)

**Comment by Brok-Bucholtz** [comment]
@jessicayung 

No problem!  I'm happy to help.
