### ISSUE TITLE
Instruction for Macport

### ISSUE THREAD

**Issue by kegan** [udacity/sdc-issue-reports#861]
Only project setup instructions for Homebrew is available. It would be good if there are instructions for Macport users too, since generally one cannot have Homebrew and Macport on the same system.

**Comment by baumanab** [comment]
Thanks for pointing this out. I'm not familiar with using macports. The only homebrew dependent step is in install-mac.sh. The first line reads:

```
brew install openssl libuv cmake
```

What would be the equivalent with macports?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
