### ISSUE TITLE
SDCND Term2, Simulator

### ISSUE THREAD

**Issue by kingkastle** [udacity/sdc-issue-reports#866]
P3 Kidnapped vehicle isn't working on my computer but same code works on reviewer' side

**Comment by kingkastle** [comment]
Dear Team,

For the SDCND Term2, P3 Kidnapped vehicle, my project that wasn't working, here is the video that reproduces how it works on my computer:

https://drive.google.com/file/d/0ByVEMD8Hdw5Cb1otZnFSOGR0emc/view

I submitted the project with the hope the reviewer would help me to dig into the errors that were causing problems, however, to our surprise, the project was working on his side smoothly.....

Link to review: https://review.udacity.com/#!/reviews/541172/shared

Would you mind to investigate this to find out why it is working on reviewer's side, but not mine?

Link to my code: https://github.com/kingkastle/Self-Driving-Car-ND/tree/master/Term2/P3%20-%20Kidnapped%20Vehicle%20Project

Thanks in advance!

Best,
Rafa

**Comment by cicaphus** [comment]
Thanks for letting us know about this, and sorry for the difficulties.  Were you able to find a solution?

**Comment by baumanab** [comment]
Thanks for letting us know and sorry for the difficulties.  Were you able to solve this?  We would like to look into this more.  Would you mind emailing selfdrivingcar-support@udacity.com?

**Comment by swwelch** [comment]
Hi @kingkastle! I'll follow up with you about this over Slack. Note that generally, reviews or support issues should be emailed to review-support@udacity.com or selfdrivingcar-support@udacity.com.
