### ISSUE TITLE
Typo error in Self driving car nano degree Term1 Lesson 8 section 30 "convolutional network in TensorFlow"

### ISSUE THREAD

**Issue by remoteblue** [udacity/sdc-issue-reports#867]
In the text, "For example, the first layer shapes the images from 28x28x1 to 28x28x32 in the convolution step. Then next step applies max pooling, turning each sample into 14x14x32." 

There is typo "28x28x32". It shall be 14x14x32.

**Comment by baumanab** [comment]
Thanks for bringing this up.  As a point of clarification, the current text is actually correct.  This reads:
 > For example, the first layer shapes the images from 28x28x1 to 28x28x32 in the convolution step. Then next step applies max pooling, turning each sample into 14x14x32.



- The data enters as 28x18x1, we then deepen to 28x28x32
- This is then narrowed by a factor of 2 (k=2) during maxpooling, with a resultant of 14x14x32
- This all takes place in the first layer, in two different steps.
