### ISSUE TITLE
Many confusing mistakes in formulas throughout Term 2, Lesson 7.

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#868]
With reference to Lesson 7, Unscented Kalman Filters.

Starting from Sec. 22, you introduce `n-with-sigma`, but don't say what it is; then use it inconsistently in the rest of the lesson.

In the video of Sec. 22, at 0:32,  you use different start and end indexes for the sum (`big-Sigma`) in the predicted mean and predicted covariance, but both sums should have the same endpoints, as suggested by the solution of the next programming exercise. I.e., assuming `n-with-sigma` is the number of sigma-points, then the sums should range from `1` to `n-with-sigma`.

You then have the indexes of the weights ranging from `0` to `n-with-sigma`, again, inconsistent (same video, at 0:54).

In Sec. 23, you now have all the indexes ranging from `1` to `n-with-sigma`.

Because of the above, it is nearly impossible to complete the programming exercise in Sec. 23 without "cheating".

Sec. 25, video at 2:55, again inconsistent end values for index `i`, between the predicted measurement mean and covariance. And again those are changed in the same formulas in Sec. 26.

Sec. 28. video at 1:21, now end-points for `i` are `0` and `2 times n-with-sigma`, which doesn't match the definition of the weights (among other things). Then in Sec. 29 the same `i` ranges from `1` to `n-with-sigma`.

**Comment by troyjlee** [comment]
To continue with this theme, also in the video of Section 22 at minute 0:50 the definition of the weights are given using n_sigma whereas I think you want to use n_aug here.  In the "helpful equations" in Section 23 you use n_a for the weight formulas, but again this is not defined (I assume it stands for n_aug).  

Also at minute 0:50 in the video of Section 22, in the formula for the weights the case i=1 is left out.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
