### ISSUE TITLE
Documentation error in Term 1 lesson 8 section 'convolution network in TensorFlow'

### ISSUE THREAD

**Issue by remoteblue** [udacity/sdc-issue-reports#869]
The comment " # Layer 1 - 28*28*1 to 14*14*32" shall be "32*32*1 to 14*14*32" in the following code

def conv_net(x, weights, biases, dropout):
    # Layer 1 - 28*28*1 to 14*14*32
    conv1 = conv2d(x, weights['wc1'], biases['bc1'])
    conv1 = maxpool2d(conv1, k=2)

    # Layer 2 - 14*14*32 to 7*7*64
    conv2 = conv2d(conv1, weights['wc2'], biases['bc2'])
    conv2 = maxpool2d(conv2, k=2)

**Comment by baumanab** [comment]
Thanks for bringing this up.  As a point of clarification, the current comments are correct. 

- The data enters as 28x18x1, we then deepen to 28x28x32
- This is then narrowed by a factor of 2 (k=2) during maxpooling, with a resultant of 14x14x32
- This all takes place in the first layer, in two different steps.
- The data enters layer 2 as 14x14x32 and is then deepened and narrowed two-fold, for a resultant 7x7x64.
