### ISSUE TITLE
College Algebra course not evaluating MathQuill expressions

### ISSUE THREAD

**Issue by iamsandesh** [udacity/sdc-issue-reports#870]
All quizzes in College Algebra course give error 'Error Message - “Something isn’t working properly. Please inform instructors.”' whenever the answer contains MathQuill expressions in them.

The issue occurs whenever you submit an answer to a quiz and the answer contains MathQuill expressions in them.

This issue is open for than a year now. There are multiple forum threads on the same. I have included them here for your reference:

1. https://discussions.udacity.com/t/error-message-something-isnt-working-properly-please-inform-instructors/193766/92

2. https://discussions.udacity.com/t/something-went-wrong-notify-instructors-on-forum/208839/10

**Comment by walesmd** [comment]
This course is scheduled to be deprecated in the near future; unfortunately, we don't have the resources at this time to dedicate to fixing this particular course (which is quite old and not related to our Nanodegree programs).
