### ISSUE TITLE
T2.L5.17 multivariate Taylor expansion

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#877]
First, in the two displayed equations the T(x) on the left hand side should be f(a+x).

Second, the formula given for the multivariate Taylor expansion is not suitable for the context.  h is a function from R^4 to R^3.  The Jacobian, in the convention you have adopted in the next lesson, will be a 3-by-4 matrix.  Thus the Jacobian should be multiplied by x-a on the right, not (x-a)^T on the left.

Also h is a vector valued function.  The second order term you write (x-a)^T D^2f(a) (x-a) is just a scalar.  

You should either specify that you are just giving the Taylor series for a multivariate scalar valued function, or state it correctly for a vector valued function.

**Comment by troyjlee** [comment]
For the first point, I should have said f(x) for the left hand side not f(x+a).  I see now the formula is the same as the one on the wikipedia page https://en.wikipedia.org/wiki/Taylor_series#Taylor_series_in_several_variables

Note that in the wikipedia page, this formula is for a scalar valued function, and Df(a) is the gradient of f, a column vector.  This makes sense.  However the formula is not compatible with how you have defined the Jacobian, or for vector valued functions as in the context of the discussion.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
