### ISSUE TITLE
Resources for exercise of Term 2 Lesson 11 unavailable for download

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#879]
Please provide a link to download the programming exercise of Term 2, Lesson 11 "Markov Localization". Especially, the data files in `data` directory. Debugging and experimenting with the program in a web browser is a waste of time. Need to be able to download it to run it on own, local environment.

Also see https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750

**Comment by fantauzzi** [comment]
Please provide a link to download the programming exercise of Term 2, Lesson 11 "Markov Localization". Especially, the data files in `data` directory. Debugging and experimenting with the program in a web browser is a waste of time. Need to be able to download it to run it on own, local environment.

Also see https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750

**Comment by baumanab** [comment]
Thank you for helping us track this.  Currently, the only practical workaround is the solution provided [here](https://discussions.udacity.com/t/text-files-for-the-markov-localization-exercise/242750).  Please let us know if this does not work for you.
