### ISSUE TITLE
Update the rubric of Kidnapped Vehicle project

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#880]
The rubric of the project seems related to an old version of the project. Rubric needs to be updated for the current version of the project, using the simulator. By the way, there is no "kidnapped vehicle", as far as I can tell, the project title may need update too.

See https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/2c318113-724b-4f9f-860c-cb334e6e4ad7/lessons/ff0810f5-583b-47b3-be49-074b37e443f4/project

**Comment by baumanab** [comment]
Thanks for letting us know about this.  It looks like the rubric has been updated to reflect use of the simulator.
