### ISSUE TITLE
T2.L7 rows and columns swapped in matrix definition

### ISSUE THREAD

**Issue by troyjlee** [udacity/sdc-issue-reports#882]
This is an error that seems to appear in all the programming assignments in Lesson 7.  In main.cpp in the definition of Xsig or Xsig_aug is not of the correct size.  The row and column indices should be swapped.  For example in chapter 18 the solution says:
MatrixXd Xsig_aug = MatrixXd(15, 7);
but the size should be 7-by-15.  This does not cause an error but it is still confusing.

**Comment by asimay** [comment]
+1, i also find in quiz Generating Sigma Points Assignment 1, 
in main.cpp, the MatrixXd Xsig = MatrixXd(11, 5);
but in ukf.cpp,  MatrixXd Xsig = MatrixXd(5, 11);
it's weird.

**Comment by baumanab** [comment]
Good catch!  These items have been corrected.
