### ISSUE TITLE
T2:setup Too many environment setup choices for beginners

### ISSUE THREAD

**Issue by river-wind** [udacity/sdc-issue-reports#883]
For Term 2, there are may possible development environments, which has resulted in many threads involving differences between environments, setup issues in particular environment setup, my RMSE is higher on windows than Ubuntu, etc.

Rather than suggesting the students pick an environment, and then providing instructions for various setups (Ubuntu, macos, Visual Studio, Win10 Bash, Docker, etc, etc), I think it would be more productive to provide instructions for 1 environment:  virtualbox with Ubuntu 16.04, and then build everything and run the simulator within the Ubuntu instance.  Other than the initial virtualbox installation steps being specific to the student's host OS, everyone would have the same environment, and new students wouldn't have to confusion of multiple choices to decide on.

If an  advanced student wants to set up a different environment, they still could, but the first few weeks of Term 2 would be made much simpler for everyone else.

**Comment by baumanab** [comment]
Thank you for this feedback.  We are actively reviewing environment and setup in an effort to streamline the process for students.  I'm not certain this will result in one recommended environment, but it should at least result in some clarification of the process and steps to fix/avoid common pitfalls.
