### ISSUE TITLE
Allow link to GitHub repository for Kindapped Vehicle Project submission

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#886]
Given that also the Kidnapped Vehicle Project (Term 2) adopted the simulator, consider to update the related instructions and change the project submission to allow submission of a GitHub repository. Currently you only allow submission of a single file.

**Comment by baumanab** [comment]
Thank you for this suggestion.  This is something we could consider.  Would you mind explaining your perspective on the benefit of allowing a repo submission instead of just ```particle_filter.cpp```?

**Comment by fantauzzi** [comment]
Constraining students to put all their code in `particle_filter.cpp` forces a specific design and code structure; contrariwise, allowing (like for *all* the other projects in the Nanodegree) to submit a repo, allows students to structure their code however they see fit, providing and editing .cpp files, header files, and other resources. The programming practice is a fundamental part of this Nanodegree program.

The constraint, specific to this project, was motivated by how reviewers used to test it: the student submission had to comply to a specific interface. Since the introduction of the simulator, that is not the case anymore. Reviewers now build the whole project, and connect to the simulator. Conformance of the project to a specific API is not required anymore.

**Comment by baumanab** [comment]
Thank you for explaining the rationale.  Your explanation brings up some great points.  I'm going to bring this up with the team and will update with feedback and relevant actions.  

Note:  Appears related to #725

**Comment by swwelch** [comment]
Hi @fantauzzi, this has been changed now, and Github submissions are permitted.
