### ISSUE TITLE
subscription paused, or past due

### ISSUE THREAD

**Issue by hedeya1980** [udacity/sdc-issue-reports#889]
When I was clicking on a link in the self-driving car nanodegree, I receive a message that "You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?"

**Comment by hedeya1980** [comment]
[Uploading screen_shot_Udacity.png...]

**Comment by baumanab** [comment]
My apologies for the technical difficulties.  The most effective way to resolve this is to contact selfdrivingcar-support@udacity.com.

**Comment by Ashwin-Kapes** [comment]
@hediya1980 Is your issue resolved?

**Comment by ritacapelaa** [comment]
I'm having this problem too.

**Comment by Sushant0612** [comment]
Me too

**Comment by baumanab** [comment]
Sorry this is happening, please contact  selfdrivingcar-support@udacity.com.

**Comment by baumanab** [comment]
Sorry for the frustration.  The most effective way to resolve this is to contact the support email for the iOS developer ND.
