### ISSUE TITLE
iOS Native Mobile App issue

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/sdc-issue-reports#89]
I am unable to access the Self-Driving Car course in the native iOS app. It was accessible to me a few days ago.

I uninstalled/reinstalled app to no avail.
I signed out/signed back in to the no avail.

I hope I'm doing something wrong. Thanks!

**Comment by Brok-Bucholtz** [comment]
@matthewzimmer 

The Self-Driving Car course is using our new classroom.  Sadly, this mean it's not yet supported on iOS.  Do you have a non mobile device you can use?

**Comment by matthewzimmer** [comment]
Thanks for clarification. Yes I do. But it was convenient when at the gym.
Safari/Chrome on iOS is clunky when running so I'll be looking forward to
the update. 😊

**Comment by Brok-Bucholtz** [comment]
@matthewzimmer 

It's no problem, sorry we don't have that feature yet.  I'll update this issue when I hear any news.
