### ISSUE TITLE
Term2 Lesson 13 Particle Filters, Section 9 Moving Robots quiz, incorrect code

### ISSUE THREAD

**Issue by JacquesRoth** [udacity/sdc-issue-reports#890]

**Comment by JacquesRoth** [comment]
The provided move method in the robot class does not modify the robot's position or orientation, but returns a new robot with the new values.  The lesson solution will not work as presented because of this.  It calls move with the expectation the robot's values are changed.  I think the best way to change the lesson solution would be to do something like:
myrobot = myrobot.move(deltaangle,dist)

**Comment by baumanab** [comment]
Thank you for bringing this up.  It did a fresh work-through of this exercise and took a closer look at the ```move``` method.  It does appear that the robot is changing position.  It's possible we have missed something.  Is it this line that is problematic?

```python
 # set particle
        res = robot()
        res.set(x, y, orientation)
```
It's true that this does initialize a new robot.  The updated values from the old robot are then set into the new robot.  This is the same process as creating a list and then assigning it back to another list object, such as done with p, p2, and p3 in this exercise.  Functionally it is the same as modifying the original object except that it gets rid of some issues that can occur in the namespace when actually modifying the same object.  Does that make sense?  If not, or if we have gotten something wrong, please let us know.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
