### ISSUE TITLE
UKF: Update Readme

### ISSUE THREAD

**Issue by adai183** [udacity/sdc-issue-reports#891]
The run command should be updated to use the simulator.

**Comment by baumanab** [comment]
Thank you for pointing this out.  To confirm, is this the README referred to? https://github.com/udacity/CarND-Unscented-Kalman-Filter-Project/blob/master/README.md

**Comment by cicaphus** [comment]
Would you mind clarifying which run command you are referring to?  This is my understanding of the process:
-  C++ code is compiled to an executable `UnscentedKF`, and that executable is run from the command  line with `./UnscentedKF`.	
- Once that is running, the user launches the simulator.

Is that correct?

**Comment by adai183** [comment]
Confirmed. I am referring to this README:
https://github.com/udacity/CarND-Unscented-Kalman-Filter-Project/blob/master/README.md.

Under the section Basic Build Instructions the run command is: 

> ./UnscentedKF path/to/input.txt path/to/output.txt

when it should say:

> ./UnscentedKF

**Comment by baumanab** [comment]
Thanks for clarifying.  Yes, previous versions used text file I/O.  The current version relies on I/O from the simulator.  This is now reflected in the README.
