### ISSUE TITLE
Lesson 10. Keras. Issue with code evaluation.

### ISSUE THREAD

**Issue by pharosproduction** [udacity/sdc-issue-reports#892]
Please check this forum thread. I have explained what's wrong there:
https://discussions.udacity.com/t/list-out-of-range/300194

**Comment by baumanab** [comment]
Thank you for the feedback.  There is more than one valid implementation.  The grader is looking for the implementation that conforms to the classroom lessons.  A note has been added to the solution code and classroom to inform students of another valid implementation.
