### ISSUE TITLE
Lesson 2 Search Quiz Bug

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#896]
The search algorithm implemented passes the test run and prints `[11, 4, 5]`.

However, on submission, the same input results in a failure  although it clearly produces the expected result:

```
search didn't return the expected output for:
grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0]]
```

**Comment by spgitmonish** [comment]
I am facing the same issue. Here is a gist: https://gist.github.com/spgitmonish/e8e3c7b7a53cc3fd53cacd3220972e96

**Comment by baumanab** [comment]
Thanks for pointing this out.  The grader looks at 3 matrices, the first of which is the one posted above.  The grader checks to see if the answer is == [11, 4, 5].  If it is, the test should pass.  I actually checked the code in the gist for all three matrices used by the grader, and they all pass.  It's not clear why the code in the gist is failing.  I'm wondering if it is a data type issue.  We are looking into it.

**Comment by baumanab** [comment]
This has been fixed.  A new version, in workspaces, is live in the classroom.
