### ISSUE TITLE
Term 3 Preditcion.I/O Recap missing vehicle for ID=1

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#897]
There is no vehicle with ID=1 in the json file. Only 2 predictions for ID=0 and another prediction for ID=0. So the correct answer of the quiz would be 3+

**Comment by anupriyachhabra** [comment]
I see the same issue

**Comment by ksmith6** [comment]
Duplicate of 895

**Comment by baumanab** [comment]
Thank you for report this, the issue has been addressed.
