### ISSUE TITLE
Term 3: Missing link for Data Driven Example - Trajectory Clustering

### ISSUE THREAD

**Issue by ChrisShepherd81** [udacity/sdc-issue-reports#898]
I can not find the link to the paper for "measures of similarity in detail" mentioned by Mahni Shayganfahr in the video.

**Comment by baumanab** [comment]
Thank you for letting us know.  The link to the paper does appear to be missing and we are working on addressing this.

**Comment by AndyAtUdacity** [comment]
Link has been added to [this node](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/a883a337-51c8-471b-a8cf-3911dc429166/concepts/fbe8638a-e90d-4564-a0f2-3548ff11d1c8?contentVersion=1.0.0&contentLocale=en-us)
