### ISSUE TITLE
Term 3 Behavior Planner incorrect goal setting

### ISSUE THREAD

**Issue by hulleywood** [udacity/sdc-issue-reports#899]
In the configure function of vehicle.py file of the provided code, self.goal_lane and self.goal_s are flipped resulting in self.goal_lane being set to the goal_s provided in the road data and vica versa. This can be fixed by using self.goal_lane = goal[1] and self.goal_s = goal[0].

**Comment by swwelch** [comment]
Thanks! I think this has been fixed now.
