### ISSUE TITLE
Possible Typo in Unit Test in Deep Learning assignment 1

### ISSUE THREAD

**Issue by autojazari** [udacity/sdc-issue-reports#9]
In [assignment 1](https://github.com/udacity/CarND-TensorFlow-L2/blob/master/lab_1.ipynb) there's the following section

```
# Problem 1 - Apply zero mean and zero variance scale to the image features
def normalize(data):
    """
    Normalize the data with zeo mean an equal variance
    :param data: The data to be normalized
    :return: Normalized data
    """
    ???

### DON'T MODIFY ANYTHING BELOW ###
# Test Cases
np.testing.assert_array_almost_equal(
    normalize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])),
    np.array([-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]),
    decimal=3)
np.testing.assert_array_almost_equal(
    normalize(np.array([-100, -30, -1000, -20, -20, -10, -10, -20, -10, -10])),
    np.array([9.5, 2.5, 99.5, 1.5, 1.5, 0.5, 0.5, 1.5, 0.5, 0.5]))
```

The unit test's expected result may not be correct
```
[-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]
```
Running `std()` on the result does not return ` 
```
np.array([-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]).std() != 1
``` 
Therefore even with the correct `normalize` implementation, the unit tests fail.

**Comment by autojazari** [comment]
http://stackoverflow.com/questions/40188922/implementing-zero-mean-and-zero-variance-in-numpy

**Comment by dalex01** [comment]
I'm also struggling with this definition :(

**Comment by autojazari** [comment]
My apologies: I wasn't able to update the description, so will add my notes here:

In [assignment 1](https://github.com/udacity/CarND-TensorFlow-L2/blob/master/lab_1.ipynb) there's the following section

```
# Problem 1 - Apply zero mean and zero variance scale to the image features
def normalize(data):
    """
    Normalize the data with zeo mean an equal variance
    :param data: The data to be normalized
    :return: Normalized data
    """
    ???



### DON'T MODIFY ANYTHING BELOW ###
# Test Cases
np.testing.assert_array_almost_equal(
    normalize(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])),
    np.array([-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]),
    decimal=3)
np.testing.assert_array_almost_equal(
    normalize(np.array([-100, -30, -1000, -20, -20, -10, -10, -20, -10, -10])),
    np.array([9.5, 2.5, 99.5, 1.5, 1.5, 0.5, 0.5, 1.5, 0.5, 0.5]))
```

The unit test's expected `[-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]` may not be correct.    `np.array([-0.4, -0.3, -0.2, -0.099, 0.0, 0.099, 0.199, 0.3, 0.4, 0.5]).std()` != 1.  Therefore even with the correct `normalize` implementation, the unit tests fail

Please see http://stackoverflow.com/questions/40188922/implementing-zero-mean-and-zero-variance-in-numpy

**Comment by Brok-Bucholtz** [comment]
@autojazari @dalex01 

The problem has been [changed](https://github.com/udacity/CarND-TensorFlow-L2/commit/2913f5a9a935d0ffb452a31279e789cedb170d17) to Min-Max scaling, including the unit tests.  Thanks for all your feedback.  Keep it up!
