### ISSUE TITLE
Term2, Localization, Kidnapped-Vehicle-Project starter code, prediction std's not properly provided or explained

### ISSUE THREAD

**Issue by JacquesRoth** [udacity/sdc-issue-reports#900]
Many discussions on the forum about this.  A GPS uncertainty is provided, but nothing for either  velocity or yaw rate, in the particle filter prediction code, and no information is provided about over what time period we might assume equals an equivalent GPS uncertainty.

**Comment by baumanab** [comment]
Thank you for reaching out about this.  The velocity and yaw are assumed noiseless in this project and noise is restricted to particle coordinates and heading.  Would you mind clarifying the statement?

> and no information is provided about over what time period we might assume equals an equivalent GPS uncertainty.

It may help for us to see some of the forum discussions.  Would you mind linking an example?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
