### ISSUE TITLE
Functional Safety, Lesson 9.1, wrong title

### ISSUE THREAD

**Issue by olegleyz** [udacity/sdc-issue-reports#901]
Dheeraj has wrong title on the 0:29 sec of lesson 9.1

**Comment by olegleyz** [comment]
In the animation with his name and job title it's written senrio instead of senior

Best regards,
Oleg Leyzerov

13 июля 2017 г., в 1:12, andrewsdc <notifications@github.com> написал(а):

Hi, thanks for looking at the functional safety beta. Can you be more specific about where the issue is and what the issue is? Are you referring to the lesson about the "hazard analysis and risk assessment" video 1?

And what is "title" referring to? Is it the video sub-titles? And what about the title is wrong? Thanks!

**Comment by andrewsdc** [comment]
ok, this will be fixed for the official course launch next week. Thanks for finding this
