### ISSUE TITLE
Term 3/Prediction/3.6: Trajectory Cluster Wrong Probability

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#902]
The probabilities of the clusters change after each update in the animation.

However, for the last animation step, the probabilities fail to sum to 1.0 and instead sum to 0.010.

**Comment by ksmith6** [comment]
See the screenshot showing the probabilities near the end of the video.

![Screen Shot 2017-07-11 at 9.41.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59658bdd8bab8b001fc2d986/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a371f1162a4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d1645d7dce3b42adb0d61bbb53ba208b4f83b4bfd84dd2f42f67b6d5db1063474f4dcbed5727a39841c95cff42e94f52a61a3062ee722431.png)

**Comment by baumanab** [comment]
Thank you for letting us know.  This has been noted below the video.
