### ISSUE TITLE
Term 3: Prediction/Process Models: Missing Process Noise Term w

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#903]
The Dynamic Bicycle Model with controller equations is missing the `+ w` term to account for process noise.

**Comment by ksmith6** [comment]
At 4:13, the narrator explains that all the models contain the additional process noise term *w*, but the dynamic bicycle model does not.  
See below: ![Screen Shot 2017-07-11 at 10.43.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59658bdd8bab8b001fc2d986/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a379ef0c2f52415f47bc21254d58eeb9cb74fce36f34985619e8d96d5676cf3517ffb98a4bbb05e8208b4f85b0be891ec1fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f242e84556a513366be374366e0a.png)

**Comment by mvirgo** [comment]
Fixed! Thanks for noting.
