### ISSUE TITLE
No output from Term 3 4.16 Implement a Behavior Planner

### ISSUE THREAD

**Issue by jendrikjoe** [udacity/sdc-issue-reports#906]
Every time when I hit test run in this coding challenge I only get the message 'Your code displayed no output'

**Comment by baumanab** [comment]
Thank you for letting us know about this.  The quiz is producing output in my classroom.  Would you mind taking another look to see if this issue persists?

**Comment by jendrikjoe** [comment]
Hello Andrew,

yes the problem is persisting.
It still states, that the code would not display any output eventhoug it contains cout statements.

Cheers,

Jendrik

On 25. Jul 2017, at 20:07, Andrew Bauman <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for letting us know about this. The quiz is producing output in my classroom. Would you mind taking another look to see if this issue persists?

**Comment by baumanab** [comment]
That is interesting.  Would you mind pasting or linking your code?  This will help troubleshoot the issue.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.

**Comment by jendrikjoe** [comment]
Sorry I was on business travel for two weeks.
I just wanted to copy my code, but now the output is working :)
So closing accepted.

On 2. Aug 2017, at 20:54, Andrew Bauman <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed as not actionable without updated information.
