### ISSUE TITLE
Term 2 MPC - installation of Ipopt - README.md

### ISSUE THREAD

**Issue by psnx** [udacity/sdc-issue-reports#907]
Hi,
I propose that the README.md be updated in line 34.

Installation of Ipopt requires sudo privileges. Without it the script will seemingly run right doing a lot of stuff but the installation will eventually fail. (it took me some time to figure out...)

Proposed wording in line 34 example:
Then call install_ipopt.sh with the source directory as the first argument, ex: `sudo bash install_ipopt.sh Ipopt-3.12.1.`

Cheers,
Tamas

**Comment by psnx** [comment]
Hi,
I propose that the README.md be updated in line 34.

Installation of Ipopt requires sudo privileges. Without it the script will seemingly run right doing a lot of stuff but the installation will eventually fail. (it took me some time to figure out...)

Proposed wording in line 34 example:
Then call install_ipopt.sh with the source directory as the first argument, ex: sudo bash install_ipopt.sh Ipopt-3.12.1.

Cheers,
Tamas

**Comment by domluna** [comment]
@psnx prepended sudo the install command in the README. Thanks for bringing this up
