### ISSUE TITLE
SDC, Term3, Lesson 4, point 10 (Code mistake)

### ISSUE THREAD

**Issue by Mahmoodsalah** [udacity/sdc-issue-reports#911]
Lesson URL:
https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/56274ea4-277d-4d1e-bd95-ce5afbad64fd/concepts/e9f08f5f-0b8f-488d-8940-45bc474b4913

wrong Indent in this line:
        costs.append({'state' : state, 'cost' : cost_for_state})

must be insde the loop not out loop

**Comment by baumanab** [comment]
Great catch!  This has been corrected.
