### ISSUE TITLE
Term 3 | Lesson 3 | I/O Recap

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#912]
The output JSON is incorrect showing both vehicles having an ID of 0

<img width="252" alt="screen shot 2017-07-14 at 9 28 43 pm" src="https://user-images.githubusercontent.com/3866405/28220065-bd23d602-68db-11e7-96ed-f3c0fcb75b30.png">

**Comment by DavidObando** [comment]
Especially important since later there's a question about the number of trajectories for the car with ID = 0.

**Comment by baumanab** [comment]
Thank you for reporting this.  Both the inputs and outputs have been corrected.
