### ISSUE TITLE
Term 3 Naive Bayes C++ quiz - issue in Load_State function

### ISSUE THREAD

**Issue by anupriyachhabra** [udacity/sdc-issue-reports#914]
In Naive Bayes C++ quiz implementation the Load_State function in main.cpp is not loading data properly from train_states.txt and test_states.txt properly. Probably the reason for this is istringstream is not used properly for comma (',') separated data. I have fixed this in my solution, please have a look at my solution and fix this method for other students

**Comment by lengly** [comment]
Yeah, I met the same issue, and that's it.

**Comment by YCSU** [comment]
Yes, I had the same issue. The data is separated by comma (',') instead of space, and this causes the problem.

**Comment by naokishibuya** [comment]
I had the same issue.  My workaround as follows:

vector<vector<double> > Load_State(string file_name)
{
    ifstream in_state_(file_name.c_str(), ifstream::in);
    vector< vector<double >> state_out;
    string line;
    
    while (getline(in_state_, line)) 
    {
    	
    	istringstream iss(line);
    	vector<double> x_coord;
    	double state1 = 0;
	    double state2 = 0;
	    double state3 = 0;
	    double state4 = 0;
	    iss >> state1;
	    x_coord.push_back(state1);
	    if (iss.peek() == ',') iss.ignore();
	    iss >> state2;
	    x_coord.push_back(state2);
	    if (iss.peek() == ',') iss.ignore();
    	iss >> state3;
    	x_coord.push_back(state3);
	    if (iss.peek() == ',') iss.ignore();
	    iss >> state4;
	    x_coord.push_back(state4);
	    if (iss.peek() == ',') iss.ignore();
	    state_out.push_back(x_coord);
    }
    return state_out;
}


It checks the existence of ',' and ignore it to move on.

**Comment by yosoufe** [comment]
I have the same issue

**Comment by baumanab** [comment]
@anupriyachhabra  Would you mind sharing your solution?  I plan on making a note of this issue and how to solve it, in the classroom.

**Comment by anupriyachhabra** [comment]
Sure @baumanab , following is my load_state function
`vector<vector<double> > Load_State(string file_name)
{
    ifstream in_state_(file_name.c_str(), ifstream::in);
    vector< vector<double >> state_out;
    string line;
    
    while (getline(in_state_, line)) 
    {
    	istringstream iss(line);
    	vector<double> x_coord;
    	while (iss) {
    	    string s;
    	    if (!getline(iss, s, ',' )) break;
    	    x_coord.push_back(stod(s));
    	    
    	}
	    iss.clear();
	    state_out.push_back(x_coord);
    }
    return state_out;
}`

**Comment by baumanab** [comment]
Thank you!  I'll work on a fix.

**Comment by baumanab** [comment]
A note has been added to to the classroom.  Thank you all for your help!

**Comment by dm1299** [comment]
vector<vector<double> > Load_State(string file_name)
{
    ifstream in_state_(file_name.c_str(), ifstream::in);
    vector< vector<double >> state_out;
    string line;
    
    while (getline(in_state_, line)) 
    {
        vector<double> x_coord;
        char* cstr = &line[0u];
        char *token = std::strtok(cstr, ",");
        while (token != NULL) 
        {
            x_coord.push_back(atof(token));
            token = std::strtok(NULL, ",");
        }

	    state_out.push_back(x_coord);
    }
    return state_out;
}

**Comment by billchenxi** [comment]
Guys, which one works???
