### ISSUE TITLE
Missing content on Term 3 Lesson 5

### ISSUE THREAD

**Issue by bguisard** [udacity/sdc-issue-reports#915]
Lesson 5.25 is empty.

https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/db4b83a1-b304-4355-92c7-66e973102079/concepts/95a6222c-595c-4ceb-a994-654821d4fcd4

**Comment by binliu-base** [comment]
+1

**Comment by baumanab** [comment]
Thank you for reporting this.  The content is currently under construction.

**Comment by baumanab** [comment]
This content is now populated.
