### ISSUE TITLE
T2.L3-25

### ISSUE THREAD

**Issue by davinderc** [udacity/sdc-issue-reports#916]
After submitting and passing the quiz, and moving on, the entered program disappears when coming back later to check it. More than 1 user has observed this behavior.

**Comment by baumanab** [comment]
Thank you for reporting this.  This appears to be something that is classroom wide and we are working towards a solution.

**Comment by baumanab** [comment]
This has been fixed since my previous comment.  Please let us know if you see this behavior again.
