### ISSUE TITLE
Typo: `classifier.py` should be `classifier.cpp`

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#918]
In Term 3, Lesson 3 (Prediction), Video #16 (Implement Naive Bayes C++), the *Instructions* area says:

1. Implement the train(self, data, labels) and predict(self, observation) methods in the class GNB in `classifier.py`.

It should be changed to `classifier.cpp`.

**Comment by baumanab** [comment]
Excellent catch!  This is now corrected and thanks for pointing it out.
