### ISSUE TITLE
Missing Quiz for Term 3, Lesson 4, Video 8

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#919]
The video prepares the viewer to enter their own states for the finite state machine, but the content immediately transitions to the next video without prompting the user for the quiz.

**Comment by baumanab** [comment]
Thank you for letting us know.  It looks like the quiz is in video 9 and that video pauses after completion.  Would you mind taking another look to verify and letting me know if I have missed something?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
