### ISSUE TITLE
Udacity modal "What is your primary goal in taking this Nanodegree?" keeps popping up

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#92]

**Comment by rm51** [comment]
I answered this already I'm pretty sure today or yesterday. And now I see it again. It would be good if there were some way to keep track of whether I've answered or not. I don't think this is new because I noticed it before as well.

**Comment by rm51** [comment]
<img width="360" alt="screen shot 2016-11-03 at 10 31 31 pm" src="https://cloud.githubusercontent.com/assets/7563076/19992601/b4275980-a215-11e6-98d2-1d1256839156.png">

**Comment by Brok-Bucholtz** [comment]
I talked with @rm51, she said she will post more information to help debug the issue.

**Comment by rm51** [comment]
I spoke to two other people in slack and they said they've also seen the same problem.

**Comment by giladgressel** [comment]
this regularly happens with me as well.
along with a lot of unwanted surveys and advertising pitchs (I've closed down the VR nanodegree pitch at least 10 times)

**Comment by dhruvp** [comment]
Ok asking the team responsible to take care of this. Sorry for the issues.

**Comment by dhruvp** [comment]
This is now fixed. Thanks!
