### ISSUE TITLE
Term 3, Lesson 5, Section 24. Wrong result + typo

### ISSUE THREAD

**Issue by carlosgalvezp** [udacity/sdc-issue-reports#921]
`evaluate_quintic.py` has the wrong results as answers, therefore failing the test. 

Confirmed by 3 students at the time of writing:

https://discussions.udacity.com/t/are-the-answers-in-5-24-polynomial-generation-correct/309083/3

Also, the Equation shown in the Tips section has a typo. For the (3x1) vector on the right (b vector in Ax = b form), the second element should be:

`sf_dot - (si_dot + si_ddot * T)`

Instead of:

`sf_dot - (si_dot * T + si_ddot * T)`

**Comment by carlosgalvezp** [comment]
Sorry, Section 24, not 25

**Comment by baumanab** [comment]
Thank you for reporting this.  It looks like this post was made when term 3 was still in beta.  The content described here no longer corresponds to content in the classroom.  Please let us know if we have missed something, but it looks like this is resolved.
