### ISSUE TITLE
Typo in Video.  Term 3, Lesson 5, Video 4.

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#924]
Typo in video saying "Potential feld" instead of "Potential *field*".

**Comment by ksmith6** [comment]
![Screen Shot 2017-07-17 at 8.47.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59658bdd8bab8b001fc2d986/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a370f1162c4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5d1645d7dce3b42adb0d61bbb53ba208b4f83b4bfd84dd2f42f67b6d5db1063474f4dcbed5727a29f41c95df64be24957a1133064e0712431.png)

**Comment by justineudacity** [comment]
This issue has been fixed. Thanks for reporting this!
