### ISSUE TITLE
Lesson 11 Session 21

### ISSUE THREAD

**Issue by karanj1** [udacity/sdc-issue-reports#925]

**Comment by karanj1** [comment]
https://discussions.udacity.com/t/lesson-11-session-21-observation-model-introduction/311252/2

**Comment by baumanab** [comment]
![image](https://user-images.githubusercontent.com/4316306/31738663-3ecfd3f8-b400-11e7-85f4-c9fcd7a977c9.png)

the circled term and the boxed (yellow) terms should be:

![image](https://user-images.githubusercontent.com/4316306/31739053-762f9df0-b401-11e7-9702-242984173c33.png)

**Comment by baumanab** [comment]
This has now been corrected.
