### ISSUE TITLE
UX of code editor is not good enought for quizes

### ISSUE THREAD

**Issue by pkol** [udacity/sdc-issue-reports#926]
I've several usability issues with code editor used for quizes. (for example, quiz in  term2, lesson 5, point 12 "laser measurements part 3").

1)On my screen (Hull HD) code editor only uses 1/4 of screen - there is a lot of code to read/write and doing it in so small window is frustrating

2) Editor window has it's own scroll bars independent from main browser's scroll bar.

3) There is no (at least known for me) way to switch between files using keyboard only. 

I see 2 possible improvements:
A) make code editor fullscreen
B) provide quizes in github or as a ZIP file so I could easily run them locally

**Comment by baumanab** [comment]
Thank you for the feedback. We will bring this up with the classroom experience team.
