### ISSUE TITLE
Term3: Behavior Planning C++ Exercise

### ISSUE THREAD

**Issue by gtg162y** [udacity/sdc-issue-reports#929]
In the behavior planning exercise (towards the end of the lesson 4), looks like the vehicle.h and road.cpp files are identical. Vehicle.h seems wrong as it doesn't even have the vehicle class definition inside.

Also it'd be nice if there is at least some guidance with regards to how to do this exercise. Right now there is almost none.

**Comment by baumanab** [comment]
Thanks for letting us know about this.  It looks like vehicle.h and road.cpp files are now distinct.  It also looks like the vehicle.cpp code now contains guidance, via code comments, on how to complete the exercise.  Would you mind verifying that the files are distinct?  Please also let us know how helpful the guidance is in completing the exercise.

**Comment by gtg162y** [comment]
Yes it's fixed. But there's a typo in the function Vehicle::realize_prep_lane_change, delta needs to be 1 for "R" and -1 for "L."

Also, the guidance is still not that clear. It'd be alot more helpful to have some more info. on how to properly implement it. Cause there are ways of doing it without cost function, but afaik that is not the goal of the exercise.

**Comment by baumanab** [comment]
It looks like the delta signs need to be reversed for the "void Vehicle::realize_lane_change" as well?  Does that make sense? Would you mind clarifying this statement?

>  Also, the guidance is still not that clear. It'd be alot more helpful to have some more info. on how to properly implement it. Cause there are ways of doing it without cost function, but afaik that is not the goal of the exercise.

What information, in particular, would be helpful?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
