### ISSUE TITLE
The following error(s) occurred: Attempting to publish draft that does not exist with id: 10323548 in Atlassian

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#93]
<img width="997" alt="screen shot 2016-11-04 at 10 20 02 am" src="https://cloud.githubusercontent.com/assets/7563076/20008793/517357c2-a278-11e6-93b5-7196378beaaf.png">

**Comment by rm51** [comment]
I was trying to create a new questions when I got that error.

**Comment by Brok-Bucholtz** [comment]
@rm51 

Are you still seeing this error or are you able to repeat the error?

**Comment by rm51** [comment]
No, It's working now. Thanks for checking.
