### ISSUE TITLE
Term3, Lesson5, Section 21 Mistakes Derivation in Derivation of Coefficients

### ISSUE THREAD

**Issue by jendrikjoe** [udacity/sdc-issue-reports#930]
https://discussions.udacity.com/t/lesson-5-21-one-coefficient-wrong/311879

**Comment by baumanab** [comment]
Thank you for reporting this.  It looks like this is a duplicate of #923

**Comment by jendrikjoe** [comment]
Hello Andrew,

the mistake I detected is later in the video, than the one from #923.

Cheers,

Jendrik

On 25. Jul 2017, at 19:37, Andrew Bauman <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for reporting this. It looks like this is a duplicate of #923<https://github.com/udacity/sdc-issue-reports/issues/923>

**Comment by baumanab** [comment]
Thank you for reporting this.  This has been corrected.
