### ISSUE TITLE
Problem With Path Planning Project Code

### ISSUE THREAD

**Issue by dehavenm** [udacity/sdc-issue-reports#931]
For the path planning project, I've tried running some simple code to test the provided functions for converting between Cartesian and Frenet coordinates. Yet whenever I try doing anything either getFrenet or getXY, I get the error "Segmentation fault (core dumped)". The code I'm trying to run is as follows:

vector<double> point = getFrenet(car_x, car_y, car_yaw, map_waypoints_x, map_waypoints_y);

std:cout << car_s << ", " << car_d << ", " << point[0] << ", " << point[1] << "\n";

vector<double> point = getXY(car_s, car_d, map_waypoints_s, map_waypoints_x, map_waypoints_y);

std:cout << car_x << ", " << car_y << ", " << point[0] << ", " << point[1] << "\n";

When I'm not running anything involving those functions, the code appears to work properly with the simulator. What's going on here? Everything I'm passing to the functions was from the data coming off of the simulator, which has been coming through properly as far as I can tell. Is there something wrong with the project code? Thank you.

**Comment by baumanab** [comment]
We are looking into this. Is this still an ongoing issue?  Please let us know if you have any additional information to add.

**Comment by baumanab** [comment]
It doesn't look like there is an issue with the project code.  I'm closing this for now, but please let us know if this is impeding your ability to complete the project.
