### ISSUE TITLE
Specify Scaffolding Code in UKF Project

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#932]
My UKF project was rejected because I accidentally modified the measurement noise parameters in an effort to minimize the RMSE. The oversight is entirely my fault; however, I think it would be helpful to include `// DO NOT MODIFY` comments above the pertinent lines in the starter code. Additionally, the rubric should explicitly state which values must not be modified. If the instructions had been more specific, it would have spared me hours of wasted parameter tuning, and the reviewer would not have spent time on a wasted submission.

**Comment by baumanab** [comment]
That does seem helpful.  Comments have been added before and after the initial scaffolding in ukf.cpp.
