### ISSUE TITLE
Clarify FG_eval Function

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#933]
FG_eval is a very strange function and not adequately explained. I suspect that vars is a previous estimate and fg is a slightly improved estimate (plus one element set aside for the cost) based on something like Jacobi iteration. Even though I've studied such techniques before, I stared at this code for hours before I figured that out. This is also the explanation for why we care about earlier equations like estimating epsi based on the previous epsi value, which seemed irrelevant when introduced.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
