### ISSUE TITLE
Update version of Keras in Udacity starter kit Docker

### ISSUE THREAD

**Issue by ooleksyuk** [udacity/sdc-issue-reports#934]

**Comment by ooleksyuk** [comment]
The docker container that we are given to use to create AWS instance or download locally with starter kit has an outdated version of Keras that may cause misunderstanding. Function from class Sequential `def fit` takes as one of the param `epochs`. The old version of Keras uses `nb_epochs` all lectures use `epochs`. Here is a github reference to the change in Keras: https://github.com/fchollet/keras/blob/master/keras/models.py#L843

**Comment by domluna** [comment]
@ooleksyuk The versions are based by what's available in the current classroom, this should be upgraded soon. Keras doesn't have look it has versioned docs which makes figuring out the API a little tricky for older versions.

**Comment by ooleksyuk** [comment]
sounds good. thank you for the update @domluna

**Comment by subodh-malgonde** [comment]
FYI -  Keras 1.2 documentation can be found [here](https://discussions.udacity.com/t/keras-1-2-documentation/244223). I think its worth mentioning this in the classroom material until the versions get upgraded. The Keras website has docs for v2.x, which has breaking API changes as compared to v1.2

**Comment by baumanab** [comment]
Thank you for letting us know about this.  This is being closed out since upcoming changes to the classroom should resolve this issue.
