### ISSUE TITLE
IPOPT requires --with-openblas on some Macs

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#936]
Hi, I am a forum mentor. There were a couple of students who could not get IPOPT to work for them for about a week. The code resulted in an error:

> Listening to port 4567
> Connected!!!
> mpc(4561,0x7ffff1eed3c0) malloc: *** error for object 0x7f911e007600: incorrect checksum for freed object - object was probably modified after being freed.
> *** set a breakpoint in malloc_error_break to debug

This is the relevant discussion on the forum [Incorrect checksum for freed object](https://discussions.udacity.com/t/incorrect-checksum-for-freed-object/313433/19).

They had followed the instructions to install ipopt. Upgrading ipopt with `--with-openblas` fixed the error.

    brew upgrade ipopt --with-openblas

Please add these note in the project instructions so that other students do not waste time on this.

**Comment by baumanab** [comment]
Thanks for reporting this. I have updated the tips and tricks in the classroom as well as the project README.
