### ISSUE TITLE
Term3 Prediction. Little fix

### ISSUE THREAD

**Issue by kingkastle** [udacity/sdc-issue-reports#937]
According to the picture attached, this should be "id": 1

**Comment by kingkastle** [comment]
![Selection_536.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a15a92e39c9a2000d1dc2b/125516c66e82c728ace21e0d46db9196268197a080e78016f70bb2d86b56357c2301a03f32dfa17de7122253565748ff40500b40f8ab892ba6b63a72890e0affcd7f1d2598694ef1e1c84afd13b032884e8fb7b98a4cc7eb3f20ee8a8b4c3b0c48.png)

**Comment by kingkastle** [comment]
Disregard this issue, two trajectories are available for id: 0

**Comment by baumanab** [comment]
Thanks for reporting this and for following up.  This has also been reported in 895 and 897 and we are currently reviewing.
