### ISSUE TITLE
Term 3: Behavior Planning C++ Exercise bug (with solution)

### ISSUE THREAD

**Issue by buffos** [udacity/sdc-issue-reports#938]
In main.cpp line 44, where you initialize the  configuration vector , MAX_acceleration is in the wrong position. 

In vehicles.cpp configure function its expected as the third argument so line 44 should change to 

vector<int> ego_config = {SPEED_LIMIT,num_lanes, MAX_ACCELERATION, goal_lane, goal_s};

**Comment by DavidObando** [comment]
Config creation:
```
vector<int> ego_config = {SPEED_LIMIT,num_lanes,goal_s,goal_lane,MAX_ACCEL};
```
Config usage:
```
    target_speed = road_data[0];
    lanes_available = road_data[1];
    max_acceleration = road_data[2];
    goal_lane = road_data[3];
    goal_s = road_data[4];
```
Consider instead using strong typing, a `CarConfiguration` class for example.

**Comment by buffos** [comment]
I am just reporting that there is a problem in the order of fields. If you apply the code like that you will try to read the goal_s and you will always get the max_acceleration.

I think you did not understand the bug.

**Comment by DavidObando** [comment]
@buffos hey dude take it easy, I'm a student too, and the code I pasted above is literally from the udacity sample we're both reporting a bug on.

That's the collaborative nature of open source / open development.

**Comment by buffos** [comment]
I know. I thought you were writing it as a solution to the problem. Don't worry I am always taking things cool. Just keeping texts short.

**Comment by ibrahim-mo** [comment]
This appears to be fixed.
