### ISSUE TITLE
Term 3 Path Planning Project: should pass vector by ref, not value

### ISSUE THREAD

**Issue by cs4nd13** [udacity/sdc-issue-reports#940]
In main.cpp, there are a few functions with signatures like this:

int NextWaypoint(double x, double y, double theta, vector<double> maps_x, vector<double> maps_y)

This specifies that every time the function is called, complete copies of vectors maps_x and maps_y are created and made available to the function.  But it is not necessary to make these copies; creating them merely consumes CPU cycles.

The function signature should be changed to:

int NextWaypoint(double x, double y, double theta, const vector<double> &maps_x, const vector<double> &maps_y)

In this case, references to the two vectors are passed to the function, which is a lot more efficient than making copies.  The "const" guarantees that the function won't modify these vectors.

Note that ClosestWaypoint, getFrenet, and getXY also have this problem.

**Comment by baumanab** [comment]
The changes have been made.  Thanks for suggesting this improvement!
