### ISSUE TITLE
Term 3 Path Planning Project: unnecessary calls to sqrt

### ISSUE THREAD

**Issue by cs4nd13** [udacity/sdc-issue-reports#941]
In main.cpp, the ClosestWaypoint() function calls the distance() function, which in turn calls sqrt().  However, ClosestWaypoint does not really need the distance; it could make do with the square of the distance (that is dx*dx + dy*dy), which eliminates the sqrt calculation.  Or perhaps the Manhattan distance (abs(dx)+abs(dy)) would be sufficient.

In any case, it is worth putting a bit of thought into this, since ClosestWaypoint is called quite a bit.  And if the maps_x and maps_y vectors are large (because the original waypoints were densely resampled, for instance), the cost of computing so many sqrts might be significant (or not, but either way, learning to eliminate unnecessary sqrt calls seems like a good habit to develop).

**Comment by baumanab** [comment]
This is a good suggestion. Have you tried this alternative approach?  How did it go?

**Comment by cs4nd13** [comment]
I made the change to use the square of the distance; all I can say for sure is that it didn't actually break anything.  I didn't run a timing test, but I doubt it made a significant difference.  It's more along the line of developing good habits.

**Comment by baumanab** [comment]
If you are willing to put in a pull request for alternative scaffolding, we can test it and consider incorporating changes. Please make the pull request on a branch other than master and @baumanab

**Comment by baumanab** [comment]
I'm going to close this out in lieu of a pull request on the repo make sure to @ me or I may not see it.  If you don't hear something back within a couple of days of making the pull request, please @ me on this thread.
