### ISSUE TITLE
Term 1, Lesson 6, Softmax

### ISSUE THREAD

**Issue by shmulik-willinger** [udacity/sdc-issue-reports#942]
The example of two-dimensional array has wrong output

**Comment by shmulik-willinger** [comment]
The example of two-dimensional array has wrong output
The output should be according to the rows and not the columns

**Comment by shmulik-willinger** [comment]
![issue942.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59746b1462b002001f6fb799/125516c66e82c728ace21e0d46e187893687dafdddabf301b44fff9e2c4533317346f67320dcb171e7147850570b4aa813585f44fcff8b28f4b72e6c981e5ab38532022d8c6853beb2901db90bbb258b4f8db6be884fc7e83522f5c6.jpg)

**Comment by baumanab** [comment]
Thank you for the feedback.  Would you mind clarifying what you mean? The classroom quiz and text seem consistent and correct.  I could be missing something though, so please let me know if that is the case.

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
