### ISSUE TITLE
Allow origin not present

### ISSUE THREAD

**Issue by ivan-ushakov** [udacity/sdc-issue-reports#944]
I see following error at https://classroom.udacity.com/nanodegrees/nd013:

XMLHttpRequest cannot load https://guru-ws.udacity.com/socket.io/?token=...&EIO=3&transport=polling&t=Lrmz8rH. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://classroom.udacity.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by baumanab** [comment]
Thanks for reporting this.  This seems to be the case with the classroom landing pages in general, and we will look into this further.

**Comment by baumanab** [comment]
This has been reported to our classroom experience team.
