### ISSUE TITLE
Term 3 Path Planning Project: incorrect angle test in NextWaypoint

### ISSUE THREAD

**Issue by cs4nd13** [udacity/sdc-issue-reports#946]
In the NextWaypoint() function, used by getFrenet() (not sure of the reason for the inconsistent capitalization convention, by the way), there is the line:
 if(angle > pi()/4)
I believe this should be:
 if(angle > pi()/2)

(pi/2 is 90 degrees, which makes sense in this context; pi/4 is 45 degrees, which doesn't really, so if pi/4 is intentional, a comment would be helpful).

**Comment by cs4nd13** [comment]
Not sure if this is correct.  I'm closing this  so I can study the issue some more.

**Comment by baumanab** [comment]
Thanks for following up.  Please let us know what you find.
