### ISSUE TITLE
Awesome Docker starter guide for term 2

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/sdc-issue-reports#948]
One student posted an awesome starter guide for Windows users for term 2 using Docker, in this post -[Getting Started with Docker and Windows for the EKF Project - a guide](https://discussions.udacity.com/t/getting-started-with-docker-and-windows-for-the-ekf-project-a-guide/320236). Would be great if a link to this post is included in the project README.

**Comment by baumanab** [comment]
This is really cool, thank you for passing it along!

**Comment by baumanab** [comment]
I've recently walked through the Windows Ubuntu Bash process.  I'm going to walk through this next.  We will use this information to inform updates to project READMEs and instructions.  It's really cool that the student provided this, it's extremely helpful.

**Comment by baumanab** [comment]
System setup guides and troubleshooting are in the process of being put into a concept that will be available in the classroom.  Since this is in the Udacity internal ticket system, I'm closing this out.
