### ISSUE TITLE
Reproducability of Traffic Sign Data

### ISSUE THREAD

**Issue by karlobermeyer** [udacity/sdc-issue-reports#949]

**Comment by karlobermeyer** [comment]
For the sign classification project, students are sent to https://d17h27t6h515a5.cloudfront.net/topher/2017/February/5898cd6f_traffic-signs-data/traffic-signs-data.zip1 for data. In the spirit of providing full reproducability/transparency in the project report, students should be informed of how this data was obtained from the original GTSRB data at http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset1 . For example, was there cropping/centering/squaring involved and if so, how? Ideally, it would be nice to be able to reference the script(s) used to prepare the data. A student cannot legitimately claim performance on the original GTSDB when really they got the data from a 3rd party (Udacity) and have no idea how that party may have modified it.

**Comment by baumanab** [comment]
This is a good point.  The developer who prepared the images indicated that they were resized to 32 X 32 and centered.  It may be an informative exercise to start from the original data set, prepare the data, and feed that into the project.  This way you can see the impact, if any, of different manipulations.
