### ISSUE TITLE
inbound_nodes should say inbound_neurons

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#95]
On this page:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/9957907d-e045-4cc7-b527-1536388471e8

In miniflow.py, the comment in Add.forward says inbound_nodes, but the property is called inbound_neurons.

**Comment by Brok-Bucholtz** [comment]
@gilcarmel 

Thanks for the feedback!  I changed the comment from inbound_nodes to inbound_neurons.
