### ISSUE TITLE
T3, L09.7 - Transposed Convolutions

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#950]
1. Not sure, but these videos (in this section and before/after that) could perhaps benefit from more visualizations/graphics of the actions being performed. It's static images currently.

2. In the video, it's mentioned "property of differentiability". This could be explained further, as I believe this has a more theoretical/conceptual reference and might not be something easily understood.

**Comment by baumanab** [comment]
Thanks for the feedback on this and apologies for the lag on response.  With respect to transposed convolutions, do you think a high level explanation of transposing known information onto a sparse matrix, a brief discussion of upsampling/interpolation, and some resources (such as a animations) would be effective?

**Comment by baumanab** [comment]
Thanks for the help!  Additional explanation has been added.
