### ISSUE TITLE
T3, L09.10 Skip Connections

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#952]
It might help to have an associated quiz to implement something basic if possible.

It might also help to explain where and how the layers are added to non-adjacent layers. Like in the benchmark example, one is connected to the last layer, while the second is connected to the penultimate layer in that example. Should it always be between the initial convolution layers and then the upscaled layers, in the order of occurrence? Or is that something to be experimented with?

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
