### ISSUE TITLE
T3, L10.6 IoU Quiz Error

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#955]
Running the solution provided gives the following error -

```
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f73446ce860>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 581, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'
```

**Comment by domluna** [comment]
@sahiljuneja can you post your solution? I can't seem to reproduce the error.

**Comment by sahiljuneja** [comment]
I did the same thing. Copy-pasted the one in `solution.py` and then clicked on "Test Run".

**Comment by sahiljuneja** [comment]
Okay, weird.

1. Opened the page again. I reset the quiz. Copy-pasted it again. Ran it. It gave the error. 

2. Closed tab. Reopened it. This time deleted the contents of `quiz.py`. Copy-pasted the solution. Ran it. No errors. 

Seems to be working now. So weird.

**Comment by sahiljuneja** [comment]
I guess I will close this for now. Thanks!
