### ISSUE TITLE
T3, 11.10 Freezing Graphs

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#958]
This section contains a lot of concepts which are just talked over but not explained properly.

1. Protobuf file: Not really sure where and how this is generated since we never covered this before as far as I remember. 

2. Nodes related to training: A visual with an example we can relate to would help, because it's a bit confusing to visualize what these nodes are. Especially since we never covered how TF works behind the scenes.

3. Related to point 1 here, but `.pb` and `.pbtxt` file formats and what they represent. No clue what they are.

4. Small request: Giving an example of some of the operations involved, and which ones get removed would help to understand the concept better.

I request the above because it would be difficult to attempt at optimizing anything on our own if we wanted to without understanding few more details. Such things help with employers, and with the projects too.

**Comment by baumanab** [comment]
related to #959

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
