### ISSUE TITLE
T3, 11.11 Graph Transforms

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#959]
Is this supposed to be 4 lines long? It links to a GitHub README. So as students are we expected to understand that GitHub page ourselves and somehow use it on our own? Or is the section not important enough to use/remember/refer to and can be ignored?

I ask because the GitHub page has lots of details we haven't covered in the ND and would be new to us. So not sure if we should study those and how they can help us or what's important for now. 

I think there's quite a bit of important content on that page that can be combined with this lesson and be converted to exercises that students could work through step-by-step with a sample DL model?

**Comment by baumanab** [comment]
Thanks for letting us know about this.  I can see the conundrum.  I've altered the text in the classroom to clarify.
