### ISSUE TITLE
Mentor Dashboard - Not receiving email notifications for mentor messages

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#96]
Would really appreciate it if we could get email notifications whenever our mentor sends/replies to messages.

**Comment by Deborah-Digges** [comment]
This already happens currently I think. I do get notifications. Check other mail tabs like Social?

**Comment by sahiljuneja** [comment]
I use the old/standard inbox so it's all on one page for me. But yeah, I never got an emails in the order of "Your mentor has replied/sent you a message" of sorts. Not even in Spam by mistake.

**Comment by Deborah-Digges** [comment]
Oh that's strange! I do get mails titled "You have 2 unread messages from your mentor." The sender is mentorship-support@udacity.com

**Comment by Deborah-Digges** [comment]
Maybe if you're online while the messages were sent, you don't get a mail?

**Comment by rm51** [comment]
Perhaps something can be added to the website so that when students are logged in they can see whether they have unread messages or not.

**Comment by sahiljuneja** [comment]
It does show on the website in that case. A small number on the top right which indicates number of unread messages, that your mentor sent you. However, it's inconvenient not to get an email because  I might not check the course website that often if, let's say, I am working on my project or working on something else. Getting an email is better because of notifications I get on my phone and my desktop instantly notifying me of it. But they are working on it, so all good 👍

**Comment by swwelch** [comment]
Hi All! I think this is duplicated on the Mentorship Trello board. If you are a mentor, please file issues with the application there going forward!

**Comment by sahiljuneja** [comment]
@swwelch Can we (mentors) get access to that Trello Board?
