### ISSUE TITLE
T3, 11.15 Reusing the graph

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#960]
Not sure if I missed it, but I think saving the optimized graph was covered, right?

Maybe an additional section which consolidates all the different techniques and how to actually implement them directly in TF and how to save the optimized graph might help?

Plus, currently, the sections which discuss optimizations don't clearly mention how the optimization is done. It doesn't seem it's done in the code, but it's done separately? Bit of a confusion there.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
