### ISSUE TITLE
T3, Lesson 11 How to run everything in AWS AMI?

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#963]
How exactly are we supposed to run the commands mentioned in the sections?

Like for example, in 11.10
```
~/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=base_graph.pb \
--input_checkpoint=ckpt \
--input_binary=true \
--output_graph=frozen_graph.pb \ 
--output_node_names=Softmax
```

That's how it's given in the section. Trying to run it throws an error 

`freeze_graph` command not found.

Same goes for others. I mentioned that in a previous issue that there should be another section consolidating all of these, showing how they should be run, and how it's all saved. Can we please have something like that?

Because right now it's honestly not clear how to follow along with this lesson using the AMI. Hopefully, I haven't missed out anything. Let me know if I did! Thanks!

**Comment by baumanab** [comment]
related to #965

**Comment by sahiljuneja** [comment]
This isn't related to 965.

This is related to conceptual details missing in the lesson on how to run the recommended commands and is not related to the missing module. 

The missing module is for the project notebook.

**Comment by domluna** [comment]
@sahiljuneja I updated `Freezing Graphs` concept with more instructions/details. Let me know if something is still unclear. 

There's an issue in copy and pasting the command where the last line is cutoff. I don't know why that is, might just be me.

**Comment by baumanab** [comment]
Closed as not actionable without further information.
