### ISSUE TITLE
T3, L11 and Project Semantic Segmentation

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#964]
How does the inference lesson related to the Project?

So is that something we don't have to focus on for this project since rubrics don't point that out? Does it impact us or benefit us if we do or don't use what we learn in this lesson? Will that affect reviews?

Is the lesson useful later for system integration?

**Comment by baumanab** [comment]
These are great questions the answers to which other students will likely benefit from.  The most effective way to resolve these questions is likely to post on the forums.  Would you mind posting these questions to the forums?  I'm closing this out for now, but please feel free to amend with a relevant forum thread or another follow-up.

**Comment by sahiljuneja** [comment]
Sorry, but that entire section/lesson is quite unrelated to the project right now and adding this to the forums won't help anyone as it would lead to a discussion that will be forgotten over time. It's a very good piece of content and is something that students could benefit from if it was related to the project somehow. Because they would be able to then directly use/implement some of that.

That's why I recommended in another waffle that there should be a better structure to this lesson so that students get more hands-on experience. This could be an important concept many could benefit from and stands out when applying for jobs because this isn't something many learn on their own. Even if it's something you can't relate to the project right away, the lesson itself could use some more details with a mini-project of sorts if possible.

Students benefit more with additions/improvements to the lesson in the classroom. I, myself, haven't checked the forums in over 2 months so can't attest to their effectiveness for all students across cohorts :)

**Comment by baumanab** [comment]
Thank you for clarifying.  I'm not able to re-open the issue (I didn't realize this when I closed it).  I'll re-open under a different number and make sure you are pinged when that occurs.
