### ISSUE TITLE
T3 - ADL AWS AMI missing module

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#965]
When running the first cell of the notebook, get the following error -

`ModuleNotFoundError: No module named 'tqdm'`

This fixes it https://anaconda.org/anaconda/tqdm

**Comment by baumanab** [comment]
Thank you for letting us know. I'll put a general note in for how to handle missing modules.

**Comment by baumanab** [comment]
Thank you for this information, I have added some notes to the AWS GPU page.
