### ISSUE TITLE
T3, Semantic Segmentation Project - train_nn() tests

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#966]
After filling out `train_nn()` function, and running the cell, there's neither a "Tests Passed" printout nor an error. Not sure if that's intentional or not. The cell just runs normally.

**Comment by sahiljuneja** [comment]
Okay, so "Tests Passed" gets printed out in the terminal instead of in the notebook (I am working off jupyter notebook right now). Will keep this open in case you guys want to add anything about this in the classroom or not.

**Comment by baumanab** [comment]
This is a good tip and may be worth adding as a project note.  Thank you.

**Comment by baumanab** [comment]
A note has been added.
