### ISSUE TITLE
T3, Semantic Segmentation Project - Submission Requirements

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#968]
It might help to have a bit more clarification on how many images are required from the `runs` folder. Or the size limit or something similar. 

I could hand pick a few that seem to show quite a good performance but there are others which don't result in good segmentation. So it's slightly confusing on what's expected to get the best possible feedback from reviews.

**Comment by baumanab** [comment]
Thank you for the feedback. Submission requirements have been clarified.
