### ISSUE TITLE
Lesson 6. Miniflow / Cost

### ISSUE THREAD

**Issue by GemmaLaraSavill** [udacity/sdc-issue-reports#97]

**Comment by GemmaLaraSavill** [comment]
I think the Equation (5) figure is incorrect:

 C(w,b) = 1/2n SUM ||y(x) - a(x))|| squared

Uneven parenthesis: it is missing the first parenthesis of the squared or the one of the double parenthesis should not be there, after the a(x)

Also I don't understand where the n in 1/2n comes from as I understand that the 1/2 is to cancel out the squared  when we use the derivative, so it should maybe just be 1/2

**Comment by Brok-Bucholtz** [comment]
@GemmaLaraSavill 

I removed the extra ")" from the equation.  The reason for the `n` in `1/2n` is to get the average, where `n` is the number of training examples.  You can read more about [here](http://neuralnetworksanddeeplearning.com/chap2.html)(The cost function is equation 26).  Let me know if you need anything else.
