### ISSUE TITLE
Project: Extended Kalman Filters 1. Intro to Extended Kalman Filter Project

### ISSUE THREAD

**Issue by andrewsdc** [udacity/sdc-issue-reports#970]
Is the link entitled "EKF project Github repository README" correct? I've clicked on it assuming it would take me to the current version of the EKF project repository. Takes me here: https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/tree/project_v2 

Seems like that repository or branch is missing a file called "cmakepatch.txt". How else will the code work in install-mac.sh?

**Comment by baumanab** [comment]
It does look like that branch is missing the patch file.  The master branch is the correct branch.  Would you mind clarifying where you found the link?

**Comment by andrewsdc** [comment]
I'll fix it, no worries.

**Comment by andrewsdc** [comment]
Okay, it is fixed
