### ISSUE TITLE
Suggestion - Environments

### ISSUE THREAD

**Issue by CJL89** [udacity/sdc-issue-reports#971]
Is it possible to tell us on the page where we get the link to the projects or any other assignments that we have to download; to specify which dependencies are needed like Numpy, tqdm, Matplolit, etc. I find myself opening my jupyter, finding out that I'm missing a dependency, closing jupyter and installing the dependency.
I think making a list of what is needed will save time but also will resolve some issues since I sometimes had difficulties installing a dependency like in the 1st project.

**Comment by baumanab** [comment]
Sorry for any frustration.  Most python dependencies should be included with the Anaconda python distribution. Are you using Anaconda?

**Comment by baumanab** [comment]
Closed as not actionable without updated information.
