### ISSUE TITLE
Incorrect value in SDCN T2, L7, S13?

### ISSUE THREAD

**Issue by KenOverholt** [udacity/sdc-issue-reports#973]
Term x sub k in the video of Term 2 Lesson 7, section 13 seems to be incorrect.

**Comment by KenOverholt** [comment]
I can't get a picture to upload here so I'll just post the link to the forms where I described the issue: https://discussions.udacity.com/t/incorrect-value-in-lesson-7-section-13/323573.

**Comment by mvirgo** [comment]
Duplicate of #776
