### ISSUE TITLE
python solution for 4.16 seems incorrect

### ISSUE THREAD

**Issue by olegleyz** [udacity/sdc-issue-reports#975]
trajectory_for_state doesn't work as expected:
https://discussions.udacity.com/t/path-planning-lecture-4-16/306201/35?u=drivewell

**Comment by baumanab** [comment]
Thank you for letting us know. Would you mind linking to the quiz?

**Comment by baumanab** [comment]
Related to #974

**Comment by baumanab** [comment]
Nevermind I found the quiz :)

**Comment by baumanab** [comment]
Fixe as part of #974
