### ISSUE TITLE
T3 video subtitles contain frequent errors

### ISSUE THREAD

**Issue by jwdunn1** [udacity/sdc-issue-reports#976]
A few examples of misinterpreted words in the subtitles:

L03:05
"into much" should be "in too much"
"offline face" should be "offline phase"

L03:13
"naive based" should be "Naive Bayes"

L04:04
"previous administration" should be "previous demonstration"

L04:15
"clock up" should be "clog up"
"half planner" should be "path planner"

L05:04
"local MIMA" should be "local minima"
"controlling pull" should be "control input"

L05:06
"on the letters." should be "on a lattice."

L05:09
"for discrete A*" should be "per discrete cell"

L05:14
"enough land" should be "an offline"

L05:16
"all ancient" should be "our lane change"

L05:19
"computer showing the efficient layer" should be "computationally efficient later"

L05:20
"are further" should be "of order"

L05:28
no transcript

L05:31
"hybridized style" should be "hybrid a-star"

L14:01
"will be reading" should be "will be leading"

**Comment by domluna** [comment]
Hi @jwdunn1, by video transcript do you mean the subtitles?

**Comment by jwdunn1** [comment]
@domluna Yes, sorry, I mean the subtitles. I watch the videos with the subtitles enabled to better understand the speaker and the content.

**Comment by baumanab** [comment]
# Status

~~L03:05~~
~~"into much" should be "in too much"~~
~~"offline face" should be "offline phase"~~

L03:13
"naive based" should be "Naive Bayes"

L04:04
"previous administration" should be "previous demonstration"

L04:15
"clock up" should be "clog up"
"half planner" should be "path planner"

L05:04
"local MIMA" should be "local minima"
"controlling pull" should be "control input"

L05:06
"on the letters." should be "on a lattice."

L05:09
"for discrete A*" should be "per discrete cell"

L05:14
"enough land" should be "an offline"

L05:16
"all ancient" should be "our lane change"

L05:19
"computer showing the efficient layer" should be "computationally efficient later"

L05:20
"are further" should be "of order"

L05:28
no transcript

L05:31
"hybridized style" should be "hybrid a-star"

L14:01
"will be reading" should be "will be leading"

**Comment by baumanab** [comment]
Thanks for the information.  These have now been corrected.

**Comment by jwdunn1** [comment]
FYI: Also in L05:15 at time mark 0:58, currently reads "And while a style is great at finding" should read "And while A* is great at finding"
