### ISSUE TITLE
T3, Semantic Segmentation Project Feedback

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/sdc-issue-reports#977]
Hey guys just thought of providing some feedback for this project [as a student]

It took me less 2 hours to go over the content related to the project. [So, discounting the inference lesson]

And it took me less than 6 hours I believe to complete the project.

I found it not so challenging, and I would recommend if students could get more out of this project. Because I am not sure currently if it satisfies the condition of being a month long elective. Open to discuss on this, of course :)

**Comment by baumanab** [comment]
Thank you for this feedback.  It's not clear whether or not your experience is typical (there is a range of durations and the estimate is intended to capture the typical experience).  Hopefully, we will have more data on this soon.  In the meantime, would you mind letting us know what, specifically, you suggest changing or adding?
