### ISSUE TITLE
Port the code for "1x1 Convolution Quiz" to a recent Tensorflow version

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#978]
With reference to [Term 3, Lesson 9, Sec. 5](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/595f35e6-b940-400f-afb2-2015319aa640/lessons/e0c6572b-27e6-48f9-a8c2-fbf05f362320/concepts/b7eca993-13e0-433e-b7c3-ad7b8805e018), consider porting the quiz to a recent version of Tensorflow API.

The quiz currently uses an old version of Tensorflow, and I couldn't find the documentation for `tf.layers.dense()` that uses a parameter `weights_initializer`. At the very least, explain what the call to `tf.layers.dense()` is supposed to do. Even better, adopt a recent version of Tensorflow: this content was published on 26-Jul with a Tensorflow API obsolete already.

With TF 1.2, I believe calls to `tf.layer` become:
`return tf.layers.conv2d(x, num_outputs, kernel_size, stride, kernel_initializer=custom_init)`
and
`dense_out = tf.layers.dense(x, num_outputs, kernel_initializer=custom_init)`

**Comment by baumanab** [comment]
Thank you for letting us know about this.  This is being closed out since upcoming changes to the classroom should resolve this issue.
