### ISSUE TITLE
Explain what "transposed convolutions" are

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#979]
With reference to [Term 3, Lesson 9, Sec. 7](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/595f35e6-b940-400f-afb2-2015319aa640/lessons/e0c6572b-27e6-48f9-a8c2-fbf05f362320/concepts/0f1e23c0-b932-4abb-b78b-70a9e5fdf89d), please provide an explanation of what "transposed convolutions" are; teach us what they are.

The instructor just glosses over it saying "a reverse convolution in which the forward and the backward passes are swapped", which is a truth, but doesn't explain a thing.

This contrasts with the effort done in Term 1 to carefully explain all the key concepts of neural networks and convolution.

You may give a look to [these animations](https://github.com/vdumoulin/conv_arithmetic)  to incorporate something similar.

**Comment by ksmith6** [comment]
:+1:

**Comment by baumanab** [comment]
Transposed Convolutions sounds like an avant garde music project.  :)  Thanks for pointing this out and for the animations.

**Comment by ashispapu** [comment]
Very rightly said . Better explanation is required for Transposed convolution

**Comment by baumanab** [comment]
Thanks for the feedback on this and apologies for the lag on response.  Do you think a high level explanation of transposing known information onto a sparse matrix, a brief discussion of upsampling/interpolation, and some resources (such as a animations) would be effective?

**Comment by baumanab** [comment]
Additional explanation of transposed convolutions has been added.  I hope it is helpful!
