### ISSUE TITLE
Lesson 6: Neural Networks - Michael Littman incorrectly says "We get a dividing line at 1"

### ISSUE THREAD

**Issue by Deborah-Digges** [udacity/sdc-issue-reports#98]
At 1:01, Michael Littman says "We get a dividing line at 1".
It should actually be "Dividing line at 0"

**Comment by Deborah-Digges** [comment]
This is in the quiz solution

**Comment by dhruvp** [comment]
Fixed. Thank you for bringing it up @deborah-digges!
