### ISSUE TITLE
Behavior Planning Psuedocode

### ISSUE THREAD

**Issue by spgitmonish** [udacity/sdc-issue-reports#980]
The statement which appends the cumulative cost for each state is at the incorrect location

**Comment by spgitmonish** [comment]
![Bug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5812b4fe41a4630e00ca4083/125516c66e82c728ace21e0d46ca819d61cec1b99de6b546a749b2ce6b137f237056fa732686b270bb162f035f5f4eac475a5c16fdeb9539e4e76224d50152a7842f4d7ed43f17a6b9871fbe04bf21834987b0b98d5e8d.png)

Appending cost calculated for each state should be as shown below. 

![Resolve.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5812b4fe41a4630e00ca4083/125516c66e82c728ace21e0d46da91892c8e95accda5fd53b652fa912a5265296b51fb7b29d7ba70e9412a590b5b4afe41585f44fafb8a79a7a42062c80d55b98e30063e937f03a6aa811eb500bf208a4a80b7b48c4ec6ed3d37aa.png)

**Comment by baumanab** [comment]
Good catch.  This was actually in the correct place in the editor but somehow didn't render at the correct level.  This has now been remedied.
