### ISSUE TITLE
Describe and explain the hybrid-A* algorithm

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#981]
With reference to Term 3, Lesson 5, please consider to provide a description of the (complete) hybrid-A* algorithm. That might include the algorithm in pseudo-code; see for instance the third page [of this paper](https://pdfs.semanticscholar.org/6e00/16024b257040db590d2de352556f64f46787.pdf) .
 Prof. Thrun's [video clip](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/db4b83a1-b304-4355-92c7-66e973102079/concepts/f5fb8a42-f27e-4093-88ca-4c0edff49070) slapped in there doesn't do: e.g. he starts updating the state without saying how to choose theta. In fact, from his presentation it looks like you do it for a fixed theta, while you do it multiple times, for different values of theta, and need to explain how you choose them. Then one needs to know ho to update the list of open and the list of closed states. And so on.

**Comment by baumanab** [comment]
We are looking into this.  There may be some existing AIND content that could be re-purposed.

**Comment by baumanab** [comment]
It looks like we don't have content to repurpose so we will likely add some classroom notes to explain the algorithm.  Here is a link that may be useful.  http://blog.habrador.com/2015/11/explaining-hybrid-star-pathfinding.html

**Comment by swwelch** [comment]
I just added a solution for the quiz, but we can still add pseudocode before the quiz as well.

**Comment by baumanab** [comment]
@fantauzzi does this help resolve this issue?

**Comment by swwelch** [comment]
I've also added pseudocode [here](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/27800789-bc8e-4adc-afe0-ec781e82ceae/lessons/db4b83a1-b304-4355-92c7-66e973102079/concepts/9c784953-9ef3-4156-8051-68803fa179cc), so I'll close this issue. Please open another issue if further changes are necessary!
