### ISSUE TITLE
T3, L10.6 IoU Quiz Precision

### ISSUE THREAD

**Issue by ksmith6** [udacity/sdc-issue-reports#983]
I computed the IoU for each class and then averaged them across all classes in Excel to compute the mean IoU.  I provided my answer to 4 significant digits (0.5386), and the quiz rejected my answer.  It only accepted my solution once I provided a fifth significant digit (0.5386*9*)!  I'd recommend opening up the tolerance a bit on submitted solutions to accept answers within 0.001 of the correct answer.

**Comment by baumanab** [comment]
This does seem a bit strict, thanks for pointing that out.

**Comment by baumanab** [comment]
The quiz now completes given 0.5387 which is the correct rounded value from 0.53869.
