### ISSUE TITLE
Term 3 Path Planning Project missing code

### ISSUE THREAD

**Issue by jwdunn1** [udacity/sdc-issue-reports#984]
Section 4 Sensor Fusion, under Changing Lanes: the sentence reads: "The acceleration and jerk part can be solved from linear equations for s and d functions, one example of this is shown in python below." There is no example code listed below that reference.

**Comment by baumanab** [comment]
Thanks for reporting this.  There was a code block here but it was moved for use in a quiz.  The text has been updated to reflect this.
