### ISSUE TITLE
Term3 - Path Planning Project - Bug in function NextWaypoint(...)

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#985]
There is a bug in function NextWaypoint which can cause that a point mapped to Frenet than mapped back to world coordinates is 10m away from the original point.

To reproduce the issue you can find my test code in this: 
https://drive.google.com/open?id=0B_6OcqZbAjLHS0hlU0V5VDZXNHc
It is between "// TEST" and "// END TEST".
In the same file you can see my fix.

(Please, consider that the linked file is based on the beta-testing project, but NextWaypoint remained the same in the final one.)

**Comment by baumanab** [comment]
This has been fixed.  Thank you for your help!
