### ISSUE TITLE
Term3 - Path Planning - Simulator problem

### ISSUE THREAD

**Issue by bartmate** [udacity/sdc-issue-reports#986]
Near waypoint 101 there is a point where the simulator indicates that car is out of lane, though it seems undoubtedly  inside the the lane. (Link to an example image: https://drive.google.com/open?id=0B_6OcqZbAjLHempsZ2poelhfbU0)

Please, consider that the image is not captured by me, but in the beta-testing phase, but the issue is still there...

(Temporary solution that I targeted the car 0.25m left of the center of the lane.)

**Comment by baumanab** [comment]
Thank you for letting us know about this. Is this still an issue with the most recent simulator version?

**Comment by baumanab** [comment]
Issue closed as not actionable without updated information.

**Comment by baumanab** [comment]
Note also that the this was investigated and we were unable to replicate the error.  We can open this back up with more detail on replicating the error, though it seems like it may not be an issue with the most recent simulator version.
