### ISSUE TITLE
Describe the FCN-8 network model, and how it connects to your pre-trained VGG16

### ISSUE THREAD

**Issue by fantauzzi** [udacity/sdc-issue-reports#987]
With reference to Term 3, [Lesson 10](https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/595f35e6-b940-400f-afb2-2015319aa640/lessons/69fe4a9c-656e-46c8-bc32-aee9e60b8984/concepts/c9cbe9d0-22c1-4362-bdaa-282a124ca852) .

Please consider providing a description of the FCN-8 model, like you did for Lenet in Term 1 [Lesson 8](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/601ae704-1035-4287-8b11-e2c2716217ad/concepts/63741833610923) and for other networks in [Lesson 11](https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/e12c47b6-316e-4a0b-aae5-2f2c5fcd99f5/concepts/eb3b073d-75cb-4a44-b21f-f8df52379a73).

And very important, how it connects to VGG16. 

For the project, you provide a pre-trained VG166 with a few named layers: 'image_input:0', 'keep_prob:0', 'layer3_out:0', 'layer4_out:0', 'layer7_out:0'. How do those layers map to VGG16 and and FCN-8? Of course you can say that only after you have described FCN-8.

**Comment by baumanab** [comment]
Thank you for reporting this.  The classroom and Github README have been updated to clarify aspects of the model and project.
