### ISSUE TITLE
Term1 - Behavioral Cloning - lecture 10

### ISSUE THREAD

**Issue by aman-ahluwalia** [udacity/sdc-issue-reports#988]
Lenet model shown in the video takes in the filter number as 6 for the second convolution layer, but according to traditional lenet architecture it should be 16 i suppose.

**Comment by baumanab** [comment]
Thanks for the feedback.  This is actually the original Lenet architecture and it follows this pattern:

input --> (6 conv) -->(6 subsample layer) --> (16 conv) --> (16 subsample) --> fully connected layers --> output 

This is essentially the same as modern Lenet except subsampling layers are replaced by pooling layers.
