### ISSUE TITLE
Painful Spelling Errors in Term 3 Functional Safety Module

### ISSUE THREAD

**Issue by schrezraoeder** [udacity/sdc-issue-reports#989]
There are numerous spelling errors and similar basic English errors in the Term 3 Functional Safety Elective module. Here are a few of them.

**Comment by schrezraoeder** [comment]
In Lesson 17: Functional Safety Concept, in sub-section 2: Functional Safety Analysis, it says "land departure warning" and then later it says "Formerly, the malfunctions would be". What was meant was "lane departure warning" and "formally, the malfunctions would be". I've seen these issues numerous times and thought they would have disappeared by now, but they haven't so I'm adding this issue on here, even though it is low priority b/c it is not a technical issue & probably the overwhelming vast majority of English-as-a-first-language speakers easily figure out what is meant while going through this lesson (it is just annoying).

**Comment by baumanab** [comment]
Thanks for letting us know about this.  The text has been updated.
