### ISSUE TITLE
Printing from python causes error

### ISSUE THREAD

**Issue by gilcarmel** [udacity/sdc-issue-reports#99]
When I print debugging info from miniflow.py, it causes my submission to fail even if the code is correct.  E.g. try submitting the exercise with this code inside Linear.forward:
        values = [v.value for v in self.inbound_neurons]
        weights = [w.value for w in self.weights]
        print weights
        self.value = numpy.dot(values, weights) + self.bias.value

The submission works without the print, but fails with it.

URL: 
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/7751ab37-b759-49df-858b-f5498d4b006a/concepts/9e2d2437-fa21-4e74-9f95-081298d7f55a#

**Comment by Brok-Bucholtz** [comment]
@gilcarmel 

Miniflow is used during the unit tests.  Adding a print statement will cause the tests to fail.  I recommend using the print statement with "Test Run".  Test Run doesn't run the unit tests, which are causing you the problems.
