### ISSUE TITLE
Term3 - Semantic Segmentation - Attach log file

### ISSUE THREAD

**Issue by sksq96** [udacity/sdc-issue-reports#991]
For Semantic Segmentation, the student submit their code along with output images.

But we (the reviewers), have no idea what was loss decrease curve and what was the final loss.

Is it possible, the students are asked to submit this `log file` along with the code, so the reviewer knows at time of training, how did the model perform ?

Some students actually go ahead and submit this `log file` of training loss along with the project, but it’s no hard requirement.

**Comment by mvirgo** [comment]
Hi there! With Waffle closing its doors next month, and the ability to leave more detailed feedback on each classroom page (see “Send Feedback” in the upper right if you are enrolled in the program), we are migrating away from our Waffle board. All issues and conversations here will be migrated onto our internal platforms. 

Over the next week, I am leaving these notes in case anyone has further follow-ups they want to get in before the board closes, as well as migrating over the tickets. As of 4/19, I will close all the remaining open tickets, and archive the related Github repository.
