### ISSUE TITLE
Forum Links Gone

### ISSUE THREAD

**Issue by LosFuegos** [udacity/sdc-issue-reports#992]

**Comment by LosFuegos** [comment]
https://discussions.udacity.com/c/nd013-term2-sensor-fusion

**Comment by LosFuegos** [comment]
Also, Can't find Term2 links in the forum.

**Comment by baumanab** [comment]
Sorry for any frustration.  These links are working for my account.  This may be an intermittent or local issue.  Would you mind checking again?  Please contact selfdrivingcar-support@udacity.com if the forum links are still missing.
