### ISSUE TITLE
Term 2 Simulator Generating Gigantic Logs

### ISSUE THREAD

**Issue by farhanhubble** [udacity/sdc-issue-reports#994]
I installed term 2 simulator and played with it for some time, then left it running. It wasn't connected to a Kalman Filter, just sitting idle. After 6-7 hours I noticed that my /home directory with about 200GB of data was filled by the Player.log file created by the simulator.

More details in the form of screenshots are here:
https://imgur.com/gallery/iufdD

**Comment by scherererer** [comment]
I had the same issue. Worked around the issue by creating an empty file and removing write permissions on it so the simulator couldn't log to it.

**Comment by baumanab** [comment]
Thank you for letting us know about this and for coming up with a clever workaround.  I'm going to add a note about this in the project instructions.

**Comment by baumanab** [comment]
A note has been added to the EKF project instructions and repo.
