### ISSUE TITLE
T1 Introduction to Tensorflow Quiz: Mini-batch

### ISSUE THREAD

**Issue by ivan-ushakov** [udacity/sdc-issue-reports#995]
> Use the parameters below, how many batches are there, and what is the last batch size?
> features is (50000, 400)
> labels is (50000, 10)
> batch_size is 128

For some reason 390 was marked Wrong for question "How many batches are there?" but 80 was marked Correct for question "What is the last batch size?".

Why?

**Comment by ivan-ushakov** [comment]
Please delete this issue.

**Comment by AhmedElSayed3210** [comment]
features is (50000, 400)
batch_size = 128

50000 / 128 = 390.625

num_batches = 391
last\_batch_size = 80
